<a href="https://colab.research.google.com/github/miguelpsmedeiros/lab-numpy/blob/master/LAB_NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#1

import numpy as np

In [ ]:
#2

print(np.__version__)

1.19.5


In [ ]:
#3 Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable a

#3.1

a = np.random.random((2,3,5))

print(a)

[[[0.17452157 0.7445674  0.95007834 0.25625986 0.78567271]
  [0.02060103 0.68590028 0.90674172 0.0875461  0.09990955]
  [0.76434896 0.69498252 0.32449504 0.00742818 0.48711646]]

 [[0.54509895 0.48440537 0.527184   0.51053503 0.10151724]
  [0.63128139 0.45206569 0.77878406 0.66678229 0.32004756]
  [0.4789057  0.6579435  0.84772085 0.0227161  0.61869243]]]


In [ ]:
#3 Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable a

#3.2

a = np.random.randint(90,100, size=(2,3,5))

print(a)

[[[98 94 95 94 90]
  [95 93 97 92 99]
  [93 95 93 95 94]]

 [[97 99 97 92 90]
  [91 97 99 90 90]
  [98 91 95 99 97]]]


In [ ]:
#3 Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable a

#3.3

a = np.random.choice(10, size = (2,3,5))

print(a)

[[[3 3 6 6 0]
  [2 1 8 0 9]
  [5 2 3 6 6]]

 [[3 9 9 6 0]
  [3 9 9 4 8]
  [0 9 0 9 7]]]


In [ ]:
#4 Print a

print(a)

[[[3 3 6 6 0]
  [2 1 8 0 9]
  [5 2 3 6 6]]

 [[3 9 9 6 0]
  [3 9 9 4 8]
  [0 9 0 9 7]]]


In [ ]:
#5 and #6 Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable b

b = np.ones(shape = (5,2,3), dtype=int)

print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


In [ ]:
#7 Do a and b have the same size? How do you prove that in Python code?

z = np.size(a) - np.size(b)

if z == 0:
  print("a and b are the same size")
else:
    print("a and b are not the same size")


a and b are the same size


In [ ]:
#8 Are you able to add a and b? Why or why not?

#they have different sizes so you can not add them

In [ ]:
#9 Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to variable c

c = b.reshape((2,3,5))

print(c)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [ ]:
#10 Try to add a and c. Now it should work. Assign the sum to variable d. But why does it work now?

d = a + c

print(d)

#they have the same structure

[[[ 4  4  7  7  1]
  [ 3  2  9  1 10]
  [ 6  3  4  7  7]]

 [[ 4 10 10  7  1]
  [ 4 10 10  5  9]
  [ 1 10  1 10  8]]]


In [ ]:
#11 Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

print(a)

print(d)

#when you add/subtract arrays this operations occurs between the same positions in the different arrays. the first value in array a will be added to first value in array b...

[[[3 3 6 6 0]
  [2 1 8 0 9]
  [5 2 3 6 6]]

 [[3 9 9 6 0]
  [3 9 9 4 8]
  [0 9 0 9 7]]]
[[[ 4  4  7  7  1]
  [ 3  2  9  1 10]
  [ 6  3  4  7  7]]

 [[ 4 10 10  7  1]
  [ 4 10 10  5  9]
  [ 1 10  1 10  8]]]


In [ ]:
#12 Multiply a and c. Assign the result to e

e = a*c

print(e)

[[[3 3 6 6 0]
  [2 1 8 0 9]
  [5 2 3 6 6]]

 [[3 9 9 6 0]
  [3 9 9 4 8]
  [0 9 0 9 7]]]


In [ ]:
#13 Does e equal to a? Why or why not?

#yes because each value was multiplied by one so the reamin the same

In [ ]:
#14 Identify the max, min, and mean values in d. Assign those values to variables d_max, d_min and d_mean

d_max = d.max()

d_min = d.min()

d_mean = d.mean()

print(d_max)
print(d_min)
print(d_mean)

10
1
5.833333333333333


In [ ]:
#15 Now we want to label the values in d. First create an empty array f with the same shape (i.e. 2x3x5) as d using np.empty.

f = np.empty(shape = (2,3,5), dtype = int, order = 'C') 


In [ ]:
#16 and #17 For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f. 
# If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f. 
# If a value equals to d_mean, assign 50 to the corresponding value in f. 
# Assign 0 to the corresponding value(s) in f for d_min in d. 
# Assign 100 to the corresponding value(s) in f for d_max in d. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

for v1 in range(0,2):
  for v2 in range(0,3):
    for v3 in range(0,5):
      if d[v1,v2,v3] > d_min and d[v1,v2,v3] < d_mean:
        f[v1,v2,v3] = 25
      elif d[v1,v2,v3] > d_mean and d[v1,v2,v3] < d_max:
        f[v1,v2,v3] = 75
      elif d[v1,v2,v3] == d_min:
        f[v1,v2,v3] = 0
      elif d[v1,v2,v3] == d_max:
        f[v1,v2,v3] = 100

print(f)
print(d)

#Yes I have the expected f

[[[ 25  25  75  75   0]
  [ 25  25  75   0 100]
  [ 75  25  25  75  75]]

 [[ 25 100 100  75   0]
  [ 25 100 100  25  75]
  [  0 100   0 100  75]]]
[[[ 4  4  7  7  1]
  [ 3  2  9  1 10]
  [ 6  3  4  7  7]]

 [[ 4 10 10  7  1]
  [ 4 10 10  5  9]
  [ 1 10  1 10  8]]]


In [ ]:
#18 Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values ("A", "B", "C", "D", and "E") to label the array elements. For the example above

f = np.empty(shape = (2,3,5), dtype = str, order = 'C') 

for v1 in range(0,2):
  for v2 in range(0,3):
    for v3 in range(0,5):
      if d[v1,v2,v3] > d_min and d[v1,v2,v3] < d_mean:
        f[v1,v2,v3] = "B"
      elif d[v1,v2,v3] > d_mean and d[v1,v2,v3] < d_max:
        f[v1,v2,v3] = "D"
      elif d[v1,v2,v3] == d_min:
        f[v1,v2,v3] = "A"
      elif d[v1,v2,v3] == d_max:
        f[v1,v2,v3] = "E"

print(f)
print(d)

[[['B' 'B' 'D' 'D' 'A']
  ['B' 'B' 'D' 'A' 'E']
  ['D' 'B' 'B' 'D' 'D']]

 [['B' 'E' 'E' 'D' 'A']
  ['B' 'E' 'E' 'B' 'D']
  ['A' 'E' 'A' 'E' 'D']]]
[[[ 4  4  7  7  1]
  [ 3  2  9  1 10]
  [ 6  3  4  7  7]]

 [[ 4 10 10  7  1]
  [ 4 10 10  5  9]
  [ 1 10  1 10  8]]]
