# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np


#### 2. Print your NumPy version.

In [2]:
# your code here
import numpy as np
# to print my np version
print(np.__version__)

1.17.3


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1 to generate a random array

a = np.random.random((2,3,5))
print(a)



[[[0.40967725 0.33731351 0.73823716 0.25724007 0.87100101]
  [0.12013084 0.93074161 0.71575614 0.51513719 0.35194305]
  [0.42980534 0.74058969 0.24918823 0.32057922 0.98727991]]

 [[0.08414193 0.89094069 0.02099019 0.65190623 0.78486955]
  [0.54202807 0.89501742 0.05939499 0.58580898 0.09424214]
  [0.43487098 0.27578342 0.66400102 0.03972802 0.15269152]]]


In [4]:
# Method 2

np.random.normal(size=100)

print(np.random.normal(size=100))

[-0.43019467  0.94966932  0.43760706  0.00836692 -1.81386021  0.14873168
  0.5887611   0.14841504  0.97024746 -0.09041173  0.16612375 -0.1534672
 -0.06290481  0.44998117 -0.40996068 -0.43240292 -1.01433831  0.42643218
 -1.35626161  0.29943447  0.18679955 -0.57766528 -1.02581519  0.46285485
  0.57874059  1.53054663 -0.88368186  0.06453373  0.15299996  0.57640151
 -1.93073913  0.09044838 -0.54315448 -0.75674232  0.16712867  0.66698477
  1.02675902  0.04812642 -0.14362566 -1.48403809  0.14329731 -0.19299869
 -0.65637602 -0.74698726  0.25816098  0.72959931 -0.97993805 -1.01282355
  1.40844393  0.58598431 -0.16976157  0.42540558 -1.02482576 -0.37601573
 -0.82740428 -0.14458066 -1.46285581  0.8402367  -0.70723952 -0.99488231
 -0.38455879 -0.2308962  -0.1735277  -1.75222096  1.00280048 -0.17013123
 -1.3067873  -1.74495523  2.32111219  0.15942922 -0.72146222  0.06053052
  0.36080759 -0.18430137  0.12646051 -0.57928588 -0.82348347 -0.65428189
 -1.49281693  1.09936644  1.11317616  0.67896573  1.

In [5]:
# Method 3
# generating 100 random numbers
np.random.uniform(size=100)

print(np.random.uniform(size = 100))

[0.03891927 0.24601736 0.4639097  0.45331017 0.05361654 0.03403621
 0.71541319 0.72004598 0.8858859  0.66018028 0.28908403 0.43132288
 0.95953322 0.2013963  0.03254777 0.27706743 0.28792951 0.34752469
 0.50116992 0.93520663 0.52053923 0.46468622 0.40850064 0.56515891
 0.10647006 0.62120411 0.38926938 0.3516033  0.02547155 0.56295935
 0.81491351 0.82382371 0.23726149 0.21667098 0.24798565 0.01187486
 0.40835625 0.95675175 0.45055002 0.66205941 0.35847374 0.57838176
 0.33154146 0.50092241 0.98471624 0.43781684 0.76723018 0.95127791
 0.20590198 0.56690147 0.01569381 0.01768582 0.57554478 0.81337784
 0.23939463 0.19303234 0.81979889 0.74437733 0.07874734 0.32693532
 0.68481592 0.11912238 0.25455658 0.61358037 0.06656338 0.50810294
 0.16750831 0.8241741  0.07631453 0.32916377 0.33119668 0.17984146
 0.82872372 0.47813949 0.33187313 0.93691751 0.66044726 0.86104943
 0.42607853 0.57268643 0.99436989 0.80502507 0.40166995 0.72656378
 0.88502313 0.65119311 0.65689938 0.49085686 0.18730964 0.6327

#### 4. Print *a*.


In [6]:
# your code here

a = np.random.random((2,3,5))
print(a)

[[[0.7806438  0.62090637 0.07218221 0.42612776 0.17251172]
  [0.03548096 0.8276122  0.43703142 0.009544   0.83764534]
  [0.77778644 0.14692062 0.19670214 0.61452097 0.53764586]]

 [[0.109715   0.95749109 0.28244057 0.59434882 0.05894705]
  [0.80855971 0.41227853 0.08839055 0.80994422 0.64550988]
  [0.97637958 0.42456065 0.73217111 0.62906419 0.80328208]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here

#5x2x3 3-dimensional array with all values equaling 1.
import numpy as np

b = np.ones((5,2,3))

#### 6. Print *b*.


In [8]:
# your code here
import numpy as np

b = np.ones((5,2,3))
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here

# a and b don´t have the same size. This can be proven by:
np.all(a == b)

print(np.all(a==b))

False


/usr/local/Cellar/ipython/7.8.0/libexec/vendor/lib/python3.7/site-packages/ipykernel_launcher.py:4: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  after removing the cwd from sys.path.
/usr/local/Cellar/ipython/7.8.0/libexec/vendor/lib/python3.7/site-packages/ipykernel_launcher.py:6: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  


#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here
# a and b can´t be added because they don´t have the same size.
print(np.add(a, b))

# this is giving the following answer: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [13]:
# your code here
# b was (5,2,3). I want the first axis (= axis(0)) as the columns, axis (1) as the tables and axis (2) as the rows, so:
c = np.transpose(b)
print(c)


[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [14]:
# your code here
# b was (5,2,3). I want the first axis (= axis(0)) as the columns, axis (1) as the tables and axis (2) as the rows, so:
c = np.transpose(b, (1, 2, 0))
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [15]:
# your code/answer here

#adding a and c

d = np.add(a, c)
print(d)

[[[1.7806438  1.62090637 1.07218221 1.42612776 1.17251172]
  [1.03548096 1.8276122  1.43703142 1.009544   1.83764534]
  [1.77778644 1.14692062 1.19670214 1.61452097 1.53764586]]

 [[1.109715   1.95749109 1.28244057 1.59434882 1.05894705]
  [1.80855971 1.41227853 1.08839055 1.80994422 1.64550988]
  [1.97637958 1.42456065 1.73217111 1.62906419 1.80328208]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [16]:
# your code/answer here

#printing a
print(a)

#adding a and c
print(d)

# The difference is because d is array a + 1 (which is c)

[[[0.7806438  0.62090637 0.07218221 0.42612776 0.17251172]
  [0.03548096 0.8276122  0.43703142 0.009544   0.83764534]
  [0.77778644 0.14692062 0.19670214 0.61452097 0.53764586]]

 [[0.109715   0.95749109 0.28244057 0.59434882 0.05894705]
  [0.80855971 0.41227853 0.08839055 0.80994422 0.64550988]
  [0.97637958 0.42456065 0.73217111 0.62906419 0.80328208]]]
[[[1.7806438  1.62090637 1.07218221 1.42612776 1.17251172]
  [1.03548096 1.8276122  1.43703142 1.009544   1.83764534]
  [1.77778644 1.14692062 1.19670214 1.61452097 1.53764586]]

 [[1.109715   1.95749109 1.28244057 1.59434882 1.05894705]
  [1.80855971 1.41227853 1.08839055 1.80994422 1.64550988]
  [1.97637958 1.42456065 1.73217111 1.62906419 1.80328208]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [17]:
# your code here
# multiplying a and c
e = print(np.multiply(a, c))

[[[0.7806438  0.62090637 0.07218221 0.42612776 0.17251172]
  [0.03548096 0.8276122  0.43703142 0.009544   0.83764534]
  [0.77778644 0.14692062 0.19670214 0.61452097 0.53764586]]

 [[0.109715   0.95749109 0.28244057 0.59434882 0.05894705]
  [0.80855971 0.41227853 0.08839055 0.80994422 0.64550988]
  [0.97637958 0.42456065 0.73217111 0.62906419 0.80328208]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [ ]:
# your code/answer here
# Yes, e and a are the same, because e is a multiplied by 1 (c is an array of ones)

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [20]:
# your code here

#max
d_max = np.max(d)
print(d_max)

#min
d_min = np.min(d)
print(d_min)

#mean
d_mean = np.mean(d)
print (d_mean)

1.976379577450496
1.0095440049344377
1.4942114943889753


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [18]:
# your code here
f = np.empty((2,3,5))
print(f)

[[[0.7806438  0.62090637 0.07218221 0.42612776 0.17251172]
  [0.03548096 0.8276122  0.43703142 0.009544   0.83764534]
  [0.77778644 0.14692062 0.19670214 0.61452097 0.53764586]]

 [[0.109715   0.95749109 0.28244057 0.59434882 0.05894705]
  [0.80855971 0.41227853 0.08839055 0.80994422 0.64550988]
  [0.97637958 0.42456065 0.73217111 0.62906419 0.80328208]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [22]:
# your code here

f[(d > d_min) & (d < d_mean)] = 25
f[(d > d_mean) & (d < d_max)] = 75
f[(d == d_mean)] = 50
f[(d == d_min)] = 0
f[(d == d_max)] = 100

print(f)
    

[[[ 75.  75.  25.  25.  25.]
  [ 25.  75.  25.   0.  75.]
  [ 75.  25.  25.  75.  75.]]

 [[ 25.  75.  25.  75.  25.]
  [ 75.  25.  25.  75.  75.]
  [100.  25.  75.  75.  75.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here
#printing d
print(d)

#printing f
print(f)

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here