# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.version.version)

1.18.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1 Random over normal distribution, mean 0.5
a = np.random.random((2,3,5))
print (a)

[[[0.41280309 0.27127039 0.57015228 0.73253031 0.9496312 ]
  [0.2808374  0.11167555 0.97669705 0.94867705 0.69607613]
  [0.40659399 0.77238189 0.70818385 0.5112713  0.42393109]]

 [[0.73186673 0.27935034 0.70759707 0.70631987 0.45859849]
  [0.18887342 0.3973089  0.85608531 0.45454882 0.99460483]
  [0.78559129 0.77253656 0.28891967 0.43922565 0.67561542]]]


In [4]:
# Method 2 Random over normal distribution, mean 0.5
x = np.random.rand(2,3,5)
print(x)

[[[0.07132055 0.72838759 0.45128954 0.89375574 0.00618644]
  [0.62338017 0.58570609 0.79912446 0.61406039 0.44528666]
  [0.4957169  0.82391513 0.52827404 0.74991225 0.59339779]]

 [[0.45077103 0.21264462 0.60222126 0.56408085 0.87654399]
  [0.77970084 0.14907392 0.40586761 0.57386528 0.82265597]
  [0.69729405 0.74242595 0.35989005 0.26626017 0.30806531]]]


In [5]:
# Method 3 Random over normal distribution, mean 0
z = np.random.randn(2,3,5)
print(z)

[[[-2.23859306  0.33138983 -0.25318781 -1.29328172  0.24817145]
  [ 0.97585316  0.95687608  0.10318638  0.82489246  0.92146522]
  [-0.38902489 -0.15181345  1.35996484 -0.29835353 -0.67043463]]

 [[-0.58912338 -0.55247746  0.50974991 -0.14754938  0.80776635]
  [ 0.12919442  0.32644087 -0.03859804  0.18779734  0.15689518]
  [ 1.15099581 -2.18367053 -0.07912842 -0.9268165   0.93505989]]]


#### 4. Print *a*.


In [6]:
# your code here
print(a)

[[[0.41280309 0.27127039 0.57015228 0.73253031 0.9496312 ]
  [0.2808374  0.11167555 0.97669705 0.94867705 0.69607613]
  [0.40659399 0.77238189 0.70818385 0.5112713  0.42393109]]

 [[0.73186673 0.27935034 0.70759707 0.70631987 0.45859849]
  [0.18887342 0.3973089  0.85608531 0.45454882 0.99460483]
  [0.78559129 0.77253656 0.28891967 0.43922565 0.67561542]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [8]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [9]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [10]:
# your code here
print(a.shape)
print(b.shape)

print(a.size)
print(b.size)

(2, 3, 5)
(5, 2, 3)
30
30


#### 8. Are you able to add *a* and *b*? Why or why not?


In [11]:
# your answer here
print(np.add(a,b))

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [12]:
# your code here
c = np.transpose(b, (1,2,0))
c.shape

(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [13]:
# your code/answer here
d = np.add(a,c)
print(d)

[[[1.41280309 1.27127039 1.57015228 1.73253031 1.9496312 ]
  [1.2808374  1.11167555 1.97669705 1.94867705 1.69607613]
  [1.40659399 1.77238189 1.70818385 1.5112713  1.42393109]]

 [[1.73186673 1.27935034 1.70759707 1.70631987 1.45859849]
  [1.18887342 1.3973089  1.85608531 1.45454882 1.99460483]
  [1.78559129 1.77253656 1.28891967 1.43922565 1.67561542]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [14]:
# your code/answer here
print(a)
print(d)

[[[0.41280309 0.27127039 0.57015228 0.73253031 0.9496312 ]
  [0.2808374  0.11167555 0.97669705 0.94867705 0.69607613]
  [0.40659399 0.77238189 0.70818385 0.5112713  0.42393109]]

 [[0.73186673 0.27935034 0.70759707 0.70631987 0.45859849]
  [0.18887342 0.3973089  0.85608531 0.45454882 0.99460483]
  [0.78559129 0.77253656 0.28891967 0.43922565 0.67561542]]]
[[[1.41280309 1.27127039 1.57015228 1.73253031 1.9496312 ]
  [1.2808374  1.11167555 1.97669705 1.94867705 1.69607613]
  [1.40659399 1.77238189 1.70818385 1.5112713  1.42393109]]

 [[1.73186673 1.27935034 1.70759707 1.70631987 1.45859849]
  [1.18887342 1.3973089  1.85608531 1.45454882 1.99460483]
  [1.78559129 1.77253656 1.28891967 1.43922565 1.67561542]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [15]:
# your code here
e = np.multiply(a,c)
print(e)

[[[0.41280309 0.27127039 0.57015228 0.73253031 0.9496312 ]
  [0.2808374  0.11167555 0.97669705 0.94867705 0.69607613]
  [0.40659399 0.77238189 0.70818385 0.5112713  0.42393109]]

 [[0.73186673 0.27935034 0.70759707 0.70631987 0.45859849]
  [0.18887342 0.3973089  0.85608531 0.45454882 0.99460483]
  [0.78559129 0.77253656 0.28891967 0.43922565 0.67561542]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [16]:
# your code/answer here
print(a-e)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [17]:
a==e

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [18]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(d_max)
print(d_min)
print(d_mean)

1.994604828082027
1.1116755452534717
1.5836584977930772


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [20]:
# your code here
z = np.empty((2,3,5))
print(z)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [28]:
# your code here
list_array = []
for element in d:
    for subelement in element:
        for i in subelement:
            if d_min < i < d_mean:
                list_array.append(25)
            elif d_mean < i < d_max:
                list_array.append(75)
            elif i == d_mean:
                list_array.append(50)
            elif i == d_min:
                list_array.append(0)
            else:
                list_array.append(100)
print(list_array)

[25, 25, 25, 75, 75, 25, 0, 75, 75, 75, 25, 75, 75, 25, 25, 75, 25, 75, 75, 25, 25, 25, 75, 25, 100, 75, 75, 25, 25, 75]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [29]:
# your code here
z2 = np.array(list_array)
print(z2)

[ 25  25  25  75  75  25   0  75  75  75  25  75  75  25  25  75  25  75
  75  25  25  25  75  25 100  75  75  25  25  75]


In [33]:
z2 = np.reshape(z2, (2,3,5))
print(z2)

[[[ 25  25  25  75  75]
  [ 25   0  75  75  75]
  [ 25  75  75  25  25]]

 [[ 75  25  75  75  25]
  [ 25  25  75  25 100]
  [ 75  75  25  25  75]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [37]:
# your code here
list_array2 = []
for element in d:
    for subelement in element:
        for i in subelement:
            if d_min < i < d_mean:
                list_array2.append('A')
            elif d_mean < i < d_max:
                list_array2.append('B')
            elif i == d_mean:
                list_array2.append('C')
            elif i == d_min:
                list_array2.append('D')
            else:
                list_array2.append('E')
print(list_array2)

['A', 'A', 'A', 'B', 'B', 'A', 'D', 'B', 'B', 'B', 'A', 'B', 'B', 'A', 'A', 'B', 'A', 'B', 'B', 'A', 'A', 'A', 'B', 'A', 'E', 'B', 'B', 'A', 'A', 'B']


In [38]:
z3 = np.array(list_array2)
print(z3)

['A' 'A' 'A' 'B' 'B' 'A' 'D' 'B' 'B' 'B' 'A' 'B' 'B' 'A' 'A' 'B' 'A' 'B'
 'B' 'A' 'A' 'A' 'B' 'A' 'E' 'B' 'B' 'A' 'A' 'B']


In [39]:
z3 = np.reshape(z3, (2,3,5))
print(z3)

[[['A' 'A' 'A' 'B' 'B']
  ['A' 'D' 'B' 'B' 'B']
  ['A' 'B' 'B' 'A' 'A']]

 [['B' 'A' 'B' 'B' 'A']
  ['A' 'A' 'B' 'A' 'E']
  ['B' 'B' 'A' 'A' 'B']]]
