# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.__version__)

1.16.4


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a = np.random.random((2,3,5)) 



In [4]:
# Method 2

a2 = np.random.randint(0, 100, size= (2,3,5))
print(a2)

[[[81 38  7 76 11]
  [54 44 34 94 75]
  [42 58 51 32 54]]

 [[67 21 97 86 88]
  [55 43 57 13 98]
  [76 23  3 66 39]]]


In [5]:
# Method 3

a3 = np.random.rand(2,3,5) 

print(a3)

[[[0.16567735 0.59032469 0.04758989 0.78520658 0.61140413]
  [0.32595878 0.62391637 0.15836798 0.91742327 0.31059116]
  [0.69529265 0.26242291 0.94711477 0.56454666 0.94001302]]

 [[0.3550054  0.50452198 0.05508997 0.99801266 0.86796803]
  [0.10150956 0.82529529 0.44374987 0.78538167 0.12206978]
  [0.47743422 0.5876408  0.39201531 0.10740595 0.7429213 ]]]


#### 4. Print *a*.


In [6]:
# your code here

print(a)

[[[0.2323151  0.94244219 0.16239423 0.30761452 0.02782307]
  [0.9190336  0.76260213 0.17143012 0.72046601 0.25121274]
  [0.16275887 0.09184573 0.63787606 0.56209176 0.43184259]]

 [[0.74599393 0.52979008 0.49958207 0.69106435 0.88322764]
  [0.74817801 0.69026896 0.2190979  0.15052492 0.41561501]
  [0.49338216 0.02320358 0.63969609 0.59025624 0.92862648]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here

b = np.ones((5,3,2))  

#### 6. Print *b*.


In [8]:
print(b)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here
## yes while

5*3*2 == 5*2*3

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here
## No, they appear different



#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here

c = np.transpose(b)

print(c)


[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# your code/answer here

d = np.add(a,c)

print(d)

[[[1.2323151  1.94244219 1.16239423 1.30761452 1.02782307]
  [1.9190336  1.76260213 1.17143012 1.72046601 1.25121274]
  [1.16275887 1.09184573 1.63787606 1.56209176 1.43184259]]

 [[1.74599393 1.52979008 1.49958207 1.69106435 1.88322764]
  [1.74817801 1.69026896 1.2190979  1.15052492 1.41561501]
  [1.49338216 1.02320358 1.63969609 1.59025624 1.92862648]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# your code/answer here
print(a)
print(d)

### They are in the same list structure and a+c=d == d+c=a



[[[0.2323151  0.94244219 0.16239423 0.30761452 0.02782307]
  [0.9190336  0.76260213 0.17143012 0.72046601 0.25121274]
  [0.16275887 0.09184573 0.63787606 0.56209176 0.43184259]]

 [[0.74599393 0.52979008 0.49958207 0.69106435 0.88322764]
  [0.74817801 0.69026896 0.2190979  0.15052492 0.41561501]
  [0.49338216 0.02320358 0.63969609 0.59025624 0.92862648]]]
[[[1.2323151  1.94244219 1.16239423 1.30761452 1.02782307]
  [1.9190336  1.76260213 1.17143012 1.72046601 1.25121274]
  [1.16275887 1.09184573 1.63787606 1.56209176 1.43184259]]

 [[1.74599393 1.52979008 1.49958207 1.69106435 1.88322764]
  [1.74817801 1.69026896 1.2190979  1.15052492 1.41561501]
  [1.49338216 1.02320358 1.63969609 1.59025624 1.92862648]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
# your code here
e = np.multiply(a,c)


#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
# your code/answer here
#well the values are simulare in how they look like (while e = a * c, c ==1 so e==a)

e == a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(d_max, d_min, d_mean)


1.9424421936873126 1.0232035769724745 1.4877418716163737


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [23]:
# your code here

f = np.empty((2, 3, 5))

print(f)

[[[ 25. 100.  25.  25.  25.]
  [ 75.  75.  25.  75.  25.]
  [ 25.  25.  75.  75.  25.]]

 [[ 75.  75.  75.  75.  75.]
  [ 75.  75.  25.  25.  25.]
  [ 75.   0.  75.  75.  75.]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [24]:

f[(d > d_min) & (d < d_mean)] = 25
f[(d > d_mean) & (d < d_max)] = 75
f[d == d_mean] = 50
f[d == d_min] = 0
f[d == d_max] = 100

print(f)







[[[ 25. 100.  25.  25.  25.]
  [ 75.  75.  25.  75.  25.]
  [ 25.  25.  75.  75.  25.]]

 [[ 75.  75.  75.  75.  75.]
  [ 75.  75.  25.  25.  25.]
  [ 75.   0.  75.  75.  75.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [25]:
# your code here
## I've expected one 0 and one 100 while there is one min and one max, probably no avarage while the change that something
## is exactly average is neglectable. The rest should be 50/50 amount of 75 and 25=(total-3)/2

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [20]:
# your code here

In [ ]:
print(d_max)
print(d_min)
print(d_mean)

print(d)

f

50   if value == d_mean
0    if value == d_min
100  if value == d_max


#quarters_d = [i for row in a for i in row if i > d_min and < d_mean f = 25 then d = 0
 #             if > d_mean and <d_max f = 75 then d = 0 
  #            if == d_mean f =50 then d = 0 else f = 0
   #          ]  

items = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
for index, item in enumerate(items):
    if not (item % 2):
        items[index] = None
        
items = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]