# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.__version__)

1.16.4


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a = np.random.random((2,3,5)) 

array([[[0.07635849, 0.37992628, 0.78048447, 0.00369564, 0.58021108],
        [0.25739747, 0.69977922, 0.63123324, 0.47761237, 0.51743561],
        [0.05074271, 0.72223753, 0.67709563, 0.42964076, 0.46120944]],

       [[0.50056411, 0.61824196, 0.80521442, 0.18458786, 0.10329633],
        [0.04581551, 0.09530502, 0.03062784, 0.21763526, 0.98265832],
        [0.28400928, 0.47755643, 0.17687907, 0.73599592, 0.89475935]]])

In [6]:
# Method 2

a2 = np.random.randint(0, 100, size=(2,3,5))
print(a2)

[[[12  0 16  5 16]
  [89 95 73 27 75]
  [ 8 70 11 45 23]]

 [[37  7 24 73 58]
  [15 80 70 31  4]
  [24 21 34 14 46]]]


In [8]:
# Method 3

a3 = np.random.rand(2,3,5)

print(a3)

[[[5.91820538e-01 6.38305551e-01 9.42900299e-04 2.14799078e-01
   7.85405497e-02]
  [5.44909175e-02 2.03145212e-01 3.73318468e-02 3.57405089e-01
   9.85997690e-01]
  [6.74412087e-01 7.15419226e-01 5.57866461e-01 1.23397140e-01
   7.86805448e-01]]

 [[9.84573522e-01 2.78863142e-01 4.13551219e-01 8.72023077e-02
   4.28029150e-03]
  [9.46068741e-01 7.06622492e-01 1.04610854e-01 7.70554722e-01
   7.80601348e-01]
  [7.29931971e-01 1.12694126e-01 4.99714750e-01 4.60586954e-01
   3.73649920e-01]]]


#### 4. Print *a*.


In [13]:
# your code here
a = np.random.random((2,3,5)) 
print(a)

[[[0.95504389 0.53194515 0.35502926 0.40683142 0.36086375]
  [0.66789079 0.2673482  0.28754451 0.80836962 0.78303956]
  [0.97532192 0.86779769 0.48012387 0.64909292 0.99091686]]

 [[0.69381954 0.24198633 0.20640763 0.01472532 0.81149399]
  [0.9627587  0.79090847 0.62101764 0.83547861 0.16395638]
  [0.84131612 0.66861298 0.50297726 0.17732189 0.61235728]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [31]:
# your code here

b = np.full((5,2,3), 1)  

#### 6. Print *b*.


In [32]:
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [33]:
# your code here
## yes while

5*2*3 == 5*2*3

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [29]:
# your answer here
## No, they appear different



#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [42]:
# your code here

c = np.transpose(b,(2,3,5))



AxisError: axis 3 is out of bounds for array of dimension 3

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [43]:
# your code/answer here


np.add(a,c)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,3,2) 

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [44]:
# your code/answer here
print(a)
print(d)

### They are in the same list structure and a+c=d == d+c=a



[[[0.95504389 0.53194515 0.35502926 0.40683142 0.36086375]
  [0.66789079 0.2673482  0.28754451 0.80836962 0.78303956]
  [0.97532192 0.86779769 0.48012387 0.64909292 0.99091686]]

 [[0.69381954 0.24198633 0.20640763 0.01472532 0.81149399]
  [0.9627587  0.79090847 0.62101764 0.83547861 0.16395638]
  [0.84131612 0.66861298 0.50297726 0.17732189 0.61235728]]]


NameError: name 'd' is not defined

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [45]:
# your code here
e = np.multiply(a,c)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,3,2) 

#### 13. Does *e* equal to *a*? Why or why not?


In [47]:
# your code/answer here
## no, e = a * c   12 = 3 * 4
##     e / a = c   12 / 3 = 4

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [ ]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [ ]:
# your code here
f = np.empty(2x3x5)

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [1]:
# your code here

quarters_d = [i for row in a for i in row if i > d_min and < d_mean f = 25 then d = 0
              if > d_mean and <d_max f = 75 then d = 0 
              if == d_mean f =50 then d = 0 else f = 0
             ]  



#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here
## probably it is expected when looking at a normal distribution

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here