# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [2]:
print(np.version.version)

1.21.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
a = np.random.random((2,3,5))


In [4]:
# Method 2

In [5]:
# Method 3

#### 4. Print *a*.


In [6]:
a

array([[[0.15157553, 0.78971684, 0.59905964, 0.660239  , 0.27591286],
        [0.5788043 , 0.69322148, 0.96907272, 0.22530605, 0.15076045],
        [0.62498959, 0.0324473 , 0.00605977, 0.35166408, 0.70207995]],

       [[0.51618279, 0.93369007, 0.24402577, 0.32711772, 0.8667912 ],
        [0.42056488, 0.23280145, 0.00642599, 0.29665961, 0.08578379],
        [0.5852012 , 0.46018   , 0.65766033, 0.59506865, 0.75267617]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
b = np.ones((5,2,3))


#### 6. Print *b*.


In [8]:
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
 np.array_equiv(a, b)

False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
#No, because the shape is not the same.
a + b

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
print(a)

[[[0.15157553 0.78971684 0.59905964 0.660239   0.27591286]
  [0.5788043  0.69322148 0.96907272 0.22530605 0.15076045]
  [0.62498959 0.0324473  0.00605977 0.35166408 0.70207995]]

 [[0.51618279 0.93369007 0.24402577 0.32711772 0.8667912 ]
  [0.42056488 0.23280145 0.00642599 0.29665961 0.08578379]
  [0.5852012  0.46018    0.65766033 0.59506865 0.75267617]]]


In [12]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [13]:
c = np.transpose(b).reshape(2,3,5)
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [14]:
#Because now the shape is equal.
d = a + c
d

array([[[1.15157553, 1.78971684, 1.59905964, 1.660239  , 1.27591286],
        [1.5788043 , 1.69322148, 1.96907272, 1.22530605, 1.15076045],
        [1.62498959, 1.0324473 , 1.00605977, 1.35166408, 1.70207995]],

       [[1.51618279, 1.93369007, 1.24402577, 1.32711772, 1.8667912 ],
        [1.42056488, 1.23280145, 1.00642599, 1.29665961, 1.08578379],
        [1.5852012 , 1.46018   , 1.65766033, 1.59506865, 1.75267617]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [15]:
#d is the sum from a + value 1 present on the b array.

In [16]:
print(a)

[[[0.15157553 0.78971684 0.59905964 0.660239   0.27591286]
  [0.5788043  0.69322148 0.96907272 0.22530605 0.15076045]
  [0.62498959 0.0324473  0.00605977 0.35166408 0.70207995]]

 [[0.51618279 0.93369007 0.24402577 0.32711772 0.8667912 ]
  [0.42056488 0.23280145 0.00642599 0.29665961 0.08578379]
  [0.5852012  0.46018    0.65766033 0.59506865 0.75267617]]]


In [17]:
print(d)

[[[1.15157553 1.78971684 1.59905964 1.660239   1.27591286]
  [1.5788043  1.69322148 1.96907272 1.22530605 1.15076045]
  [1.62498959 1.0324473  1.00605977 1.35166408 1.70207995]]

 [[1.51618279 1.93369007 1.24402577 1.32711772 1.8667912 ]
  [1.42056488 1.23280145 1.00642599 1.29665961 1.08578379]
  [1.5852012  1.46018    1.65766033 1.59506865 1.75267617]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [18]:
 e = a * c
e

array([[[0.15157553, 0.78971684, 0.59905964, 0.660239  , 0.27591286],
        [0.5788043 , 0.69322148, 0.96907272, 0.22530605, 0.15076045],
        [0.62498959, 0.0324473 , 0.00605977, 0.35166408, 0.70207995]],

       [[0.51618279, 0.93369007, 0.24402577, 0.32711772, 0.8667912 ],
        [0.42056488, 0.23280145, 0.00642599, 0.29665961, 0.08578379],
        [0.5852012 , 0.46018   , 0.65766033, 0.59506865, 0.75267617]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [19]:
#Equal because it will be the values of a multiplied by one.


e == a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [20]:
d_max = d.max()
d_max

1.969072722287173

In [21]:
d_min = d.min()
d_min

1.0060597746668543

In [22]:
d_mean = d.mean()
d_mean

1.459724639231665

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [23]:
f = np.empty((2,3,5), dtype=int)
f

array([[[-1271987816,         400,          70,           0,
                   0],
        [          0,           0,           0,           0,
                   0],
        [ 1868767867,   975332708,   543564320,  1886265405,
          1886217518]],

       [[  673741172,   741551154,   539765045,  1887007844,
          1852390757],
        [ 1851533684,   539763302,  1702389026,  1769239907,
          1667198575],
        [ 1953396079,   840972834,       32051,           0,
                   0]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [24]:
for i in range(2):
    for j in range(3):
        for k in range(5):
            if d[i,j,k] > d_min and d[i,j,k] < d_mean:
                f[i,j,k] = 25
            elif d[i,j,k] > d_mean and d[i,j,k] < d_max:
                f[i,j,k] = 75
            elif d[i,j,k] == d_mean:
                f[i,j,k] = 50
            elif d[i,j,k] == d_min:
                f[i,j,k] = 0
            elif d[i,j,k] == d_max:
                f[i,j,k] = 100
                
f

array([[[ 25,  75,  75,  75,  25],
        [ 75,  75, 100,  25,  25],
        [ 75,  25,   0,  25,  75]],

       [[ 75,  75,  25,  25,  75],
        [ 25,  25,  25,  25,  25],
        [ 75,  75,  75,  75,  75]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [25]:
f

array([[[ 25,  75,  75,  75,  25],
        [ 75,  75, 100,  25,  25],
        [ 75,  25,   0,  25,  75]],

       [[ 75,  75,  25,  25,  75],
        [ 25,  25,  25,  25,  25],
        [ 75,  75,  75,  75,  75]]])

In [26]:
d

array([[[1.15157553, 1.78971684, 1.59905964, 1.660239  , 1.27591286],
        [1.5788043 , 1.69322148, 1.96907272, 1.22530605, 1.15076045],
        [1.62498959, 1.0324473 , 1.00605977, 1.35166408, 1.70207995]],

       [[1.51618279, 1.93369007, 1.24402577, 1.32711772, 1.8667912 ],
        [1.42056488, 1.23280145, 1.00642599, 1.29665961, 1.08578379],
        [1.5852012 , 1.46018   , 1.65766033, 1.59506865, 1.75267617]]])

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.