# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [38]:
import numpy as np

#### 2. Print your NumPy version.

In [42]:
a = np.version.version
print(a)

1.18.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [68]:
# Method 1

a = np.random.random((2, 3, 5))



In [67]:
# Method 2

a = np.random.rand(2,3, 5)

In [78]:
# Method 3

a = np.random.randint(10, size = (2,3,5));


#### 4. Print *a*.


In [79]:
# your code here
print(a)

[[[0 1 3 2 9]
  [2 4 4 6 4]
  [6 0 8 3 7]]

 [[0 5 6 8 9]
  [7 8 1 6 7]
  [2 0 5 6 2]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [92]:
# your code here
b = np.ones((5,2,3))
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 6. Print *b*.


In [13]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [93]:
# your code here
print(a.size == b.size)

True


#### 8. Are you able to add *a* and *b*? Why or why not?


In [114]:
# your answer here
print(a.shape == b.shape)

np.add(a, b)
#a and b have the same size but not the same shape.

False


ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [113]:
# your code here

print(a.shape, b.shape)
c = np.transpose(b,[1,2,0])
print(c)
print(a.shape, c.shape)


(2, 3, 5) (5, 2, 3)
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
(2, 3, 5) (2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [112]:
# your code/answer here

d = np.add(a,c);
print(d)

#a and c have the same size and the same shape

[[[ 1.  2.  4.  3. 10.]
  [ 3.  5.  5.  7.  5.]
  [ 7.  1.  9.  4.  8.]]

 [[ 1.  6.  7.  9. 10.]
  [ 8.  9.  2.  7.  8.]
  [ 3.  1.  6.  7.  3.]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [119]:
# your code/answer here

print(a)
print(d)


[[[0 1 3 2 9]
  [2 4 4 6 4]
  [6 0 8 3 7]]

 [[0 5 6 8 9]
  [7 8 1 6 7]
  [2 0 5 6 2]]]
[[[ 1.  2.  4.  3. 10.]
  [ 3.  5.  5.  7.  5.]
  [ 7.  1.  9.  4.  8.]]

 [[ 1.  6.  7.  9. 10.]
  [ 8.  9.  2.  7.  8.]
  [ 3.  1.  6.  7.  3.]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [118]:
# your code here

e = np.multiply(a,c)
print(e)

[[[0. 1. 3. 2. 9.]
  [2. 4. 4. 6. 4.]
  [6. 0. 8. 3. 7.]]

 [[0. 5. 6. 8. 9.]
  [7. 8. 1. 6. 7.]
  [2. 0. 5. 6. 2.]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [120]:
# your code/answer here

print(a.size == e.size)


True


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [122]:
# your code here

print(d)
d_max = d.max()
print("MAX: ", d_max)
d_min = d.min()
print("MIN: ", d_min)
d_mean = d.mean()
print("MEAN: ", d_mean)


[[[ 1.  2.  4.  3. 10.]
  [ 3.  5.  5.  7.  5.]
  [ 7.  1.  9.  4.  8.]]

 [[ 1.  6.  7.  9. 10.]
  [ 8.  9.  2.  7.  8.]
  [ 3.  1.  6.  7.  3.]]]
MAX:  10.0
MIN:  1.0
MEAN:  5.366666666666666


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [123]:
# your code here

f = np.empty((2, 3, 5), dtype=np.int8);

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [125]:
# your code here

it = np.nditer(d, flags=['multi_index']);
while not it.finished:
    if it[0] == d_min:
        f[it.multi_index] = 0;
    elif it[0] > d_min and it[0] < d_mean:
        f[it.multi_index] = 25;
    elif it[0] == d_mean:
        f[it.multi_index] = 50;
    elif it[0] > d_mean and it[0] < d_max:
        f[it.multi_index] = 75;
    else:
        f[it.multi_index] = 100;
    it.iternext()


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [126]:
# your code here

print(d)
print(f)

[[[ 1.  2.  4.  3. 10.]
  [ 3.  5.  5.  7.  5.]
  [ 7.  1.  9.  4.  8.]]

 [[ 1.  6.  7.  9. 10.]
  [ 8.  9.  2.  7.  8.]
  [ 3.  1.  6.  7.  3.]]]
[[[  0  25  25  25 100]
  [ 25  25  25  75  25]
  [ 75   0  75  25  75]]

 [[  0  75  75  75 100]
  [ 75  75  25  75  75]
  [ 25   0  75  75  25]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [127]:
# your code here

g = np.empty((2, 3, 5), dtype=str);
it = np.nditer(d, flags=['multi_index']);
while not it.finished:
    if it[0] == d_min:
        g[it.multi_index] = 'A';
    elif it[0] > d_min and it[0] < d_mean:
        g[it.multi_index] = 'B';
    elif it[0] == d_mean:
        g[it.multi_index] = 'C';
    elif it[0] > d_mean and it[0] < d_max:
        g[it.multi_index] = 'D';
    else:
        g[it.multi_index] = 'E';
    it.iternext()
    
print(g)

[[['A' 'B' 'B' 'B' 'E']
  ['B' 'B' 'B' 'D' 'B']
  ['D' 'A' 'D' 'B' 'D']]

 [['A' 'D' 'D' 'D' 'E']
  ['D' 'D' 'B' 'D' 'D']
  ['B' 'A' 'D' 'D' 'B']]]
