# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [25]:
np.version.version

'1.21.5'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [5]:
new_array = np.random.random(size = (2,3,5))
new_array

array([[[0.26347749, 0.07828423, 0.29862839, 0.15366829, 0.67417001],
        [0.34767638, 0.0771898 , 0.74369082, 0.71208482, 0.07304296],
        [0.80166138, 0.51339036, 0.27318251, 0.94149311, 0.2287255 ]],

       [[0.44365861, 0.68199016, 0.31989072, 0.080943  , 0.24966301],
        [0.06577791, 0.62012891, 0.38803027, 0.36833548, 0.65197115],
        [0.46933885, 0.5092976 , 0.91005934, 0.14236737, 0.32877812]]])

In [11]:
new_array2 = np.random.sample(size = (2,3,5))
new_array2

array([[[0.8443671 , 0.37115011, 0.72160647, 0.84061845, 0.68822913],
        [0.14657494, 0.17429454, 0.08657985, 0.76531292, 0.37811503],
        [0.07561252, 0.55756172, 0.70778312, 0.07695481, 0.11313757]],

       [[0.61894859, 0.68908519, 0.42498373, 0.24688767, 0.55114211],
        [0.28343154, 0.64322114, 0.60777954, 0.83844945, 0.10884731],
        [0.65708967, 0.24029868, 0.41412779, 0.56291148, 0.74506422]]])

In [20]:
new_array3 = np.random.randn(2,3,5)
new_array3

array([[[-1.34436793e+00,  8.24952585e-01, -1.03283808e+00,
          2.79800777e-01,  2.25766087e-01],
        [ 1.27668394e-01, -1.40425921e+00,  1.13214400e-01,
         -1.45324159e+00, -5.78822754e-01],
        [-1.54466005e+00,  8.58855420e-02,  8.07042019e-01,
          3.06952146e-04, -7.02806791e-01]],

       [[ 2.45751156e+00, -3.94415283e-01,  2.58248924e-01,
          9.10660843e-01,  8.32247982e-01],
        [-1.21853552e-01, -4.17641844e-01, -1.35387833e+00,
         -1.73496154e+00,  2.78136970e-01],
        [-6.31571207e-01,  1.93843965e+00,  6.69909763e-01,
         -9.45070802e-02, -1.52779907e+00]]])

#### 4. Print *a*.


In [26]:
a = new_array
print(a)

[[[0.26347749 0.07828423 0.29862839 0.15366829 0.67417001]
  [0.34767638 0.0771898  0.74369082 0.71208482 0.07304296]
  [0.80166138 0.51339036 0.27318251 0.94149311 0.2287255 ]]

 [[0.44365861 0.68199016 0.31989072 0.080943   0.24966301]
  [0.06577791 0.62012891 0.38803027 0.36833548 0.65197115]
  [0.46933885 0.5092976  0.91005934 0.14236737 0.32877812]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [27]:
b = np.ones(shape = (5,2,3), dtype = int)

#### 6. Print *b*.


In [28]:
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [29]:
a == b

C:\Users\Matheus Freire\AppData\Local\Temp\ipykernel_7564\160026346.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  a == b


False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [30]:
a + b

# You cannot add them because they don't have the same shape

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [43]:
c = b.transpose()
c

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [45]:
c = c.reshape(2,3,5)
d = a + c
d

array([[[1.26347749, 1.07828423, 1.29862839, 1.15366829, 1.67417001],
        [1.34767638, 1.0771898 , 1.74369082, 1.71208482, 1.07304296],
        [1.80166138, 1.51339036, 1.27318251, 1.94149311, 1.2287255 ]],

       [[1.44365861, 1.68199016, 1.31989072, 1.080943  , 1.24966301],
        [1.06577791, 1.62012891, 1.38803027, 1.36833548, 1.65197115],
        [1.46933885, 1.5092976 , 1.91005934, 1.14236737, 1.32877812]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [36]:
print(a)
print(d)

# they're different because we added variable c to d

[[[0.26347749 0.07828423 0.29862839 0.15366829 0.67417001]
  [0.34767638 0.0771898  0.74369082 0.71208482 0.07304296]
  [0.80166138 0.51339036 0.27318251 0.94149311 0.2287255 ]]

 [[0.44365861 0.68199016 0.31989072 0.080943   0.24966301]
  [0.06577791 0.62012891 0.38803027 0.36833548 0.65197115]
  [0.46933885 0.5092976  0.91005934 0.14236737 0.32877812]]]
[[[1.26347749 1.07828423 1.29862839 1.15366829 1.67417001]
  [1.34767638 1.0771898  1.74369082 1.71208482 1.07304296]
  [1.80166138 1.51339036 1.27318251 1.94149311 1.2287255 ]]

 [[1.44365861 1.68199016 1.31989072 1.080943   1.24966301]
  [1.06577791 1.62012891 1.38803027 1.36833548 1.65197115]
  [1.46933885 1.5092976  1.91005934 1.14236737 1.32877812]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [48]:
e = a * c
e

array([[[0.26347749, 0.07828423, 0.29862839, 0.15366829, 0.67417001],
        [0.34767638, 0.0771898 , 0.74369082, 0.71208482, 0.07304296],
        [0.80166138, 0.51339036, 0.27318251, 0.94149311, 0.2287255 ]],

       [[0.44365861, 0.68199016, 0.31989072, 0.080943  , 0.24966301],
        [0.06577791, 0.62012891, 0.38803027, 0.36833548, 0.65197115],
        [0.46933885, 0.5092976 , 0.91005934, 0.14236737, 0.32877812]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [49]:
e == a

# because they have the same values

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [40]:
d_max = d.max()
d_min = d.min()
d_mean =d.mean()

print(d_max)
print(d_min)
print(d_mean)

1.941493106239979
1.0657779061710917
1.4136865513101253


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [47]:
f = np.empty(shape = (2,3,5))
f

array([[[1.26347749, 1.07828423, 1.29862839, 1.15366829, 1.67417001],
        [1.34767638, 1.0771898 , 1.74369082, 1.71208482, 1.07304296],
        [1.80166138, 1.51339036, 1.27318251, 1.94149311, 1.2287255 ]],

       [[1.44365861, 1.68199016, 1.31989072, 1.080943  , 1.24966301],
        [1.06577791, 1.62012891, 1.38803027, 1.36833548, 1.65197115],
        [1.46933885, 1.5092976 , 1.91005934, 1.14236737, 1.32877812]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here