# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.version.version)

1.17.3


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1

a = np.random.rand(2, 3 ,5)


In [4]:
# Method 2

a = np.random.randint(5, size=(2, 3, 5))


In [5]:
# Method 3

a = np.random.randn(2,3,5)


#### 4. Print *a*.


In [6]:
# your code here
print(a)

[[[ 5.16672934e-01  4.25284156e-01 -1.75756014e+00  8.66100052e-01
    5.78142237e-01]
  [-5.53066812e-01  1.17524413e+00 -7.84250246e-04  2.59036760e-01
    1.66920502e+00]
  [-2.52396601e+00 -1.89570613e+00 -1.40534909e+00  3.78908328e-01
    5.39961393e-01]]

 [[ 1.42370804e+00  5.81722412e-01 -6.14046971e-01 -8.96537962e-01
   -1.20831972e+00]
  [-2.40713142e+00  6.29121611e-01  4.13408705e-01  8.02546306e-01
   -3.08461282e-01]
  [ 5.43269279e-03  4.45262825e-01 -7.84059528e-01 -4.95589367e-01
   -1.30465162e+00]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here
b = np.ones((5,3,2))

#### 6. Print *b*.


In [8]:
# your code here
print(b)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here

np.size(a) == np.size(b)

# Yes the arrays have the same size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here

np.add(a, b)

# No, I can't add because they have different dimensions, but they are both 3 dimensional.

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,3,2) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here

c = np.transpose(b)
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# your code/answer here
d = a + c

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# your code/answer here

print('array a', a)
print(' ')
print('array d', d)

#f = d - a
#print(f)

# The array d is the sum of the values in array a plus 1. Therefore, they cannot be equal in terms of their values.

array a [[[ 5.16672934e-01  4.25284156e-01 -1.75756014e+00  8.66100052e-01
    5.78142237e-01]
  [-5.53066812e-01  1.17524413e+00 -7.84250246e-04  2.59036760e-01
    1.66920502e+00]
  [-2.52396601e+00 -1.89570613e+00 -1.40534909e+00  3.78908328e-01
    5.39961393e-01]]

 [[ 1.42370804e+00  5.81722412e-01 -6.14046971e-01 -8.96537962e-01
   -1.20831972e+00]
  [-2.40713142e+00  6.29121611e-01  4.13408705e-01  8.02546306e-01
   -3.08461282e-01]
  [ 5.43269279e-03  4.45262825e-01 -7.84059528e-01 -4.95589367e-01
   -1.30465162e+00]]]
 
array d [[[ 1.51667293  1.42528416 -0.75756014  1.86610005  1.57814224]
  [ 0.44693319  2.17524413  0.99921575  1.25903676  2.66920502]
  [-1.52396601 -0.89570613 -0.40534909  1.37890833  1.53996139]]

 [[ 2.42370804  1.58172241  0.38595303  0.10346204 -0.20831972]
  [-1.40713142  1.62912161  1.4134087   1.80254631  0.69153872]
  [ 1.00543269  1.44526283  0.21594047  0.50441063 -0.30465162]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
# your code here
e = a * c
print(e)

[[[ 5.16672934e-01  4.25284156e-01 -1.75756014e+00  8.66100052e-01
    5.78142237e-01]
  [-5.53066812e-01  1.17524413e+00 -7.84250246e-04  2.59036760e-01
    1.66920502e+00]
  [-2.52396601e+00 -1.89570613e+00 -1.40534909e+00  3.78908328e-01
    5.39961393e-01]]

 [[ 1.42370804e+00  5.81722412e-01 -6.14046971e-01 -8.96537962e-01
   -1.20831972e+00]
  [-2.40713142e+00  6.29121611e-01  4.13408705e-01  8.02546306e-01
   -3.08461282e-01]
  [ 5.43269279e-03  4.45262825e-01 -7.84059528e-01 -4.95589367e-01
   -1.30465162e+00]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
# your code/answer here
e == a

# Yes, because the array c is an array full of values that are 1. 
# if you multiply any number by 1, you will get that number.
# In this case you will get exatly the same array a. So e is euqal to a.

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
# your code here
d_max = np.max(d)
print(d_max)

d_min = np.min(d)
print(d_min)

d_mean = np.mean(d)
print(d_mean)

2.6692050209185654
-1.523966012106568
0.8184842434687635


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [17]:
# your code here
f = np.empty((2,3,5))
print(f)

[[[5.16672934e-01 4.25284156e-01 1.75756014e+00 8.66100052e-01
   5.78142237e-01]
  [5.53066812e-01 1.17524413e+00 7.84250246e-04 2.59036760e-01
   1.66920502e+00]
  [2.52396601e+00 1.89570613e+00 1.40534909e+00 3.78908328e-01
   5.39961393e-01]]

 [[1.42370804e+00 5.81722412e-01 6.14046971e-01 8.96537962e-01
   1.20831972e+00]
  [2.40713142e+00 6.29121611e-01 4.13408705e-01 8.02546306e-01
   3.08461282e-01]
  [5.43269279e-03 4.45262825e-01 7.84059528e-01 4.95589367e-01
   1.30465162e+00]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [26]:
# your code here
    
f[(d > d_min) & (d < d_mean)] = 25

f[(d > d_mean) & (d < d_max)] = 75

f[d == d_mean] = 50

f[d == d_min] = 0

f[d == d_max] = 100

    
print(f)

[[[ 75.  75.  25.  75.  75.]
  [ 25.  75.  75.  75. 100.]
  [  0.  25.  25.  75.  75.]]

 [[ 75.  75.  25.  25.  25.]
  [ 25.  75.  75.  75.  25.]
  [ 75.  75.  25.  25.  25.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [27]:
# your code here
print(d)
print(' ')
print(f)

# Yes, the code is returning the expected output. 

[[[ 1.51667293  1.42528416 -0.75756014  1.86610005  1.57814224]
  [ 0.44693319  2.17524413  0.99921575  1.25903676  2.66920502]
  [-1.52396601 -0.89570613 -0.40534909  1.37890833  1.53996139]]

 [[ 2.42370804  1.58172241  0.38595303  0.10346204 -0.20831972]
  [-1.40713142  1.62912161  1.4134087   1.80254631  0.69153872]
  [ 1.00543269  1.44526283  0.21594047  0.50441063 -0.30465162]]]
 
[[[ 75.  75.  25.  75.  75.]
  [ 25.  75.  75.  75. 100.]
  [  0.  25.  25.  75.  75.]]

 [[ 75.  75.  25.  25.  25.]
  [ 25.  75.  75.  75.  25.]
  [ 75.  75.  25.  25.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [20]:
# your code here