# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [75]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [7]:
# your code here
print(np.__version__)

1.18.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [10]:
# Method 1
a = np.random.randn(2,3,5) 

In [ ]:
# Method 2

In [ ]:
# Method 3

#### 4. Print *a*.


In [11]:
# your code here
print(a)

[[[ 1.25454174  0.92986327  0.16030554 -0.32334455  0.27718766]
  [ 0.3036097   0.84345489 -0.09605682 -2.64470918 -0.21267165]
  [ 0.10888042  0.7117896  -0.33697247  0.47486574  0.01023044]]

 [[ 0.41766317 -0.40276368 -1.12868501  1.14609004 -0.56728269]
  [-0.84542574  0.09144039  0.16488572 -1.28370762  3.05720259]
  [-0.70086261 -0.89043317  0.29799849  0.93634769 -0.44980326]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [12]:
# your code here
b = np.ones((5,2,3)) 

#### 6. Print *b*.


In [13]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [14]:
# your code here
len(a) == len (b)

False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [15]:
# your answer here
x = np.add(a,b)
print (x) #it won't be possible because one array is 2*3*5 and the other 5*2*3; they are different

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [16]:
# your code here
c = b.reshape(2,3,5)
print (c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [63]:
# your code/answer here
d = np.add(a,c)
print (d)

[[[ 2.25454174  1.92986327  1.16030554  0.67665545  1.27718766]
  [ 1.3036097   1.84345489  0.90394318 -1.64470918  0.78732835]
  [ 1.10888042  1.7117896   0.66302753  1.47486574  1.01023044]]

 [[ 1.41766317  0.59723632 -0.12868501  2.14609004  0.43271731]
  [ 0.15457426  1.09144039  1.16488572 -0.28370762  4.05720259]
  [ 0.29913739  0.10956683  1.29799849  1.93634769  0.55019674]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [64]:
# your code/answer here
print ("a=", a)
print('\n')
print ("d=", d)

#d is a result of the addition of a with c

a= [[[ 1.25454174  0.92986327  0.16030554 -0.32334455  0.27718766]
  [ 0.3036097   0.84345489 -0.09605682 -2.64470918 -0.21267165]
  [ 0.10888042  0.7117896  -0.33697247  0.47486574  0.01023044]]

 [[ 0.41766317 -0.40276368 -1.12868501  1.14609004 -0.56728269]
  [-0.84542574  0.09144039  0.16488572 -1.28370762  3.05720259]
  [-0.70086261 -0.89043317  0.29799849  0.93634769 -0.44980326]]]


d= [[[ 2.25454174  1.92986327  1.16030554  0.67665545  1.27718766]
  [ 1.3036097   1.84345489  0.90394318 -1.64470918  0.78732835]
  [ 1.10888042  1.7117896   0.66302753  1.47486574  1.01023044]]

 [[ 1.41766317  0.59723632 -0.12868501  2.14609004  0.43271731]
  [ 0.15457426  1.09144039  1.16488572 -0.28370762  4.05720259]
  [ 0.29913739  0.10956683  1.29799849  1.93634769  0.55019674]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [65]:
# your code here
e = np.multiply(a,c)
print (e)

[[[ 1.25454174  0.92986327  0.16030554 -0.32334455  0.27718766]
  [ 0.3036097   0.84345489 -0.09605682 -2.64470918 -0.21267165]
  [ 0.10888042  0.7117896  -0.33697247  0.47486574  0.01023044]]

 [[ 0.41766317 -0.40276368 -1.12868501  1.14609004 -0.56728269]
  [-0.84542574  0.09144039  0.16488572 -1.28370762  3.05720259]
  [-0.70086261 -0.89043317  0.29799849  0.93634769 -0.44980326]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [66]:
# your code/answer here
print ("a =", a)
('\n')
print ("e =", e)

np.array_equal(a, e)

    
#a and e are equal. e is a result of a multiplication between a and c, and each value in c is equal to 1. a number multiplied by one remains the same.

a = [[[ 1.25454174  0.92986327  0.16030554 -0.32334455  0.27718766]
  [ 0.3036097   0.84345489 -0.09605682 -2.64470918 -0.21267165]
  [ 0.10888042  0.7117896  -0.33697247  0.47486574  0.01023044]]

 [[ 0.41766317 -0.40276368 -1.12868501  1.14609004 -0.56728269]
  [-0.84542574  0.09144039  0.16488572 -1.28370762  3.05720259]
  [-0.70086261 -0.89043317  0.29799849  0.93634769 -0.44980326]]]
e = [[[ 1.25454174  0.92986327  0.16030554 -0.32334455  0.27718766]
  [ 0.3036097   0.84345489 -0.09605682 -2.64470918 -0.21267165]
  [ 0.10888042  0.7117896  -0.33697247  0.47486574  0.01023044]]

 [[ 0.41766317 -0.40276368 -1.12868501  1.14609004 -0.56728269]
  [-0.84542574  0.09144039  0.16488572 -1.28370762  3.05720259]
  [-0.70086261 -0.89043317  0.29799849  0.93634769 -0.44980326]]]


True

14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [67]:
# your code here
d_max = np.max(d)
print ("Maximum of d:", d_max)
d_min = np.min(d)
print ("Minimum of d:", d_min)
d_mean = np.mean (d)
print ("Mean of d:", d_mean)

Maximum of d: 4.0572025896022215
Minimum of d: -1.6447091779012841
Mean of d: 1.0434546219173926


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [68]:
# your code here
f = np.empty ([2,3,5])
print ("f=", f)

f= [[[1.25454174 0.92986327 0.16030554 0.32334455 0.27718766]
  [0.3036097  0.84345489 0.09605682 2.64470918 0.21267165]
  [0.10888042 0.7117896  0.33697247 0.47486574 0.01023044]]

 [[0.41766317 0.40276368 1.12868501 1.14609004 0.56728269]
  [0.84542574 0.09144039 0.16488572 1.28370762 3.05720259]
  [0.70086261 0.89043317 0.29799849 0.93634769 0.44980326]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [69]:
#2x3x5 array

index_x = 0
for x in d:    
    index_y = 0
    for y in x:
        index_z = 0
        for z in y:
            #print(z)
            if (z>d_min and z<d_mean):
                f[index_x,index_y,index_z] = 25
            if (z>d_mean and z<d_max):
                f[index_x,index_y,index_z] = 75
            if (z == d_mean):
                f[index_x,index_y,index_z] = 50
            if (z == d_min):
                f[index_x,index_y,index_z] = 0
            if (z == d_max):
                f[index_x,index_y,index_z] = 100
            index_z = index_z + 1 
        index_y = index_y + 1       
    index_x = index_x + 1           

print(f)









[[[ 75.  75.  75.  25.  75.]
  [ 75.  75.  25.   0.  25.]
  [ 75.  75.  25.  75.  25.]]

 [[ 75.  25.  25.  75.  25.]
  [ 25.  75.  75.  25. 100.]
  [ 25.  25.  75.  75.  25.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [70]:
# your code here
print (d)
print (e)

[[[ 2.25454174  1.92986327  1.16030554  0.67665545  1.27718766]
  [ 1.3036097   1.84345489  0.90394318 -1.64470918  0.78732835]
  [ 1.10888042  1.7117896   0.66302753  1.47486574  1.01023044]]

 [[ 1.41766317  0.59723632 -0.12868501  2.14609004  0.43271731]
  [ 0.15457426  1.09144039  1.16488572 -0.28370762  4.05720259]
  [ 0.29913739  0.10956683  1.29799849  1.93634769  0.55019674]]]
[[[ 1.25454174  0.92986327  0.16030554 -0.32334455  0.27718766]
  [ 0.3036097   0.84345489 -0.09605682 -2.64470918 -0.21267165]
  [ 0.10888042  0.7117896  -0.33697247  0.47486574  0.01023044]]

 [[ 0.41766317 -0.40276368 -1.12868501  1.14609004 -0.56728269]
  [-0.84542574  0.09144039  0.16488572 -1.28370762  3.05720259]
  [-0.70086261 -0.89043317  0.29799849  0.93634769 -0.44980326]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [80]:
#2x3x5 array

k = np.chararray((2, 3, 5))
index_x = 0
for x in d:    
    index_y = 0
    for y in x:
        index_z = 0
        for z in y:
            #print(z)
            if (z>d_min and z<d_mean):
                k[index_x,index_y,index_z] = "B"
            if (z>d_mean and z<d_max):
                k[index_x,index_y,index_z] = "D"
            if (z == d_mean):
                k[index_x,index_y,index_z] = "C"
            if (z == d_min):
                k[index_x,index_y,index_z] = "A"
            if (z == d_max):
                k[index_x,index_y,index_z] = "E"
            index_z = index_z + 1 
        index_y = index_y + 1       
    index_x = index_x + 1           

print(k)

[[[b'D' b'D' b'D' b'B' b'D']
  [b'D' b'D' b'B' b'A' b'B']
  [b'D' b'D' b'B' b'D' b'B']]

 [[b'D' b'B' b'B' b'D' b'B']
  [b'B' b'D' b'D' b'B' b'E']
  [b'B' b'B' b'D' b'D' b'B']]]
