# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [5]:
# your code here

import numpy as np

#### 2. Print your NumPy version.

In [6]:
# your code here

print("NumPy Version : ",np.__version__)

NumPy Version :  1.24.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [18]:
# Method 1

a = np.random.random(size = (2,3,4))
a

array([[[0.49394801, 0.41606977, 0.99594286, 0.16336667],
        [0.40480256, 0.42771307, 0.61766931, 0.38438541],
        [0.02539472, 0.51858253, 0.32983082, 0.45802613]],

       [[0.82307997, 0.59724382, 0.17152116, 0.41463204],
        [0.24915744, 0.59025771, 0.58242819, 0.29615499],
        [0.02870235, 0.87646794, 0.29586079, 0.11474045]]])

In [19]:
# Method 2

a = np.random.random_sample((2, 3, 5))
a

array([[[0.68792027, 0.91506177, 0.17069798, 0.91554771, 0.66658621],
        [0.50636034, 0.20579295, 0.77528482, 0.10918329, 0.44881792],
        [0.1614752 , 0.95593983, 0.72585752, 0.94133837, 0.27115026]],

       [[0.67429144, 0.98566251, 0.50494178, 0.34624013, 0.21878849],
        [0.13481798, 0.78977384, 0.05629741, 0.09793456, 0.67794858],
        [0.30028245, 0.44141246, 0.6870931 , 0.6099192 , 0.2525572 ]]])

In [20]:
# Method 3

a = np.random.randint(0, 10, size=(2, 3, 5))
a

array([[[8, 6, 0, 3, 0],
        [8, 0, 2, 5, 7],
        [5, 1, 6, 4, 7]],

       [[1, 8, 9, 4, 7],
        [1, 5, 8, 5, 9],
        [5, 3, 2, 2, 9]]])

#### 4. Print *a*.


In [21]:
# your code here
a

array([[[8, 6, 0, 3, 0],
        [8, 0, 2, 5, 7],
        [5, 1, 6, 4, 7]],

       [[1, 8, 9, 4, 7],
        [1, 5, 8, 5, 9],
        [5, 3, 2, 2, 9]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [23]:
# your code here

b = np.ones((5, 2, 3))
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 6. Print *b*.


In [24]:
# your code here

b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [25]:
# your code here

if a.size == b.size:
    print("The arrays have the same size.")
else:
    print("The arrays do not have the same size.")

The arrays have the same size.


#### 8. Are you able to add *a* and *b*? Why or why not?


In [30]:
# your answer here

if a.shape == b.shape:
    print("The arrays can be added.")
else:
    print("The arrays cannot be added.")

    # arrays can only be added if they share the same shape

The arrays cannot be added.


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [37]:
# your code here

c = b.transpose((1, 2, 0))

c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [43]:
# your code/answer here

d = a + c

d

# Because both a and c share the same shape (2x3x5)

array([[[ 9.,  7.,  1.,  4.,  1.],
        [ 9.,  1.,  3.,  6.,  8.],
        [ 6.,  2.,  7.,  5.,  8.]],

       [[ 2.,  9., 10.,  5.,  8.],
        [ 2.,  6.,  9.,  6., 10.],
        [ 6.,  4.,  3.,  3., 10.]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [44]:
# your code/answer here

print(a)

print(d)

# because d is the sum between a and c, d has then the same values as a but icremented by one

[[[8 6 0 3 0]
  [8 0 2 5 7]
  [5 1 6 4 7]]

 [[1 8 9 4 7]
  [1 5 8 5 9]
  [5 3 2 2 9]]]
[[[ 9.  7.  1.  4.  1.]
  [ 9.  1.  3.  6.  8.]
  [ 6.  2.  7.  5.  8.]]

 [[ 2.  9. 10.  5.  8.]
  [ 2.  6.  9.  6. 10.]
  [ 6.  4.  3.  3. 10.]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [45]:
# your code here

e = a * c

e

array([[[8., 6., 0., 3., 0.],
        [8., 0., 2., 5., 7.],
        [5., 1., 6., 4., 7.]],

       [[1., 8., 9., 4., 7.],
        [1., 5., 8., 5., 9.],
        [5., 3., 2., 2., 9.]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [52]:
# your code/answer here

if np.array_equal(e, a):
    print("e is equal to a")
else:
    print("e is not equal to a")

    # because a is just an array of random numbers and e is a multiplication between a and c, they cant be equal

e is equal to a


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [55]:
# your code here

d_max = np.max(d)
print("Maximum value in d:", d_max)

d_min = np.min(d)
print("Minimum value in d:", d_min)

d_mean = np.mean(d)
print("Mean value of d:", d_mean)

Maximum value in d: 10.0
Minimum value in d: 1.0
Mean value of d: 5.666666666666667


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [56]:
# your code here

f = np.empty((2, 3, 5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [67]:
# your code here

for i in range(2):
    for j in range(3):
        for k in range(5):
            if d[i, j, k] == d_min:
                f[i, j, k] = 0
            elif d_min < d[i, j, k] < d_mean:
                f[i, j, k] = 25
            elif d[i, j, k] == d_mean:
                f[i, j, k] = 50
            elif d_mean < d[i, j, k] < d_max:
                f[i, j, k] = 75
            else:
                f[i, j, k] = 100


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [70]:
# your code here

print(d)

print(f)

[[[ 9.  7.  1.  4.  1.]
  [ 9.  1.  3.  6.  8.]
  [ 6.  2.  7.  5.  8.]]

 [[ 2.  9. 10.  5.  8.]
  [ 2.  6.  9.  6. 10.]
  [ 6.  4.  3.  3. 10.]]]
[[[ 75.  75.   0.  25.   0.]
  [ 75.   0.  25.  75.  75.]
  [ 75.  25.  75.  25.  75.]]

 [[ 25.  75. 100.  25.  75.]
  [ 25.  75.  75.  75. 100.]
  [ 75.  25.  25.  25. 100.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [71]:
# your code here

# I guess the previous is already wrong