# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.__version__)

1.17.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a = np.random.random((2,3,5))
a

array([[[0.22488954, 0.27520517, 0.3800705 , 0.840079  , 0.60953995],
        [0.35409395, 0.44434122, 0.54234801, 0.41266563, 0.44931683],
        [0.72322262, 0.53672047, 0.58174597, 0.08300996, 0.4681634 ]],

       [[0.32592794, 0.36161454, 0.75087165, 0.82108347, 0.2923642 ],
        [0.50786092, 0.02457398, 0.02282437, 0.88207954, 0.30474049],
        [0.82281123, 0.11893279, 0.44741443, 0.45863714, 0.45558088]]])

In [23]:
# Method 2
a = np.random.rand(2,3,5)
a

array([[[0.64372012, 0.27711405, 0.9458925 , 0.21884288, 0.74085799],
        [0.64578472, 0.41697138, 0.69378829, 0.7145878 , 0.61600993],
        [0.01635281, 0.94679162, 0.1625695 , 0.37912513, 0.88571873]],

       [[0.25452179, 0.84721543, 0.34196343, 0.54072369, 0.16542487],
        [0.48352368, 0.18945721, 0.81970219, 0.07365815, 0.9355492 ],
        [0.77707689, 0.76777819, 0.65525539, 0.00600283, 0.67812575]]])

In [24]:
# Method 3
a = np.random.randint(1,100, size=(2,3,5))
a

array([[[ 2, 31, 99, 28, 23],
        [68, 50, 56, 28, 59],
        [70, 52, 12, 52, 41]],

       [[32, 10, 56,  6, 68],
        [20, 38,  3, 31, 45],
        [48, 41, 93, 31, 68]]])

#### 4. Print *a*.


In [25]:
# your code here
print(a)

[[[ 2 31 99 28 23]
  [68 50 56 28 59]
  [70 52 12 52 41]]

 [[32 10 56  6 68]
  [20 38  3 31 45]
  [48 41 93 31 68]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [26]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [27]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [28]:
# your code here
a = np.array(a)
b = np.array(b)
ab_size = bool(a.size == b.size)

print(f"Is the size of and b the same? That information is {ab_size}.")

Is the size of and b the same? That information is True.


#### 8. Are you able to add *a* and *b*? Why or why not?


Not as they are, since they have different shapes.


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [29]:
# your code here
c = np.transpose(b,(1,2,0))
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [30]:
# your code/answer here
d = np.add(a,c)
d

array([[[  3.,  32., 100.,  29.,  24.],
        [ 69.,  51.,  57.,  29.,  60.],
        [ 71.,  53.,  13.,  53.,  42.]],

       [[ 33.,  11.,  57.,   7.,  69.],
        [ 21.,  39.,   4.,  32.,  46.],
        [ 49.,  42.,  94.,  32.,  69.]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [33]:
# your code/answer here
print(a)
print(d)

# the .add function added each values of one matrix to the other one

[[[ 2 31 99 28 23]
  [68 50 56 28 59]
  [70 52 12 52 41]]

 [[32 10 56  6 68]
  [20 38  3 31 45]
  [48 41 93 31 68]]]
[[[  3.  32. 100.  29.  24.]
  [ 69.  51.  57.  29.  60.]
  [ 71.  53.  13.  53.  42.]]

 [[ 33.  11.  57.   7.  69.]
  [ 21.  39.   4.  32.  46.]
  [ 49.  42.  94.  32.  69.]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [34]:
# your code here
e = np.multiply(a, c)
e

array([[[ 2., 31., 99., 28., 23.],
        [68., 50., 56., 28., 59.],
        [70., 52., 12., 52., 41.]],

       [[32., 10., 56.,  6., 68.],
        [20., 38.,  3., 31., 45.],
        [48., 41., 93., 31., 68.]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [37]:
# your code/answer here

ae_equal = np.array_equal (a, e)

# yes, because we were multiplying everything by one
print(f"Are a and e? That information is {ae_equal}.")


Are a and e? That information is True.


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [81]:
# your code here

d_max = np.amax(d)
d_min = np.amin(d)
d_mean = np.mean(d)

print(d_max, d_min, d_mean)

100.0 3.0 43.03333333333333


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [82]:
# your code here

f = np.empty([2,3,5])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [90]:
# your code here

d = np.ndarray.flatten(d)
f = np.ndarray.flatten(f)

for i, x in enumerate(d):
    if x > d_min and x < d_mean:
        f[i] = 25
    if x > d_mean and x < d_max:
        f[i] = 75
    if x == d_mean:
        f[i] = 50
    if x == d_min:
        f[i] = 0
    if x == d_max:
        f[i] = 100
            
d = d.reshape(2,3,5)
f = f.reshape(2,3,5)

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [91]:
# your code here
print(d)
print(f)

[[[  3.  32. 100.  29.  24.]
  [ 69.  51.  57.  29.  60.]
  [ 71.  53.  13.  53.  42.]]

 [[ 33.  11.  57.   7.  69.]
  [ 21.  39.   4.  32.  46.]
  [ 49.  42.  94.  32.  69.]]]
[[[  0.  25. 100.  25.  25.]
  [ 75.  75.  75.  25.  75.]
  [ 75.  75.  25.  75.  25.]]

 [[ 25.  25.  75.  25.  75.]
  [ 25.  25.  25.  25.  75.]
  [ 75.  25.  75.  25.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [97]:
# your code here

f = np.ndarray.flatten(f)
new_f = []

for x in f:
    if x == 25:
        new_f.append("B")
    if x == 75:
        new_f.append("D")
    if x == 50:
        new_f.append("C")
    if x == 0:
        new_f.append("A")
    if x == 100:
        new_f.append("E")

new_f = np.asarray(new_f)        
new_f = new_f.reshape(2,3,5)
new_f

array([[['A', 'B', 'E', 'B', 'B'],
        ['D', 'D', 'D', 'B', 'D'],
        ['D', 'D', 'B', 'D', 'B']],

       [['B', 'B', 'D', 'B', 'D'],
        ['B', 'B', 'B', 'B', 'D'],
        ['D', 'B', 'D', 'B', 'D']]], dtype='<U1')