# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [447]:
import numpy as np# your code here

#### 2. Print your NumPy version.

In [448]:
# your code here
print("np version:",np.__version__)

np version: 1.18.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [449]:
# Method 1
# Parameters:	size : int or tuple of ints, optional
# Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn
a = np.random.random((2,3,5))
print(a)

[[[0.43678043 0.76925811 0.46531316 0.67728898 0.12069809]
  [0.85291128 0.01904371 0.81279013 0.407801   0.18026026]
  [0.5443839  0.36981399 0.46975703 0.97896527 0.11641586]]

 [[0.14541196 0.68543216 0.75963369 0.11598369 0.86108774]
  [0.87131766 0.07758428 0.01756934 0.62338864 0.19807906]
  [0.9176943  0.55537225 0.91254738 0.61434475 0.85609868]]]


In [450]:
# Method 2
# The empty function creates an array. Its initial content is random and depends on the state of the memory.

a = np.empty((2,3,5))
a

array([[[0.43678043, 0.76925811, 0.46531316, 0.67728898, 0.12069809],
        [0.85291128, 0.01904371, 0.81279013, 0.407801  , 0.18026026],
        [0.5443839 , 0.36981399, 0.46975703, 0.97896527, 0.11641586]],

       [[0.14541196, 0.68543216, 0.75963369, 0.11598369, 0.86108774],
        [0.87131766, 0.07758428, 0.01756934, 0.62338864, 0.19807906],
        [0.9176943 , 0.55537225, 0.91254738, 0.61434475, 0.85609868]]])

In [451]:
# Method 3
# Random values in a given shape.
a = np.random.rand(2,3,5)
a

array([[[0.64563827, 0.85758238, 0.85429354, 0.41411468, 0.61440135],
        [0.93795836, 0.0526075 , 0.3631687 , 0.87142369, 0.46103842],
        [0.86852681, 0.95276247, 0.39342568, 0.00278073, 0.75823234]],

       [[0.25575462, 0.25937491, 0.83762821, 0.05941857, 0.75961581],
        [0.78437133, 0.74522979, 0.99515121, 0.09903598, 0.69447252],
        [0.98808442, 0.17621395, 0.47275621, 0.6522219 , 0.58693921]]])

#### 4. Print *a*.


In [452]:
# your code here

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [453]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [454]:
# your code here
print (b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [455]:
# your code here
a.shape == b.shape

False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [456]:
# your answer here

# Value error: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 
# I guess because they dont have the same shape 🤔

# Find the overlapping range, and then add the arrays using slicing.

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [457]:
# your code here
from numpy import reshape
c = b.reshape(a.shape)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [458]:
# your code/answer here
d = a + c
d
# It works because it has the same shape.

array([[[1.64563827, 1.85758238, 1.85429354, 1.41411468, 1.61440135],
        [1.93795836, 1.0526075 , 1.3631687 , 1.87142369, 1.46103842],
        [1.86852681, 1.95276247, 1.39342568, 1.00278073, 1.75823234]],

       [[1.25575462, 1.25937491, 1.83762821, 1.05941857, 1.75961581],
        [1.78437133, 1.74522979, 1.99515121, 1.09903598, 1.69447252],
        [1.98808442, 1.17621395, 1.47275621, 1.6522219 , 1.58693921]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [459]:
# your code/answer here
print ("np d array:\n",a)
print("np d array:\n",d)

np d array:
 [[[0.64563827 0.85758238 0.85429354 0.41411468 0.61440135]
  [0.93795836 0.0526075  0.3631687  0.87142369 0.46103842]
  [0.86852681 0.95276247 0.39342568 0.00278073 0.75823234]]

 [[0.25575462 0.25937491 0.83762821 0.05941857 0.75961581]
  [0.78437133 0.74522979 0.99515121 0.09903598 0.69447252]
  [0.98808442 0.17621395 0.47275621 0.6522219  0.58693921]]]
np d array:
 [[[1.64563827 1.85758238 1.85429354 1.41411468 1.61440135]
  [1.93795836 1.0526075  1.3631687  1.87142369 1.46103842]
  [1.86852681 1.95276247 1.39342568 1.00278073 1.75823234]]

 [[1.25575462 1.25937491 1.83762821 1.05941857 1.75961581]
  [1.78437133 1.74522979 1.99515121 1.09903598 1.69447252]
  [1.98808442 1.17621395 1.47275621 1.6522219  1.58693921]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [460]:
# your code here
e = c*a
e

array([[[0.64563827, 0.85758238, 0.85429354, 0.41411468, 0.61440135],
        [0.93795836, 0.0526075 , 0.3631687 , 0.87142369, 0.46103842],
        [0.86852681, 0.95276247, 0.39342568, 0.00278073, 0.75823234]],

       [[0.25575462, 0.25937491, 0.83762821, 0.05941857, 0.75961581],
        [0.78437133, 0.74522979, 0.99515121, 0.09903598, 0.69447252],
        [0.98808442, 0.17621395, 0.47275621, 0.6522219 , 0.58693921]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [461]:
# your code/answer here
e == a
# Because any number multiplied by 1 is equal to the number



array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [462]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print("max:",d_max,"min:",d_min,"mean:",d_mean)


max: 1.9951512094456882 min: 1.0027807348229478 mean: 1.580474119252917


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [463]:
# your code here
f = np.empty(d.shape)
f

array([[[0.64563827, 0.85758238, 0.85429354, 0.41411468, 0.61440135],
        [0.93795836, 0.0526075 , 0.3631687 , 0.87142369, 0.46103842],
        [0.86852681, 0.95276247, 0.39342568, 0.00278073, 0.75823234]],

       [[0.25575462, 0.25937491, 0.83762821, 0.05941857, 0.75961581],
        [0.78437133, 0.74522979, 0.99515121, 0.09903598, 0.69447252],
        [0.98808442, 0.17621395, 0.47275621, 0.6522219 , 0.58693921]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [464]:
# Parameters:	
# a : array_like
# Target array.

# mask : array_like
# Boolean mask array. It has to be the same shape as a.

# values : array_like
# Values to put into a where mask is True. If values is smaller than a it will be repeated.
# condition = [(min < d) & (d < d_mean)]

mask1 = np.logical_and(d < d_mean, d > d_min)
# value1 = 25.
mask2 = np.logical_and(d > d_mean, d < d_max)
# value2 = 75.
mask3 = d == d_mean
mask4 = d == d_min
mask5 = d == d_max

np.putmask(f, mask1, 25. )
np.putmask(f, mask2, 75. )
np.putmask(f, mask3, 50. )
np.putmask(f, mask4, 0. )
np.putmask(f, mask5, 100. )

f

array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  25.,  25.,  75.,  25.],
        [ 75.,  75.,  25.,   0.,  75.]],

       [[ 25.,  25.,  75.,  25.,  75.],
        [ 75.,  75., 100.,  25.,  75.],
        [ 75.,  25.,  25.,  75.,  75.]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [465]:
# your code here
print(d)
print(f)

[[[1.64563827 1.85758238 1.85429354 1.41411468 1.61440135]
  [1.93795836 1.0526075  1.3631687  1.87142369 1.46103842]
  [1.86852681 1.95276247 1.39342568 1.00278073 1.75823234]]

 [[1.25575462 1.25937491 1.83762821 1.05941857 1.75961581]
  [1.78437133 1.74522979 1.99515121 1.09903598 1.69447252]
  [1.98808442 1.17621395 1.47275621 1.6522219  1.58693921]]]
[[[ 75.  75.  75.  25.  75.]
  [ 75.  25.  25.  75.  25.]
  [ 75.  75.  25.   0.  75.]]

 [[ 25.  25.  75.  25.  75.]
  [ 75.  75. 100.  25.  75.]
  [ 75.  25.  25.  75.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [473]:
# your code here
# NOT THERE YET!

# print(np.where(f == 25, "A", f))


np.putmask(f, mask1, "B")
np.putmask(f, mask2, "D" )
np.putmask(f, mask3, "C" )
np.putmask(f, mask4, "A" )
np.putmask(f, mask5, "E" )

f

ValueError: could not convert string to float: 'B'