# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np


#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.version.version)

1.18.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1

a = np.random.random((2,3,5))
a

array([[[0.01211221, 0.22358094, 0.00292748, 0.64106289, 0.10676724],
        [0.61651014, 0.09218315, 0.19070391, 0.31367289, 0.97511983],
        [0.19924088, 0.38221008, 0.10343186, 0.47092111, 0.15025097]],

       [[0.385889  , 0.64237869, 0.80005777, 0.35143797, 0.34504157],
        [0.05841984, 0.83522699, 0.06712718, 0.80058127, 0.46546479],
        [0.9936475 , 0.49303385, 0.64934614, 0.15526027, 0.05965893]]])

In [4]:
# Method 2
a = np.random.random((2,5,3))
a = a.reshape(2,3,5)
a

array([[[0.15195189, 0.55183619, 0.59416504, 0.57608279, 0.04357642],
        [0.22652174, 0.35205801, 0.34113844, 0.81708066, 0.24188676],
        [0.58069088, 0.22981401, 0.53514084, 0.61829065, 0.33404257]],

       [[0.76797426, 0.87097567, 0.81968641, 0.39692946, 0.44524158],
        [0.1582932 , 0.0164242 , 0.03230287, 0.72605236, 0.3943521 ],
        [0.24934172, 0.48791709, 0.3666166 , 0.11704715, 0.49227905]]])

In [5]:
# Method 3
h = np.random.random((3,5))
y = np.random.random((3,5))
c = np.array((h,y))
c.shape


(2, 3, 5)

#### 4. Print *a*.


In [6]:

print(a)

[[[0.15195189 0.55183619 0.59416504 0.57608279 0.04357642]
  [0.22652174 0.35205801 0.34113844 0.81708066 0.24188676]
  [0.58069088 0.22981401 0.53514084 0.61829065 0.33404257]]

 [[0.76797426 0.87097567 0.81968641 0.39692946 0.44524158]
  [0.1582932  0.0164242  0.03230287 0.72605236 0.3943521 ]
  [0.24934172 0.48791709 0.3666166  0.11704715 0.49227905]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here
b= np.ones((5,2,3), dtype = int)
b

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

#### 6. Print *b*.


In [8]:
# your code here
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here
b.size == a.size


True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
print(b.shape)
print(a.shape)

# your answer here

if a.shape == b.shape: 
    print('a and b have the same shape and can be added')
else: 
    print('a and b have different shapes and cant be added')

#No, because they don't have the same shape

(5, 2, 3)
(2, 3, 5)
a and b have different shapes and cant be added


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here

c = np.transpose(b,(1,2,0)) # b was a 5x2x3 if we want to get it to 2x3x5 then ints go from 0,1,2 to 1,2,0

print(c.shape)



(2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# your code/answer here
d = np.add(a,c)
d


array([[[1.15195189, 1.55183619, 1.59416504, 1.57608279, 1.04357642],
        [1.22652174, 1.35205801, 1.34113844, 1.81708066, 1.24188676],
        [1.58069088, 1.22981401, 1.53514084, 1.61829065, 1.33404257]],

       [[1.76797426, 1.87097567, 1.81968641, 1.39692946, 1.44524158],
        [1.1582932 , 1.0164242 , 1.03230287, 1.72605236, 1.3943521 ],
        [1.24934172, 1.48791709, 1.3666166 , 1.11704715, 1.49227905]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# your code/answer here
print(a,'\n')
print(d)


print('Every value of d corresponds to the sum of each individual value of a to the correspondent value of c, the transposed shape of b')

[[[0.15195189 0.55183619 0.59416504 0.57608279 0.04357642]
  [0.22652174 0.35205801 0.34113844 0.81708066 0.24188676]
  [0.58069088 0.22981401 0.53514084 0.61829065 0.33404257]]

 [[0.76797426 0.87097567 0.81968641 0.39692946 0.44524158]
  [0.1582932  0.0164242  0.03230287 0.72605236 0.3943521 ]
  [0.24934172 0.48791709 0.3666166  0.11704715 0.49227905]]] 

[[[1.15195189 1.55183619 1.59416504 1.57608279 1.04357642]
  [1.22652174 1.35205801 1.34113844 1.81708066 1.24188676]
  [1.58069088 1.22981401 1.53514084 1.61829065 1.33404257]]

 [[1.76797426 1.87097567 1.81968641 1.39692946 1.44524158]
  [1.1582932  1.0164242  1.03230287 1.72605236 1.3943521 ]
  [1.24934172 1.48791709 1.3666166  1.11704715 1.49227905]]]
Every value of d corresponds to the sum of each individual value of a to the correspondent value of c, the transposed shape of b


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
# your code here
e = np.multiply(a,c)


#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
# your code/answer here
e == a
("Yes, we basically just multiplied every value of a by 1, so e is exactly the same as a")

'Yes, we basically just multiplied every value of a by 1, so e is exactly the same as a'

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
# your code here
print(d)

# max
d_max = np.max(d)
print("Max value of d:", d_max)

# min 
d_min = np.min(d)
print("Min value of d:", d_min)


d_mean = np.mean(d)
print("Mean value of d:",d_mean)



[[[1.15195189 1.55183619 1.59416504 1.57608279 1.04357642]
  [1.22652174 1.35205801 1.34113844 1.81708066 1.24188676]
  [1.58069088 1.22981401 1.53514084 1.61829065 1.33404257]]

 [[1.76797426 1.87097567 1.81968641 1.39692946 1.44524158]
  [1.1582932  1.0164242  1.03230287 1.72605236 1.3943521 ]
  [1.24934172 1.48791709 1.3666166  1.11704715 1.49227905]]]
Max value of d: 1.8709756650604175
Min value of d: 1.0164242016773302
Mean value of d: 1.4178570199511527


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [71]:
# your code here

f = np.empty([2,3,5], dtype = float )
print(f)

# why is this equal to d?

[[[25.          1.55183619  1.59416504  1.57608279 25.        ]
  [25.         25.         25.          1.81708066 25.        ]
  [ 1.58069088 25.          1.53514084  1.61829065 25.        ]]

 [[ 1.76797426  1.87097567  1.81968641 25.          1.44524158]
  [25.          1.0164242  25.          1.72605236 25.        ]
  [25.          1.48791709 25.         25.          1.49227905]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [78]:
# your code here



f = np.where((d<d_mean)&(d>d_min),25,d)
f = np.where((d>d_mean)&(d<d_max),75,f)
f = np.where((d==d_min),0,f)
f = np.where((d==d_max),100,f)
f = np.where(d==d_mean,50,f)


print(f)


[[[ 25.  75.  75.  75.  25.]
  [ 25.  25.  25.  75.  25.]
  [ 75.  25.  75.  75.  25.]]

 [[ 75. 100.  75.  25.  75.]
  [ 25.   0.  25.  75.  25.]
  [ 25.  75.  25.  25.  75.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [79]:
# your code here
print(d,'\n')
print(f,'\n')
    

[[[1.15195189 1.55183619 1.59416504 1.57608279 1.04357642]
  [1.22652174 1.35205801 1.34113844 1.81708066 1.24188676]
  [1.58069088 1.22981401 1.53514084 1.61829065 1.33404257]]

 [[1.76797426 1.87097567 1.81968641 1.39692946 1.44524158]
  [1.1582932  1.0164242  1.03230287 1.72605236 1.3943521 ]
  [1.24934172 1.48791709 1.3666166  1.11704715 1.49227905]]] 

[[[ 25.  75.  75.  75.  25.]
  [ 25.  25.  25.  75.  25.]
  [ 75.  25.  75.  75.  25.]]

 [[ 75. 100.  75.  25.  75.]
  [ 25.   0.  25.  75.  25.]
  [ 25.  75.  25.  25.  75.]]] 



#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [80]:
# your code here
f = np.where((d<d_mean)&(d>d_min),'A',d)
f = np.where((d>d_mean)&(d<d_max),'B',f)
f = np.where((d==d_min),'C',f)
f = np.where((d==d_max),'D',f)
f = np.where(d==d_mean,'E',f)

print(d,'\n')
print(f,'\n')

[[[1.15195189 1.55183619 1.59416504 1.57608279 1.04357642]
  [1.22652174 1.35205801 1.34113844 1.81708066 1.24188676]
  [1.58069088 1.22981401 1.53514084 1.61829065 1.33404257]]

 [[1.76797426 1.87097567 1.81968641 1.39692946 1.44524158]
  [1.1582932  1.0164242  1.03230287 1.72605236 1.3943521 ]
  [1.24934172 1.48791709 1.3666166  1.11704715 1.49227905]]] 

[[['A' 'B' 'B' 'B' 'A']
  ['A' 'A' 'A' 'B' 'A']
  ['B' 'A' 'B' 'B' 'A']]

 [['B' 'D' 'B' 'A' 'B']
  ['A' 'C' 'A' 'B' 'A']
  ['A' 'B' 'A' 'A' 'B']]] 

