# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [44]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [45]:
# your code here
print(np.version.version)

1.20.3


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [58]:
# Method 1
#a = np.random.random((2,3,5))

In [63]:
# Method 2
a = np.random.randint(0,100,(2,3,5))

In [60]:
# Method 3
a = [[[np.random.random() for k in range(5)] for j in range(3)] for i in range(2)]
a = np.array(a)

#### 4. Print *a*.


In [64]:
# your code here
print(a)

[[[ 0 80  9 70 40]
  [79 80 44 15 50]
  [70 42 49 18 95]]

 [[37 98 47 78 62]
  [ 5 67 42 40 95]
  [ 1  3 38 50 17]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [61]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [62]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [65]:
# your code here
size_a = np.prod(a.shape)
size_b = np.prod(b.shape)

size_a == size_b

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [53]:
# your answer here
c = a + b
# because although the size is the same, the shape is not. (2x3x5) != (5x2x3) and to multiply matrices they need to have the same shape


ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [66]:
# your code here
c = b.transpose

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [68]:
# your code/answer here
d = a + c
d

TypeError: unsupported operand type(s) for +: 'int' and 'builtin_function_or_method'

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [69]:
# your code/answer here
print(a)
print(d)

# It's the same but each element in d is equal to ( a + 1) because we added a to c and each element of c is == 1

[[[ 0 80  9 70 40]
  [79 80 44 15 50]
  [70 42 49 18 95]]

 [[37 98 47 78 62]
  [ 5 67 42 40 95]
  [ 1  3 38 50 17]]]
[[[10.6280778  38.66202657 35.83011842 49.25552783 95.83766925]
  [63.66885576 73.67102693 16.18234506 20.28145498 93.49957226]
  [76.33077025 44.70427876 21.0700358  53.0653282  18.83903974]]

 [[45.32612281 86.46649168 52.17576705 19.33226285 77.47549168]
  [86.63056375 86.0134475  52.50514467 60.36717973 75.73284967]
  [32.54579014 92.43794536  2.54272646 54.59361142 10.52953822]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [ ]:
# your code here
e = a * c
e

ValueError: operands could not be broadcast together with shapes (2,3,5) (3,2,5) 

#### 13. Does *e* equal to *a*? Why or why not?


In [ ]:
# your code/answer here

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [70]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [71]:
# your code here
f = np.empty((2,3,5))
f

array([[[10.6280778 , 38.66202657, 35.83011842, 49.25552783,
         95.83766925],
        [63.66885576, 73.67102693, 16.18234506, 20.28145498,
         93.49957226],
        [76.33077025, 44.70427876, 21.0700358 , 53.0653282 ,
         18.83903974]],

       [[45.32612281, 86.46649168, 52.17576705, 19.33226285,
         77.47549168],
        [86.63056375, 86.0134475 , 52.50514467, 60.36717973,
         75.73284967],
        [32.54579014, 92.43794536,  2.54272646, 54.59361142,
         10.52953822]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [72]:
# your code here
before_list = []

for element in d:
    for subelement in element:
        for a in subelement:
            if a > d_min and a < d_mean:
                before_list.append(25)
               
            elif a > d_min and a < d_max:
                before_list.append(75)
                
            elif a == d_mean:
                before_list.append(50)
                
            elif a == d_min:
                before_list.append(0)
                
            else:
                before_list.append(100)
                
            
array = np.array(before_list)

f = np.reshape(before_list, (2,3,5))

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [73]:
# your code here
print(f)

[[[ 25  25  25  25 100]
  [ 75  75  25  25  75]
  [ 75  25  25  75  25]]

 [[ 25  75  75  25  75]
  [ 75  75  75  75  75]
  [ 25  75   0  75  25]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here