# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [3]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [4]:
# your code here
np.version.version

'1.17.2'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [6]:
# Method 1
a = np.random.random((2,3,5)) ## *0.4 + 0.3 # in order to get a range between two certain numbers. first multuply the diference of the highest number that we want and after that add the value of the minimun value 
print (a)
print('')
print(a.shape) 
print('')
print(a.size) # = 3*5*2

[[[0.69471841 0.95293258 0.56994401 0.15962752 0.3289983 ]
  [0.06782549 0.78106273 0.44663008 0.38004194 0.80580282]
  [0.44912041 0.01126432 0.24276345 0.77431388 0.36342136]]

 [[0.68783512 0.60136456 0.74548641 0.30369637 0.17862069]
  [0.89259473 0.37947965 0.29616912 0.37257548 0.86643742]
  [0.65101742 0.51528465 0.63257559 0.6080083  0.61579248]]]

(2, 3, 5)

30


In [7]:
# Method 2

ex = np.random.randint(192, size=(2,3,5))
print(ex)

print('')
print('')

#slicing tests

     #1st wich , group 2nd wich rows , 3rd wich columns
    
print(f'This is slicing: \n\n {ex[1, 1:, 1:4]}, \n\n here we have the values from second to last row, in the second to the third column of the second grup')

[[[ 36  14  45 110  41]
  [105 120 130  87  57]
  [162  90  25  16  40]]

 [[ 32  25  58  63  74]
  [ 28 170 184   0 164]
  [ 67 135 155  87  20]]]


This is slicing: 

 [[170 184   0]
 [135 155  87]], 

 here we have the values from second to last row, in the second to the third column of the second grup


In [8]:
import random

In [9]:
# Method 3
 

ls = random.sample(range(100), k= 5)

list_of_lists = [ls] * 3

#print(list_of_lists)

grup_of_2_list_of_lists = [list_of_lists] * 2

#print(grup_of_2_list_of_lists)

np.array(grup_of_2_list_of_lists)


array([[[16, 49, 83,  0, 68],
        [16, 49, 83,  0, 68],
        [16, 49, 83,  0, 68]],

       [[16, 49, 83,  0, 68],
        [16, 49, 83,  0, 68],
        [16, 49, 83,  0, 68]]])

#### 4. Print *a*.


In [10]:
# your code here
print(a)

[[[0.69471841 0.95293258 0.56994401 0.15962752 0.3289983 ]
  [0.06782549 0.78106273 0.44663008 0.38004194 0.80580282]
  [0.44912041 0.01126432 0.24276345 0.77431388 0.36342136]]

 [[0.68783512 0.60136456 0.74548641 0.30369637 0.17862069]
  [0.89259473 0.37947965 0.29616912 0.37257548 0.86643742]
  [0.65101742 0.51528465 0.63257559 0.6080083  0.61579248]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [11]:
# your code here

b = np.ones((5,2,3), dtype = int) # the default dtype is float

#### 6. Print *b*.


In [12]:
# your code here
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [13]:
# your code here
a_size = a.size
b_size = b.size
print(a_size)
print(b_size)

print(a_size == b_size)

30
30
True


#### 8. Are you able to add *a* and *b*? Why or why not?


In [14]:
# your answer here

sum_a_b = a + b

#because the arrays have diverent shapes!

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [15]:
# your code here
print(b.transpose())

#HOW DO I DO THIS WITH TRANSPOSE? WHEN I TRANSPOSE B (5,2,3) I GET AN ARRAY
#WITH SHAPE (3,2,5) AND NOT (2,3,5)??

print('')
print('')


c = np.reshape(b, (2,3,5))

print(c)


[[[1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]]]


[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [52]:
# your code/answer here
d = a + c

print(d)

[[[1.69471841 1.95293258 1.56994401 1.15962752 1.3289983 ]
  [1.06782549 1.78106273 1.44663008 1.38004194 1.80580282]
  [1.44912041 1.01126432 1.24276345 1.77431388 1.36342136]]

 [[1.68783512 1.60136456 1.74548641 1.30369637 1.17862069]
  [1.89259473 1.37947965 1.29616912 1.37257548 1.86643742]
  [1.65101742 1.51528465 1.63257559 1.6080083  1.61579248]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [53]:
# your code/answer here
print(a)

print('')
print('')

print(d)

print('')
print('')

"""array d is the sum of the values from array a with
values from array c"""

[[[0.69471841 0.95293258 0.56994401 0.15962752 0.3289983 ]
  [0.06782549 0.78106273 0.44663008 0.38004194 0.80580282]
  [0.44912041 0.01126432 0.24276345 0.77431388 0.36342136]]

 [[0.68783512 0.60136456 0.74548641 0.30369637 0.17862069]
  [0.89259473 0.37947965 0.29616912 0.37257548 0.86643742]
  [0.65101742 0.51528465 0.63257559 0.6080083  0.61579248]]]


[[[1.69471841 1.95293258 1.56994401 1.15962752 1.3289983 ]
  [1.06782549 1.78106273 1.44663008 1.38004194 1.80580282]
  [1.44912041 1.01126432 1.24276345 1.77431388 1.36342136]]

 [[1.68783512 1.60136456 1.74548641 1.30369637 1.17862069]
  [1.89259473 1.37947965 1.29616912 1.37257548 1.86643742]
  [1.65101742 1.51528465 1.63257559 1.6080083  1.61579248]]]




'array d is the sum of the values from array a with\nvalues from array c'

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [54]:
# your code here
e = a * c

#### 13. Does *e* equal to *a*? Why or why not?


In [55]:
# your code/answer here
print(e)

print('')
print('')

print(e)

"""They are the same because we are multypling
each value from array a by 1"""

[[[0.69471841 0.95293258 0.56994401 0.15962752 0.3289983 ]
  [0.06782549 0.78106273 0.44663008 0.38004194 0.80580282]
  [0.44912041 0.01126432 0.24276345 0.77431388 0.36342136]]

 [[0.68783512 0.60136456 0.74548641 0.30369637 0.17862069]
  [0.89259473 0.37947965 0.29616912 0.37257548 0.86643742]
  [0.65101742 0.51528465 0.63257559 0.6080083  0.61579248]]]


[[[0.69471841 0.95293258 0.56994401 0.15962752 0.3289983 ]
  [0.06782549 0.78106273 0.44663008 0.38004194 0.80580282]
  [0.44912041 0.01126432 0.24276345 0.77431388 0.36342136]]

 [[0.68783512 0.60136456 0.74548641 0.30369637 0.17862069]
  [0.89259473 0.37947965 0.29616912 0.37257548 0.86643742]
  [0.65101742 0.51528465 0.63257559 0.6080083  0.61579248]]]


'They are the same because we are multypling\neach value from array a by 1'

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [56]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)



#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [57]:
# your code here

f = np.empty((2,3,5))


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [74]:
d = [[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]

d = np.array(d)
s = d.shape

#HERE WE ASSIGNE EACH POSITION OF THE ARRAY THROUGH INDEXING A VALUE
# DEPENDING ON THE CONDITION

for gr in range(s[0]):
    for row in range(s[1]):
        for col in range(s[2]):
            if (d[gr, row, col] > d_min) & (d[gr, row, col] < d_mean):
                f[gr,row,col] = 25
            elif (d[gr, row, col] > d_mean) & (d[gr, row, col] < d_max):
                f[gr,row,col] = 75
            elif d[gr, row, col] == d_min:
                f[gr,row,col] = 0
            elif d[gr, row, col] == d_max:
                f[gr,row,col] = 100


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [71]:

print(f)


[[[75. 75. 75. 25. 75.]
  [75. 75. 25. 75. 25.]
  [75. 25. 75. 75. 75.]]

 [[25. 25. 25. 75. 25.]
  [75. 75. 25. 75. 75.]
  [25. 75. 75. 75. 75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [67]:
# your code here

new_array = np.empty((2,3,5), dtype = str)

new_array[(d_min < d) & (d < d_mean)] = 'B'
new_array[(d_mean < d) & (d < d_max)] = 'D'
new_array[d == d_mean] = 'C'
new_array[d == d_min] = 'A'
new_array[d == d_max] = 'E'

#tis returns an array all True if we look at the combination of all conditions
# but depending where the condition is True we add the value we are equaling that condition

print(new_array)

#we can use booleas or 'masks' index arrays and use them as indices,
#  Boolean arrays must be of the same shape as the initial dimensions of the array being indexed.

[[['D' 'E' 'D' 'B' 'B']
  ['B' 'D' 'B' 'B' 'D']
  ['B' 'A' 'B' 'D' 'B']]

 [['D' 'D' 'D' 'B' 'B']
  ['D' 'B' 'B' 'B' 'D']
  ['D' 'D' 'D' 'D' 'D']]]


In [73]:
#MASK INDEX

print((d_min < d) | (d < d_mean) | (d_mean < d) & (d < d_max) | (d == d_mean) | (d == d_min) | (d == d_max)) 

[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]
