# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [2]:
import numpy as np

#### 2. Print your NumPy version.

In [3]:
np.version.version

'1.18.5'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [4]:
a=np.random.random((2,3,5))
a

array([[[0.10636637, 0.4342913 , 0.16204783, 0.87309934, 0.58609425],
        [0.07007362, 0.94078042, 0.47125589, 0.77110435, 0.77823225],
        [0.74753253, 0.37094754, 0.39287408, 0.78947608, 0.5763445 ]],

       [[0.87569457, 0.45613031, 0.94309214, 0.2403313 , 0.22754336],
        [0.98963296, 0.47082716, 0.25839404, 0.27983093, 0.26871957],
        [0.9697306 , 0.47290429, 0.90850089, 0.56223022, 0.42335221]]])

In [5]:
a2=np.random.rand(2,3,5)
a2

array([[[0.45021654, 0.49117507, 0.58893872, 0.76900336, 0.32949575],
        [0.11963311, 0.59351904, 0.43342435, 0.63074584, 0.50899715],
        [0.37938587, 0.74609766, 0.38142219, 0.87739178, 0.50997925]],

       [[0.88565728, 0.34767454, 0.56030177, 0.66002596, 0.72186927],
        [0.29134062, 0.87379484, 0.21540628, 0.48566869, 0.68628598],
        [0.86504355, 0.97108188, 0.77059903, 0.66886133, 0.51230763]]])

In [7]:
a3 = np.empty((2,3,5))
print(a3)

[[[0.45021654 0.49117507 0.58893872 0.76900336 0.32949575]
  [0.11963311 0.59351904 0.43342435 0.63074584 0.50899715]
  [0.37938587 0.74609766 0.38142219 0.87739178 0.50997925]]

 [[0.88565728 0.34767454 0.56030177 0.66002596 0.72186927]
  [0.29134062 0.87379484 0.21540628 0.48566869 0.68628598]
  [0.86504355 0.97108188 0.77059903 0.66886133 0.51230763]]]


#### 4. Print *a*.


In [8]:
print(a)

[[[0.10636637 0.4342913  0.16204783 0.87309934 0.58609425]
  [0.07007362 0.94078042 0.47125589 0.77110435 0.77823225]
  [0.74753253 0.37094754 0.39287408 0.78947608 0.5763445 ]]

 [[0.87569457 0.45613031 0.94309214 0.2403313  0.22754336]
  [0.98963296 0.47082716 0.25839404 0.27983093 0.26871957]
  [0.9697306  0.47290429 0.90850089 0.56223022 0.42335221]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [12]:
b=np.ones((5,2,3))

#### 6. Print *b*.


In [13]:
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [16]:
size_a=a.size
size_b=b.size

if size_b==size_a:
    print('Same size')
else:
    print('Not the same size')

30
30
Same size


#### 8. Are you able to add *a* and *b*? Why or why not?


In [18]:
#We can only add arrays with the same shape

'We can only add arrays with the same shape'

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [15]:
c=np.reshape(b,(2,3,5))

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [20]:
d=np.add(a,c)
#Works because 'a' and 'c' have the same shape

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [26]:
print('a=',a,'\n\n','d=',d)
#the array 'd' is the sum of array 'a' and 'c' where all elements are the int=1

a= [[[0.10636637 0.4342913  0.16204783 0.87309934 0.58609425]
  [0.07007362 0.94078042 0.47125589 0.77110435 0.77823225]
  [0.74753253 0.37094754 0.39287408 0.78947608 0.5763445 ]]

 [[0.87569457 0.45613031 0.94309214 0.2403313  0.22754336]
  [0.98963296 0.47082716 0.25839404 0.27983093 0.26871957]
  [0.9697306  0.47290429 0.90850089 0.56223022 0.42335221]]] 

 d= [[[1.10636637 1.4342913  1.16204783 1.87309934 1.58609425]
  [1.07007362 1.94078042 1.47125589 1.77110435 1.77823225]
  [1.74753253 1.37094754 1.39287408 1.78947608 1.5763445 ]]

 [[1.87569457 1.45613031 1.94309214 1.2403313  1.22754336]
  [1.98963296 1.47082716 1.25839404 1.27983093 1.26871957]
  [1.9697306  1.47290429 1.90850089 1.56223022 1.42335221]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [27]:
e=np.multiply(a,c)

#### 13. Does *e* equal to *a*? Why or why not?


In [29]:
print(e)
#They are equal, because when 'c' is neutral in multiplication (i.e==1)

[[[0.10636637 0.4342913  0.16204783 0.87309934 0.58609425]
  [0.07007362 0.94078042 0.47125589 0.77110435 0.77823225]
  [0.74753253 0.37094754 0.39287408 0.78947608 0.5763445 ]]

 [[0.87569457 0.45613031 0.94309214 0.2403313  0.22754336]
  [0.98963296 0.47082716 0.25839404 0.27983093 0.26871957]
  [0.9697306  0.47290429 0.90850089 0.56223022 0.42335221]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [38]:
d_max=np.max(d)
d_min=np.min(d)
d_mean=np.mean(d)

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [36]:
f=np.empty((2,3,5))


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [44]:
f=np.copy(d)
f[f==d_min]=0
f[f==d_mean]=50
f[f==d_max]=100
f[(f>d_min)&(f<d_mean)]=25
f[(f>d_mean)&(f<d_max)]=75

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [46]:
print(d)
print(f)

[[[1.10636637 1.4342913  1.16204783 1.87309934 1.58609425]
  [1.07007362 1.94078042 1.47125589 1.77110435 1.77823225]
  [1.74753253 1.37094754 1.39287408 1.78947608 1.5763445 ]]

 [[1.87569457 1.45613031 1.94309214 1.2403313  1.22754336]
  [1.98963296 1.47082716 1.25839404 1.27983093 1.26871957]
  [1.9697306  1.47290429 1.90850089 1.56223022 1.42335221]]]
[[[ 25.  25.  25.  75.  75.]
  [  0.  75.  25.  75.  75.]
  [ 75.  25.  25.  75.  75.]]

 [[ 75.  25.  75.  25.  25.]
  [100.  25.  25.  25.  25.]
  [ 75.  25.  75.  75.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here