# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [2]:
print(np.__version__)

1.20.3


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
a = np.random.random(size = (2,3, 5)) 

a

array([[[0.9615594 , 0.29613416, 0.62156674, 0.55524137, 0.03991176],
        [0.67287674, 0.34479779, 0.43459218, 0.76537728, 0.16541233],
        [0.12028328, 0.57475743, 0.87560858, 0.88464413, 0.00492948]],

       [[0.26828206, 0.03660877, 0.16525551, 0.23727485, 0.50236813],
        [0.4719377 , 0.87151464, 0.62339235, 0.45263895, 0.01467945],
        [0.37732589, 0.93940039, 0.98907157, 0.77181611, 0.28740555]]])

In [4]:
# Method 2

In [5]:
# Method 3

#### 4. Print *a*.


In [21]:
print(a)

[[[0.9615594  0.29613416 0.62156674 0.55524137 0.03991176]
  [0.67287674 0.34479779 0.43459218 0.76537728 0.16541233]
  [0.12028328 0.57475743 0.87560858 0.88464413 0.00492948]]

 [[0.26828206 0.03660877 0.16525551 0.23727485 0.50236813]
  [0.4719377  0.87151464 0.62339235 0.45263895 0.01467945]
  [0.37732589 0.93940039 0.98907157 0.77181611 0.28740555]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [23]:
b = np.zeros(shape = (5,2,3), dtype = int)+1
b

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

#### 6. Print *b*.


In [24]:
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [27]:
a.shape == b.shape

False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
## No, I cannnot do it. Because they don´t have the same shape.

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [34]:
c = b.reshape(2,3,5)
c# the number of elements must be the same 2x2x3 == 4x3

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [35]:
d = a + c
d
## Beacuse now the number of elements it is the same 2x3x5 

array([[[1.9615594 , 1.29613416, 1.62156674, 1.55524137, 1.03991176],
        [1.67287674, 1.34479779, 1.43459218, 1.76537728, 1.16541233],
        [1.12028328, 1.57475743, 1.87560858, 1.88464413, 1.00492948]],

       [[1.26828206, 1.03660877, 1.16525551, 1.23727485, 1.50236813],
        [1.4719377 , 1.87151464, 1.62339235, 1.45263895, 1.01467945],
        [1.37732589, 1.93940039, 1.98907157, 1.77181611, 1.28740555]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [37]:
print(a)
print(d)

### The d array it is +1 because I did +1 before convert in d (b and c)

[[[0.9615594  0.29613416 0.62156674 0.55524137 0.03991176]
  [0.67287674 0.34479779 0.43459218 0.76537728 0.16541233]
  [0.12028328 0.57475743 0.87560858 0.88464413 0.00492948]]

 [[0.26828206 0.03660877 0.16525551 0.23727485 0.50236813]
  [0.4719377  0.87151464 0.62339235 0.45263895 0.01467945]
  [0.37732589 0.93940039 0.98907157 0.77181611 0.28740555]]]
[[[1.9615594  1.29613416 1.62156674 1.55524137 1.03991176]
  [1.67287674 1.34479779 1.43459218 1.76537728 1.16541233]
  [1.12028328 1.57475743 1.87560858 1.88464413 1.00492948]]

 [[1.26828206 1.03660877 1.16525551 1.23727485 1.50236813]
  [1.4719377  1.87151464 1.62339235 1.45263895 1.01467945]
  [1.37732589 1.93940039 1.98907157 1.77181611 1.28740555]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [39]:
e = a * c
e

array([[[0.9615594 , 0.29613416, 0.62156674, 0.55524137, 0.03991176],
        [0.67287674, 0.34479779, 0.43459218, 0.76537728, 0.16541233],
        [0.12028328, 0.57475743, 0.87560858, 0.88464413, 0.00492948]],

       [[0.26828206, 0.03660877, 0.16525551, 0.23727485, 0.50236813],
        [0.4719377 , 0.87151464, 0.62339235, 0.45263895, 0.01467945],
        [0.37732589, 0.93940039, 0.98907157, 0.77181611, 0.28740555]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [40]:
e == a 

## Yes, it is. I don´t now 

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [47]:
d_max = (d.max())
d_max



1.989071571898791

In [48]:
d_min = (d.min())
d_min


1.0049294815106573

In [49]:
d_mean = (d.mean())
d_mean

1.4775554858833793

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [56]:
f = np.empty([2, 3, 5])
f


array([[[0.9615594 , 0.29613416, 0.62156674, 0.55524137, 0.03991176],
        [0.67287674, 0.34479779, 0.43459218, 0.76537728, 0.16541233],
        [0.12028328, 0.57475743, 0.87560858, 0.88464413, 0.00492948]],

       [[0.26828206, 0.03660877, 0.16525551, 0.23727485, 0.50236813],
        [0.4719377 , 0.87151464, 0.62339235, 0.45263895, 0.01467945],
        [0.37732589, 0.93940039, 0.98907157, 0.77181611, 0.28740555]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [18]:
# your code here

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [20]:
# your code here