# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here

import numpy as np


#### 2. Print your NumPy version.

In [2]:
# your code here

np.version.version

'1.18.1'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1

a = np.random.random(size = (2,3,5))

a

array([[[0.12622515, 0.74234073, 0.28720891, 0.90645884, 0.47883732],
        [0.20866396, 0.22970167, 0.42097244, 0.93608751, 0.77166652],
        [0.8804467 , 0.36734131, 0.13991964, 0.43061568, 0.89516475]],

       [[0.03356652, 0.38684222, 0.27830817, 0.23018301, 0.84025728],
        [0.71392386, 0.38953532, 0.20993318, 0.89906968, 0.65548247],
        [0.66942355, 0.98516189, 0.05773723, 0.02194669, 0.30470207]]])

In [4]:
# Method 2

a = np.random.randint(100, size = (2,3,5))
a

array([[[27, 65, 33, 14, 19],
        [88, 69, 78, 38, 76],
        [87, 43, 28, 90, 76]],

       [[27, 27, 68, 98, 69],
        [82, 38, 30, 73, 50],
        [52, 39, 72,  9, 68]]])

In [5]:
# Method 3

a = np.random.rand(2,3,5)

a

array([[[0.4382436 , 0.06807011, 0.71598094, 0.41956512, 0.48805571],
        [0.48056941, 0.0311562 , 0.57979628, 0.50982657, 0.45538117],
        [0.93218416, 0.98913565, 0.49024174, 0.82831139, 0.58396209]],

       [[0.20305025, 0.70795304, 0.92825776, 0.75038291, 0.93505778],
        [0.92125537, 0.49576392, 0.50468718, 0.51929099, 0.05940104],
        [0.86098565, 0.24269009, 0.99939224, 0.59325685, 0.72016905]]])

#### 4. Print *a*.


In [6]:
# your code here

print(a)

[[[0.4382436  0.06807011 0.71598094 0.41956512 0.48805571]
  [0.48056941 0.0311562  0.57979628 0.50982657 0.45538117]
  [0.93218416 0.98913565 0.49024174 0.82831139 0.58396209]]

 [[0.20305025 0.70795304 0.92825776 0.75038291 0.93505778]
  [0.92125537 0.49576392 0.50468718 0.51929099 0.05940104]
  [0.86098565 0.24269009 0.99939224 0.59325685 0.72016905]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here

b = np.ones((5,2,3), dtype = int)
b

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

#### 6. Print *b*.


In [8]:
# your code here

print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here

a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here

np.add(a,b)

#They have different shapes

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here

c = b.transpose()
c

np.shape(c)

(3, 2, 5)

In [12]:
print(b)
print(a)
np.shape(a)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
[[[0.4382436  0.06807011 0.71598094 0.41956512 0.48805571]
  [0.48056941 0.0311562  0.57979628 0.50982657 0.45538117]
  [0.93218416 0.98913565 0.49024174 0.82831139 0.58396209]]

 [[0.20305025 0.70795304 0.92825776 0.75038291 0.93505778]
  [0.92125537 0.49576392 0.50468718 0.51929099 0.05940104]
  [0.86098565 0.24269009 0.99939224 0.59325685 0.72016905]]]


(2, 3, 5)

In [13]:
#transpose on its all just reverses the order of the axis
#this allows you do define the order in which you want the axis to be transposed

c = np.transpose(b, (1,2,0))
print(c)

np.shape(c)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [14]:
# your code/answer here

d = np.add(a,c)

#arrays a and c now have the same shape, each value in array a may be matched to a value in array c

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [15]:
# your code/answer here

print(a)
print(np.shape(a))

print(d)
print(np.shape(d))

# np.add(a,c) added each value in array d to each value in array a

[[[0.4382436  0.06807011 0.71598094 0.41956512 0.48805571]
  [0.48056941 0.0311562  0.57979628 0.50982657 0.45538117]
  [0.93218416 0.98913565 0.49024174 0.82831139 0.58396209]]

 [[0.20305025 0.70795304 0.92825776 0.75038291 0.93505778]
  [0.92125537 0.49576392 0.50468718 0.51929099 0.05940104]
  [0.86098565 0.24269009 0.99939224 0.59325685 0.72016905]]]
(2, 3, 5)
[[[1.4382436  1.06807011 1.71598094 1.41956512 1.48805571]
  [1.48056941 1.0311562  1.57979628 1.50982657 1.45538117]
  [1.93218416 1.98913565 1.49024174 1.82831139 1.58396209]]

 [[1.20305025 1.70795304 1.92825776 1.75038291 1.93505778]
  [1.92125537 1.49576392 1.50468718 1.51929099 1.05940104]
  [1.86098565 1.24269009 1.99939224 1.59325685 1.72016905]]]
(2, 3, 5)


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [16]:
# your code here

e = np.multiply(a,c)
e

array([[[0.4382436 , 0.06807011, 0.71598094, 0.41956512, 0.48805571],
        [0.48056941, 0.0311562 , 0.57979628, 0.50982657, 0.45538117],
        [0.93218416, 0.98913565, 0.49024174, 0.82831139, 0.58396209]],

       [[0.20305025, 0.70795304, 0.92825776, 0.75038291, 0.93505778],
        [0.92125537, 0.49576392, 0.50468718, 0.51929099, 0.05940104],
        [0.86098565, 0.24269009, 0.99939224, 0.59325685, 0.72016905]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [17]:
# your code/answer here

e == a

#each item in array a is equal to each value in array e

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [18]:
# your code here

d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(d_max)
print(d_min)
print(d_mean)

1.9993922412943692
1.0311561989364635
1.5817358081227961


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [19]:
# your code here

f = np.empty(shape = (2,3,5), dtype = float)
print(f)

[[[0.4382436  0.06807011 0.71598094 0.41956512 0.48805571]
  [0.48056941 0.0311562  0.57979628 0.50982657 0.45538117]
  [0.93218416 0.98913565 0.49024174 0.82831139 0.58396209]]

 [[0.20305025 0.70795304 0.92825776 0.75038291 0.93505778]
  [0.92125537 0.49576392 0.50468718 0.51929099 0.05940104]
  [0.86098565 0.24269009 0.99939224 0.59325685 0.72016905]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [38]:
# your code here

condition0 = (d == d_min)
condition25 = (d > d_min) & (d < d_mean)
condition50 = (d == d_mean)
condition75 = (d > d_mean) & (d < d_max)
condition100 = (d == d_max)

f = np.where(condition0, 0, d)
f = np.where(condition25, 25, f)
f = np.where(condition50, 50, f)
f = np.where(condition75, 75, f)
f = np.where(condition100, 100, f)
      
print(f)

[[[ 25.  25.  75.  25.  25.]
  [ 25.   0.  25.  25.  25.]
  [ 75.  75.  25.  75.  75.]]

 [[ 25.  75.  75.  75.  75.]
  [ 75.  25.  25.  25.  25.]
  [ 75.  25. 100.  75.  75.]]]


In [39]:
#Maybe could use something like this as another method together with split?

x = np.array([[ 0.42436315, 0.48558583, 0.32924763], [ 0.7439979,0.58220701,0.38213418], [ 0.5097581,0.34528799,0.1563123 ]])

print("Original array:")
print(x)

print("Replace all elements of the said array with .5 which are greater than .5")
x[x > .5] = .5
print(x)

np.shape(x)

Original array:
[[0.42436315 0.48558583 0.32924763]
 [0.7439979  0.58220701 0.38213418]
 [0.5097581  0.34528799 0.1563123 ]]
Replace all elements of the said array with .5 which are greater than .5
[[0.42436315 0.48558583 0.32924763]
 [0.5        0.5        0.38213418]
 [0.5        0.34528799 0.1563123 ]]


(3, 3)

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [40]:
# your code here

print(d)

print("Minimum value in d is", d_min)
print("Mean of d is", d_mean)
print("Maximum value in d is", d_max)

print(f)

#This is the expected f

[[[1.4382436  1.06807011 1.71598094 1.41956512 1.48805571]
  [1.48056941 1.0311562  1.57979628 1.50982657 1.45538117]
  [1.93218416 1.98913565 1.49024174 1.82831139 1.58396209]]

 [[1.20305025 1.70795304 1.92825776 1.75038291 1.93505778]
  [1.92125537 1.49576392 1.50468718 1.51929099 1.05940104]
  [1.86098565 1.24269009 1.99939224 1.59325685 1.72016905]]]
Minimum value in d is 1.0311561989364635
Mean of d is 1.5817358081227961
Maximum value in d is 1.9993922412943692
[[[ 25.  25.  75.  25.  25.]
  [ 25.   0.  25.  25.  25.]
  [ 75.  75.  25.  75.  75.]]

 [[ 25.  75.  75.  75.  75.]
  [ 75.  25.  25.  25.  25.]
  [ 75.  25. 100.  75.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [41]:
# your code here

conditionA = (d == d_min)
conditionB = (d > d_min) & (d < d_mean)
conditionC = (d == d_mean)
conditionD = (d > d_mean) & (d < d_max)
conditionE = (d == d_max)

f = np.where(conditionA, "A", d)
f = np.where(conditionB, "B", f)
f = np.where(conditionC, "C", f)
f = np.where(conditionD, "D", f)
f = np.where(conditionE, "E", f)
      
print(f)

[[['B' 'B' 'D' 'B' 'B']
  ['B' 'A' 'B' 'B' 'B']
  ['D' 'D' 'B' 'D' 'D']]

 [['B' 'D' 'D' 'D' 'D']
  ['D' 'B' 'B' 'B' 'B']
  ['D' 'B' 'E' 'D' 'D']]]
