# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [375]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [376]:
# your code here
#np.version.version
print(np.__version__)

1.18.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [377]:
# Method 1
"""This created an array with 2 groups of 3 x 5 matrices."""
a = np.random.randint(100, size=(2,3,5))
#print(a.shape)

In [378]:
# Method 2
a = np.random.rand(2,3,5)
#print(a.shape)

In [379]:
# Method 3
#import random
#lst_lst = []
#for i in range(0,3):
#    lst = []
#    lst_lst.append(lst)
#    for j in range(0,5):
#        lst.append(random.randint(0,100))
#print(lst_lst)

#a = np.array(lst_lst)
#print(a)
#print(a.shape)
a = np.random.randint(low = 0, high = 100, size = (2,3,5))
#print(a.shape)

#### 4. Print *a*.


In [380]:
# your code here
print(a)

[[[12 88 61  8 53]
  [12 46 10 22 65]
  [84 17 61 47 58]]

 [[76  4 57 22 92]
  [44 17 90 19 96]
  [15 47 65 59 40]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [381]:
# your code here
"""Using list to solve the problem, then change list -> array"""
#import random
#lst_lstb = []
#for i in range(0,3):
#    lstb = []
#    lst_lstb.append(lstb)
#    for j in range(0,5):
#        lstb.append(1)
#print(lst_lstb)

#b = np.array(lst_lstb)

"""Using np.ones to solve the problem"""
b = np.ones((5,2,3), dtype=np.int16)

"""Using np.full to solve. This form is more general because allow you to build with any  value (not only 1)"""
#b = np.full(shape=(5,2,3),fill_value=1)

'Using np.full to solve. This form is more general because allow you to build with any  value (not only 1)'

#### 6. Print *b*.


In [382]:
# your code here
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [383]:
# your code here
if a.size == b.size:
    print("They have the same amount of elements.")
else:
    print("They don't have the same amount of elements.")

They have the same amount of elements.


#### 8. Are you able to add *a* and *b*? Why or why not?


In [384]:
# your answer here
"""a = [2,3,5] and b = [5,2,3]"""
print(a.shape)
print(b.shape)
print(np.add(a, b))
"""Why not?"""
#They don't have the same shape. numpy.add() function is used when we want to compute the addition of two array. It add arguments element-wise. If shape of two arrays are not same, that is arr1.shape != arr2.shape, they must be broadcastable to a common shape (which may be the shape of one or the other).

(2, 3, 5)
(5, 2, 3)


ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [342]:
# your code here
"""This method do the transposed matrix"""
c = b.T 
#print(c)
#print(b.shape)
#print(c.shape)
"""
This method reshape the matrix
Reshaping means changing the shape of an array.
Reshape works as long as the elements required for reshaping are equal in both shapes.

"""
c = b.reshape(2,3,5)
#print(b)
#print(c)
#print(c.shape)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [269]:
# your code/answer here
d = np.add(a,c)
#print(d)
print(a.shape)
print(c.shape)
#Works because they have the same shape.

(2, 3, 5)
(2, 3, 5)


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [387]:
# your code/answer here
print("a: ",a)
print("d: ", d)
"The method np.add sum the element of matrix c into matrix a, in this case d = a + 1"

a:  [[[12 88 61  8 53]
  [12 46 10 22 65]
  [84 17 61 47 58]]

 [[76  4 57 22 92]
  [44 17 90 19 96]
  [15 47 65 59 40]]]
d:  [[[74 12 85 68 32]
  [16 28 57 73 58]
  [28 91 38 80 44]]

 [[30  4 62  8 87]
  [38 45 66 33 30]
  [29 29 16 26 85]]]


'The method np.add sum the element of matrix c into matrix a, in this case d = a + 1'

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [344]:
# your code here
e = a*c
print(e)

[[[84 88  4 94 31]
  [13 39 80  2 69]
  [61 45 47 89 37]]

 [[54 36 87 11 62]
  [79 95 43 71 61]
  [50  2 37 97 73]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [345]:
# your code/answer here
"Yes. Because matrix c is a unitary matrix. Multiply one number per 1 gives the same number."

'Yes. Because matrix c is a unitary matrix. Multiply one number per 1 gives the same number.'

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [386]:
# your code here
d_max = d.max()
print("Max:",d_max)
d_min = d.min()
print("Min:",d_min)
d_mean = d.mean()
print("Mean:",d_mean)

Max: 91
Min: 4
Mean: 45.733333333333334


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [347]:
# your code here
f = np.empty((2,3,5), dtype=np.int16)
print(f)

[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [390]:
# your code here
#print(d.size)

list_d = []

for i in d:
    for j in i:
        for k in j:
            if k == d_min:
                list_d.append(0)
            elif k == d_mean:
                list_d.append(50)
            elif k == d_max:
                list_d.append(100)
            elif (k > d_min) & (k < d_mean):
                list_d.append(25)
            else:
                list_d.append(75)
f  = np.array(list_d).reshape(2,3,5)

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [391]:
# your code here
print("original: ",d)

print("Modified:",f)

#Yes.

original:  [[[74 12 85 68 32]
  [16 28 57 73 58]
  [28 91 38 80 44]]

 [[30  4 62  8 87]
  [38 45 66 33 30]
  [29 29 16 26 85]]]
Modified: [[[ 75  25  75  75  25]
  [ 25  25  75  75  75]
  [ 25 100  25  75  25]]

 [[ 25   0  75  25  75]
  [ 25  25  75  25  25]
  [ 25  25  25  25  75]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [393]:
# your code here
list_d_bonus = []

for i in d:
    for j in i:
        for k in j:
            if k == d_min:
                list_d_bonus.append("A")
            elif k == d_mean:
                list_d_bonus.append("C")
            elif k == d_max:
                list_d_bonus.append("E")
            elif (k > d_min) & (k < d_mean):
                list_d_bonus.append("B")
            else:
                list_d_bonus.append("D")
f_bonus  = np.array(list_d_bonus).reshape(2,3,5)
print(f_bonus)

[[['D' 'B' 'D' 'D' 'B']
  ['B' 'B' 'D' 'D' 'D']
  ['B' 'E' 'B' 'D' 'B']]

 [['B' 'A' 'D' 'B' 'D']
  ['B' 'B' 'D' 'B' 'B']
  ['B' 'B' 'B' 'B' 'D']]]
