# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [81]:
import numpy as np

#### 2. Print your NumPy version.

In [82]:
print(np.version.version)

1.18.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [83]:
import random

In [84]:
a = np.random.random((2,3,5))

In [88]:
a = np.random.randint(0,100,(2,3,5))

In [86]:
a = [[[random.random() for k in range(5)] for j in range(3)] for i in range(2)]
a = np.array(a)

#### 4. Print *a*.


In [89]:
print(a)

[[[78 43 78 15 70]
  [62 61 83 20 87]
  [19 67 20 55 60]]

 [[56 19 71 47 98]
  [21  9 90 51 34]
  [ 0 73 78 73 71]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [90]:
b = [[[1 for z in range(2)] for y in range(3)] for x in range(5)]
b = np.array(b)


#### 6. Print *b*.


In [91]:
print(b)

[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [92]:
size_a = np.prod(a.shape)
size_b = np.prod(b.shape)

size_a == size_b

# if we multiply 5x2x3 (in this case) we get the number of elements in the array -> which is the size I guess

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [93]:
c = a + b
# because although the size is the same, the shape is not. (2x3x5) != (5x2x3) and to multiply matrices they need to have the same shape

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,3,2) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [94]:
c = b.transpose()
c

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [95]:
d = a + c
d
# Now it works because the shape is the same!

array([[[79, 44, 79, 16, 71],
        [63, 62, 84, 21, 88],
        [20, 68, 21, 56, 61]],

       [[57, 20, 72, 48, 99],
        [22, 10, 91, 52, 35],
        [ 1, 74, 79, 74, 72]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [96]:
print(a)
print(d)

# It's the same but each element in d is equal to ( a + 1) because we added a to c and each element of c is == 1

[[[78 43 78 15 70]
  [62 61 83 20 87]
  [19 67 20 55 60]]

 [[56 19 71 47 98]
  [21  9 90 51 34]
  [ 0 73 78 73 71]]]
[[[79 44 79 16 71]
  [63 62 84 21 88]
  [20 68 21 56 61]]

 [[57 20 72 48 99]
  [22 10 91 52 35]
  [ 1 74 79 74 72]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [97]:
e = a * c
e

array([[[78, 43, 78, 15, 70],
        [62, 61, 83, 20, 87],
        [19, 67, 20, 55, 60]],

       [[56, 19, 71, 47, 98],
        [21,  9, 90, 51, 34],
        [ 0, 73, 78, 73, 71]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [98]:
print(e)
print(a)

# yes it does! because all elements in c are equal to 1 and every number multiplied by 1 gives the number. we could multiply this
# because we transposed b before, otherwise it would give an error

[[[78 43 78 15 70]
  [62 61 83 20 87]
  [19 67 20 55 60]]

 [[56 19 71 47 98]
  [21  9 90 51 34]
  [ 0 73 78 73 71]]]
[[[78 43 78 15 70]
  [62 61 83 20 87]
  [19 67 20 55 60]]

 [[56 19 71 47 98]
  [21  9 90 51 34]
  [ 0 73 78 73 71]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [124]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [123]:
f = np.empty((2,3,5))
f

array([[[0.60010429, 0.07089059, 0.33541471, 0.88183591, 0.09091293],
        [0.20306814, 0.41147225, 0.29448002, 0.97076658, 0.73769519],
        [0.22893966, 0.50070259, 0.63485843, 0.62111116, 0.751432  ]],

       [[0.95679678, 0.54021741, 0.95848312, 0.45057345, 0.10421974],
        [0.06125026, 0.40331841, 0.98199821, 0.14446695, 0.65230674],
        [0.53598296, 0.99681996, 0.71817399, 0.74340994, 0.54003983]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [127]:
before_list = []

for element in d:
    for subelement in element:
        for a in subelement:
            if a > d_min and a < d_mean:
                before_list.append(25)
               
            elif a > d_min and a < d_max:
                before_list.append(75)
                
            elif a == d_mean:
                before_list.append(50)
                
            elif a == d_min:
                before_list.append(0)
                
            else:
                before_list.append(100)
                
            
array = np.array(before_list)

f = np.reshape(before_list, (2,3,5))

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [128]:
print(f)

[[[ 75  25  75  25  75]
  [ 75  75  75  25  75]
  [ 25  75  25  75  75]]

 [[ 75  25  75  25 100]
  [ 25  25  75  25  25]
  [  0  75  75  75  75]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here