# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here

import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here

print(np.version.version)

1.19.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1

a = np.random.random(size = (2,3,5))


In [4]:
# Method 2

In [5]:
# Method 3

#### 4. Print *a*.


In [6]:
# your code here

print(a)

[[[0.05961658 0.10776828 0.97183793 0.38055463 0.73608566]
  [0.54278794 0.18848332 0.39022548 0.07129026 0.93194385]
  [0.11198383 0.01288698 0.62214286 0.12066881 0.73019833]]

 [[0.07411777 0.8200664  0.13697736 0.9810925  0.72660473]
  [0.04076914 0.05709989 0.38686838 0.74405086 0.82718655]
  [0.17742751 0.18209001 0.28140753 0.69319298 0.8098939 ]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here

b = np.ones(shape = (5,2,3), dtype = int)

#### 6. Print *b*.


In [8]:
# your code here

print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here

#2*3*5 == 5*2*3

(b.size) == (a.size)

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here

a_b = sum(a + b)

print(a_b)

#I cant add A and B, the shapes are different 

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [ ]:
# your code here

c = b.reshape((2,3,5))
print(c)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [ ]:
# your code/answer here

d = a + c

print(d)

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [ ]:
# your code/answer here
print(a)
print('\n')
print('\n')
print(d)

#Array D is the sum of the values in array a with values of c

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [ ]:
# your code here

e = a*c
print(e)

#### 13. Does *e* equal to *a*? Why or why not?


In [ ]:
# your code/answer here

e == a

#they are the same, because in array C we just reshape the array B, which values were 1

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [ ]:
# your code here

print('The max in array d is:', (d.max()))
print('The min in array d is:', (d.min()))
print('The mean in array d is:', (d.mean()))

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [ ]:
# your code here

f = np.empty((2,3,5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here

# fazer um for loop para 2, um para 3, e um para 5. as parametrizaçoes de if ficam na 5 usando os for de cima.

dmin = d.min()
dmax = d.max()
dmean = d.mean()

for arr in range(2):
    for row in range(3):
        for num in range(5):
            if(dmin < d[arr][row][num] < dmean):
                f[arr][row][num] = 25
            if(dmean < d[arr][row][num] < dmax):
                f[arr][row][num] = 75
            if(d[arr][row][num] == dmean):
                f[arr][row][num] = 50
            if(d[arr][row][num] == dmin):
                f[arr][row][num] = 0 
            if(d[arr][row][num] == dmax):
                f[arr][row][num] = 100


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
print(d)

In [ ]:
# your code here

print(f)

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here