# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [135]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [136]:
# your code here
np.__version__

'1.19.1'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [137]:
# Method 1
a = np.random.random((2,3,5)) #This will create an array of random numbers in the range 0.0 up to but not including 1.0. This means that the range can included anything from 0.0 up to the largest float that is less than 1 



In [138]:
# Method 2
np.random.randint(10, size=(2,3,5))  #The randint function creates an array of integers. In this case, it creates values in the range [0,10), that is integers from 0 up to but not including 10. The value 10 could be something else.

array([[[0, 8, 1, 0, 5],
        [8, 8, 9, 5, 9],
        [1, 7, 4, 7, 0]],

       [[7, 3, 0, 0, 9],
        [5, 3, 4, 8, 3],
        [1, 9, 2, 9, 2]]])

In [139]:
# Method 3
np.random.standard_normal((2,3,5)) #This function creates values using the standard Normal distribution

array([[[-0.82875695, -0.87989041, -1.16533414,  0.16353425,
          0.11072276],
        [-0.14969245,  1.74549682, -2.15764131,  0.64297729,
         -0.8430509 ],
        [-2.71115847,  0.3835615 , -0.85225524,  1.09929146,
         -0.45974331]],

       [[ 0.98602153, -0.0694877 ,  0.59090508, -2.09282957,
         -0.84789807],
        [-0.45279619,  0.89407639, -0.81642417,  0.45318482,
          2.09654833],
        [ 2.08527007, -1.00678076,  0.12216976, -2.17045422,
          0.56613344]]])

#### 4. Print *a*.


In [140]:
# your code here
print(a)


[[[0.86269426 0.40523701 0.37537687 0.47972061 0.81979094]
  [0.38372989 0.92316687 0.99908481 0.13869463 0.00987633]
  [0.2783546  0.99833476 0.73288141 0.71185812 0.12649989]]

 [[0.73765362 0.29665452 0.40753774 0.87932544 0.63038449]
  [0.2000198  0.43747137 0.40609367 0.36018807 0.38064085]
  [0.8114271  0.90167628 0.02176153 0.39701081 0.7740511 ]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [141]:
# your code here
b = np.full((5,2,3), 1)

#### 6. Print *b*.


In [142]:
# your code here
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [143]:
# your code here
a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [144]:
# your answer here
#No, np.add() function is used when we want to compute the sum of two arrays. But If shape of two arrays are not same, a.shape != b.shape, they must be in a common shape which may be the shape of one or the other.


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [145]:
# your code here
c = np.transpose(b, (1, 2, 0))
c.shape

(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [146]:
# your code/answer here
d = np.add(c,a) #It worked because c.shape == a.shape
c.shape == a.shape

True

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [147]:
# your code/answer here
print(a)
print(d)

# each value in table "a" is 1 unit larger than each value in table "d" comparing according to the position of the numbers.




[[[0.86269426 0.40523701 0.37537687 0.47972061 0.81979094]
  [0.38372989 0.92316687 0.99908481 0.13869463 0.00987633]
  [0.2783546  0.99833476 0.73288141 0.71185812 0.12649989]]

 [[0.73765362 0.29665452 0.40753774 0.87932544 0.63038449]
  [0.2000198  0.43747137 0.40609367 0.36018807 0.38064085]
  [0.8114271  0.90167628 0.02176153 0.39701081 0.7740511 ]]]
[[[1.86269426 1.40523701 1.37537687 1.47972061 1.81979094]
  [1.38372989 1.92316687 1.99908481 1.13869463 1.00987633]
  [1.2783546  1.99833476 1.73288141 1.71185812 1.12649989]]

 [[1.73765362 1.29665452 1.40753774 1.87932544 1.63038449]
  [1.2000198  1.43747137 1.40609367 1.36018807 1.38064085]
  [1.8114271  1.90167628 1.02176153 1.39701081 1.7740511 ]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [148]:
# your code here
e = np.multiply(a,c)
#print(c)
e

array([[[0.86269426, 0.40523701, 0.37537687, 0.47972061, 0.81979094],
        [0.38372989, 0.92316687, 0.99908481, 0.13869463, 0.00987633],
        [0.2783546 , 0.99833476, 0.73288141, 0.71185812, 0.12649989]],

       [[0.73765362, 0.29665452, 0.40753774, 0.87932544, 0.63038449],
        [0.2000198 , 0.43747137, 0.40609367, 0.36018807, 0.38064085],
        [0.8114271 , 0.90167628, 0.02176153, 0.39701081, 0.7740511 ]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [149]:
# your code/answer here
print(a == e)

#print(a.shape)          #yes, because they have the same shape, size and same elements value inside the arrays. "e" resultes from a multiplication between a and c, being c an array with all elements equal 1.
#print(e.shape
#print(a.size)
#print(b.size)

[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [150]:
# your code here
d_mean = np.mean(d)
d_max = np.max(d)
d_min = np.min(d)


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [151]:
# your code here
f = np.empty([2,3,5])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [152]:
# your code here

#f1 = [[[25 if d_min<item<d_mean else 75 if d_mean<item<d_max else 0 if item == d_min else 100 for item in in_list] for in_list in out_list] for out_list in d]

f1 = 25 * (d > d_min) * (d < d_mean) + 75 * (d < d_max) * (d > d_mean) + 0 * (d == d_min) + 100 * (d == d_max)
 

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [153]:
# your code here
print(d)
f1


[[[1.86269426 1.40523701 1.37537687 1.47972061 1.81979094]
  [1.38372989 1.92316687 1.99908481 1.13869463 1.00987633]
  [1.2783546  1.99833476 1.73288141 1.71185812 1.12649989]]

 [[1.73765362 1.29665452 1.40753774 1.87932544 1.63038449]
  [1.2000198  1.43747137 1.40609367 1.36018807 1.38064085]
  [1.8114271  1.90167628 1.02176153 1.39701081 1.7740511 ]]]


array([[[ 75,  25,  25,  25,  75],
        [ 25,  75, 100,  25,   0],
        [ 25,  75,  75,  75,  25]],

       [[ 75,  25,  25,  75,  75],
        [ 25,  25,  25,  25,  25],
        [ 75,  75,  25,  25,  75]]])

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.