# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here

import numpy as np

#### 2. Print your NumPy version.

In [44]:
# your code here

#Option 1
print(np.__version__)

#Option 2
np.version.version

1.21.2


'1.21.2'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [45]:
# Method 1

#We created an array, of random values - which range is by default (0-1.0), of 2 groups, of 3 rows and 5 columns

a = np.random.random(size=(2,3,5))

In [46]:
# Method 2
#As opposed to np.random.random, in np.random.randit we must specify the range (0, 10) in the first arguments 
#of the function

np.random.randint(0, 10, size=(2,3,5))


array([[[0, 3, 9, 9, 8],
        [5, 5, 6, 0, 5],
        [9, 7, 2, 8, 0]],

       [[7, 8, 5, 1, 9],
        [6, 8, 4, 6, 0],
        [0, 4, 7, 1, 4]]])

In [47]:
# Method 3

np.empty((2,3,5))


array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 4. Print *a*.


In [48]:
# your code here

print(a)

[[[0.1195979  0.91269041 0.51031225 0.67547521 0.82040641]
  [0.5562328  0.82437856 0.29239371 0.3520462  0.7648831 ]
  [0.11249437 0.92722868 0.44864088 0.80492877 0.93996494]]

 [[0.02296741 0.92902342 0.42622173 0.46975591 0.66061059]
  [0.88140239 0.62741043 0.48837715 0.3262053  0.63657154]
  [0.68451055 0.52759617 0.22261142 0.46338941 0.8823581 ]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [49]:
# your code here

b = np.ones(shape = (5,2,3), dtype = int)

#### 6. Print *b*.


In [50]:
# your code here

print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [53]:
# your code here

#1. Print the shape of a and b
print(a.shape)
print(b.shape)



#2. Compare the size of a and b

a.shape == b.shape

(2, 3, 5)
(5, 2, 3)


False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [54]:
# your answer here

a + b

#We cannot add a and b because our arrays have different shapes.

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [62]:
# your code here

#We want to transpose b into c and create a structure of 2 groups, 3 rows and 5 columns. In order to do so, we need
#to invert the index of each dimension. 

##b has a shape of (5,2,3), which means that in our tuple, 5 is 0 index, 2 is 1 index, and 3 is 2 index.
##In order to get c with a shape of (2,3,5), we need to create a tuple with our original 2 in 0 index, our original
##3 in 1 index and our original 5 in 2 index. 

c = np.transpose(b, (1, 2, 0))

c


array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [63]:
c.shape

(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [65]:
# your code/answer here

d = a + c

d

#It works because a and c have the same shape.

array([[[1.1195979 , 1.91269041, 1.51031225, 1.67547521, 1.82040641],
        [1.5562328 , 1.82437856, 1.29239371, 1.3520462 , 1.7648831 ],
        [1.11249437, 1.92722868, 1.44864088, 1.80492877, 1.93996494]],

       [[1.02296741, 1.92902342, 1.42622173, 1.46975591, 1.66061059],
        [1.88140239, 1.62741043, 1.48837715, 1.3262053 , 1.63657154],
        [1.68451055, 1.52759617, 1.22261142, 1.46338941, 1.8823581 ]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [66]:
# your code/answer here

print(a)

[[[0.1195979  0.91269041 0.51031225 0.67547521 0.82040641]
  [0.5562328  0.82437856 0.29239371 0.3520462  0.7648831 ]
  [0.11249437 0.92722868 0.44864088 0.80492877 0.93996494]]

 [[0.02296741 0.92902342 0.42622173 0.46975591 0.66061059]
  [0.88140239 0.62741043 0.48837715 0.3262053  0.63657154]
  [0.68451055 0.52759617 0.22261142 0.46338941 0.8823581 ]]]


In [67]:
print(d)

#Every element in d equals to the corresponding summed element of a + c:
##The values of a are between 0 and 1.0, 1.0 excluded
##The value of c is 1 always

[[[1.1195979  1.91269041 1.51031225 1.67547521 1.82040641]
  [1.5562328  1.82437856 1.29239371 1.3520462  1.7648831 ]
  [1.11249437 1.92722868 1.44864088 1.80492877 1.93996494]]

 [[1.02296741 1.92902342 1.42622173 1.46975591 1.66061059]
  [1.88140239 1.62741043 1.48837715 1.3262053  1.63657154]
  [1.68451055 1.52759617 1.22261142 1.46338941 1.8823581 ]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [69]:
# your code here

e = a * c

print(e)

[[[0.1195979  0.91269041 0.51031225 0.67547521 0.82040641]
  [0.5562328  0.82437856 0.29239371 0.3520462  0.7648831 ]
  [0.11249437 0.92722868 0.44864088 0.80492877 0.93996494]]

 [[0.02296741 0.92902342 0.42622173 0.46975591 0.66061059]
  [0.88140239 0.62741043 0.48837715 0.3262053  0.63657154]
  [0.68451055 0.52759617 0.22261142 0.46338941 0.8823581 ]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [70]:
# your code/answer here

e == a

#e equals to a because, because c = 1, and a*1 = a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [73]:
# your code here

#1. Maximum of d

d_max = d.max()
print(d_max)


1.939964942951444


In [74]:
#2. Minimum of d

d_min = d.min()
print(d_min)

1.0229674125601935


In [75]:
#3. Mean of d

d_mean = d.mean()
print(d_mean)

1.5770228576031116


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [77]:
# your code here

#1. We create an empty array, called f
f = np.empty((2,3,5))
print(f)


[[[0.1195979  0.91269041 0.51031225 0.67547521 0.82040641]
  [0.5562328  0.82437856 0.29239371 0.3520462  0.7648831 ]
  [0.11249437 0.92722868 0.44864088 0.80492877 0.93996494]]

 [[0.02296741 0.92902342 0.42622173 0.46975591 0.66061059]
  [0.88140239 0.62741043 0.48837715 0.3262053  0.63657154]
  [0.68451055 0.52759617 0.22261142 0.46338941 0.8823581 ]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [79]:
# your code here

for x in range(d.shape[0]):
  for y in range(d.shape[1]):
    for z in range(d.shape[2]):
      if d[x,y,z] > d_min and d[x,y,z] < d_mean:
        f[x,y,z] = 25
      if d[x,y,z] == d_min:
        f[x,y,z] = 0
      if d[x,y,z] == d_mean:
        f[x,y,z] = 50
      if d[x,y,z] > d_mean and d[x,y,z] < d_max:
        f[x,y,z] = 75
      if d[x,y,z] == d_max:
        f[x,y,z] = 100

f

array([[[ 25.,  75.,  25.,  75.,  75.],
        [ 25.,  75.,  25.,  25.,  75.],
        [ 25.,  75.,  25.,  75., 100.]],

       [[  0.,  75.,  25.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  75.],
        [ 75.,  25.,  25.,  25.,  75.]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [82]:
# your code here

print(d)

print(f)

[[[1.1195979  1.91269041 1.51031225 1.67547521 1.82040641]
  [1.5562328  1.82437856 1.29239371 1.3520462  1.7648831 ]
  [1.11249437 1.92722868 1.44864088 1.80492877 1.93996494]]

 [[1.02296741 1.92902342 1.42622173 1.46975591 1.66061059]
  [1.88140239 1.62741043 1.48837715 1.3262053  1.63657154]
  [1.68451055 1.52759617 1.22261142 1.46338941 1.8823581 ]]]
[[[ 25.  75.  25.  75.  75.]
  [ 25.  75.  25.  25.  75.]
  [ 25.  75.  25.  75. 100.]]

 [[  0.  75.  25.  25.  75.]
  [ 75.  75.  25.  25.  75.]
  [ 75.  25.  25.  25.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [90]:
# your code here

# A is equal to 0
# B is equal to 25
# C is equal to 50
# D is equal to 75
# E is equal to 100

f = np.empty(shape=d.shape, dtype = str)

for x in range(d.shape[0]):
  for y in range(d.shape[1]):
    for z in range(d.shape[2]):
      if d[x,y,z] > d_min and d[x,y,z] < d_mean:
        f[x,y,z] = 'B'
      if d[x,y,z] == d_min:
        f[x,y,z] = 'A'
      if d[x,y,z] == d_mean:
        f[x,y,z] = 'C'
      if d[x,y,z] > d_mean and d[x,y,z] < d_max:
        f[x,y,z] = 'D'
      if d[x,y,z] == d_max:
        f[x,y,z] = 'E'
        
f

array([[['B', 'D', 'B', 'D', 'D'],
        ['B', 'D', 'B', 'B', 'D'],
        ['B', 'D', 'B', 'D', 'E']],

       [['A', 'D', 'B', 'B', 'D'],
        ['D', 'D', 'B', 'B', 'D'],
        ['D', 'B', 'B', 'B', 'D']]], dtype='<U1')