# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [166]:
import numpy as np

#### 2. Print your NumPy version.

In [167]:
np.version.version

'1.21.5'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [168]:
a = np.random.random(size=(2,3,5))

In [169]:
a = np.random.randint(4,size=(2,3,5))

In [170]:
a = np.random.uniform(low=0, high=10, size=(2,3,5))

#### 4. Print *a*.


In [171]:
print(a)

[[[3.65460896 1.32088222 4.50002897 1.41835817 2.83635066]
  [0.24429129 8.92311661 1.80790442 9.14966992 1.56818779]
  [3.70079445 3.81193572 5.47208707 8.18949785 4.52887066]]

 [[9.15505023 0.83904687 2.14167211 2.92428788 5.22334731]
  [7.24886796 0.97497731 7.25998926 3.8398516  1.60053629]
  [2.03854993 8.77727627 2.83782187 2.08392737 3.84577399]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [172]:
b = np.ones(shape=(5,2,3)) 

#### 6. Print *b*.


In [173]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [174]:
a.shape == b.shape

False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [175]:
# no because they do not have the same shape

print(a + b)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [176]:
c = b.transpose()
print(c.shape) # since transposing b results in 3x2x5 and not 2x3x5 im changing b so i can continue the lab

(3, 2, 5)


In [177]:
b = np.ones(shape=(5,3,2)) 
c = b.transpose()
print(c.shape)

(2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [178]:
d = a + c # because they have the same shape

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [179]:
print("a = ",a,"\n","\n","d = ",d) # values from d are equal to values from a + 1

a =  [[[3.65460896 1.32088222 4.50002897 1.41835817 2.83635066]
  [0.24429129 8.92311661 1.80790442 9.14966992 1.56818779]
  [3.70079445 3.81193572 5.47208707 8.18949785 4.52887066]]

 [[9.15505023 0.83904687 2.14167211 2.92428788 5.22334731]
  [7.24886796 0.97497731 7.25998926 3.8398516  1.60053629]
  [2.03854993 8.77727627 2.83782187 2.08392737 3.84577399]]] 
 
 d =  [[[ 4.65460896  2.32088222  5.50002897  2.41835817  3.83635066]
  [ 1.24429129  9.92311661  2.80790442 10.14966992  2.56818779]
  [ 4.70079445  4.81193572  6.47208707  9.18949785  5.52887066]]

 [[10.15505023  1.83904687  3.14167211  3.92428788  6.22334731]
  [ 8.24886796  1.97497731  8.25998926  4.8398516   2.60053629]
  [ 3.03854993  9.77727627  3.83782187  3.08392737  4.84577399]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [180]:
e = a * c

#### 13. Does *e* equal to *a*? Why or why not?


In [181]:
e == a # because c is being multiplied by 1

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [182]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

print(d_max,d_min,d_mean)

10.155050229322814 1.2442912919556928 5.063918699924077


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [183]:
f = np.empty_like(d)

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [189]:
f[(d == d.min())] = 0
f[(d > d.min()) & (d < d.mean())] = 25
f[(d == d.mean())] = 50
f[(d > d.mean()) & (d < d.max())] = 75
f[(d == d.max())] = 100

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [191]:
print(d, "\n\n\n",f)

[[[ 4.65460896  2.32088222  5.50002897  2.41835817  3.83635066]
  [ 1.24429129  9.92311661  2.80790442 10.14966992  2.56818779]
  [ 4.70079445  4.81193572  6.47208707  9.18949785  5.52887066]]

 [[10.15505023  1.83904687  3.14167211  3.92428788  6.22334731]
  [ 8.24886796  1.97497731  8.25998926  4.8398516   2.60053629]
  [ 3.03854993  9.77727627  3.83782187  3.08392737  4.84577399]]] 


 [[[ 25.  25.  75.  25.  25.]
  [  0.  75.  25.  75.  25.]
  [ 25.  25.  75.  75.  75.]]

 [[100.  25.  25.  25.  75.]
  [ 75.  25.  75.  25.  25.]
  [ 25.  75.  25.  25.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [207]:
g = f.astype(str)
h = np.empty_like(g)

h[(g == "0.0")] = "A"
h[(g == "25.0")] = "B"
h[(g == "50.0")] = "C"
h[(g == "75.0")] = "D"
h[(g == "100.0")] = "E"

print(h)

[[['B' 'B' 'D' 'B' 'B']
  ['A' 'D' 'B' 'D' 'B']
  ['B' 'B' 'D' 'D' 'D']]

 [['E' 'B' 'B' 'B' 'D']
  ['D' 'B' 'D' 'B' 'B']
  ['B' 'D' 'B' 'B' 'B']]]
