# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
np.__version__

'1.20.3'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a = np.random.random(size =(2,3,5))
a

array([[[0.78917057, 0.72776751, 0.38574475, 0.34578259, 0.16711561],
        [0.87780448, 0.48550729, 0.75731685, 0.69283172, 0.59813658],
        [0.36573392, 0.96806535, 0.61794327, 0.16516799, 0.15350497]],

       [[0.36719095, 0.73682834, 0.81086404, 0.93168058, 0.76506046],
        [0.01195392, 0.69987299, 0.85849873, 0.84643551, 0.0766242 ],
        [0.00921332, 0.32827608, 0.81099497, 0.35438328, 0.76695139]]])

In [4]:
# Method 2
a = np.random.randint(100, size=(2,3, 5))
a

array([[[60, 93, 92, 37, 90],
        [27, 48, 29,  6, 63],
        [23, 98, 10, 75, 73]],

       [[44,  8, 74, 41,  8],
        [39, 25, 16, 90, 34],
        [44,  3, 55, 68, 46]]])

In [5]:
# Method 3
a=np.random.random_sample((2,3,5))
a

array([[[0.17414738, 0.96398478, 0.00427823, 0.61376339, 0.74519894],
        [0.6884615 , 0.29248112, 0.02226616, 0.93656423, 0.06743907],
        [0.77932254, 0.80178279, 0.38295666, 0.24819733, 0.02222811]],

       [[0.30842358, 0.8524591 , 0.10480512, 0.64130288, 0.3435161 ],
        [0.09683002, 0.64596585, 0.67274443, 0.91593005, 0.31344192],
        [0.30796629, 0.1767896 , 0.41718149, 0.0342524 , 0.59654723]]])

#### 4. Print *a*.


In [6]:
# your code here
a

array([[[0.17414738, 0.96398478, 0.00427823, 0.61376339, 0.74519894],
        [0.6884615 , 0.29248112, 0.02226616, 0.93656423, 0.06743907],
        [0.77932254, 0.80178279, 0.38295666, 0.24819733, 0.02222811]],

       [[0.30842358, 0.8524591 , 0.10480512, 0.64130288, 0.3435161 ],
        [0.09683002, 0.64596585, 0.67274443, 0.91593005, 0.31344192],
        [0.30796629, 0.1767896 , 0.41718149, 0.0342524 , 0.59654723]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here
b = np.ones((5,2,3),dtype = int)

#### 6. Print *b*.


In [8]:
# your code here
b

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here
a.shape == b.shape

False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here
print(a.shape)
print(b.shape)
#It is possible (AFTER RESHAPING) because the result of the multiplication
##of the shape is equal in both

resh_b = b.reshape(2,3,5)
a + resh_b

(2, 3, 5)
(5, 2, 3)


array([[[1.17414738, 1.96398478, 1.00427823, 1.61376339, 1.74519894],
        [1.6884615 , 1.29248112, 1.02226616, 1.93656423, 1.06743907],
        [1.77932254, 1.80178279, 1.38295666, 1.24819733, 1.02222811]],

       [[1.30842358, 1.8524591 , 1.10480512, 1.64130288, 1.3435161 ],
        [1.09683002, 1.64596585, 1.67274443, 1.91593005, 1.31344192],
        [1.30796629, 1.1767896 , 1.41718149, 1.0342524 , 1.59654723]]])

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here
#c = b.transpose()     ##not transposing to the same shape of a
                       ##transposing from (5, 2, 3) to (3, 2, 5)
c = b.reshape(2,3,5)
c

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# your code/answer here
d = a + c
d

array([[[1.17414738, 1.96398478, 1.00427823, 1.61376339, 1.74519894],
        [1.6884615 , 1.29248112, 1.02226616, 1.93656423, 1.06743907],
        [1.77932254, 1.80178279, 1.38295666, 1.24819733, 1.02222811]],

       [[1.30842358, 1.8524591 , 1.10480512, 1.64130288, 1.3435161 ],
        [1.09683002, 1.64596585, 1.67274443, 1.91593005, 1.31344192],
        [1.30796629, 1.1767896 , 1.41718149, 1.0342524 , 1.59654723]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# your code/answer here
print(a)
print(d)     ##The array d has the a values plus 1

[[[0.17414738 0.96398478 0.00427823 0.61376339 0.74519894]
  [0.6884615  0.29248112 0.02226616 0.93656423 0.06743907]
  [0.77932254 0.80178279 0.38295666 0.24819733 0.02222811]]

 [[0.30842358 0.8524591  0.10480512 0.64130288 0.3435161 ]
  [0.09683002 0.64596585 0.67274443 0.91593005 0.31344192]
  [0.30796629 0.1767896  0.41718149 0.0342524  0.59654723]]]
[[[1.17414738 1.96398478 1.00427823 1.61376339 1.74519894]
  [1.6884615  1.29248112 1.02226616 1.93656423 1.06743907]
  [1.77932254 1.80178279 1.38295666 1.24819733 1.02222811]]

 [[1.30842358 1.8524591  1.10480512 1.64130288 1.3435161 ]
  [1.09683002 1.64596585 1.67274443 1.91593005 1.31344192]
  [1.30796629 1.1767896  1.41718149 1.0342524  1.59654723]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
# your code here
e = a * c
e

array([[[0.17414738, 0.96398478, 0.00427823, 0.61376339, 0.74519894],
        [0.6884615 , 0.29248112, 0.02226616, 0.93656423, 0.06743907],
        [0.77932254, 0.80178279, 0.38295666, 0.24819733, 0.02222811]],

       [[0.30842358, 0.8524591 , 0.10480512, 0.64130288, 0.3435161 ],
        [0.09683002, 0.64596585, 0.67274443, 0.91593005, 0.31344192],
        [0.30796629, 0.1767896 , 0.41718149, 0.0342524 , 0.59654723]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
# your code/answer here
e == a
#yes because the values in e are the multiplication of a values by 1

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
# your code here
d_max = np.max(d)
print(f'd_max is {d_max}')
d_min = np.min(d)
print(f'd_min is {d_min}')
d_mean = np.mean(d)
print(f'd_mean is {d_mean}')

d_max is 1.9639847765850256
d_min is 1.0042782305221736
d_mean is 1.439040943263058


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [17]:
# your code here
f = np.empty(shape=(2,3,5))
f

array([[[0.17414738, 0.96398478, 0.00427823, 0.61376339, 0.74519894],
        [0.6884615 , 0.29248112, 0.02226616, 0.93656423, 0.06743907],
        [0.77932254, 0.80178279, 0.38295666, 0.24819733, 0.02222811]],

       [[0.30842358, 0.8524591 , 0.10480512, 0.64130288, 0.3435161 ],
        [0.09683002, 0.64596585, 0.67274443, 0.91593005, 0.31344192],
        [0.30796629, 0.1767896 , 0.41718149, 0.0342524 , 0.59654723]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [19]:
# your code here
print(d)
#d_max is 1.993729308044249
#d_min is 1.0117399139742211
#d_mean is 1.482211832297412
f = []
for el in np.nditer(d):      #method for iterating an array
    if d_min < el < d_mean:
        f += [25]
    if d_mean < el < d_max:
        f += [75]
    if el == d_mean:
        f += [50]
    if el == d_min:
        f += [0]
    if el == d_max:
        f += [100]

f=np.reshape(f, (2,3,5))
f

[[[1.17414738 1.96398478 1.00427823 1.61376339 1.74519894]
  [1.6884615  1.29248112 1.02226616 1.93656423 1.06743907]
  [1.77932254 1.80178279 1.38295666 1.24819733 1.02222811]]

 [[1.30842358 1.8524591  1.10480512 1.64130288 1.3435161 ]
  [1.09683002 1.64596585 1.67274443 1.91593005 1.31344192]
  [1.30796629 1.1767896  1.41718149 1.0342524  1.59654723]]]


array([[[ 25, 100,   0,  75,  75],
        [ 75,  25,  25,  75,  25],
        [ 75,  75,  25,  25,  25]],

       [[ 25,  75,  25,  75,  25],
        [ 25,  75,  75,  75,  25],
        [ 25,  25,  25,  25,  75]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [20]:
# your code here
print(d)
print(f)

[[[1.17414738 1.96398478 1.00427823 1.61376339 1.74519894]
  [1.6884615  1.29248112 1.02226616 1.93656423 1.06743907]
  [1.77932254 1.80178279 1.38295666 1.24819733 1.02222811]]

 [[1.30842358 1.8524591  1.10480512 1.64130288 1.3435161 ]
  [1.09683002 1.64596585 1.67274443 1.91593005 1.31344192]
  [1.30796629 1.1767896  1.41718149 1.0342524  1.59654723]]]
[[[ 25 100   0  75  75]
  [ 75  25  25  75  25]
  [ 75  75  25  25  25]]

 [[ 25  75  25  75  25]
  [ 25  75  75  75  25]
  [ 25  25  25  25  75]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [22]:
# your code here
f = []
for el in np.nditer(d):      #method for iterating an array
    if d_min < el < d_mean:
        f += ['A']
    if d_mean < el < d_max:
        f += ['B']
    if el == d_mean:
        f += ['C']
    if el == d_min:
        f += ['D']
    if el == d_max:
        f += ['E']

f=np.reshape(f, (2,3,5))
f

array([[['A', 'E', 'D', 'B', 'B'],
        ['B', 'A', 'A', 'B', 'A'],
        ['B', 'B', 'A', 'A', 'A']],

       [['A', 'B', 'A', 'B', 'A'],
        ['A', 'B', 'B', 'B', 'A'],
        ['A', 'A', 'A', 'A', 'B']]], dtype='<U1')