# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [4]:
import numpy as np

#### 2. Print your NumPy version.

In [5]:
print(np.__version__)

1.23.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [51]:
# syntax: random.randint(low, high=None, size=None, dtype=int); if high is None (the default), then results are from [0, low)
# integers, from "discrete uniform" distribution, [low, high)

a = np.random.randint(100, size = (2, 3, 5))

In [52]:
# syntax: random.rand(d0, d1, ..., dn)
# floats, from uniform distribution, [0, 1)

a = np.random.rand(2, 3, 5)

In [53]:
# syntax: random.randn(d0, d1, ..., dn)
# floats, from "standard normal" distribution

a = np.random.randn(2, 3, 5)

In [54]:
# syntax: random.random_sample(size=None)
# floats, "continuous uniform" distribtuion, [0.0, 1.0)

a = np.random.random_sample(size = (2, 3, 5))

In [55]:
# syntax: random.random(size=None)
# floats, [0.0, 1.0)

a = np.random.random(size = (2, 3, 5))

#### 4. Print *a*.


In [56]:
print(a)

[[[0.41685763 0.86218193 0.40424214 0.65916744 0.38822751]
  [0.40456356 0.6913081  0.72844646 0.045383   0.50828095]
  [0.376908   0.09780231 0.83434537 0.75355341 0.95188708]]

 [[0.46131671 0.32621905 0.89250888 0.74166322 0.90079063]
  [0.78921746 0.42424457 0.9193221  0.60638787 0.24101044]
  [0.41183555 0.55754807 0.38693262 0.37329723 0.90172869]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [57]:
# syntax: ones(shape, dtype=None, order="C", *, like=None)

b = np.ones(shape = (5, 2, 3), dtype = int)

#### 6. Print *b*.


In [58]:
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [60]:
a.size == b.size

# yes, a and b have the same size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [61]:
a + b

# no you cannot add a and b because they have a different shape

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [85]:
# syntax: transpose(a, axes=None)
# axes: tuple or list of ints, optional
# if specified, it must be a tuple or list which contains a permutation of [0,1,…,N-1] where N is the number of axes of a
# The i’th axis of the returned array will correspond to the axis numbered axes[i] of the input

c = np.transpose(b, axes=[1, 2, 0]) # i could also do c = b.reshape(a.shape)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [73]:
d = a + c

# it works because a and c have the same shape

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [77]:
print(a, "\n \n")

print(d)

# the values of d differ by 1 as compared to the values of a (as d is the product of addition of c -only ones- to a)

[[[0.41685763 0.86218193 0.40424214 0.65916744 0.38822751]
  [0.40456356 0.6913081  0.72844646 0.045383   0.50828095]
  [0.376908   0.09780231 0.83434537 0.75355341 0.95188708]]

 [[0.46131671 0.32621905 0.89250888 0.74166322 0.90079063]
  [0.78921746 0.42424457 0.9193221  0.60638787 0.24101044]
  [0.41183555 0.55754807 0.38693262 0.37329723 0.90172869]]] 
 

[[[1.41685763 1.86218193 1.40424214 1.65916744 1.38822751]
  [1.40456356 1.6913081  1.72844646 1.045383   1.50828095]
  [1.376908   1.09780231 1.83434537 1.75355341 1.95188708]]

 [[1.46131671 1.32621905 1.89250888 1.74166322 1.90079063]
  [1.78921746 1.42424457 1.9193221  1.60638787 1.24101044]
  [1.41183555 1.55754807 1.38693262 1.37329723 1.90172869]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [78]:
e = a * c

#### 13. Does *e* equal to *a*? Why or why not?


In [80]:
e == a

# it does because c contains only ones

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [81]:
d_max = d.max()

d_min = d.min()

d_mean = d.mean()

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [84]:
# syntax empty(shape, dtype=float, order='C', *, like=None)
# return a new array of given shape and type, without initializing entries

f = np.empty((d.shape))

(2, 3, 5)

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [86]:
f[(d > d_min) & (d < d_mean)] = 25

f[(d > d_mean) & (d < d_max)] = 75

f[d == d_mean] = 50

f[d == d_min] = 0

f[d == d_max] = 100

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [88]:
print(d, "\n \n")

print(f)

# yes

[[[1.41685763 1.86218193 1.40424214 1.65916744 1.38822751]
  [1.40456356 1.6913081  1.72844646 1.045383   1.50828095]
  [1.376908   1.09780231 1.83434537 1.75355341 1.95188708]]

 [[1.46131671 1.32621905 1.89250888 1.74166322 1.90079063]
  [1.78921746 1.42424457 1.9193221  1.60638787 1.24101044]
  [1.41183555 1.55754807 1.38693262 1.37329723 1.90172869]]] 
 

[[[ 25.  75.  25.  75.  25.]
  [ 25.  75.  75.   0.  25.]
  [ 25.  25.  75.  75. 100.]]

 [[ 25.  25.  75.  75.  75.]
  [ 75.  25.  75.  75.  25.]
  [ 25.  25.  25.  25.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [90]:
f = f.astype(str)

f[(d > d_min) & (d < d_mean)] = "B"
f[(d > d_mean) & (d < d_max)] = "D"
f[d == d_mean] = "C"
f[d == d_min] = "A"
f[d == d_max] = "E"

print(f)

[[['B' 'D' 'B' 'D' 'B']
  ['B' 'D' 'D' 'A' 'B']
  ['B' 'B' 'D' 'D' 'E']]

 [['B' 'B' 'D' 'D' 'D']
  ['D' 'B' 'D' 'D' 'B']
  ['B' 'B' 'B' 'B' 'D']]]
