# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [4]:
# your code here
print(np.__version__)

1.18.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [8]:
# Method 1
a = np.random.random((2,3,5))

In [10]:
# Method 2
a= np.zeros((2,3,5))

In [13]:
# Method 3
a = np.random.randint(10, size=(2,3,5))

#### 4. Print *a*.


In [14]:
# your code here
print(a)



[[[4 1 9 0 0]
  [9 7 6 5 6]
  [7 1 5 3 3]]

 [[7 9 9 2 4]
  [0 6 0 3 0]
  [8 7 6 5 7]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [15]:
# your code here
b = np.ones((5,2,3))


#### 6. Print *b*.


In [16]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [19]:
# your code here
a_size = a.size
b_size = b.size
print(a_size == b_size)

True


#### 8. Are you able to add *a* and *b*? Why or why not?


In [ ]:
# your answer here
#Although they have the same size, they don't have the same shape.

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [24]:
# your code here

c = b.reshape(2,3,5)
print(new_b)
c.shape

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [25]:
# your code/answer here

d = a + c
print(d)

[[[ 5.  2. 10.  1.  1.]
  [10.  8.  7.  6.  7.]
  [ 8.  2.  6.  4.  4.]]

 [[ 8. 10. 10.  3.  5.]
  [ 1.  7.  1.  4.  1.]
  [ 9.  8.  7.  6.  8.]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [29]:
# your code/answer here
print(a,"\n\n",d)

[[[4 1 9 0 0]
  [9 7 6 5 6]
  [7 1 5 3 3]]

 [[7 9 9 2 4]
  [0 6 0 3 0]
  [8 7 6 5 7]]] 

 [[[ 5.  2. 10.  1.  1.]
  [10.  8.  7.  6.  7.]
  [ 8.  2.  6.  4.  4.]]

 [[ 8. 10. 10.  3.  5.]
  [ 1.  7.  1.  4.  1.]
  [ 9.  8.  7.  6.  8.]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [30]:
# your code here
e = a*c

#### 13. Does *e* equal to *a*? Why or why not?


In [31]:
# your code/answer here
e == a

#Its equal because we are multiplying by one.

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [57]:
# your code here
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

print(d_max,d_min,d_mean)

1.97066381 1.00656599 1.6175069086666667


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [36]:
# your code here
f = np.empty((2,3,5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [61]:
for group in range(2):
    for row in range(3):
        for column in range(5):
            if (d[group][row][column] > d_min) & (d[group][row][column] < d_mean):
                f[group][row][column] = 25
            elif (d[group][row][column] <= d_min):
                f[group][row][column] = 0
            elif (d[group][row][column] == d_mean):
                  f[group][row][column] = 50
            elif(d[group][row][column] >d_mean) &(d[group][row][column] < d_max):
                  f[group][row][column] = 75
            elif (d[group][row][column] >= d_max):
                f[group][row][column] = 100
                    
                    


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [62]:
# your code here
d = np.array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

print(f)

[[[ 75.  75.  75.  25.  75.]
  [ 75.  75.  25.  25.  25.]
  [ 75.  25.  75.  75.  75.]]

 [[ 25.  25.  25.  25. 100.]
  [ 75.  75.  75.  75.  75.]
  [ 25.  75.   0.  75.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [70]:
# your code here
letter_array = np.empty((2,3,5), dtype = str)
for group in range(2):
    for row in range(3):
        for column in range(5):
            if f[group][row][column] == 0:
                letter_array[group][row][column] = 'A'
            elif f[group][row][column] == 25:
                letter_array[group][row][column] = 'B'
            elif f[group][row][column] == 50:
                letter_array[group][row][column] = 'C'
            elif f[group][row][column] == 75:
                letter_array[group][row][column] = 'D'
            elif f[group][row][column] == 100:
                letter_array[group][row][column] = 'E'
                
letter_array

array([[['D', 'D', 'D', 'B', 'D'],
        ['D', 'D', 'B', 'B', 'B'],
        ['D', 'B', 'D', 'D', 'D']],

       [['B', 'B', 'B', 'B', 'E'],
        ['D', 'D', 'D', 'D', 'D'],
        ['B', 'D', 'A', 'D', 'D']]], dtype='<U1')