# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.__version__)

1.18.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a = np.random.rand(2,3,5)

In [4]:
# Method 2
a = np.random.choice([x for x in range(100)], size=(2,3,5))

In [5]:
# Method 3
a = np.random.random((2,3,5))

#### 4. Print *a*.


In [6]:
# your code here
print(a)

[[[0.81293579 0.9618986  0.71993259 0.19573018 0.32072246]
  [0.75228165 0.99783741 0.19653519 0.58122385 0.84270934]
  [0.11661425 0.26138952 0.35498524 0.0655844  0.8031763 ]]

 [[0.08049333 0.89104626 0.28322666 0.93208582 0.72597512]
  [0.07470322 0.52054156 0.60669996 0.85477187 0.4366375 ]
  [0.89545019 0.85274315 0.18278016 0.21933532 0.30377583]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here
b = np.full((5, 2, 3), 1)

#### 6. Print *b*.


In [8]:
# your code here
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here
print('Size a and b equal:', a.size == b.size)
print('Size a:', a.size)
print('Size b:', b.size)
print('Shape a and b equal:', a.shape == b.shape)
print('Shape a:', a.shape)
print('Shape b:', b.shape)
#c = a + b

Size a and b equal: True
Size a: 30
Size b: 30
Shape a and b equal: False
Shape a: (2, 3, 5)
Shape b: (5, 2, 3)


#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here
# a and b cannot be added together, because they do NOT have the same SHAPE!

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here
c = b.transpose(1, 2, 0)
#print(c)
#print(c.shape)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# your code/answer here
d = a + c
# Now it has the same SHAPE!

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# your code/answer here
print('Array a:')
print(a)
print()
print('Array d:')
print(d)
print()
print('In array d all values are larger by 1 because of d is equal to a plus c, whereas the later contains only 1s.')

Array a:
[[[0.81293579 0.9618986  0.71993259 0.19573018 0.32072246]
  [0.75228165 0.99783741 0.19653519 0.58122385 0.84270934]
  [0.11661425 0.26138952 0.35498524 0.0655844  0.8031763 ]]

 [[0.08049333 0.89104626 0.28322666 0.93208582 0.72597512]
  [0.07470322 0.52054156 0.60669996 0.85477187 0.4366375 ]
  [0.89545019 0.85274315 0.18278016 0.21933532 0.30377583]]]

Array d:
[[[1.81293579 1.9618986  1.71993259 1.19573018 1.32072246]
  [1.75228165 1.99783741 1.19653519 1.58122385 1.84270934]
  [1.11661425 1.26138952 1.35498524 1.0655844  1.8031763 ]]

 [[1.08049333 1.89104626 1.28322666 1.93208582 1.72597512]
  [1.07470322 1.52054156 1.60669996 1.85477187 1.4366375 ]
  [1.89545019 1.85274315 1.18278016 1.21933532 1.30377583]]]

In array d all values are larger by 1 because of d is equal to a plus c, whereas the later contains only 1s.


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
# your code here
e = a * c
print(e)

[[[0.81293579 0.9618986  0.71993259 0.19573018 0.32072246]
  [0.75228165 0.99783741 0.19653519 0.58122385 0.84270934]
  [0.11661425 0.26138952 0.35498524 0.0655844  0.8031763 ]]

 [[0.08049333 0.89104626 0.28322666 0.93208582 0.72597512]
  [0.07470322 0.52054156 0.60669996 0.85477187 0.4366375 ]
  [0.89545019 0.85274315 0.18278016 0.21933532 0.30377583]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
# your code/answer here
# 1) e is equal to a * c
# 2) c is equal to b transposed
# 3) b is array with 1s
# 4) coming back to 1) e is a multiplied by 1s which is equal to array a
# 5) so e = a

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
# your code here
d_max = d.max()
d_min = d.min()
d_mean = d.mean()
print('Max:', d_max)
print('Min:', d_min)
print('Mean:', d_mean)

Max: 1.997837408670714
Min: 1.0655844034113664
Mean: 1.5281274234733249


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [17]:
# your code here
f = np.empty((2, 3, 5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [18]:
# your code here

# (2, 3, 5)
for x1 in range(2):
    for x2 in range(3):
        for x3 in range(5):
            d_value = (d[x1][x2][x3])
            if (d_value > d_min) and (d_value < d_mean):
                f_value = 25
            elif (d_value == d_mean):
                f_value = 50
            elif (d_value > d_mean) and (d_value < d_max):
                f_value = 75
            else:
                f_value = 100
            f[x1][x2][x3] = f_value

# MOST PROBABLY THERE IS AN EASIER WAY ... ?           
#f[np.where(d>d_min and d<d_mean)] = 25
#arr[arr==''] = '0'
#f[np.where(d=d_mean)] = 50
#f[np.where(d>d_mean and d<d_max)] = 75
#f[np.where(d>d_max)] = 100
#f

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [19]:
# your code here
print('Array d:')
print(d)
print()
print('Array f:')
print(f)

Array d:
[[[1.81293579 1.9618986  1.71993259 1.19573018 1.32072246]
  [1.75228165 1.99783741 1.19653519 1.58122385 1.84270934]
  [1.11661425 1.26138952 1.35498524 1.0655844  1.8031763 ]]

 [[1.08049333 1.89104626 1.28322666 1.93208582 1.72597512]
  [1.07470322 1.52054156 1.60669996 1.85477187 1.4366375 ]
  [1.89545019 1.85274315 1.18278016 1.21933532 1.30377583]]]

Array f:
[[[ 75.  75.  75.  25.  25.]
  [ 75. 100.  25.  75.  75.]
  [ 25.  25.  25. 100.  75.]]

 [[ 25.  75.  25.  75.  75.]
  [ 25.  25.  75.  75.  25.]
  [ 75.  75.  25.  25.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [20]:
# your code here
# (2, 3, 5)
g = np.empty((2, 3, 5), dtype='S')
for x1 in range(2):
    for x2 in range(3):
        for x3 in range(5):
            d_value = (d[x1][x2][x3])
            if d_value < d_min:
                g_value = 'A'
            if (d_value > d_min) and (d_value < d_mean):
                g_value = 'B'
            elif (d_value == d_mean):
                g_value = 'C'
            elif (d_value > d_mean) and (d_value < d_max):
                g_value = 'D'
            else:
                g_value = 'E'
            g[x1][x2][x3] = g_value
print(g)

[[[b'D' b'D' b'D' b'B' b'B']
  [b'D' b'E' b'B' b'D' b'D']
  [b'B' b'B' b'B' b'E' b'D']]

 [[b'B' b'D' b'B' b'D' b'D']
  [b'B' b'B' b'D' b'D' b'B']
  [b'D' b'D' b'B' b'B' b'B']]]
