# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [2]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [3]:
# your code here
print(np.__version__)

1.18.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [10]:
# Method 1
a = np.random.random((2,3,5))
print(a)

[[[0.16587425 0.64631583 0.91480984 0.02294751 0.09402828]
  [0.80979244 0.24858724 0.40445553 0.73124872 0.90333452]
  [0.76537961 0.43481897 0.87661    0.18044196 0.78204169]]

 [[0.92339615 0.2480772  0.05176864 0.26361237 0.39057687]
  [0.47394276 0.60544178 0.64197064 0.43957889 0.86796284]
  [0.16666012 0.6558461  0.08114815 0.39475667 0.38666035]]]


In [11]:
# Method 2
a = np.random.rand(2,3,5)
print(a)

[[[0.59140403 0.10340913 0.43819107 0.02741737 0.07614519]
  [0.23976655 0.50338872 0.84093056 0.04334432 0.69268753]
  [0.08498307 0.85702168 0.78988873 0.66193748 0.61581008]]

 [[0.74427462 0.41519327 0.14125188 0.80252797 0.32310965]
  [0.21929508 0.11459286 0.56976076 0.24426359 0.21218463]
  [0.40869245 0.21736798 0.335822   0.97744355 0.5530687 ]]]


In [12]:
# Method 3
a = np.random.randint (0,11, size=(2,3,5))
print(a)

[[[ 7  1  1  4  0]
  [ 2 10  8  8  5]
  [ 9  6  6  6  5]]

 [[ 9  3  0  4  4]
  [ 8  9  5  0  5]
  [ 0  3  7  8  9]]]


#### 4. Print *a*.


In [13]:
# your code here
print(a)

[[[ 7  1  1  4  0]
  [ 2 10  8  8  5]
  [ 9  6  6  6  5]]

 [[ 9  3  0  4  4]
  [ 8  9  5  0  5]
  [ 0  3  7  8  9]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [17]:
# your code here
b=np.ones((5,2,3))

#### 6. Print *b*.


In [18]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [20]:
# your code here
a.size==b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [21]:
# your answer here
x=a+b
print(x)

#we cannot add them because they have different shapes

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [23]:
# your code here
c=np.reshape(b, (2,3,5))
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [24]:
# your code/answer here
d=a+c
print(d)
#it works because bot a and c have the same shape

[[[ 8.  2.  2.  5.  1.]
  [ 3. 11.  9.  9.  6.]
  [10.  7.  7.  7.  6.]]

 [[10.  4.  1.  5.  5.]
  [ 9. 10.  6.  1.  6.]
  [ 1.  4.  8.  9. 10.]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [26]:
# your code/answer here
print(a)

[[[ 7  1  1  4  0]
  [ 2 10  8  8  5]
  [ 9  6  6  6  5]]

 [[ 9  3  0  4  4]
  [ 8  9  5  0  5]
  [ 0  3  7  8  9]]]


In [27]:
print(d)
#both arrays have the same shape but the elements for d are a+1

[[[ 8.  2.  2.  5.  1.]
  [ 3. 11.  9.  9.  6.]
  [10.  7.  7.  7.  6.]]

 [[10.  4.  1.  5.  5.]
  [ 9. 10.  6.  1.  6.]
  [ 1.  4.  8.  9. 10.]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [28]:
# your code here
e=a*c
print(e)

[[[ 7.  1.  1.  4.  0.]
  [ 2. 10.  8.  8.  5.]
  [ 9.  6.  6.  6.  5.]]

 [[ 9.  3.  0.  4.  4.]
  [ 8.  9.  5.  0.  5.]
  [ 0.  3.  7.  8.  9.]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [29]:
# your code/answer here
e==a
#they are the same because e = a * c, and all elements in c are 1

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [31]:
# your code here
d_max=d.max()
d_min=d.min()
d_mean=d.mean()
print(d_max)
print(d_min)
print(d_mean)

11.0
1.0
6.066666666666666


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [46]:
# your code here
f = np.empty([2,3,5])
f

array([[[-2.31584178e+077, -2.31584178e+077,  9.88131292e-323,
          0.00000000e+000,  3.77780766e+180],
        [ 5.02034658e+175,  2.25459749e+184,  1.58898883e-076,
          2.12753111e+160,  3.92449583e+179],
        [ 1.17665042e-047,  3.59751658e+252,  8.93185432e+271,
          4.76484771e+180,  1.70537005e+256]],

       [[ 5.49109388e-143,  1.43954137e+214,  4.50617646e-144,
          7.79952704e-143,  5.22105387e-037],
        [ 1.69103234e-052,  7.93286707e+165,  3.26939353e-032,
          1.41529402e+161,  6.00736899e-067],
        [ 5.16740031e+097,  1.83322654e-076,  4.09933514e+126,
          9.30350598e+199,  3.67152475e-062]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [59]:
# your code here
for x, y in np.ndenumerate(d):
            if y == d_min:
                    f[x] = 0 
            elif y > d_min and y < d_mean:
                    f[x] = 25  
            elif y == d_mean:
                    f[x] = 50 
            elif y > d_mean and y < d_max:
                    f[x] = 75  
            elif y == d_max:
                    f[x] = 100
f                    

array([[[ 75.,  25.,  25.,  25.,   0.],
        [ 25., 100.,  75.,  75.,  25.],
        [ 75.,  75.,  75.,  75.,  25.]],

       [[ 75.,  25.,   0.,  25.,  25.],
        [ 75.,  75.,  25.,   0.,  25.],
        [  0.,  25.,  75.,  75.,  75.]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [54]:
# your code here
print(d)
print (f)

[[[ 8.  2.  2.  5.  1.]
  [ 3. 11.  9.  9.  6.]
  [10.  7.  7.  7.  6.]]

 [[10.  4.  1.  5.  5.]
  [ 9. 10.  6.  1.  6.]
  [ 1.  4.  8.  9. 10.]]]
[[[ 75.  25.  25.  25.   0.]
  [ 25. 100.  75.  75.  25.]
  [ 75.  75.  75.  75.  25.]]

 [[ 75.  25.   0.  25.  25.]
  [ 75.  75.  25.   0.  25.]
  [  0.  25.  75.  75.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here