# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here

import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
import numpy
numpy.version.version

'1.16.5'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1

a = np.random.random((2,3,5))

a

array([[[0.19181976, 0.81733496, 0.0863185 , 0.97223589, 0.59531501],
        [0.06459784, 0.76244816, 0.30917379, 0.98161322, 0.12201512],
        [0.72798353, 0.28871925, 0.99096033, 0.8552469 , 0.1393634 ]],

       [[0.27982336, 0.62447735, 0.69585649, 0.26832723, 0.60804053],
        [0.03760639, 0.89827548, 0.60883644, 0.84714893, 0.45395838],
        [0.74901455, 0.20971533, 0.74093836, 0.96017272, 0.62034731]]])

In [4]:
# Method 2

a2 = np.random.rand(2,3,5)
a2

array([[[0.60399257, 0.90932086, 0.24112909, 0.26002911, 0.25949726],
        [0.06414318, 0.10090519, 0.76949508, 0.74420003, 0.22276238],
        [0.15897019, 0.42775946, 0.08899276, 0.91284557, 0.94199596]],

       [[0.30887638, 0.79086636, 0.97028273, 0.2964336 , 0.63560773],
        [0.00931168, 0.20172456, 0.10983801, 0.02404445, 0.71440009],
        [0.59920498, 0.39906409, 0.51143517, 0.08863701, 0.18791908]]])

In [5]:
# Method 3

a3 = np.random.randint(1,10,(2,3,5))
a3

array([[[1, 3, 3, 7, 6],
        [8, 7, 9, 5, 4],
        [6, 2, 4, 8, 2]],

       [[5, 7, 8, 1, 1],
        [2, 2, 9, 6, 6],
        [4, 6, 2, 1, 5]]])

#### 4. Print *a*.


In [6]:
# your code here
print(a)

[[[0.19181976 0.81733496 0.0863185  0.97223589 0.59531501]
  [0.06459784 0.76244816 0.30917379 0.98161322 0.12201512]
  [0.72798353 0.28871925 0.99096033 0.8552469  0.1393634 ]]

 [[0.27982336 0.62447735 0.69585649 0.26832723 0.60804053]
  [0.03760639 0.89827548 0.60883644 0.84714893 0.45395838]
  [0.74901455 0.20971533 0.74093836 0.96017272 0.62034731]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here

b = np.ones((5,2,3), dtype = int)
b

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

#### 6. Print *b*.


In [8]:
# your code here
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here

print(a.size)
print(b.size)
print(a.size == b.size)

30
30
True


#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here

# No, because they have different dimensions

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here

c = np.transpose(b,(1,2,0))

print(c)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# your code/answer here

d = np.add(a,c)

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# your code/answer here

print(d)

#The values from array a were added to the correlated values from array c.

[[[1.19181976 1.81733496 1.0863185  1.97223589 1.59531501]
  [1.06459784 1.76244816 1.30917379 1.98161322 1.12201512]
  [1.72798353 1.28871925 1.99096033 1.8552469  1.1393634 ]]

 [[1.27982336 1.62447735 1.69585649 1.26832723 1.60804053]
  [1.03760639 1.89827548 1.60883644 1.84714893 1.45395838]
  [1.74901455 1.20971533 1.74093836 1.96017272 1.62034731]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
# your code here

e = np.multiply(a,c)

print(e)

[[[0.19181976 0.81733496 0.0863185  0.97223589 0.59531501]
  [0.06459784 0.76244816 0.30917379 0.98161322 0.12201512]
  [0.72798353 0.28871925 0.99096033 0.8552469  0.1393634 ]]

 [[0.27982336 0.62447735 0.69585649 0.26832723 0.60804053]
  [0.03760639 0.89827548 0.60883644 0.84714893 0.45395838]
  [0.74901455 0.20971533 0.74093836 0.96017272 0.62034731]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
# your code/answer here

print(e==a)

#Yes, because e was multiplied by 1.

[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
# your code here
d_max = np.amax(d)
d_min = np.amin(d)
d_mean = np.mean(d)

print(d_max)
print(d_min)
print(d_mean)

1.9909603253201347
1.0376063872123071
1.5502561498860998


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [17]:
# your code here

f = np.empty((2,3,5))
print(f)

[[[0.19181976 0.81733496 0.0863185  0.97223589 0.59531501]
  [0.06459784 0.76244816 0.30917379 0.98161322 0.12201512]
  [0.72798353 0.28871925 0.99096033 0.8552469  0.1393634 ]]

 [[0.27982336 0.62447735 0.69585649 0.26832723 0.60804053]
  [0.03760639 0.89827548 0.60883644 0.84714893 0.45395838]
  [0.74901455 0.20971533 0.74093836 0.96017272 0.62034731]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [19]:
print(d)

# Teste coordenada
for x in range(d.shape[0]):
    for y in range(d.shape[1]):
        for z in range(d.shape[2]):
            print(x,y,z)

# Your code
for x in range(d.shape[0]):
    for y in range(d.shape[1]):
        for z in range(d.shape[2]):
            if d[x,y,z] > d_min and d[x,y,z] < d_mean:
                f[x,y,z] = 25
            elif d[x,y,z] > d_mean and d[x,y,z] < d_max:
                f[x,y,z] = 75
            elif d[x,y,z] == d_mean:
                f[x,y,z] = 50
            elif d[x,y,z] == d_max:
                f[x,y,z] = 100
            else:
                f[x,y,z] = 0

[[[1.19181976 1.81733496 1.0863185  1.97223589 1.59531501]
  [1.06459784 1.76244816 1.30917379 1.98161322 1.12201512]
  [1.72798353 1.28871925 1.99096033 1.8552469  1.1393634 ]]

 [[1.27982336 1.62447735 1.69585649 1.26832723 1.60804053]
  [1.03760639 1.89827548 1.60883644 1.84714893 1.45395838]
  [1.74901455 1.20971533 1.74093836 1.96017272 1.62034731]]]
0 0 0
0 0 1
0 0 2
0 0 3
0 0 4
0 1 0
0 1 1
0 1 2
0 1 3
0 1 4
0 2 0
0 2 1
0 2 2
0 2 3
0 2 4
1 0 0
1 0 1
1 0 2
1 0 3
1 0 4
1 1 0
1 1 1
1 1 2
1 1 3
1 1 4
1 2 0
1 2 1
1 2 2
1 2 3
1 2 4


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [20]:
# your code here

print(d)
print(f)

[[[1.19181976 1.81733496 1.0863185  1.97223589 1.59531501]
  [1.06459784 1.76244816 1.30917379 1.98161322 1.12201512]
  [1.72798353 1.28871925 1.99096033 1.8552469  1.1393634 ]]

 [[1.27982336 1.62447735 1.69585649 1.26832723 1.60804053]
  [1.03760639 1.89827548 1.60883644 1.84714893 1.45395838]
  [1.74901455 1.20971533 1.74093836 1.96017272 1.62034731]]]
[[[ 25.  75.  25.  75.  75.]
  [ 25.  75.  25.  75.  25.]
  [ 75.  25. 100.  75.  25.]]

 [[ 25.  75.  75.  25.  75.]
  [  0.  75.  75.  75.  25.]
  [ 75.  25.  75.  75.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [21]:
# your code here

new_arrf = np.zeros(shape = f.shape, dtype=np.str)
for x in range(f.shape[0]):
    for y in range(f.shape[1]):
        for z in range(f.shape[2]):
            if f[x,y,z] == 25:
                new_arrf[x,y,z] = 'B'
            elif f[x,y,z] == 75:
                new_arrf[x,y,z] = 'D'
            elif f[x,y,z] == 50:
                new_arrf[x,y,z] = 'C'
            elif f[x,y,z] == 50:
                new_arrf[x,y,z] = 'A'
            else:
                new_arrf[x,y,z] = 'E'
print(new_arrf)

[[['B' 'D' 'B' 'D' 'D']
  ['B' 'D' 'B' 'D' 'B']
  ['D' 'B' 'E' 'D' 'B']]

 [['B' 'D' 'D' 'B' 'D']
  ['E' 'D' 'D' 'D' 'B']
  ['D' 'B' 'D' 'D' 'D']]]
