# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [2]:
# your code here

import numpy as np

#### 2. Print your NumPy version.

In [3]:
# your code here

np.version.version

'1.16.4'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [4]:
# Method 1

a = np.random.random((2,3,5))
print(a)

[[[0.47337413 0.81765873 0.92382413 0.50513485 0.05276936]
  [0.97732517 0.7597362  0.03825288 0.35637185 0.53043878]
  [0.46633139 0.14837093 0.72222053 0.48426855 0.17568202]]

 [[0.69765021 0.82824999 0.2990933  0.48792768 0.6419506 ]
  [0.56327879 0.00307787 0.29858077 0.0930649  0.02917292]
  [0.66057889 0.70024363 0.46795107 0.5612745  0.21855432]]]


In [5]:
# Method 2

a = np.random.normal(size=(2,3,5))
print(a)

[[[-0.89121729 -1.13184297 -0.22525443 -0.6828161  -0.1190455 ]
  [-1.38747057 -0.59535264  3.25367745  1.15893445 -1.21622496]
  [ 2.17671592  0.89907608  2.20156563  1.15452227  0.11739488]]

 [[-1.30832683 -0.74143199 -2.72315716 -0.22146643 -0.61947432]
  [-0.57662363  1.54297912 -0.55146248 -1.54256023 -0.45778461]
  [ 1.21333609 -0.38125094  0.50752143  1.3459024  -0.304347  ]]]


In [6]:
# Method 3

a = np.random.randint(100, size=(2,3,5))
print(a)

[[[82 91 27 14 35]
  [37 58 19 51 77]
  [59 78 83 93 76]]

 [[91 54  1 20 32]
  [87 60 37  7 64]
  [59  5  1 32 36]]]


#### 4. Print *a*.


In [7]:
# your code here

print(a)

[[[82 91 27 14 35]
  [37 58 19 51 77]
  [59 78 83 93 76]]

 [[91 54  1 20 32]
  [87 60 37  7 64]
  [59  5  1 32 36]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [8]:
# your code here

b = np.full((5,2,3), 1)

#### 6. Print *b*.


In [9]:
# your code here
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [10]:
# your code here

a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [11]:
# your answer here

print(a + b)
# No - because they do not have the same shape.

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [12]:
# your code here

c = np.transpose(b, (1,2,0))
print(c)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [13]:
# your code/answer here

d = a + c
print(d)

[[[83 92 28 15 36]
  [38 59 20 52 78]
  [60 79 84 94 77]]

 [[92 55  2 21 33]
  [88 61 38  8 65]
  [60  6  2 33 37]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [14]:
# your code/answer here

print(a)
print(d)

# Each value in d is just one larger than that value in the same position in a (ie. a + 1)

[[[82 91 27 14 35]
  [37 58 19 51 77]
  [59 78 83 93 76]]

 [[91 54  1 20 32]
  [87 60 37  7 64]
  [59  5  1 32 36]]]
[[[83 92 28 15 36]
  [38 59 20 52 78]
  [60 79 84 94 77]]

 [[92 55  2 21 33]
  [88 61 38  8 65]
  [60  6  2 33 37]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [15]:
# your code here

e = a * c
print(e)

[[[82 91 27 14 35]
  [37 58 19 51 77]
  [59 78 83 93 76]]

 [[91 54  1 20 32]
  [87 60 37  7 64]
  [59  5  1 32 36]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [17]:
# your code/answer here

e == a

# Yes, because e is a * 1 so all the values sould remain the same

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [18]:
# your code here

d_max = np.max(d)
print(d_max)

d_min = np.min(d)
print(d_min)

d_mean = np.mean(d)
print(d_mean)

94
2
49.86666666666667


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [19]:
# your code here

f = np.empty((2,3,5))
print(f)

[[[-0.89121729 -1.13184297 -0.22525443 -0.6828161  -0.1190455 ]
  [-1.38747057 -0.59535264  3.25367745  1.15893445 -1.21622496]
  [ 2.17671592  0.89907608  2.20156563  1.15452227  0.11739488]]

 [[-1.30832683 -0.74143199 -2.72315716 -0.22146643 -0.61947432]
  [-0.57662363  1.54297912 -0.55146248 -1.54256023 -0.45778461]
  [ 1.21333609 -0.38125094  0.50752143  1.3459024  -0.304347  ]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [20]:
# your code here


f[(d_min < d) & (d < d_mean)] = 25
f[(d_mean < d) & (d < d_max)] = 75
f[(d == d_mean)] = 50
f[(d == d_max)] = 100
f[(d == d_min)] = 0

print(f)

[[[ 75.  75.  25.  25.  25.]
  [ 25.  75.  25.  75.  75.]
  [ 75.  75.  75. 100.  75.]]

 [[ 75.  75.   0.  25.  25.]
  [ 75.  75.  25.  25.  75.]
  [ 75.  25.   0.  25.  25.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [21]:
# your code here

print(d)
print(f)

[[[83 92 28 15 36]
  [38 59 20 52 78]
  [60 79 84 94 77]]

 [[92 55  2 21 33]
  [88 61 38  8 65]
  [60  6  2 33 37]]]
[[[ 75.  75.  25.  25.  25.]
  [ 25.  75.  25.  75.  75.]
  [ 75.  75.  75. 100.  75.]]

 [[ 75.  75.   0.  25.  25.]
  [ 75.  75.  25.  25.  75.]
  [ 75.  25.   0.  25.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [22]:
# your code here

g = np.empty((2,3,5))
g = f.astype(np.str)

g[(f == 0)] = "A"
g[(f == 25)] = "B"
g[(f == 50)] = "C"
g[(f == 75)] = "D"
g[(f == 100)] = "E"

print(g)

[[['D' 'D' 'B' 'B' 'B']
  ['B' 'D' 'B' 'D' 'D']
  ['D' 'D' 'D' 'E' 'D']]

 [['D' 'D' 'A' 'B' 'B']
  ['D' 'D' 'B' 'B' 'D']
  ['D' 'B' 'A' 'B' 'B']]]
