# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [2]:
print(np)

<module 'numpy' from 'C:\\Users\\Alina Hartsch\\anaconda3\\envs\\Ironhack\\lib\\site-packages\\numpy\\__init__.py'>


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
import random
my_array1=np.random.random((2,3,5))
print(my_array1)

[[[0.45212451 0.99419736 0.26721761 0.29503479 0.53122187]
  [0.18723441 0.38049381 0.58250755 0.53964635 0.87406238]
  [0.16902952 0.53330595 0.91915933 0.67076783 0.84115263]]

 [[0.71419725 0.53525228 0.27304484 0.17006746 0.34922489]
  [0.88040529 0.48709812 0.68773308 0.40935681 0.49839945]
  [0.20446089 0.15818978 0.98327006 0.66451539 0.10397223]]]


In [4]:
my_array2=np.random.rand(2,3,5)

print(my_array2)


[[[0.11452336 0.36391143 0.57740359 0.84774828 0.54840504]
  [0.18815367 0.43161078 0.93670385 0.18418401 0.60100185]
  [0.91392934 0.6153358  0.11482241 0.51792407 0.58349722]]

 [[0.76600488 0.04782908 0.55442207 0.68426984 0.92428475]
  [0.45328118 0.7832134  0.29395923 0.14968769 0.43779134]
  [0.10758394 0.0234385  0.58545727 0.23145985 0.44056508]]]


In [5]:
list1=[element for element in random.sample(range(100),2)]
print(list1)


[58, 79]


In [6]:
list2=[element for element in random.sample(range(100),3)]
print(list2)

[92, 69, 9]


In [7]:
list3=[element for element in random.sample(range(100),5)]
print(list3)

[56, 21, 91, 62, 76]


#### 4. Print *a*.


In [8]:
a=my_array1
print(a)

[[[0.45212451 0.99419736 0.26721761 0.29503479 0.53122187]
  [0.18723441 0.38049381 0.58250755 0.53964635 0.87406238]
  [0.16902952 0.53330595 0.91915933 0.67076783 0.84115263]]

 [[0.71419725 0.53525228 0.27304484 0.17006746 0.34922489]
  [0.88040529 0.48709812 0.68773308 0.40935681 0.49839945]
  [0.20446089 0.15818978 0.98327006 0.66451539 0.10397223]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [9]:
b=np.ones((5,2,3),int)

#### 6. Print *b*.


In [10]:
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [11]:
a.size==b.size #yes they have, you can prove it by comparing the sizes with ==

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [12]:
C=a+b #No because they have different shapes 

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [13]:
c=b.reshape(2,3,5)
print(c)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [14]:
d=a+c

print(d) #it works now becasue we reshaped c so it has the same shape as a which allows us to add both arrays

[[[1.45212451 1.99419736 1.26721761 1.29503479 1.53122187]
  [1.18723441 1.38049381 1.58250755 1.53964635 1.87406238]
  [1.16902952 1.53330595 1.91915933 1.67076783 1.84115263]]

 [[1.71419725 1.53525228 1.27304484 1.17006746 1.34922489]
  [1.88040529 1.48709812 1.68773308 1.40935681 1.49839945]
  [1.20446089 1.15818978 1.98327006 1.66451539 1.10397223]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [15]:
print('This is a:') 
print(a)
print('This is d:')
print(d)

# #the difference of the value is for each value +1, since c consistet of only ones and its values were added to the values of a 
#and the result stored in d (d=a+c)

This is a:
[[[0.45212451 0.99419736 0.26721761 0.29503479 0.53122187]
  [0.18723441 0.38049381 0.58250755 0.53964635 0.87406238]
  [0.16902952 0.53330595 0.91915933 0.67076783 0.84115263]]

 [[0.71419725 0.53525228 0.27304484 0.17006746 0.34922489]
  [0.88040529 0.48709812 0.68773308 0.40935681 0.49839945]
  [0.20446089 0.15818978 0.98327006 0.66451539 0.10397223]]]
This is d:
[[[1.45212451 1.99419736 1.26721761 1.29503479 1.53122187]
  [1.18723441 1.38049381 1.58250755 1.53964635 1.87406238]
  [1.16902952 1.53330595 1.91915933 1.67076783 1.84115263]]

 [[1.71419725 1.53525228 1.27304484 1.17006746 1.34922489]
  [1.88040529 1.48709812 1.68773308 1.40935681 1.49839945]
  [1.20446089 1.15818978 1.98327006 1.66451539 1.10397223]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [16]:
e=a*c
e

array([[[0.45212451, 0.99419736, 0.26721761, 0.29503479, 0.53122187],
        [0.18723441, 0.38049381, 0.58250755, 0.53964635, 0.87406238],
        [0.16902952, 0.53330595, 0.91915933, 0.67076783, 0.84115263]],

       [[0.71419725, 0.53525228, 0.27304484, 0.17006746, 0.34922489],
        [0.88040529, 0.48709812, 0.68773308, 0.40935681, 0.49839945],
        [0.20446089, 0.15818978, 0.98327006, 0.66451539, 0.10397223]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [17]:
a==e #they equal to each other because a was multiplied with c which only contains values 1 and number*1 always equals number

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [19]:
d_max = np.amax(d)
d_min = np.amin(d)
d_mean = np.mean(d)
print(d_max)
print(d_min)
print(d_mean)

1.994197356449543
1.103972226550883
1.5118781235722758


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [20]:
f=np.empty([2,3,5])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [21]:
my_list=[]

for column in d:
    for element in column: 
        if element > d_min and element < d_mean:
            my_list.append('25')
        elif element > d_mean and element < d_max:
            my_list.append('75')
        elif element == d_mean:
            my_list.append('50')
        elif element == d_min:
            my_list.append('0')
        elif element == d_max:
            my_list.append('100')
        else:
            continue
print(my_list)
            

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here