# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [10]:
import numpy as np

#### 2. Print your NumPy version.

In [11]:
print(np.__version__)

1.16.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [12]:
a = np.random.rand(2,3,5)

In [13]:
np.random.randint(0,100, size=(2,3,5))

array([[[67, 62, 53, 42, 13],
        [71, 29, 99, 98, 21],
        [96,  6, 34, 13, 83]],

       [[55, 66, 38, 92, 77],
        [52, 74, 65, 16, 79],
        [88, 69, 86, 38, 82]]])

#### 4. Print *a*.


In [14]:
a

array([[[0.5239852 , 0.41240818, 0.92285941, 0.09099365, 0.88940424],
        [0.30852222, 0.5990402 , 0.70101286, 0.64467521, 0.91560324],
        [0.23455429, 0.28135846, 0.15878081, 0.24647327, 0.51983621]],

       [[0.66013435, 0.00948574, 0.62968605, 0.76290329, 0.69443625],
        [0.96433365, 0.25634769, 0.5605018 , 0.29057973, 0.46381081],
        [0.34268294, 0.93459561, 0.04838198, 0.80295077, 0.00470777]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [15]:
b = np.full((5,2,3), 1)

#### 6. Print *b*.


In [16]:
b

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [17]:
True if a.size == b.size else False

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [18]:
a + b
#unable to add both arrays due to different shapes

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [19]:
c = b.transpose(1,2,0)
c

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [20]:
d = a + c
d #this works because the shape is now the same

array([[[1.5239852 , 1.41240818, 1.92285941, 1.09099365, 1.88940424],
        [1.30852222, 1.5990402 , 1.70101286, 1.64467521, 1.91560324],
        [1.23455429, 1.28135846, 1.15878081, 1.24647327, 1.51983621]],

       [[1.66013435, 1.00948574, 1.62968605, 1.76290329, 1.69443625],
        [1.96433365, 1.25634769, 1.5605018 , 1.29057973, 1.46381081],
        [1.34268294, 1.93459561, 1.04838198, 1.80295077, 1.00470777]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [21]:
print("A", a, "D", d, sep='\n') #"c" is "b" transposed and d is "a" plus "c"

A
[[[0.5239852  0.41240818 0.92285941 0.09099365 0.88940424]
  [0.30852222 0.5990402  0.70101286 0.64467521 0.91560324]
  [0.23455429 0.28135846 0.15878081 0.24647327 0.51983621]]

 [[0.66013435 0.00948574 0.62968605 0.76290329 0.69443625]
  [0.96433365 0.25634769 0.5605018  0.29057973 0.46381081]
  [0.34268294 0.93459561 0.04838198 0.80295077 0.00470777]]]
D
[[[1.5239852  1.41240818 1.92285941 1.09099365 1.88940424]
  [1.30852222 1.5990402  1.70101286 1.64467521 1.91560324]
  [1.23455429 1.28135846 1.15878081 1.24647327 1.51983621]]

 [[1.66013435 1.00948574 1.62968605 1.76290329 1.69443625]
  [1.96433365 1.25634769 1.5605018  1.29057973 1.46381081]
  [1.34268294 1.93459561 1.04838198 1.80295077 1.00470777]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [22]:
e = a*c
e

array([[[0.5239852 , 0.41240818, 0.92285941, 0.09099365, 0.88940424],
        [0.30852222, 0.5990402 , 0.70101286, 0.64467521, 0.91560324],
        [0.23455429, 0.28135846, 0.15878081, 0.24647327, 0.51983621]],

       [[0.66013435, 0.00948574, 0.62968605, 0.76290329, 0.69443625],
        [0.96433365, 0.25634769, 0.5605018 , 0.29057973, 0.46381081],
        [0.34268294, 0.93459561, 0.04838198, 0.80295077, 0.00470777]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [23]:
np.array_equal(e,a) #because each element of A is multiplied by 1 (elements of array c) so these remain unchanged

True

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [24]:
d_max = np.amax(d)
d_min = np.min(d)
d_mean = np.mean(d)

(f"Maxmimum value in 'd' is {d_max}, minimum value is {d_min} and mean is {d_mean}")

"Maxmimum value in 'd' is 1.9643336489124497, minimum value is 1.0047077654000867 and mean is 1.4958348631882952"

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [25]:
f = np.empty(shape=[2,3,5])
f

array([[[0.5239852 , 0.41240818, 0.92285941, 0.09099365, 0.88940424],
        [0.30852222, 0.5990402 , 0.70101286, 0.64467521, 0.91560324],
        [0.23455429, 0.28135846, 0.15878081, 0.24647327, 0.51983621]],

       [[0.66013435, 0.00948574, 0.62968605, 0.76290329, 0.69443625],
        [0.96433365, 0.25634769, 0.5605018 , 0.29057973, 0.46381081],
        [0.34268294, 0.93459561, 0.04838198, 0.80295077, 0.00470777]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [27]:
for i in range(len(d)):
    for j in range(len(d[i])):
        for k in range(len(d[i][j])):
            if d[i][j][k] > d_min and d[i][j][k] < d_mean:
                f[i][j][k] = 25
            elif d[i][j][k] > d_mean and d[i][j][k] < d_max:
                f[i][j][k] = 75
            elif d[i][j][k] == d_mean:
                f[i][j][k] = 5
            elif d[i][j][k] == d_min:
                f[i][j][k] = 0
            elif d[i][j][k] == d_max:
                f[i][j][k] = 100

array([[[ 75.,  25.,  75.,  25.,  75.],
        [ 25.,  75.,  75.,  75.,  75.],
        [ 25.,  25.,  25.,  25.,  75.]],

       [[ 75.,  25.,  75.,  75.,  75.],
        [100.,  25.,  75.,  25.,  25.],
        [ 25.,  75.,  25.,  75.,   0.]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [31]:
print("D", d, "F", f, sep='\n')

D
[[[1.5239852  1.41240818 1.92285941 1.09099365 1.88940424]
  [1.30852222 1.5990402  1.70101286 1.64467521 1.91560324]
  [1.23455429 1.28135846 1.15878081 1.24647327 1.51983621]]

 [[1.66013435 1.00948574 1.62968605 1.76290329 1.69443625]
  [1.96433365 1.25634769 1.5605018  1.29057973 1.46381081]
  [1.34268294 1.93459561 1.04838198 1.80295077 1.00470777]]]
F
[[[ 75.  25.  75.  25.  75.]
  [ 25.  75.  75.  75.  75.]
  [ 25.  25.  25.  25.  75.]]

 [[ 75.  25.  75.  75.  75.]
  [100.  25.  75.  25.  25.]
  [ 25.  75.  25.  75.   0.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here