# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.__version__)

1.18.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 
a = np.random.random([2,3,5])

In [4]:
# Method 2
print (np.random.rand(2,3,5))

[[[0.62334221 0.1389542  0.33226767 0.00986633 0.65789957]
  [0.37884278 0.32669207 0.06578851 0.48375521 0.62939416]
  [0.2608515  0.40528664 0.13381271 0.14455405 0.72716758]]

 [[0.11104267 0.30876503 0.97487607 0.45060636 0.78807583]
  [0.29664469 0.03138181 0.39593619 0.7824754  0.33016372]
  [0.03204823 0.1775842  0.67601508 0.67938746 0.39872504]]]


In [5]:
# Method 3
print(np.random.random_sample((2,3,5)))

[[[0.46932271 0.7744894  0.52907825 0.29782462 0.5824996 ]
  [0.68476814 0.94071917 0.94610135 0.84034608 0.50982104]
  [0.3467383  0.65308756 0.78036107 0.54039013 0.54744089]]

 [[0.66058402 0.93324597 0.1868598  0.69155586 0.87836646]
  [0.89110109 0.46948221 0.8091823  0.53073159 0.86946781]
  [0.44721089 0.27369938 0.18262774 0.57465803 0.62540099]]]


#### 4. Print *a*.


In [6]:
# your code here
print(a)

[[[0.34583886 0.78396511 0.72030164 0.9518944  0.87448718]
  [0.96037454 0.5491077  0.72916403 0.08116027 0.36983349]
  [0.40877896 0.82942905 0.8225327  0.97030017 0.35583221]]

 [[0.732603   0.1937281  0.71089492 0.67738728 0.67291152]
  [0.94207619 0.74636537 0.44691331 0.46114507 0.88724346]
  [0.07751247 0.93365867 0.04470483 0.24838873 0.71484558]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here
b = np.random.random([5,2,3])

#### 6. Print *b*.


In [8]:
# your code here
print(b)

[[[0.86592543 0.92342798 0.09952525]
  [0.65917965 0.57377591 0.07946549]]

 [[0.13584437 0.84832124 0.50434988]
  [0.58720692 0.42612263 0.7336684 ]]

 [[0.84969563 0.91154723 0.38432394]
  [0.32497418 0.63007505 0.12825151]]

 [[0.96433404 0.14759668 0.95283315]
  [0.86590552 0.76895943 0.48555958]]

 [[0.7688195  0.80787956 0.14471717]
  [0.53292523 0.41629041 0.62961887]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here
print(a.size)
print(b.size)

print(a.size==b.size)

30
30
True


#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here
np.add((a,b))
"""ValueError: all the input array dimensions for the concatenation axis must match exactly, 
but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2"""
#So, matrix a is 3x5 and matrix b is 2x3. Matrix a has 3 rows and matrix b has only 2.

ValueError: invalid number of arguments

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here

c = b.transpose(1,2,0)
print(c)

[[[0.86592543 0.13584437 0.84969563 0.96433404 0.7688195 ]
  [0.92342798 0.84832124 0.91154723 0.14759668 0.80787956]
  [0.09952525 0.50434988 0.38432394 0.95283315 0.14471717]]

 [[0.65917965 0.58720692 0.32497418 0.86590552 0.53292523]
  [0.57377591 0.42612263 0.63007505 0.76895943 0.41629041]
  [0.07946549 0.7336684  0.12825151 0.48555958 0.62961887]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# your code/answer here
d = np.add(a,c)
#They have the same shape.

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# your code/answer here
print (a)
print ("")
print (d)
# The value of d[i,j,k] is equal to the sum of a[i,j,k]+c[i,j,k]. 
# E.g. d[0,0,0]=a[0,0,0]+c[0,0,0]; i.e. 1.12019293 = 0.30262553 + 0.8175674.
# Both have the same shape as the result of the transposition of b assigned to c.

[[[0.34583886 0.78396511 0.72030164 0.9518944  0.87448718]
  [0.96037454 0.5491077  0.72916403 0.08116027 0.36983349]
  [0.40877896 0.82942905 0.8225327  0.97030017 0.35583221]]

 [[0.732603   0.1937281  0.71089492 0.67738728 0.67291152]
  [0.94207619 0.74636537 0.44691331 0.46114507 0.88724346]
  [0.07751247 0.93365867 0.04470483 0.24838873 0.71484558]]]

[[[1.21176429 0.91980948 1.56999727 1.91622844 1.64330669]
  [1.88380252 1.39742894 1.64071126 0.22875695 1.17771305]
  [0.50830422 1.33377893 1.20685664 1.92313332 0.50054938]]

 [[1.39178265 0.78093501 1.0358691  1.5432928  1.20583674]
  [1.51585209 1.172488   1.07698836 1.2301045  1.30353387]
  [0.15697796 1.66732707 0.17295634 0.73394831 1.34446445]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
# your code here
c = b.transpose(1,0,2)
e = np.dot(a,c)

#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
# your code/answer here
print(a.shape)
print(c.shape)
print(e.shape)
# First of all, it was necessary to transpose again b and store in c.
# So that the columns of a have the same size of the rows of c.

(2, 3, 5)
(2, 5, 3)
(2, 3, 2, 3)


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
# your code here
d_max = np.max(d)
d_min = np.amin(d)
d_mean = np.mean(d)

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [17]:
# your code here
f = np.empty([2,3,5])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [18]:
# your code here
for i in d:
    for j in i:
        for k in j:
            if k > d_min and k < d_mean:
                f[np.where(d==k)] = 25
            elif k > d_mean and k < d_max:
                f[np.where(d==k)] = 75
            elif k == d_mean:
                f[np.where(d==k)] = 50
            elif k == d_min:
                f[np.where(d==k)] = 0
            elif k == d_max:
                f[np.where(d==k)] = 100

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [19]:
# your code here
print (d)
print ("")
print (f)

[[[1.21176429 0.91980948 1.56999727 1.91622844 1.64330669]
  [1.88380252 1.39742894 1.64071126 0.22875695 1.17771305]
  [0.50830422 1.33377893 1.20685664 1.92313332 0.50054938]]

 [[1.39178265 0.78093501 1.0358691  1.5432928  1.20583674]
  [1.51585209 1.172488   1.07698836 1.2301045  1.30353387]
  [0.15697796 1.66732707 0.17295634 0.73394831 1.34446445]]]

[[[ 75.  25.  75.  75.  75.]
  [ 75.  75.  75.  25.  25.]
  [ 25.  75.  75. 100.  25.]]

 [[ 75.  25.  25.  75.  75.]
  [ 75.  25.  25.  75.  75.]
  [  0.  75.  25.  25.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [20]:
# your code here
g = np.empty([2,3,5],dtype=str)

for i in d:
    for j in i:
        for k in j:
            if k > d_min and k < d_mean:
                g[np.where(d==k)] = "B"
            elif k > d_mean and k < d_max:
                g[np.where(d==k)] = "D"
            elif k == d_mean:
                g[np.where(d==k)] = "C"
            elif k == d_min:
                g[np.where(d==k)] = "A"
            elif k == d_max:
                g[np.where(d==k)] = "E"

print (g)

[[['D' 'B' 'D' 'D' 'D']
  ['D' 'D' 'D' 'B' 'B']
  ['B' 'D' 'D' 'E' 'B']]

 [['D' 'B' 'B' 'D' 'D']
  ['D' 'B' 'B' 'D' 'D']
  ['A' 'D' 'B' 'B' 'D']]]
