# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [2]:
# your code here

import numpy as np

#### 2. Print your NumPy version.

In [3]:
# your code here

print(np.__version__)

1.18.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [4]:
# Method 1

a = np.random.random((2,3,5))

a

array([[[0.94919224, 0.74039184, 0.278346  , 0.4858283 , 0.81142966],
        [0.33051209, 0.84516726, 0.93786966, 0.56621057, 0.51074151],
        [0.42817177, 0.37263258, 0.82035927, 0.59416579, 0.07595274]],

       [[0.5711624 , 0.04357343, 0.62988447, 0.65192286, 0.69244069],
        [0.791548  , 0.74761589, 0.63384425, 0.58622038, 0.48526568],
        [0.52477016, 0.87926919, 0.12536088, 0.35580098, 0.76053918]]])

In [ ]:
# Method 2

In [ ]:
# Method 3

#### 4. Print *a*.


In [ ]:
# your code here

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [5]:
# your code here

b = np.ones((5,2,3))

#### 6. Print *b*.


In [6]:
# your code here

b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [7]:
# your code here

print(a.size)
print(b.size)

30
30


#### 8. Are you able to add *a* and *b*? Why or why not?


In [8]:
# your answer here

print(np.add(a, b))
 

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [9]:
# your code here

c = np.ones((2,3,5))

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [10]:
# your code/answer here

d = np.add(a, c)

print(d)

[[[1.94919224 1.74039184 1.278346   1.4858283  1.81142966]
  [1.33051209 1.84516726 1.93786966 1.56621057 1.51074151]
  [1.42817177 1.37263258 1.82035927 1.59416579 1.07595274]]

 [[1.5711624  1.04357343 1.62988447 1.65192286 1.69244069]
  [1.791548   1.74761589 1.63384425 1.58622038 1.48526568]
  [1.52477016 1.87926919 1.12536088 1.35580098 1.76053918]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [37]:
# your code/answer here

print(a)

print(d)



[[[0.94919224 0.74039184 0.278346   0.4858283  0.81142966]
  [0.33051209 0.84516726 0.93786966 0.56621057 0.51074151]
  [0.42817177 0.37263258 0.82035927 0.59416579 0.07595274]]

 [[0.5711624  0.04357343 0.62988447 0.65192286 0.69244069]
  [0.791548   0.74761589 0.63384425 0.58622038 0.48526568]
  [0.52477016 0.87926919 0.12536088 0.35580098 0.76053918]]]
[[[1.94919224 1.74039184 1.278346   1.4858283  1.81142966]
  [1.33051209 1.84516726 1.93786966 1.56621057 1.51074151]
  [1.42817177 1.37263258 1.82035927 1.59416579 1.07595274]]

 [[1.5711624  1.04357343 1.62988447 1.65192286 1.69244069]
  [1.791548   1.74761589 1.63384425 1.58622038 1.48526568]
  [1.52477016 1.87926919 1.12536088 1.35580098 1.76053918]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [12]:
# your code here

e = np.multiply(a, c)

print(e)

[[[0.94919224 0.74039184 0.278346   0.4858283  0.81142966]
  [0.33051209 0.84516726 0.93786966 0.56621057 0.51074151]
  [0.42817177 0.37263258 0.82035927 0.59416579 0.07595274]]

 [[0.5711624  0.04357343 0.62988447 0.65192286 0.69244069]
  [0.791548   0.74761589 0.63384425 0.58622038 0.48526568]
  [0.52477016 0.87926919 0.12536088 0.35580098 0.76053918]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [13]:
# your code/answer here

print(a)

print(e)


#Yes, cause C is an array created with ones method

[[[0.94919224 0.74039184 0.278346   0.4858283  0.81142966]
  [0.33051209 0.84516726 0.93786966 0.56621057 0.51074151]
  [0.42817177 0.37263258 0.82035927 0.59416579 0.07595274]]

 [[0.5711624  0.04357343 0.62988447 0.65192286 0.69244069]
  [0.791548   0.74761589 0.63384425 0.58622038 0.48526568]
  [0.52477016 0.87926919 0.12536088 0.35580098 0.76053918]]]
[[[0.94919224 0.74039184 0.278346   0.4858283  0.81142966]
  [0.33051209 0.84516726 0.93786966 0.56621057 0.51074151]
  [0.42817177 0.37263258 0.82035927 0.59416579 0.07595274]]

 [[0.5711624  0.04357343 0.62988447 0.65192286 0.69244069]
  [0.791548   0.74761589 0.63384425 0.58622038 0.48526568]
  [0.52477016 0.87926919 0.12536088 0.35580098 0.76053918]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [14]:
# your code here

d_max = np.max(d)

d_min = np.min(d)

d_mean = np.mean(d)


print(d_max)
print(d_min)
print(d_mean)

1.9491922406773625
1.0435734277318915
1.574206323551092


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [48]:
# your code here

f = np.empty((2,3,5))

print(f)

[[[1.94919224 1.74039184 1.278346   1.4858283  1.81142966]
  [1.33051209 1.84516726 1.93786966 1.56621057 1.51074151]
  [1.42817177 1.37263258 1.82035927 1.59416579 1.07595274]]

 [[1.5711624  1.04357343 1.62988447 1.65192286 1.69244069]
  [1.791548   1.74761589 1.63384425 1.58622038 1.48526568]
  [1.52477016 1.87926919 1.12536088 1.35580098 1.76053918]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [56]:
# your code here

lst_f = []


for x in d:
    for z in x:
        for y in z:
            if y > d_min and y < d_mean:
                lst_f.append(25)
            elif y > d_mean and y < d_max:
                lst_f.append(75)
            elif y == d_mean:
                lst_f.append(50)
            elif y ==d_min:
                lst_f.append(0)
            elif y == d_max:
                lst_f.append(100)
                
                
lst_f

array_f = np.array(lst_f)

f = np.reshape(array_f, (2,3,5))


f

array([[[100,  75,  25,  25,  75],
        [ 25,  75,  75,  25,  25],
        [ 25,  25,  75,  75,  25]],

       [[ 25,   0,  75,  75,  75],
        [ 75,  75,  75,  75,  25],
        [ 25,  75,  25,  25,  75]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [57]:
# your code here

f

array([[[100,  75,  25,  25,  75],
        [ 25,  75,  75,  25,  25],
        [ 25,  25,  75,  75,  25]],

       [[ 25,   0,  75,  75,  75],
        [ 75,  75,  75,  75,  25],
        [ 25,  75,  25,  25,  75]]])

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here