# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [3]:
# your code here
print(np.__version__)

1.20.3


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [4]:
# Method 1
#random.random creates random float values between 0 and 1 (1 not included). We provide as input the shape
a = np.random.random(size=(2,3,5))
print(a)

[[[0.45042602 0.88836101 0.67249418 0.35368989 0.2106621 ]
  [0.43261252 0.16624859 0.48976024 0.53674269 0.2306427 ]
  [0.87456477 0.76648544 0.12115395 0.41343812 0.80072039]]

 [[0.22259706 0.77283324 0.84516887 0.39945478 0.46892946]
  [0.52681866 0.6835956  0.30427686 0.89799583 0.72143351]
  [0.56693116 0.14887491 0.68612346 0.36715513 0.15148542]]]


In [22]:
#Method 2
#random.randn generates random float values between 0 and 1 based on the normal distribution, 
#having the mean equal to 0 and variation equal to 1.

a = np.random.randn(2,3,5)
print(a)

[[[-1.12147229  2.28875481 -0.24890365  1.10765741  1.56361773]
  [ 0.16736379  1.44047875  0.51580812  0.97796607  0.28891117]
  [ 0.45660575 -0.32384668  0.13000476 -0.11719279  0.22016187]]

 [[ 1.16563502 -0.41438948  1.39035977 -0.2168152   1.29886388]
  [ 0.45646185  0.30145095  2.0619674   0.57916816 -0.41762892]
  [-1.17580556  0.45181011 -0.47549853  3.20855224  0.32349438]]]


In [23]:
# Method 3 - let's say I want to create the array with random values between 0 and 100
#random.randint generates random values (int by default) for the given range. We provide the range and shape
a = np.random.randint(0,101,(2,3,5))
print(a)

[[[69 16 53 33 76]
  [66 96 21 59 49]
  [13  1 19 90 46]]

 [[41 45 29 82  9]
  [34 57 96 12 16]
  [12 84 30 97 49]]]


#### 4. Print *a*.


In [24]:
# your code here
#Keeping the third option (ints with randint) for simplicity
print(a)

[[[69 16 53 33 76]
  [66 96 21 59 49]
  [13  1 19 90 46]]

 [[41 45 29 82  9]
  [34 57 96 12 16]
  [12 84 30 97 49]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [26]:
# your code here
b = np.ones((5,2,3))  #equals np.ones(shape(5,2,3))

#### 6. Print *b*.


In [27]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [35]:
# your code here
# to check if a and b have the same size (i.e. number of elements) we use array_name.size
print('size of a:',a.size)
print('size of b:',b.size)
print('a and b have the same size:', a.size == b.size)

print('a and b have the same shape:',a.shape == b.shape)

#these 2 arrays have the same size BUT different shapes

size of a: 30
size of b: 30
a and b have the same size: True
a and b have the same shape: False


#### 8. Are you able to add *a* and *b*? Why or why not?


In [ ]:
# your answer here
# Answer: we can add a and b because they have the same size (number of elements). However,
# to add 2 arrays, they also must have the same shape. We need to reshape b first

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [36]:
# your code here
c = b.reshape(2,3,5)
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [37]:
# your code/answer here
d = a + c
print(d)

#Answer: now it works because both arrays have the same shape

[[[70. 17. 54. 34. 77.]
  [67. 97. 22. 60. 50.]
  [14.  2. 20. 91. 47.]]

 [[42. 46. 30. 83. 10.]
  [35. 58. 97. 13. 17.]
  [13. 85. 31. 98. 50.]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [38]:
# your code/answer here
print(a)
print(d)

#Answer: values in array d equal all values in array a + 1. Also, values in array d are floats because np.ones
#generates floats by default, whereas array a has integers because randint generates int by default. 
#The sum of float + int becomes float, which is why array d contains floats

[[[69 16 53 33 76]
  [66 96 21 59 49]
  [13  1 19 90 46]]

 [[41 45 29 82  9]
  [34 57 96 12 16]
  [12 84 30 97 49]]]
[[[70. 17. 54. 34. 77.]
  [67. 97. 22. 60. 50.]
  [14.  2. 20. 91. 47.]]

 [[42. 46. 30. 83. 10.]
  [35. 58. 97. 13. 17.]
  [13. 85. 31. 98. 50.]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [39]:
# your code here
e = a * c
print(e)

[[[69. 16. 53. 33. 76.]
  [66. 96. 21. 59. 49.]
  [13.  1. 19. 90. 46.]]

 [[41. 45. 29. 82.  9.]
  [34. 57. 96. 12. 16.]
  [12. 84. 30. 97. 49.]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [42]:
# your code/answer here
print(e == a)
print(e is a)

#Answer: values inside e equal values inside a, because we have multiplied each value in a * 1
#However, a and e are different objects

[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]
False


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [45]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(f'The max is {d_max}, the min is {d_min}, and the mean is {d_mean}')

The max is 98.0, the min is 2.0, and the mean is 47.666666666666664


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [50]:
# your code here
f = np.empty([2,3,5])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [55]:
#Just copying all values in d again for reference:
print(d)
print(d_max)
print(d_min)
print(d_mean)

[[[70. 17. 54. 34. 77.]
  [67. 97. 22. 60. 50.]
  [14.  2. 20. 91. 47.]]

 [[42. 46. 30. 83. 10.]
  [35. 58. 97. 13. 17.]
  [13. 85. 31. 98. 50.]]]
98.0
2.0
47.666666666666664


In [75]:
# your code here

# Note: I have had problems to append the new values to the already created empty list
# The code below is not exactly what was asked (first I generate a new flat list, then I reshape it), but
# it achieves the same result

list_updated = []
for big_list in d:
    for small_list in big_list:
        for value in small_list:
            if value > d_min and value < d_mean:
                value = 25
            elif value > d_mean and value < d_max:
                value = 75
            elif value == d_mean:
                value = 50
            elif value == d_min:
                value = 0
            else:
                value = 100
            list_updated.append(value)

f = np.array(list_updated).reshape(2,3,5)

print(f)


[[[ 75  25  75  25  75]
  [ 75  75  25  75  75]
  [ 25   0  25  75  25]]

 [[ 25  25  25  75  25]
  [ 25  75  75  25  25]
  [ 25  75  25 100  75]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [78]:
# your code here
print(d)
print()
print(f)

#Answer: yes, the result for f is as expected

[[[70. 17. 54. 34. 77.]
  [67. 97. 22. 60. 50.]
  [14.  2. 20. 91. 47.]]

 [[42. 46. 30. 83. 10.]
  [35. 58. 97. 13. 17.]
  [13. 85. 31. 98. 50.]]]

[[[ 75  25  75  25  75]
  [ 75  75  25  75  75]
  [ 25   0  25  75  25]]

 [[ 25  25  25  75  25]
  [ 25  75  75  25  25]
  [ 25  75  25 100  75]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [80]:
# your code here

list_updated_2 = []
for big_list in d:
    for small_list in big_list:
        for value in small_list:
            if value > d_min and value < d_mean:
                value = 'B'
            elif value > d_mean and value < d_max:
                value = 'D'
            elif value == d_mean:
                value = 'C'
            elif value == d_min:
                value = 'A'
            else:
                value = 'E'
            list_updated_2.append(value)

g = np.array(list_updated_2).reshape(2,3,5)

print(g)

[[['D' 'B' 'D' 'B' 'D']
  ['D' 'D' 'B' 'D' 'D']
  ['B' 'A' 'B' 'D' 'B']]

 [['B' 'B' 'B' 'D' 'B']
  ['B' 'D' 'D' 'B' 'B']
  ['B' 'D' 'B' 'E' 'D']]]
