# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [52]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [53]:
# your code here
np.version.version

'1.21.5'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [54]:
# Method 1
a = np.random.random((2,3,5))

In [55]:
# Method 2
a = np.random.rand(2,3,5)

In [56]:
# Method 3
# I don't know! Other ways like np.ones() or np.arange() would also create arrays, whose content I could mathematically change into random numbers afterwards, but why do two steps instead of one?

#### 4. Print *a*.


In [57]:
# your code here
print(a)

[[[0.66407689 0.94249516 0.04647149 0.86750956 0.26386561]
  [0.09618169 0.34545946 0.88745855 0.61773872 0.24663683]
  [0.07340457 0.74372877 0.87338146 0.14233951 0.18860584]]

 [[0.02119918 0.87088232 0.56582874 0.89502201 0.06453057]
  [0.23817208 0.38428596 0.90832534 0.72790736 0.22907889]
  [0.47310153 0.38067001 0.12087035 0.723798   0.1167673 ]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [58]:
# your code here
b = np.ones((5,2,3), dtype = int)

#### 6. Print *b*.


In [59]:
# your code here
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [60]:
# your code here
#YES:
a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [61]:
# your answer here
#No, a+b gives an error as the arrays do have different shapes. One of them has to be reshaped to be able to do the Addition.

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [62]:
# your code here
c = b.reshape(a.shape)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [63]:
# your code/answer here
d = a+c
d
#Because now both arrays have the same shape, there is always a matching position for each number in a and c, so it is clear which numbers are to be added.

array([[[1.66407689, 1.94249516, 1.04647149, 1.86750956, 1.26386561],
        [1.09618169, 1.34545946, 1.88745855, 1.61773872, 1.24663683],
        [1.07340457, 1.74372877, 1.87338146, 1.14233951, 1.18860584]],

       [[1.02119918, 1.87088232, 1.56582874, 1.89502201, 1.06453057],
        [1.23817208, 1.38428596, 1.90832534, 1.72790736, 1.22907889],
        [1.47310153, 1.38067001, 1.12087035, 1.723798  , 1.1167673 ]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [64]:
# your code/answer here
print(a)
print(d)
#Well the array c held only ones. 
#So the addition of a+c resulted in the random numbers of a but now between 1 and 2, instead of between 0 and 1.
#E.g., the number in d[0,0,0] is 1 + a[0,0,0], and so on.

[[[0.66407689 0.94249516 0.04647149 0.86750956 0.26386561]
  [0.09618169 0.34545946 0.88745855 0.61773872 0.24663683]
  [0.07340457 0.74372877 0.87338146 0.14233951 0.18860584]]

 [[0.02119918 0.87088232 0.56582874 0.89502201 0.06453057]
  [0.23817208 0.38428596 0.90832534 0.72790736 0.22907889]
  [0.47310153 0.38067001 0.12087035 0.723798   0.1167673 ]]]
[[[1.66407689 1.94249516 1.04647149 1.86750956 1.26386561]
  [1.09618169 1.34545946 1.88745855 1.61773872 1.24663683]
  [1.07340457 1.74372877 1.87338146 1.14233951 1.18860584]]

 [[1.02119918 1.87088232 1.56582874 1.89502201 1.06453057]
  [1.23817208 1.38428596 1.90832534 1.72790736 1.22907889]
  [1.47310153 1.38067001 1.12087035 1.723798   1.1167673 ]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [65]:
# your code here
e = a*c

#### 13. Does *e* equal to *a*? Why or why not?


In [66]:
# your code/answer here
a == e
# Yes it does: Because c is only holding ones, the multiplication does not change anything but gives an unchanged array a.

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [67]:
# your code here
d_max = d.max()
d_min = d.min()
d_mean = d.mean()
print(d_max, d_min, d_mean)

1.942495162607959 1.0211991791111972 1.457326457864582


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [69]:
# your code here
f = np.empty(d.shape)
f

array([[[0.67734447, 0.75473707, 0.16609059, 0.23830211, 0.38899046],
        [0.30343346, 0.73817359, 0.34107315, 0.98368489, 0.24016596],
        [0.47168358, 0.30652894, 0.90716382, 0.51189928, 0.74868751]],

       [[0.68733529, 0.89680261, 0.26754308, 0.96525471, 0.99437861],
        [0.09705258, 0.87397358, 0.9356049 , 0.23363103, 0.20994961],
        [0.25608787, 0.03307156, 0.40749082, 0.52715848, 0.6815295 ]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [81]:
# your code here
condition_0 = (d == d_min)
condition_25 = (d > d_min) & (d < d_mean)
condition_50 = (d == d_mean)
condition_75 = (d > d_mean) & (d < d_max)
condition_100 = (d == d_max)
f[condition_0] = 0
f[condition_25] = 25
f[condition_50] = 50
f[condition_75] = 75
f[condition_100] = 100
print(d)
f

[[[1.66407689 1.94249516 1.04647149 1.86750956 1.26386561]
  [1.09618169 1.34545946 1.88745855 1.61773872 1.24663683]
  [1.07340457 1.74372877 1.87338146 1.14233951 1.18860584]]

 [[1.02119918 1.87088232 1.56582874 1.89502201 1.06453057]
  [1.23817208 1.38428596 1.90832534 1.72790736 1.22907889]
  [1.47310153 1.38067001 1.12087035 1.723798   1.1167673 ]]]


array([[[ 75., 100.,  25.,  75.,  25.],
        [ 25.,  25.,  75.,  75.,  25.],
        [ 25.,  75.,  75.,  25.,  25.]],

       [[  0.,  75.,  75.,  75.,  25.],
        [ 25.,  25.,  75.,  75.,  25.],
        [ 75.,  25.,  25.,  75.,  25.]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [82]:
# your code here
print(d)
print(f)
#Yes. :-)

[[[1.66407689 1.94249516 1.04647149 1.86750956 1.26386561]
  [1.09618169 1.34545946 1.88745855 1.61773872 1.24663683]
  [1.07340457 1.74372877 1.87338146 1.14233951 1.18860584]]

 [[1.02119918 1.87088232 1.56582874 1.89502201 1.06453057]
  [1.23817208 1.38428596 1.90832534 1.72790736 1.22907889]
  [1.47310153 1.38067001 1.12087035 1.723798   1.1167673 ]]]
[[[ 75. 100.  25.  75.  25.]
  [ 25.  25.  75.  75.  25.]
  [ 25.  75.  75.  25.  25.]]

 [[  0.  75.  75.  75.  25.]
  [ 25.  25.  75.  75.  25.]
  [ 75.  25.  25.  75.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [84]:
# your code here
f = f.astype(str)

f[condition_0] = "A"
f[condition_25] = "B"
f[condition_50] = "C"
f[condition_75] = "D"
f[condition_100] = "E"
print(f)

[[['D' 'E' 'B' 'D' 'B']
  ['B' 'B' 'D' 'D' 'B']
  ['B' 'D' 'D' 'B' 'B']]

 [['A' 'D' 'D' 'D' 'B']
  ['B' 'B' 'D' 'D' 'B']
  ['D' 'B' 'B' 'D' 'B']]]
