# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [79]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [80]:
# your code here
print(np.version.version)

1.17.3


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [81]:
# Method 1
a = np.random.random((2,3,5))

#OR a = np.random.rand(2,3,5)

print(a)

[[[0.27311985 0.03465887 0.22221441 0.78393803 0.30659928]
  [0.75788693 0.4201673  0.55869072 0.74734216 0.39027151]
  [0.65764303 0.05248178 0.70198932 0.81799566 0.85737568]]

 [[0.3069704  0.87229758 0.11767223 0.16495809 0.59018924]
  [0.84559491 0.90258597 0.80742494 0.62290233 0.30888967]
  [0.07091466 0.79460005 0.77640589 0.54677592 0.56660105]]]


In [82]:
# Method 2
N=2
M=3
Z=5
a = np.array([[[np.random.random() for z in range(Z)]for m in range(M)] for n in range(N)])

print(a)

[[[0.42945002 0.60105052 0.02083866 0.12014776 0.13224093]
  [0.61362046 0.74382264 0.10584652 0.28666462 0.48324301]
  [0.30953783 0.12304357 0.49434917 0.33838127 0.89898461]]

 [[0.32002822 0.682813   0.16168835 0.97711396 0.77073794]
  [0.50624622 0.69605808 0.31827209 0.20355265 0.96689331]
  [0.63596785 0.26940964 0.99227566 0.00504087 0.29335792]]]


In [83]:
# Method 3
a = np.random.randint(0, 10, (2,3,5))
print(a)

[[[2 1 3 2 9]
  [5 3 1 7 8]
  [9 0 6 8 6]]

 [[8 1 0 7 2]
  [8 1 8 2 6]
  [4 3 0 1 3]]]


#### 4. Print *a*.


In [84]:
# your code here
print(a)
print("\n")
print(a[0]) #Prints the 1st sub-array
print("\n")
print(a[:,0]) #Prints the 1st row of each sub-array
print("\n")
print(a[:,:,0]) #Prints the 1st column of the array
print("\n")
print(a[0][0][0]) #Prints the 1st element of the array
print("\n")
print("\n")
print(a[0][0]) #Prints the 1st row of the 1st sub-array
print("\n")
print(a[0][:,0]) #Prints the 1st column of the 1st sub-array



[[[2 1 3 2 9]
  [5 3 1 7 8]
  [9 0 6 8 6]]

 [[8 1 0 7 2]
  [8 1 8 2 6]
  [4 3 0 1 3]]]


[[2 1 3 2 9]
 [5 3 1 7 8]
 [9 0 6 8 6]]


[[2 1 3 2 9]
 [8 1 0 7 2]]


[[2 5 9]
 [8 8 4]]


2




[2 1 3 2 9]


[2 5 9]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [85]:
# your code here
b = np.full((5,2,3), 1)

#### 6. Print *b*.


In [86]:
# your code here
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [88]:
# your code here
print(np.size(a))

print(np.size(b))

30
30


#### 8. Are you able to add *a* and *b*? Why or why not?


In [89]:
# your answer here
print(np.shape(a))
print(np.shape(b))
c = np.add(a,b) #or c = a + b

#the 2 cannot be added since they have different shapes

(2, 3, 5)
(5, 2, 3)


ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [102]:
# your code here

c = np.transpose(b, (1,2,0))

print(c)
print(np.size(c))
print(np.shape(c))

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]
30
(2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [103]:
# your code/answer here
d = np.add(a,c)

print(d)

#It now works because, given the identical shape, each value of a can be actually summed to
#the respecive mirror one in c (Matrix Algebra)

[[[ 3  2  4  3 10]
  [ 6  4  2  8  9]
  [10  1  7  9  7]]

 [[ 9  2  1  8  3]
  [ 9  2  9  3  7]
  [ 5  4  1  2  4]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [104]:
# your code/answer here
print(a)
print("\n")
print(d)

#YES, each value of d = a + 1

[[[2 1 3 2 9]
  [5 3 1 7 8]
  [9 0 6 8 6]]

 [[8 1 0 7 2]
  [8 1 8 2 6]
  [4 3 0 1 3]]]


[[[ 3  2  4  3 10]
  [ 6  4  2  8  9]
  [10  1  7  9  7]]

 [[ 9  2  1  8  3]
  [ 9  2  9  3  7]
  [ 5  4  1  2  4]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [105]:
# your code here
e  = np.multiply(a,c)

print(e)

[[[2 1 3 2 9]
  [5 3 1 7 8]
  [9 0 6 8 6]]

 [[8 1 0 7 2]
  [8 1 8 2 6]
  [4 3 0 1 3]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [106]:
# your code/answer here
check = e - a
print(check)

#YES, it does, since multiply a times c, corresponds to multiply each value of a for
#each value of c, but each value of c == 1, thus e == a

[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [107]:
# your code here
print(d)
print("\n")
d_max = np.max(d)
print(d_max)
print("\n")
d_min = np.min(d)
print(d_min)
print("\n")
d_mean = np.mean(d)
print(d_mean)
print("\n")

[[[ 3  2  4  3 10]
  [ 6  4  2  8  9]
  [10  1  7  9  7]]

 [[ 9  2  1  8  3]
  [ 9  2  9  3  7]
  [ 5  4  1  2  4]]]


10


1


5.133333333333334




#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [110]:
# your code here
f = np.empty((2,3,5))
print(d)
print(f)

[[[ 3  2  4  3 10]
  [ 6  4  2  8  9]
  [10  1  7  9  7]]

 [[ 9  2  1  8  3]
  [ 9  2  9  3  7]
  [ 5  4  1  2  4]]]
[[[6.91118483e-310 1.70763791e-316 0.00000000e+000 0.00000000e+000
   0.00000000e+000]
  [5.02034658e+175 1.61964606e-051 2.57642435e-056 4.66541477e-033
   1.53154679e-047]
  [1.47763641e+248 1.16096346e-028 7.69165785e+218 1.35617292e+248
   6.07870605e+170]]

 [[1.11597885e-046 8.97800512e-067 4.08606197e+179 4.30712432e-096
   6.32299154e+233]
  [6.48224638e+170 5.22411352e+257 5.74020278e+180 8.37174974e-144
   1.41529402e+161]
  [9.16651763e-072 4.95463596e+097 1.69422171e-052 2.91142527e+126
   6.91118335e-310]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [115]:
# your code here
f[(d_min < d) & (d < d_mean)] = 25
f[(d_mean < d) & (d < d_max)] = 75
f[d == d_mean] = 50
f[d == d_min] = 0
f[d == d_max] = 100


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [116]:
# your code here
print(d)
print("\n")
print(f)

[[[ 3  2  4  3 10]
  [ 6  4  2  8  9]
  [10  1  7  9  7]]

 [[ 9  2  1  8  3]
  [ 9  2  9  3  7]
  [ 5  4  1  2  4]]]


[[[ 25.  25.  25.  25. 100.]
  [ 75.  25.  25.  75.  75.]
  [100.   0.  75.  75.  75.]]

 [[ 75.  25.   0.  75.  25.]
  [ 75.  25.  75.  25.  75.]
  [ 25.  25.   0.  25.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [122]:
# your code here
g = np.empty((2,3,5), dtype=str)

g[(d_min < d) & (d < d_mean)] = "A"
g[(d_mean < d) & (d < d_max)] = "B"
g[d == d_mean] = "C"
g[d == d_min] = "D"
g[d == d_max] = "E"

print(d)
print("\n")
print(g)

[[[ 3  2  4  3 10]
  [ 6  4  2  8  9]
  [10  1  7  9  7]]

 [[ 9  2  1  8  3]
  [ 9  2  9  3  7]
  [ 5  4  1  2  4]]]


[[['A' 'A' 'A' 'A' 'E']
  ['B' 'A' 'A' 'B' 'B']
  ['E' 'D' 'B' 'B' 'B']]

 [['B' 'A' 'D' 'B' 'A']
  ['B' 'A' 'B' 'A' 'B']
  ['A' 'A' 'D' 'A' 'A']]]
