# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [70]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [71]:
# your code here
print(np.__version__)

1.18.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [72]:
# Method 1
a = np.random.random((2, 3, 5))
a

array([[[0.92853772, 0.66446377, 0.13138034, 0.26211625, 0.55033108],
        [0.36307577, 0.52370193, 0.35527129, 0.44645313, 0.18846449],
        [0.20829702, 0.58517437, 0.36632549, 0.89739812, 0.09423203]],

       [[0.09504691, 0.66489362, 0.75330232, 0.77055047, 0.4735184 ],
        [0.15173102, 0.76202474, 0.90911125, 0.67448273, 0.24129992],
        [0.44651122, 0.57587683, 0.24643351, 0.86659899, 0.59553369]]])

In [73]:
# Method 2
# change this for random and reshape
lst = [i for i in range(10)] # have to make this list comp into a random generator

#a = np.array(lst)
#a.reshape(2, 3, 5)
#a

In [74]:
# Method 3


#### 4. Print *a*.


In [75]:
# your code here
print(a)

[[[0.92853772 0.66446377 0.13138034 0.26211625 0.55033108]
  [0.36307577 0.52370193 0.35527129 0.44645313 0.18846449]
  [0.20829702 0.58517437 0.36632549 0.89739812 0.09423203]]

 [[0.09504691 0.66489362 0.75330232 0.77055047 0.4735184 ]
  [0.15173102 0.76202474 0.90911125 0.67448273 0.24129992]
  [0.44651122 0.57587683 0.24643351 0.86659899 0.59553369]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [76]:
# your code here
b = np.ones((5, 2, 3), dtype = int)

#### 6. Print *b*.


In [77]:
# your code here
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [82]:
# your code here
print(a.size == b.size)
#print("No. They do not have the same size.")
#print("Yes. They do have the same size.")

True


#### 8. Are you able to add *a* and *b*? Why or why not?


In [97]:
# your answer here
#np.add(a,b)
a + b
# No, I'm not able to add them together because they do not have the same shape.

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [172]:
# your code here
c = b.transpose(1,2,0) # we have to add the axis 1,2,0 so it knows the order to transpose
print(b.shape)

(5, 2, 3)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [173]:
# your code/answer here
d = a + c
d
# Now it works because they have the same shape

array([[[1.92853772, 1.66446377, 1.13138034, 1.26211625, 1.55033108],
        [1.36307577, 1.52370193, 1.35527129, 1.44645313, 1.18846449],
        [1.20829702, 1.58517437, 1.36632549, 1.89739812, 1.09423203]],

       [[1.09504691, 1.66489362, 1.75330232, 1.77055047, 1.4735184 ],
        [1.15173102, 1.76202474, 1.90911125, 1.67448273, 1.24129992],
        [1.44651122, 1.57587683, 1.24643351, 1.86659899, 1.59553369]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [217]:
# your code/answer here
print("Array 'a':\n", a)
print("\n")

# print("Array 'b':\n", b) # b was just an array of ones
# print("\n")

print("Array 'c':\n", c) # c is b transposed to match a so that we could later add them together
print("\n")

print("Array 'd':\n", d) # d is a + c, therefore d consists of just adding +1 to the array a

Array 'a':
 [[[0.92853772 0.66446377 0.13138034 0.26211625 0.55033108]
  [0.36307577 0.52370193 0.35527129 0.44645313 0.18846449]
  [0.20829702 0.58517437 0.36632549 0.89739812 0.09423203]]

 [[0.09504691 0.66489362 0.75330232 0.77055047 0.4735184 ]
  [0.15173102 0.76202474 0.90911125 0.67448273 0.24129992]
  [0.44651122 0.57587683 0.24643351 0.86659899 0.59553369]]]


Array 'c':
 [[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


Array 'd':
 [[[1.92853772 1.66446377 1.13138034 1.26211625 1.55033108]
  [1.36307577 1.52370193 1.35527129 1.44645313 1.18846449]
  [1.20829702 1.58517437 1.36632549 1.89739812 1.09423203]]

 [[1.09504691 1.66489362 1.75330232 1.77055047 1.4735184 ]
  [1.15173102 1.76202474 1.90911125 1.67448273 1.24129992]
  [1.44651122 1.57587683 1.24643351 1.86659899 1.59553369]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [223]:
# your code here
e = a * c
e

array([[[0.92853772, 0.66446377, 0.13138034, 0.26211625, 0.55033108],
        [0.36307577, 0.52370193, 0.35527129, 0.44645313, 0.18846449],
        [0.20829702, 0.58517437, 0.36632549, 0.89739812, 0.09423203]],

       [[0.09504691, 0.66489362, 0.75330232, 0.77055047, 0.4735184 ],
        [0.15173102, 0.76202474, 0.90911125, 0.67448273, 0.24129992],
        [0.44651122, 0.57587683, 0.24643351, 0.86659899, 0.59553369]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [226]:
# your code/answer here
e == a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [ ]:
# your code here

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [ ]:
# your code here

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [1]:
# your code here

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here