# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [34]:
import numpy as np

#### 2. Print your NumPy version.

In [35]:
np.version.version

'1.16.4'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [36]:
a = np.random.random((2,3,5))

In [37]:
a_2 = np.random.rand(2,3,5)

In [38]:
#Generate ints between x and y, with a size of z
a_3 = np.random.randint(1, high = 10, size = (2,3,5))

#### 4. Print *a*.


In [39]:
a

array([[[0.73591276, 0.46063581, 0.32819152, 0.77741868, 0.76964407],
        [0.73095653, 0.19906888, 0.81812895, 0.4166102 , 0.3089727 ],
        [0.26941977, 0.28184013, 0.17078811, 0.47372053, 0.46723845]],

       [[0.70636388, 0.97440735, 0.33742544, 0.6679823 , 0.30358662],
        [0.98769745, 0.27968746, 0.60159691, 0.1918013 , 0.23161095],
        [0.66497822, 0.61546454, 0.29706063, 0.09519018, 0.87128549]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [40]:
b = np.ones((5,2,3), dtype = int)

#### 6. Print *b*.


In [41]:
b

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [42]:
a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


No, because NumPy arrays with different sizes cannot be added or subtracted

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [43]:
c = np.transpose(b).reshape((2,3,5))
c

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [44]:
d = a + c
d
# Now it works because both arrays have the same shape

array([[[1.73591276, 1.46063581, 1.32819152, 1.77741868, 1.76964407],
        [1.73095653, 1.19906888, 1.81812895, 1.4166102 , 1.3089727 ],
        [1.26941977, 1.28184013, 1.17078811, 1.47372053, 1.46723845]],

       [[1.70636388, 1.97440735, 1.33742544, 1.6679823 , 1.30358662],
        [1.98769745, 1.27968746, 1.60159691, 1.1918013 , 1.23161095],
        [1.66497822, 1.61546454, 1.29706063, 1.09519018, 1.87128549]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [45]:
print("A", a)
print("D", d)

# "d" is "a" plus 1, because c (which was b transposed and had values of 1)
# was summed up to a. 

A [[[0.73591276 0.46063581 0.32819152 0.77741868 0.76964407]
  [0.73095653 0.19906888 0.81812895 0.4166102  0.3089727 ]
  [0.26941977 0.28184013 0.17078811 0.47372053 0.46723845]]

 [[0.70636388 0.97440735 0.33742544 0.6679823  0.30358662]
  [0.98769745 0.27968746 0.60159691 0.1918013  0.23161095]
  [0.66497822 0.61546454 0.29706063 0.09519018 0.87128549]]]
D [[[1.73591276 1.46063581 1.32819152 1.77741868 1.76964407]
  [1.73095653 1.19906888 1.81812895 1.4166102  1.3089727 ]
  [1.26941977 1.28184013 1.17078811 1.47372053 1.46723845]]

 [[1.70636388 1.97440735 1.33742544 1.6679823  1.30358662]
  [1.98769745 1.27968746 1.60159691 1.1918013  1.23161095]
  [1.66497822 1.61546454 1.29706063 1.09519018 1.87128549]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [46]:
e = a * c
e

array([[[0.73591276, 0.46063581, 0.32819152, 0.77741868, 0.76964407],
        [0.73095653, 0.19906888, 0.81812895, 0.4166102 , 0.3089727 ],
        [0.26941977, 0.28184013, 0.17078811, 0.47372053, 0.46723845]],

       [[0.70636388, 0.97440735, 0.33742544, 0.6679823 , 0.30358662],
        [0.98769745, 0.27968746, 0.60159691, 0.1918013 , 0.23161095],
        [0.66497822, 0.61546454, 0.29706063, 0.09519018, 0.87128549]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [47]:
e == a

# Yes, because it multiplies each value by 1. eg. 0.43967539 x 1 = 0.43967539

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [48]:
d_min = d.min()
d_max = d.max()
d_mean = d.mean()


In [49]:
d_min

1.0951901752358855

In [50]:
d_mean

1.5011561940235725

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [51]:
f = np.empty([2,3,5])
f

array([[[0.73591276, 0.46063581, 0.32819152, 0.77741868, 0.76964407],
        [0.73095653, 0.19906888, 0.81812895, 0.4166102 , 0.3089727 ],
        [0.26941977, 0.28184013, 0.17078811, 0.47372053, 0.46723845]],

       [[0.70636388, 0.97440735, 0.33742544, 0.6679823 , 0.30358662],
        [0.98769745, 0.27968746, 0.60159691, 0.1918013 , 0.23161095],
        [0.66497822, 0.61546454, 0.29706063, 0.09519018, 0.87128549]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [55]:
f = np.copy(d)
f[(f > d_min) & (f < d_mean)] = 25
f[(f > d_mean) & (f < d_max)] = 75
f[(f == d_mean)] = 50
f[(f == d_min)] = 0
f[(f == d_max)] = 100

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [56]:
print(f)

[[[ 75.  25.  25.  75.  75.]
  [ 75.  25.  75.  25.  25.]
  [ 25.  25.  25.  25.  25.]]

 [[ 75.  75.  25.  75.  25.]
  [100.  25.  75.  25.  25.]
  [ 75.  75.  25.   0.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [60]:
f2 = f.astype(str)

In [74]:
f2[(f2 == "0.")] = "A"
f2[(f2 == "25.0")] = "B"
f2[(f2 == "50.0")] = "C"
f2[(f2 == "75.0")] = "D"
f2[(f2 == "100.0")] = "E"

In [75]:
f2

array([[['A', 'B', 'B', 'A', 'A'],
        ['A', 'B', 'A', 'B', 'B'],
        ['B', 'B', 'B', 'B', 'B']],

       [['A', 'A', 'B', 'A', 'B'],
        ['E', 'B', 'A', 'B', 'B'],
        ['A', 'A', 'B', '0.0', 'A']]], dtype='<U32')