# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [2]:
print(np.__version__)

1.19.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a = np.random.random((2,3,5))

In [4]:
# Method 2
a = np.random.sample((2, 3, 5))

In [ ]:
# Method 3
#??

#### 4. Print *a*.


In [5]:
print(a)

[[[0.00486623 0.13678838 0.74915061 0.76816421 0.27638746]
  [0.7912251  0.58458469 0.54010411 0.83793232 0.52410363]
  [0.53537841 0.40147873 0.39443573 0.82765273 0.34869305]]

 [[0.1315344  0.2411162  0.34621881 0.90484895 0.07631258]
  [0.21183472 0.7382578  0.42936884 0.25971955 0.13429596]
  [0.90418081 0.09846739 0.85165841 0.77377716 0.44248435]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [6]:
b = np.ones((5, 2, 3))

#### 6. Print *b*.


In [ ]:
print(b)

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [7]:
# your code here
print(a.size == b.size)

True


#### 8. Are you able to add *a* and *b*? Why or why not?


In [ ]:
#We can´t add them because they have different shapes


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [8]:
c = np.transpose(b, axes=(1, 2, 0))
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [9]:
# we can add them because now they have the same shape
d = a + c
print(d)

[[[1.00486623 1.13678838 1.74915061 1.76816421 1.27638746]
  [1.7912251  1.58458469 1.54010411 1.83793232 1.52410363]
  [1.53537841 1.40147873 1.39443573 1.82765273 1.34869305]]

 [[1.1315344  1.2411162  1.34621881 1.90484895 1.07631258]
  [1.21183472 1.7382578  1.42936884 1.25971955 1.13429596]
  [1.90418081 1.09846739 1.85165841 1.77377716 1.44248435]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [10]:
print(a, '\n\n\n')
print(d)
#each value has +1 because we summed the values of a and c. all the values in c were (1)

[[[0.00486623 0.13678838 0.74915061 0.76816421 0.27638746]
  [0.7912251  0.58458469 0.54010411 0.83793232 0.52410363]
  [0.53537841 0.40147873 0.39443573 0.82765273 0.34869305]]

 [[0.1315344  0.2411162  0.34621881 0.90484895 0.07631258]
  [0.21183472 0.7382578  0.42936884 0.25971955 0.13429596]
  [0.90418081 0.09846739 0.85165841 0.77377716 0.44248435]]] 



[[[1.00486623 1.13678838 1.74915061 1.76816421 1.27638746]
  [1.7912251  1.58458469 1.54010411 1.83793232 1.52410363]
  [1.53537841 1.40147873 1.39443573 1.82765273 1.34869305]]

 [[1.1315344  1.2411162  1.34621881 1.90484895 1.07631258]
  [1.21183472 1.7382578  1.42936884 1.25971955 1.13429596]
  [1.90418081 1.09846739 1.85165841 1.77377716 1.44248435]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [11]:
e = a * c
print(e)

[[[0.00486623 0.13678838 0.74915061 0.76816421 0.27638746]
  [0.7912251  0.58458469 0.54010411 0.83793232 0.52410363]
  [0.53537841 0.40147873 0.39443573 0.82765273 0.34869305]]

 [[0.1315344  0.2411162  0.34621881 0.90484895 0.07631258]
  [0.21183472 0.7382578  0.42936884 0.25971955 0.13429596]
  [0.90418081 0.09846739 0.85165841 0.77377716 0.44248435]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [12]:
#they are the same because c is an array of only 1's. So we are multiplying every value of a by 1
print(np.array_equal(e, a))

True


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [13]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

print(d_max)
print(d_min)
print(d_mean)

1.9048489476930555
1.0048662279142215
1.475500711046931


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [14]:
f = np.empty([2, 3, 5])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [15]:
f = []
for x in np.nditer(d):
    if d_min < x < d_mean:
        f += [25]
    if d_mean < x < d_max:
        f += [75]
    if x == d_mean:
        f += [50]
    if x == d_min:
        f += [0]
    if x == d_max:
        f += [100]
    
        
f = np.reshape(f, d.shape) 
print(f)

[[[  0  25  75  75  25]
  [ 75  75  75  75  75]
  [ 75  25  25  75  25]]

 [[ 25  25  25 100  25]
  [ 25  75  25  25  25]
  [ 75  25  75  75  25]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [16]:
print(f)
print(d)

[[[  0  25  75  75  25]
  [ 75  75  75  75  75]
  [ 75  25  25  75  25]]

 [[ 25  25  25 100  25]
  [ 25  75  25  25  25]
  [ 75  25  75  75  25]]]
[[[1.00486623 1.13678838 1.74915061 1.76816421 1.27638746]
  [1.7912251  1.58458469 1.54010411 1.83793232 1.52410363]
  [1.53537841 1.40147873 1.39443573 1.82765273 1.34869305]]

 [[1.1315344  1.2411162  1.34621881 1.90484895 1.07631258]
  [1.21183472 1.7382578  1.42936884 1.25971955 1.13429596]
  [1.90418081 1.09846739 1.85165841 1.77377716 1.44248435]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [17]:
j = []
for x in np.nditer(d):
    if d_min < x < d_mean:
        j += ['B']
    if d_mean < x < d_max:
        j += ['D']
    if x == d_mean:
        j += ['C']
    if x == d_min:
        j += ['A']
    if x == d_max:
        j += ['E']
    
j = np.reshape(j, d.shape) 
print(j)

[[['A' 'B' 'D' 'D' 'B']
  ['D' 'D' 'D' 'D' 'D']
  ['D' 'B' 'B' 'D' 'B']]

 [['B' 'B' 'B' 'E' 'B']
  ['B' 'D' 'B' 'B' 'B']
  ['D' 'B' 'D' 'D' 'B']]]
