# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [2]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [3]:
# your code here
print(np. __version__)

1.24.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [4]:
# Method 1
a = np.random.rand(2,3,5)


In [5]:
# Method 2

a = np.random.randn(2,3,5)

In [18]:
# Method 3

a = np.random.randint(10000,size = (2,3,5))

#### 4. Print *a*.


In [7]:
# your code here
a

array([[[8403, 5316, 6339, 1936, 6078],
        [ 768, 5510, 5795, 8321, 6965],
        [7672, 2741, 5836, 4365, 6080]],

       [[6036, 2325, 8478, 9486, 5833],
        [5138, 6564,  903, 1669, 6675],
        [6281, 2941, 7059, 1718, 4671]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [19]:
# your code here
b = np.ones(shape = (5,3,2), dtype = int)


#### 6. Print *b*.


In [20]:
# your code here
b

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [21]:
# your code here
print(a.shape)
print(b.shape)
a.shape == b.shape

(2, 3, 5)
(5, 3, 2)


False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [22]:
# your answer here
a+b
# I am not able because they are not the same shape

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,3,2) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [23]:
# your code here
c = b.transpose()
c.shape

(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [24]:
# your code/answer here

d = a + c
# it works now becasue by transposing the variable b it takes the same shape as a

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [25]:
# your code/answer here
print(a)
print(d)

# the values of d are plus 1 the values of a because of the addiction o a and c

[[[3221 8546 9378 7381 4049]
  [7038 3329 3378 3678 7633]
  [4890 9752 9094 4658  618]]

 [[9733 6700 8506 4661 5699]
  [4845 7634 4554 2434 4385]
  [8437  872 8551  155 8608]]]
[[[3222 8547 9379 7382 4050]
  [7039 3330 3379 3679 7634]
  [4891 9753 9095 4659  619]]

 [[9734 6701 8507 4662 5700]
  [4846 7635 4555 2435 4386]
  [8438  873 8552  156 8609]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [26]:
# your code here

e = a*c

#### 13. Does *e* equal to *a*? Why or why not?


In [ ]:
# your code/answer here

e == a

# a equals to e becasue a value times 1 is always the value

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [31]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean =np.mean(d)


156

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [28]:
# your code here
f = np.empty(d.shape)
f

array([[[-0.90125632, -0.49884927,  0.67843865,  0.44780927,
          1.43855835],
        [-0.25272754, -0.39347233, -0.13074275,  0.68259649,
         -0.64556267],
        [ 0.73851437, -0.54868685,  0.47604965, -1.03821367,
         -0.17148502]],

       [[-1.07091061,  0.43254853,  1.00275267,  0.66797931,
         -0.30161907],
        [ 0.88236507,  2.03968168,  0.18384814,  0.26181123,
         -1.64071659],
        [ 1.137504  ,  0.44397436,  0.8348345 , -0.35858541,
         -0.35941937]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [32]:
# your code here

for item in range(f.shape[0]):
    for item2 in range(f.shape[1]):
        for item3 in range(f.shape[2]):
            if d[item ][item2][item3] > d_min and d[item ][item2][item3] < d_mean:
                f[item ][item2][item3] = 25
            elif d[item ][item2][item3]< d_max and d[item ][item2][item3] > d_mean:
                f[item ][item2][item3] = 75
            elif d[item ][item2][item3] == d_mean:
                f[item ][item2][item3] = 50
            elif d[item ][item2][item3] == d_min:
                f[item ][item2][item3] = 0
            else:
                f[item ][item2][item3] = 100

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [33]:
# your code here
f

array([[[ 25.,  75.,  75.,  75.,  25.],
        [ 75.,  25.,  25.,  25.,  75.],
        [ 25., 100.,  75.,  25.,  25.]],

       [[ 75.,  75.,  75.,  25.,  25.],
        [ 25.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,   0.,  75.]]])

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [35]:
# your code here

TypeError: '<' not supported between instances of 'numpy.ndarray' and 'str'