# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here

import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here

print(np.__version__)

1.22.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1

a=np.random.random(size=(2,3,5))

In [20]:
# Method 2

In [ ]:
# Method 3

#### 4. Print *a*.


In [4]:
# your code here

print(a)

[[[0.25945837 0.40460239 0.12128721 0.2810712  0.28739955]
  [0.41370115 0.60746653 0.76558108 0.87806809 0.27977697]
  [0.02302042 0.26971514 0.49114352 0.51101896 0.59987445]]

 [[0.24181165 0.31349191 0.72005727 0.50557798 0.90010245]
  [0.85008852 0.2883589  0.99847719 0.45305741 0.66047039]
  [0.73599741 0.85065936 0.27513305 0.05797807 0.8089227 ]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [5]:
# your code here

b=np.ones(shape=(5,2,3), dtype=int)

#### 6. Print *b*.


In [6]:
# your code here
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [7]:
# your code here

a.shape==b.shape

False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [ ]:
# your answer here

#No because they have different shapes

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [17]:
# your code here

c=np.transpose(b, (1,2,0))
                

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [19]:
# your code/answer here

d=a+c

print(d)

#Now it works because the arrays have the same shape/structure

[[[1.25945837 1.40460239 1.12128721 1.2810712  1.28739955]
  [1.41370115 1.60746653 1.76558108 1.87806809 1.27977697]
  [1.02302042 1.26971514 1.49114352 1.51101896 1.59987445]]

 [[1.24181165 1.31349191 1.72005727 1.50557798 1.90010245]
  [1.85008852 1.2883589  1.99847719 1.45305741 1.66047039]
  [1.73599741 1.85065936 1.27513305 1.05797807 1.8089227 ]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [20]:
# your code/answer here

print(a)

print(d)

#The vaues of the d matrix are the values of the a matrix plus 1

[[[0.25945837 0.40460239 0.12128721 0.2810712  0.28739955]
  [0.41370115 0.60746653 0.76558108 0.87806809 0.27977697]
  [0.02302042 0.26971514 0.49114352 0.51101896 0.59987445]]

 [[0.24181165 0.31349191 0.72005727 0.50557798 0.90010245]
  [0.85008852 0.2883589  0.99847719 0.45305741 0.66047039]
  [0.73599741 0.85065936 0.27513305 0.05797807 0.8089227 ]]]
[[[1.25945837 1.40460239 1.12128721 1.2810712  1.28739955]
  [1.41370115 1.60746653 1.76558108 1.87806809 1.27977697]
  [1.02302042 1.26971514 1.49114352 1.51101896 1.59987445]]

 [[1.24181165 1.31349191 1.72005727 1.50557798 1.90010245]
  [1.85008852 1.2883589  1.99847719 1.45305741 1.66047039]
  [1.73599741 1.85065936 1.27513305 1.05797807 1.8089227 ]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [23]:
# your code here

e=a*c

print(e)

[[[0.25945837 0.40460239 0.12128721 0.2810712  0.28739955]
  [0.41370115 0.60746653 0.76558108 0.87806809 0.27977697]
  [0.02302042 0.26971514 0.49114352 0.51101896 0.59987445]]

 [[0.24181165 0.31349191 0.72005727 0.50557798 0.90010245]
  [0.85008852 0.2883589  0.99847719 0.45305741 0.66047039]
  [0.73599741 0.85065936 0.27513305 0.05797807 0.8089227 ]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [24]:
# your code/answer here

a==e

#They are equal since 'e' is 'a' multiplied by a matrix of ones

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [25]:
# your code here

d_max=d.max()

d_min=d.min()

d_mean=d.mean()

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [26]:
# your code here

f=np.empty((2,3,5), dtype=int)

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [27]:
# your code here

for i in range(len(d)):
    for j in range(len(d[i])):
        for k in range(len(d[i,j])): 
            if d_min<d[i,j,k]<d_mean:
                f[i,j,k]=25
            elif d_mean<d[i,j,k]<d_max:
                f[i,j,k]=75
            elif d[i,j,k]==d_mean:
                f[i,j,k]=50
            elif d[i,j,k]==d_min:
                f[i,j,k]=0
            elif d[i,j,k]==d_max:
                f[i,j,k]=100
            
print(f)

[[[ 25  25  25  25  25]
  [ 25  75  75  75  25]
  [  0  25  25  75  75]]

 [[ 25  25  75  75  75]
  [ 75  25 100  25  75]
  [ 75  75  25  25  75]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [28]:
# your code here

print(d)
print(f)

[[[1.25945837 1.40460239 1.12128721 1.2810712  1.28739955]
  [1.41370115 1.60746653 1.76558108 1.87806809 1.27977697]
  [1.02302042 1.26971514 1.49114352 1.51101896 1.59987445]]

 [[1.24181165 1.31349191 1.72005727 1.50557798 1.90010245]
  [1.85008852 1.2883589  1.99847719 1.45305741 1.66047039]
  [1.73599741 1.85065936 1.27513305 1.05797807 1.8089227 ]]]
[[[ 25  25  25  25  25]
  [ 25  75  75  75  25]
  [  0  25  25  75  75]]

 [[ 25  25  75  75  75]
  [ 75  25 100  25  75]
  [ 75  75  25  25  75]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [29]:
# your code here

f=np.empty((2,3,5), dtype=str)

for i in range(len(d)):
    for j in range(len(d[i])):
        for k in range(len(d[i,j])): 
            if d_min<d[i,j,k]<d_mean:
                f[i,j,k]='B'
            elif d_mean<d[i,j,k]<d_max:
                f[i,j,k]='D'
            elif d[i,j,k]==d_mean:
                f[i,j,k]='C'
            elif d[i,j,k]==d_min:
                f[i,j,k]='A'
            elif d[i,j,k]==d_max:
                f[i,j,k]='E'
            
print(f)

[[['B' 'B' 'B' 'B' 'B']
  ['B' 'D' 'D' 'D' 'B']
  ['A' 'B' 'B' 'D' 'D']]

 [['B' 'B' 'D' 'D' 'D']
  ['D' 'B' 'E' 'B' 'D']
  ['D' 'D' 'B' 'B' 'D']]]
