# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [6]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [9]:
# your code here
print(np.__version__)

1.17.3


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [19]:
# Method 1 - Return random floats in the half-open interval [0.0, 1.0).
a = np.random.random((2,3,5))
print(a)

[[[0.17443743 0.66304203 0.91639466 0.761683   0.45445189]
  [0.13227001 0.65104539 0.15674951 0.02315129 0.47056485]
  [0.372441   0.38270969 0.29324326 0.57227832 0.5162894 ]]

 [[0.69900907 0.93551099 0.64383459 0.42174404 0.63911086]
  [0.2890149  0.09052766 0.87975018 0.80855035 0.39437378]
  [0.13959938 0.80798493 0.18199464 0.86051483 0.84749658]]]


In [26]:
# Method 2 -Random values in a given shape.
b = np.random.rand(2,3,5)
print(b)

[[[0.23463339 0.39917455 0.42469133 0.72368797 0.12475843]
  [0.59074814 0.73346156 0.74762843 0.50228938 0.26140656]
  [0.13250885 0.17314649 0.91258735 0.1732175  0.94809788]]

 [[0.93535915 0.63076695 0.7766722  0.98390487 0.94185194]
  [0.85688182 0.95494376 0.85043283 0.32008728 0.43374024]
  [0.05810816 0.4781207  0.13479377 0.4960676  0.14642857]]]


In [25]:
# Method 3
x = np.random.random_sample((2,3,5))
print(x)

[[[0.18418349 0.28448931 0.08864634 0.39125031 0.0923661 ]
  [0.92069606 0.89193503 0.22078821 0.53969103 0.93959651]
  [0.40230295 0.23966969 0.25978184 0.85354753 0.34867091]]

 [[0.6176323  0.75547094 0.67464237 0.57882063 0.14915681]
  [0.58561816 0.45072179 0.86430452 0.99889826 0.08048098]
  [0.07187869 0.15940382 0.96871332 0.76168784 0.40847274]]]


#### 4. Print *a*.


In [27]:
# your code here
print(a)

[[[0.17443743 0.66304203 0.91639466 0.761683   0.45445189]
  [0.13227001 0.65104539 0.15674951 0.02315129 0.47056485]
  [0.372441   0.38270969 0.29324326 0.57227832 0.5162894 ]]

 [[0.69900907 0.93551099 0.64383459 0.42174404 0.63911086]
  [0.2890149  0.09052766 0.87975018 0.80855035 0.39437378]
  [0.13959938 0.80798493 0.18199464 0.86051483 0.84749658]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [66]:
# your code here
b = np.ones((5,2,3), dtype = float)

#### 6. Print *b*.


In [67]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [68]:
# your code here
print(a.size)
print(b.size)

30
30


#### 8. Are you able to add *a* and *b*? Why or why not?


In [34]:
# your answer here
# the array dimensions for the concatenation axis must match exactly, so it does not work

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [69]:
# your code here
c = np.transpose(b)
#d = np.ones((2,3,5), dtype = float)
print(d)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [77]:
# your code/answer here
d = np.append(a,c)
print(np.sum(ac))

[0.17443743 0.66304203 0.91639466 0.761683   0.45445189 0.13227001
 0.65104539 0.15674951 0.02315129 0.47056485 0.372441   0.38270969
 0.29324326 0.57227832 0.5162894  0.69900907 0.93551099 0.64383459
 0.42174404 0.63911086 0.2890149  0.09052766 0.87975018 0.80855035
 0.39437378 0.13959938 0.80798493 0.18199464 0.86051483 0.84749658
 1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.         1.         1.        ]
45.17976853180568


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [81]:
# your code/answer here
print(a)
print(d)
# d is 2-dimensional with 10 rows and 6 columns
# it had to be amended, because of the different group and row relation
# the arrays in a are longer because it has more rows

[[[0.17443743 0.66304203 0.91639466 0.761683   0.45445189]
  [0.13227001 0.65104539 0.15674951 0.02315129 0.47056485]
  [0.372441   0.38270969 0.29324326 0.57227832 0.5162894 ]]

 [[0.69900907 0.93551099 0.64383459 0.42174404 0.63911086]
  [0.2890149  0.09052766 0.87975018 0.80855035 0.39437378]
  [0.13959938 0.80798493 0.18199464 0.86051483 0.84749658]]]
[0.17443743 0.66304203 0.91639466 0.761683   0.45445189 0.13227001
 0.65104539 0.15674951 0.02315129 0.47056485 0.372441   0.38270969
 0.29324326 0.57227832 0.5162894  0.69900907 0.93551099 0.64383459
 0.42174404 0.63911086 0.2890149  0.09052766 0.87975018 0.80855035
 0.39437378 0.13959938 0.80798493 0.18199464 0.86051483 0.84749658
 1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.         1.         1.        ]
60


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [89]:
# your code here
# Compute the outer product of two vectors.
e = np.multiply.outer(a,c)
print(e)

[[[[[[0.17443743 0.17443743 0.17443743 0.17443743 0.17443743]
     [0.17443743 0.17443743 0.17443743 0.17443743 0.17443743]]

    [[0.17443743 0.17443743 0.17443743 0.17443743 0.17443743]
     [0.17443743 0.17443743 0.17443743 0.17443743 0.17443743]]

    [[0.17443743 0.17443743 0.17443743 0.17443743 0.17443743]
     [0.17443743 0.17443743 0.17443743 0.17443743 0.17443743]]]


   [[[0.66304203 0.66304203 0.66304203 0.66304203 0.66304203]
     [0.66304203 0.66304203 0.66304203 0.66304203 0.66304203]]

    [[0.66304203 0.66304203 0.66304203 0.66304203 0.66304203]
     [0.66304203 0.66304203 0.66304203 0.66304203 0.66304203]]

    [[0.66304203 0.66304203 0.66304203 0.66304203 0.66304203]
     [0.66304203 0.66304203 0.66304203 0.66304203 0.66304203]]]


   [[[0.91639466 0.91639466 0.91639466 0.91639466 0.91639466]
     [0.91639466 0.91639466 0.91639466 0.91639466 0.91639466]]

    [[0.91639466 0.91639466 0.91639466 0.91639466 0.91639466]
     [0.91639466 0.91639466 0.91639466 0.91639466 0.

#### 13. Does *e* equal to *a*? Why or why not?


In [91]:
# your code/answer here
print(a.size)
print(c.size)
print(e.size)
# e and a can not be equal because of the fact that its a 30 items out of are muliplied by 30 items out of c

30
30
900


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [94]:
# your code here
d_max = np.mean(d) 
print(d_max)
d_min = np.min(d)
print(d_min)
d_mean = np.mean(d)
print(d_mean)

0.7529961421967613
0.023151291719235467
0.7529961421967613


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [98]:
# your code here
# empty, unlike zeros, does not set the array values to zero, and may therefore be marginally faster. On the other hand, 
# it requires the user to manually set all the values in the array, and should be used with caution.
f = np.empty([2,3,5])
print(f)

[[[0.17443743 0.66304203 0.91639466 0.761683   0.45445189]
  [0.13227001 0.65104539 0.15674951 0.02315129 0.47056485]
  [0.372441   0.38270969 0.29324326 0.57227832 0.5162894 ]]

 [[0.69900907 0.93551099 0.64383459 0.42174404 0.63911086]
  [0.2890149  0.09052766 0.87975018 0.80855035 0.39437378]
  [0.13959938 0.80798493 0.18199464 0.86051483 0.84749658]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [126]:
# your code here
print(d)
        
v = [25 for i in d if i > d_min and i < d_mean]   
w = [75 for i in d if i < d_mean and i < d_max]
x = [50 for i in d if i == d_mean]
y = [0 for i in d if i == d_min]
z = [100 for i in d if i == d_max]

f = v+w+x+y+z  

print(np.array(f))

[0.17443743 0.66304203 0.91639466 0.761683   0.45445189 0.13227001
 0.65104539 0.15674951 0.02315129 0.47056485 0.372441   0.38270969
 0.29324326 0.57227832 0.5162894  0.69900907 0.93551099 0.64383459
 0.42174404 0.63911086 0.2890149  0.09052766 0.87975018 0.80855035
 0.39437378 0.13959938 0.80798493 0.18199464 0.86051483 0.84749658
 1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.         1.         1.        ]
[25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 75 75 75
 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75 75  0]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [125]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here