# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [61]:
import numpy as np

#### 2. Print your NumPy version.

In [62]:
print(np.__version__)

1.21.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [75]:
a = np.random.randint(0, 100, size=(2, 3, 5))
#print(a)

In [37]:
a = np.random.random((2,3,5))
#print(a)

In [36]:
a = np.random.rand(2,3,5)
#print(a)

#### 4. Print *a*.


In [64]:
print(a)

[[[16  0 45 23 85]
  [47 98  4 73 68]
  [90 26 10 61 27]]

 [[11 37 82 41 69]
  [78 28 24 24 99]
  [38 55 56 38 42]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [73]:
b = np.ones((5,2,3),dtype = int)

#### 6. Print *b*.


In [74]:
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [67]:
#We can use the len to find the size of an array
len(a) == len(b)

False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [76]:
#since they have difference shapes, we cannot same both arrays
#when we try to do it, it generates an error as shown below:
c = a + b
print(c)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [116]:
c = np.array(b).reshape((2,3,5))
print(c)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [136]:
d = a + c
print(d)
#Now it works because both arrays have the same size

[[[ 89  36  46  50  63]
  [ 45  82  18  17  53]
  [ 58  31  46  32  18]]

 [[100  75  51  43  23]
  [ 70  92  21  24  70]
  [ 91  32  22  23  14]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [137]:
print("array a:", a)
print("array d:",d)
len(a) == len(d) #to confirm that they have the same size, it returns True

#Now both array have the same size so we can use them to sum it

array a: [[[88 35 45 49 62]
  [44 81 17 16 52]
  [57 30 45 31 17]]

 [[99 74 50 42 22]
  [69 91 20 23 69]
  [90 31 21 22 13]]]
array d: [[[ 89  36  46  50  63]
  [ 45  82  18  17  53]
  [ 58  31  46  32  18]]

 [[100  75  51  43  23]
  [ 70  92  21  24  70]
  [ 91  32  22  23  14]]]


True

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [138]:
e = a*c
print(e)

[[[88 35 45 49 62]
  [44 81 17 16 52]
  [57 30 45 31 17]]

 [[99 74 50 42 22]
  [69 91 20 23 69]
  [90 31 21 22 13]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [139]:
e == a
#boht array have the same size and size c is an array with only ones, when we multiply a per c, we have the result a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [149]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean()
print("The max of d:", d_max, "and the min of d:", d_min, " and the mean of d:", d_mean)

The max of d: 100 and the min of d: 14  and the mean of d: 47.833333333333336


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [161]:
f = np.empty(shape = [2,3,5], dtype='object')
print(f)

[[[None None None None None]
  [None None None None None]
  [None None None None None]]

 [[None None None None None]
  [None None None None None]
  [None None None None None]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [162]:
for x, y in np.ndenumerate(d):
    if y == d_min:
        f[x] = 0
    elif y > d_min and y < d_mean:
        f[x] = 25
    elif y == d_mean:
        f[x] = 50
    elif y > d_mean and y < d_max:
        f[x] = 75
    elif y == d_max:
        f[x] = 100
print(f)

[[[75 25 25 75 75]
  [25 75 25 25 75]
  [75 25 25 25 25]]

 [[100 75 75 25 25]
  [75 75 25 25 75]
  [75 25 25 25 0]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [163]:
print(d)
print(f)

[[[ 89  36  46  50  63]
  [ 45  82  18  17  53]
  [ 58  31  46  32  18]]

 [[100  75  51  43  23]
  [ 70  92  21  24  70]
  [ 91  32  22  23  14]]]
[[[75 25 25 75 75]
  [25 75 25 25 75]
  [75 25 25 25 25]]

 [[100 75 75 25 25]
  [75 75 25 25 75]
  [75 25 25 25 0]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [164]:
for x, y in np.ndenumerate(d):
    if y == d_min:
        f[x] = "A"
    elif y > d_min and y < d_mean:
        f[x] = "B"
    elif y == d_mean:
        f[x] = "C"
    elif y > d_mean and y < d_max:
        f[x] = "D"
    elif y == d_max:
        f[x] = "E"
print(f)

[[['D' 'B' 'B' 'D' 'D']
  ['B' 'D' 'B' 'B' 'D']
  ['D' 'B' 'B' 'B' 'B']]

 [['E' 'D' 'D' 'B' 'B']
  ['D' 'D' 'B' 'B' 'D']
  ['D' 'B' 'B' 'B' 'A']]]
