# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [154]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [155]:
# your code here
print(np.__version__)

1.21.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [156]:
# Method 1
np.random.random(size = (2,3,5))


array([[[0.68292023, 0.24278407, 0.191408  , 0.47760188, 0.75541167],
        [0.28412999, 0.9129296 , 0.74898182, 0.21755002, 0.03217562],
        [0.87739275, 0.04313339, 0.67160761, 0.41725138, 0.5014646 ]],

       [[0.85972397, 0.66854972, 0.63699777, 0.38823569, 0.827936  ],
        [0.19931073, 0.72961601, 0.83171976, 0.61258272, 0.48052627],
        [0.12425274, 0.64061573, 0.23724638, 0.9023152 , 0.32547382]]])

In [157]:
# Method 2
a = np.random.rand(2,3,5)


In [158]:
# Method 3
np.random.randint(low=1, high=9, size=(2,3,5))


array([[[6, 8, 3, 7, 1],
        [8, 5, 1, 1, 8],
        [4, 3, 2, 7, 2]],

       [[4, 2, 7, 5, 8],
        [7, 6, 7, 3, 1],
        [7, 2, 2, 8, 5]]])

#### 4. Print *a*.


In [159]:
# your code here
print(a)

[[[0.69383785 0.31557124 0.77128259 0.97539613 0.36927456]
  [0.10023612 0.35177448 0.86386996 0.41433631 0.27002812]
  [0.67394949 0.69947547 0.53958484 0.76677251 0.3238135 ]]

 [[0.7446107  0.54961824 0.6571615  0.20705326 0.52782555]
  [0.03877731 0.84286891 0.47123326 0.76601986 0.38554845]
  [0.25812644 0.43447495 0.33672481 0.41459509 0.41545317]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [160]:
# your code here
b = np.ones((5,2,3), int)


#### 6. Print *b*.


In [161]:
# your code here
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [162]:
# your code here
print(a.shape)
print(b.shape)

(2, 3, 5)
(5, 2, 3)


#### 8. Are you able to add *a* and *b*? Why or why not?


In [163]:
# your answer here
c = a + b
#both need to have the same shape

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [164]:
# your code here
c = b.reshape(2,3,5)
c.shape

(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [165]:
# your code/answer here
d = a + c
#same shape

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [166]:
# your code/answer here
print(a)

print(b)

[[[0.69383785 0.31557124 0.77128259 0.97539613 0.36927456]
  [0.10023612 0.35177448 0.86386996 0.41433631 0.27002812]
  [0.67394949 0.69947547 0.53958484 0.76677251 0.3238135 ]]

 [[0.7446107  0.54961824 0.6571615  0.20705326 0.52782555]
  [0.03877731 0.84286891 0.47123326 0.76601986 0.38554845]
  [0.25812644 0.43447495 0.33672481 0.41459509 0.41545317]]]
[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [167]:
# your code here
e = a * c

#### 13. Does *e* equal to *a*? Why or why not?


In [168]:
# your code/answer here

e == a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [209]:
# your code here
print(d)

d_max = (np.max(d))
d_min = (np.min(d))
d_mean = (np.mean(d))
print(d_min)
print(d_mean)
print(d_max)

[[[1.69383785 1.31557124 1.77128259 1.97539613 1.36927456]
  [1.10023612 1.35177448 1.86386996 1.41433631 1.27002812]
  [1.67394949 1.69947547 1.53958484 1.76677251 1.3238135 ]]

 [[1.7446107  1.54961824 1.6571615  1.20705326 1.52782555]
  [1.03877731 1.84286891 1.47123326 1.76601986 1.38554845]
  [1.25812644 1.43447495 1.33672481 1.41459509 1.41545317]]]
1.0387773097423767
1.5059764891084542
1.9753961306386971


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [171]:
# your code here
f = np.empty((2,3,5), dtype = int )

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [224]:
# your code here
aaa = []

for x in d:
    for y in x:
        for z in y:
            if z > d_min and z < d_mean:
                z = 25
                aaa.append(z)
            elif z > d_mean and z < d_max:
                z = 75
                aaa.append(z)
            elif z == d_mean:
                z = 50
                aaa.append(z)
            elif z == d_min:
                z = 0 
                aaa.append(z)
            elif z == d_max :
                z = 100
                aaa.append(z)
print(d)
f = np.array(aaa).reshape(2,3,5)

[[[1.69383785 1.31557124 1.77128259 1.97539613 1.36927456]
  [1.10023612 1.35177448 1.86386996 1.41433631 1.27002812]
  [1.67394949 1.69947547 1.53958484 1.76677251 1.3238135 ]]

 [[1.7446107  1.54961824 1.6571615  1.20705326 1.52782555]
  [1.03877731 1.84286891 1.47123326 1.76601986 1.38554845]
  [1.25812644 1.43447495 1.33672481 1.41459509 1.41545317]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [220]:
# your code here
(print(d_min), print(d_mean), print(d_max))
print(d)
print(f)
                    

1.0387773097423767
1.5059764891084542
1.9753961306386971
[[[1.69383785 1.31557124 1.77128259 1.97539613 1.36927456]
  [1.10023612 1.35177448 1.86386996 1.41433631 1.27002812]
  [1.67394949 1.69947547 1.53958484 1.76677251 1.3238135 ]]

 [[1.7446107  1.54961824 1.6571615  1.20705326 1.52782555]
  [1.03877731 1.84286891 1.47123326 1.76601986 1.38554845]
  [1.25812644 1.43447495 1.33672481 1.41459509 1.41545317]]]
[[[ 75  25  75 100  25]
  [ 25  25  75  25  25]
  [ 75  75  75  75  25]]

 [[ 75  75  75  25  75]
  [  0  75  25  75  25]
  [ 25  25  25  25  25]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [227]:
# your code here
bb = []

for x in d:
    for y in x:
        for z in y:
            if z > d_min and z < d_mean:
                z = 'B'
                bb.append(z)
            elif z > d_mean and z < d_max:
                z = 'D'
                bb.append(z)
            elif z == d_mean:
                z = 'C'
                bb.append(z)
            elif z == d_min:
                z = 'A' 
                bb.append(z)
            elif z == d_max :
                z = 'E'
                bb.append(z)

g = np.array(bb).reshape(2,3,5)
print(g)

[[['D' 'B' 'D' 'E' 'B']
  ['B' 'B' 'D' 'B' 'B']
  ['D' 'D' 'D' 'D' 'B']]

 [['D' 'D' 'D' 'B' 'D']
  ['A' 'D' 'B' 'D' 'B']
  ['B' 'B' 'B' 'B' 'B']]]
