# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.version.version)

1.16.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [5]:
a= np.random.random((2,3,5))
a

array([[[0.9705557 , 0.44980969, 0.66409772, 0.83224065, 0.65611951],
        [0.07045795, 0.83259967, 0.88452304, 0.28756936, 0.64760802],
        [0.89723508, 0.95844028, 0.69043383, 0.43651011, 0.61316514]],

       [[0.29813991, 0.20028531, 0.79113356, 0.37356991, 0.7810931 ],
        [0.78599498, 0.93385541, 0.08225474, 0.90246335, 0.17172438],
        [0.28297528, 0.21285817, 0.73472196, 0.30973048, 0.4100263 ]]])

In [15]:
# Method 2
f = np.empty((2,3,5))
f

array([[[0.9705557 , 0.44980969, 0.66409772, 0.83224065, 0.65611951],
        [0.07045795, 0.83259967, 0.88452304, 0.28756936, 0.64760802],
        [0.89723508, 0.95844028, 0.69043383, 0.43651011, 0.61316514]],

       [[0.29813991, 0.20028531, 0.79113356, 0.37356991, 0.7810931 ],
        [0.78599498, 0.93385541, 0.08225474, 0.90246335, 0.17172438],
        [0.28297528, 0.21285817, 0.73472196, 0.30973048, 0.4100263 ]]])

In [18]:
# Method 3
arr = np.random.randint(0, 100, size=(2, 3, 5))
arr

array([[[24, 89, 78, 60, 70],
        [50, 50, 29, 23, 41],
        [11,  4, 25, 39, 96]],

       [[17, 32, 10, 64, 47],
        [42, 63, 99, 75,  1],
        [34, 31, 73, 75, 81]]])

#### 4. Print *a*.


In [20]:
# your code here
print(a)

[[[0.9705557  0.44980969 0.66409772 0.83224065 0.65611951]
  [0.07045795 0.83259967 0.88452304 0.28756936 0.64760802]
  [0.89723508 0.95844028 0.69043383 0.43651011 0.61316514]]

 [[0.29813991 0.20028531 0.79113356 0.37356991 0.7810931 ]
  [0.78599498 0.93385541 0.08225474 0.90246335 0.17172438]
  [0.28297528 0.21285817 0.73472196 0.30973048 0.4100263 ]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [40]:
# your code here
b = np.ones((5,3,2))
b

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

#### 6. Print *b*.


In [41]:
# your code here
print(b)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [42]:
# your code here
#np.array_equiv(a,b)
np.broadcast(a,b)

ValueError: shape mismatch: objects cannot be broadcast to a single shape

#### 8. Are you able to add *a* and *b*? Why or why not?


In [43]:
# your answer here
np.concatenate((a, b))
#the arrays doesn't have the same size/shape

ValueError: all the input array dimensions except for the concatenation axis must match exactly

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [44]:
# your code here
c = np.transpose(b, axes=None)
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [46]:
# your code/answer here
d = a + c
d
#because I changed the b array to 2,3,5 and so they got the same shape/size

array([[[1.9705557 , 1.44980969, 1.66409772, 1.83224065, 1.65611951],
        [1.07045795, 1.83259967, 1.88452304, 1.28756936, 1.64760802],
        [1.89723508, 1.95844028, 1.69043383, 1.43651011, 1.61316514]],

       [[1.29813991, 1.20028531, 1.79113356, 1.37356991, 1.7810931 ],
        [1.78599498, 1.93385541, 1.08225474, 1.90246335, 1.17172438],
        [1.28297528, 1.21285817, 1.73472196, 1.30973048, 1.4100263 ]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [47]:
# your code/answer here
print(a)

print(d)

# added 1 to each value of the a array

[[[0.9705557  0.44980969 0.66409772 0.83224065 0.65611951]
  [0.07045795 0.83259967 0.88452304 0.28756936 0.64760802]
  [0.89723508 0.95844028 0.69043383 0.43651011 0.61316514]]

 [[0.29813991 0.20028531 0.79113356 0.37356991 0.7810931 ]
  [0.78599498 0.93385541 0.08225474 0.90246335 0.17172438]
  [0.28297528 0.21285817 0.73472196 0.30973048 0.4100263 ]]]
[[[1.9705557  1.44980969 1.66409772 1.83224065 1.65611951]
  [1.07045795 1.83259967 1.88452304 1.28756936 1.64760802]
  [1.89723508 1.95844028 1.69043383 1.43651011 1.61316514]]

 [[1.29813991 1.20028531 1.79113356 1.37356991 1.7810931 ]
  [1.78599498 1.93385541 1.08225474 1.90246335 1.17172438]
  [1.28297528 1.21285817 1.73472196 1.30973048 1.4100263 ]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [49]:
# your code here
e = a*c
e

array([[[0.9705557 , 0.44980969, 0.66409772, 0.83224065, 0.65611951],
        [0.07045795, 0.83259967, 0.88452304, 0.28756936, 0.64760802],
        [0.89723508, 0.95844028, 0.69043383, 0.43651011, 0.61316514]],

       [[0.29813991, 0.20028531, 0.79113356, 0.37356991, 0.7810931 ],
        [0.78599498, 0.93385541, 0.08225474, 0.90246335, 0.17172438],
        [0.28297528, 0.21285817, 0.73472196, 0.30973048, 0.4100263 ]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [51]:
# your code/answer here
np.array_equal(e,a)

True

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [59]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)


d_max, d_min, d_mean

(1.9705556999047857, 1.0704579523343436, 1.5720730870896285)

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [62]:
# your code here
f = np.empty((2,3,5))
f

array([[[0.9705557 , 0.44980969, 0.66409772, 0.83224065, 0.65611951],
        [0.07045795, 0.83259967, 0.88452304, 0.28756936, 0.64760802],
        [0.89723508, 0.95844028, 0.69043383, 0.43651011, 0.61316514]],

       [[0.29813991, 0.20028531, 0.79113356, 0.37356991, 0.7810931 ],
        [0.78599498, 0.93385541, 0.08225474, 0.90246335, 0.17172438],
        [0.28297528, 0.21285817, 0.73472196, 0.30973048, 0.4100263 ]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [68]:
# your code here

#with np.nditer(d, op_flags=['readwrite']) as it:
#...    for x in it:
for x in np.nditer(d):
    if x > d_min and x<d_mean:
        x in np.nditer(f) = 25
    if x > d_mean and x< d_max:
        x in np.nditer(f) = 75
    if x == d_mean:
        x in np.nditer(f) = 50
    if x == d_min:
        x in np.nditer(f) = 0
    if x == d_max:
        x in np.nditer(f) = 100
print(f)

SyntaxError: can't assign to comparison (<ipython-input-68-d3b433099f8f>, line 7)

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [69]:
# your code here
print(d), print(f)

[[[1.9705557  1.44980969 1.66409772 1.83224065 1.65611951]
  [1.07045795 1.83259967 1.88452304 1.28756936 1.64760802]
  [1.89723508 1.95844028 1.69043383 1.43651011 1.61316514]]

 [[1.29813991 1.20028531 1.79113356 1.37356991 1.7810931 ]
  [1.78599498 1.93385541 1.08225474 1.90246335 1.17172438]
  [1.28297528 1.21285817 1.73472196 1.30973048 1.4100263 ]]]
[[[0.9705557  0.44980969 0.66409772 0.83224065 0.65611951]
  [0.07045795 0.83259967 0.88452304 0.28756936 0.64760802]
  [0.89723508 0.95844028 0.69043383 0.43651011 0.61316514]]

 [[0.29813991 0.20028531 0.79113356 0.37356991 0.7810931 ]
  [0.78599498 0.93385541 0.08225474 0.90246335 0.17172438]
  [0.28297528 0.21285817 0.73472196 0.30973048 0.4100263 ]]]


(None, None)

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here