# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np


#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.__version__)

1.18.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a= np.random.rand(2,3,5)
a

array([[[0.99605642, 0.54417451, 0.18911758, 0.56203691, 0.7373075 ],
        [0.81781253, 0.53512341, 0.86186086, 0.97283091, 0.64104628],
        [0.31040381, 0.71879796, 0.2345406 , 0.14233455, 0.70530322]],

       [[0.57272876, 0.31509497, 0.34904004, 0.88567127, 0.15011593],
        [0.45628197, 0.52623055, 0.89562213, 0.35825978, 0.47346038],
        [0.8350635 , 0.64935671, 0.47174505, 0.59558726, 0.72257498]]])

In [5]:
# Method 2
a = np.random.randint(100, size=(2,3, 5))
a

array([[[40, 28, 57, 79, 16],
        [38, 87, 88,  4, 17],
        [52, 91, 16, 52, 66]],

       [[15, 60, 70, 83, 68],
        [74, 81, 73, 79, 78],
        [42, 79, 28, 45, 99]]])

In [6]:
# Method 3
a = np.random.randn(2,3,5)
a

array([[[-2.78857586e+00, -2.41321308e+00,  2.29950125e+00,
         -3.52116193e-01,  6.55351759e-01],
        [ 6.15919275e-01, -6.59435656e-01, -5.93113245e-01,
         -1.13461113e+00, -9.54392008e-02],
        [ 1.01496524e+00, -4.14402671e-01,  1.20862280e+00,
          7.59538026e-01, -1.17211196e-01]],

       [[-6.28709771e-01,  6.13822753e-01,  5.05669255e-01,
         -6.79594566e-02, -1.60725681e-01],
        [ 1.32725398e+00,  2.10415642e-01, -7.34514895e-01,
         -1.43052284e+00, -1.41857660e-01],
        [ 2.65420186e-03,  2.12041229e+00, -4.90381489e-01,
          3.57890533e-01,  1.47141329e-01]]])

#### 4. Print *a*.


In [7]:
# your code here
a

array([[[-2.78857586e+00, -2.41321308e+00,  2.29950125e+00,
         -3.52116193e-01,  6.55351759e-01],
        [ 6.15919275e-01, -6.59435656e-01, -5.93113245e-01,
         -1.13461113e+00, -9.54392008e-02],
        [ 1.01496524e+00, -4.14402671e-01,  1.20862280e+00,
          7.59538026e-01, -1.17211196e-01]],

       [[-6.28709771e-01,  6.13822753e-01,  5.05669255e-01,
         -6.79594566e-02, -1.60725681e-01],
        [ 1.32725398e+00,  2.10415642e-01, -7.34514895e-01,
         -1.43052284e+00, -1.41857660e-01],
        [ 2.65420186e-03,  2.12041229e+00, -4.90381489e-01,
          3.57890533e-01,  1.47141329e-01]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [8]:
# your code here
b = np.random.randint(1,2,(5,2,3)) 



#### 6. Print *b*.


In [9]:
# your code here
b


array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [10]:
# your code here
print("Shpe of a: ",a.shape,",and size: ",a.size)
print("Shpe of b: ",b.shape,",and size: ",b.size)

# They do have the same size

Shpe of a:  (2, 3, 5) ,and size:  30
Shpe of b:  (5, 2, 3) ,and size:  30


#### 8. Are you able to add *a* and *b*? Why or why not?


In [11]:
# your answer here

np.add(a,b)

# It's not possible because their shapes are different

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [12]:
# your code here
c=b.reshape(2,3,5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [29]:
# your code/answer here
d = np.add(a,c)
# Now they have the same shape

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [30]:
# your code/answer here
print(a)
print("\nSeparator\n")
print(d)

# Each value was added 1

[[[-2.78857586e+00 -2.41321308e+00  2.29950125e+00 -3.52116193e-01
    6.55351759e-01]
  [ 6.15919275e-01 -6.59435656e-01 -5.93113245e-01 -1.13461113e+00
   -9.54392008e-02]
  [ 1.01496524e+00 -4.14402671e-01  1.20862280e+00  7.59538026e-01
   -1.17211196e-01]]

 [[-6.28709771e-01  6.13822753e-01  5.05669255e-01 -6.79594566e-02
   -1.60725681e-01]
  [ 1.32725398e+00  2.10415642e-01 -7.34514895e-01 -1.43052284e+00
   -1.41857660e-01]
  [ 2.65420186e-03  2.12041229e+00 -4.90381489e-01  3.57890533e-01
    1.47141329e-01]]]

Separator

[[[-1.78857586 -1.41321308  3.29950125  0.64788381  1.65535176]
  [ 1.61591927  0.34056434  0.40688676 -0.13461113  0.9045608 ]
  [ 2.01496524  0.58559733  2.2086228   1.75953803  0.8827888 ]]

 [[ 0.37129023  1.61382275  1.50566926  0.93204054  0.83927432]
  [ 2.32725398  1.21041564  0.2654851  -0.43052284  0.85814234]
  [ 1.0026542   3.12041229  0.50961851  1.35789053  1.14714133]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [15]:
# your code here
e = np.multiply(a,c)

#### 13. Does *e* equal to *a*? Why or why not?


In [16]:
# your code/answer here
a==e

# Yes, we multiplied a with an array of 1 , so its going to be exatcly the same

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [17]:
# your code here
d_max=np.max(d)
d_min=np.min(d)
d_mean=np.mean(d)



#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [27]:
# your code here

f=np.empty((2,3,5))


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [40]:
# your code here
a=0
b=0
c=0

for array in d:
    for array1 in array:
        for number in array1:
            if ((number > d_min) and (number < d_mean)):
                f[a,b,c]=25
            elif ((number > d_mean) and (number < d_max)):
                f[a,b,c]=75
            elif number == d_mean:
                f[a,b,c]=50
            elif number == d_min:
                f[a,b,c]=0
            elif number ==d_max:
                f[a,b,c]=100
            c+=1
        b+=1
        c=0
    a+=1
    b=0

    

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [41]:
#your code here
print(d)
print("\n separator \n")
print(f)

[[[-1.78857586 -1.41321308  3.29950125  0.64788381  1.65535176]
  [ 1.61591927  0.34056434  0.40688676 -0.13461113  0.9045608 ]
  [ 2.01496524  0.58559733  2.2086228   1.75953803  0.8827888 ]]

 [[ 0.37129023  1.61382275  1.50566926  0.93204054  0.83927432]
  [ 2.32725398  1.21041564  0.2654851  -0.43052284  0.85814234]
  [ 1.0026542   3.12041229  0.50961851  1.35789053  1.14714133]]]

 separator 

[[[  0.  25. 100.  25.  75.]
  [ 75.  25.  25.  25.  25.]
  [ 75.  25.  75.  75.  25.]]

 [[ 25.  75.  75.  25.  25.]
  [ 75.  75.  25.  25.  25.]
  [ 75.  75.  25.  75.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [50]:
# your code here
a=0
b=0
c=0

f = f.astype(str)


for array in d:
    for array1 in array:
        for number in array1:
            if ((number > d_min) and (number < d_mean)):
                f[a,b,c]='B'
            elif ((number > d_mean) and (number < d_max)):
                f[a,b,c]='D'
            elif number == d_mean:
                f[a,b,c]='C'
            elif number == d_min:
                f[a,b,c]="A"
            elif number ==d_max:
                f[a,b,c]='E'
            c+=1
        b+=1
        c=0
    a+=1
    b=0

f

array([[['A', 'B', 'E', 'B', 'D'],
        ['D', 'B', 'B', 'B', 'B'],
        ['D', 'B', 'D', 'D', 'B']],

       [['B', 'D', 'D', 'B', 'B'],
        ['D', 'D', 'B', 'B', 'B'],
        ['D', 'D', 'B', 'D', 'D']]], dtype='<U4')