# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [91]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [92]:
# your code here
print(np.version.version)

1.17.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [93]:
# Method 1
a = np.random.random(size = (2,3,5))
a

array([[[0.68839854, 0.14554227, 0.23782252, 0.08191285, 0.64483386],
        [0.68218563, 0.05276887, 0.30329156, 0.94313963, 0.09717865],
        [0.72727763, 0.54101991, 0.9836327 , 0.90239479, 0.26425891]],

       [[0.93248652, 0.53620022, 0.57639087, 0.53787757, 0.69691087],
        [0.52195299, 0.96352584, 0.44469538, 0.51135055, 0.82750919],
        [0.97806659, 0.44359129, 0.36935168, 0.3217536 , 0.65154404]]])

In [94]:
# Method 2
b=np.random.randint(5,size = (2,3,5))
b

array([[[2, 4, 0, 0, 2],
        [3, 0, 3, 2, 3],
        [2, 1, 2, 4, 0]],

       [[4, 4, 0, 0, 3],
        [2, 3, 2, 2, 3],
        [2, 4, 1, 3, 4]]])

In [95]:
# Method 3
c = np.random.random_sample(size = (2,3,5))
c

array([[[0.5620757 , 0.61753597, 0.01607758, 0.85170262, 0.89668717],
        [0.33769582, 0.87274512, 0.61257176, 0.67158922, 0.57202808],
        [0.67633532, 0.24173722, 0.64321664, 0.21663306, 0.64391371]],

       [[0.38840719, 0.24182543, 0.71501568, 0.33572217, 0.54766718],
        [0.55176662, 0.35053643, 0.93703329, 0.86851006, 0.56793354],
        [0.79998644, 0.02173161, 0.73496797, 0.78223545, 0.979474  ]]])

#### 4. Print *a*.


In [96]:
# your code here
print(a)

[[[0.68839854 0.14554227 0.23782252 0.08191285 0.64483386]
  [0.68218563 0.05276887 0.30329156 0.94313963 0.09717865]
  [0.72727763 0.54101991 0.9836327  0.90239479 0.26425891]]

 [[0.93248652 0.53620022 0.57639087 0.53787757 0.69691087]
  [0.52195299 0.96352584 0.44469538 0.51135055 0.82750919]
  [0.97806659 0.44359129 0.36935168 0.3217536  0.65154404]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [97]:
# your code here
b = np.ones(shape=(5,2,3))

#### 6. Print *b*.


In [98]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [99]:
# your code here
# No, that don't have the same size
a.shape == b.shape

False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [100]:
# your answer here
# No, they don't have the same shape

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [101]:
# your code here
c = b.reshape(a.shape)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [102]:
# your code/answer here
d =a + c

# It works now because they have the same shape 

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [103]:
# your code/answer here
print(a)
print('\n')
print(d)

# every value in d is 1 higher since we added the ones matrix (c) to it.

[[[0.68839854 0.14554227 0.23782252 0.08191285 0.64483386]
  [0.68218563 0.05276887 0.30329156 0.94313963 0.09717865]
  [0.72727763 0.54101991 0.9836327  0.90239479 0.26425891]]

 [[0.93248652 0.53620022 0.57639087 0.53787757 0.69691087]
  [0.52195299 0.96352584 0.44469538 0.51135055 0.82750919]
  [0.97806659 0.44359129 0.36935168 0.3217536  0.65154404]]]


[[[1.68839854 1.14554227 1.23782252 1.08191285 1.64483386]
  [1.68218563 1.05276887 1.30329156 1.94313963 1.09717865]
  [1.72727763 1.54101991 1.9836327  1.90239479 1.26425891]]

 [[1.93248652 1.53620022 1.57639087 1.53787757 1.69691087]
  [1.52195299 1.96352584 1.44469538 1.51135055 1.82750919]
  [1.97806659 1.44359129 1.36935168 1.3217536  1.65154404]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [104]:
# your code here
e = a * c
e

array([[[0.68839854, 0.14554227, 0.23782252, 0.08191285, 0.64483386],
        [0.68218563, 0.05276887, 0.30329156, 0.94313963, 0.09717865],
        [0.72727763, 0.54101991, 0.9836327 , 0.90239479, 0.26425891]],

       [[0.93248652, 0.53620022, 0.57639087, 0.53787757, 0.69691087],
        [0.52195299, 0.96352584, 0.44469538, 0.51135055, 0.82750919],
        [0.97806659, 0.44359129, 0.36935168, 0.3217536 , 0.65154404]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [105]:
# your code/answer here
e == a

# every value in e is the same as a since we multiplied every value by 1

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [106]:
# your code here
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [107]:
# your code here
f=np.empty(shape=(2,3,5))


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [108]:
# your code here

def myfunc(d):
    if (d > d_min) and (d < d_mean):
        return 25
    elif (d > d_mean) and (d < d_max):
        return 75
    elif d == d_mean:
        return 50
    elif d == d_max:
        return 100
    else:
        return 0


f = np.vectorize(myfunc)
f = f(d)
f


array([[[ 75,  25,  25,  25,  75],
        [ 75,   0,  25,  75,  25],
        [ 75,  25, 100,  75,  25]],

       [[ 75,  25,  75,  25,  75],
        [ 25,  75,  25,  25,  75],
        [ 75,  25,  25,  25,  75]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [112]:
# your code here
print(d)
print('\n')
print(f)

#yes it is as expected

[[[1.68839854 1.14554227 1.23782252 1.08191285 1.64483386]
  [1.68218563 1.05276887 1.30329156 1.94313963 1.09717865]
  [1.72727763 1.54101991 1.9836327  1.90239479 1.26425891]]

 [[1.93248652 1.53620022 1.57639087 1.53787757 1.69691087]
  [1.52195299 1.96352584 1.44469538 1.51135055 1.82750919]
  [1.97806659 1.44359129 1.36935168 1.3217536  1.65154404]]]


[[[ 75  25  25  25  75]
  [ 75   0  25  75  25]
  [ 75  25 100  75  25]]

 [[ 75  25  75  25  75]
  [ 25  75  25  25  75]
  [ 75  25  25  25  75]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [110]:
# your code here
