# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [104]:
# your code here
import numpy as np
#whenever we need to do math we should import numpy. It is used to do the math to arrays of numbers.

#### 2. Print your NumPy version.

In [105]:
# your code here
print(np.__version__)

1.18.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [106]:
# Method 1
a = np.random.random((2,3,5))
a.shape

(2, 3, 5)

In [107]:
# Method 2
a = np.random.rand(2,3,5) # rand -> uniform distributed random numbers, from 0 to 1
a.shape

(2, 3, 5)

In [108]:
#Method 3
a = np.random.randn(2,3,5) ## randn -> normally distributed random numbers, mean=0 and pstdev=0
a.shape


(2, 3, 5)

#### 4. Print *a*.


In [109]:
# your code here
print(a)

[[[-0.05988657 -0.87869859 -0.50730347  0.25380406 -1.24041516]
  [-0.45820493 -0.53715261  0.37075476 -0.0245456  -0.63613457]
  [ 0.98524822 -1.80659654 -0.60221687 -0.51688234  0.48753625]]

 [[ 1.31688464 -0.64359511 -0.93282021 -1.221918    0.23159015]
  [ 1.3414791   0.02510026 -0.64346589 -0.86249373 -0.14066935]
  [-0.46678181 -0.43644211  2.21704744 -1.01430296 -1.13147263]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [110]:
# your code here
b = np.ones((5,2,3), dtype = int) #changed to 5x3x2 for the later exercises to work

#### 6. Print *b*.


In [111]:
# your code here
print(b)
print(b.dtype)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
int32


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [112]:
# your code here
#size = number of elements
print(a.size == b.size) #same because 5x3x2 = 30 for both

True


#### 8. Are you able to add *a* and *b*? Why or why not?


In [113]:
# your answer here
c = np.concatenate((a, b)) #2x3x5 + 5x2x3
#no because all the input array dimensions for the concatenation axis must match exactly

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [114]:
# your code here
#Outra forma de fazer, mas não tão eficiente:
'''b = np.reshape(b, (5,3,2)) #dimensions we need to get array 'c' correct
print(b.shape)
c = np.transpose(b)
print(c)
print(c.shape)'''

#Melhor forma
c = b.transpose(1,2,0)
print(c.shape)

(2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [115]:
# your code/answer here
d = np.add(a,c)
print(d.shape)
#because with the transpose method we have the same array dimensions

(2, 3, 5)


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [116]:
# your code/answer here
print('array a: ')
print(a, a.dtype)
print('array d: ')
print(d, d.dtype)

#The b array elements became a float, because the a array elements were float type

array a: 
[[[-0.05988657 -0.87869859 -0.50730347  0.25380406 -1.24041516]
  [-0.45820493 -0.53715261  0.37075476 -0.0245456  -0.63613457]
  [ 0.98524822 -1.80659654 -0.60221687 -0.51688234  0.48753625]]

 [[ 1.31688464 -0.64359511 -0.93282021 -1.221918    0.23159015]
  [ 1.3414791   0.02510026 -0.64346589 -0.86249373 -0.14066935]
  [-0.46678181 -0.43644211  2.21704744 -1.01430296 -1.13147263]]] float64
array d: 
[[[ 0.94011343  0.12130141  0.49269653  1.25380406 -0.24041516]
  [ 0.54179507  0.46284739  1.37075476  0.9754544   0.36386543]
  [ 1.98524822 -0.80659654  0.39778313  0.48311766  1.48753625]]

 [[ 2.31688464  0.35640489  0.06717979 -0.221918    1.23159015]
  [ 2.3414791   1.02510026  0.35653411  0.13750627  0.85933065]
  [ 0.53321819  0.56355789  3.21704744 -0.01430296 -0.13147263]]] float64


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [117]:
# your code here
e = np.multiply(a, c)
print(e)

[[[-0.05988657 -0.87869859 -0.50730347  0.25380406 -1.24041516]
  [-0.45820493 -0.53715261  0.37075476 -0.0245456  -0.63613457]
  [ 0.98524822 -1.80659654 -0.60221687 -0.51688234  0.48753625]]

 [[ 1.31688464 -0.64359511 -0.93282021 -1.221918    0.23159015]
  [ 1.3414791   0.02510026 -0.64346589 -0.86249373 -0.14066935]
  [-0.46678181 -0.43644211  2.21704744 -1.01430296 -1.13147263]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [118]:
# your code/answer here
np.array_equal(e, a)
#Yes, because the c array (transpose b array) are numbers = 1.

True

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [119]:
# your code here
d_max = np.amax(d)
d_min = np.amin(d)
d_mean = np.mean(d)
print('max: ', d_max)
print('min: ', d_min)
print('mean: ', d_mean)

#a.mean(axis = 1) axis tell the direction in which the operation is made

max:  3.2170474449106505
min:  -0.8065965358254026
mean:  0.7489148613775974


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [120]:
# your code here
f = np.empty([2, 3, 5])
print(f)


#do every element of the array squared
#np.power(a.4) to the power of 4
#np.exp(a)

#a >= 5
#a[a >= 5] or a[condition] se tivermos condition = a >= 5


[[[0.05988657 0.87869859 0.50730347 0.25380406 1.24041516]
  [0.45820493 0.53715261 0.37075476 0.0245456  0.63613457]
  [0.98524822 1.80659654 0.60221687 0.51688234 0.48753625]]

 [[1.31688464 0.64359511 0.93282021 1.221918   0.23159015]
  [1.3414791  0.02510026 0.64346589 0.86249373 0.14066935]
  [0.46678181 0.43644211 2.21704744 1.01430296 1.13147263]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [121]:
# your code here

for x in range(d.shape[0]):
     for y in range(d.shape[1]):
        for z in range(d.shape[2]):
            if d[x][y][z] > d_min and d[x][y][z] < d_mean:
                f[x][y][z] = 25
       
            elif d[x][y][z] > d_mean and d[x][y][z] < d_max:
                f[x][y][z] = 75

            elif d[x][y][z] == d_mean:
                f[x][y][z] = 50

            elif d[x][y][z] == d_min:
                f[x][y][z] = 0

            elif d[x][y][z] == d_max:
                f[x][y][z] = 100

#list comprehension optional

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [122]:
# your code here
'''max:  3.12
min:  -1.94
mean:  0.76'''

print(d)
print(f)

[[[ 0.94011343  0.12130141  0.49269653  1.25380406 -0.24041516]
  [ 0.54179507  0.46284739  1.37075476  0.9754544   0.36386543]
  [ 1.98524822 -0.80659654  0.39778313  0.48311766  1.48753625]]

 [[ 2.31688464  0.35640489  0.06717979 -0.221918    1.23159015]
  [ 2.3414791   1.02510026  0.35653411  0.13750627  0.85933065]
  [ 0.53321819  0.56355789  3.21704744 -0.01430296 -0.13147263]]]
[[[ 75.  25.  25.  75.  25.]
  [ 25.  25.  75.  75.  25.]
  [ 75.   0.  25.  25.  75.]]

 [[ 75.  25.  25.  25.  75.]
  [ 75.  75.  25.  25.  75.]
  [ 25.  25. 100.  25.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [15]:
# your code here