# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.__version__)

1.16.4


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a=np.random.random((2,3,5))
print(a)

[[[0.58269494 0.21200737 0.74602857 0.12338075 0.91847877]
  [0.95318303 0.33045932 0.9076762  0.51278527 0.65186261]
  [0.47587046 0.10350682 0.32363821 0.21591805 0.840699  ]]

 [[0.2347698  0.92434874 0.53761246 0.45768947 0.57105486]
  [0.0083586  0.29649951 0.49445554 0.95444835 0.13078967]
  [0.01784564 0.74852566 0.96493281 0.13508983 0.01601079]]]


In [4]:
# Method 2
a=np.random.random(size=(2,3,5))
print(a)

[[[0.71596514 0.01716128 0.08159316 0.20260849 0.2860153 ]
  [0.29387206 0.02556175 0.11013146 0.31051021 0.23457181]
  [0.37262503 0.30425142 0.30379861 0.68827857 0.00711368]]

 [[0.53122322 0.0028232  0.89557607 0.78996196 0.09317764]
  [0.70080278 0.90398644 0.25529167 0.6398528  0.46727099]
  [0.72700476 0.35147833 0.73731613 0.01267415 0.40841375]]]


In [5]:
# Method 3
a=np.random.rand(2,3,5)
print(a)

[[[0.93626277 0.59404586 0.84827772 0.97780841 0.91407224]
  [0.07700006 0.90866235 0.57853529 0.22291791 0.56588149]
  [0.91807672 0.70457539 0.53862645 0.85424835 0.50659547]]

 [[0.45566715 0.3521729  0.62702057 0.31244542 0.46499476]
  [0.07518685 0.67098621 0.308703   0.41996144 0.66333963]
  [0.85516042 0.31060401 0.23809239 0.30067083 0.48092262]]]


#### 4. Print *a*.


In [6]:
# your code here
# Already answered in the previous question

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here
b= np.ones(shape=(5,2,3))

#### 6. Print *b*.


In [8]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here
# Yes they do. We compare the size of eachother and check if it's true or not
a.size==b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here
# Yes we are, because they have the same size. However, as they don't have the same shape
# we need to reshape one of them so we can add it to the other. For Exp: a=a.reshape(5,2,3)

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here
c=b.reshape(2,3,5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# your code/answer here
d=a+c

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# your code/answer here
print('a: ',a,'\n')
print('d: ', d)

a:  [[[0.93626277 0.59404586 0.84827772 0.97780841 0.91407224]
  [0.07700006 0.90866235 0.57853529 0.22291791 0.56588149]
  [0.91807672 0.70457539 0.53862645 0.85424835 0.50659547]]

 [[0.45566715 0.3521729  0.62702057 0.31244542 0.46499476]
  [0.07518685 0.67098621 0.308703   0.41996144 0.66333963]
  [0.85516042 0.31060401 0.23809239 0.30067083 0.48092262]]] 

d:  [[[1.93626277 1.59404586 1.84827772 1.97780841 1.91407224]
  [1.07700006 1.90866235 1.57853529 1.22291791 1.56588149]
  [1.91807672 1.70457539 1.53862645 1.85424835 1.50659547]]

 [[1.45566715 1.3521729  1.62702057 1.31244542 1.46499476]
  [1.07518685 1.67098621 1.308703   1.41996144 1.66333963]
  [1.85516042 1.31060401 1.23809239 1.30067083 1.48092262]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
# your code here
e=a*c

#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
# your code/answer here
e==a
# They are equal because e = a*c and c is an array of ones with the shape of a. So, e = a *1 = a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
# your code here
d_max=d.max()
d_min=d.min()
d_mean=d.mean()

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [23]:
# your code here
f=np.empty(shape=(2,3,5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [24]:
# your code here
for array in d:
    for sub_array in array:
        for value in sub_array:
            if (value > d_min) & (value<d_mean):
                    index=np.where(f == value)
                    f[index]=25
            elif (value > d_mean) & (value<d_max):
                index=np.where(f == value)
                f[index]=75
            elif (value == d_mean):
                index=np.where(f == value)
                f[index]=50
            elif (value == d_min):
                index=np.where(f == value)
                f[index]=0
            elif (value == d_max):
                index=np.where(f == value)
                f[index]=100

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [19]:
# your code here
print(d)
print(f)

[[[1.93626277 1.59404586 1.84827772 1.97780841 1.91407224]
  [1.07700006 1.90866235 1.57853529 1.22291791 1.56588149]
  [1.91807672 1.70457539 1.53862645 1.85424835 1.50659547]]

 [[1.45566715 1.3521729  1.62702057 1.31244542 1.46499476]
  [1.07518685 1.67098621 1.308703   1.41996144 1.66333963]
  [1.85516042 1.31060401 1.23809239 1.30067083 1.48092262]]]
[[[ 75.  75.  75. 100.  75.]
  [ 25.  75.  75.  25.  75.]
  [ 75.  75.  25.  75.  25.]]

 [[ 25.  25.  75.  25.  25.]
  [  0.  75.  25.  25.  75.]
  [ 75.  25.  25.  25.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [26]:
# your code here
# your code here
e=np.empty(shape=(2,3,5), dtype=str)
for array in d:
    for sub_array in array:
        for value in sub_array:
            if (value > d_min) & (value<d_mean):
                    index=np.where(d == value)
                    e[index]="B"
            elif (value > d_mean) & (value<d_max):
                index=np.where(d == value)
                e[index]="D"
            elif (value == d_mean):
                index=np.where(d == value)
                e[index]="C"
            elif (value == d_min):
                index=np.where(d == value)
                e[index]="A"
            elif (value == d_max):
                index=np.where(d == value)
                e[index]="E"
print(e)

[[['D' 'D' 'D' 'E' 'D']
  ['B' 'D' 'D' 'B' 'D']
  ['D' 'D' 'B' 'D' 'B']]

 [['B' 'B' 'D' 'B' 'B']
  ['A' 'D' 'B' 'B' 'D']
  ['D' 'B' 'B' 'B' 'B']]]
