# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [4]:
# your code here

import numpy as np

#### 2. Print your NumPy version.

In [5]:
# your code here
print(np.__version__)

1.18.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [6]:
# Method 1
a = np.random.rand(2,3,5)


In [63]:
# Method 2
a = np.random.randint (0, 100, size = (2,3,5))
a

array([[[27, 85, 97, 61, 38],
        [60, 95, 57, 42, 31],
        [94, 16,  3, 71, 84]],

       [[74, 93, 94, 91, 56],
        [ 8, 13, 68, 74, 62],
        [ 5, 43, 35, 22, 61]]])

In [65]:
# Method 3
import random
a = [[[random.random() for k in range(5)] for j in range(3)] for i in range(2)]
a = np.array(a)

#### 4. Print *a*.


In [66]:
# your code here
print(a)

[[[0.84613231 0.52251974 0.32580203 0.93252812 0.20021774]
  [0.08734578 0.11180998 0.30690342 0.30381197 0.30290416]
  [0.03064252 0.7302843  0.59604655 0.40674654 0.70105076]]

 [[0.84931069 0.25666761 0.82770201 0.31543971 0.82041828]
  [0.17146553 0.19594232 0.90039807 0.75234299 0.29724666]
  [0.82971063 0.01832211 0.42713862 0.02181418 0.67252155]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [10]:
# your code here

b = np.ones((5,2,3))

#### 6. Print *b*.


In [11]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [12]:
# your code here

a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [13]:
# your answer here
#np.add(a,b)
sum_ab = a + b
#no, because they have a diferent shapes

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [14]:
# your code here


c = np.reshape(b, (2, 3, 5))
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [15]:
# your code/answer here
#because now i apply the reshape method e they booth have the same shape, then now works
d = a + c

print(d)

[[[1.74304273 1.80572399 1.13109332 1.83435461 1.33117117]
  [1.17963608 1.55489945 1.41567182 1.54921652 1.62016055]
  [1.7790312  1.97764327 1.1761357  1.27304587 1.34612664]]

 [[1.92640257 1.4883551  1.13440865 1.17197416 1.43571156]
  [1.08788263 1.93759318 1.87916336 1.65723989 1.03677341]
  [1.26943115 1.98030239 1.3950108  1.28257886 1.08319054]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [45]:
# your code/answer here
#duvida
#they have the same values
print(a)
print(d)


[[[0.74304273 0.80572399 0.13109332 0.83435461 0.33117117]
  [0.17963608 0.55489945 0.41567182 0.54921652 0.62016055]
  [0.7790312  0.97764327 0.1761357  0.27304587 0.34612664]]

 [[0.92640257 0.4883551  0.13440865 0.17197416 0.43571156]
  [0.08788263 0.93759318 0.87916336 0.65723989 0.03677341]
  [0.26943115 0.98030239 0.3950108  0.28257886 0.08319054]]]
[[[1.74304273 1.80572399 1.13109332 1.83435461 1.33117117]
  [1.17963608 1.55489945 1.41567182 1.54921652 1.62016055]
  [1.7790312  1.97764327 1.1761357  1.27304587 1.34612664]]

 [[1.92640257 1.4883551  1.13440865 1.17197416 1.43571156]
  [1.08788263 1.93759318 1.87916336 1.65723989 1.03677341]
  [1.26943115 1.98030239 1.3950108  1.28257886 1.08319054]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [17]:
# your code here

e = np.multiply(a, c)
e

array([[[0.74304273, 0.80572399, 0.13109332, 0.83435461, 0.33117117],
        [0.17963608, 0.55489945, 0.41567182, 0.54921652, 0.62016055],
        [0.7790312 , 0.97764327, 0.1761357 , 0.27304587, 0.34612664]],

       [[0.92640257, 0.4883551 , 0.13440865, 0.17197416, 0.43571156],
        [0.08788263, 0.93759318, 0.87916336, 0.65723989, 0.03677341],
        [0.26943115, 0.98030239, 0.3950108 , 0.28257886, 0.08319054]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [33]:
# your code/answer here
#Yes, they have the same shape

e == a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [40]:
# your code here
d_max = np.amax(d)
print(d_max)
d_min = np.amin(d)
print(d_min)
d_mean = np.mean(d)
print(d_mean)
print(d)

1.9803023873641865
1.0367734119532583
1.4827657059972787
[[[1.74304273 1.80572399 1.13109332 1.83435461 1.33117117]
  [1.17963608 1.55489945 1.41567182 1.54921652 1.62016055]
  [1.7790312  1.97764327 1.1761357  1.27304587 1.34612664]]

 [[1.92640257 1.4883551  1.13440865 1.17197416 1.43571156]
  [1.08788263 1.93759318 1.87916336 1.65723989 1.03677341]
  [1.26943115 1.98030239 1.3950108  1.28257886 1.08319054]]]


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [41]:
# your code here
f = np.empty((2,3,5))
print(f)

[[[1.74304273 1.80572399 1.13109332 1.83435461 1.33117117]
  [1.17963608 1.55489945 1.41567182 1.54921652 1.62016055]
  [1.7790312  1.97764327 1.1761357  1.27304587 1.34612664]]

 [[1.92640257 1.4883551  1.13440865 1.17197416 1.43571156]
  [1.08788263 1.93759318 1.87916336 1.65723989 1.03677341]
  [1.26943115 1.98030239 1.3950108  1.28257886 1.08319054]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [61]:

result = []
for x in d:
    for y in x:
        for z in y :
            if z > d_min and z < d_mean :
                result.append(25)
            elif z > d_mean and z < d_max :
                result.append(75)
            elif z == d_mean :
                result.append(50)
            elif z == d_min :
                result.append(0)
            elif z == d_max :
                result.append(100)
                
#print(result)

result = np.reshape(result, (2, 3, 5))
print(result)

[75, 75, 25, 75, 25, 25, 75, 25, 75, 75, 75, 75, 25, 25, 25, 75, 75, 25, 25, 25, 25, 75, 75, 75, 0, 25, 100, 25, 25, 25]
[[[ 75  75  25  75  25]
  [ 25  75  25  75  75]
  [ 75  75  25  25  25]]

 [[ 75  75  25  25  25]
  [ 25  75  75  75   0]
  [ 25 100  25  25  25]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [212]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [198]:
# your code here