# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np


#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.__version__)
numpy.version.version

1.18.5


NameError: name 'numpy' is not defined

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a = np.random.random((2,3,5))
print(a)

[[[0.51657877 0.22097703 0.25910774 0.74432073 0.55515565]
  [0.27750253 0.05205443 0.1045537  0.84315066 0.69290437]
  [0.12161644 0.36789825 0.78315677 0.21630151 0.98034448]]

 [[0.27694313 0.14770787 0.79720869 0.12960402 0.17303637]
  [0.76538792 0.09153273 0.55730909 0.42516679 0.59935033]
  [0.29849783 0.87700755 0.74209341 0.3332795  0.67990864]]]


In [4]:
# Method 2
a = np.arange(30).reshape(2,3,5)
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [5]:
# Method 3
a = np.random.randint(1,90,(2,3,5)) 
print(a)

[[[55 19 33 76 47]
  [88 13 54 68 53]
  [ 8 76 56 24 72]]

 [[11 74 25 84  2]
  [31 75 60 15 19]
  [38 71 26 12 73]]]


#### 4. Print *a*.


In [6]:
# your code here
print(a)

[[[55 19 33 76 47]
  [88 13 54 68 53]
  [ 8 76 56 24 72]]

 [[11 74 25 84  2]
  [31 75 60 15 19]
  [38 71 26 12 73]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here
#he cambiado esto
b = np.ones((5,2,3))

#### 6. Print *b*.


In [8]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here
print(a.shape)
print(a.size)
print(b.shape)
print(b.size)

a.size == b.size

(2, 3, 5)
30
(5, 2, 3)
30


True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here
print(np.add(a, b))

#No ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [14]:
# your code here
c = b.reshape(2,3,5) 
#c = b.transpose()
print(c)
print(c.shape)






[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
(2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [15]:
# your code/answer here
d = np.add(a, c)


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [16]:
# your code/answer here
print(a)
print(d)

[[[55 19 33 76 47]
  [88 13 54 68 53]
  [ 8 76 56 24 72]]

 [[11 74 25 84  2]
  [31 75 60 15 19]
  [38 71 26 12 73]]]
[[[56. 20. 34. 77. 48.]
  [89. 14. 55. 69. 54.]
  [ 9. 77. 57. 25. 73.]]

 [[12. 75. 26. 85.  3.]
  [32. 76. 61. 16. 20.]
  [39. 72. 27. 13. 74.]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [17]:
# your code here
e = np.multiply(a,c)
print(e)

[[[55. 19. 33. 76. 47.]
  [88. 13. 54. 68. 53.]
  [ 8. 76. 56. 24. 72.]]

 [[11. 74. 25. 84.  2.]
  [31. 75. 60. 15. 19.]
  [38. 71. 26. 12. 73.]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [18]:
# your code/answer here

e == a

#it is equal because the content of c are the number 1, so something multiply by 1 the result is the same

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [19]:
# your code here
#max
d_max = np.max(d)
print(d_max)

#min
d_min = np.min(d)
print(d_min)

#mean 
d_mean = np.mean(d)
print(d_mean)

89.0
3.0
46.266666666666666


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [20]:
# your code here
f = np.empty([2,3,5])
print(f)

#f = np.zeros([2,3,5])
#print(f)



[[[55. 19. 33. 76. 47.]
  [88. 13. 54. 68. 53.]
  [ 8. 76. 56. 24. 72.]]

 [[11. 74. 25. 84.  2.]
  [31. 75. 60. 15. 19.]
  [38. 71. 26. 12. 73.]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [21]:
# your code here
for i in range(len(d)):
    for j in range(len(d[i])):
        for k in range(len(d[i][j])):
            if d[i][j][k] > d_min and d[i][j][k] < d_mean:
                f[i][j][k] = 25
            elif d[i][j][k] > d_mean and d[i][j][k] < d_max:
                f[i][j][k] = 75
            elif d[i][j][k] == d_mean:
                f[i][j][k] = 50
            elif d[i][j][k] == d_max:
                f[i][j][k] = 100
            else:
                f[i][j][k] = 0

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [135]:
# your code here
print(d)
print(f)

[[[1.07673012 1.29714635 1.65746342 1.1341411  1.62856151]
  [1.97004281 1.73718482 1.46363167 1.12245596 1.01074341]
  [1.26598189 1.05672328 1.73048304 1.00568366 1.51600458]]

 [[1.20455671 1.63116771 1.04914241 1.34322866 1.31092459]
  [1.67071732 1.1909073  1.97160655 1.95742105 1.53836422]
  [1.41510007 1.18392202 1.61584405 1.99337492 1.39387371]]]
[[[ 25.  25.  75.  25.  75.]
  [ 75.  75.  75.  25.  25.]
  [ 25.  25.  75.   0.  75.]]

 [[ 25.  75.  25.  25.  25.]
  [ 75.  25.  75.  75.  75.]
  [ 25.  25.  75. 100.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here
