# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here

import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.version.version)

1.19.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [16]:
# Method 1
a = np.random.random((2,3,5))
print(a)

[[[0.92233999 0.08018433 0.55086031 0.4942538  0.90026178]
  [0.82350235 0.15501897 0.64755835 0.6504808  0.69187869]
  [0.17611926 0.42715314 0.64193175 0.72258572 0.93576789]]

 [[0.3059574  0.57691025 0.71531297 0.09959294 0.05724134]
  [0.30048507 0.33384366 0.14347624 0.30239793 0.4764545 ]
  [0.21619717 0.22294816 0.65820183 0.68382243 0.03091092]]]


In [15]:
# Method 2
a2 = np.random.rand(2,3,5)
print(a2)

[[[0.60720755 0.01215559 0.58854697 0.85756453 0.77092141]
  [0.37642042 0.65698286 0.35929285 0.48847163 0.27141379]
  [0.25966424 0.00280654 0.43505239 0.73738157 0.52383485]]

 [[0.81392758 0.42584408 0.49162411 0.34575957 0.12339341]
  [0.30248613 0.83356527 0.86626517 0.49386206 0.57896788]
  [0.06133624 0.88754837 0.92185995 0.02114531 0.44220027]]]


In [17]:
# Method 3
a3 = np.empty((2,3,5))
print(a3)

[[[0.92233999 0.08018433 0.55086031 0.4942538  0.90026178]
  [0.82350235 0.15501897 0.64755835 0.6504808  0.69187869]
  [0.17611926 0.42715314 0.64193175 0.72258572 0.93576789]]

 [[0.3059574  0.57691025 0.71531297 0.09959294 0.05724134]
  [0.30048507 0.33384366 0.14347624 0.30239793 0.4764545 ]
  [0.21619717 0.22294816 0.65820183 0.68382243 0.03091092]]]


#### 4. Print *a*.


In [18]:
# your code here
print(a)

[[[0.92233999 0.08018433 0.55086031 0.4942538  0.90026178]
  [0.82350235 0.15501897 0.64755835 0.6504808  0.69187869]
  [0.17611926 0.42715314 0.64193175 0.72258572 0.93576789]]

 [[0.3059574  0.57691025 0.71531297 0.09959294 0.05724134]
  [0.30048507 0.33384366 0.14347624 0.30239793 0.4764545 ]
  [0.21619717 0.22294816 0.65820183 0.68382243 0.03091092]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [19]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [20]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [21]:
# your code here
proof = np.multiply(a,b)
print(proof)
#with the error below it proves they are not the same size.

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 8. Are you able to add *a* and *b*? Why or why not?


In [ ]:
# your answer here
#I am not able to add a and b because they dont have the same shape.

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [22]:
# your code here
c = np.reshape(b,(2,3,5))
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [23]:
# your code/answer here
d= np.add(a,c)

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [24]:
# your code/answer here
print(a)
print(d)
#Every value of d is has the sum of 1 compared to the value of a in the same position (line,column)

[[[0.92233999 0.08018433 0.55086031 0.4942538  0.90026178]
  [0.82350235 0.15501897 0.64755835 0.6504808  0.69187869]
  [0.17611926 0.42715314 0.64193175 0.72258572 0.93576789]]

 [[0.3059574  0.57691025 0.71531297 0.09959294 0.05724134]
  [0.30048507 0.33384366 0.14347624 0.30239793 0.4764545 ]
  [0.21619717 0.22294816 0.65820183 0.68382243 0.03091092]]]
[[[1.92233999 1.08018433 1.55086031 1.4942538  1.90026178]
  [1.82350235 1.15501897 1.64755835 1.6504808  1.69187869]
  [1.17611926 1.42715314 1.64193175 1.72258572 1.93576789]]

 [[1.3059574  1.57691025 1.71531297 1.09959294 1.05724134]
  [1.30048507 1.33384366 1.14347624 1.30239793 1.4764545 ]
  [1.21619717 1.22294816 1.65820183 1.68382243 1.03091092]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [25]:
# your code here
e=np.multiply(a,c)

#### 13. Does *e* equal to *a*? Why or why not?


In [27]:
# your code/answer here
print(a)
print(e)
e==a
#Since all i did was multiply a with an array that had everything valued as 1 it followed the simple rule of neutral element of multiplication.

[[[0.92233999 0.08018433 0.55086031 0.4942538  0.90026178]
  [0.82350235 0.15501897 0.64755835 0.6504808  0.69187869]
  [0.17611926 0.42715314 0.64193175 0.72258572 0.93576789]]

 [[0.3059574  0.57691025 0.71531297 0.09959294 0.05724134]
  [0.30048507 0.33384366 0.14347624 0.30239793 0.4764545 ]
  [0.21619717 0.22294816 0.65820183 0.68382243 0.03091092]]]
[[[0.92233999 0.08018433 0.55086031 0.4942538  0.90026178]
  [0.82350235 0.15501897 0.64755835 0.6504808  0.69187869]
  [0.17611926 0.42715314 0.64193175 0.72258572 0.93576789]]

 [[0.3059574  0.57691025 0.71531297 0.09959294 0.05724134]
  [0.30048507 0.33384366 0.14347624 0.30239793 0.4764545 ]
  [0.21619717 0.22294816 0.65820183 0.68382243 0.03091092]]]


array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [28]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [29]:
# your code here
f = np.empty((2,3,5))
print(f)

[[[0.92233999 0.08018433 0.55086031 0.4942538  0.90026178]
  [0.82350235 0.15501897 0.64755835 0.6504808  0.69187869]
  [0.17611926 0.42715314 0.64193175 0.72258572 0.93576789]]

 [[0.3059574  0.57691025 0.71531297 0.09959294 0.05724134]
  [0.30048507 0.33384366 0.14347624 0.30239793 0.4764545 ]
  [0.21619717 0.22294816 0.65820183 0.68382243 0.03091092]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [30]:
# your code here
f = np.copy(d)
f[f == d_min] = 0
f[(f>d_min) & (f<d_mean)] = 25
f[(f == d_mean)] = 50
f[(f>d_mean) & (f<d_max)] = 75
f[f == d_max] = 100

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [31]:
# your code here
print (d)
print (f)

[[[1.92233999 1.08018433 1.55086031 1.4942538  1.90026178]
  [1.82350235 1.15501897 1.64755835 1.6504808  1.69187869]
  [1.17611926 1.42715314 1.64193175 1.72258572 1.93576789]]

 [[1.3059574  1.57691025 1.71531297 1.09959294 1.05724134]
  [1.30048507 1.33384366 1.14347624 1.30239793 1.4764545 ]
  [1.21619717 1.22294816 1.65820183 1.68382243 1.03091092]]]
[[[ 75.  25.  75.  75.  75.]
  [ 75.  25.  75.  75.  75.]
  [ 25.  25.  75.  75. 100.]]

 [[ 25.  75.  75.  25.  25.]
  [ 25.  25.  25.  25.  75.]
  [ 25.  25.  75.  75.   0.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [32]:
# your code here
g = np.where(d==d_min, "A", d)
g = np.where((d>d_min) & (d<d_mean), "B", g)
g = np.where(d == d_mean, "C", g)
g = np.where((d>d_mean) & (d<d_max) & (d<d_max), "D", g)
g = np.where(d == d_max, "E", g)

In [33]:
print (g)

[[['D' 'B' 'D' 'D' 'D']
  ['D' 'B' 'D' 'D' 'D']
  ['B' 'B' 'D' 'D' 'E']]

 [['B' 'D' 'D' 'B' 'B']
  ['B' 'B' 'B' 'B' 'D']
  ['B' 'B' 'D' 'D' 'A']]]
