# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [3]:
# your code here
np.version.version

'1.19.5'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [4]:
# Method 1
a = np.random.random((2,3,5))

In [7]:
# Method 2
method2 = np.random.randint(100, size=(2,3,5))
print(method2)


[[[94 34 82 27 47]
  [88 38 27 22 51]
  [35 64 24 56 94]]

 [[18 32 83 86 85]
  [65 99 85 72 41]
  [93 39 14 27 89]]]


In [ ]:
# Method 3

#### 4. Print *a*.


In [5]:
# your code here
print(a)

[[[0.80596416 0.17186268 0.99868607 0.28875665 0.75824616]
  [0.96178728 0.27656866 0.15736336 0.25888027 0.49608155]
  [0.40595248 0.55490453 0.92396206 0.31626289 0.48762072]]

 [[0.12373041 0.8377156  0.24460297 0.7406092  0.01638144]
  [0.16611845 0.71872591 0.94070197 0.03411888 0.08183091]
  [0.25732686 0.79720183 0.21984402 0.7703678  0.62566471]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [17]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [18]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [12]:
# your code here
a_size = a.size
b_size = b.size
print(a_size)
print(b_size)

print(a_size == b_size)

30
30
True


#### 8. Are you able to add *a* and *b*? Why or why not?


In [13]:
# your answer here
sum_a_b = a + b

#they have different shape 

ValueError: ignored

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [34]:
# your code here
c = b.transpose((1,2,0))
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [35]:
# your code/answer here
d = a + c

d

array([[[1.80596416, 1.17186268, 1.99868607, 1.28875665, 1.75824616],
        [1.96178728, 1.27656866, 1.15736336, 1.25888027, 1.49608155],
        [1.40595248, 1.55490453, 1.92396206, 1.31626289, 1.48762072]],

       [[1.12373041, 1.8377156 , 1.24460297, 1.7406092 , 1.01638144],
        [1.16611845, 1.71872591, 1.94070197, 1.03411888, 1.08183091],
        [1.25732686, 1.79720183, 1.21984402, 1.7703678 , 1.62566471]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [36]:
# your code/answer here
print(a)
print(d)

#it added one to another, it's exactly +1 because we added an array with ones


[[[0.80596416 0.17186268 0.99868607 0.28875665 0.75824616]
  [0.96178728 0.27656866 0.15736336 0.25888027 0.49608155]
  [0.40595248 0.55490453 0.92396206 0.31626289 0.48762072]]

 [[0.12373041 0.8377156  0.24460297 0.7406092  0.01638144]
  [0.16611845 0.71872591 0.94070197 0.03411888 0.08183091]
  [0.25732686 0.79720183 0.21984402 0.7703678  0.62566471]]]
[[[1.80596416 1.17186268 1.99868607 1.28875665 1.75824616]
  [1.96178728 1.27656866 1.15736336 1.25888027 1.49608155]
  [1.40595248 1.55490453 1.92396206 1.31626289 1.48762072]]

 [[1.12373041 1.8377156  1.24460297 1.7406092  1.01638144]
  [1.16611845 1.71872591 1.94070197 1.03411888 1.08183091]
  [1.25732686 1.79720183 1.21984402 1.7703678  1.62566471]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [37]:
# your code here
e = a * c
e

array([[[0.80596416, 0.17186268, 0.99868607, 0.28875665, 0.75824616],
        [0.96178728, 0.27656866, 0.15736336, 0.25888027, 0.49608155],
        [0.40595248, 0.55490453, 0.92396206, 0.31626289, 0.48762072]],

       [[0.12373041, 0.8377156 , 0.24460297, 0.7406092 , 0.01638144],
        [0.16611845, 0.71872591, 0.94070197, 0.03411888, 0.08183091],
        [0.25732686, 0.79720183, 0.21984402, 0.7703678 , 0.62566471]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [38]:
# your code/answer here
e == a
#because we multiplied by 1

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [39]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print(d_max)
print(d_min)
print(d_mean)


1.9986860669644089
1.0163814401209168
1.4812613495019062


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [40]:
# your code here
f = np.empty((2,3,5))
f

array([[[0.80596416, 0.17186268, 0.99868607, 0.28875665, 0.75824616],
        [0.96178728, 0.27656866, 0.15736336, 0.25888027, 0.49608155],
        [0.40595248, 0.55490453, 0.92396206, 0.31626289, 0.48762072]],

       [[0.12373041, 0.8377156 , 0.24460297, 0.7406092 , 0.01638144],
        [0.16611845, 0.71872591, 0.94070197, 0.03411888, 0.08183091],
        [0.25732686, 0.79720183, 0.21984402, 0.7703678 , 0.62566471]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [42]:
# your code here
s = d.shape

#HERE WE ASSIGNE EACH POSITION OF THE ARRAY THROUGH INDEXING A VALUE
# DEPENDING ON THE CONDITION

for gr in range(s[0]):
    for row in range(s[1]):
        for col in range(s[2]):
            if (d[gr, row, col] > d_min) & (d[gr, row, col] < d_mean):
                f[gr,row,col] = 25
            elif (d[gr, row, col] > d_mean) & (d[gr, row, col] < d_max):
                f[gr,row,col] = 75
            elif d[gr, row, col] == d_min:
                f[gr,row,col] = 0
            elif d[gr, row, col] == d_max:
                f[gr,row,col] = 100

f


array([[[ 75.,  25., 100.,  25.,  75.],
        [ 75.,  25.,  25.,  25.,  75.],
        [ 25.,  75.,  75.,  25.,  75.]],

       [[ 25.,  75.,  25.,  75.,   0.],
        [ 25.,  75.,  75.,  25.,  25.],
        [ 25.,  75.,  25.,  75.,  75.]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [43]:
# your code here
print(d)
print(f)

[[[1.80596416 1.17186268 1.99868607 1.28875665 1.75824616]
  [1.96178728 1.27656866 1.15736336 1.25888027 1.49608155]
  [1.40595248 1.55490453 1.92396206 1.31626289 1.48762072]]

 [[1.12373041 1.8377156  1.24460297 1.7406092  1.01638144]
  [1.16611845 1.71872591 1.94070197 1.03411888 1.08183091]
  [1.25732686 1.79720183 1.21984402 1.7703678  1.62566471]]]
[[[ 75.  25. 100.  25.  75.]
  [ 75.  25.  25.  25.  75.]
  [ 25.  75.  75.  25.  75.]]

 [[ 25.  75.  25.  75.   0.]
  [ 25.  75.  75.  25.  25.]
  [ 25.  75.  25.  75.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here