# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [2]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [3]:
# your code here
print(np.__version__)

1.18.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [4]:
# Method 1
a=np.random.randint(1,100,(2,3,5))
print(a)

[[[32 36 29 34 35]
  [58 23  4 90 27]
  [48 56  1  5  2]]

 [[78 75 55 15 14]
  [70 58 59 99 21]
  [86 58  4 62 47]]]


In [23]:
# Method 2
#careful, the number of elements in the array must be equal to the product of the dimensions of the array for the following to work
a = np.arange(30).reshape(2,3,5)

print(a)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [6]:
# Method 3
a=np.empty((2,3,5))
print(a)

[[[1.58e-322 1.78e-322 1.43e-322 1.68e-322 1.73e-322]
  [2.87e-322 1.14e-322 1.98e-323 4.45e-322 1.33e-322]
  [2.37e-322 2.77e-322 4.94e-324 2.47e-323 9.88e-324]]

 [[3.85e-322 3.71e-322 2.72e-322 7.41e-323 6.92e-323]
  [3.46e-322 2.87e-322 2.91e-322 4.89e-322 1.04e-322]
  [4.25e-322 2.87e-322 1.98e-323 3.06e-322 2.32e-322]]]


#### 4. Print *a*.


In [7]:
# your code here
print(a)

[[[1.58e-322 1.78e-322 1.43e-322 1.68e-322 1.73e-322]
  [2.87e-322 1.14e-322 1.98e-323 4.45e-322 1.33e-322]
  [2.37e-322 2.77e-322 4.94e-324 2.47e-323 9.88e-324]]

 [[3.85e-322 3.71e-322 2.72e-322 7.41e-323 6.92e-323]
  [3.46e-322 2.87e-322 2.91e-322 4.89e-322 1.04e-322]
  [4.25e-322 2.87e-322 1.98e-323 3.06e-322 2.32e-322]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [24]:
# your code here
b=np.ones((5,2,3),int)

#### 6. Print *b*.


In [25]:
# your code here
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [26]:
# your code here

if a.shape==b.shape:
    print("arrays a and b have the same size")
else:
    print("arrays a and b do not have the same size")


arrays a and b do not have the same size


#### 8. Are you able to add *a* and *b*? Why or why not?


In [27]:
# your answer here
# adding a and b will return an error, because they are not defined in the same way, namely (2,3,5) and (5,2,3)

print(a.shape)
print(b.shape)
c = a + b

(2, 3, 5)
(5, 2, 3)


ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [28]:
# your code here
# transpose without argument does the following (a,b,c)-->(c,b,a)
# with a tuple as an argument in .transpose() I can decide how to transform (a,b,c) which can become (2,1,0) or (2,0,1)... 
c=b.transpose((1,2,0))
print(c.shape)
print(c)

(2, 3, 5)
[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [29]:
# your code/answer here
d = a + c
print(d)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [30]:
# your code/answer here
print(a)
print(" ")
print(d)

# a and d have the same shape
# d is simply equal to a + 1 because b is an array of ones 

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
 
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [31]:
# your code here
e=a*c

print(e)


[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [32]:
# your code/answer here
# e is equal to a because c is an array of ones, consequently multiplying the values in a by 1 is equal to these same values

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [33]:
# your code here
d_max = a.max()
d_min = a.min()
d_mean = a.mean()

print(d_max, d_min, d_mean)


29 0 14.5


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [34]:
# your code here
#creating the empty array
shape_array=(2,3,5)
f = np.ones(shape_array,int)


print(f)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [35]:
# your code here
print(d)
print("d_max is ",d_max,)
print("d_min is ",d_min,)
print("d_mean is ",d_mean,)
print(" ")

# assign the value if <d_max and >d_mean
condition1=(d>d_min) & (d<d_mean)
# create an array with only 75s
#mult1=np.full(shape_array,75)

#assign in f the first condition
#f = f * condition1 * mult1

#condition2: if a value equals d_mean than assign 50
condition2=(d>d_mean) & (d<d_max)
condition3=(d==d_mean)
condition4=(d==d_min)
condition5=(d==d_max)
#create an array with only 50s
#mult2=np.full(shape_array,50)

#assign in f the second condition
#f = f * condition2 * mult2

#condition3: 

#print(f)
#print(d[condition1])
#print(d[condition1])
#f=f.transpose()
#print(f)

f = np.where(condition4,0,d)
f = np.where(condition1,25,f)
f = np.where(condition3,50,f)
f = np.where(condition2,75,f)
f = np.where(condition5,100,f)


print(f)




[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]]]
d_max is  29
d_min is  0
d_mean is  14.5
 
[[[ 25  25  25  25  25]
  [ 25  25  25  25  25]
  [ 25  25  25  25  75]]

 [[ 75  75  75  75  75]
  [ 75  75  75  75  75]
  [ 75  75  75 100  30]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here
# no, I don't get what I expected because,
# the biggest value in d is 30 and array d = a + 1
# d_min, d_max and d_mean are computed based on a
# therefore the biggest value in f remains 30 and does not change
# conclusion: it is a mathematical issue and not a coding error

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here