# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.version.version)

1.18.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1

##is this also a uniform distribution? is it filled by random sampling as method 2 or 3?

a = np.full((2,3,5), np.random.random())

a

array([[[0.90642965, 0.90642965, 0.90642965, 0.90642965, 0.90642965],
        [0.90642965, 0.90642965, 0.90642965, 0.90642965, 0.90642965],
        [0.90642965, 0.90642965, 0.90642965, 0.90642965, 0.90642965]],

       [[0.90642965, 0.90642965, 0.90642965, 0.90642965, 0.90642965],
        [0.90642965, 0.90642965, 0.90642965, 0.90642965, 0.90642965],
        [0.90642965, 0.90642965, 0.90642965, 0.90642965, 0.90642965]]])

In [4]:
# Method 2
sometuple = (2,3,5)
##also uniform distribution - not feeling the difference from random.random_sample or random.random to random.int
##except for the fact i can pass to random.random a tuple... more straightforward i guess
a = np.random.random_sample(sometuple)
a

array([[[0.30415605, 0.41267711, 0.0039158 , 0.76868183, 0.99574189],
        [0.148777  , 0.72415433, 0.39434487, 0.54839068, 0.76243389],
        [0.15440847, 0.06751534, 0.13535913, 0.97600981, 0.18721141]],

       [[0.26637531, 0.17208588, 0.46437648, 0.06309795, 0.81023138],
        [0.37329201, 0.16853696, 0.19780915, 0.77278722, 0.11514833],
        [0.47240815, 0.07574524, 0.91371144, 0.26769315, 0.72913534]]])

In [5]:
# Method 3

####np.random.rand for uniform dist
sometuple
scalar = 3
a = np.random.rand(2,3,5)*scalar

print(a)

[[[1.83260888 0.81747731 2.41801844 0.23330246 2.25011002]
  [0.35560723 0.14795013 0.65301161 2.56046339 1.80904812]
  [2.4544934  1.08359634 0.89925802 1.39198021 0.44905994]]

 [[1.22212759 1.99972802 0.23749795 2.00465839 1.30683336]
  [0.24784918 1.2081217  0.46516134 0.68335154 2.77792698]
  [2.31538454 2.43905342 0.69439594 2.7981092  2.32771162]]]


#### 4. Print *a*.


In [6]:
# your code here
a = a/scalar
a

array([[[0.61086963, 0.27249244, 0.80600615, 0.07776749, 0.75003667],
        [0.11853574, 0.04931671, 0.21767054, 0.8534878 , 0.60301604],
        [0.81816447, 0.36119878, 0.29975267, 0.4639934 , 0.14968665]],

       [[0.40737586, 0.66657601, 0.07916598, 0.66821946, 0.43561112],
        [0.08261639, 0.40270723, 0.15505378, 0.22778385, 0.92597566],
        [0.77179485, 0.81301781, 0.23146531, 0.93270307, 0.77590387]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here

b = np.ones((5,2,3))

#### 6. Print *b*.


In [8]:
# your code here
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here
print(a.size == b.size)
## also could've listed all elements for dimension and len(list_of_a_elements) == len(list_of_b_elements) i guess
## but i can't be bothered and the point stands that it contains the same number of elements since 2*3*5 == 5*2*3

True


#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here
## no. dimensions do not match.

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here

c = c = np.transpose(b,(1,2,0))
c

##

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# your code/answer here

d = c + a

print(d)

[[[1.61086963 1.27249244 1.80600615 1.07776749 1.75003667]
  [1.11853574 1.04931671 1.21767054 1.8534878  1.60301604]
  [1.81816447 1.36119878 1.29975267 1.4639934  1.14968665]]

 [[1.40737586 1.66657601 1.07916598 1.66821946 1.43561112]
  [1.08261639 1.40270723 1.15505378 1.22778385 1.92597566]
  [1.77179485 1.81301781 1.23146531 1.93270307 1.77590387]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# your code/answer here
print(a)
print(d)
## yes, d is just a with 1 added to the value of each element.
## so i can say d is an uniform distribution between 1 and 2

[[[0.61086963 0.27249244 0.80600615 0.07776749 0.75003667]
  [0.11853574 0.04931671 0.21767054 0.8534878  0.60301604]
  [0.81816447 0.36119878 0.29975267 0.4639934  0.14968665]]

 [[0.40737586 0.66657601 0.07916598 0.66821946 0.43561112]
  [0.08261639 0.40270723 0.15505378 0.22778385 0.92597566]
  [0.77179485 0.81301781 0.23146531 0.93270307 0.77590387]]]
[[[1.61086963 1.27249244 1.80600615 1.07776749 1.75003667]
  [1.11853574 1.04931671 1.21767054 1.8534878  1.60301604]
  [1.81816447 1.36119878 1.29975267 1.4639934  1.14968665]]

 [[1.40737586 1.66657601 1.07916598 1.66821946 1.43561112]
  [1.08261639 1.40270723 1.15505378 1.22778385 1.92597566]
  [1.77179485 1.81301781 1.23146531 1.93270307 1.77590387]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
# your code here

e = a*c

print(e)

[[[0.61086963 0.27249244 0.80600615 0.07776749 0.75003667]
  [0.11853574 0.04931671 0.21767054 0.8534878  0.60301604]
  [0.81816447 0.36119878 0.29975267 0.4639934  0.14968665]]

 [[0.40737586 0.66657601 0.07916598 0.66821946 0.43561112]
  [0.08261639 0.40270723 0.15505378 0.22778385 0.92597566]
  [0.77179485 0.81301781 0.23146531 0.93270307 0.77590387]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
# your code/answer here
a == e
## evidently, because we are using multiplication identity on every element. it's the same as adding 0

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
# your code here
d_max = np.max(d)
d_min = np.min(d) 
d_mean = np.mean(d)
print(d_max, d_min, d_mean)

1.9327030673850096 1.0493167115416022 1.4675988474651982


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [17]:
# your code here

f = np.zeros((2,3,5))
f

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [35]:
# your code here
f = d

f = np.where(d < d_mean, 25, f)
f = np.where(d > d_mean, 75, f)
f = np.where(d == d_min, 0, f)
f = np.where(d == d_max, 100, f)
f = np.where(d == d_mean, 50, f)
# f = np.where(0 < f < d_mean, 25, f)


# np.where(f == d_min, 50, f)
# np.where(f == d_mean, 50, f)
# np.where(f > d_mean, 50, f)

print(f)

[[[ 75.  25.  75.  25.  75.]
  [ 25.   0.  25.  75.  75.]
  [ 75.  25.  25.  25.  25.]]

 [[ 25.  75.  25.  75.  25.]
  [ 25.  25.  25.  25.  75.]
  [ 75.  75.  25. 100.  75.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [45]:
# your code here

print(d, "\n\n", f, "\n\n", d_min, d_mean, d_max)

##yes

[[[1.61086963 1.27249244 1.80600615 1.07776749 1.75003667]
  [1.11853574 1.04931671 1.21767054 1.8534878  1.60301604]
  [1.81816447 1.36119878 1.29975267 1.4639934  1.14968665]]

 [[1.40737586 1.66657601 1.07916598 1.66821946 1.43561112]
  [1.08261639 1.40270723 1.15505378 1.22778385 1.92597566]
  [1.77179485 1.81301781 1.23146531 1.93270307 1.77590387]]] 

 [[['D' 'B' 'D' 'B' 'D']
  ['B' 'A' 'B' 'D' 'D']
  ['D' 'B' 'B' 'B' 'B']]

 [['B' 'D' 'B' 'D' 'B']
  ['B' 'B' 'B' 'B' 'D']
  ['D' 'D' 'B' 'E' 'D']]] 

 1.0493167115416022 1.4675988474651982 1.9327030673850096


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [46]:
# your code here

f = np.where(d < d_mean, "B", f)
f = np.where(d > d_mean, "D", f)
f = np.where(d == d_min, "A", f)
f = np.where(d == d_max, "E", f)
f = np.where(d == d_mean, "C", f)

print(f)

[[['D' 'B' 'D' 'B' 'D']
  ['B' 'A' 'B' 'D' 'D']
  ['D' 'B' 'B' 'B' 'B']]

 [['B' 'D' 'B' 'D' 'B']
  ['B' 'B' 'B' 'B' 'D']
  ['D' 'D' 'B' 'E' 'D']]]
