# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [2]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [3]:
# your code here
import numpy as np
print(np.__version__)


1.18.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [4]:
# Method 1
a=np.random.random((2,3,5))
print(a)

[[[0.75218913 0.04999114 0.64164322 0.23233384 0.15747591]
  [0.59073897 0.66131441 0.78701775 0.14624708 0.41241064]
  [0.1580179  0.98939194 0.67215685 0.60985974 0.15950983]]

 [[0.78554692 0.36069624 0.08008967 0.85403863 0.13489239]
  [0.26248821 0.25338236 0.68672967 0.07594917 0.27804082]
  [0.55020886 0.44792208 0.47806879 0.75839276 0.15184753]]]


In [5]:
# Method 2
import numpy as np
from random import seed
seed(1)

b=np.random.rand(2,3,5)
b

array([[[0.77342427, 0.1051615 , 0.65763152, 0.73440391, 0.03897714],
        [0.76833809, 0.76309909, 0.36522914, 0.04480221, 0.20292998],
        [0.32426656, 0.11426847, 0.51762977, 0.13530069, 0.46685272]],

       [[0.03433308, 0.25636706, 0.70799977, 0.46906437, 0.22527153],
        [0.35383609, 0.18311572, 0.064193  , 0.57816927, 0.05630473],
        [0.99894364, 0.10477492, 0.8095096 , 0.33488504, 0.43931748]]])

In [6]:
# Method 3
from numpy import random

x = random.randint(100, size=(2,3, 5))

print(x)

[[[74 44 35 77 56]
  [91  3 83 53 52]
  [75 24 98 99 39]]

 [[80  8 51 15  5]
  [17 14 40 37 94]
  [62 80 91 93 57]]]


#### 4. Print *a*.


In [7]:
# your code here
print(a)

[[[0.75218913 0.04999114 0.64164322 0.23233384 0.15747591]
  [0.59073897 0.66131441 0.78701775 0.14624708 0.41241064]
  [0.1580179  0.98939194 0.67215685 0.60985974 0.15950983]]

 [[0.78554692 0.36069624 0.08008967 0.85403863 0.13489239]
  [0.26248821 0.25338236 0.68672967 0.07594917 0.27804082]
  [0.55020886 0.44792208 0.47806879 0.75839276 0.15184753]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [8]:
# your code here
import numpy as np
b=np.ones((5,2,3), dtype=int)
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 6. Print *b*.


In [9]:
# your code here
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [10]:
# your code here

size_a = len(a)
print(size_a)
size_b = len(b)
print(size_b)
print(size_a == size_b)

2
5
False


#### 8. Are you able to add *a* and *b*? Why or why not?


In [11]:
# your answer here
array_sum = np.add(a,b)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [ ]:
#can't sum array with different sizes

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [13]:
# your code here
b=np.ones((5,2,3), dtype=int)
#print(b)

#c=np.transpose(b, axes=(1,0,2))
c=b.reshape((2,3,5))

#print(c)
print(np.shape(c))
print(np.shape(b))
print(np.shape(a))

#new_array = np.add(a,c)
#print(new_array)

(2, 3, 5)
(5, 2, 3)
(2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [14]:
# your code/answer here
d = np.add(a,c)
print(d)
print(np.shape(d))
#because both arrays have the same dimensions

[[[1.75218913 1.04999114 1.64164322 1.23233384 1.15747591]
  [1.59073897 1.66131441 1.78701775 1.14624708 1.41241064]
  [1.1580179  1.98939194 1.67215685 1.60985974 1.15950983]]

 [[1.78554692 1.36069624 1.08008967 1.85403863 1.13489239]
  [1.26248821 1.25338236 1.68672967 1.07594917 1.27804082]
  [1.55020886 1.44792208 1.47806879 1.75839276 1.15184753]]]
(2, 3, 5)


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [15]:
# your code/answer here
#print(a)
#print(d)

#'d' is the result of adding always 1 do all elements of 'a'
difference_a_b = print(d-a)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [16]:
# your code here
e=a*c
print(e)

[[[0.75218913 0.04999114 0.64164322 0.23233384 0.15747591]
  [0.59073897 0.66131441 0.78701775 0.14624708 0.41241064]
  [0.1580179  0.98939194 0.67215685 0.60985974 0.15950983]]

 [[0.78554692 0.36069624 0.08008967 0.85403863 0.13489239]
  [0.26248821 0.25338236 0.68672967 0.07594917 0.27804082]
  [0.55020886 0.44792208 0.47806879 0.75839276 0.15184753]]]


In [ ]:
print(c)

#### 13. Does *e* equal to *a*? Why or why not?


In [ ]:
# your code/answer here
#because 'c' is an erray of ones (all elements are equal to 1). Because 1 is the neutral element
#of multiplication, c*a=a  because a=e than c*a=e

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [17]:
# your code here
d_min= d.min()
print(d_min)
d_max=d.max()
print(d_max)
d_mean=d.mean()
print(d_mean)

1.0499911401519388
1.989391935143709
1.439286414645068


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [37]:
# your code here

f=np.empty((2,3,5))
print(f)

[[[0.75218913 0.04999114 0.64164322 0.23233384 0.15747591]
  [0.59073897 0.66131441 0.78701775 0.14624708 0.41241064]
  [0.1580179  0.98939194 0.67215685 0.60985974 0.15950983]]

 [[0.78554692 0.36069624 0.08008967 0.85403863 0.13489239]
  [0.26248821 0.25338236 0.68672967 0.07594917 0.27804082]
  [0.55020886 0.44792208 0.47806879 0.75839276 0.15184753]]]


In [21]:
f.flatten()

array([0.75218913, 0.04999114, 0.64164322, 0.23233384, 0.15747591,
       0.59073897, 0.66131441, 0.78701775, 0.14624708, 0.41241064,
       0.1580179 , 0.98939194, 0.67215685, 0.60985974, 0.15950983,
       0.78554692, 0.36069624, 0.08008967, 0.85403863, 0.13489239,
       0.26248821, 0.25338236, 0.68672967, 0.07594917, 0.27804082,
       0.55020886, 0.44792208, 0.47806879, 0.75839276, 0.15184753])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [43]:
# your code here
d_min= d.min()   #larger than
d_mean=d.mean()  #smaller than 


d_flatten = d.flatten()
f = []
#why it doesnt work?
for number in d_flatten:
    if number > d_min and number < d_mean:
        f.append(25)
    elif number > d_mean and number < d_max:
        f.append(75)
    elif number ==d_mean:
        f.append(50)
    elif d_min:
        f.append(0)
    elif d_max:
        f.append(100)

        
#print(f)

f_array = np.array([f]) 
f_array=f_array.reshape((2,3,5))
print(f_array)


[[[75  0 75 25 25]
  [75 75 75 25 25]
  [25  0 75 75 25]]

 [[75 25 25 75 25]
  [25 25 75 25 25]
  [75 75 75 75 25]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [12]:
# your code here

In [44]:

h = []
#why it doesnt work?
for number in d_flatten:
    if number > d_min and number < d_mean:
        h.append("B")
    elif number > d_mean and number < d_max:
        h.append("D")
    elif number ==d_mean:
        h.append("C")
    elif d_min:
        h.append("A")
    elif d_max:
        h.append("E")

        
#print(f)

h_array = np.array([h]) 
h_array=h_array.reshape((2,3,5))
print(h_array)


[[['D' 'A' 'D' 'B' 'B']
  ['D' 'D' 'D' 'B' 'B']
  ['B' 'A' 'D' 'D' 'B']]

 [['D' 'B' 'B' 'D' 'B']
  ['B' 'B' 'D' 'B' 'B']
  ['D' 'D' 'D' 'D' 'B']]]
