# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [3]:
# your code here
np.version.version

'1.20.1'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [6]:
# Method 1
# assigning all entries with zeros
a = np.zeros((2,3,5))
a

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [7]:
# Method 2
a = np.random.random((2,3,5))
a

array([[[0.48515334, 0.36841026, 0.46954765, 0.39753777, 0.45261437],
        [0.93355509, 0.71956182, 0.67776654, 0.15846853, 0.66620819],
        [0.50422907, 0.79359442, 0.83999668, 0.40909941, 0.93784196]],

       [[0.06909687, 0.42356436, 0.28795757, 0.25772452, 0.6026362 ],
        [0.44637786, 0.82389829, 0.90152387, 0.15050678, 0.05071867],
        [0.31362   , 0.26115843, 0.67944761, 0.10498725, 0.72686109]]])

In [24]:
# Method 3
a = np.arange(1,150,5)
a = a.reshape(2,3,5)
a

array([[[  1,   6,  11,  16,  21],
        [ 26,  31,  36,  41,  46],
        [ 51,  56,  61,  66,  71]],

       [[ 76,  81,  86,  91,  96],
        [101, 106, 111, 116, 121],
        [126, 131, 136, 141, 146]]])

In [29]:
#true mehtod 1

a = np.linspace(5.0,300,30)
a = a.reshape(2,3,5)

#### 4. Print *a*.


In [34]:
# your code here
print(a)

[[[  5.          15.17241379  25.34482759  35.51724138  45.68965517]
  [ 55.86206897  66.03448276  76.20689655  86.37931034  96.55172414]
  [106.72413793 116.89655172 127.06896552 137.24137931 147.4137931 ]]

 [[157.5862069  167.75862069 177.93103448 188.10344828 198.27586207]
  [208.44827586 218.62068966 228.79310345 238.96551724 249.13793103]
  [259.31034483 269.48275862 279.65517241 289.82758621 300.        ]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [57]:
# your code here
list = [1]
b = np.array(list*30)
b = b.reshape(5,2,3)

#### 6. Print *b*.


In [58]:
# your code here
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [59]:
# your code here
print(a.size)
print(b.size)
a.size == b.size

30
30


True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [75]:
# your answer here
#cause they do not have the same shape as we can see
print(a.shape == b.shape)
a + b

False


ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [76]:
# your code here
c = b.reshape(2,3,5)
print(c)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [80]:
# your code/answer here
print(c.shape)
d = a + c
print(d)

(2, 3, 5)
[[[  6.          16.17241379  26.34482759  36.51724138  46.68965517]
  [ 56.86206897  67.03448276  77.20689655  87.37931034  97.55172414]
  [107.72413793 117.89655172 128.06896552 138.24137931 148.4137931 ]]

 [[158.5862069  168.75862069 178.93103448 189.10344828 199.27586207]
  [209.44827586 219.62068966 229.79310345 239.96551724 250.13793103]
  [260.31034483 270.48275862 280.65517241 290.82758621 301.        ]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [81]:
# your code/answer here
print(a)
print(d)

#as we did in the previous task they are the same but with 1 valued sumed to 'a' array

[[[  5.          15.17241379  25.34482759  35.51724138  45.68965517]
  [ 55.86206897  66.03448276  76.20689655  86.37931034  96.55172414]
  [106.72413793 116.89655172 127.06896552 137.24137931 147.4137931 ]]

 [[157.5862069  167.75862069 177.93103448 188.10344828 198.27586207]
  [208.44827586 218.62068966 228.79310345 238.96551724 249.13793103]
  [259.31034483 269.48275862 279.65517241 289.82758621 300.        ]]]
[[[  6.          16.17241379  26.34482759  36.51724138  46.68965517]
  [ 56.86206897  67.03448276  77.20689655  87.37931034  97.55172414]
  [107.72413793 117.89655172 128.06896552 138.24137931 148.4137931 ]]

 [[158.5862069  168.75862069 178.93103448 189.10344828 199.27586207]
  [209.44827586 219.62068966 229.79310345 239.96551724 250.13793103]
  [260.31034483 270.48275862 280.65517241 290.82758621 301.        ]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [83]:
# your code here
e = a * c
print(e)

[[[  5.          15.17241379  25.34482759  35.51724138  45.68965517]
  [ 55.86206897  66.03448276  76.20689655  86.37931034  96.55172414]
  [106.72413793 116.89655172 127.06896552 137.24137931 147.4137931 ]]

 [[157.5862069  167.75862069 177.93103448 188.10344828 198.27586207]
  [208.44827586 218.62068966 228.79310345 238.96551724 249.13793103]
  [259.31034483 269.48275862 279.65517241 289.82758621 300.        ]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [87]:
# your code/answer here
print(e == a)
#they are the same cause the shape are equal
print(e.shape == a.shape)

[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]
True


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [94]:
# your code here
d_max = d.max()
print(d_max)
d_min  = d.min()
print(d_min)
d_mean = d.mean()
print(d_mean)

301.0
6.0
153.5


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [ ]:
# your code here


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [1]:
# your code here

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here