# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.__version__)

1.21.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
a = np.random.randint(0,100, size = (2, 3, 5))

In [4]:
a = np.random.random(size = (3,5))

In [5]:
c = np.random.random_sample(5)

#### 4. Print *a*.


In [6]:
# your code here
a

array([[0.44458897, 0.67811475, 0.8902734 , 0.72689935, 0.76244942],
       [0.98720331, 0.97638523, 0.6867897 , 0.53243629, 0.52401953],
       [0.74181821, 0.08895457, 0.89644935, 0.27694139, 0.15833334]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
b = np.ones((5,2,3),dtype = int)

#### 6. Print *b*.


In [8]:
b

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
print(np.size(a))
print(np.size(b))

15
30


#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
#You can't add to the array, but you can change it. The only wat to add to arrays would be creating a new one and using the append function.

arr1_ = np.append(a, 3)
arr1_

array([0.44458897, 0.67811475, 0.8902734 , 0.72689935, 0.76244942,
       0.98720331, 0.97638523, 0.6867897 , 0.53243629, 0.52401953,
       0.74181821, 0.08895457, 0.89644935, 0.27694139, 0.15833334,
       3.        ])

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
a.shape

(3, 5)

In [25]:
b.transpose()

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [26]:
c = b.reshape(2,3,5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [27]:
d = a + c
d

#It didn't work previously bcause the arrays had different shapes and you can't sum arrays that have different shapes. Now they were similar and it was possible.

array([[[1.44458897, 1.67811475, 1.8902734 , 1.72689935, 1.76244942],
        [1.98720331, 1.97638523, 1.6867897 , 1.53243629, 1.52401953],
        [1.74181821, 1.08895457, 1.89644935, 1.27694139, 1.15833334]],

       [[1.44458897, 1.67811475, 1.8902734 , 1.72689935, 1.76244942],
        [1.98720331, 1.97638523, 1.6867897 , 1.53243629, 1.52401953],
        [1.74181821, 1.08895457, 1.89644935, 1.27694139, 1.15833334]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [28]:
print(a)

[[0.44458897 0.67811475 0.8902734  0.72689935 0.76244942]
 [0.98720331 0.97638523 0.6867897  0.53243629 0.52401953]
 [0.74181821 0.08895457 0.89644935 0.27694139 0.15833334]]


In [29]:
print(d)

[[[1.44458897 1.67811475 1.8902734  1.72689935 1.76244942]
  [1.98720331 1.97638523 1.6867897  1.53243629 1.52401953]
  [1.74181821 1.08895457 1.89644935 1.27694139 1.15833334]]

 [[1.44458897 1.67811475 1.8902734  1.72689935 1.76244942]
  [1.98720331 1.97638523 1.6867897  1.53243629 1.52401953]
  [1.74181821 1.08895457 1.89644935 1.27694139 1.15833334]]]


In [16]:
#They're organized in the same way, they just possess different numbers of displayed values. d has more values.

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [30]:
e = a * c
e

array([[[0.44458897, 0.67811475, 0.8902734 , 0.72689935, 0.76244942],
        [0.98720331, 0.97638523, 0.6867897 , 0.53243629, 0.52401953],
        [0.74181821, 0.08895457, 0.89644935, 0.27694139, 0.15833334]],

       [[0.44458897, 0.67811475, 0.8902734 , 0.72689935, 0.76244942],
        [0.98720331, 0.97638523, 0.6867897 , 0.53243629, 0.52401953],
        [0.74181821, 0.08895457, 0.89644935, 0.27694139, 0.15833334]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [18]:
e

array([[[0.44458897, 0.67811475, 0.8902734 , 0.72689935, 0.76244942],
        [0.98720331, 0.97638523, 0.6867897 , 0.53243629, 0.52401953],
        [0.74181821, 0.08895457, 0.89644935, 0.27694139, 0.15833334]],

       [[0.44458897, 0.67811475, 0.8902734 , 0.72689935, 0.76244942],
        [0.98720331, 0.97638523, 0.6867897 , 0.53243629, 0.52401953],
        [0.74181821, 0.08895457, 0.89644935, 0.27694139, 0.15833334]]])

In [19]:
a

array([[0.44458897, 0.67811475, 0.8902734 , 0.72689935, 0.76244942],
       [0.98720331, 0.97638523, 0.6867897 , 0.53243629, 0.52401953],
       [0.74181821, 0.08895457, 0.89644935, 0.27694139, 0.15833334]])

In [ ]:
# e has the same results as a but duplicated.

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [31]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

print(d_max, d_min, d_mean)

1.987203308110419 1.0889545715053037 1.624777121667439


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [45]:
f = np.empty([2,3,5])
f

array([[[1.44458897, 1.67811475, 1.8902734 , 1.72689935, 1.76244942],
        [1.98720331, 1.97638523, 1.6867897 , 1.53243629, 1.52401953],
        [1.74181821, 1.08895457, 1.89644935, 1.27694139, 1.15833334]],

       [[1.44458897, 1.67811475, 1.8902734 , 1.72689935, 1.76244942],
        [1.98720331, 1.97638523, 1.6867897 , 1.53243629, 1.52401953],
        [1.74181821, 1.08895457, 1.89644935, 1.27694139, 1.15833334]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [51]:
for x, value_x in enumerate(d):
    for y, value_y in enumerate(value_x):
        for index, value in enumerate(value_y):
            if value > d_min and value < d_mean:
                value = 25
                f[x][y][index] = value
        
            if value > d_mean and value < d_max:
                value = 75
                f[x][y][index] = value
        
            if value == d_mean:
                value = 50
                f[x][y][index] = value
        
            if value == d_min:
                value = 0
                f[x][y][index] = value
        
            if value == d_max:
                value = 100
                f[x][y][index] = value

f

array([[[ 25.,  75.,  75.,  75.,  75.],
        [100.,  75.,  75.,  25.,  25.],
        [ 75.,   0.,  75.,  25.,  25.]],

       [[ 25.,  75.,  75.,  75.,  75.],
        [100.,  75.,  75.,  25.,  25.],
        [ 75.,   0.,  75.,  25.,  25.]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [54]:
print(d)
print(f) 

# max // 1.987203308110419 || min // 1.0889545715053037 || mean // 1.624777121667439
# all good yeah

[[[1.44458897 1.67811475 1.8902734  1.72689935 1.76244942]
  [1.98720331 1.97638523 1.6867897  1.53243629 1.52401953]
  [1.74181821 1.08895457 1.89644935 1.27694139 1.15833334]]

 [[1.44458897 1.67811475 1.8902734  1.72689935 1.76244942]
  [1.98720331 1.97638523 1.6867897  1.53243629 1.52401953]
  [1.74181821 1.08895457 1.89644935 1.27694139 1.15833334]]]
[[[ 25.  75.  75.  75.  75.]
  [100.  75.  75.  25.  25.]
  [ 75.   0.  75.  25.  25.]]

 [[ 25.  75.  75.  75.  75.]
  [100.  75.  75.  25.  25.]
  [ 75.   0.  75.  25.  25.]]]
