# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.version.version)

1.17.3


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a = np.full((2,3,5), np.random.random())
print(a)

[[[0.41580721 0.41580721 0.41580721 0.41580721 0.41580721]
  [0.41580721 0.41580721 0.41580721 0.41580721 0.41580721]
  [0.41580721 0.41580721 0.41580721 0.41580721 0.41580721]]

 [[0.41580721 0.41580721 0.41580721 0.41580721 0.41580721]
  [0.41580721 0.41580721 0.41580721 0.41580721 0.41580721]
  [0.41580721 0.41580721 0.41580721 0.41580721 0.41580721]]]


In [4]:
# Method 2
a = np.random.random((2,3,5))
print(a)

[[[0.86126832 0.34313151 0.44267808 0.32742993 0.81768907]
  [0.82911302 0.86416595 0.61361754 0.17160476 0.75406051]
  [0.56370183 0.54849675 0.18723881 0.1014041  0.91038811]]

 [[0.30970124 0.78225673 0.1460774  0.57572149 0.36309804]
  [0.58271393 0.41462029 0.17664022 0.93344359 0.95114801]
  [0.89475891 0.00235162 0.34782544 0.54934301 0.86715745]]]


In [5]:
# Method 3
a = np.random.rand(2,3,5)
print(a)

[[[0.82773972 0.94588555 0.50613791 0.16623967 0.58113502]
  [0.81931653 0.36103658 0.09331229 0.0016481  0.4760086 ]
  [0.15566157 0.27787747 0.28519514 0.99001287 0.30659312]]

 [[0.19887564 0.7854187  0.73600153 0.21563679 0.14227911]
  [0.3920094  0.7020292  0.4565794  0.02836779 0.64145586]
  [0.38156677 0.33972491 0.75158348 0.17546113 0.10329371]]]


#### 4. Print *a*.


In [6]:
# your code here
print(a)

[[[0.82773972 0.94588555 0.50613791 0.16623967 0.58113502]
  [0.81931653 0.36103658 0.09331229 0.0016481  0.4760086 ]
  [0.15566157 0.27787747 0.28519514 0.99001287 0.30659312]]

 [[0.19887564 0.7854187  0.73600153 0.21563679 0.14227911]
  [0.3920094  0.7020292  0.4565794  0.02836779 0.64145586]
  [0.38156677 0.33972491 0.75158348 0.17546113 0.10329371]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here
b = np.ones((5,2,3), dtype=float)

#### 6. Print *b*.


In [8]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here
# a and b have the same size (same number of total elements) but not the same shape
print(a.size == b.size)

True


#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here
print(a+b)

# add fails because array dimensions do not match up:
# a has 2 rows, b has 5 rows
# a has 3 columns, b has 2 columns
# a has 5 third-dimension elements, b has 3

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here
c = b.transpose()

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# your code/answer here

# d = a+c
# add fails because the transposed array dimensions are (3,2,5)
# and array a has shape (2,3,5)
# for addition to work, b must have shape (5,3,2)
b = np.ones((5,3,2), dtype=float)
c = b.transpose()
d = a + c

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# your code/answer here
print(a)
print(d)

# each value in d is equal to the corresponding value in a plus 1

[[[0.82773972 0.94588555 0.50613791 0.16623967 0.58113502]
  [0.81931653 0.36103658 0.09331229 0.0016481  0.4760086 ]
  [0.15566157 0.27787747 0.28519514 0.99001287 0.30659312]]

 [[0.19887564 0.7854187  0.73600153 0.21563679 0.14227911]
  [0.3920094  0.7020292  0.4565794  0.02836779 0.64145586]
  [0.38156677 0.33972491 0.75158348 0.17546113 0.10329371]]]
[[[1.82773972 1.94588555 1.50613791 1.16623967 1.58113502]
  [1.81931653 1.36103658 1.09331229 1.0016481  1.4760086 ]
  [1.15566157 1.27787747 1.28519514 1.99001287 1.30659312]]

 [[1.19887564 1.7854187  1.73600153 1.21563679 1.14227911]
  [1.3920094  1.7020292  1.4565794  1.02836779 1.64145586]
  [1.38156677 1.33972491 1.75158348 1.17546113 1.10329371]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
# your code here
e = a*c
print(e)

[[[0.82773972 0.94588555 0.50613791 0.16623967 0.58113502]
  [0.81931653 0.36103658 0.09331229 0.0016481  0.4760086 ]
  [0.15566157 0.27787747 0.28519514 0.99001287 0.30659312]]

 [[0.19887564 0.7854187  0.73600153 0.21563679 0.14227911]
  [0.3920094  0.7020292  0.4565794  0.02836779 0.64145586]
  [0.38156677 0.33972491 0.75158348 0.17546113 0.10329371]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
# your code/answer here
print(a == e)
# all values in c are equal to 1 (value*1=value)

[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
# your code here
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

print(d_max)
print(d_min)
print(d_mean)

1.990012866804334
1.0016481014598708
1.4281361190558342


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [17]:
# your code here
f = np.empty((2,3,5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [18]:
# your code here
tup = d.shape
for row in range(tup[0]):
    for col in range(tup[1]):
        for z in range(tup[2]):
            if d[row,col,z]==d_min:
                f[row,col,z] = 0
            elif d[row,col,z]<d_mean:
                f[row,col,z] = 25
            elif d[row,col,z]==d_mean:
                f[row,col,z] = 50
            elif d[row,col,z]==d_max:
                f[row,col,z] = 100
            elif d[row,col,z]>d_mean:
                f[row,col,z] = 75
print(f)

[[[ 75.  75.  75.  25.  75.]
  [ 75.  25.  25.   0.  75.]
  [ 25.  25.  25. 100.  25.]]

 [[ 25.  75.  75.  25.  25.]
  [ 25.  75.  75.  25.  75.]
  [ 25.  25.  75.  25.  25.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [19]:
# your code here
print(d)
print(f)

[[[1.82773972 1.94588555 1.50613791 1.16623967 1.58113502]
  [1.81931653 1.36103658 1.09331229 1.0016481  1.4760086 ]
  [1.15566157 1.27787747 1.28519514 1.99001287 1.30659312]]

 [[1.19887564 1.7854187  1.73600153 1.21563679 1.14227911]
  [1.3920094  1.7020292  1.4565794  1.02836779 1.64145586]
  [1.38156677 1.33972491 1.75158348 1.17546113 1.10329371]]]
[[[ 75.  75.  75.  25.  75.]
  [ 75.  25.  25.   0.  75.]
  [ 25.  25.  25. 100.  25.]]

 [[ 25.  75.  75.  25.  25.]
  [ 25.  75.  75.  25.  75.]
  [ 25.  25.  75.  25.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [20]:
# your code here
tup = d.shape
g = np.empty(tup, dtype="object")
for row in range(tup[0]):
    for col in range(tup[1]):
        for z in range(tup[2]):
            if d[row,col,z]==d_min:
                g[row,col,z] = "A"
            elif d[row,col,z]<d_mean:
                g[row,col,z] = "B"
            elif d[row,col,z]==d_mean:
                g[row,col,z] = "C"
            elif d[row,col,z]==d_max:
                g[row,col,z] = "E"
            elif d[row,col,z]>d_mean:
                g[row,col,z] = "D"
print(g)

[[['D' 'D' 'D' 'B' 'D']
  ['D' 'B' 'B' 'A' 'D']
  ['B' 'B' 'B' 'E' 'B']]

 [['B' 'D' 'D' 'B' 'B']
  ['B' 'D' 'D' 'B' 'D']
  ['B' 'B' 'D' 'B' 'B']]]
