# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [48]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [49]:
# your code here
np.version.version

'1.21.5'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [50]:
# Method 1
a = np.random.random(size=(2,3,5)) 
a

array([[[0.79680604, 0.94358711, 0.58643839, 0.37726779, 0.91725683],
        [0.22003344, 0.82214262, 0.0601602 , 0.49815809, 0.98309072],
        [0.96706848, 0.16183576, 0.98893206, 0.52562609, 0.17477361]],

       [[0.35783487, 0.72820453, 0.93925808, 0.44626323, 0.34527304],
        [0.97425549, 0.86044818, 0.392201  , 0.0348609 , 0.4373033 ],
        [0.1926788 , 0.90899032, 0.47971337, 0.33169505, 0.17283461]]])

In [51]:
# Method 2


In [52]:
# Method 3


#### 4. Print *a*.


In [53]:
# your code here
print(a)

[[[0.79680604 0.94358711 0.58643839 0.37726779 0.91725683]
  [0.22003344 0.82214262 0.0601602  0.49815809 0.98309072]
  [0.96706848 0.16183576 0.98893206 0.52562609 0.17477361]]

 [[0.35783487 0.72820453 0.93925808 0.44626323 0.34527304]
  [0.97425549 0.86044818 0.392201   0.0348609  0.4373033 ]
  [0.1926788  0.90899032 0.47971337 0.33169505 0.17283461]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [54]:
# your code here
b = np.ones(shape=(5,2,3))

#### 6. Print *b*.


In [55]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [56]:
# your code here
print(a.shape)
print(b.shape)

# a has 10 elements and b has 10 elements.

(2, 3, 5)
(5, 2, 3)


#### 8. Are you able to add *a* and *b*? Why or why not?


In [57]:
# your answer here
# First we have to reshape for the same format. And after is possible

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [58]:
# your code here
c = b.reshape(2,3,5) 

print(c)
print(c.shape)


[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
(2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [59]:
# your code/answer here
d = a + c
print(d)

[[[1.79680604 1.94358711 1.58643839 1.37726779 1.91725683]
  [1.22003344 1.82214262 1.0601602  1.49815809 1.98309072]
  [1.96706848 1.16183576 1.98893206 1.52562609 1.17477361]]

 [[1.35783487 1.72820453 1.93925808 1.44626323 1.34527304]
  [1.97425549 1.86044818 1.392201   1.0348609  1.4373033 ]
  [1.1926788  1.90899032 1.47971337 1.33169505 1.17283461]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [60]:
# your code/answer here
print(a)
print(b)

# different array shapes is not possible to make math operations because it don't know witch elements apply the operation. 

[[[0.79680604 0.94358711 0.58643839 0.37726779 0.91725683]
  [0.22003344 0.82214262 0.0601602  0.49815809 0.98309072]
  [0.96706848 0.16183576 0.98893206 0.52562609 0.17477361]]

 [[0.35783487 0.72820453 0.93925808 0.44626323 0.34527304]
  [0.97425549 0.86044818 0.392201   0.0348609  0.4373033 ]
  [0.1926788  0.90899032 0.47971337 0.33169505 0.17283461]]]
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [61]:
# your code here
e = a*c
print(e)

[[[0.79680604 0.94358711 0.58643839 0.37726779 0.91725683]
  [0.22003344 0.82214262 0.0601602  0.49815809 0.98309072]
  [0.96706848 0.16183576 0.98893206 0.52562609 0.17477361]]

 [[0.35783487 0.72820453 0.93925808 0.44626323 0.34527304]
  [0.97425549 0.86044818 0.392201   0.0348609  0.4373033 ]
  [0.1926788  0.90899032 0.47971337 0.33169505 0.17283461]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [62]:
# your code/answer here
print(e == a)

# they are exactly the same. e = a * 1

[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [63]:
# your code here
d_max = d.max()

d_min = d.min()

d_mean = d.mean()

print("The max is: ",d_max)
print("The min is: ",d_min)
print("The mean is: ",d_mean)

The max is:  1.9889320586215231
The min is:  1.03486090455688
The mean is:  1.554166400419355


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [74]:
# your code here
f = np.empty(shape=(2,3,5),dtype=int)

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [75]:
# your code here

f[(d_mean < d) & (d > d_min)]= 25
f[(d > d_mean) & (d < d_max)] = 75
f[d == d_mean] = 50
f[d_min == d] = 0
f[d_max == d] = 100

print(d)
print(f)

[[[1.79680604 1.94358711 1.58643839 1.37726779 1.91725683]
  [1.22003344 1.82214262 1.0601602  1.49815809 1.98309072]
  [1.96706848 1.16183576 1.98893206 1.52562609 1.17477361]]

 [[1.35783487 1.72820453 1.93925808 1.44626323 1.34527304]
  [1.97425549 1.86044818 1.392201   1.0348609  1.4373033 ]
  [1.1926788  1.90899032 1.47971337 1.33169505 1.17283461]]]
[[[ 75  75  75   0  75]
  [  0  75   0   0  75]
  [ 75   0 100   0   0]]

 [[  0  75  75   0   0]
  [ 75  75   0   0   0]
  [  0  75   0   0   0]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [78]:
g = f.astype(str)
h = np.empty_like(g)

h[ g == "25"]= "B"
h[g == "75"] = "D"
h[g == "50"] = "C"
h[g == "0"] = "A"
h[g == "100"] = "E"

print(h)

[[['D' 'D' 'D' 'A' 'D']
  ['A' 'D' 'A' 'A' 'D']
  ['D' 'A' 'E' 'A' 'A']]

 [['A' 'D' 'D' 'A' 'A']
  ['D' 'D' 'A' 'A' 'A']
  ['A' 'D' 'A' 'A' 'A']]]


In [73]:
# your code here
# from numpy import dtype

# f = np.array(f, dtype=object)

# f[(d_mean < d) & (d > d_min)]= "B"
# f[(d > d_mean) & (d < d_max)] = "D"
# f[d == d_mean] = "C"
# f[d_min == d] = "A"
# f[d_max == d] = "E"

# print(f)

[[['D' 'D' 'D' 0 'D']
  [0 'D' 0 0 'D']
  ['D' 0 'E' 0 0]]

 [[0 'D' 'D' 0 0]
  ['D' 'D' 0 'A' 0]
  [0 'D' 0 0 0]]]
