# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [6]:
# your code here
np.__version__

'1.18.5'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [5]:
# Method 1

a = np.random.random((2,3,5))
a

array([[[0.05966224, 0.60959248, 0.28720662, 0.82225747, 0.4729437 ],
        [0.78432817, 0.99137852, 0.66001183, 0.54587878, 0.86617818],
        [0.94357415, 0.97202756, 0.74523095, 0.38592396, 0.39052644]],

       [[0.9471266 , 0.64650234, 0.95962988, 0.73729041, 0.45289482],
        [0.7732689 , 0.09976103, 0.37121404, 0.38374721, 0.03188197],
        [0.45567805, 0.07002082, 0.01995934, 0.38800057, 0.01569916]]])

In [7]:
# Method 2

from numpy import random
a = random.randint(100,size=(2,3,5))
a

array([[[94, 47,  3, 54, 46],
        [31, 77, 89, 22, 63],
        [ 8, 76, 22, 99, 71]],

       [[98, 77, 37, 62, 12],
        [79, 70, 24, 93, 70],
        [19, 46,  6, 19,  1]]])

In [8]:
# Method 3

a = random.rand(2,3,5)
a

array([[[0.89543516, 0.44197635, 0.41223665, 0.27060679, 0.32398086],
        [0.32498346, 0.78651385, 0.20545471, 0.01966314, 0.89537545],
        [0.74266813, 0.37157605, 0.28223995, 0.93833963, 0.59470976]],

       [[0.88748311, 0.81666676, 0.56226109, 0.34899726, 0.74369482],
        [0.83944767, 0.1757549 , 0.67574558, 0.39782976, 0.92127426],
        [0.72010639, 0.06343847, 0.68219272, 0.86099813, 0.07885872]]])

#### 4. Print *a*.


In [9]:
# your code here

print(a)

[[[0.89543516 0.44197635 0.41223665 0.27060679 0.32398086]
  [0.32498346 0.78651385 0.20545471 0.01966314 0.89537545]
  [0.74266813 0.37157605 0.28223995 0.93833963 0.59470976]]

 [[0.88748311 0.81666676 0.56226109 0.34899726 0.74369482]
  [0.83944767 0.1757549  0.67574558 0.39782976 0.92127426]
  [0.72010639 0.06343847 0.68219272 0.86099813 0.07885872]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [14]:
# your code here
b = np.ones((5,2,3))
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 6. Print *b*.


In [15]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [16]:
# your code here

a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [20]:
# your answer here
#print(np.add(a,b))
#they can't be added together because thet don't have the same shape
#we get the error "operands could not be broadcast together with shapes (2,3,5) (5,2,3)

print(a.shape)
print(b.shape)

(2, 3, 5)
(5, 2, 3)


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [27]:
# your code here
c = b.reshape(2,3,5)
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [29]:
# your code/answer here
d = np.add(a,c)
d
#unlike previously, the arrays have the same shape now and can be added

array([[[1.89543516, 1.44197635, 1.41223665, 1.27060679, 1.32398086],
        [1.32498346, 1.78651385, 1.20545471, 1.01966314, 1.89537545],
        [1.74266813, 1.37157605, 1.28223995, 1.93833963, 1.59470976]],

       [[1.88748311, 1.81666676, 1.56226109, 1.34899726, 1.74369482],
        [1.83944767, 1.1757549 , 1.67574558, 1.39782976, 1.92127426],
        [1.72010639, 1.06343847, 1.68219272, 1.86099813, 1.07885872]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [30]:
# your code/answer here
print(a)
print(d)

#the second array's (b) values are the (a) value's +1

[[[0.89543516 0.44197635 0.41223665 0.27060679 0.32398086]
  [0.32498346 0.78651385 0.20545471 0.01966314 0.89537545]
  [0.74266813 0.37157605 0.28223995 0.93833963 0.59470976]]

 [[0.88748311 0.81666676 0.56226109 0.34899726 0.74369482]
  [0.83944767 0.1757549  0.67574558 0.39782976 0.92127426]
  [0.72010639 0.06343847 0.68219272 0.86099813 0.07885872]]]
[[[1.89543516 1.44197635 1.41223665 1.27060679 1.32398086]
  [1.32498346 1.78651385 1.20545471 1.01966314 1.89537545]
  [1.74266813 1.37157605 1.28223995 1.93833963 1.59470976]]

 [[1.88748311 1.81666676 1.56226109 1.34899726 1.74369482]
  [1.83944767 1.1757549  1.67574558 1.39782976 1.92127426]
  [1.72010639 1.06343847 1.68219272 1.86099813 1.07885872]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [32]:
# your code here
e = a*c
e

array([[[0.89543516, 0.44197635, 0.41223665, 0.27060679, 0.32398086],
        [0.32498346, 0.78651385, 0.20545471, 0.01966314, 0.89537545],
        [0.74266813, 0.37157605, 0.28223995, 0.93833963, 0.59470976]],

       [[0.88748311, 0.81666676, 0.56226109, 0.34899726, 0.74369482],
        [0.83944767, 0.1757549 , 0.67574558, 0.39782976, 0.92127426],
        [0.72010639, 0.06343847, 0.68219272, 0.86099813, 0.07885872]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [35]:
# your code/answer here
print(e)
print(a)
e == a

#yes, they have the same values and the same shape

[[[0.89543516 0.44197635 0.41223665 0.27060679 0.32398086]
  [0.32498346 0.78651385 0.20545471 0.01966314 0.89537545]
  [0.74266813 0.37157605 0.28223995 0.93833963 0.59470976]]

 [[0.88748311 0.81666676 0.56226109 0.34899726 0.74369482]
  [0.83944767 0.1757549  0.67574558 0.39782976 0.92127426]
  [0.72010639 0.06343847 0.68219272 0.86099813 0.07885872]]]
[[[0.89543516 0.44197635 0.41223665 0.27060679 0.32398086]
  [0.32498346 0.78651385 0.20545471 0.01966314 0.89537545]
  [0.74266813 0.37157605 0.28223995 0.93833963 0.59470976]]

 [[0.88748311 0.81666676 0.56226109 0.34899726 0.74369482]
  [0.83944767 0.1757549  0.67574558 0.39782976 0.92127426]
  [0.72010639 0.06343847 0.68219272 0.86099813 0.07885872]]]


array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [37]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print(d_max)
print(d_min)
print(d_mean)

1.9383396267152015
1.019663135348662
1.542683652363173


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [46]:
# your code here
f = np.empty((2,3,5))
f

array([[[0.37001269, 0.87463272, 0.50562485, 0.34974534, 0.04823769],
        [0.69486634, 0.85930052, 0.03248325, 0.47115404, 0.11658407],
        [0.52762115, 0.28460843, 0.38550359, 0.03250432, 0.16807243]],

       [[0.07420282, 0.54831336, 0.71966688, 0.65452407, 0.3657328 ],
        [0.20644648, 0.07098188, 0.9934662 , 0.17617772, 0.10371129],
        [0.30604952, 0.65718781, 0.70628892, 0.54496362, 0.5450142 ]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [70]:
# your code here

f = np.where(d == d_max, 100, d)
#since f is an empty array, we're assigning the value on d because otherwise there would be
#no reference.
f = np.where(d < d_max, 75, f)
f = np.where(d == d_mean, 50, f)
f = np.where(d < d_mean, 25, f)
f = np.where(d == d_min, 0, f)
    

print(f)

[[[ 75.  25.  25.  25.  25.]
  [ 25.  75.  25.   0.  75.]
  [ 75.  25.  25. 100.  75.]]

 [[ 75.  75.  75.  25.  75.]
  [ 75.  25.  75.  25.  75.]
  [ 75.  25.  75.  75.  25.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [68]:
# your code here
print(d)
print(f)

[[[1.89543516 1.44197635 1.41223665 1.27060679 1.32398086]
  [1.32498346 1.78651385 1.20545471 1.01966314 1.89537545]
  [1.74266813 1.37157605 1.28223995 1.93833963 1.59470976]]

 [[1.88748311 1.81666676 1.56226109 1.34899726 1.74369482]
  [1.83944767 1.1757549  1.67574558 1.39782976 1.92127426]
  [1.72010639 1.06343847 1.68219272 1.86099813 1.07885872]]]
[[[ 75.  25.  25.  25.  25.]
  [ 25.  75.  25.   0.  75.]
  [ 75.  25.  25. 100.  75.]]

 [[ 75.  75.  75.  25.  75.]
  [ 75.  25.  75.  25.  75.]
  [ 75.  25.  75.  75.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [78]:
# your code here
f = np.where(d == d_max, 'E', d)
#since f is an empty array, we're assigning the value on d because otherwise there would be
#no reference.
f = np.where(d < d_max, 'D', f)
f = np.where(d == d_mean, 'C', f)
f = np.where(d < d_mean, 'B', f)
f = np.where(d == d_min, 'A', f)
    

print(f)

[[['D' 'B' 'B' 'B' 'B']
  ['B' 'D' 'B' 'A' 'D']
  ['D' 'B' 'B' 'E' 'D']]

 [['D' 'D' 'D' 'B' 'D']
  ['D' 'B' 'D' 'B' 'D']
  ['D' 'B' 'D' 'D' 'B']]]
