# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [3]:
print(np.__version__) 

1.20.3


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [4]:
a = np.random.random((2,3,5))
print(a)

[[[0.25374083 0.51830984 0.56738505 0.84817591 0.76124148]
  [0.1792013  0.09898284 0.13832219 0.76298556 0.84713354]
  [0.68241823 0.8800192  0.01472199 0.44798564 0.33462393]]

 [[0.4101816  0.87626492 0.35324532 0.66876848 0.59075928]
  [0.35764702 0.95942269 0.06628844 0.6952114  0.9226963 ]
  [0.80124214 0.79934916 0.16554571 0.22027699 0.53892083]]]


In [15]:
a1 = np.zeros(shape = (2,3,5), dtype = float) #how to insert random values in here?
print(a1)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [13]:
a2 = np.empty(shape = (2,3,5), dtype = float)
print(a2)

[[[0.25374083 0.51830984 0.56738505 0.84817591 0.76124148]
  [0.1792013  0.09898284 0.13832219 0.76298556 0.84713354]
  [0.68241823 0.8800192  0.01472199 0.44798564 0.33462393]]

 [[0.4101816  0.87626492 0.35324532 0.66876848 0.59075928]
  [0.35764702 0.95942269 0.06628844 0.6952114  0.9226963 ]
  [0.80124214 0.79934916 0.16554571 0.22027699 0.53892083]]]


In [29]:
a3 = np.arange(30).reshape(2,3,5) #these are not random values.
print(a3)



[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


#### 4. Print *a*.


In [30]:
print(a)

[[[0.25374083 0.51830984 0.56738505 0.84817591 0.76124148]
  [0.1792013  0.09898284 0.13832219 0.76298556 0.84713354]
  [0.68241823 0.8800192  0.01472199 0.44798564 0.33462393]]

 [[0.4101816  0.87626492 0.35324532 0.66876848 0.59075928]
  [0.35764702 0.95942269 0.06628844 0.6952114  0.9226963 ]
  [0.80124214 0.79934916 0.16554571 0.22027699 0.53892083]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [35]:
b = np.ones(shape = (5,2,3), dtype = int)


#### 6. Print *b*.


In [34]:
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [37]:
if len(a) == len(b):
    print("array is equal")
else:
    print("array is not equal") 

array is not equal


#### 8. Are you able to add *a* and *b*? Why or why not?


In [ ]:
#No because they have different shapes

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [38]:
c = b.reshape (2,3,5)
print(c)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [39]:
d = a + c
print(d)

#it works because we reshaped b into a 2,3,5 array and made it equally shaped as a

[[[1.25374083 1.51830984 1.56738505 1.84817591 1.76124148]
  [1.1792013  1.09898284 1.13832219 1.76298556 1.84713354]
  [1.68241823 1.8800192  1.01472199 1.44798564 1.33462393]]

 [[1.4101816  1.87626492 1.35324532 1.66876848 1.59075928]
  [1.35764702 1.95942269 1.06628844 1.6952114  1.9226963 ]
  [1.80124214 1.79934916 1.16554571 1.22027699 1.53892083]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [41]:
print(a)
print(d)

#array d is array a with 1 instead of the 0; 
#it is the sum of an array of only ones and array a which was randomly created with values between 0 and 1

[[[0.25374083 0.51830984 0.56738505 0.84817591 0.76124148]
  [0.1792013  0.09898284 0.13832219 0.76298556 0.84713354]
  [0.68241823 0.8800192  0.01472199 0.44798564 0.33462393]]

 [[0.4101816  0.87626492 0.35324532 0.66876848 0.59075928]
  [0.35764702 0.95942269 0.06628844 0.6952114  0.9226963 ]
  [0.80124214 0.79934916 0.16554571 0.22027699 0.53892083]]]
[[[1.25374083 1.51830984 1.56738505 1.84817591 1.76124148]
  [1.1792013  1.09898284 1.13832219 1.76298556 1.84713354]
  [1.68241823 1.8800192  1.01472199 1.44798564 1.33462393]]

 [[1.4101816  1.87626492 1.35324532 1.66876848 1.59075928]
  [1.35764702 1.95942269 1.06628844 1.6952114  1.9226963 ]
  [1.80124214 1.79934916 1.16554571 1.22027699 1.53892083]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [42]:
e = a * c
print(e)

[[[0.25374083 0.51830984 0.56738505 0.84817591 0.76124148]
  [0.1792013  0.09898284 0.13832219 0.76298556 0.84713354]
  [0.68241823 0.8800192  0.01472199 0.44798564 0.33462393]]

 [[0.4101816  0.87626492 0.35324532 0.66876848 0.59075928]
  [0.35764702 0.95942269 0.06628844 0.6952114  0.9226963 ]
  [0.80124214 0.79934916 0.16554571 0.22027699 0.53892083]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [43]:
a == e
#it's equal because a was multiplied by an array of ones (c), so the values stay the same

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [48]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print(d_max)
print(d_min)
print(d_mean)

1.9594226904169711
1.0147219861061534
1.5253689264617478


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [49]:
f = np.empty(shape = (2,3,5), dtype = float)

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [51]:
for item in d:
    if d_min < item and item < d_mean:
        f.append(item + 25)
    elif d_mean < item and item < d_max:
        f.append(item + 75)
    elif item == d_mean:
        f.append(item + 50)
    elif item == d_min:
        f.append(0)
    elif item == d_max:
        f.append(100)
    else: 
        continue 

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [57]:
f[(d_min < d) & (d < d_mean)] = 25
f[(d_mean < d) & (d < d_max)] = 75
f[d == d_mean] = 50
f[d == d_min] = 0
f[d == d_max] = 100

print(d)
print(f)

[[[1.25374083 1.51830984 1.56738505 1.84817591 1.76124148]
  [1.1792013  1.09898284 1.13832219 1.76298556 1.84713354]
  [1.68241823 1.8800192  1.01472199 1.44798564 1.33462393]]

 [[1.4101816  1.87626492 1.35324532 1.66876848 1.59075928]
  [1.35764702 1.95942269 1.06628844 1.6952114  1.9226963 ]
  [1.80124214 1.79934916 1.16554571 1.22027699 1.53892083]]]
[[[ 25.  25.  75.  75.  75.]
  [ 25.  25.  25.  75.  75.]
  [ 75.  75.   0.  25.  25.]]

 [[ 25.  75.  25.  75.  75.]
  [ 25. 100.  25.  75.  75.]
  [ 75.  75.  25.  25.  75.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here