# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [2]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [4]:
# your code here
np.version.version

'1.21.5'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [8]:
# Method 1
a=np.random.random((2,3,5))

In [ ]:
# Method 2

In [ ]:
# Method 3

#### 4. Print *a*.


In [9]:
# your code here
print(a)

[[[0.36203516 0.4142569  0.51915552 0.98044203 0.11333573]
  [0.0536844  0.01228644 0.92406549 0.92158768 0.47369442]
  [0.14892623 0.33485303 0.81753522 0.91311977 0.81509042]]

 [[0.76214022 0.26127816 0.00439032 0.52190189 0.36703281]
  [0.97290962 0.19390571 0.7883143  0.05968723 0.10858036]
  [0.4072449  0.35704964 0.75737186 0.46507548 0.00595555]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [10]:
# your code here
b=np.ones((5,2,3))

#### 6. Print *b*.


In [11]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [13]:
# your code here
a.size==b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [14]:
# your answer here
##np.add(a, b)
## can t add because a and b have different shapes

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [33]:
# your code here
c=np.reshape(b,(2,3,5))
c.shape
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [34]:
# your code/answer here
d=np.add(a, c)

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [37]:
# your code/answer here
print(a)
print(d)

##a terms are always smaller than 1 by definition.
##d terms are bigger because d is the sum of elemsnts of a with 1. 

[[[0.36203516 0.4142569  0.51915552 0.98044203 0.11333573]
  [0.0536844  0.01228644 0.92406549 0.92158768 0.47369442]
  [0.14892623 0.33485303 0.81753522 0.91311977 0.81509042]]

 [[0.76214022 0.26127816 0.00439032 0.52190189 0.36703281]
  [0.97290962 0.19390571 0.7883143  0.05968723 0.10858036]
  [0.4072449  0.35704964 0.75737186 0.46507548 0.00595555]]]
[[[1.36203516 1.4142569  1.51915552 1.98044203 1.11333573]
  [1.0536844  1.01228644 1.92406549 1.92158768 1.47369442]
  [1.14892623 1.33485303 1.81753522 1.91311977 1.81509042]]

 [[1.76214022 1.26127816 1.00439032 1.52190189 1.36703281]
  [1.97290962 1.19390571 1.7883143  1.05968723 1.10858036]
  [1.4072449  1.35704964 1.75737186 1.46507548 1.00595555]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [40]:
# your code here
e=np.multiply(a, c)
print(e)

[[[0.36203516 0.4142569  0.51915552 0.98044203 0.11333573]
  [0.0536844  0.01228644 0.92406549 0.92158768 0.47369442]
  [0.14892623 0.33485303 0.81753522 0.91311977 0.81509042]]

 [[0.76214022 0.26127816 0.00439032 0.52190189 0.36703281]
  [0.97290962 0.19390571 0.7883143  0.05968723 0.10858036]
  [0.4072449  0.35704964 0.75737186 0.46507548 0.00595555]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [ ]:
# your code/answer here
## e is different to a because a recalculates and numbers keep changing.

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [42]:
# your code here
d_max=np.max(d)
d_min=np.min(d)
d_mean=np.mean(d)

print(d_max, d_min, d_mean)

1.9804420289953064 1.004390324951761 1.4612302168923272


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [50]:
# your code here
f=np.empty((2, 3, 5))
type(f)

numpy.ndarray

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [49]:
# your code here

if d>d_min & value<d_mean:
    f=25
if d>d_mean & value<d_max:
    f=75
if d==d_mean:
    f=50
if d==d_min:
    f=0
if d==d_max:
    f=100

TypeError: ufunc 'bitwise_and' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here