# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [2]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [3]:
# your code here
!pip show numpy

Name: numpy
Version: 1.23.3
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: BSD
Location: c:\users\jocar\appdata\local\programs\python\python310\lib\site-packages
Requires: 
Required-by: contourpy, matplotlib, pandas, scikit-learn, scipy, seaborn


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [4]:
# Method 1
a = np.random.rand(2,3,5)
a

array([[[0.80612739, 0.65669639, 0.46740848, 0.56939236, 0.91824474],
        [0.5492919 , 0.58366474, 0.71279625, 0.14582235, 0.49713105],
        [0.21169585, 0.55993254, 0.28868695, 0.15693683, 0.45607403]],

       [[0.82690511, 0.17972308, 0.77602871, 0.33851515, 0.46030005],
        [0.78737776, 0.79760313, 0.7157659 , 0.12840245, 0.40354932],
        [0.79929133, 0.9818131 , 0.49235625, 0.93871932, 0.397476  ]]])

In [5]:
# Method 2


In [6]:
# Method 3

#### 4. Print *a*.


In [7]:
# your code here
a 

array([[[0.80612739, 0.65669639, 0.46740848, 0.56939236, 0.91824474],
        [0.5492919 , 0.58366474, 0.71279625, 0.14582235, 0.49713105],
        [0.21169585, 0.55993254, 0.28868695, 0.15693683, 0.45607403]],

       [[0.82690511, 0.17972308, 0.77602871, 0.33851515, 0.46030005],
        [0.78737776, 0.79760313, 0.7157659 , 0.12840245, 0.40354932],
        [0.79929133, 0.9818131 , 0.49235625, 0.93871932, 0.397476  ]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [8]:
# your code here
b = np.ones((5,2,3))
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 6. Print *b*.


In [9]:
# your code here
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [10]:
# your code
a.transpose() # as we can see here it does not have the same size, it has the same number o inicial arrays but in the and A has more quantity of values overall
print(np.size(a))
print(np.size(b))

30
30


#### 8. Are you able to add *a* and *b*? Why or why not?


In [11]:
# your answer here
a.transpose() + b # WE can can't because they are not the same size as we can see

ValueError: operands could not be broadcast together with shapes (5,3,2) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [12]:
# your code here
c = b.reshape(2,3,5)
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [17]:
# your code/answer here
d = a + c # Not sure if this lab was intended this way but it seems there is a error in the way this lab was done since A and B are not the same transposed

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [14]:
# your code/answer here
print(a)

[[[0.80612739 0.65669639 0.46740848 0.56939236 0.91824474]
  [0.5492919  0.58366474 0.71279625 0.14582235 0.49713105]
  [0.21169585 0.55993254 0.28868695 0.15693683 0.45607403]]

 [[0.82690511 0.17972308 0.77602871 0.33851515 0.46030005]
  [0.78737776 0.79760313 0.7157659  0.12840245 0.40354932]
  [0.79929133 0.9818131  0.49235625 0.93871932 0.397476  ]]]


In [18]:
print(d)

[[[1.80612739 1.65669639 1.46740848 1.56939236 1.91824474]
  [1.5492919  1.58366474 1.71279625 1.14582235 1.49713105]
  [1.21169585 1.55993254 1.28868695 1.15693683 1.45607403]]

 [[1.82690511 1.17972308 1.77602871 1.33851515 1.46030005]
  [1.78737776 1.79760313 1.7157659  1.12840245 1.40354932]
  [1.79929133 1.9818131  1.49235625 1.93871932 1.397476  ]]]


In [ ]:
#they have the same size but has diffente values since we added a +  c to get D

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [19]:
# your code here
e = a*c

#### 13. Does *e* equal to *a*? Why or why not?


In [21]:
# your code/answer here
e==a
# because a is mupliplying with one's 2*1 = 2

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [22]:
# your code here
d_max = d.max()
d_mean = d.mean()
d_min = d.min()

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [23]:
# your code here
f = np.empty([2,3,5])
f

array([[[1.80612739, 1.65669639, 1.46740848, 1.56939236, 1.91824474],
        [1.5492919 , 1.58366474, 1.71279625, 1.14582235, 1.49713105],
        [1.21169585, 1.55993254, 1.28868695, 1.15693683, 1.45607403]],

       [[1.82690511, 1.17972308, 1.77602871, 1.33851515, 1.46030005],
        [1.78737776, 1.79760313, 1.7157659 , 1.12840245, 1.40354932],
        [1.79929133, 1.9818131 , 1.49235625, 1.93871932, 1.397476  ]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [39]:
# your code here
for x,g in enumerate(d):
    for y,w in enumerate(g):
        for value,data in enumerate(w) :
            if data > d_min and data < d_mean:
                f[x,y,value] = 25
            elif data > d_mean and data < d_max:
                f[x,y,value] = 75
            elif data == d_mean:
                f[x,y,value] = 50
            elif data == d_min:
                f[x,y,value] = 0
            elif data == d_max:
                f[x,y,value] = 100

print (f)

[[[ 75.  75.  25.  75.  75.]
  [ 25.  75.  75.  25.  25.]
  [ 25.  75.  25.  25.  25.]]

 [[ 75.  25.  75.  25.  25.]
  [ 75.  75.  75.   0.  25.]
  [ 75. 100.  25.  75.  25.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [40]:
# your code h
print(d)
print(f)

[[[1.80612739 1.65669639 1.46740848 1.56939236 1.91824474]
  [1.5492919  1.58366474 1.71279625 1.14582235 1.49713105]
  [1.21169585 1.55993254 1.28868695 1.15693683 1.45607403]]

 [[1.82690511 1.17972308 1.77602871 1.33851515 1.46030005]
  [1.78737776 1.79760313 1.7157659  1.12840245 1.40354932]
  [1.79929133 1.9818131  1.49235625 1.93871932 1.397476  ]]]
[[[ 75.  75.  25.  75.  75.]
  [ 25.  75.  75.  25.  25.]
  [ 25.  75.  25.  25.  25.]]

 [[ 75.  25.  75.  25.  25.]
  [ 75.  75.  75.   0.  25.]
  [ 75. 100.  25.  75.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here