# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.__version__)

1.21.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a=np.random.random(size=(2,3,5))
a

array([[[0.15696991, 0.62565735, 0.98788551, 0.38398747, 0.57149632],
        [0.6772698 , 0.43907222, 0.45743632, 0.20829584, 0.22336059],
        [0.82852863, 0.2629899 , 0.77307479, 0.66854656, 0.19466355]],

       [[0.52891689, 0.12725656, 0.15677488, 0.8542248 , 0.39108584],
        [0.98002878, 0.00366966, 0.74338414, 0.32168089, 0.39036856],
        [0.14949692, 0.01593364, 0.37153532, 0.78638022, 0.26487117]]])

In [4]:
# Method 2
a=np.random.sample((2,3,5))
a

array([[[0.33795126, 0.9584807 , 0.80696026, 0.42875806, 0.40659598],
        [0.5625337 , 0.60207634, 0.10809737, 0.07108886, 0.7858583 ],
        [0.90092768, 0.79140608, 0.619479  , 0.45033619, 0.38332968]],

       [[0.6633066 , 0.43275199, 0.24603228, 0.30307683, 0.97276216],
        [0.08570198, 0.21090535, 0.20829156, 0.32309112, 0.10387773],
        [0.7314834 , 0.0018555 , 0.80220992, 0.68161013, 0.21868146]]])

In [5]:
# Method 3
a = np.random.rand(2,3,5)
a

array([[[0.56317069, 0.7967897 , 0.7822923 , 0.98929286, 0.46659671],
        [0.51553912, 0.04689961, 0.00565442, 0.97353292, 0.02886666],
        [0.75410196, 0.12099879, 0.47409389, 0.99859742, 0.47955492]],

       [[0.82553193, 0.55234016, 0.30800271, 0.7996393 , 0.26353607],
        [0.90856176, 0.16669377, 0.83708388, 0.56550642, 0.59067109],
        [0.24948347, 0.7343331 , 0.9685156 , 0.97377229, 0.67013971]]])

#### 4. Print *a*.


In [6]:
# your code here
print(a)

[[[0.56317069 0.7967897  0.7822923  0.98929286 0.46659671]
  [0.51553912 0.04689961 0.00565442 0.97353292 0.02886666]
  [0.75410196 0.12099879 0.47409389 0.99859742 0.47955492]]

 [[0.82553193 0.55234016 0.30800271 0.7996393  0.26353607]
  [0.90856176 0.16669377 0.83708388 0.56550642 0.59067109]
  [0.24948347 0.7343331  0.9685156  0.97377229 0.67013971]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here
b=np.ones(shape=(5,2,3), dtype=int )

#### 6. Print *b*.


In [8]:
# your code here
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here
a.size==b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here
'''No different shape'''
a.shape==b.shape

False

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here
c=np.reshape(b,(2,3,5))
a.shape==c.shape

True

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# your code/answer here
''' 2 arrays with the same shape, we can apply the sum '''
d=a+c
d

array([[[1.56317069, 1.7967897 , 1.7822923 , 1.98929286, 1.46659671],
        [1.51553912, 1.04689961, 1.00565442, 1.97353292, 1.02886666],
        [1.75410196, 1.12099879, 1.47409389, 1.99859742, 1.47955492]],

       [[1.82553193, 1.55234016, 1.30800271, 1.7996393 , 1.26353607],
        [1.90856176, 1.16669377, 1.83708388, 1.56550642, 1.59067109],
        [1.24948347, 1.7343331 , 1.9685156 , 1.97377229, 1.67013971]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# your code/answer here
print(a)
print(d)

""" we add on d we add +1 on a' values """

[[[0.56317069 0.7967897  0.7822923  0.98929286 0.46659671]
  [0.51553912 0.04689961 0.00565442 0.97353292 0.02886666]
  [0.75410196 0.12099879 0.47409389 0.99859742 0.47955492]]

 [[0.82553193 0.55234016 0.30800271 0.7996393  0.26353607]
  [0.90856176 0.16669377 0.83708388 0.56550642 0.59067109]
  [0.24948347 0.7343331  0.9685156  0.97377229 0.67013971]]]
[[[1.56317069 1.7967897  1.7822923  1.98929286 1.46659671]
  [1.51553912 1.04689961 1.00565442 1.97353292 1.02886666]
  [1.75410196 1.12099879 1.47409389 1.99859742 1.47955492]]

 [[1.82553193 1.55234016 1.30800271 1.7996393  1.26353607]
  [1.90856176 1.16669377 1.83708388 1.56550642 1.59067109]
  [1.24948347 1.7343331  1.9685156  1.97377229 1.67013971]]]


" we add on d we add +1 on a' values "

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
# your code here
e=a*c
e

array([[[0.56317069, 0.7967897 , 0.7822923 , 0.98929286, 0.46659671],
        [0.51553912, 0.04689961, 0.00565442, 0.97353292, 0.02886666],
        [0.75410196, 0.12099879, 0.47409389, 0.99859742, 0.47955492]],

       [[0.82553193, 0.55234016, 0.30800271, 0.7996393 , 0.26353607],
        [0.90856176, 0.16669377, 0.83708388, 0.56550642, 0.59067109],
        [0.24948347, 0.7343331 , 0.9685156 , 0.97377229, 0.67013971]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
# your code/answer here
''' e=a*c because c is the ones array e=a*1=a'''
e==a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
# your code here
d_max=np.max(d)
print("Max of array d:",d_max)
d_min=np.min(d)
print("Min of array d:",d_min)
d_mean=np.mean(d)
print("Mean of array d:",d_mean)

Max of array d: 1.9985974185575826
Min of array d: 1.005654420263388
Mean of array d: 1.5803264410787028


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [56]:
# your code here
f=np.empty((2,3,5))
type(f)

numpy.ndarray

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [58]:
# your code here
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
            for element in range(d.shape[2]):
                if d[i,j,element]>d_min and d[i,j,element]<d_mean:
                    f[i,j,element]=25
                elif (d[i,j,element]>d_mean)&(d[i,j,element]<d_max):
                    f[i,j,element]=75
                elif d[i,j,element]==d_mean:
                    f[i,j,element]=50
                elif d[i,j,element]==d_max:
                    f[i,j,element]=100
                else:
                    f[i,j,element]=0




print(f)



            


[[[ 25.  75.  75.  75.  25.]
  [ 25.  25.   0.  75.  25.]
  [ 75.  25.  25. 100.  25.]]

 [[ 75.  25.  25.  75.  25.]
  [ 75.  25.  75.  25.  75.]
  [ 25.  75.  75.  75.  75.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [59]:
# your code here
print(f)

[[[ 25.  75.  75.  75.  25.]
  [ 25.  25.   0.  75.  25.]
  [ 75.  25.  25. 100.  25.]]

 [[ 75.  25.  25.  75.  25.]
  [ 75.  25.  75.  25.  75.]
  [ 25.  75.  75.  75.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here