# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [2]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [3]:
# your code here
print(np.__version__)

1.20.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [4]:
# Method 1
a = np.random.random((2,3,5))
a

array([[[0.51880248, 0.06422391, 0.17803866, 0.49853836, 0.83231322],
        [0.59554803, 0.34552515, 0.04538314, 0.92169806, 0.87656234],
        [0.62260909, 0.0846587 , 0.6577086 , 0.96511461, 0.2780843 ]],

       [[0.13687628, 0.451198  , 0.65366642, 0.97735164, 0.91371213],
        [0.72132968, 0.61638732, 0.69533996, 0.45632266, 0.22392013],
        [0.0217385 , 0.75482036, 0.22997785, 0.98965945, 0.49823521]]])

In [5]:
# Method 2
a = np.random.sample((2,3,5))
a

array([[[0.29242921, 0.36998357, 0.16993157, 0.88374627, 0.29049383],
        [0.10208427, 0.47444865, 0.32570216, 0.54191343, 0.92680673],
        [0.82978712, 0.20076068, 0.01141497, 0.61139476, 0.41314209]],

       [[0.23952032, 0.50742041, 0.24001296, 0.69721935, 0.10079676],
        [0.10887526, 0.50379409, 0.39951339, 0.08340188, 0.95516227],
        [0.51808502, 0.42726852, 0.3792554 , 0.40319683, 0.28910488]]])

In [6]:
# Method 3
a = np.random.rand(2,3,5)
a

array([[[0.20209236, 0.47858196, 0.85090448, 0.98696473, 0.6861098 ],
        [0.08797378, 0.51836021, 0.82407351, 0.52705598, 0.4733966 ],
        [0.69555128, 0.41537482, 0.21098487, 0.37764275, 0.17138176]],

       [[0.86322271, 0.91173869, 0.61070357, 0.17682686, 0.71027826],
        [0.19338501, 0.8590601 , 0.44438534, 0.36959941, 0.33780595],
        [0.15044503, 0.00533743, 0.85337784, 0.10158207, 0.96054382]]])

#### 4. Print *a*.


In [7]:
# your code here
print(a)

[[[0.20209236 0.47858196 0.85090448 0.98696473 0.6861098 ]
  [0.08797378 0.51836021 0.82407351 0.52705598 0.4733966 ]
  [0.69555128 0.41537482 0.21098487 0.37764275 0.17138176]]

 [[0.86322271 0.91173869 0.61070357 0.17682686 0.71027826]
  [0.19338501 0.8590601  0.44438534 0.36959941 0.33780595]
  [0.15044503 0.00533743 0.85337784 0.10158207 0.96054382]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [8]:
# your code here
b=np.ones((5,2,3))
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 6. Print *b*.


In [9]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [10]:
# your code here
if a.size == b.size:
    print("They have the same size")
else:
    print("They do not have the same size")

They have the same size


#### 8. Are you able to add *a* and *b*? Why or why not?


In [11]:
# your answer here

if a.shape == b.shape:
    print("They have the same shape, so we can add a and b")
else:
    print("They do not have the same shape, so we can not add a and b")

They do not have the same shape, so we can not add a and b


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [12]:
# your code here
c = np.transpose(b, axes=(1,2,0))
       

print(c.shape)

(2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [13]:
# your code/answer here
d = a + c
d
print("It is possible to add a and c because now they have the same shape!")

It is possible to add a and c because now they have the same shape!


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [14]:
# your code/answer here
print(a)

print("\n")

print(d)

print("\n")
print("All the values existing in d seem to be the values in a added 1!")

[[[0.20209236 0.47858196 0.85090448 0.98696473 0.6861098 ]
  [0.08797378 0.51836021 0.82407351 0.52705598 0.4733966 ]
  [0.69555128 0.41537482 0.21098487 0.37764275 0.17138176]]

 [[0.86322271 0.91173869 0.61070357 0.17682686 0.71027826]
  [0.19338501 0.8590601  0.44438534 0.36959941 0.33780595]
  [0.15044503 0.00533743 0.85337784 0.10158207 0.96054382]]]


[[[1.20209236 1.47858196 1.85090448 1.98696473 1.6861098 ]
  [1.08797378 1.51836021 1.82407351 1.52705598 1.4733966 ]
  [1.69555128 1.41537482 1.21098487 1.37764275 1.17138176]]

 [[1.86322271 1.91173869 1.61070357 1.17682686 1.71027826]
  [1.19338501 1.8590601  1.44438534 1.36959941 1.33780595]
  [1.15044503 1.00533743 1.85337784 1.10158207 1.96054382]]]


All the values existing in d seem to be the values in a added 1!


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [15]:
# your code here
e = a * c
e

array([[[0.20209236, 0.47858196, 0.85090448, 0.98696473, 0.6861098 ],
        [0.08797378, 0.51836021, 0.82407351, 0.52705598, 0.4733966 ],
        [0.69555128, 0.41537482, 0.21098487, 0.37764275, 0.17138176]],

       [[0.86322271, 0.91173869, 0.61070357, 0.17682686, 0.71027826],
        [0.19338501, 0.8590601 , 0.44438534, 0.36959941, 0.33780595],
        [0.15044503, 0.00533743, 0.85337784, 0.10158207, 0.96054382]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [16]:
# your code/answer here

if np.array_equal(e, a):
    print("Yes, they're the same!")
else:    
    print("No, they're are not the same!")

print("\n")

print("a and e are equal, becase all elements inside c are ones, and if we multiply value by one we will get allways value")


Yes, they're the same!


a and e are equal, becase all elements inside c are ones, and if we multiply value by one we will get allways value


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [17]:
# your code here
d_max=d.max()
print(d_max)

d_min=d.min()
print(d_min)

d_mean=d.mean()
print(d_mean)


1.9869647277116465
1.005337433056428
1.5018246996028943


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [29]:
# your code here
f = np.empty((2, 3, 5))
f

array([[[1.20209236, 1.47858196, 1.85090448, 1.98696473, 1.6861098 ],
        [1.08797378, 1.51836021, 1.82407351, 1.52705598, 1.4733966 ],
        [1.69555128, 1.41537482, 1.21098487, 1.37764275, 1.17138176]],

       [[1.86322271, 1.91173869, 1.61070357, 1.17682686, 1.71027826],
        [1.19338501, 1.8590601 , 1.44438534, 1.36959941, 1.33780595],
        [1.15044503, 1.00533743, 1.85337784, 1.10158207, 1.96054382]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [30]:
# your code here

for arrays in range(2):
    for rows in range(3):
        for values in range(5):

            if d[arrays,rows,values]>d_min and d[arrays,rows,values]<d_mean:
                f[arrays,rows,values]=25
            elif d[arrays,rows,values]>d_mean and d[arrays,rows,values]<d_max:
                f[arrays,rows,values]=75
            elif d[arrays,rows,values]==d_mean:
                f[arrays,rows,values]=50
            elif d[arrays,rows,values]==d_min:
                f[arrays,rows,values]=0
            elif d[arrays,rows,values]==d_max:
                f[arrays,rows,values]=100



#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [31]:
# your code here

print(d,"\n")                
print(f)

[[[1.20209236 1.47858196 1.85090448 1.98696473 1.6861098 ]
  [1.08797378 1.51836021 1.82407351 1.52705598 1.4733966 ]
  [1.69555128 1.41537482 1.21098487 1.37764275 1.17138176]]

 [[1.86322271 1.91173869 1.61070357 1.17682686 1.71027826]
  [1.19338501 1.8590601  1.44438534 1.36959941 1.33780595]
  [1.15044503 1.00533743 1.85337784 1.10158207 1.96054382]]] 

[[[ 25.  25.  75. 100.  75.]
  [ 25.  75.  75.  75.  25.]
  [ 75.  25.  25.  25.  25.]]

 [[ 75.  75.  75.  25.  75.]
  [ 25.  75.  25.  25.  25.]
  [ 25.   0.  75.  25.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [32]:
# your code here

f = np.empty((2, 3, 5), str)

for arrays in range(2):
    for rows in range(3):
        for values in range(5):

            if d[arrays,rows,values]>d_min and d[arrays,rows,values]<d_mean:
                f[arrays,rows,values]="B"
            elif d[arrays,rows,values]>d_mean and d[arrays,rows,values]<d_max:
                f[arrays,rows,values]="D"
            elif d[arrays,rows,values]==d_mean:
                f[arrays,rows,values]="C"
            elif d[arrays,rows,values]==d_min:
                f[arrays,rows,values]="A"
            elif d[arrays,rows,values]==d_max:
                f[arrays,rows,values]="E"
                
print(f)       

[[['B' 'B' 'D' 'E' 'D']
  ['B' 'D' 'D' 'D' 'B']
  ['D' 'B' 'B' 'B' 'B']]

 [['D' 'D' 'D' 'B' 'D']
  ['B' 'D' 'B' 'B' 'B']
  ['B' 'A' 'D' 'B' 'D']]]
