# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.version.version)

1.20.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [4]:
# Method 1
a = np.empty((2,3,5))
a

array([[[9.38187998e-312, 9.63428009e-322, 0.00000000e+000,
         0.00000000e+000, 7.56571287e-307],
        [1.16097020e-028, 2.57707022e-057, 9.71521737e-067,
         1.65982454e-076, 5.01163173e+217],
        [8.37170074e-144, 6.22688250e-038, 3.88586809e-033,
         6.25768489e-091, 9.13768337e+169]],

       [[5.01163113e+217, 5.49419094e-143, 3.68777431e+180,
         5.56111702e+180, 7.49874326e+247],
        [9.51498384e-053, 6.25527297e-091, 1.43692990e-051,
         4.31696156e-038, 3.92321515e+179],
        [1.47763641e+248, 1.16096346e-028, 1.28625693e+248,
         4.24948967e-086, 1.69121096e-306]]])

In [6]:
# Method 2
a1 = np.random.rand(2,3,5)  #random float in range 0 - 1
a1

array([[[0.27159911, 0.94736951, 0.88077186, 0.1245827 , 0.76305289],
        [0.32522655, 0.16666657, 0.17732118, 0.30999294, 0.34994209],
        [0.13279279, 0.40320341, 0.76182174, 0.2494437 , 0.73881351]],

       [[0.49042553, 0.92835517, 0.05342939, 0.03533115, 0.40104133],
        [0.98365327, 0.50800479, 0.68601262, 0.46959034, 0.08481008],
        [0.59367031, 0.32073678, 0.24976952, 0.91603902, 0.52344917]]])

In [10]:
# Method 3
a2 = np.random.randint(1000000,size=(2,3,5))  #random integers in range 0 - 1000000
a2

array([[[236732, 478199, 951685, 700019, 544526],
        [274853,  75880, 995957, 670597, 378379],
        [658419, 673356, 282825, 119318, 597483]],

       [[252459, 918708, 450232, 812279, 237307],
        [773450, 386459,  84065, 160001, 306920],
        [887788, 589563, 507831, 308949,  12653]]])

#### 4. Print *a*.


In [12]:
# your code here
print(a)
print(a1)
print(a2)

[[[9.38187998e-312 9.63428009e-322 0.00000000e+000 0.00000000e+000
   7.56571287e-307]
  [1.16097020e-028 2.57707022e-057 9.71521737e-067 1.65982454e-076
   5.01163173e+217]
  [8.37170074e-144 6.22688250e-038 3.88586809e-033 6.25768489e-091
   9.13768337e+169]]

 [[5.01163113e+217 5.49419094e-143 3.68777431e+180 5.56111702e+180
   7.49874326e+247]
  [9.51498384e-053 6.25527297e-091 1.43692990e-051 4.31696156e-038
   3.92321515e+179]
  [1.47763641e+248 1.16096346e-028 1.28625693e+248 4.24948967e-086
   1.69121096e-306]]]
[[[0.27159911 0.94736951 0.88077186 0.1245827  0.76305289]
  [0.32522655 0.16666657 0.17732118 0.30999294 0.34994209]
  [0.13279279 0.40320341 0.76182174 0.2494437  0.73881351]]

 [[0.49042553 0.92835517 0.05342939 0.03533115 0.40104133]
  [0.98365327 0.50800479 0.68601262 0.46959034 0.08481008]
  [0.59367031 0.32073678 0.24976952 0.91603902 0.52344917]]]
[[[236732 478199 951685 700019 544526]
  [274853  75880 995957 670597 378379]
  [658419 673356 282825 119318 597483]

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [14]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [15]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [18]:
# your code here
a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [22]:
# your answer here
# No. They have same size but different shape: a shape (2,3,5) and b shape (5,2,3)

a.shape == b.shape

False

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [23]:
# your code here
c = b.reshape(2,3,5)
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [24]:
# your code/answer here
d = a + c
d                #now they have the same shape because we reshape the b array

array([[[1.00000000e+000, 1.00000000e+000, 1.00000000e+000,
         1.00000000e+000, 1.00000000e+000],
        [1.00000000e+000, 1.00000000e+000, 1.00000000e+000,
         1.00000000e+000, 5.01163173e+217],
        [1.00000000e+000, 1.00000000e+000, 1.00000000e+000,
         1.00000000e+000, 9.13768337e+169]],

       [[5.01163113e+217, 1.00000000e+000, 3.68777431e+180,
         5.56111702e+180, 7.49874326e+247],
        [1.00000000e+000, 1.00000000e+000, 1.00000000e+000,
         1.00000000e+000, 3.92321515e+179],
        [1.47763641e+248, 1.00000000e+000, 1.28625693e+248,
         1.00000000e+000, 1.00000000e+000]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [25]:
# your code/answer here
print(a)
print(d)

# the array c had the value 1 in all positions. adding to array a, if the value is much bigger than 1 the difference is not notceable printing the array. if the value is much lower than 1 the value in d will be 1. 

[[[9.38187998e-312 9.63428009e-322 0.00000000e+000 0.00000000e+000
   7.56571287e-307]
  [1.16097020e-028 2.57707022e-057 9.71521737e-067 1.65982454e-076
   5.01163173e+217]
  [8.37170074e-144 6.22688250e-038 3.88586809e-033 6.25768489e-091
   9.13768337e+169]]

 [[5.01163113e+217 5.49419094e-143 3.68777431e+180 5.56111702e+180
   7.49874326e+247]
  [9.51498384e-053 6.25527297e-091 1.43692990e-051 4.31696156e-038
   3.92321515e+179]
  [1.47763641e+248 1.16096346e-028 1.28625693e+248 4.24948967e-086
   1.69121096e-306]]]
[[[1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
   1.00000000e+000]
  [1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
   5.01163173e+217]
  [1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
   9.13768337e+169]]

 [[5.01163113e+217 1.00000000e+000 3.68777431e+180 5.56111702e+180
   7.49874326e+247]
  [1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
   3.92321515e+179]
  [1.47763641e+248 1.00000000e+000 1.

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [26]:
# your code here
e = a*c
print(e)

[[[9.38187998e-312 9.63428009e-322 0.00000000e+000 0.00000000e+000
   7.56571287e-307]
  [1.16097020e-028 2.57707022e-057 9.71521737e-067 1.65982454e-076
   5.01163173e+217]
  [8.37170074e-144 6.22688250e-038 3.88586809e-033 6.25768489e-091
   9.13768337e+169]]

 [[5.01163113e+217 5.49419094e-143 3.68777431e+180 5.56111702e+180
   7.49874326e+247]
  [9.51498384e-053 6.25527297e-091 1.43692990e-051 4.31696156e-038
   3.92321515e+179]
  [1.47763641e+248 1.16096346e-028 1.28625693e+248 4.24948967e-086
   1.69121096e-306]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [27]:
# your code/answer here
# Yes. because multiplying one number by 1 will give the number.

e == a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [34]:
# your code here
d_max = np.amax(d)
d_min = np.amin(d)
d_mean = np.mean(d)

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [36]:
# your code here

f = np.empty((2,3,5))
f

array([[[9.38187998e-312, 9.63428009e-322, 0.00000000e+000,
         0.00000000e+000, 7.56571287e-307],
        [1.16097020e-028, 2.57707022e-057, 9.71521737e-067,
         1.65982454e-076, 5.01163173e+217],
        [8.37170074e-144, 6.22688250e-038, 3.88586809e-033,
         6.25768489e-091, 9.13768337e+169]],

       [[5.01163113e+217, 5.49419094e-143, 3.68777431e+180,
         5.56111702e+180, 7.49874326e+247],
        [9.51498384e-053, 6.25527297e-091, 1.43692990e-051,
         4.31696156e-038, 3.92321515e+179],
        [1.47763641e+248, 1.16096346e-028, 1.28625693e+248,
         4.24948967e-086, 1.69121096e-306]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [40]:
# your code here
#d.shape = (2,3,5)

for i in range(0,2):
    for j in range (0,3):
        for k in range (0,5):
            if d[i][j][k] > d_min and d[i][j][k] < d_mean:
                f[i][j][k] = 25
            elif d[i][j][k] < d_max and d[i][j][k] > d_mean:
                f[i][j][k] = 75
            elif d[i][j][k] == d_mean:
                f[i][j][k] = 50
            elif d[i][j][k] == d_min:
                f[i][j][k] = 0
            elif d[i][j][k] == d_max:
                f[i][j][k] = 100
            else:
                print("error")

f

array([[[  0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,  25.],
        [  0.,   0.,   0.,   0.,  25.]],

       [[ 25.,   0.,  25.,  25.,  75.],
        [  0.,   0.,   0.,   0.,  25.],
        [100.,   0.,  75.,   0.,   0.]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [41]:
# your code here
print(d)
print(f)

#yes

[[[1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
   1.00000000e+000]
  [1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
   5.01163173e+217]
  [1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
   9.13768337e+169]]

 [[5.01163113e+217 1.00000000e+000 3.68777431e+180 5.56111702e+180
   7.49874326e+247]
  [1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
   3.92321515e+179]
  [1.47763641e+248 1.00000000e+000 1.28625693e+248 1.00000000e+000
   1.00000000e+000]]]
[[[  0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.  25.]
  [  0.   0.   0.   0.  25.]]

 [[ 25.   0.  25.  25.  75.]
  [  0.   0.   0.   0.  25.]
  [100.   0.  75.   0.   0.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [49]:
# your code here
g = np.empty((2,3,5),dtype="U")


for i in range(0,2):
    for j in range (0,3):
        for k in range (0,5):
            if d[i][j][k] > d_min and d[i][j][k] < d_mean:
                g[i][j][k] = "B"
            elif d[i][j][k] < d_max and d[i][j][k] > d_mean:
                g[i][j][k] = "D"
            elif d[i][j][k] == d_mean:
                g[i][j][k] = "C"
            elif d[i][j][k] == d_min:
                g[i][j][k] = "A"
            elif d[i][j][k] == d_max:
                g[i][j][k] = "E"
            else:
                print("error")
print(g)

[[['A' 'A' 'A' 'A' 'A']
  ['A' 'A' 'A' 'A' 'B']
  ['A' 'A' 'A' 'A' 'B']]

 [['B' 'A' 'B' 'B' 'D']
  ['A' 'A' 'A' 'A' 'B']
  ['E' 'A' 'D' 'A' 'A']]]
