# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [76]:
# your code here
import numpy as np


#### 2. Print your NumPy version.

In [77]:
# your code here

print(np.__version__)

1.23.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [78]:
# Method 1
myarraya = np.random.rand(2, 3, 5)
a = myarraya

In [79]:
# Method 2
#¿?

In [80]:
# Method 3
#¿?

#### 4. Print *a*.


In [81]:
# your code herea
a

array([[[0.9622012 , 0.68401175, 0.92129142, 0.21063041, 0.9531126 ],
        [0.6448279 , 0.83191571, 0.57907917, 0.89587852, 0.41243569],
        [0.98967683, 0.03546157, 0.25337469, 0.95921911, 0.15031784]],

       [[0.53010454, 0.13710341, 0.02179434, 0.21937253, 0.51261877],
        [0.32979838, 0.57808173, 0.5667957 , 0.80159631, 0.96924552],
        [0.28306735, 0.54886252, 0.45906404, 0.03135791, 0.49664123]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [82]:
# your code here
myarrayb = np.ones((5, 2, 3))

b = myarrayb

#### 6. Print *b*.


In [83]:
# your code here
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [84]:
# your code here
if np.shape(a) == np.shape(b):
    print(True)
else:
    print("They are not equal")

They are not equal


#### 8. Are you able to add *a* and *b*? Why or why not?


In [85]:
# your answer here

# ab = a + b
# ab

# Cannot add them because they don't have the same shape
    # ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [86]:
# your code here
b = np.transpose(a, (1, 2, 0)).reshape(2, 3, 5)
c = b
c

array([[[0.9622012 , 0.53010454, 0.68401175, 0.13710341, 0.92129142],
        [0.02179434, 0.21063041, 0.21937253, 0.9531126 , 0.51261877],
        [0.6448279 , 0.32979838, 0.83191571, 0.57808173, 0.57907917]],

       [[0.5667957 , 0.89587852, 0.80159631, 0.41243569, 0.96924552],
        [0.98967683, 0.28306735, 0.03546157, 0.54886252, 0.25337469],
        [0.45906404, 0.95921911, 0.03135791, 0.15031784, 0.49664123]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [87]:
# your code/answer here
d = a + c
d

# It works now because they are the same shape

array([[[1.9244024 , 1.21411629, 1.60530316, 0.34773382, 1.87440401],
        [0.66662224, 1.04254612, 0.7984517 , 1.84899112, 0.92505446],
        [1.63450473, 0.36525995, 1.0852904 , 1.53730085, 0.72939701]],

       [[1.09690025, 1.03298193, 0.82339065, 0.63180822, 1.48186428],
        [1.31947521, 0.86114909, 0.60225727, 1.35045883, 1.22262021],
        [0.74213139, 1.50808163, 0.49042195, 0.18167575, 0.99328245]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [88]:
# your code/answer here
print(a)
print(" ")
print(d)
# that they are both floats?

[[[0.9622012  0.68401175 0.92129142 0.21063041 0.9531126 ]
  [0.6448279  0.83191571 0.57907917 0.89587852 0.41243569]
  [0.98967683 0.03546157 0.25337469 0.95921911 0.15031784]]

 [[0.53010454 0.13710341 0.02179434 0.21937253 0.51261877]
  [0.32979838 0.57808173 0.5667957  0.80159631 0.96924552]
  [0.28306735 0.54886252 0.45906404 0.03135791 0.49664123]]]
 
[[[1.9244024  1.21411629 1.60530316 0.34773382 1.87440401]
  [0.66662224 1.04254612 0.7984517  1.84899112 0.92505446]
  [1.63450473 0.36525995 1.0852904  1.53730085 0.72939701]]

 [[1.09690025 1.03298193 0.82339065 0.63180822 1.48186428]
  [1.31947521 0.86114909 0.60225727 1.35045883 1.22262021]
  [0.74213139 1.50808163 0.49042195 0.18167575 0.99328245]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [89]:
# your code here
e = a * c
c

array([[[0.9622012 , 0.53010454, 0.68401175, 0.13710341, 0.92129142],
        [0.02179434, 0.21063041, 0.21937253, 0.9531126 , 0.51261877],
        [0.6448279 , 0.32979838, 0.83191571, 0.57808173, 0.57907917]],

       [[0.5667957 , 0.89587852, 0.80159631, 0.41243569, 0.96924552],
        [0.98967683, 0.28306735, 0.03546157, 0.54886252, 0.25337469],
        [0.45906404, 0.95921911, 0.03135791, 0.15031784, 0.49664123]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [90]:
# your code/answer here
e == a
#ttey don't have the same values

array([[[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]],

       [[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [91]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(d_max)
print(d_min)
print(d_mean)

1.9244023966818753
0.181675752341653
1.0645959118302344


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [92]:
# your code here
f = np.empty((2,3,5))
f

array([[[0.9622012 , 0.53010454, 0.68401175, 0.13710341, 0.92129142],
        [0.02179434, 0.21063041, 0.21937253, 0.9531126 , 0.51261877],
        [0.6448279 , 0.32979838, 0.83191571, 0.57808173, 0.57907917]],

       [[0.5667957 , 0.89587852, 0.80159631, 0.41243569, 0.96924552],
        [0.98967683, 0.28306735, 0.03546157, 0.54886252, 0.25337469],
        [0.45906404, 0.95921911, 0.03135791, 0.15031784, 0.49664123]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [96]:
# your code here

f[(d > d_min) & (d < d_mean)] = 25
f[(d > d_mean) & (d < d_max)] = 75
f[d == d_mean] = 50
f[d == d_min] = 0
f[d == d_max] = 100

print(d)
print(" ")
print(f)


[[[1.9244024  1.21411629 1.60530316 0.34773382 1.87440401]
  [0.66662224 1.04254612 0.7984517  1.84899112 0.92505446]
  [1.63450473 0.36525995 1.0852904  1.53730085 0.72939701]]

 [[1.09690025 1.03298193 0.82339065 0.63180822 1.48186428]
  [1.31947521 0.86114909 0.60225727 1.35045883 1.22262021]
  [0.74213139 1.50808163 0.49042195 0.18167575 0.99328245]]]
 
[[[100.  75.  75.  25.  75.]
  [ 25.  25.  25.  75.  25.]
  [ 75.  25.  75.  75.  25.]]

 [[ 75.  25.  25.  25.  75.]
  [ 75.  25.  25.  75.  75.]
  [ 25.  75.  25.   0.  25.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [94]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [95]:
# your code here