# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [5]:
print(np.__version__)

1.23.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [35]:
# Method 1
a = np.random.random(size = (2,5,3))
a

array([[[0.27037873, 0.70309754, 0.82337817],
        [0.20766475, 0.05413314, 0.8032404 ],
        [0.38223483, 0.5359152 , 0.67083381],
        [0.28344007, 0.79039299, 0.63706239],
        [0.95277429, 0.35026345, 0.40956157]],

       [[0.48340665, 0.91636314, 0.1425986 ],
        [0.02143037, 0.19644788, 0.83660673],
        [0.00513804, 0.34560732, 0.39811757],
        [0.74611856, 0.17200909, 0.80826464],
        [0.67436406, 0.82727513, 0.58980246]]])

In [16]:
# Method 2
np.arange(start = 10, stop = 30)


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [9]:
# Method 3
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [17]:
np.linspace(start = 18, stop = 80, num = 30)


array([18.        , 20.13793103, 22.27586207, 24.4137931 , 26.55172414,
       28.68965517, 30.82758621, 32.96551724, 35.10344828, 37.24137931,
       39.37931034, 41.51724138, 43.65517241, 45.79310345, 47.93103448,
       50.06896552, 52.20689655, 54.34482759, 56.48275862, 58.62068966,
       60.75862069, 62.89655172, 65.03448276, 67.17241379, 69.31034483,
       71.44827586, 73.5862069 , 75.72413793, 77.86206897, 80.        ])

#### 4. Print *a*.


In [20]:
# your code here
print (a)

[[[0.89097919 0.05595845 0.97682385]
  [0.49302744 0.95289283 0.34244638]
  [0.02879384 0.52265663 0.85916947]
  [0.08807397 0.40824695 0.35273691]
  [0.83319282 0.60011868 0.90759892]]

 [[0.82002392 0.14040795 0.07741416]
  [0.19218605 0.42625625 0.02376496]
  [0.28585249 0.820609   0.48523099]
  [0.74063318 0.37669379 0.1529996 ]
  [0.15708925 0.527143   0.42613889]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [21]:
# your code here
b = np.ones(shape = (5,2,3), dtype=int)
b

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

#### 6. Print *b*.


In [22]:
# your code here
print (b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [25]:
# your code here

#No, their size is different

print (a.shape)
print (b.shape)

(2, 5, 3)
(5, 2, 3)


#### 8. Are you able to add *a* and *b*? Why or why not?


In [ ]:
# your answer here

##No, because their structure is different

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [31]:
# your code here
c = b.reshape (2,5,3)
c

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [36]:
# your code/answer here
d = a + c
d

array([[[1.27037873, 1.70309754, 1.82337817],
        [1.20766475, 1.05413314, 1.8032404 ],
        [1.38223483, 1.5359152 , 1.67083381],
        [1.28344007, 1.79039299, 1.63706239],
        [1.95277429, 1.35026345, 1.40956157]],

       [[1.48340665, 1.91636314, 1.1425986 ],
        [1.02143037, 1.19644788, 1.83660673],
        [1.00513804, 1.34560732, 1.39811757],
        [1.74611856, 1.17200909, 1.80826464],
        [1.67436406, 1.82727513, 1.58980246]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [38]:
print (a)
print (d)

#Yes, they are different because the second one is the values of the first plus 1

[[[0.27037873 0.70309754 0.82337817]
  [0.20766475 0.05413314 0.8032404 ]
  [0.38223483 0.5359152  0.67083381]
  [0.28344007 0.79039299 0.63706239]
  [0.95277429 0.35026345 0.40956157]]

 [[0.48340665 0.91636314 0.1425986 ]
  [0.02143037 0.19644788 0.83660673]
  [0.00513804 0.34560732 0.39811757]
  [0.74611856 0.17200909 0.80826464]
  [0.67436406 0.82727513 0.58980246]]]
[[[1.27037873 1.70309754 1.82337817]
  [1.20766475 1.05413314 1.8032404 ]
  [1.38223483 1.5359152  1.67083381]
  [1.28344007 1.79039299 1.63706239]
  [1.95277429 1.35026345 1.40956157]]

 [[1.48340665 1.91636314 1.1425986 ]
  [1.02143037 1.19644788 1.83660673]
  [1.00513804 1.34560732 1.39811757]
  [1.74611856 1.17200909 1.80826464]
  [1.67436406 1.82727513 1.58980246]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [39]:
e = a * c
e

array([[[0.27037873, 0.70309754, 0.82337817],
        [0.20766475, 0.05413314, 0.8032404 ],
        [0.38223483, 0.5359152 , 0.67083381],
        [0.28344007, 0.79039299, 0.63706239],
        [0.95277429, 0.35026345, 0.40956157]],

       [[0.48340665, 0.91636314, 0.1425986 ],
        [0.02143037, 0.19644788, 0.83660673],
        [0.00513804, 0.34560732, 0.39811757],
        [0.74611856, 0.17200909, 0.80826464],
        [0.67436406, 0.82727513, 0.58980246]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [40]:
# your code/answer here

print (a)
print (e)

#Yes it does, because the second array is the values of the first times 1 and as we know a number times 1 equals
#the number

[[[0.27037873 0.70309754 0.82337817]
  [0.20766475 0.05413314 0.8032404 ]
  [0.38223483 0.5359152  0.67083381]
  [0.28344007 0.79039299 0.63706239]
  [0.95277429 0.35026345 0.40956157]]

 [[0.48340665 0.91636314 0.1425986 ]
  [0.02143037 0.19644788 0.83660673]
  [0.00513804 0.34560732 0.39811757]
  [0.74611856 0.17200909 0.80826464]
  [0.67436406 0.82727513 0.58980246]]]
[[[0.27037873 0.70309754 0.82337817]
  [0.20766475 0.05413314 0.8032404 ]
  [0.38223483 0.5359152  0.67083381]
  [0.28344007 0.79039299 0.63706239]
  [0.95277429 0.35026345 0.40956157]]

 [[0.48340665 0.91636314 0.1425986 ]
  [0.02143037 0.19644788 0.83660673]
  [0.00513804 0.34560732 0.39811757]
  [0.74611856 0.17200909 0.80826464]
  [0.67436406 0.82727513 0.58980246]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [51]:
# your code here

d_max = d.max()
d_max


1.9527742895851388

In [53]:
d_min = d.min()
d_min



1.005138035128263

In [54]:
d_mean = d.mean()
d_mean

1.501264052400867

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [60]:
# your code here

f = np.empty(shape = (2,3,5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [1]:
# your code here

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here