# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [2]:
import numpy as np

#### 2. Print your NumPy version.

In [3]:
# your code here
print(np.__version__)

1.21.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [16]:
a=np.random.random((2,3,5))
a

array([[[0.96881227, 0.06016052, 0.26759621, 0.28355687, 0.4507519 ],
        [0.25693934, 0.41231298, 0.60250247, 0.47060494, 0.30482515],
        [0.07830898, 0.5700477 , 0.40427318, 0.94153008, 0.93954432]],

       [[0.97575154, 0.10227755, 0.3257704 , 0.91062939, 0.49662268],
        [0.22001142, 0.80869521, 0.83740595, 0.63127145, 0.05766389],
        [0.83299504, 0.05845878, 0.08581865, 0.368717  , 0.95264678]]])

In [17]:
a = np.random.rand(2, 3, 5)
a

array([[[0.92068654, 0.43079997, 0.32932657, 0.31582423, 0.85125125],
        [0.25692332, 0.32522498, 0.42901798, 0.39736523, 0.75127485],
        [0.11979122, 0.45008064, 0.45931856, 0.41801972, 0.88101788]],

       [[0.69719929, 0.06920114, 0.34742023, 0.33152093, 0.99809335],
        [0.47099167, 0.54715114, 0.42512594, 0.10057153, 0.8678816 ],
        [0.5012752 , 0.93740914, 0.46619138, 0.69017922, 0.60014649]]])

In [18]:
# Method 3
a = np.random.sample((2, 3, 5))
a

array([[[0.49045168, 0.52661492, 0.19157676, 0.15995021, 0.6499651 ],
        [0.98028578, 0.61605114, 0.65571319, 0.92224772, 0.40507601],
        [0.79134972, 0.96853535, 0.07217886, 0.63143297, 0.80706936]],

       [[0.2207653 , 0.85498994, 0.76804519, 0.10552899, 0.95400725],
        [0.23216503, 0.82324473, 0.38848851, 0.88400883, 0.53002719],
        [0.66639163, 0.65837778, 0.62914288, 0.1365919 , 0.60187818]]])

#### 4. Print *a*.


In [19]:
# your code here
print(a)

[[[0.49045168 0.52661492 0.19157676 0.15995021 0.6499651 ]
  [0.98028578 0.61605114 0.65571319 0.92224772 0.40507601]
  [0.79134972 0.96853535 0.07217886 0.63143297 0.80706936]]

 [[0.2207653  0.85498994 0.76804519 0.10552899 0.95400725]
  [0.23216503 0.82324473 0.38848851 0.88400883 0.53002719]
  [0.66639163 0.65837778 0.62914288 0.1365919  0.60187818]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [20]:
# your code here
b = np.ones((5, 2, 3))

#### 6. Print *b*.


In [21]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [22]:
# your code here
if a.size == b.size:
    print("They have the same size!")
else:
    print("They don't have the same size.")

They have the same size!


#### 8. Are you able to add *a* and *b*? Why or why not?


In [23]:
# your answer here
# No, because even they have the same size, they have a different shape
c=a+b

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [24]:
# your code here
c = np.transpose(b, axes=(1, 2, 0))
c.shape

(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [26]:
# your code/answer here
d=a+c
d

array([[[1.49045168, 1.52661492, 1.19157676, 1.15995021, 1.6499651 ],
        [1.98028578, 1.61605114, 1.65571319, 1.92224772, 1.40507601],
        [1.79134972, 1.96853535, 1.07217886, 1.63143297, 1.80706936]],

       [[1.2207653 , 1.85498994, 1.76804519, 1.10552899, 1.95400725],
        [1.23216503, 1.82324473, 1.38848851, 1.88400883, 1.53002719],
        [1.66639163, 1.65837778, 1.62914288, 1.1365919 , 1.60187818]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [28]:
# your code/answer here
print(a)
print(d)
# d is equal to a + 1

[[[0.49045168 0.52661492 0.19157676 0.15995021 0.6499651 ]
  [0.98028578 0.61605114 0.65571319 0.92224772 0.40507601]
  [0.79134972 0.96853535 0.07217886 0.63143297 0.80706936]]

 [[0.2207653  0.85498994 0.76804519 0.10552899 0.95400725]
  [0.23216503 0.82324473 0.38848851 0.88400883 0.53002719]
  [0.66639163 0.65837778 0.62914288 0.1365919  0.60187818]]]
[[[1.49045168 1.52661492 1.19157676 1.15995021 1.6499651 ]
  [1.98028578 1.61605114 1.65571319 1.92224772 1.40507601]
  [1.79134972 1.96853535 1.07217886 1.63143297 1.80706936]]

 [[1.2207653  1.85498994 1.76804519 1.10552899 1.95400725]
  [1.23216503 1.82324473 1.38848851 1.88400883 1.53002719]
  [1.66639163 1.65837778 1.62914288 1.1365919  1.60187818]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [30]:
# your code here
e=a*c
print(e)

[[[0.49045168 0.52661492 0.19157676 0.15995021 0.6499651 ]
  [0.98028578 0.61605114 0.65571319 0.92224772 0.40507601]
  [0.79134972 0.96853535 0.07217886 0.63143297 0.80706936]]

 [[0.2207653  0.85498994 0.76804519 0.10552899 0.95400725]
  [0.23216503 0.82324473 0.38848851 0.88400883 0.53002719]
  [0.66639163 0.65837778 0.62914288 0.1365919  0.60187818]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [31]:
# your code/answer here
e==a
#because c is just a transpose of a array with values of 1, and multiply by 1 doesnt change the value

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [32]:
# your code here
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

print(d_max)
print(d_min)
print(d_mean)

1.9802857772756273
1.0721788609926723
1.5774050698340716


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [33]:
# your code here
f = np.empty([2, 3, 5])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [35]:
# your code here
f = []
for number in np.nditer(d):
    if d_min < number < d_mean:
        f = f +[25]
    if d_mean < number < d_max:
        f = f +[75]
    if number == d_mean:
        f = f +[50]
    if number == d_min:
        f = f +[0]
    if number == d_max:
        f = f +[100]
    
        
f = np.reshape(f, d.shape) 

[[[ 25  25  25  25  75]
  [100  75  75  75  25]
  [ 75  75   0  75  75]]

 [[ 25  75  75  25  75]
  [ 25  75  25  75  25]
  [ 75  75  75  25  75]]]
[[[1.49045168 1.52661492 1.19157676 1.15995021 1.6499651 ]
  [1.98028578 1.61605114 1.65571319 1.92224772 1.40507601]
  [1.79134972 1.96853535 1.07217886 1.63143297 1.80706936]]

 [[1.2207653  1.85498994 1.76804519 1.10552899 1.95400725]
  [1.23216503 1.82324473 1.38848851 1.88400883 1.53002719]
  [1.66639163 1.65837778 1.62914288 1.1365919  1.60187818]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [37]:
# your code here
print(d)
print(f)

[[[1.49045168 1.52661492 1.19157676 1.15995021 1.6499651 ]
  [1.98028578 1.61605114 1.65571319 1.92224772 1.40507601]
  [1.79134972 1.96853535 1.07217886 1.63143297 1.80706936]]

 [[1.2207653  1.85498994 1.76804519 1.10552899 1.95400725]
  [1.23216503 1.82324473 1.38848851 1.88400883 1.53002719]
  [1.66639163 1.65837778 1.62914288 1.1365919  1.60187818]]]
[[[ 25  25  25  25  75]
  [100  75  75  75  25]
  [ 75  75   0  75  75]]

 [[ 25  75  75  25  75]
  [ 25  75  25  75  25]
  [ 75  75  75  25  75]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here
g = []
for letter in np.nditer(d):
    if d_min < letter < d_mean:
        j += ['B']
    if d_mean < x < d_max:
        j += ['D']
    if x == d_mean:
        j += ['C']
    if x == d_min:
        j += ['A']
    if x == d_max:
        j += ['E']
    
j = np.reshape(j, d.shape) 
print(j)