# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [2]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [3]:
# your code here
np.version

<module 'numpy.version' from '/srv/conda/envs/notebook/lib/python3.7/site-packages/numpy/version.py'>

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [8]:
# Method 1
a = np.random.random((2,3,5))

array([[[0.27459585, 0.87059051, 0.83884431, 0.17084112, 0.55276139],
        [0.02536632, 0.41271126, 0.01799559, 0.30268202, 0.87323472],
        [0.65378818, 0.01569161, 0.45748629, 0.32168189, 0.14882876]],

       [[0.9152309 , 0.06278466, 0.12895659, 0.13779077, 0.85627357],
        [0.67416908, 0.4806742 , 0.66850602, 0.68975136, 0.65070012],
        [0.64971675, 0.89360778, 0.56062464, 0.19241429, 0.76969478]]])

In [13]:
# Method 2

#lst1 = np.random.random([3,5])
#lst2 = np.random.random([3,5])
#b = np.array(lst1, lst2)


In [ ]:
# Method 3

#### 4. Print *a*.


In [9]:
# your code here
print(a)

[[[0.27459585 0.87059051 0.83884431 0.17084112 0.55276139]
  [0.02536632 0.41271126 0.01799559 0.30268202 0.87323472]
  [0.65378818 0.01569161 0.45748629 0.32168189 0.14882876]]

 [[0.9152309  0.06278466 0.12895659 0.13779077 0.85627357]
  [0.67416908 0.4806742  0.66850602 0.68975136 0.65070012]
  [0.64971675 0.89360778 0.56062464 0.19241429 0.76969478]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [53]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [54]:
# your code here
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [55]:
# your code here
comp = np.array_equiv(a,b)
print(comp)

False


#### 8. Are you able to add *a* and *b*? Why or why not?


In [ ]:
# your answer here
# Not without modifiyng either one, as they do not match size/shape.

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [84]:
# your code here
c = b.reshape(2,3,5)
#np.shape(b)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [86]:
# your code/answer here
d = np.add(a, c)

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [90]:
# your code/answer here
print(a,"\n\n", d)
# D is just a+1 on each value.

[[[0.27459585 0.87059051 0.83884431 0.17084112 0.55276139]
  [0.02536632 0.41271126 0.01799559 0.30268202 0.87323472]
  [0.65378818 0.01569161 0.45748629 0.32168189 0.14882876]]

 [[0.9152309  0.06278466 0.12895659 0.13779077 0.85627357]
  [0.67416908 0.4806742  0.66850602 0.68975136 0.65070012]
  [0.64971675 0.89360778 0.56062464 0.19241429 0.76969478]]] 

 [[[1.27459585 1.87059051 1.83884431 1.17084112 1.55276139]
  [1.02536632 1.41271126 1.01799559 1.30268202 1.87323472]
  [1.65378818 1.01569161 1.45748629 1.32168189 1.14882876]]

 [[1.9152309  1.06278466 1.12895659 1.13779077 1.85627357]
  [1.67416908 1.4806742  1.66850602 1.68975136 1.65070012]
  [1.64971675 1.89360778 1.56062464 1.19241429 1.76969478]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [92]:
# your code here
e = np.multiply(a, c)
print(e)

[[[0.27459585 0.87059051 0.83884431 0.17084112 0.55276139]
  [0.02536632 0.41271126 0.01799559 0.30268202 0.87323472]
  [0.65378818 0.01569161 0.45748629 0.32168189 0.14882876]]

 [[0.9152309  0.06278466 0.12895659 0.13779077 0.85627357]
  [0.67416908 0.4806742  0.66850602 0.68975136 0.65070012]
  [0.64971675 0.89360778 0.56062464 0.19241429 0.76969478]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [94]:
# your code/answer here
comp = np.array_equiv(a,e)
print(comp)
# Yes, as 1*X = X is a mathematical true (mostly)

True


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [98]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print(d_max, d_min, d_mean)

1.9152309007688615 1.0156916074615945 1.475599843938419


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [104]:
# your code here
f = np.empty((2,3,5))
print(f)

[[[1.27459585 1.87059051 1.83884431 1.17084112 1.55276139]
  [1.02536632 1.41271126 1.01799559 1.30268202 1.87323472]
  [1.65378818 1.01569161 1.45748629 1.32168189 1.14882876]]

 [[1.9152309  1.06278466 1.12895659 1.13779077 1.85627357]
  [1.67416908 1.4806742  1.66850602 1.68975136 1.65070012]
  [1.64971675 1.89360778 1.56062464 1.19241429 1.76969478]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [130]:
# your code here
pos1 = 0
pos2 = 0
pos3 = 0
f = np.empty((2,3,5))
for i in d:
    for x in i:
        for y in x:
            if(y<=d_min):
                f[pos1, pos2, pos3] = 0
            if(d_min<y<d_mean):
                f[pos1, pos2, pos3] = 25
            if(y == d_mean):
                f[pos1, pos2, pos3] = 50
            if(d_mean<y<d_max):
                f[pos1, pos2, pos3] = 75
            if(d_max<=y):
                f[pos1, pos2, pos3] = 100
            pos3 += 1
        pos2 += 1
        pos3 = 0
    pos1 += 1
    pos2 =0
print(f)

[[[ 25.  75.  75.  25.  75.]
  [ 25.  25.  25.  25.  75.]
  [ 75.   0.  25.  25.  25.]]

 [[100.  25.  25.  25.  75.]
  [ 75.  75.  75.  75.  75.]
  [ 75.  75.  75.  25.  75.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [131]:
# your code here
print(d,"\n\n", f)

[[[1.27459585 1.87059051 1.83884431 1.17084112 1.55276139]
  [1.02536632 1.41271126 1.01799559 1.30268202 1.87323472]
  [1.65378818 1.01569161 1.45748629 1.32168189 1.14882876]]

 [[1.9152309  1.06278466 1.12895659 1.13779077 1.85627357]
  [1.67416908 1.4806742  1.66850602 1.68975136 1.65070012]
  [1.64971675 1.89360778 1.56062464 1.19241429 1.76969478]]] 

 [[[ 25.  75.  75.  25.  75.]
  [ 25.  25.  25.  25.  75.]
  [ 75.   0.  25.  25.  25.]]

 [[100.  25.  25.  25.  75.]
  [ 75.  75.  75.  75.  75.]
  [ 75.  75.  75.  25.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [133]:
# your code here
pos1 = 0
pos2 = 0
pos3 = 0
f = np.empty((2,3,5))
for i in d:
    for x in i:
        for y in x:
            if(y<=d_min):
                f[pos1, pos2, pos3] = 'A'
            if(d_min<y<d_mean):
                f[pos1, pos2, pos3] = 'B'
            if(y == d_mean):
                f[pos1, pos2, pos3] = 'C'
            if(d_mean<y<d_max):
                f[pos1, pos2, pos3] = 'D'
            if(d_max<=y):
                f[pos1, pos2, pos3] = 'E'
            pos3 += 1
        pos2 += 1
        pos3 = 0
    pos1 += 1
    pos2 =0
print(f)

ValueError: could not convert string to float: 'B'