# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.__version__)

1.19.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1

a = np.random.rand(2,3,5)

In [4]:
# Method 2

In [5]:
# Method 3

#### 4. Print *a*.


In [6]:
# your code here
print(a)

[[[0.7139753  0.76290987 0.38842701 0.27982504 0.6467288 ]
  [0.13711485 0.59582936 0.54450591 0.56561999 0.06507731]
  [0.81957304 0.8743094  0.08568628 0.63999586 0.48570776]]

 [[0.16673634 0.26347942 0.26486046 0.21815434 0.13777591]
  [0.89019238 0.82449191 0.38049991 0.5390604  0.37358366]
  [0.34594491 0.73721361 0.38888815 0.91444649 0.24377833]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here

b = np.ones((5,2,3))

#### 6. Print *b*.


In [8]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here

#from https://stackoverflow.com/questions/10580676/comparing-two-numpy-arrays-for-equality-element-wise

np.array_equal(a,b)

False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here

a+b

#justify: you can't add a and b because they have different shapes (2,3,5) different than (5,2,3)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here

#create variable c; transpose and reshape b to have the same structure as a (2,3,5)

c = b.transpose().reshape(2,3,5)
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# your code/answer here

d = a+c
print(d)

#justify: you can add a and c. This is because c has the same shape as a (exercise 9)

[[[1.7139753  1.76290987 1.38842701 1.27982504 1.6467288 ]
  [1.13711485 1.59582936 1.54450591 1.56561999 1.06507731]
  [1.81957304 1.8743094  1.08568628 1.63999586 1.48570776]]

 [[1.16673634 1.26347942 1.26486046 1.21815434 1.13777591]
  [1.89019238 1.82449191 1.38049991 1.5390604  1.37358366]
  [1.34594491 1.73721361 1.38888815 1.91444649 1.24377833]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# your code/answer here
print('variable a')
print(a)
print('variable d')
print(d)

#there are differences in terms of values on the two arrays. but why??

variable a
[[[0.7139753  0.76290987 0.38842701 0.27982504 0.6467288 ]
  [0.13711485 0.59582936 0.54450591 0.56561999 0.06507731]
  [0.81957304 0.8743094  0.08568628 0.63999586 0.48570776]]

 [[0.16673634 0.26347942 0.26486046 0.21815434 0.13777591]
  [0.89019238 0.82449191 0.38049991 0.5390604  0.37358366]
  [0.34594491 0.73721361 0.38888815 0.91444649 0.24377833]]]
variable d
[[[1.7139753  1.76290987 1.38842701 1.27982504 1.6467288 ]
  [1.13711485 1.59582936 1.54450591 1.56561999 1.06507731]
  [1.81957304 1.8743094  1.08568628 1.63999586 1.48570776]]

 [[1.16673634 1.26347942 1.26486046 1.21815434 1.13777591]
  [1.89019238 1.82449191 1.38049991 1.5390604  1.37358366]
  [1.34594491 1.73721361 1.38888815 1.91444649 1.24377833]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
# your code here
e = a*c
print(e)

[[[0.7139753  0.76290987 0.38842701 0.27982504 0.6467288 ]
  [0.13711485 0.59582936 0.54450591 0.56561999 0.06507731]
  [0.81957304 0.8743094  0.08568628 0.63999586 0.48570776]]

 [[0.16673634 0.26347942 0.26486046 0.21815434 0.13777591]
  [0.89019238 0.82449191 0.38049991 0.5390604  0.37358366]
  [0.34594491 0.73721361 0.38888815 0.91444649 0.24377833]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
# your code/answer here
print('variable e')
print(e)
print('variable a')
print(a)

e==a

#i can see that e is equal to a, but why??

variable e
[[[0.7139753  0.76290987 0.38842701 0.27982504 0.6467288 ]
  [0.13711485 0.59582936 0.54450591 0.56561999 0.06507731]
  [0.81957304 0.8743094  0.08568628 0.63999586 0.48570776]]

 [[0.16673634 0.26347942 0.26486046 0.21815434 0.13777591]
  [0.89019238 0.82449191 0.38049991 0.5390604  0.37358366]
  [0.34594491 0.73721361 0.38888815 0.91444649 0.24377833]]]
variable a
[[[0.7139753  0.76290987 0.38842701 0.27982504 0.6467288 ]
  [0.13711485 0.59582936 0.54450591 0.56561999 0.06507731]
  [0.81957304 0.8743094  0.08568628 0.63999586 0.48570776]]

 [[0.16673634 0.26347942 0.26486046 0.21815434 0.13777591]
  [0.89019238 0.82449191 0.38049991 0.5390604  0.37358366]
  [0.34594491 0.73721361 0.38888815 0.91444649 0.24377833]]]


array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
# your code here

#max
d_max = d.max()

#min
d_min = d.min()

#mean
d_mean = d.mean()

#print results
print(d_max)
print(d_min)
print(d_mean)

1.9144464929404226
1.0650773051548867
1.476479732902927


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [17]:
# your code here
f = np.empty((2,3,5))
f

array([[[0.7139753 , 0.76290987, 0.38842701, 0.27982504, 0.6467288 ],
        [0.13711485, 0.59582936, 0.54450591, 0.56561999, 0.06507731],
        [0.81957304, 0.8743094 , 0.08568628, 0.63999586, 0.48570776]],

       [[0.16673634, 0.26347942, 0.26486046, 0.21815434, 0.13777591],
        [0.89019238, 0.82449191, 0.38049991, 0.5390604 , 0.37358366],
        [0.34594491, 0.73721361, 0.38888815, 0.91444649, 0.24377833]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [1]:
# your code here

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here