# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [3]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [4]:
# your code here
print(np.version.version)

1.21.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [5]:
# Method 1 Make a Random Array with the .random.random
a = np.random.random((2,3,5))

In [6]:
# Method 2 Using lists with random numbers and convert them to an array
a = np.array([[[1, 2, 3, 4, 5], [3, 4, 3, 4, 3, ], [3, 4, 3, 4, 3, ]], [[5, 6, 3, 5, 6], [7, 8, 3, 4, 7], [3, 4, 3, 4, 3, ]]])

In [7]:
# Method 3 Reshape an existing array
a = (np.random.random((3,5,2))).reshape(2,3,5)


#### 4. Print *a*.


In [8]:
# your code here
print(a)

[[[0.00464312 0.94691879 0.02984961 0.27018632 0.94045694]
  [0.31931921 0.68006492 0.92952451 0.82968184 0.27259965]
  [0.46809694 0.98665943 0.58276136 0.26059739 0.49403273]]

 [[0.46450408 0.61601987 0.77993737 0.78346448 0.00268526]
  [0.29697656 0.97355295 0.60076447 0.02544459 0.06286578]
  [0.64912949 0.55952939 0.87046637 0.53607584 0.48164286]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [9]:
# your code here
b = np.ones((5,2,3), dtype = int)

#### 6. Print *b*.


In [10]:
# your code here
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [11]:
# your code here
a.shape == b.shape

False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [12]:
# your answer here
#No, because the arrays a and b do NOT have the same dimensions


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [13]:
# your code here
c = np.transpose(b, (1,2,0))
c.shape

(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [14]:
# your code/answer here
d = a + c
d
#Because the arrays have the same dimensions

array([[[1.00464312, 1.94691879, 1.02984961, 1.27018632, 1.94045694],
        [1.31931921, 1.68006492, 1.92952451, 1.82968184, 1.27259965],
        [1.46809694, 1.98665943, 1.58276136, 1.26059739, 1.49403273]],

       [[1.46450408, 1.61601987, 1.77993737, 1.78346448, 1.00268526],
        [1.29697656, 1.97355295, 1.60076447, 1.02544459, 1.06286578],
        [1.64912949, 1.55952939, 1.87046637, 1.53607584, 1.48164286]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [15]:
print(a)

print("----------------------------------------------------")
print(d)

#Matrix d values are equal to matrix a values+1 due to the previous sum with matrix c, which was an array whose values were all 1

[[[0.00464312 0.94691879 0.02984961 0.27018632 0.94045694]
  [0.31931921 0.68006492 0.92952451 0.82968184 0.27259965]
  [0.46809694 0.98665943 0.58276136 0.26059739 0.49403273]]

 [[0.46450408 0.61601987 0.77993737 0.78346448 0.00268526]
  [0.29697656 0.97355295 0.60076447 0.02544459 0.06286578]
  [0.64912949 0.55952939 0.87046637 0.53607584 0.48164286]]]
----------------------------------------------------
[[[1.00464312 1.94691879 1.02984961 1.27018632 1.94045694]
  [1.31931921 1.68006492 1.92952451 1.82968184 1.27259965]
  [1.46809694 1.98665943 1.58276136 1.26059739 1.49403273]]

 [[1.46450408 1.61601987 1.77993737 1.78346448 1.00268526]
  [1.29697656 1.97355295 1.60076447 1.02544459 1.06286578]
  [1.64912949 1.55952939 1.87046637 1.53607584 1.48164286]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [16]:
# your code here
e = a*c


#### 13. Does *e* equal to *a*? Why or why not?


In [17]:
# your code/answer here
e == a 
#Yes! Because we multiplied the matrix a values with the matrix c values (which are all 1)

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [18]:
# your code here
d_max = np.max(d)
print(d_max)

d_min = np.min(d)
print(d_min)

d_mean = np.mean(d)
print(d_mean)


1.9866594272282194
1.002685264082344
1.523948403458608


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [19]:
# your code here
f = np.empty((2,3,5))
print(f)

[[[1.00464312 1.94691879 1.02984961 1.27018632 1.94045694]
  [1.31931921 1.68006492 1.92952451 1.82968184 1.27259965]
  [1.46809694 1.98665943 1.58276136 1.26059739 1.49403273]]

 [[1.46450408 1.61601987 1.77993737 1.78346448 1.00268526]
  [1.29697656 1.97355295 1.60076447 1.02544459 1.06286578]
  [1.64912949 1.55952939 1.87046637 1.53607584 1.48164286]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [45]:
# your code here

#fast and easey way
# f = 25 * (d > d_min) * (d < d_mean) + 75 * (d < d_max) * (d > d_mean) + 0 * (d == d_min) + 100 * (d == d_max) + 50 * (d == d_mean)


f_list =[]
for list_ in d:
    for sublist_ in list_:
        for item in sublist_:
            if d_min < item < d_mean:
                f_list.append(25)
            if d_mean < item < d_max:
                f_list.append(75)
            if item == d_min:
                f_list.append(0)
            if item == d_mean:
                f_list.append(50)
            if item == d_max:
                f_list.append(100)
f1 = np.array(f_list)
f =f1.reshape(2,3,5)
f


array([[[ 25,  75,  25,  25,  75],
        [ 25,  75,  75,  75,  25],
        [ 25, 100,  75,  25,  25]],

       [[ 25,  75,  75,  75,   0],
        [ 25,  75,  75,  25,  25],
        [ 75,  75,  75,  75,  25]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [21]:
# your code here
print(d)
print(f)

[[[1.00464312 1.94691879 1.02984961 1.27018632 1.94045694]
  [1.31931921 1.68006492 1.92952451 1.82968184 1.27259965]
  [1.46809694 1.98665943 1.58276136 1.26059739 1.49403273]]

 [[1.46450408 1.61601987 1.77993737 1.78346448 1.00268526]
  [1.29697656 1.97355295 1.60076447 1.02544459 1.06286578]
  [1.64912949 1.55952939 1.87046637 1.53607584 1.48164286]]]
[[[ 25  75  25  25  75]
  [ 25  75  75  75  25]
  [ 25 100  75  25  25]]

 [[ 25  75  75  75   0]
  [ 25  75  75  25  25]
  [ 75  75  75  75  25]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [46]:

f_list =[]
for list_ in d:
    for sublist_ in list_:
        for item in sublist_:
            if d_min < item < d_mean:
                f_list.append("B")
            if d_mean < item < d_max:
                f_list.append("D")
            if item == d_min:
                f_list.append("A")
            if item == d_mean:
                f_list.append("C")
            if item == d_max:
                f_list.append("E")
f1 = np.array(f_list)
f =f1.reshape(2,3,5)
f
   

array([[['B', 'D', 'B', 'B', 'D'],
        ['B', 'D', 'D', 'D', 'B'],
        ['B', 'E', 'D', 'B', 'B']],

       [['B', 'D', 'D', 'D', 'A'],
        ['B', 'D', 'D', 'B', 'B'],
        ['D', 'D', 'D', 'D', 'B']]], dtype='<U1')