# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [2]:
import numpy as np# your code here

#### 2. Print your NumPy version.

In [3]:
np.version.version

'1.17.2'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [4]:
a = np.random.rand(2,3,5) 
a

array([[[0.80192377, 0.07927071, 0.92332741, 0.29567035, 0.2754369 ],
        [0.60421576, 0.52463199, 0.08307221, 0.14841183, 0.69836097],
        [0.76166989, 0.03427547, 0.2393135 , 0.35700692, 0.34655561]],

       [[0.5709747 , 0.4650664 , 0.07941604, 0.19495666, 0.19515428],
        [0.3486418 , 0.03951058, 0.15345685, 0.32205818, 0.53388221],
        [0.28419047, 0.51502379, 0.1392722 , 0.72763056, 0.01725346]]])

In [5]:
a = np.random.choice(10**8, size=(2,3,5))/(10**8) # to keep with same decimal plates & interval as previous
a

array([[[0.53428595, 0.69088674, 0.61671384, 0.01569166, 0.3768081 ],
        [0.59940649, 0.85782237, 0.31119841, 0.70553019, 0.72964368],
        [0.69660932, 0.23440719, 0.242684  , 0.10818089, 0.45926301]],

       [[0.35461952, 0.35852282, 0.93696106, 0.44662275, 0.12727906],
        [0.7891333 , 0.64822401, 0.5455352 , 0.18663284, 0.35329708],
        [0.07159887, 0.80259879, 0.69866282, 0.91522242, 0.82729156]]])

In [6]:
a = np.random.randint(10**8, size=(2,3,5))/10**8 # to keep with same decimal plates & interval as previous
a

array([[[0.16183433, 0.58498109, 0.56889758, 0.21827362, 0.14299773],
        [0.24847285, 0.63889039, 0.18909729, 0.04703202, 0.88168408],
        [0.62008769, 0.5181677 , 0.77804595, 0.2811388 , 0.91487449]],

       [[0.38995703, 0.05149927, 0.72082426, 0.51558835, 0.71549209],
        [0.36101849, 0.18603588, 0.54764081, 0.00185797, 0.81251314],
        [0.23795039, 0.46989392, 0.99953652, 0.04549058, 0.18518391]]])

#### 4. Print *a*.


In [7]:
print (a)

[[[0.16183433 0.58498109 0.56889758 0.21827362 0.14299773]
  [0.24847285 0.63889039 0.18909729 0.04703202 0.88168408]
  [0.62008769 0.5181677  0.77804595 0.2811388  0.91487449]]

 [[0.38995703 0.05149927 0.72082426 0.51558835 0.71549209]
  [0.36101849 0.18603588 0.54764081 0.00185797 0.81251314]
  [0.23795039 0.46989392 0.99953652 0.04549058 0.18518391]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [23]:
b = np.ones((5,2,3))

#### 6. Print *b*.


In [24]:
print (b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [25]:
a.size == b.size

a.shape == b.shape

# They have the same size but different shapes

False

#### 8. Are you able to add *a* and *b*? Why or why not?


c = a + b 

#generates error because you cannot add two numpy arrays of different shapes 
# (like in algebra you cannot add two matrices of different shape)

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [27]:
c = b.transpose((1,2,0))
c.shape

(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [28]:
d = a + c
d
# it works because (5,3,2) transposed is (2,3,5) so now c and a have the same shape/dimensions

array([[[1.16183433, 1.58498109, 1.56889758, 1.21827362, 1.14299773],
        [1.24847285, 1.63889039, 1.18909729, 1.04703202, 1.88168408],
        [1.62008769, 1.5181677 , 1.77804595, 1.2811388 , 1.91487449]],

       [[1.38995703, 1.05149927, 1.72082426, 1.51558835, 1.71549209],
        [1.36101849, 1.18603588, 1.54764081, 1.00185797, 1.81251314],
        [1.23795039, 1.46989392, 1.99953652, 1.04549058, 1.18518391]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
print (a)
print (d)

#since we added to a an array of all 1's, d is just equivalent a+1 in every position

[[[0.16183433 0.58498109 0.56889758 0.21827362 0.14299773]
  [0.24847285 0.63889039 0.18909729 0.04703202 0.88168408]
  [0.62008769 0.5181677  0.77804595 0.2811388  0.91487449]]

 [[0.38995703 0.05149927 0.72082426 0.51558835 0.71549209]
  [0.36101849 0.18603588 0.54764081 0.00185797 0.81251314]
  [0.23795039 0.46989392 0.99953652 0.04549058 0.18518391]]]
[[[1.16183433 1.58498109 1.56889758 1.21827362 1.14299773]
  [1.24847285 1.63889039 1.18909729 1.04703202 1.88168408]
  [1.62008769 1.5181677  1.77804595 1.2811388  1.91487449]]

 [[1.38995703 1.05149927 1.72082426 1.51558835 1.71549209]
  [1.36101849 1.18603588 1.54764081 1.00185797 1.81251314]
  [1.23795039 1.46989392 1.99953652 1.04549058 1.18518391]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
e = a * c
e

array([[[0.16183433, 0.58498109, 0.56889758, 0.21827362, 0.14299773],
        [0.24847285, 0.63889039, 0.18909729, 0.04703202, 0.88168408],
        [0.62008769, 0.5181677 , 0.77804595, 0.2811388 , 0.91487449]],

       [[0.38995703, 0.05149927, 0.72082426, 0.51558835, 0.71549209],
        [0.36101849, 0.18603588, 0.54764081, 0.00185797, 0.81251314],
        [0.23795039, 0.46989392, 0.99953652, 0.04549058, 0.18518391]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
e == a

# Yes, e == a because I used * that is element wise multiplication and so we multiply each element by 1. 

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(d_max, d_min, d_mean)

1.99953652 1.00185797 1.4344986073333332


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [17]:
f = np.empty((2,3,5))
f
# do not understand why f is initialized to the same values as a???

array([[[0.16183433, 0.58498109, 0.56889758, 0.21827362, 0.14299773],
        [0.24847285, 0.63889039, 0.18909729, 0.04703202, 0.88168408],
        [0.62008769, 0.5181677 , 0.77804595, 0.2811388 , 0.91487449]],

       [[0.38995703, 0.05149927, 0.72082426, 0.51558835, 0.71549209],
        [0.36101849, 0.18603588, 0.54764081, 0.00185797, 0.81251314],
        [0.23795039, 0.46989392, 0.99953652, 0.04549058, 0.18518391]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [18]:
#old school

for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d_min < d[i,j,k] < d_mean:
                f[i,j,k] = 25
            elif d_mean < d[i,j,k] < d_max:
                f[i,j,k] = 75
            elif d[i,j,k] == d_mean:
                f[i,j,k] = 50
            elif d[i,j,k] == d_min:
                f[i,j,k] = 0
            elif d[i,j,k] == d_max:
                f[i,j,k] = 100

In [19]:
# no tabbing version

# sum all for conditions above in one line
# d=d_min is filled by default
f = np.where((d > d_min) & (d < d_mean),25,0) + np.where((d > d_mean) & (d < d_max),75,0) + np.where(d == d_mean,50,0) + np.where(d == d_max,100,0)

print(d)
print(f)

[[[1.16183433 1.58498109 1.56889758 1.21827362 1.14299773]
  [1.24847285 1.63889039 1.18909729 1.04703202 1.88168408]
  [1.62008769 1.5181677  1.77804595 1.2811388  1.91487449]]

 [[1.38995703 1.05149927 1.72082426 1.51558835 1.71549209]
  [1.36101849 1.18603588 1.54764081 1.00185797 1.81251314]
  [1.23795039 1.46989392 1.99953652 1.04549058 1.18518391]]]
[[[ 25  75  75  25  25]
  [ 25  75  25  25  75]
  [ 75  75  75  25  75]]

 [[ 25  25  75  75  75]
  [ 25  25  75   0  75]
  [ 25  75 100  25  25]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [20]:
print(d)
print(f)

[[[1.16183433 1.58498109 1.56889758 1.21827362 1.14299773]
  [1.24847285 1.63889039 1.18909729 1.04703202 1.88168408]
  [1.62008769 1.5181677  1.77804595 1.2811388  1.91487449]]

 [[1.38995703 1.05149927 1.72082426 1.51558835 1.71549209]
  [1.36101849 1.18603588 1.54764081 1.00185797 1.81251314]
  [1.23795039 1.46989392 1.99953652 1.04549058 1.18518391]]]
[[[ 25  75  75  25  25]
  [ 25  75  25  25  75]
  [ 75  75  75  25  75]]

 [[ 25  25  75  75  75]
  [ 25  25  75   0  75]
  [ 25  75 100  25  25]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [21]:
f1 = np.where((d > d_min) & (d < d_mean),'B','') 
f2 = np.where((d > d_mean) & (d < d_max),'D','')
f3 = np.where(d == d_mean,'C','') 
f4 = np.where(d == d_max,'E','')
f5 = np.where(d == d_min,'A','')
f = np.char.add(np.char.add(np.char.add(np.char.add(f1, f2),f3),f4),f5)
f
#could be old school for/if also

array([[['B', 'D', 'D', 'B', 'B'],
        ['B', 'D', 'B', 'B', 'D'],
        ['D', 'D', 'D', 'B', 'D']],

       [['B', 'B', 'D', 'D', 'D'],
        ['B', 'B', 'D', 'A', 'D'],
        ['B', 'D', 'E', 'B', 'B']]], dtype='<U5')