# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [2]:
import numpy as np

#### 2. Print your NumPy version.

In [3]:
print(np.__version__)

1.21.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [4]:
a = np.random.random((2,3,5))
print(a)

[[[0.76871696 0.95117362 0.85369766 0.68890371 0.03418881]
  [0.28470005 0.02891409 0.39697087 0.57792366 0.7144177 ]
  [0.57333044 0.80034927 0.39254611 0.60313499 0.44050539]]

 [[0.80417132 0.93401808 0.783584   0.4602797  0.21306761]
  [0.15027641 0.64861718 0.69495405 0.7198217  0.43489992]
  [0.42749711 0.31010971 0.0414107  0.7724225  0.31463509]]]


In [5]:
b = np.arange(30).reshape(2,3,5)
b

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [6]:
c = np.zeros((2,3,5))
c

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

#### 4. Print *a*.


In [7]:
print(a)

[[[0.76871696 0.95117362 0.85369766 0.68890371 0.03418881]
  [0.28470005 0.02891409 0.39697087 0.57792366 0.7144177 ]
  [0.57333044 0.80034927 0.39254611 0.60313499 0.44050539]]

 [[0.80417132 0.93401808 0.783584   0.4602797  0.21306761]
  [0.15027641 0.64861718 0.69495405 0.7198217  0.43489992]
  [0.42749711 0.31010971 0.0414107  0.7724225  0.31463509]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [8]:
b = np.ones((5,2,3))

#### 6. Print *b*.


In [9]:
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [10]:
a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [11]:
c = a + b

#No you cannot because they are different shapes

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [12]:
c = b.reshape(2,3,5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [13]:
d = a + c
d

#Because now they are the same shape so the values can be summed from each specific index to the other 

array([[[1.76871696, 1.95117362, 1.85369766, 1.68890371, 1.03418881],
        [1.28470005, 1.02891409, 1.39697087, 1.57792366, 1.7144177 ],
        [1.57333044, 1.80034927, 1.39254611, 1.60313499, 1.44050539]],

       [[1.80417132, 1.93401808, 1.783584  , 1.4602797 , 1.21306761],
        [1.15027641, 1.64861718, 1.69495405, 1.7198217 , 1.43489992],
        [1.42749711, 1.31010971, 1.0414107 , 1.7724225 , 1.31463509]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [14]:
print(a)
print(d)

#Because d is a sum of both a nd c

[[[0.76871696 0.95117362 0.85369766 0.68890371 0.03418881]
  [0.28470005 0.02891409 0.39697087 0.57792366 0.7144177 ]
  [0.57333044 0.80034927 0.39254611 0.60313499 0.44050539]]

 [[0.80417132 0.93401808 0.783584   0.4602797  0.21306761]
  [0.15027641 0.64861718 0.69495405 0.7198217  0.43489992]
  [0.42749711 0.31010971 0.0414107  0.7724225  0.31463509]]]
[[[1.76871696 1.95117362 1.85369766 1.68890371 1.03418881]
  [1.28470005 1.02891409 1.39697087 1.57792366 1.7144177 ]
  [1.57333044 1.80034927 1.39254611 1.60313499 1.44050539]]

 [[1.80417132 1.93401808 1.783584   1.4602797  1.21306761]
  [1.15027641 1.64861718 1.69495405 1.7198217  1.43489992]
  [1.42749711 1.31010971 1.0414107  1.7724225  1.31463509]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [15]:
e = a*c
e

array([[[0.76871696, 0.95117362, 0.85369766, 0.68890371, 0.03418881],
        [0.28470005, 0.02891409, 0.39697087, 0.57792366, 0.7144177 ],
        [0.57333044, 0.80034927, 0.39254611, 0.60313499, 0.44050539]],

       [[0.80417132, 0.93401808, 0.783584  , 0.4602797 , 0.21306761],
        [0.15027641, 0.64861718, 0.69495405, 0.7198217 , 0.43489992],
        [0.42749711, 0.31010971, 0.0414107 , 0.7724225 , 0.31463509]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [16]:
e == a
#Yes because c was just the value 1 so a didnt change

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [17]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(d_max, d_min, d_mean)

1.9511736164445157 1.0289140900164269 1.527307946136587


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [38]:
f = np.empty((2,3,5))

In [42]:
f

array([[[25.        , 25.        , 25.        , 25.        ,
         25.        ],
        [25.        , 25.        , 25.        , 25.        ,
         25.        ],
        [25.        , 25.        , 25.        , 25.        ,
         25.        ]],

       [[ 0.80417132,  0.93401808,  0.783584  ,  0.4602797 ,
          0.21306761],
        [ 0.15027641,  0.64861718,  0.69495405,  0.7198217 ,
          0.43489992],
        [ 0.42749711,  0.31010971,  0.0414107 ,  0.7724225 ,
          0.31463509]]])

In [44]:
f[0] = 

array([[0.80417132, 0.93401808, 0.783584  , 0.4602797 , 0.21306761],
       [0.15027641, 0.64861718, 0.69495405, 0.7198217 , 0.43489992],
       [0.42749711, 0.31010971, 0.0414107 , 0.7724225 , 0.31463509]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [54]:
for i in range(d.shape[0]):
    for subarray in range(d.shape[1]):
        for el in range(d.shape[2]):
            if (el > d_min) and (el < d_mean):
                print(f)
                f=25
            elif (el > d_mean) and (el < d_max):
                f=75
            elif el == d_mean:
                 f=50
            elif el == d_min:
                 f=0
            elif el == d_max:
                 f=100

array([[[25.        , 25.        , 25.        , 25.        ,
         25.        ],
        [25.        , 25.        , 25.        , 25.        ,
         25.        ],
        [25.        , 25.        , 25.        , 25.        ,
         25.        ]],

       [[ 0.80417132,  0.93401808,  0.783584  ,  0.4602797 ,
          0.21306761],
        [ 0.15027641,  0.64861718,  0.69495405,  0.7198217 ,
          0.43489992],
        [ 0.42749711,  0.31010971,  0.0414107 ,  0.7724225 ,
          0.31463509]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [55]:
f.shape

(2, 3, 5)

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here