# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [5]:
import numpy as np

#### 2. Print your NumPy version.

In [11]:
version=(np.version.full_version)
print(version)

1.18.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [23]:
a1=np.random.randint(0,10,(2,3,5))
print(a1)
#random1.shape   Just to confirm size of array

[[[1 5 3 6 0]
  [0 6 4 2 5]
  [2 6 3 8 9]]

 [[9 4 6 7 5]
  [8 5 4 1 2]
  [5 5 4 3 0]]]


In [24]:
a2=np.random.random_sample((2,3,5))
print(a2)

[[[0.67440859 0.74700771 0.95252595 0.38067559 0.46250386]
  [0.63692971 0.60698347 0.66414362 0.546691   0.96149726]
  [0.34470589 0.36839297 0.96529132 0.6990608  0.39070748]]

 [[0.82344878 0.60008979 0.65025927 0.77981089 0.6061534 ]
  [0.17477463 0.47968541 0.66948582 0.75431781 0.64696164]
  [0.34122346 0.31185962 0.19350572 0.61228023 0.42287943]]]


In [25]:
a3=np.random.randn(2,3,5)
print(a3)

[[[-0.39426959 -0.7430547  -0.74486398  0.2146897  -0.38725388]
  [-2.68673751 -0.30574227  2.00110512  0.47824955  0.47454347]
  [ 0.93792597  0.54889427 -0.43255654 -2.69411428  1.74261203]]

 [[-0.21035021  0.72755833  0.52946138  1.31150148 -0.62946888]
  [ 0.89052543  0.09708348 -0.22734488  0.39204699 -0.61825841]
  [ 1.04552259 -0.1345551   0.63855989  0.21042289 -0.31589855]]]


#### 4. Print *a*.


In [26]:
a=a1
print(a)

[[[1 5 3 6 0]
  [0 6 4 2 5]
  [2 6 3 8 9]]

 [[9 4 6 7 5]
  [8 5 4 1 2]
  [5 5 4 3 0]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [52]:
b=np.random.randint(1,2,(5,2,3))
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 6. Print *b*.


In [53]:
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [54]:
print(a.shape)
print(b.shape)
print(a.shape==b.shape)

(2, 3, 5)
(5, 2, 3)
False


#### 8. Are you able to add *a* and *b*? Why or why not?


In [55]:
a_soma_b=a+b #NO! Because they are not the same size

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [72]:
c=np.transpose(b,) #Didn't work

#c=b.reshape(2,3,5)

print(c.shape)

(2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [148]:
d=a+c #yes they are now the same size

print(d)
print(a.shape)
print(c.shape)

[[[ 2  6  4  7  1]
  [ 1  7  5  3  6]
  [ 3  7  4  9 10]]

 [[10  5  7  8  6]
  [ 9  6  5  2  3]
  [ 6  6  5  4  1]]]
(2, 3, 5)
(2, 3, 5)


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [149]:
print(a)
print(d)

#d is equal to array a adding the value 1

[[[1 5 3 6 0]
  [0 6 4 2 5]
  [2 6 3 8 9]]

 [[9 4 6 7 5]
  [8 5 4 1 2]
  [5 5 4 3 0]]]
[[[ 2  6  4  7  1]
  [ 1  7  5  3  6]
  [ 3  7  4  9 10]]

 [[10  5  7  8  6]
  [ 9  6  5  2  3]
  [ 6  6  5  4  1]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [150]:
e=a*c
print(e)

[[[1 5 3 6 0]
  [0 6 4 2 5]
  [2 6 3 8 9]]

 [[9 4 6 7 5]
  [8 5 4 1 2]
  [5 5 4 3 0]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [151]:
print(e==a)

#Yes, e equals to a. Because e=a*c and c is an array of values 1

[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [152]:
d_max=np.max(d)
d_min=np.min(d)
d_mean=np.mean(d)

print(d)
print(d_max)
print(d_min)
print(d_mean)

[[[ 2  6  4  7  1]
  [ 1  7  5  3  6]
  [ 3  7  4  9 10]]

 [[10  5  7  8  6]
  [ 9  6  5  2  3]
  [ 6  6  5  4  1]]]
10
1
5.266666666666667


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [153]:
f=np.empty([2,3,5])
print(f)

[[[1.85836099 1.67064465 1.62576044 1.40243961 1.88454931]
  [1.75354326 1.69403643 1.36729252 1.61415071 1.12104981]
  [1.72201435 1.1862918  1.87078449 1.7726778  1.88180042]]

 [[1.44747908 1.31673383 1.02000951 1.52218947 1.97066381]
  [1.79129243 1.74983003 1.96028037 1.85166831 1.65450881]
  [1.18068344 1.9587381  1.00656599 1.93402165 1.73514584]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [154]:
def populate_f(my_array):
    
    d_max=np.max(my_array)
    d_min=np.min(my_array)
    d_mean=np.mean(my_array)
    
    f_temp1=np.array([(d>d_min)&(d<d_mean)])*25
    f_temp2=np.array([(d<d_max)&(d>d_mean)])*75
    f_temp3=np.array([(d==d_mean)])*50
    f_temp4=np.array([(d==d_min)])*0
    f_temp5=np.array([(d==d_max)])*100

    f=f_temp1+f_temp2+f_temp3+f_temp4+f_temp5
    
    print(f)
    return f

populate_f(d)

[[[[ 25  75  25  75   0]
   [  0  75  25  25  75]
   [ 25  75  25  75 100]]

  [[100  25  75  75  75]
   [ 75  75  25  25  25]
   [ 75  75  25  25   0]]]]


array([[[[ 25,  75,  25,  75,   0],
         [  0,  75,  25,  25,  75],
         [ 25,  75,  25,  75, 100]],

        [[100,  25,  75,  75,  75],
         [ 75,  75,  25,  25,  25],
         [ 75,  75,  25,  25,   0]]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [155]:
d=[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]

populate_f(d)

[[[[ 75  75  75  25  75]
   [ 75  75  25  25  25]
   [ 75  25  75  75  75]]

  [[ 25  25  25  25 100]
   [ 75  75  75  75  75]
   [ 25  75   0  75  75]]]]


array([[[[ 75,  75,  75,  25,  75],
         [ 75,  75,  25,  25,  25],
         [ 75,  25,  75,  75,  75]],

        [[ 25,  25,  25,  25, 100],
         [ 75,  75,  75,  75,  75],
         [ 25,  75,   0,  75,  75]]]])

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.