# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np
import random

#### 2. Print your NumPy version.

In [2]:
# your code here

np.version.version

'1.20.1'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a=np.random.random(size = (2,3,5))

print(a)

[[[0.64402145 0.35347817 0.58777267 0.31364236 0.85046791]
  [0.6965113  0.77839511 0.05927197 0.42253468 0.50392326]
  [0.32341327 0.85987689 0.00298627 0.61632719 0.19325709]]

 [[0.89297134 0.32963423 0.55049823 0.43060547 0.08419103]
  [0.43244928 0.93469705 0.24306709 0.55202818 0.9966241 ]
  [0.2106286  0.83146949 0.90017151 0.18785911 0.38195324]]]


In [4]:
# Method 2
a=np.empty((2,3,5))

print(a)

[[[0.64402145 0.35347817 0.58777267 0.31364236 0.85046791]
  [0.6965113  0.77839511 0.05927197 0.42253468 0.50392326]
  [0.32341327 0.85987689 0.00298627 0.61632719 0.19325709]]

 [[0.89297134 0.32963423 0.55049823 0.43060547 0.08419103]
  [0.43244928 0.93469705 0.24306709 0.55202818 0.9966241 ]
  [0.2106286  0.83146949 0.90017151 0.18785911 0.38195324]]]


In [5]:
# Method 3
a=np.random.rand(2,3,5)

print(a)

[[[0.43869801 0.55680016 0.05660745 0.33756355 0.18830153]
  [0.83776361 0.57405662 0.65263365 0.35270112 0.08473826]
  [0.36729363 0.73533685 0.07938781 0.40243582 0.14454966]]

 [[0.9229689  0.8179589  0.96554897 0.59934543 0.01335697]
  [0.46443651 0.48047708 0.45638387 0.7609358  0.61439943]
  [0.89061265 0.88984993 0.40908741 0.7380981  0.36401429]]]


#### 4. Print *a*.


In [6]:
# your code here
print(a)

[[[0.43869801 0.55680016 0.05660745 0.33756355 0.18830153]
  [0.83776361 0.57405662 0.65263365 0.35270112 0.08473826]
  [0.36729363 0.73533685 0.07938781 0.40243582 0.14454966]]

 [[0.9229689  0.8179589  0.96554897 0.59934543 0.01335697]
  [0.46443651 0.48047708 0.45638387 0.7609358  0.61439943]
  [0.89061265 0.88984993 0.40908741 0.7380981  0.36401429]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here

b=np.ones((5,2,3))

#### 6. Print *b*.


In [8]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here

if a.size == b.size:
    print("They are the same size")
else:
    ('They don´t have the same size')

They are the same size


#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here
print('Besides that they have the same size, they don´t have the same shape so it´s not possible to add')

Besides that they have the same size, they don´t have the same shape so it´s not possible to add


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here
c=b.reshape(2,3,5)
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# your code/answer here
d= a+c

print(d)

[[[1.43869801 1.55680016 1.05660745 1.33756355 1.18830153]
  [1.83776361 1.57405662 1.65263365 1.35270112 1.08473826]
  [1.36729363 1.73533685 1.07938781 1.40243582 1.14454966]]

 [[1.9229689  1.8179589  1.96554897 1.59934543 1.01335697]
  [1.46443651 1.48047708 1.45638387 1.7609358  1.61439943]
  [1.89061265 1.88984993 1.40908741 1.7380981  1.36401429]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# your code/answer here

print(a,'\n')
print(d,'\n')

print("It sum the two values of each arrow")

[[[0.43869801 0.55680016 0.05660745 0.33756355 0.18830153]
  [0.83776361 0.57405662 0.65263365 0.35270112 0.08473826]
  [0.36729363 0.73533685 0.07938781 0.40243582 0.14454966]]

 [[0.9229689  0.8179589  0.96554897 0.59934543 0.01335697]
  [0.46443651 0.48047708 0.45638387 0.7609358  0.61439943]
  [0.89061265 0.88984993 0.40908741 0.7380981  0.36401429]]] 

[[[1.43869801 1.55680016 1.05660745 1.33756355 1.18830153]
  [1.83776361 1.57405662 1.65263365 1.35270112 1.08473826]
  [1.36729363 1.73533685 1.07938781 1.40243582 1.14454966]]

 [[1.9229689  1.8179589  1.96554897 1.59934543 1.01335697]
  [1.46443651 1.48047708 1.45638387 1.7609358  1.61439943]
  [1.89061265 1.88984993 1.40908741 1.7380981  1.36401429]]] 

It sum the two values of each arrow


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
# your code here

e = a*c

print(e)

[[[0.43869801 0.55680016 0.05660745 0.33756355 0.18830153]
  [0.83776361 0.57405662 0.65263365 0.35270112 0.08473826]
  [0.36729363 0.73533685 0.07938781 0.40243582 0.14454966]]

 [[0.9229689  0.8179589  0.96554897 0.59934543 0.01335697]
  [0.46443651 0.48047708 0.45638387 0.7609358  0.61439943]
  [0.89061265 0.88984993 0.40908741 0.7380981  0.36401429]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
# your code/answer here

print('Because you are doing a multiplication by 1 ;)')

Because you are doing a multiplication by 1 ;)


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
# your code here
d_max= d.max()
d_min=d.min()
d_mean= d.mean()
print('d_max=',d_max,'\n','d_min=',d_min,'\n','d_mean',d_mean)

d_max= 1.9655489710935157 
 d_min= 1.0133569715470747 
 d_mean 1.5065447329519925


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [17]:
# your code here
f= np.empty([2,3,5])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [24]:
# your code here

f[(d_mean > d) & (d_min < d)] = 25
f[(d_mean <d) & (d_max >d)]=75
f[d == d_mean]=50
f[d == d_min] = 0
f[d == d_max] = 100
print(f)

[[[ 25.  75.  25.  25.  25.]
  [ 75.  75.  75.  25.  25.]
  [ 25.  75.  25.  25.  25.]]

 [[ 75.  75. 100.  75.   0.]
  [ 25.  25.  25.  75.  75.]
  [ 75.  75.  25.  75.  25.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [19]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.