# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.version.version)

1.18.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [8]:
# Method 1
# random floats in the half-open interval [0.0, 1.0). Results are from the “continuous uniform” distribution over the stated interval. 
a = np.random.random(size=(2, 3, 5))


array([[[0.25273293, 0.61552322, 0.0710703 , 0.56083813, 0.48219053],
        [0.80013714, 0.87087519, 0.56725241, 0.98702592, 0.84714385],
        [0.76096116, 0.85732542, 0.64628543, 0.30544768, 0.29728131]],

       [[0.84609149, 0.42837361, 0.88546522, 0.37559273, 0.69192274],
        [0.20711017, 0.31426938, 0.31240055, 0.65793315, 0.35401347],
        [0.98208067, 0.82591876, 0.72772742, 0.87084133, 0.03338424]]])

In [5]:
# Method 2
# random floats in the half-open interval [0.0, 1.0). samples from a uniform distribution.
a = np.random.rand(2, 3, 5)


array([[[0.21888394, 0.94460449, 0.40613164, 0.40967394, 0.20034005],
        [0.99344188, 0.45311099, 0.62568063, 0.90936535, 0.29054306],
        [0.65015628, 0.74780947, 0.05659543, 0.13491811, 0.3677703 ]],

       [[0.08798167, 0.26943109, 0.99914223, 0.24246934, 0.39643453],
        [0.85737221, 0.78538814, 0.22873711, 0.91334867, 0.96208219],
        [0.95530305, 0.06249823, 0.25341496, 0.14592595, 0.90096865]]])

In [7]:
# Method 3
# random integers with low and high specified
a = np.random.randint(42, high=666, size=(2, 3, 5))


array([[[150, 664,  99, 567, 209],
        [251,  97, 382, 216,  94],
        [614, 314, 478, 551, 304]],

       [[354,  55, 542, 371, 473],
        [508, 562, 198, 122, 475],
        [360, 217, 355, 115, 268]]])

#### 4. Print *a*.


In [10]:
# your code here
print(a)

[[[0.25273293 0.61552322 0.0710703  0.56083813 0.48219053]
  [0.80013714 0.87087519 0.56725241 0.98702592 0.84714385]
  [0.76096116 0.85732542 0.64628543 0.30544768 0.29728131]]

 [[0.84609149 0.42837361 0.88546522 0.37559273 0.69192274]
  [0.20711017 0.31426938 0.31240055 0.65793315 0.35401347]
  [0.98208067 0.82591876 0.72772742 0.87084133 0.03338424]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [12]:
# your code here
b = np.ones((5, 2, 3))


array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 6. Print *b*.


In [13]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [17]:
# your code here
# we can use the size method and try equivalence
np.size(a) == np.size(b)

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [19]:
# your answer here
try:
    a + b
except ValueError:
    print("You cannot add a to b because they have different shapes. You'd have to convert them into the same shape.")

You cannot add a to b because they have different shapes. You'd have to convert them into the same shape.


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [22]:
# your code here
c = b.reshape(2, 3, 5)
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [23]:
# your code/answer here
d = a + c


array([[[1.25273293, 1.61552322, 1.0710703 , 1.56083813, 1.48219053],
        [1.80013714, 1.87087519, 1.56725241, 1.98702592, 1.84714385],
        [1.76096116, 1.85732542, 1.64628543, 1.30544768, 1.29728131]],

       [[1.84609149, 1.42837361, 1.88546522, 1.37559273, 1.69192274],
        [1.20711017, 1.31426938, 1.31240055, 1.65793315, 1.35401347],
        [1.98208067, 1.82591876, 1.72772742, 1.87084133, 1.03338424]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [25]:
# your code/answer here

# print a
print(a)

# print d
print(d)

# explanation
print("The values in d are each 1 greater than the values in a, because we added an array where all values are 1 to a")

[[[0.25273293 0.61552322 0.0710703  0.56083813 0.48219053]
  [0.80013714 0.87087519 0.56725241 0.98702592 0.84714385]
  [0.76096116 0.85732542 0.64628543 0.30544768 0.29728131]]

 [[0.84609149 0.42837361 0.88546522 0.37559273 0.69192274]
  [0.20711017 0.31426938 0.31240055 0.65793315 0.35401347]
  [0.98208067 0.82591876 0.72772742 0.87084133 0.03338424]]]
[[[1.25273293 1.61552322 1.0710703  1.56083813 1.48219053]
  [1.80013714 1.87087519 1.56725241 1.98702592 1.84714385]
  [1.76096116 1.85732542 1.64628543 1.30544768 1.29728131]]

 [[1.84609149 1.42837361 1.88546522 1.37559273 1.69192274]
  [1.20711017 1.31426938 1.31240055 1.65793315 1.35401347]
  [1.98208067 1.82591876 1.72772742 1.87084133 1.03338424]]]
The values in d are each 1 greater than the values in a, because we added an array where all values are 1 to a


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [26]:
# your code here
e = a * c
e

array([[[0.25273293, 0.61552322, 0.0710703 , 0.56083813, 0.48219053],
        [0.80013714, 0.87087519, 0.56725241, 0.98702592, 0.84714385],
        [0.76096116, 0.85732542, 0.64628543, 0.30544768, 0.29728131]],

       [[0.84609149, 0.42837361, 0.88546522, 0.37559273, 0.69192274],
        [0.20711017, 0.31426938, 0.31240055, 0.65793315, 0.35401347],
        [0.98208067, 0.82591876, 0.72772742, 0.87084133, 0.03338424]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [32]:
# your code/answer here
if np.array_equal(e, a):
    print("Yes, e and a are equal because we multiplied each value in a with 1.")

Yes, e and a are equal because we multiplied each value in a with 1.


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [37]:
# your code here
# max
d_max =  np.max(d)

# min
d_min =  np.min(d)

# mean
d_mean = np.mean(d)


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [39]:
# your code here
f = np.empty(shape=(2,3,5))


array([[[0.25273293, 0.61552322, 0.0710703 , 0.56083813, 0.48219053],
        [0.80013714, 0.87087519, 0.56725241, 0.98702592, 0.84714385],
        [0.76096116, 0.85732542, 0.64628543, 0.30544768, 0.29728131]],

       [[0.84609149, 0.42837361, 0.88546522, 0.37559273, 0.69192274],
        [0.20711017, 0.31426938, 0.31240055, 0.65793315, 0.35401347],
        [0.98208067, 0.82591876, 0.72772742, 0.87084133, 0.03338424]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [47]:
# your code here

# create masks for each group of conditions and use for assigning values

# First assignment
mask1 = np.logical_and(d > d_min, d < d_mean)
f[mask1] = 25

# Second assignment
mask2 = np.logical_and(d > d_mean, d < d_max)
f[mask2] = 75

# Third assignment
mask3 = (d == d_mean)
f[mask3] = 50

# Fourth assignment
mask4 = (d == d_min)
f[mask4] = 0

# Fifth assignment
mask4 = (d == d_max)
f[mask4] = 100

f

array([[[ 25.,  75.,  25.,  25.,  25.],
        [ 75.,  75.,  25., 100.,  75.],
        [ 75.,  75.,  75.,  25.,  25.]],

       [[ 75.,  25.,  75.,  25.,  75.],
        [ 25.,  25.,  25.,  75.,  25.],
        [ 75.,  75.,  75.,  75.,   0.]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [48]:
# your code here
print(d)
print(f)


[[[1.25273293 1.61552322 1.0710703  1.56083813 1.48219053]
  [1.80013714 1.87087519 1.56725241 1.98702592 1.84714385]
  [1.76096116 1.85732542 1.64628543 1.30544768 1.29728131]]

 [[1.84609149 1.42837361 1.88546522 1.37559273 1.69192274]
  [1.20711017 1.31426938 1.31240055 1.65793315 1.35401347]
  [1.98208067 1.82591876 1.72772742 1.87084133 1.03338424]]]
[[[ 25.  75.  25.  25.  25.]
  [ 75.  75.  25. 100.  75.]
  [ 75.  75.  75.  25.  25.]]

 [[ 75.  25.  75.  25.  75.]
  [ 25.  25.  25.  75.  25.]
  [ 75.  75.  75.  75.   0.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [53]:
# your code here

# create masks for each group of conditions and use for assigning values

# create empty array with dtype string
f = np.empty(shape=(2,3,5), dtype=np.str)

# First assignment
mask1 = np.logical_and(d > d_min, d < d_mean)
f[mask1] = "B"

# Second assignment
mask2 = np.logical_and(d > d_mean, d < d_max)
f[mask2] = "D"

# Third assignment
mask3 = (d == d_mean)
f[mask3] = "C"

# Fourth assignment
mask4 = (d == d_min)
f[mask4] = "A"

# Fifth assignment
mask4 = (d == d_max)
f[mask4] = "E"

print(f)

[[['B' 'D' 'B' 'B' 'B']
  ['D' 'D' 'B' 'E' 'D']
  ['D' 'D' 'D' 'B' 'B']]

 [['D' 'B' 'D' 'B' 'D']
  ['B' 'B' 'B' 'D' 'B']
  ['D' 'D' 'D' 'D' 'A']]]
