# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [2]:
np.version.version

'1.16.4'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
a = np.random.random((2,3,5))

In [4]:
# Method 2

In [5]:
# Method 3

#### 4. Print *a*.


In [6]:
print(a)

[[[0.30341259 0.28985886 0.80115618 0.41382576 0.52622596]
  [0.49097892 0.33432328 0.19081999 0.67007989 0.48265008]
  [0.99110392 0.29490496 0.38588964 0.46792302 0.63041102]]

 [[0.04115354 0.6701774  0.85042478 0.38353584 0.23507322]
  [0.00418648 0.74165423 0.72795803 0.3251954  0.30127651]
  [0.02558559 0.73159298 0.35892732 0.93269844 0.50458098]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
b = np.ones((5,2,3))

#### 6. Print *b*.


In [8]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
np.sum(a) == np.sum(b)

False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
#a + b
# no, because it does not have the same shape

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
c = (np.reshape(b, (2, 3, 5)))
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
d = a + c

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
a + d

#because a is random

array([[[1.60682518, 1.57971772, 2.60231235, 1.82765153, 2.05245192],
        [1.98195783, 1.66864657, 1.38163998, 2.34015977, 1.96530016],
        [2.98220785, 1.58980992, 1.77177929, 1.93584604, 2.26082204]],

       [[1.08230708, 2.3403548 , 2.70084956, 1.76707168, 1.47014644],
        [1.00837296, 2.48330846, 2.45591605, 1.6503908 , 1.60255301],
        [1.05117117, 2.46318596, 1.71785465, 2.86539688, 2.00916196]]])

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
e = a * c

#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
e == a
#because c is multiplying all values by 1, creating the same value.

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
d_max = (np.amax(d))
d_min = (np.amin(d))
d_mean= (np.mean(d))

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [17]:
f = np.empty((2,3,5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [22]:
f[(d > d_min) & (d < d_mean)] = 25
f[(d > d_mean) & (d < d_max)] = 75
f[(d == d_min)] = 0
f[(d == d_max)] = 100

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [23]:
print(d)
print(f)

[[[1.30341259 1.28985886 1.80115618 1.41382576 1.52622596]
  [1.49097892 1.33432328 1.19081999 1.67007989 1.48265008]
  [1.99110392 1.29490496 1.38588964 1.46792302 1.63041102]]

 [[1.04115354 1.6701774  1.85042478 1.38353584 1.23507322]
  [1.00418648 1.74165423 1.72795803 1.3251954  1.30127651]
  [1.02558559 1.73159298 1.35892732 1.93269844 1.50458098]]]
[[[ 25.  25.  75.  25.  75.]
  [ 75.  25.  25.  75.  75.]
  [100.  25.  25.  25.  75.]]

 [[ 25.  75.  75.  25.  25.]
  [  0.  75.  75.  25.  25.]
  [ 25.  75.  25.  75.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

SyntaxError: invalid syntax (<ipython-input-50-a9e11fece2b8>, line 8)