# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [93]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [94]:
# your code here
print(np.__version__)

1.18.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [95]:
# Method 1
a = np.random.random((2,3,5))
print(a)
print(np.shape(a))

[[[0.09954731 0.50464153 0.92209444 0.99733445 0.76630192]
  [0.20360294 0.46259768 0.56746744 0.99985076 0.41571937]
  [0.5340406  0.64881041 0.8913457  0.29623008 0.26627407]]

 [[0.73335881 0.27648327 0.57251958 0.74617908 0.65687257]
  [0.92943888 0.4176199  0.65225711 0.34323913 0.43187819]
  [0.15191185 0.59528714 0.32687549 0.45181202 0.88233529]]]
(2, 3, 5)


In [96]:
# Method 2


In [97]:
# Method 3

#### 4. Print *a*.


In [98]:
# your code here
print(a)

[[[0.09954731 0.50464153 0.92209444 0.99733445 0.76630192]
  [0.20360294 0.46259768 0.56746744 0.99985076 0.41571937]
  [0.5340406  0.64881041 0.8913457  0.29623008 0.26627407]]

 [[0.73335881 0.27648327 0.57251958 0.74617908 0.65687257]
  [0.92943888 0.4176199  0.65225711 0.34323913 0.43187819]
  [0.15191185 0.59528714 0.32687549 0.45181202 0.88233529]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [99]:
# your code here

b=np.ones(((5,2,3)))


#### 6. Print *b*.


In [100]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [101]:
# your code here

sizea=np.size(a)
sizeb=np.size(b)

if sizea==sizeb:
    print("Same size")
else:
    print("Different size")

Same size


#### 8. Are you able to add *a* and *b*? Why or why not?


In [102]:
# your answer here

d=a+b
print(d)

print("As they are different shapes, the addition between them is impossible")

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [103]:
# your code here
c=np.transpose(b, (1, 2, 0))
print(c)
print(np.shape(c))

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
(2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [104]:
# your code/answer here
d=a+c
print(d)
print("It works because there are the same shape")

[[[1.09954731 1.50464153 1.92209444 1.99733445 1.76630192]
  [1.20360294 1.46259768 1.56746744 1.99985076 1.41571937]
  [1.5340406  1.64881041 1.8913457  1.29623008 1.26627407]]

 [[1.73335881 1.27648327 1.57251958 1.74617908 1.65687257]
  [1.92943888 1.4176199  1.65225711 1.34323913 1.43187819]
  [1.15191185 1.59528714 1.32687549 1.45181202 1.88233529]]]
It works because there are the same shape


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [105]:
# your code/answer here
print(a)
print(d)

print("c is a matrix of ones, so the matrix d is the matrix a adding 1 to every single element of the matrix")


[[[0.09954731 0.50464153 0.92209444 0.99733445 0.76630192]
  [0.20360294 0.46259768 0.56746744 0.99985076 0.41571937]
  [0.5340406  0.64881041 0.8913457  0.29623008 0.26627407]]

 [[0.73335881 0.27648327 0.57251958 0.74617908 0.65687257]
  [0.92943888 0.4176199  0.65225711 0.34323913 0.43187819]
  [0.15191185 0.59528714 0.32687549 0.45181202 0.88233529]]]
[[[1.09954731 1.50464153 1.92209444 1.99733445 1.76630192]
  [1.20360294 1.46259768 1.56746744 1.99985076 1.41571937]
  [1.5340406  1.64881041 1.8913457  1.29623008 1.26627407]]

 [[1.73335881 1.27648327 1.57251958 1.74617908 1.65687257]
  [1.92943888 1.4176199  1.65225711 1.34323913 1.43187819]
  [1.15191185 1.59528714 1.32687549 1.45181202 1.88233529]]]
c is a matrix of ones, so the matrix d is the matrix a adding 1 to every single element of the matrix


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [106]:
# your code here
e=a*c
print(e)

[[[0.09954731 0.50464153 0.92209444 0.99733445 0.76630192]
  [0.20360294 0.46259768 0.56746744 0.99985076 0.41571937]
  [0.5340406  0.64881041 0.8913457  0.29623008 0.26627407]]

 [[0.73335881 0.27648327 0.57251958 0.74617908 0.65687257]
  [0.92943888 0.4176199  0.65225711 0.34323913 0.43187819]
  [0.15191185 0.59528714 0.32687549 0.45181202 0.88233529]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [107]:
# your code/answer here
print("Yes, multiplicating any number by one we get the same number")

Yes, multiplicating any number by one we get the same number


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [108]:
# your code here
d_max=np.max(d)
d_min=np.min(d)
d_mean=np.mean(d)

print(d_max, d_min, d_mean)

1.9998507637262803 1.0995473122431976 1.5581309006474884


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [109]:
# your code here
f=np.empty((2,3,5))
print(f)

[[[0.09954731 0.50464153 0.92209444 0.99733445 0.76630192]
  [0.20360294 0.46259768 0.56746744 0.99985076 0.41571937]
  [0.5340406  0.64881041 0.8913457  0.29623008 0.26627407]]

 [[0.73335881 0.27648327 0.57251958 0.74617908 0.65687257]
  [0.92943888 0.4176199  0.65225711 0.34323913 0.43187819]
  [0.15191185 0.59528714 0.32687549 0.45181202 0.88233529]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [110]:
# your code here
print(d)

listaf=[]

for bmat in d:
    for matrix in bmat:
        for value in matrix:
            if value == d_min:
                listaf.append(0)
            elif value == d_mean:
                listaf.append(50)
            elif value== d_max:
                listaf.append(100)
            elif (value > d_min) and (value < d_mean):
                listaf.append(25)
            else:
                listaf.append(75)
                
f  = np.array(listaf).reshape(2,3,5)

print(f)

[[[1.09954731 1.50464153 1.92209444 1.99733445 1.76630192]
  [1.20360294 1.46259768 1.56746744 1.99985076 1.41571937]
  [1.5340406  1.64881041 1.8913457  1.29623008 1.26627407]]

 [[1.73335881 1.27648327 1.57251958 1.74617908 1.65687257]
  [1.92943888 1.4176199  1.65225711 1.34323913 1.43187819]
  [1.15191185 1.59528714 1.32687549 1.45181202 1.88233529]]]
[[[  0  25  75  75  75]
  [ 25  25  75 100  25]
  [ 25  75  75  25  25]]

 [[ 75  25  75  75  75]
  [ 75  25  75  25  25]
  [ 25  75  25  25  75]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [64]:
# your code here



#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [65]:
# your code here