# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [3]:
# your code here
np.version.version

'1.18.1'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [7]:
# Method 1
a = np.random.rand(2,3,5)
a

array([[[0.91514029, 0.26422136, 0.00808478, 0.10127546, 0.09511469],
        [0.18982882, 0.1697282 , 0.07040081, 0.2095277 , 0.8732175 ],
        [0.5360284 , 0.55259612, 0.74863578, 0.89845349, 0.16362588]],

       [[0.68443628, 0.70050814, 0.62703913, 0.9196405 , 0.065126  ],
        [0.57716317, 0.35902573, 0.15571174, 0.12469575, 0.48756558],
        [0.11883183, 0.56165792, 0.12993002, 0.47037233, 0.33651996]]])

In [31]:
# Method 2
a = np.random.randn(2,3,5)
a

array([[[ 0.44708676, -0.3419347 , -1.19229976,  0.36954353,
          0.54377505],
        [-1.17865045, -0.79418122, -1.88345288, -1.71355827,
         -0.21389048],
        [-0.41435784,  0.55061211, -1.12984151, -0.48925606,
          0.71085272]],

       [[-0.00878284,  0.79515765,  0.74493955,  0.13871432,
         -0.59682344],
        [-0.69678064,  0.58089646,  1.00326688,  0.66891891,
         -0.58970663],
        [-0.55780637, -2.42350613, -0.39464536, -0.33683366,
         -0.51548709]]])

In [32]:
# Method 3
a = np.random.randint(100,size=(2,3,5))
a

array([[[33, 13, 98, 71, 99],
        [60, 23, 62, 56, 19],
        [48, 85, 21, 37, 52]],

       [[66, 92, 75, 92, 15],
        [26, 98, 43, 56, 95],
        [75, 78, 18, 53, 76]]])

#### 4. Print *a*.


In [33]:
# your code here
a

array([[[33, 13, 98, 71, 99],
        [60, 23, 62, 56, 19],
        [48, 85, 21, 37, 52]],

       [[66, 92, 75, 92, 15],
        [26, 98, 43, 56, 95],
        [75, 78, 18, 53, 76]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [34]:
# your code here
b = np.ones((5,2,3))
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 6. Print *b*.


In [35]:
# your code here
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [36]:
# your code here
a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [37]:
# your answer here
# Can not. Arrays have different shapes
a.shape == b.shape

False

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [50]:
# your code here
c = np.reshape(b,(2,3,5))
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [52]:
# your code/answer here
# a and c have the same shape
d = a+c 
d

array([[[ 34.,  14.,  99.,  72., 100.],
        [ 61.,  24.,  63.,  57.,  20.],
        [ 49.,  86.,  22.,  38.,  53.]],

       [[ 67.,  93.,  76.,  93.,  16.],
        [ 27.,  99.,  44.,  57.,  96.],
        [ 76.,  79.,  19.,  54.,  77.]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [55]:
# your code/answer here
print(a)
print(d)
# d = a + c all values of a were sum to values of c

[[[33 13 98 71 99]
  [60 23 62 56 19]
  [48 85 21 37 52]]

 [[66 92 75 92 15]
  [26 98 43 56 95]
  [75 78 18 53 76]]]
[[[ 34.  14.  99.  72. 100.]
  [ 61.  24.  63.  57.  20.]
  [ 49.  86.  22.  38.  53.]]

 [[ 67.  93.  76.  93.  16.]
  [ 27.  99.  44.  57.  96.]
  [ 76.  79.  19.  54.  77.]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [57]:
# your code here
e = a*c
e

array([[[33., 13., 98., 71., 99.],
        [60., 23., 62., 56., 19.],
        [48., 85., 21., 37., 52.]],

       [[66., 92., 75., 92., 15.],
        [26., 98., 43., 56., 95.],
        [75., 78., 18., 53., 76.]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [59]:
# your code/answer here
e==a
# Yes because c has only 1s

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [61]:
# your code here
d_max = d.max()
print(d_max)
d_min = d.min()
print(d_min)
d_mean = d.mean()
print(d_mean)

100.0
14.0
58.833333333333336


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [76]:
# your code here
f = np.empty((2,3,5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [77]:
# your code here


1
1


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here