# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [339]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [318]:
# your code here
print(np.__version__)

1.21.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [319]:
# Method 1
a = np.random.random((2,3,5))
print(a)

[[[0.95631584 0.41141796 0.38880668 0.37988925 0.49437349]
  [0.37461065 0.45949193 0.33533647 0.87096876 0.70867683]
  [0.12239341 0.59354259 0.86123391 0.16841005 0.39688409]]

 [[0.79676545 0.25978891 0.53047298 0.86352398 0.44918973]
  [0.15581548 0.55711616 0.07735143 0.72414889 0.37969157]
  [0.22150798 0.46880091 0.76339816 0.64187858 0.8128744 ]]]


In [320]:
# Method 2
lst_lst = [[1,2,3,4,5],[4,5,6,5,1],[7,8,9,5,3]]
d = np.array(lst_lst)
print(d)

[[1 2 3 4 5]
 [4 5 6 5 1]
 [7 8 9 5 3]]


In [321]:
# Method 3

#### 4. Print *a*.


In [322]:
print(a)

[[[0.95631584 0.41141796 0.38880668 0.37988925 0.49437349]
  [0.37461065 0.45949193 0.33533647 0.87096876 0.70867683]
  [0.12239341 0.59354259 0.86123391 0.16841005 0.39688409]]

 [[0.79676545 0.25978891 0.53047298 0.86352398 0.44918973]
  [0.15581548 0.55711616 0.07735143 0.72414889 0.37969157]
  [0.22150798 0.46880091 0.76339816 0.64187858 0.8128744 ]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [323]:
# your code here

b = np.ones((5,2,3))
#b.shape

#### 6. Print *b*.


In [324]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [325]:
# your code here
print(np.array_equal(a,b))
print("a:",a.shape) 
print("b:",b.shape) 

False
a: (2, 3, 5)
b: (5, 2, 3)


#### 8. Are you able to add *a* and *b*? Why or why not?


In [326]:
# your answer here
np.add(a,b)
#The number os 2D Arrays declared in both must have the same shape

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [327]:
# your code here
#b 5x2x3
#  0 1 2 
c = np.transpose(b,(1,2,0))
print(c.shape)

(2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [328]:
# your code/answer here
print("A:",a.shape)
print("C:",c.shape)
d = np.add(a,c)
print("D:",d.shape)
#print(d)
#The number os 2D Arrays declared in both must have the same shape

A: (2, 3, 5)
C: (2, 3, 5)
D: (2, 3, 5)


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [329]:
# your code/answer here
print("A:",a)
print("-- ")
print("D:",d)
#It sum's de content of array A with the B's 'ones' array.

A: [[[0.95631584 0.41141796 0.38880668 0.37988925 0.49437349]
  [0.37461065 0.45949193 0.33533647 0.87096876 0.70867683]
  [0.12239341 0.59354259 0.86123391 0.16841005 0.39688409]]

 [[0.79676545 0.25978891 0.53047298 0.86352398 0.44918973]
  [0.15581548 0.55711616 0.07735143 0.72414889 0.37969157]
  [0.22150798 0.46880091 0.76339816 0.64187858 0.8128744 ]]]
-- 
D: [[[1.95631584 1.41141796 1.38880668 1.37988925 1.49437349]
  [1.37461065 1.45949193 1.33533647 1.87096876 1.70867683]
  [1.12239341 1.59354259 1.86123391 1.16841005 1.39688409]]

 [[1.79676545 1.25978891 1.53047298 1.86352398 1.44918973]
  [1.15581548 1.55711616 1.07735143 1.72414889 1.37969157]
  [1.22150798 1.46880091 1.76339816 1.64187858 1.8128744 ]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [330]:
# your code here
e = a * c

#### 13. Does *e* equal to *a*? Why or why not?


In [331]:
# your code/answer here
print(np.array_equal(a,e))

# It is because It multiplied the content of A with the content of B wich are only 'ones'

True


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [332]:
# your code here
#print(d)
d_max = np.amax(d)
d_min = np.amin(d)
d_mean = np.mean(d)
print("Max:",d_max)
print("Min:",d_min)
print("Mean:",d_mean)



Max: 1.956315842580949
Min: 1.0773514327283324
Mean: 1.5074892172936971


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [333]:
# your code here

shape = (2,3,5)
f = np.zeros(shape) 
f

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [334]:
# your code here
print("Mean:",d_mean)
print("MIN:",d_min)

#z = np.empty(shape) * 0

for b in range(0,2):
    for l in range(0,3):
        for r in range(0,5):
            if d[b][l][r] > d_min and d[b][l][r] < d_mean:
                f[b][l][r]=25
                
            elif d[b][l][r] > d_mean and d[b][l][r] < d_max:
                f[b][l][r]=75
                
            elif d[b][l][r] == d_mean:
                f[b][l][r]=50
                
            elif d[b][l][r] == d_min:
                f[b][l][r]=0
                
            elif d[b][l][r] == d_max:
                f[b][l][r]=100 


Mean: 1.5074892172936971
MIN: 1.0773514327283324


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [335]:
print(f)

[[[100.  25.  25.  25.  25.]
  [ 25.  25.  25.  75.  75.]
  [ 25.  75.  75.  25.  25.]]

 [[ 75.  25.  75.  75.  25.]
  [ 25.  75.   0.  75.  25.]
  [ 25.  25.  75.  75.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [336]:
# your code here

In [337]:
lst_lst = [1,2,3,4,5],[4,5,6,5,1],[7,8,'A',8,3],[7,10,9,5,3],[7,10,9,5,3],[7,10,9,5,3]
ar = np.array(lst_lst)
print(ar)

[['1' '2' '3' '4' '5']
 ['4' '5' '6' '5' '1']
 ['7' '8' 'A' '8' '3']
 ['7' '10' '9' '5' '3']
 ['7' '10' '9' '5' '3']
 ['7' '10' '9' '5' '3']]
