# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [2]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [3]:
# your code here
np.version.version

'1.21.5'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [77]:
# Method 1
a = np.random.random(size=(2,3,5))
print(a)


[[[0.42057787 0.09442148 0.0928313  0.81039497 0.81075383]
  [0.9271127  0.10428369 0.10223697 0.90826624 0.91030508]
  [0.64909792 0.6322396  0.298537   0.53527134 0.88144574]]

 [[0.03781055 0.87232768 0.54418274 0.3243791  0.36194245]
  [0.8081575  0.73860703 0.88434312 0.6038452  0.90978899]
  [0.49777283 0.52788194 0.04923826 0.09402499 0.23473841]]]


In [80]:
# Method 2
random2 = np.random.randint(50,355,(2,3,5)) # random numpy array of shape (4,5)
print(random2)

[[[ 90 153 241 263  51]
  [354 338 333 138  98]
  [179  66 307 162 325]]

 [[209 221 102 345 293]
  [ 88 171 168 182  78]
  [311 222  90 174 138]]]


In [79]:
# Method 3
random3 = np.random.rand(2,3,5)
print(random3)

[[[0.4156287  0.85982744 0.94770671 0.35630518 0.06761132]
  [0.25419991 0.07546604 0.3887248  0.4362552  0.28586224]
  [0.84689104 0.26278503 0.48969815 0.62030608 0.42676399]]

 [[0.10190762 0.81643413 0.45416388 0.32498126 0.94771732]
  [0.37906443 0.55370391 0.40750181 0.3155018  0.15859912]
  [0.19137958 0.73164921 0.63978202 0.52572189 0.41766717]]]


#### 4. Print *a*.


In [7]:
# your code here
print(a)

[[[7.80478385e-01 1.39674476e-01 7.64792177e-01 1.49270366e-04
   5.32071306e-02]
  [5.04479440e-01 9.56431274e-02 5.55454468e-01 7.04680311e-01
   2.30605073e-01]
  [5.08683984e-01 2.20915882e-01 1.54262765e-01 4.25913331e-01
   5.52691157e-01]]

 [[6.63919777e-01 6.32773207e-01 8.47524331e-02 2.89901109e-01
   6.33854624e-01]
  [1.47892727e-01 8.57948059e-02 5.12510142e-02 1.65508086e-01
   1.45448253e-01]
  [6.10764088e-01 2.78997677e-01 9.16090034e-01 9.81033333e-01
   2.03736293e-01]]]


In [26]:
# your code here

b = np.ones(shape = (5,2,3))

#### 6. Print *b*.


In [9]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [10]:
# your code here
a.shape == b.shape

False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [11]:
# your answer here
# we cant add a and be if they don't have the same size, we have to transpose one of the arrays to the shape of the other.

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [82]:
# your code here
c = b.reshape(2,3,5)
c


array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [42]:
# your code/answer here

d = a + c
d

#it works because we can perform math operations to arrays with the same shape. if they 
# dont have the same shape, we cant perform these operations.

array([[[1.78047839, 1.13967448, 1.76479218, 1.00014927, 1.05320713],
        [1.50447944, 1.09564313, 1.55545447, 1.70468031, 1.23060507],
        [1.50868398, 1.22091588, 1.15426276, 1.42591333, 1.55269116]],

       [[1.66391978, 1.63277321, 1.08475243, 1.28990111, 1.63385462],
        [1.14789273, 1.08579481, 1.05125101, 1.16550809, 1.14544825],
        [1.61076409, 1.27899768, 1.91609003, 1.98103333, 1.20373629]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [44]:
# your code/answer here
print(a)
print(d)

# the values of d result from the sum of a and c, for that reason, to each element of a we
# added an element of c

[[[7.80478385e-01 1.39674476e-01 7.64792177e-01 1.49270366e-04
   5.32071306e-02]
  [5.04479440e-01 9.56431274e-02 5.55454468e-01 7.04680311e-01
   2.30605073e-01]
  [5.08683984e-01 2.20915882e-01 1.54262765e-01 4.25913331e-01
   5.52691157e-01]]

 [[6.63919777e-01 6.32773207e-01 8.47524331e-02 2.89901109e-01
   6.33854624e-01]
  [1.47892727e-01 8.57948059e-02 5.12510142e-02 1.65508086e-01
   1.45448253e-01]
  [6.10764088e-01 2.78997677e-01 9.16090034e-01 9.81033333e-01
   2.03736293e-01]]]
[[[1.78047839 1.13967448 1.76479218 1.00014927 1.05320713]
  [1.50447944 1.09564313 1.55545447 1.70468031 1.23060507]
  [1.50868398 1.22091588 1.15426276 1.42591333 1.55269116]]

 [[1.66391978 1.63277321 1.08475243 1.28990111 1.63385462]
  [1.14789273 1.08579481 1.05125101 1.16550809 1.14544825]
  [1.61076409 1.27899768 1.91609003 1.98103333 1.20373629]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [46]:
# your code here
e = a * c
e

array([[[7.80478385e-01, 1.39674476e-01, 7.64792177e-01, 1.49270366e-04,
         5.32071306e-02],
        [5.04479440e-01, 9.56431274e-02, 5.55454468e-01, 7.04680311e-01,
         2.30605073e-01],
        [5.08683984e-01, 2.20915882e-01, 1.54262765e-01, 4.25913331e-01,
         5.52691157e-01]],

       [[6.63919777e-01, 6.32773207e-01, 8.47524331e-02, 2.89901109e-01,
         6.33854624e-01],
        [1.47892727e-01, 8.57948059e-02, 5.12510142e-02, 1.65508086e-01,
         1.45448253e-01],
        [6.10764088e-01, 2.78997677e-01, 9.16090034e-01, 9.81033333e-01,
         2.03736293e-01]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [47]:
# your code/answer here
a == e

# c  is a ones array. for that reason we are multiplitying values with 1, therefore we get an array (e)
# that has the same values of a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [74]:
# your code here
d_max = d.max()
print(d_max)

d_min = d.min()
print(d_min)

d_mean = d.mean()
print(d_mean)

1.9810333332307026
1.0001492703659673
1.3861116145999384


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [81]:
# your code here
f = np.empty(shape = [2,3,5])
f

array([[[0.4156287 , 0.85982744, 0.94770671, 0.35630518, 0.06761132],
        [0.25419991, 0.07546604, 0.3887248 , 0.4362552 , 0.28586224],
        [0.84689104, 0.26278503, 0.48969815, 0.62030608, 0.42676399]],

       [[0.10190762, 0.81643413, 0.45416388, 0.32498126, 0.94771732],
        [0.37906443, 0.55370391, 0.40750181, 0.3155018 , 0.15859912],
        [0.19137958, 0.73164921, 0.63978202, 0.52572189, 0.41766717]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [72]:
# your code here
f[(d > d_min) & (d < d_mean)] = 25
f[(d > d_mean) & (d < d_max)] = 75
f[(d == d.mean)] = 50
f[(d == d.min)] = 0
f[(d == d.max)] = 100
f

array([[[7.50000000e+01, 2.50000000e+01, 7.50000000e+01, 1.49270366e-04,
         2.50000000e+01],
        [7.50000000e+01, 2.50000000e+01, 7.50000000e+01, 7.50000000e+01,
         2.50000000e+01],
        [7.50000000e+01, 2.50000000e+01, 2.50000000e+01, 7.50000000e+01,
         7.50000000e+01]],

       [[7.50000000e+01, 7.50000000e+01, 2.50000000e+01, 2.50000000e+01,
         7.50000000e+01],
        [2.50000000e+01, 2.50000000e+01, 2.50000000e+01, 2.50000000e+01,
         2.50000000e+01],
        [7.50000000e+01, 2.50000000e+01, 7.50000000e+01, 9.81033333e-01,
         2.50000000e+01]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [73]:
# your code here
print(d)
print(f)

[[[1.78047839 1.13967448 1.76479218 1.00014927 1.05320713]
  [1.50447944 1.09564313 1.55545447 1.70468031 1.23060507]
  [1.50868398 1.22091588 1.15426276 1.42591333 1.55269116]]

 [[1.66391978 1.63277321 1.08475243 1.28990111 1.63385462]
  [1.14789273 1.08579481 1.05125101 1.16550809 1.14544825]
  [1.61076409 1.27899768 1.91609003 1.98103333 1.20373629]]]
[[[7.50000000e+01 2.50000000e+01 7.50000000e+01 1.49270366e-04
   2.50000000e+01]
  [7.50000000e+01 2.50000000e+01 7.50000000e+01 7.50000000e+01
   2.50000000e+01]
  [7.50000000e+01 2.50000000e+01 2.50000000e+01 7.50000000e+01
   7.50000000e+01]]

 [[7.50000000e+01 7.50000000e+01 2.50000000e+01 2.50000000e+01
   7.50000000e+01]
  [2.50000000e+01 2.50000000e+01 2.50000000e+01 2.50000000e+01
   2.50000000e+01]
  [7.50000000e+01 2.50000000e+01 7.50000000e+01 9.81033333e-01
   2.50000000e+01]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [21]:
# your code here