# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [139]:
import numpy as np
from numpy import random

#### 2. Print your NumPy version.

In [140]:
print(np.__version__)

1.20.3


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [141]:
a=random.uniform(size=(2,3,5))

In [142]:
a=random.normal(size=(2,3,5))

In [143]:
a=random.logistic(size=[2,3,5])

#### 4. Print *a*.


In [144]:
print(a)

[[[-1.87885153  0.63814458  1.71396307  1.47427931 -1.93080065]
  [ 2.03313925 -0.39316646 -0.77062827 -0.51087586 -4.16213523]
  [ 2.85249837  0.08976785  0.13021868 -0.80925294 -0.83814986]]

 [[-1.54090688 -7.98397287  0.42288834 -0.96150814  0.78395527]
  [ 0.43344005 -3.8145407  -0.46052305  1.14609186  1.64763924]
  [-0.58458454  2.09347636 -2.79875442 -2.06261691 -0.4151056 ]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [145]:
b=np.ones(shape=[5,2,3])

#### 6. Print *b*.


In [146]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [147]:
a.shape==b.shape

False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [148]:
# Since they don't have the same dimensions, such mathematical opperation is not possible. It is needed to reshape first.

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [160]:
# b=b.transpose() Using b.transpose() the final array is not 2x3x5. It is needed to use reshape

c=b.reshape([2,3,5])


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [161]:
d=a+c  # It works now beacause a.shape == c.shape (same dimensions)

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [162]:
print(a)
print("\n ---------------//----------------- \n")
print(c)
print("\n ---------------//----------------- \n")
print(d)

# d was generated using a and c arrays, and is the pointwise sum of them, i.e., d(m,n)=a(m,n)+c(m,n)

[[[-1.87885153  0.63814458  1.71396307  1.47427931 -1.93080065]
  [ 2.03313925 -0.39316646 -0.77062827 -0.51087586 -4.16213523]
  [ 2.85249837  0.08976785  0.13021868 -0.80925294 -0.83814986]]

 [[-1.54090688 -7.98397287  0.42288834 -0.96150814  0.78395527]
  [ 0.43344005 -3.8145407  -0.46052305  1.14609186  1.64763924]
  [-0.58458454  2.09347636 -2.79875442 -2.06261691 -0.4151056 ]]]

 ---------------//----------------- 

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]

 ---------------//----------------- 

[[[-0.87885153  1.63814458  2.71396307  2.47427931 -0.93080065]
  [ 3.03313925  0.60683354  0.22937173  0.48912414 -3.16213523]
  [ 3.85249837  1.08976785  1.13021868  0.19074706  0.16185014]]

 [[-0.54090688 -6.98397287  1.42288834  0.03849186  1.78395527]
  [ 1.43344005 -2.8145407   0.53947695  2.14609186  2.64763924]
  [ 0.41541546  3.09347636 -1.79875442 -1.06261691  0.5848944 ]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [163]:
e=a*c

#### 13. Does *e* equal to *a*? Why or why not?


In [164]:
print(a)
print("\n ---------------//----------------- \n")
print(c)
print("\n ---------------//----------------- \n")
print(e)


# e and a arrays are equal, since one (array c) is the null element in multiplications. This way the a array stays the same

[[[-1.87885153  0.63814458  1.71396307  1.47427931 -1.93080065]
  [ 2.03313925 -0.39316646 -0.77062827 -0.51087586 -4.16213523]
  [ 2.85249837  0.08976785  0.13021868 -0.80925294 -0.83814986]]

 [[-1.54090688 -7.98397287  0.42288834 -0.96150814  0.78395527]
  [ 0.43344005 -3.8145407  -0.46052305  1.14609186  1.64763924]
  [-0.58458454  2.09347636 -2.79875442 -2.06261691 -0.4151056 ]]]

 ---------------//----------------- 

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]

 ---------------//----------------- 

[[[-1.87885153  0.63814458  1.71396307  1.47427931 -1.93080065]
  [ 2.03313925 -0.39316646 -0.77062827 -0.51087586 -4.16213523]
  [ 2.85249837  0.08976785  0.13021868 -0.80925294 -0.83814986]]

 [[-1.54090688 -7.98397287  0.42288834 -0.96150814  0.78395527]
  [ 0.43344005 -3.8145407  -0.46052305  1.14609186  1.64763924]
  [-0.58458454  2.09347636 -2.79875442 -2.06261691 -0.4151056 ]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [165]:
d_max=d.max()
d_min=d.min()
d_mean=d.mean()

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [166]:
f=np.empty([2,3,5])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [167]:
g=0
m=0
n=0

for g in range(len(f)):
    for m in range(len(f[0])):
        for n in range(len(f[0][0])):
            if d_min<d[g,m,n]<d_mean:
                f[g,m,n]=25
            elif d_mean<d[g,m,n]<d_max:
                f[g,m,n]=75
            elif d[g,m,n]==d_mean:
                f[g,m,n]=50
            elif d[g,m,n]==d_min:
                f[g,m,n]=0
            elif d[g,m,n]==d_max:
                f[g,m,n]=100

print(f)

[[[ 25.  75.  75.  75.  25.]
  [ 75.  75.  25.  75.  25.]
  [100.  75.  75.  25.  25.]]

 [[ 25.   0.  75.  25.  75.]
  [ 75.  25.  75.  75.  75.]
  [ 25.  75.  25.  25.  75.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# Yes, got what i was expecting

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [172]:
f=np.empty([2,3,5],dtype="str")

for g in range(len(f)):
    for m in range(len(f[0])):
        for n in range(len(f[0][0])):
            if d_min<d[g,m,n]<d_mean:
                f[g,m,n]="B"
            elif d_mean<d[g,m,n]<d_max:
                f[g,m,n]="D"
            elif d[g,m,n]==d_mean:
                f[g,m,n]="C"
            elif d[g,m,n]==d_min:
                f[g,m,n]="A"
            elif d[g,m,n]==d_max:
                f[g,m,n]="E"

print(f)

[[['B' 'D' 'D' 'D' 'B']
  ['D' 'D' 'B' 'D' 'B']
  ['E' 'D' 'D' 'B' 'B']]

 [['B' 'A' 'D' 'B' 'D']
  ['D' 'B' 'D' 'D' 'D']
  ['B' 'D' 'B' 'B' 'D']]]
