# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np
import random

#### 2. Print your NumPy version.

In [2]:
# your code here
np.version.version

'1.22.3'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a1 = np.random.random((2,3,5))
a1

array([[[0.23602085, 0.04494475, 0.53123357, 0.59774992, 0.11885405],
        [0.1191895 , 0.58677956, 0.1182133 , 0.04517857, 0.54044946],
        [0.38921018, 0.29118541, 0.97685141, 0.8002397 , 0.23107002]],

       [[0.27938238, 0.29227256, 0.16808994, 0.08898697, 0.82938068],
        [0.79486278, 0.17641645, 0.87105975, 0.62225751, 0.34767988],
        [0.86951478, 0.75380681, 0.30688751, 0.96371675, 0.78420352]]])

In [4]:
# Method 2
a2 = np.random.randint(0, 100, size=(2, 3, 5))
a2

array([[[38, 44, 34, 25,  0],
        [59, 75, 50, 33, 99],
        [18, 61, 43, 27, 21]],

       [[13, 95, 41, 62, 17],
        [85, 49, 89, 44, 31],
        [69, 64, 44, 25, 62]]])

In [5]:
# Method 3
a3 = np.random.normal(0,20, size=(2,3,5))
a3

array([[[-19.90947876,  13.2256764 ,   3.10192365,  -2.78223611,
          24.84429155],
        [ -4.52867232,  28.37294551, -49.99456384, -27.28935612,
         -32.13621614],
        [  2.48677739,   2.44617269,  28.44007768,  17.85526814,
          29.79342275]],

       [[  9.91216112,   4.94906936,   9.11095791,  17.15545556,
          26.99514955],
        [ 10.23357043,  11.65391199, -36.78216623,   5.66794895,
          16.86894888],
        [-16.98531616,  -6.84053548,  -3.27879455,   3.4177939 ,
           0.60429241]]])

#### 4. Print *a*.


In [6]:
# your code here
a = a1
print(a)

[[[0.23602085 0.04494475 0.53123357 0.59774992 0.11885405]
  [0.1191895  0.58677956 0.1182133  0.04517857 0.54044946]
  [0.38921018 0.29118541 0.97685141 0.8002397  0.23107002]]

 [[0.27938238 0.29227256 0.16808994 0.08898697 0.82938068]
  [0.79486278 0.17641645 0.87105975 0.62225751 0.34767988]
  [0.86951478 0.75380681 0.30688751 0.96371675 0.78420352]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here
b = np.ones(shape=(5,2,3))

#### 6. Print *b*.


In [8]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here
a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here
#c = a + b
# i can´t sum them because they dont have the same shape
print(a.shape)
print(b.shape)

(2, 3, 5)
(5, 2, 3)


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code/answer here
from pandas import array

b = b.reshape((5,3,2))
b.shape

c = b.T
c.shape



(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# your code/answer here
#now it works because "a" and "c" have the same shape (2,3,5)
d = a + c
d

array([[[1.23602085, 1.04494475, 1.53123357, 1.59774992, 1.11885405],
        [1.1191895 , 1.58677956, 1.1182133 , 1.04517857, 1.54044946],
        [1.38921018, 1.29118541, 1.97685141, 1.8002397 , 1.23107002]],

       [[1.27938238, 1.29227256, 1.16808994, 1.08898697, 1.82938068],
        [1.79486278, 1.17641645, 1.87105975, 1.62225751, 1.34767988],
        [1.86951478, 1.75380681, 1.30688751, 1.96371675, 1.78420352]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# your code/answer here
print(a)
print(d)

# "d" is the sum of "a" and "c", and "c's" origin is in "b", which is a np.one array. the difference between "a" and "d" is precisely that unit (of "ones")

[[[0.23602085 0.04494475 0.53123357 0.59774992 0.11885405]
  [0.1191895  0.58677956 0.1182133  0.04517857 0.54044946]
  [0.38921018 0.29118541 0.97685141 0.8002397  0.23107002]]

 [[0.27938238 0.29227256 0.16808994 0.08898697 0.82938068]
  [0.79486278 0.17641645 0.87105975 0.62225751 0.34767988]
  [0.86951478 0.75380681 0.30688751 0.96371675 0.78420352]]]
[[[1.23602085 1.04494475 1.53123357 1.59774992 1.11885405]
  [1.1191895  1.58677956 1.1182133  1.04517857 1.54044946]
  [1.38921018 1.29118541 1.97685141 1.8002397  1.23107002]]

 [[1.27938238 1.29227256 1.16808994 1.08898697 1.82938068]
  [1.79486278 1.17641645 1.87105975 1.62225751 1.34767988]
  [1.86951478 1.75380681 1.30688751 1.96371675 1.78420352]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
# your code here

e = a * c
e

array([[[0.23602085, 0.04494475, 0.53123357, 0.59774992, 0.11885405],
        [0.1191895 , 0.58677956, 0.1182133 , 0.04517857, 0.54044946],
        [0.38921018, 0.29118541, 0.97685141, 0.8002397 , 0.23107002]],

       [[0.27938238, 0.29227256, 0.16808994, 0.08898697, 0.82938068],
        [0.79486278, 0.17641645, 0.87105975, 0.62225751, 0.34767988],
        [0.86951478, 0.75380681, 0.30688751, 0.96371675, 0.78420352]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
# your code/answer here
# once "c" is all composed by number 1, when multiplied by any variable, the final value is that variable. that's why e = a
e == a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
# your code here
d_max = np.max(d)
print(d_max)
d_min = np.min(d)
print(d_min)
d_mean = np.mean(d)
print(d_mean)

1.976851409252876
1.044944753785126
1.4591896171836536


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [17]:
# your code here
f = np.empty((2,3,5))
fl = []



#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [18]:
# your code here

my_list = [z for x in d for y in x for z in y]
my_list
for i in my_list:
    if i > d_min and i < d_mean:
        fl.append(25)
    if i > d_mean and i < d_max:
        fl.append(75)
    if i == d_mean:
        fl.append(50)
    if i == d_min:
        fl.append(0)
    if i == d_max:
        fl.append(100)
    else:
        continue



In [26]:
fnp = np.asarray(fl)
freshape = fnp.reshape((2,3,5))
f = freshape
f


array([[[ 25,   0,  75,  75,  25],
        [ 25,  75,  25,  25,  75],
        [ 25,  25, 100,  75,  25]],

       [[ 25,  25,  25,  25,  75],
        [ 75,  25,  75,  75,  25],
        [ 75,  75,  25,  75,  75]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [20]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [21]:
# your code here