# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [13]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [14]:
# your code here
print(np.__version__)

1.23.3


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [15]:
# Method 1
a = np.random.random(size=(2,3,5))

In [16]:
# Method 2
a = np.random.choice((range(100)),size=(2,3,5))

In [17]:
# Method 3
a = np.random.rand(2,3,5)

In [18]:
# Method 4
a = np.random.randint(low = 1, high = 52, size=(2,3,5))

#### 4. Print *a*.


In [19]:
# your code here
print(a)

[[[39 33 37 11 16]
  [14 31 40  2 25]
  [26 26  1  9 38]]

 [[43 19 50 43 31]
  [45  8  4 16  1]
  [44  7 17 50  1]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [20]:
# your code here
b = np.ones(shape=(5, 2, 3))

#### 6. Print *b*.


In [21]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [22]:
# your code here
print(a.shape)
print(b.shape)
print(a.shape == b.shape)

## They are not the same size (although they have the same number of elements)

(2, 3, 5)
(5, 2, 3)
False


#### 8. Are you able to add *a* and *b*? Why or why not?


In [23]:
# your answer here
# You can't add a and b as they are not the same size. If they have the same number of elements (which is the case), you can add them if you reshape one of them
# c = a + b <-- This will throw a ValueError

# This...
c = a + b.reshape(2,3,5)
# ...or this will work
d = a.reshape(5,2,3) + b
print(c)
print(d)

[[[40. 34. 38. 12. 17.]
  [15. 32. 41.  3. 26.]
  [27. 27.  2. 10. 39.]]

 [[44. 20. 51. 44. 32.]
  [46.  9.  5. 17.  2.]
  [45.  8. 18. 51.  2.]]]
[[[40. 34. 38.]
  [12. 17. 15.]]

 [[32. 41.  3.]
  [26. 27. 27.]]

 [[ 2. 10. 39.]
  [44. 20. 51.]]

 [[44. 32. 46.]
  [ 9.  5. 17.]]

 [[ 2. 45.  8.]
  [18. 51.  2.]]]


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [24]:
# your code here
c= b.reshape(2,3,5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [25]:
# your code/answer here

d = a + c

# It works now, because the arrays have the same shape

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [26]:
# your code/answer here
print(a)
print(d)

# The values of d are the values of a + 1. This can be explained as:
# d was created by adding a and c, and c is a reshape of b, which was created with the np.ones() functions, thus all values in c are 1.

[[[39 33 37 11 16]
  [14 31 40  2 25]
  [26 26  1  9 38]]

 [[43 19 50 43 31]
  [45  8  4 16  1]
  [44  7 17 50  1]]]
[[[40. 34. 38. 12. 17.]
  [15. 32. 41.  3. 26.]
  [27. 27.  2. 10. 39.]]

 [[44. 20. 51. 44. 32.]
  [46.  9.  5. 17.  2.]
  [45.  8. 18. 51.  2.]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [27]:
# your code here
e = a * c

#### 13. Does *e* equal to *a*? Why or why not?


In [28]:
# your code/answer here
print(e == a)

## Yes, it does because, once again, all elements of c are 1 and 1 is the multiplication identity (ie, any number * 1 = number).

[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [29]:
# your code here
d_max = d.max()
d_min = d.min()
d_mean = d.mean()
print(d_max, d_min, d_mean)

51.0 2.0 25.233333333333334


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [46]:
# your code here
f = np.empty(shape = (2,3,5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [52]:
# your code here
f[d == d_max] = 100
f[np.logical_and(d > d_mean, d < d_max)] = 75
f[d == d_mean] = 50
f[np.logical_and(d < d_mean, d > d_min)] = 25
f[d == d_min] = 0

[[[ 75.  75.  75.  25.  25.]
  [ 25.  75.  75.  25.  75.]
  [ 75.  75.   0.  25.  75.]]

 [[ 75.  25. 100.  75.  75.]
  [ 75.  25.  25.  25.   0.]
  [ 75.  25.  25. 100.   0.]]]


'\nmax_index = np.argwhere(d == d_max)\nlarge_index = np.argwhere(np.logical_and(d > d_mean,d < d_max))\nmean_index = np.argwhere(d == d_mean)\nlow_index = np.argwhere(np.logical_and(d > d_min, d < d_mean))\nmin_index = np.argwhere(d == d_min)\n\nfor element in max_index:\n\tf[element[0], element[1], element[2]] = 100\n\nfor element in large_index:\n\tf[element[0], element[1], element[2]] = 75\n\nfor element in mean_index:\n\tf[element[0], element[1], element[2]] = 50\n\nfor element in low_index:\n\tf[element[0], element[1], element[2]] = 25\n\nfor element in min_index:\n\tf[element[0], element[1], element[2]] = 0\n\t'

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [53]:
# your code here
print(d)
print(f)

# Sure seems like it!

[[[40. 34. 38. 12. 17.]
  [15. 32. 41.  3. 26.]
  [27. 27.  2. 10. 39.]]

 [[44. 20. 51. 44. 32.]
  [46.  9.  5. 17.  2.]
  [45.  8. 18. 51.  2.]]]
[[[ 75.  75.  75.  25.  25.]
  [ 25.  75.  75.  25.  75.]
  [ 75.  75.   0.  25.  75.]]

 [[ 75.  25. 100.  75.  75.]
  [ 75.  25.  25.  25.   0.]
  [ 75.  25.  25. 100.   0.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [54]:
# your code here

f = np.array(f, dtype=object)

f[d == d_max] = "E"
f[np.logical_and(d > d_mean, d < d_max)] = "D"
f[d == d_mean] = "C"
f[np.logical_and(d < d_mean, d > d_min)] = "B"
f[d == d_min] = "A"

print(f)
	


[[['D' 'D' 'D' 'B' 'B']
  ['B' 'D' 'D' 'B' 'D']
  ['D' 'D' 'A' 'B' 'D']]

 [['D' 'B' 'E' 'D' 'D']
  ['D' 'B' 'B' 'B' 'A']
  ['D' 'B' 'B' 'E' 'A']]]
