# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [5]:
np.version.version

'1.16.5'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [8]:
np.random.random((2,3,5))

array([[[0.81642223, 0.40715487, 0.55950664, 0.71352249, 0.64178277],
        [0.96520713, 0.4936748 , 0.4309857 , 0.70504843, 0.04182138],
        [0.32845577, 0.84057356, 0.84100469, 0.75023791, 0.44932702]],

       [[0.77099965, 0.38080713, 0.88714738, 0.07546853, 0.47264692],
        [0.64864705, 0.8944192 , 0.77987441, 0.22113007, 0.09529973],
        [0.17574632, 0.21089218, 0.54066716, 0.5919014 , 0.73324125]]])

In [13]:
a = np.random.randint(100,1000,(2,3,5))

In [12]:
np.random.randn(2,3,5)

array([[[-1.67641713,  0.10417867,  0.58872847,  0.01142102,
          0.23460267],
        [-0.52974377,  1.53519573, -0.71104573,  0.29378909,
          0.28106318],
        [ 1.56036651,  1.43876588, -1.54060473,  0.62306965,
         -0.20921278]],

       [[ 0.9851794 ,  1.45706427,  0.80161225, -0.96864804,
         -0.07514173],
        [ 1.38552403, -0.40641148,  0.13189449,  0.12519222,
         -0.79323609],
        [-0.59197967,  0.97617078, -1.04113697, -0.64291451,
          0.21444307]]])

#### 4. Print *a*.


In [14]:
print(a)

[[[596 733 272 310 413]
  [172 739 488 861 505]
  [579 488 885 181 983]]

 [[782 225 531 292 710]
  [762 486 375 179 159]
  [287 110 507 716 224]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [34]:
b = np.ones((5,2,3), dtype=int)

#### 6. Print *b*.


In [20]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [22]:
a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [23]:
a + b

# no, we can't because the shapes are different

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [31]:
c = b.transpose(1, 2, 0)
print(a.shape, b.shape, c.shape)

(2, 3, 5) (5, 2, 3) (2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [36]:
d = a + c

# now the arrays are the same shape

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [42]:
#print(a)
print(d)

# each value is the sum of the values in the same position in  a  and  c

[[[597. 734. 273. 311. 414.]
  [173. 740. 489. 862. 506.]
  [580. 489. 886. 182. 984.]]

 [[783. 226. 532. 293. 711.]
  [763. 487. 376. 180. 160.]
  [288. 111. 508. 717. 225.]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [41]:
e = a * c
print(e, e.shape)

[[[596. 733. 272. 310. 413.]
  [172. 739. 488. 861. 505.]
  [579. 488. 885. 181. 983.]]

 [[782. 225. 531. 292. 710.]
  [762. 486. 375. 179. 159.]
  [287. 110. 507. 716. 224.]]] (2, 3, 5)


#### 13. Does *e* equal to *a*? Why or why not?


In [45]:
a == e
# yes. the array  e  is the result of the multiplications of each value in the same positions in in a and c

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [49]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print (d_max, d_min, d_mean)

984.0 111.0 486.0


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [63]:
f = np.empty((2,3,5))
print (f)

[[[597. 734. 273. 311. 414.]
  [173. 740. 489. 862. 506.]
  [580. 489. 886. 182. 984.]]

 [[783. 226. 532. 293. 711.]
  [763. 487. 376. 180. 160.]
  [288. 111. 508. 717. 225.]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [72]:
#temp = [0 if (elem == d_min) else 25 if (elem < d_mean) else 50 if (elem == d_mean) else 75 if (elem < d_max) else 100 for z in d for y in z for elem in y]

for z in range(d.shape[0]):
    for y in range(d.shape[1]):
        for x in range(d.shape[2]):
            f[z][y][x] = 0 if (d[z][y][x] == d_min) else 25 if (d[z][y][x] < d_mean) else 50 if (d[z][y][x] == d_mean) else 75 if (d[z][y][x] < d_max) else 100


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [73]:
print(d)
print(f)

[[[597. 734. 273. 311. 414.]
  [173. 740. 489. 862. 506.]
  [580. 489. 886. 182. 984.]]

 [[783. 226. 532. 293. 711.]
  [763. 487. 376. 180. 160.]
  [288. 111. 508. 717. 225.]]]
[[[ 75.  75.  25.  25.  25.]
  [ 25.  75.  75.  75.  75.]
  [ 75.  75.  75.  25. 100.]]

 [[ 75.  25.  75.  25.  75.]
  [ 75.  75.  25.  25.  25.]
  [ 25.   0.  75.  75.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here