# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [2]:
import numpy as np

#### 2. Print your NumPy version.

In [3]:
np.__version__

'1.18.1'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [4]:
a = np.random.randint(2, 15, size=(2,3,5))
a.shape

(2, 3, 5)

In [5]:
a = np.random.rand(2,3,5) #rand - de 0 a 1
a.shape

(2, 3, 5)

In [6]:
#a = np.random.uniform(low = 2, high = 3, size = 5) # Trye
#a = np.random.choice(2,3,5)
a = np.random.random((2,3,5)) #with negative numbers
a.shape

(2, 3, 5)

#### 4. Print *a*.


In [7]:
print(a)

[[[0.34747413 0.98773866 0.2031462  0.77061017 0.17825109]
  [0.78627188 0.1856317  0.79620119 0.61912943 0.0362252 ]
  [0.50236616 0.74465093 0.16553572 0.70290965 0.40962866]]

 [[0.3739402  0.85655762 0.88587278 0.65339948 0.81160438]
  [0.27844821 0.36051207 0.23156242 0.56586291 0.33710416]
  [0.7916235  0.88051315 0.11558167 0.82739294 0.89673734]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [8]:
b = np.ones((5, 2, 3), dtype = int) #changed to 5x2x3

#### 6. Print *b*.


In [9]:
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [10]:
a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [11]:
c = npconcatenate((a, b)) #Different dimension cannot concat

NameError: name 'npconcatenate' is not defined

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [12]:
c = b.transpose(1, 2, 0)
print(c.shape)

(2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [52]:
d = a + c #works because when i did transpose he starts to work
print(d.shape)

(2, 3, 5)


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [53]:
print('array a : ')
print(a, a.dtype)
print('array d: ')
print(d, d.dtype)

array a : 
[[[0.34747413 0.98773866 0.2031462  0.77061017 0.17825109]
  [0.78627188 0.1856317  0.79620119 0.61912943 0.0362252 ]
  [0.50236616 0.74465093 0.16553572 0.70290965 0.40962866]]

 [[0.3739402  0.85655762 0.88587278 0.65339948 0.81160438]
  [0.27844821 0.36051207 0.23156242 0.56586291 0.33710416]
  [0.7916235  0.88051315 0.11558167 0.82739294 0.89673734]]] float64
array d: 
[[[1.34747413 1.98773866 1.2031462  1.77061017 1.17825109]
  [1.78627188 1.1856317  1.79620119 1.61912943 1.0362252 ]
  [1.50236616 1.74465093 1.16553572 1.70290965 1.40962866]]

 [[1.3739402  1.85655762 1.88587278 1.65339948 1.81160438]
  [1.27844821 1.36051207 1.23156242 1.56586291 1.33710416]
  [1.7916235  1.88051315 1.11558167 1.82739294 1.89673734]]] float64


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [54]:
e = np.multiply(a, c)
print(e)

[[[0.34747413 0.98773866 0.2031462  0.77061017 0.17825109]
  [0.78627188 0.1856317  0.79620119 0.61912943 0.0362252 ]
  [0.50236616 0.74465093 0.16553572 0.70290965 0.40962866]]

 [[0.3739402  0.85655762 0.88587278 0.65339948 0.81160438]
  [0.27844821 0.36051207 0.23156242 0.56586291 0.33710416]
  [0.7916235  0.88051315 0.11558167 0.82739294 0.89673734]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [55]:
np.array_equal(e, a)

True

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [60]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print('max:', round(d_max, 2))
print('min:', round(d_min, 2))
print('mean:', round(d_mean, 2))

max: 1.99
min: 1.04
mean: 1.54


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [61]:
f = np.empty([2, 3, 5])
print(f)

[[[ 25. 100.  25.  75.  25.]
  [ 75.  25.  75.  75.   0.]
  [ 25.  75.  25.  75.  25.]]

 [[ 25.  75.  75.  75.  75.]
  [ 25.  25.  25.  75.  25.]
  [ 75.  75.  25.  75.  75.]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [62]:
f[(d_min < d) & (d< d_mean)] = 25
f[(d_mean < d) & (d < d_max)] = 75
f[d == d_mean] = 50
f[d == d_min] = 0 
f[d == d_max] = 100

print(f)
'f = [0 if (elem == d_min) else 25 if (elem < d_mean) else 50 if (elem == d_mean) else 75 if (elem < d_max) else 100 for z in d for y in z for elem in y]'

[[[ 25. 100.  25.  75.  25.]
  [ 75.  25.  75.  75.   0.]
  [ 25.  75.  25.  75.  25.]]

 [[ 25.  75.  75.  75.  75.]
  [ 25.  25.  25.  75.  25.]
  [ 75.  75.  25.  75.  75.]]]


'f = [0 if (elem == d_min) else 25 if (elem < d_mean) else 50 if (elem == d_mean) else 75 if (elem < d_max) else 100 for z in d for y in z for elem in y]'

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [63]:
print(d)
print(f)

[[[1.34747413 1.98773866 1.2031462  1.77061017 1.17825109]
  [1.78627188 1.1856317  1.79620119 1.61912943 1.0362252 ]
  [1.50236616 1.74465093 1.16553572 1.70290965 1.40962866]]

 [[1.3739402  1.85655762 1.88587278 1.65339948 1.81160438]
  [1.27844821 1.36051207 1.23156242 1.56586291 1.33710416]
  [1.7916235  1.88051315 1.11558167 1.82739294 1.89673734]]]
[[[ 25. 100.  25.  75.  25.]
  [ 75.  25.  75.  75.   0.]
  [ 25.  75.  25.  75.  25.]]

 [[ 25.  75.  75.  75.  75.]
  [ 25.  25.  25.  75.  25.]
  [ 75.  75.  25.  75.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [66]:
g = np.empty((2,3,5), dtype = str)

g[(d_min < d) & (d < d_mean)] = 'B'
g[(d_mean < d) & (d < d_max)] = 'D'
g[d == d_mean] = 'C'
g[d ==d_min] = 'A'
g[d == d_max] = 'E'
print(g)

[[['B' 'E' 'B' 'D' 'B']
  ['D' 'B' 'D' 'D' 'A']
  ['B' 'D' 'B' 'D' 'B']]

 [['B' 'D' 'D' 'D' 'D']
  ['B' 'B' 'B' 'D' 'B']
  ['D' 'D' 'B' 'D' 'D']]]
