# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [2]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [3]:
# your code here
print(np.version.version)

1.21.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [4]:
# Method 1
a = np.random.random(size = (2,3,5)) 

In [ ]:
# Method 2

In [ ]:
# Method 3

#### 4. Print *a*.


In [5]:
# your code here
print(a)

[[[9.00668094e-01 3.16617088e-01 6.90184981e-01 5.74862929e-01
   1.30400779e-01]
  [8.80196855e-01 7.05241997e-01 3.04961631e-01 2.40474248e-01
   8.09836524e-01]
  [1.37826583e-01 4.52991807e-01 1.78741215e-01 7.33357581e-01
   9.52647886e-01]]

 [[4.96952232e-01 3.88277468e-01 3.89283189e-01 2.20401577e-01
   3.57342058e-01]
  [5.38897916e-04 7.65239110e-01 2.42774422e-01 7.11955297e-01
   8.00606382e-01]
  [7.41280463e-01 4.84497527e-01 1.31868488e-01 1.24724045e-01
   6.71256170e-01]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [6]:
# your code here
b = np.ones(shape=(5,2,3), dtype=int)

#### 6. Print *b*.


In [7]:
# your code here
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here
a + b

They do not have the same size

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 8. Are you able to add *a* and *b*? Why or why not?


In [ ]:
# your answer here
You cannot add a and b as they are not the same size.

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [10]:
# your code here
c = b.reshape(2,3,5)
print(c)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [11]:
# your code/answer here
d = a + c 

a and c are now the same size.

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [12]:
# your code/answer here
print(a)


[[[9.00668094e-01 3.16617088e-01 6.90184981e-01 5.74862929e-01
   1.30400779e-01]
  [8.80196855e-01 7.05241997e-01 3.04961631e-01 2.40474248e-01
   8.09836524e-01]
  [1.37826583e-01 4.52991807e-01 1.78741215e-01 7.33357581e-01
   9.52647886e-01]]

 [[4.96952232e-01 3.88277468e-01 3.89283189e-01 2.20401577e-01
   3.57342058e-01]
  [5.38897916e-04 7.65239110e-01 2.42774422e-01 7.11955297e-01
   8.00606382e-01]
  [7.41280463e-01 4.84497527e-01 1.31868488e-01 1.24724045e-01
   6.71256170e-01]]]


In [14]:
print(d)

They are now the same size array and the only difference in the values of each element is '1'.

[[[1.90066809 1.31661709 1.69018498 1.57486293 1.13040078]
  [1.88019686 1.705242   1.30496163 1.24047425 1.80983652]
  [1.13782658 1.45299181 1.17874122 1.73335758 1.95264789]]

 [[1.49695223 1.38827747 1.38928319 1.22040158 1.35734206]
  [1.0005389  1.76523911 1.24277442 1.7119553  1.80060638]
  [1.74128046 1.48449753 1.13186849 1.12472405 1.67125617]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [15]:
# your code here
e = a*c
print(e)

[[[9.00668094e-01 3.16617088e-01 6.90184981e-01 5.74862929e-01
   1.30400779e-01]
  [8.80196855e-01 7.05241997e-01 3.04961631e-01 2.40474248e-01
   8.09836524e-01]
  [1.37826583e-01 4.52991807e-01 1.78741215e-01 7.33357581e-01
   9.52647886e-01]]

 [[4.96952232e-01 3.88277468e-01 3.89283189e-01 2.20401577e-01
   3.57342058e-01]
  [5.38897916e-04 7.65239110e-01 2.42774422e-01 7.11955297e-01
   8.00606382e-01]
  [7.41280463e-01 4.84497527e-01 1.31868488e-01 1.24724045e-01
   6.71256170e-01]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [16]:
# your code/answer here
e == a

Yes, all the elements in a were multiplied by 1 so it returned the same value.

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [17]:
# your code here
d_max = d.max()
d_min = d.min()
d_mean = d.mean()
print(d_max)
print(d_min)
print(d_mean)

1.9526478863048242
1.000538897916194
1.484533584170888


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [18]:
# your code here
f = np.empty_like(d)

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [49]:
# your code here


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [48]:
# your code here


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here