# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [48]:
# your code here

import numpy as np

#### 2. Print your NumPy version.

In [49]:
# your code here
print(np.__version__)

1.19.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [50]:
# Method 1  : 

a =  np.random.randn(2,3,5)
print(a)

[[[-2.13181403 -0.56242785 -0.90310062  0.53376134 -0.5891905 ]
  [-2.22229163 -0.73985147  0.44056093  0.65990561  0.45827274]
  [-0.55984819 -1.1387512  -0.28814173 -0.25962169 -0.13737865]]

 [[ 1.61485071 -0.743767   -2.26609456 -3.07815377 -1.92745582]
  [ 0.01326791 -2.37034726  0.00975812 -1.01065251 -0.08992144]
  [-1.41258487 -0.0370563   0.12398769 -1.31814265  0.63841421]]]


In [51]:
# Method 2  : generate random floating from 0 to 1

a = np.random.random(size = (2,3,5))

print(a)

[[[0.62527715 0.67631684 0.75575192 0.43211692 0.58492117]
  [0.65941337 0.88122469 0.94753942 0.62465319 0.57615418]
  [0.08963309 0.14134174 0.32056881 0.87733251 0.75420669]]

 [[0.84731561 0.2612063  0.46214831 0.35057692 0.22988484]
  [0.66819618 0.72611694 0.0275701  0.49328894 0.95340656]
  [0.50985468 0.59177016 0.66614095 0.14408541 0.3748011 ]]]


In [52]:
# Method 3

a = np.random.randint(0,100,(2,3,5))

print(a)

[[[66 54 38 44 53]
  [43 92 20 29 23]
  [85 86 99 36 18]]

 [[ 4 56 48 26 99]
  [50  2 50 12 48]
  [30 37 95 53  5]]]


#### 4. Print *a*.


In [53]:
# your code here
a = np.random.randint(0,100,(2,3,5))

print(a)

[[[ 4 68 54 26 61]
  [36 22 73 61  0]
  [74 26 48 45 45]]

 [[ 3 13 96 87 47]
  [30  2 77 91 81]
  [54 29  9 97 82]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [54]:
# your code here

b = np.ones(shape = (5,2,3), dtype = int)

#### 6. Print *b*.


In [55]:
# your code here
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [56]:
# your code here
a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [57]:
# your answer here

c = a + b
print(c)   # operands could not be broadcast together with shapes (2,3,5) (5,2,3)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [58]:
# your code here

#c = b.transpose()  # transpose give a 3,2,5 array

c = b.reshape(2,3,5)  # actually need to reshape no transpose
c.shape

(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [59]:
# your code/answer here
d = a + c
print(d)   # now it works because they have the same shape

[[[ 5 69 55 27 62]
  [37 23 74 62  1]
  [75 27 49 46 46]]

 [[ 4 14 97 88 48]
  [31  3 78 92 82]
  [55 30 10 98 83]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [60]:
# your code/answer here

print(a)   ### yes, is sum +1

[[[ 4 68 54 26 61]
  [36 22 73 61  0]
  [74 26 48 45 45]]

 [[ 3 13 96 87 47]
  [30  2 77 91 81]
  [54 29  9 97 82]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [61]:
# your code here

e = a * c
print(e)

[[[ 4 68 54 26 61]
  [36 22 73 61  0]
  [74 26 48 45 45]]

 [[ 3 13 96 87 47]
  [30  2 77 91 81]
  [54 29  9 97 82]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [62]:
# your code/answer here

e == a  # they are equal as c is the reshape of b that was an array with only ones

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [64]:
# your code here
d_max = d.max()

d_min = d.min()

d_mean = d.mean()

print(d_max)
print(d_min)
print(d_mean)

98
1
49.03333333333333


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [90]:
# your code here

f = np.empty_like(d)


#d[0][1][2]

#print(d)

f

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

In [71]:


list(np.nditer(d))

[array(5),
 array(69),
 array(55),
 array(27),
 array(62),
 array(37),
 array(23),
 array(74),
 array(62),
 array(1),
 array(75),
 array(27),
 array(49),
 array(46),
 array(46),
 array(4),
 array(14),
 array(97),
 array(88),
 array(48),
 array(31),
 array(3),
 array(78),
 array(92),
 array(82),
 array(55),
 array(30),
 array(10),
 array(98),
 array(83)]

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [73]:
# your code here

f = []

for i in list(np.nditer(d)):
    
        if (i > d_min) & (i < d_mean):
            f += [25]
        if (i > d_mean) & (i < d_max):
            f += [75]
        if i == d_mean:
            f += [50]
        if i == d_min:
            f += [0]
        if i == d_max:
            f += [100]

print(f)


[25, 75, 75, 25, 75, 25, 25, 75, 75, 0, 75, 25, 25, 25, 25, 25, 25, 75, 75, 25, 25, 25, 75, 75, 75, 75, 25, 25, 100, 75]


In [80]:
cond1 = (d > d_min) & (d < d_mean)
cond2 = (d > d_mean) & (d < d_max)
cond3 = d == d_mean
cond4 = d == d_min
cond5 = d == d_max


f[cond1] = 25
f[cond2] = 75
f[cond3] = 50
f[cond4] = 0
f[cond5] = 100

f

array([[[ 25,  75,  75,  25,  75],
        [ 25,  25,  75,  75,   0],
        [ 75,  25,  25,  25,  25]],

       [[ 25,  25,  75,  75,  25],
        [ 25,  25,  75,  75,  75],
        [ 75,  25,  25, 100,  75]]])

In [91]:
print(d.shape)

print(d)

for gr in range(d.shape[0]):
    for row in range(d.shape[1]):
        for col in range(d.shape[2]):
            #print(gr, row, col)
            if (d[gr, row, col] > d_min) & (d[gr, row, col] < d_mean):
                f[gr, row, col] = 25
                
            else:
                
                continue
h
            
    
    


(2, 3, 5)
[[[ 5 69 55 27 62]
  [37 23 74 62  1]
  [75 27 49 46 46]]

 [[ 4 14 97 88 48]
  [31  3 78 92 82]
  [55 30 10 98 83]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here