# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [2]:
import numpy as np

#### 2. Print your NumPy version.

In [4]:
print(np.version.version)

1.19.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [18]:
# Method 1

a = np.random.random((2,3,5))
a= np.round(a,1)
a

array([[[1. , 0.9, 0.4, 0.4, 0.5],
        [0.3, 0.4, 0.5, 0.5, 0.8],
        [0.4, 1. , 1. , 0.9, 0.2]],

       [[0.8, 0.4, 0.7, 0.9, 0. ],
        [0.8, 0.1, 0.7, 0.4, 0.2],
        [0. , 0.9, 0.1, 0.6, 0.5]]])

In [24]:
a = np.random.randint(1,10,(2,3,5))
a = np.round(a,1)
a

array([[[7, 4, 8, 4, 7],
        [5, 2, 6, 8, 8],
        [3, 6, 2, 5, 4]],

       [[7, 1, 6, 1, 2],
        [2, 5, 8, 7, 6],
        [7, 2, 3, 5, 9]]])

In [69]:
# Method 3
a = np.round(np.random.rand(2,3,5),1)
a.shape

(2, 3, 5)

#### 4. Print *a*.


In [28]:
# your code here
print(a)

[[[0.  0.1 0.1 0.8 0.7]
  [0.  0.4 0.6 0.6 0.5]
  [0.9 0.8 0.6 0.2 0.6]]

 [[0.8 0.5 0.1 1.  0.1]
  [0.8 0.8 0.8 0.7 0.3]
  [1.  1.  0.9 0.9 0.4]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [90]:
# your code here
b = np.ones((5,2,3))
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 6. Print *b*.


In [54]:
# your code here
a

array([[[0.9, 0.6, 0.9, 0.9, 0.9],
        [0.4, 0.3, 0.4, 0.1, 0.9],
        [0.7, 0.9, 0.2, 0.3, 0.2]],

       [[0.9, 0.8, 0.6, 0. , 0.9],
        [0.6, 0.9, 0.8, 0.1, 0.8],
        [0.9, 0.4, 0.8, 0.4, 0.6]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [35]:
# your code here
np.shape(a) == np.shape(b)

False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [47]:
a.resize(b.shape)
c = a+b
c

# you can only add arrays of same size(my understanding) so you have to manipulate the shapes. 

array([[[1. , 1.1, 1.1],
        [1.8, 1.7, 1. ]],

       [[1.4, 1.6, 1.6],
        [1.5, 1.9, 1.8]],

       [[1.6, 1.2, 1.6],
        [1.8, 1.5, 1.1]],

       [[2. , 1.1, 1.8],
        [1.8, 1.8, 1.7]],

       [[1.3, 2. , 2. ],
        [1.9, 1.9, 1.4]]])

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [89]:
# your code here
a = np.round(np.random.rand(2,3,5),1)
b.shape
c = np.transpose(b,axes = (1,2,0))
c


array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [92]:
# your code/answer here
d = a+c

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [94]:
# your code/answer here
print(a)
print()
print(d)

[[[0.8 0.6 0.8 0.1 0.3]
  [0.4 0.9 0.2 0.2 0.4]
  [0.8 0.1 0.3 0.9 0.7]]

 [[0.2 0.9 0.1 0.7 0.8]
  [0.6 0.6 0.9 0.7 0.9]
  [0.5 0.3 0.6 0.5 0.7]]]

[[[1.8 1.6 1.8 1.1 1.3]
  [1.4 1.9 1.2 1.2 1.4]
  [1.8 1.1 1.3 1.9 1.7]]

 [[1.2 1.9 1.1 1.7 1.8]
  [1.6 1.6 1.9 1.7 1.9]
  [1.5 1.3 1.6 1.5 1.7]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [95]:
# your code here
e = a*c
e

array([[[0.8, 0.6, 0.8, 0.1, 0.3],
        [0.4, 0.9, 0.2, 0.2, 0.4],
        [0.8, 0.1, 0.3, 0.9, 0.7]],

       [[0.2, 0.9, 0.1, 0.7, 0.8],
        [0.6, 0.6, 0.9, 0.7, 0.9],
        [0.5, 0.3, 0.6, 0.5, 0.7]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [96]:
# your code/answer here

e == a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [101]:
# your code here


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [126]:
# your code here
f = np.empty((2,3,5))



array([[[1.8, 1.6, 1.8, 1.1, 1.3],
        [1.4, 1.9, 1.2, 1.2, 1.4],
        [1.8, 1.1, 1.3, 1.9, 1.7]],

       [[1.2, 1.9, 1.1, 1.7, 1.8],
        [1.6, 1.6, 1.9, 1.7, 1.9],
        [1.5, 1.3, 1.6, 1.5, 1.7]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [139]:
# your code here

d = np.array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

d.shape

d_min = np.min(d)
d_max = np.max(d)
d_mean = np.mean(d)

for element in range(2):
    for subelement in range(3):
        for subsub in range(5):
            if (d[element][subelement][subsub] > d_min) & (d[element][subelement][subsub] < d_mean):
                f[element][subelement][subsub] = 25
            elif (d[element][subelement][subsub] > d_mean) & (d[element][subelement][subsub] < d_max):
                f[element][subelement][subsub] = 75
            elif (d[element][subelement][subsub] == d_mean):
                f[element][subelement][subsub] = 50
            elif (d[element][subelement][subsub] == d_min):
                f[element][subelement][subsub] = 0
            elif (d[element][subelement][subsub] == d_max):
                f[element][subelement][subsub] = 100
f
                
            
            
        

array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [140]:
# your code here
print(d)
print(f)

[[[1.85836099 1.67064465 1.62576044 1.40243961 1.88454931]
  [1.75354326 1.69403643 1.36729252 1.61415071 1.12104981]
  [1.72201435 1.1862918  1.87078449 1.7726778  1.88180042]]

 [[1.44747908 1.31673383 1.02000951 1.52218947 1.97066381]
  [1.79129243 1.74983003 1.96028037 1.85166831 1.65450881]
  [1.18068344 1.9587381  1.00656599 1.93402165 1.73514584]]]
[[[ 75.  75.  75.  25.  75.]
  [ 75.  75.  25.  25.  25.]
  [ 75.  25.  75.  75.  75.]]

 [[ 25.  25.  25.  25. 100.]
  [ 75.  75.  75.  75.  75.]
  [ 25.  75.   0.  75.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [143]:
# your code here
f= np.empty((2,3,5),dtype=str)

for element in range(2):
    for subelement in range(3):
        for subsub in range(5):
            if (d[element][subelement][subsub] > d_min) & (d[element][subelement][subsub] < d_mean):
                f[element][subelement][subsub] = 'B'
            elif (d[element][subelement][subsub] > d_mean) & (d[element][subelement][subsub] < d_max):
                f[element][subelement][subsub] = 'D'
            elif (d[element][subelement][subsub] == d_mean):
                f[element][subelement][subsub] = 'C'
            elif (d[element][subelement][subsub] == d_min):
                f[element][subelement][subsub] = 'A'
            elif (d[element][subelement][subsub] == d_max):
                f[element][subelement][subsub] = 'E'
f

array([[['D', 'D', 'D', 'B', 'D'],
        ['D', 'D', 'B', 'B', 'B'],
        ['D', 'B', 'D', 'D', 'D']],

       [['B', 'B', 'B', 'B', 'E'],
        ['D', 'D', 'D', 'D', 'D'],
        ['B', 'D', 'A', 'D', 'D']]], dtype='<U1')