# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [72]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [73]:
# your code here
print(np.__version__)

1.18.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [107]:
# Method 1
a = np.random.random((2,3,5))
a

array([[[0.71213873, 0.62349962, 0.78235194, 0.5552574 , 0.01644977],
        [0.73510526, 0.72071385, 0.41246491, 0.09346386, 0.65013981],
        [0.10747612, 0.92049502, 0.14677122, 0.56767236, 0.19712749]],

       [[0.41649393, 0.47731968, 0.63894744, 0.6686356 , 0.93510448],
        [0.11464139, 0.10700649, 0.38835344, 0.22707903, 0.74507579],
        [0.35492301, 0.40811602, 0.14642585, 0.28050292, 0.77320368]]])

In [94]:
# Method 2
rand = np.random.randint(10,90,(2,3,5))
print(rand)

[[[31 58 32 25 16]
  [70 43 36 65 46]
  [60 32 44 50 64]]

 [[38 18 57 24 80]
  [59 29 64 51 49]
  [46 13 57 57 65]]]


In [95]:
# Method 3

rand_n = np.random.randn(2,3,5)
print(rand_n)

[[[ 2.41752793e+00 -1.26707191e+00 -1.55398840e-01 -9.96391731e-02
   -2.65798244e-01]
  [-3.89342878e-01 -9.66318967e-04  1.69324910e+00 -1.56450878e+00
    7.52404028e-03]
  [ 3.89657182e-01 -7.80321133e-01  1.03073997e+00 -1.21988582e+00
    1.38038516e+00]]

 [[ 1.62226528e+00 -1.07504785e-01 -4.38464821e-01  1.22712103e+00
    3.85941521e-01]
  [ 5.76910520e-01 -1.25335815e+00 -1.19960371e+00  1.04686901e+00
    3.15741448e-01]
  [-1.00883107e+00 -9.89397256e-01  8.64950629e-01 -3.92011653e-01
   -1.60837283e+00]]]


#### 4. Print *a*.


In [108]:
# your code here
print(a)

[[[0.71213873 0.62349962 0.78235194 0.5552574  0.01644977]
  [0.73510526 0.72071385 0.41246491 0.09346386 0.65013981]
  [0.10747612 0.92049502 0.14677122 0.56767236 0.19712749]]

 [[0.41649393 0.47731968 0.63894744 0.6686356  0.93510448]
  [0.11464139 0.10700649 0.38835344 0.22707903 0.74507579]
  [0.35492301 0.40811602 0.14642585 0.28050292 0.77320368]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [97]:
# your code here
b = np.ones([5, 3, 2], dtype=int)   

#### 6. Print *b*.


In [98]:
# your code here
print(b)

[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [99]:
# your code here
np.array_equal(a, b)

False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [100]:
# your answer here
c = a + b

#cannot add arrays with different shapes

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,3,2) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [101]:
# your code here
c = b.transpose()
print(c)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [109]:
# your code/answer here
d = a + c
# same shape

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [ ]:
# your code/answer here

print(a)

print(d)

#each value is increased by one because we did addition which takes one element from one and one from the other and prints the result

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [ ]:
# your code here
e = a*c
print(e)

#### 13. Does *e* equal to *a*? Why or why not?


In [ ]:
# your code/answer here

np.array_equal(e, a)
#e is the result of a*c so it has to have the same shape as a

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [90]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
print(d_min)
d_mean = np.mean(d)
print(d_mean)


1.0130621905210657
1.4229964554417274


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [110]:
# your code here
f = np.empty([2,3,5], dtype=float)
f

array([[[1.55942651, 1.32176956, 1.44806662, 1.50081531, 1.53074664],
        [1.0941795 , 1.30218229, 1.65085628, 1.78426595, 1.3608968 ],
        [1.7803107 , 1.73004236, 1.64591522, 1.88951127, 1.78380615]],

       [[1.93104104, 1.48694791, 1.83634476, 1.78032302, 1.49532506],
        [1.92561416, 1.40814477, 1.64065922, 1.46555106, 1.3243798 ],
        [1.82339023, 1.47333282, 1.72465227, 1.17451029, 1.97468796]]])

In [91]:
d

array([[[1.97933834, 1.14988921, 1.69349306, 1.33543319, 1.19949365],
        [1.70894356, 1.57920233, 1.01306219, 1.50083882, 1.29333909],
        [1.1858911 , 1.39504506, 1.39192524, 1.97882346, 1.77455072]],

       [[1.03730052, 1.07868205, 1.5111067 , 1.05066926, 1.23408659],
        [1.1366883 , 1.24362564, 1.46817279, 1.29015162, 1.67379455],
        [1.36195174, 1.92052382, 1.85382556, 1.09850443, 1.55154108]]])

In [114]:
#f = np.copy(d)
for gr in range(f.shape[0]):
    for li in range(f.shape[1]):
        for val in range(f.shape[2]):
            if (d[gr,li,val] > d_min) & (d[gr,li,val] < d_mean):
                f[gr,li,val] = 25
            elif (d[gr,li,val] > d_mean) & (d[gr,li,val] < d_max):
                f[gr,li,val] = 75
            elif d[gr,li,val] == d_mean:
                f[gr,li,val] = 50
            elif d[gr,li,val] == d_min:
                f[gr,li,val] = 0
            elif d[gr,li,val] == d_max:
                f[gr,li,val] = 100


                
         #   f[gr,li,val]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [115]:
print(f)
print(d)

[[[75. 75. 75. 75. 25.]
  [75. 75. 25. 25. 75.]
  [25. 75. 25. 75. 25.]]

 [[25. 75. 75. 75. 75.]
  [25. 25. 25. 25. 75.]
  [25. 25. 25. 25. 75.]]]
[[[1.71213873 1.62349962 1.78235194 1.5552574  1.01644977]
  [1.73510526 1.72071385 1.41246491 1.09346386 1.65013981]
  [1.10747612 1.92049502 1.14677122 1.56767236 1.19712749]]

 [[1.41649393 1.47731968 1.63894744 1.6686356  1.93510448]
  [1.11464139 1.10700649 1.38835344 1.22707903 1.74507579]
  [1.35492301 1.40811602 1.14642585 1.28050292 1.77320368]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here