# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [4]:
import numpy as np

#### 2. Print your NumPy version.

In [5]:
np.__version__

'1.20.1'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [36]:
import random 
n = random.random() 
print(n)

0.8596909237651145


In [37]:
a = np.random.random(size = (2,3,5))

In [38]:
np.full((2,3,5), random.random())

array([[[0.91806959, 0.91806959, 0.91806959, 0.91806959, 0.91806959],
        [0.91806959, 0.91806959, 0.91806959, 0.91806959, 0.91806959],
        [0.91806959, 0.91806959, 0.91806959, 0.91806959, 0.91806959]],

       [[0.91806959, 0.91806959, 0.91806959, 0.91806959, 0.91806959],
        [0.91806959, 0.91806959, 0.91806959, 0.91806959, 0.91806959],
        [0.91806959, 0.91806959, 0.91806959, 0.91806959, 0.91806959]]])

In [39]:
np.random.random((2,3,5))

array([[[0.43918761, 0.25792257, 0.56698544, 0.88770246, 0.42191916],
        [0.88558858, 0.48904852, 0.99418103, 0.99368276, 0.66655617],
        [0.28179168, 0.34741773, 0.95366194, 0.59998256, 0.86565268]],

       [[0.8593305 , 0.90236158, 0.5872337 , 0.40578249, 0.78230976],
        [0.58952803, 0.32392912, 0.73283029, 0.41414792, 0.44733299],
        [0.09051304, 0.17789226, 0.16558105, 0.2146186 , 0.58032108]]])

#### 4. Print *a*.


In [40]:
print(a)

[[[0.68280185 0.45687441 0.69200707 0.15887363 0.78925768]
  [0.6139505  0.26671251 0.37503242 0.29303005 0.50820139]
  [0.31353804 0.92717044 0.23066288 0.17164697 0.52343843]]

 [[0.99342139 0.34856218 0.46782495 0.1166899  0.78585102]
  [0.82235698 0.04321051 0.58536411 0.082507   0.97043697]
  [0.05097817 0.05551934 0.00310151 0.08080689 0.90554514]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [41]:
b = np.full((5,2,3), 1)

#### 6. Print *b*.


In [42]:
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [43]:
len(a)==len(b)

False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [44]:
a.append(b)
#they have not the same size of columns and rows
#'numpy.ndarray' object has no attribute 'append'

AttributeError: 'numpy.ndarray' object has no attribute 'append'

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [45]:
c = b.reshape(2,3,5)
c

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [46]:
d = a + c
d
#it works, because they have now the same structure

array([[[1.68280185, 1.45687441, 1.69200707, 1.15887363, 1.78925768],
        [1.6139505 , 1.26671251, 1.37503242, 1.29303005, 1.50820139],
        [1.31353804, 1.92717044, 1.23066288, 1.17164697, 1.52343843]],

       [[1.99342139, 1.34856218, 1.46782495, 1.1166899 , 1.78585102],
        [1.82235698, 1.04321051, 1.58536411, 1.082507  , 1.97043697],
        [1.05097817, 1.05551934, 1.00310151, 1.08080689, 1.90554514]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [47]:
print(a)
print(d)
#the arrays have the same strucrure but d has one number more in each position

[[[0.68280185 0.45687441 0.69200707 0.15887363 0.78925768]
  [0.6139505  0.26671251 0.37503242 0.29303005 0.50820139]
  [0.31353804 0.92717044 0.23066288 0.17164697 0.52343843]]

 [[0.99342139 0.34856218 0.46782495 0.1166899  0.78585102]
  [0.82235698 0.04321051 0.58536411 0.082507   0.97043697]
  [0.05097817 0.05551934 0.00310151 0.08080689 0.90554514]]]
[[[1.68280185 1.45687441 1.69200707 1.15887363 1.78925768]
  [1.6139505  1.26671251 1.37503242 1.29303005 1.50820139]
  [1.31353804 1.92717044 1.23066288 1.17164697 1.52343843]]

 [[1.99342139 1.34856218 1.46782495 1.1166899  1.78585102]
  [1.82235698 1.04321051 1.58536411 1.082507   1.97043697]
  [1.05097817 1.05551934 1.00310151 1.08080689 1.90554514]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [48]:
e = a*c
e

array([[[0.68280185, 0.45687441, 0.69200707, 0.15887363, 0.78925768],
        [0.6139505 , 0.26671251, 0.37503242, 0.29303005, 0.50820139],
        [0.31353804, 0.92717044, 0.23066288, 0.17164697, 0.52343843]],

       [[0.99342139, 0.34856218, 0.46782495, 0.1166899 , 0.78585102],
        [0.82235698, 0.04321051, 0.58536411, 0.082507  , 0.97043697],
        [0.05097817, 0.05551934, 0.00310151, 0.08080689, 0.90554514]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [49]:
e == a
#because they have the same structure


array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [50]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(d_max)
print(d_min)
print(d_mean)

1.9934213917542973
1.0031015078234873
1.443845812310652


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [51]:
f = np.empty((2,3,5))
f

array([[[0.68280185, 0.45687441, 0.69200707, 0.15887363, 0.78925768],
        [0.6139505 , 0.26671251, 0.37503242, 0.29303005, 0.50820139],
        [0.31353804, 0.92717044, 0.23066288, 0.17164697, 0.52343843]],

       [[0.99342139, 0.34856218, 0.46782495, 0.1166899 , 0.78585102],
        [0.82235698, 0.04321051, 0.58536411, 0.082507  , 0.97043697],
        [0.05097817, 0.05551934, 0.00310151, 0.08080689, 0.90554514]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [52]:
f[(d_max in d)]= 100
f[(d_min in d )]=0
f[(d > d_min) & (d< d_mean)] = 25
f[(d > d_mean) & (d < d_max)] = 75
f[(d == d_mean)]=50

In [53]:
print(f)

[[[75. 75. 75. 25. 75.]
  [75. 25. 25. 25. 75.]
  [25. 75. 25. 25. 75.]]

 [[ 0. 25. 75. 25. 75.]
  [75. 25. 75. 25. 75.]
  [25. 25.  0. 25. 75.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here