# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [56]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [57]:
# your code here
print(np.__version__)

1.21.6


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [58]:
# Method 1
a = np.random.sample(size=(2,3,5))

print(a)


[[[0.43589356 0.75143214 0.85939307 0.65776187 0.76011045]
  [0.89997975 0.18832961 0.84385042 0.34419506 0.06129113]
  [0.29876626 0.82407758 0.92277807 0.93420204 0.66039465]]

 [[0.76329817 0.69737277 0.40967706 0.9759126  0.0745771 ]
  [0.29595984 0.04922384 0.76572204 0.32926792 0.76820789]
  [0.60438578 0.83083879 0.73504658 0.81787558 0.86696272]]]


In [59]:
a = np.random.randint(100, size = (2,3,5))
print(a)

[[[69  8 87  7 57]
  [87 17 57 26 69]
  [98 28  9 82 28]]

 [[14 94 57 46 38]
  [67 33 83 97 19]
  [ 9 98 10 47 51]]]


In [60]:

a = np.random.random(size=(2,3,5))

print(a)

[[[0.97912552 0.63062069 0.48322617 0.04013556 0.60453071]
  [0.19251799 0.6643125  0.77325803 0.02816087 0.28361563]
  [0.84088713 0.09418897 0.31356481 0.51190156 0.12055931]]

 [[0.04462924 0.22528526 0.0258587  0.70798016 0.29841503]
  [0.54106406 0.02240927 0.14081269 0.11653198 0.08997294]
  [0.44456006 0.26590443 0.59891482 0.32479383 0.82619321]]]


#### 4. Print *a*.


In [61]:
# your code here
print(a)
print(a.shape)

[[[0.97912552 0.63062069 0.48322617 0.04013556 0.60453071]
  [0.19251799 0.6643125  0.77325803 0.02816087 0.28361563]
  [0.84088713 0.09418897 0.31356481 0.51190156 0.12055931]]

 [[0.04462924 0.22528526 0.0258587  0.70798016 0.29841503]
  [0.54106406 0.02240927 0.14081269 0.11653198 0.08997294]
  [0.44456006 0.26590443 0.59891482 0.32479383 0.82619321]]]
(2, 3, 5)


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [62]:
b = np.ones(shape=(5,2,3))



#### 6. Print *b*.


In [63]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [64]:
if a.shape == b.shape:
    print('the arrays are the same size')
else:
    print('dimentions are not the same')

dimentions are not the same


#### 8. Are you able to add *a* and *b*? Why or why not?


In [65]:
try:
    np.add(a,b)
except ValueError:
    print("operation not possible, different dimentions")

operation not possible, different dimentions


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [66]:
# your code here
c = np.transpose(b, (1,2,0))
print(c.shape)
print(a.shape)

(2, 3, 5)
(2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [67]:
d = np.add(a, c)
print("they have the same shape")

they have the same shape


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [68]:
print(a)
print('----')
print(d)

# the values from a were added to c

[[[0.97912552 0.63062069 0.48322617 0.04013556 0.60453071]
  [0.19251799 0.6643125  0.77325803 0.02816087 0.28361563]
  [0.84088713 0.09418897 0.31356481 0.51190156 0.12055931]]

 [[0.04462924 0.22528526 0.0258587  0.70798016 0.29841503]
  [0.54106406 0.02240927 0.14081269 0.11653198 0.08997294]
  [0.44456006 0.26590443 0.59891482 0.32479383 0.82619321]]]
----
[[[1.97912552 1.63062069 1.48322617 1.04013556 1.60453071]
  [1.19251799 1.6643125  1.77325803 1.02816087 1.28361563]
  [1.84088713 1.09418897 1.31356481 1.51190156 1.12055931]]

 [[1.04462924 1.22528526 1.0258587  1.70798016 1.29841503]
  [1.54106406 1.02240927 1.14081269 1.11653198 1.08997294]
  [1.44456006 1.26590443 1.59891482 1.32479383 1.82619321]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [69]:
# your code here

e = np.multiply(a,c)

print(e)

[[[0.97912552 0.63062069 0.48322617 0.04013556 0.60453071]
  [0.19251799 0.6643125  0.77325803 0.02816087 0.28361563]
  [0.84088713 0.09418897 0.31356481 0.51190156 0.12055931]]

 [[0.04462924 0.22528526 0.0258587  0.70798016 0.29841503]
  [0.54106406 0.02240927 0.14081269 0.11653198 0.08997294]
  [0.44456006 0.26590443 0.59891482 0.32479383 0.82619321]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [70]:
print(a == e)

# E is the result of a multiplied buy C. C is result of transpose B. B is a "ones" array. so the multiplication is values from a multiplied by 1. 

[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [71]:
print(f'max value of "d" is {np.max(d)}')
print(f'min value of "d" is {np.min(d)}')
print(f'mean value of "d" is {np.mean(d)}')

max value of "d" is 1.9791255171845976
min value of "d" is 1.0224092687521098
mean value of "d" is 1.3744643712094642


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [72]:
# your code 
f = np.empty((2,3,5))

print(f)

[[[0.97912552 0.63062069 0.48322617 0.04013556 0.60453071]
  [0.19251799 0.6643125  0.77325803 0.02816087 0.28361563]
  [0.84088713 0.09418897 0.31356481 0.51190156 0.12055931]]

 [[0.04462924 0.22528526 0.0258587  0.70798016 0.29841503]
  [0.54106406 0.02240927 0.14081269 0.11653198 0.08997294]
  [0.44456006 0.26590443 0.59891482 0.32479383 0.82619321]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [73]:
for i, item in enumerate(d):
    for si, sub_item in enumerate(item):
        for ssi, ssub_item in enumerate(sub_item):
            if np.min(d) < ssub_item < np.mean(d):
                f[i][si][ssi] = 25
            elif np.mean(d) < ssub_item < np.max(d):
                f[i][si][ssi] = 75
            elif ssub_item == np.mean(d):
                f[i][si][ssi] = 50
            elif ssub_item == np.min(d):
                f[i][si][ssi] = 0
            elif ssub_item == np.max(d):
                f[i][si][ssi] = 100

print(f)

[[[100.  75.  75.  25.  75.]
  [ 25.  75.  75.  25.  25.]
  [ 75.  25.  25.  75.  25.]]

 [[ 25.  25.  25.  75.  25.]
  [ 75.   0.  25.  25.  25.]
  [ 75.  25.  75.  25.  75.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [74]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [75]:
# your code here
f = np.empty((2,3,5), dtype=object)


for i, item in enumerate(d):
    for si, sub_item in enumerate(item):
        for ssi, ssub_item in enumerate(sub_item):
            if np.min(d) < ssub_item < np.mean(d):
                f[i][si][ssi] = "B"
            elif np.mean(d) < ssub_item < np.max(d):
                f[i][si][ssi] = "C"
            elif ssub_item == np.mean(d):
                f[i][si][ssi] = "D"
            elif ssub_item == np.min(d):
                f[i][si][ssi] = "A"
            elif ssub_item == np.max(d):
                f[i][si][ssi] = "E"

print(f)

[[['E' 'C' 'C' 'B' 'C']
  ['B' 'C' 'C' 'B' 'B']
  ['C' 'B' 'B' 'C' 'B']]

 [['B' 'B' 'B' 'C' 'B']
  ['C' 'A' 'B' 'B' 'B']
  ['C' 'B' 'C' 'B' 'C']]]
