# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [33]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [34]:
# your code here
print(np.__version__)

1.18.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [35]:
# Method 1
a = np.random.random((2, 3, 5))
a

array([[[0.87168059, 0.85519852, 0.3277511 , 0.78694983, 0.99675027],
        [0.72512239, 0.4199359 , 0.81106099, 0.82816995, 0.50518826],
        [0.32447349, 0.50447012, 0.93504163, 0.91955065, 0.21785995]],

       [[0.79956835, 0.79679953, 0.9301846 , 0.62921308, 0.19022706],
        [0.53087749, 0.29902353, 0.68766847, 0.41584048, 0.6422458 ],
        [0.57815905, 0.31740337, 0.76498707, 0.96037315, 0.58638103]]])

In [36]:
# Method 2
a2 = np.random.rand(2, 3, 5)
a2

array([[[0.54697551, 0.90660611, 0.96062445, 0.54397843, 0.69071178],
        [0.5803701 , 0.6472441 , 0.91771607, 0.10508556, 0.86579241],
        [0.80206584, 0.42236296, 0.93688259, 0.56155189, 0.80083929]],

       [[0.93980668, 0.55054783, 0.86345282, 0.10477895, 0.38344104],
        [0.38501488, 0.51037244, 0.23756548, 0.70624502, 0.47619574],
        [0.548442  , 0.88542363, 0.17306609, 0.00678901, 0.04681045]]])

In [37]:
# Method 3
a3 = np.random.sample((2, 3, 5))
a3

array([[[0.40902884, 0.96718353, 0.25434813, 0.92129509, 0.94310643],
        [0.9336804 , 0.34090795, 0.06762212, 0.87875411, 0.28698404],
        [0.82600936, 0.13288875, 0.11886806, 0.79906489, 0.41591371]],

       [[0.10581123, 0.56441162, 0.83141549, 0.43576132, 0.54446687],
        [0.12473125, 0.6381086 , 0.70356619, 0.23634458, 0.2876001 ],
        [0.03882927, 0.99876441, 0.26884889, 0.67498926, 0.92798151]]])

In [71]:
# Method 4
a4 = np.random.randint(1,38439582,(2,3,5))
a4

array([[[10155980, 30527090,  4616690, 32263086, 32321247],
        [25022577,  6901809, 26345288, 35687192,  1901439],
        [ 2421813, 27245353, 29363455, 31802435, 35365033]],

       [[14381196, 20863543,  7111597, 25338407, 12197531],
        [36285308,  9050252, 16767950, 14362845, 19775634],
        [18698240, 16789988,  9535211, 31798665, 31864124]]])

#### 4. Print *a*.


In [39]:
# your code here
print(a)

[[[0.87168059 0.85519852 0.3277511  0.78694983 0.99675027]
  [0.72512239 0.4199359  0.81106099 0.82816995 0.50518826]
  [0.32447349 0.50447012 0.93504163 0.91955065 0.21785995]]

 [[0.79956835 0.79679953 0.9301846  0.62921308 0.19022706]
  [0.53087749 0.29902353 0.68766847 0.41584048 0.6422458 ]
  [0.57815905 0.31740337 0.76498707 0.96037315 0.58638103]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [43]:
# your code here
b = np.ones((5, 2, 3), dtype = int)

#### 6. Print *b*.


In [44]:
# your code here
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [46]:
# your code here
print(a.size == b.size)
print("Yes. They do have the same size.")

True
Yes. They do have the same size.


#### 8. Are you able to add *a* and *b*? Why or why not?


In [52]:
# your answer here

#a + b
print("No, I'm not able to add them together because they do not have the same shape.")

No, I'm not able to add them together because they do not have the same shape.


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [60]:
# your code here
c = b.transpose(1,2,0) # we have to add the axis 1,2,0 so it knows the order to transpose
print(c.shape)

(2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [77]:
# your code/answer here
d = a + c
d
# Now it works because they have the same shape

array([[[1.87168059, 1.85519852, 1.3277511 , 1.78694983, 1.99675027],
        [1.72512239, 1.4199359 , 1.81106099, 1.82816995, 1.50518826],
        [1.32447349, 1.50447012, 1.93504163, 1.91955065, 1.21785995]],

       [[1.79956835, 1.79679953, 1.9301846 , 1.62921308, 1.19022706],
        [1.53087749, 1.29902353, 1.68766847, 1.41584048, 1.6422458 ],
        [1.57815905, 1.31740337, 1.76498707, 1.96037315, 1.58638103]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [63]:
# your code/answer here
print("Array 'a':\n", a)
print("\n")

# print("Array 'b':\n", b) # b was just an array of ones
# print("\n")

print("Array 'c':\n", c) # c is b transposed to match 'a' so that we could later add them together
print("\n")

print("Array 'd':\n", d) # d is a + c, therefore d consists of just adding +1 to the array a

Array 'a':
 [[[0.87168059 0.85519852 0.3277511  0.78694983 0.99675027]
  [0.72512239 0.4199359  0.81106099 0.82816995 0.50518826]
  [0.32447349 0.50447012 0.93504163 0.91955065 0.21785995]]

 [[0.79956835 0.79679953 0.9301846  0.62921308 0.19022706]
  [0.53087749 0.29902353 0.68766847 0.41584048 0.6422458 ]
  [0.57815905 0.31740337 0.76498707 0.96037315 0.58638103]]]


Array 'c':
 [[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


Array 'd':
 [[[1.87168059 1.85519852 1.3277511  1.78694983 1.99675027]
  [1.72512239 1.4199359  1.81106099 1.82816995 1.50518826]
  [1.32447349 1.50447012 1.93504163 1.91955065 1.21785995]]

 [[1.79956835 1.79679953 1.9301846  1.62921308 1.19022706]
  [1.53087749 1.29902353 1.68766847 1.41584048 1.6422458 ]
  [1.57815905 1.31740337 1.76498707 1.96037315 1.58638103]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [64]:
# your code here
e = a * c
e

array([[[0.87168059, 0.85519852, 0.3277511 , 0.78694983, 0.99675027],
        [0.72512239, 0.4199359 , 0.81106099, 0.82816995, 0.50518826],
        [0.32447349, 0.50447012, 0.93504163, 0.91955065, 0.21785995]],

       [[0.79956835, 0.79679953, 0.9301846 , 0.62921308, 0.19022706],
        [0.53087749, 0.29902353, 0.68766847, 0.41584048, 0.6422458 ],
        [0.57815905, 0.31740337, 0.76498707, 0.96037315, 0.58638103]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [67]:
# your code/answer here
np.array_equal(e, a)

# Yes, it does equal to a, because c is the transpose of b, so we're essentially just multiplying a by 1

True

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [72]:
# your code here
d_max = np.amax(d)
d_min = np.amin(d)
d_mean = np.mean(d)

print("Max. value:", d_max, "\n" "Min. value:", d_min, "\n" "Mean value:", d_mean)

Max. value: 1.9967502723604307 
Min. value: 1.1902270635232424 
Mean value: 1.6386051907711976


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [80]:
# your code here
f = np.empty((2,3,5))
f

array([[[1.87168059, 1.85519852, 1.3277511 , 1.78694983, 1.99675027],
        [1.72512239, 1.4199359 , 1.81106099, 1.82816995, 1.50518826],
        [1.32447349, 1.50447012, 1.93504163, 1.91955065, 1.21785995]],

       [[1.79956835, 1.79679953, 1.9301846 , 1.62921308, 1.19022706],
        [1.53087749, 1.29902353, 1.68766847, 1.41584048, 1.6422458 ],
        [1.57815905, 1.31740337, 1.76498707, 1.96037315, 1.58638103]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [81]:
# your code here


# Needed help in this one. Beatriz helped me out by showing her code which was the same as Marie's.

#for understanding purposes
#for x in range(d.shape[0]): 
#    for y in range(d.shape[1]):
#        for z in range(d.shape[2]):
#            print([x,y,z])
        
for x in range(d.shape[0]): # We're asking for the index 0, which in the shape (2, 3, 5) is 2 -> numb of sets
    for y in range(d.shape[1]): # Rows
        for z in range(d.shape[2]): # Columns
            if d[x,y,z] > d_min and d[x,y,z] < d_mean:
                f[x,y,z] = 25
            elif d[x,y,z] > d_mean and d[x,y,z] < d_max:
                f[x,y,z] = 75
            elif d[x,y,z] == d_mean:
                f[x,y,z] = 50
            elif d[x,y,z] == d_max:
                f[x,y,z] = 100
            else:
                f[x,y,z] = 0
print(f)
    
#i in d if d_min < i < d_mean, i =25
#i in d if d_mean < i < d_max, i =75
#i in d if i == d_mean, i = 50
#d_min = 0
#d_max = 100


[[[ 75.  75.  25.  75. 100.]
  [ 75.  25.  75.  75.  25.]
  [ 25.  25.  75.  75.  25.]]

 [[ 75.  75.  75.  25.   0.]
  [ 25.  25.  75.  25.  75.]
  [ 25.  25.  75.  75.  25.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [83]:
# your code here
print(d)
print('\n')
print(f)

[[[1.87168059 1.85519852 1.3277511  1.78694983 1.99675027]
  [1.72512239 1.4199359  1.81106099 1.82816995 1.50518826]
  [1.32447349 1.50447012 1.93504163 1.91955065 1.21785995]]

 [[1.79956835 1.79679953 1.9301846  1.62921308 1.19022706]
  [1.53087749 1.29902353 1.68766847 1.41584048 1.6422458 ]
  [1.57815905 1.31740337 1.76498707 1.96037315 1.58638103]]]


[[[ 75.  75.  25.  75. 100.]
  [ 75.  25.  75.  75.  25.]
  [ 25.  25.  75.  75.  25.]]

 [[ 75.  75.  75.  25.   0.]
  [ 25.  25.  75.  25.  75.]
  [ 25.  25.  75.  75.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [84]:
# your code here

#arr = np.array([-3-2-1,0,1,2,3,4,5,6])
#new_arr = np.zeros(shape = arr.shape, dtype=np.str)

#new_arr[(arr>3)] = 'S'
#new_arr[((arr>=-3) & (arr<=-1))] = 'F'
#new_arr[((arr>=0)&(arr<=3))] = 'M'
#new_arr
#array(['', 'M', 'M', 'M', 'M', 'S', 'S', 'S'], dtype='<U1')

#for understanding purposes

new_arrf = np.zeros(shape = f.shape, dtype=np.str)
for x in range(f.shape[0]):  
    for y in range(f.shape[1]):
        for z in range(f.shape[2]):
            if f[x,y,z] == 25:
                new_arrf[x,y,z] = 'B'
            elif f[x,y,z] == 75:
                new_arrf[x,y,z] = 'D'
            elif f[x,y,z] == 50:
                new_arrf[x,y,z] = 'C'
            elif f[x,y,z] == 50:
                new_arrf[x,y,z] = 'A'
            else:
                new_arrf[x,y,z] = 'E'
print(new_arrf)
    
#i in d if d_min < i < d_mean, i =25
#i in d if d_mean < i < d_max, i =75
#i in d if i == d_mean, i = 50
#d_min = 0
#d_max = 100

[[['D' 'D' 'B' 'D' 'E']
  ['D' 'B' 'D' 'D' 'B']
  ['B' 'B' 'D' 'D' 'B']]

 [['D' 'D' 'D' 'B' 'E']
  ['B' 'B' 'D' 'B' 'D']
  ['B' 'B' 'D' 'D' 'B']]]
