# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [124]:
import numpy as np

#### 2. Print your NumPy version.

In [126]:
print(np.__version__)

1.19.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
from numpy import random
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [127]:
from numpy import random

a = np.random.randint(0, 100, size=(2, 3, 5))

In [128]:
# Method 2

In [129]:
# Method 3

#### 4. Print *a*.


In [130]:
print(a)

[[[35 48 72  5 16]
  [36 66 68 55 74]
  [39 10 15 95  1]]

 [[ 5 25 23 39 45]
  [88 91 62 40 50]
  [39 50 92 82 18]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [131]:
b = np.ones((5, 3, 2))

#b = np.zeros((5, 3, 2))

#b = np.where(b==0, 1, b)

#### 6. Print *b*.


In [132]:
print(b)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [133]:
print(a.shape)

print(b.shape)

(2, 3, 5)
(5, 3, 2)


#### 8. Are you able to add *a* and *b*? Why or why not?


In [134]:
#No, because the shapes don´t match.

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [135]:
c = np.transpose(b)

print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [136]:
d = np.add(a,c)

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [137]:
print(a)

[[[35 48 72  5 16]
  [36 66 68 55 74]
  [39 10 15 95  1]]

 [[ 5 25 23 39 45]
  [88 91 62 40 50]
  [39 50 92 82 18]]]


In [138]:
print(d)

d.shape

[[[36. 49. 73.  6. 17.]
  [37. 67. 69. 56. 75.]
  [40. 11. 16. 96.  2.]]

 [[ 6. 26. 24. 40. 46.]
  [89. 92. 63. 41. 51.]
  [40. 51. 93. 83. 19.]]]


(2, 3, 5)

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [139]:
e = np.multiply(a,c)

e

array([[[35., 48., 72.,  5., 16.],
        [36., 66., 68., 55., 74.],
        [39., 10., 15., 95.,  1.]],

       [[ 5., 25., 23., 39., 45.],
        [88., 91., 62., 40., 50.],
        [39., 50., 92., 82., 18.]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [140]:
#Because it multiplies each index corresponded element to the other

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [141]:
d_mean = np.mean(d)
d_max = np.amax(d)
d_min = np.amin(d)

print(d_mean)
print(d_max)
print(d_min)

47.13333333333333
96.0
2.0


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [150]:
f = np.empty([2,3,5])

print(f)

[[[35. 48. 72.  5. 16.]
  [36. 66. 68. 55. 74.]
  [ 2.  2.  2.  2.  2.]]

 [[ 5. 25. 23. 39. 45.]
  [88. 91. 62. 40. 50.]
  [ 2.  2.  2.  2.  2.]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [148]:
# I spent two hours on this, and couldn't do it. Sorry.

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# This depends on the last one.

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here