# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [11]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [12]:
# your code here
print(np.__version__)

1.21.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [13]:
# Method 1
a = np.random.random(size = (2,3,5))
a

array([[[0.66536148, 0.29245678, 0.83563423, 0.55237304, 0.91975499],
        [0.05131494, 0.5864381 , 0.65968284, 0.17890602, 0.3815296 ],
        [0.78020314, 0.14256638, 0.38964225, 0.50084246, 0.31902153]],

       [[0.2465774 , 0.92443592, 0.85669106, 0.88672312, 0.8810249 ],
        [0.9041104 , 0.37042173, 0.59571544, 0.30522661, 0.48931655],
        [0.21305138, 0.98276336, 0.46789973, 0.87599076, 0.16069003]]])

In [14]:
# Method 2
a = np.random.rand(2,3,5)
a

array([[[0.42476348, 0.30031313, 0.98539975, 0.67030128, 0.24983073],
        [0.88602157, 0.40964455, 0.89939308, 0.09946825, 0.75423002],
        [0.47914147, 0.40656387, 0.969349  , 0.58586148, 0.5092982 ]],

       [[0.4530604 , 0.26408613, 0.78403827, 0.87009994, 0.56476561],
        [0.02117219, 0.7763562 , 0.11359528, 0.22844845, 0.3824505 ],
        [0.10263167, 0.48483418, 0.01620143, 0.8391797 , 0.04989422]]])

In [15]:
# Method 3

#### 4. Print *a*.


In [16]:
# your code here
print(a)

[[[0.42476348 0.30031313 0.98539975 0.67030128 0.24983073]
  [0.88602157 0.40964455 0.89939308 0.09946825 0.75423002]
  [0.47914147 0.40656387 0.969349   0.58586148 0.5092982 ]]

 [[0.4530604  0.26408613 0.78403827 0.87009994 0.56476561]
  [0.02117219 0.7763562  0.11359528 0.22844845 0.3824505 ]
  [0.10263167 0.48483418 0.01620143 0.8391797  0.04989422]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [17]:
# your code here
b = np.ones(shape = (5,2,3), dtype = int)


#### 6. Print *b*.


In [18]:
# your code here
print(b)


[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [19]:
# your code here
np.size(a) == np.size(b)

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [20]:
# your answer here
a+b
# We are not able to add them since their shape is not the same

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [21]:
# your code here
c = b.reshape(2,3,5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [22]:
# your code/answer here
d = a+c
#because the two arrays are the same shape now

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [23]:
# your code/answer here
print(d)
# the item in a certain position in the arrays were added so we see a new array with all those values summed

[[[1.42476348 1.30031313 1.98539975 1.67030128 1.24983073]
  [1.88602157 1.40964455 1.89939308 1.09946825 1.75423002]
  [1.47914147 1.40656387 1.969349   1.58586148 1.5092982 ]]

 [[1.4530604  1.26408613 1.78403827 1.87009994 1.56476561]
  [1.02117219 1.7763562  1.11359528 1.22844845 1.3824505 ]
  [1.10263167 1.48483418 1.01620143 1.8391797  1.04989422]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [24]:
# your code here
e = a*c
e

array([[[0.42476348, 0.30031313, 0.98539975, 0.67030128, 0.24983073],
        [0.88602157, 0.40964455, 0.89939308, 0.09946825, 0.75423002],
        [0.47914147, 0.40656387, 0.969349  , 0.58586148, 0.5092982 ]],

       [[0.4530604 , 0.26408613, 0.78403827, 0.87009994, 0.56476561],
        [0.02117219, 0.7763562 , 0.11359528, 0.22844845, 0.3824505 ],
        [0.10263167, 0.48483418, 0.01620143, 0.8391797 , 0.04989422]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [25]:
# your code/answer here
e == a
# It is equal because all the values of c are the transposed values of b which were all 1. 
# Since e = a multiplied by c, all the values in a were mutiplied by one so they stayed the same

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [26]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [34]:
# your code here
f = np.empty(shape = (2,3,5))
print(f)

[[[0.42476348 0.30031313 0.98539975 0.67030128 0.24983073]
  [0.88602157 0.40964455 0.89939308 0.09946825 0.75423002]
  [0.47914147 0.40656387 0.969349   0.58586148 0.5092982 ]]

 [[0.4530604  0.26408613 0.78403827 0.87009994 0.56476561]
  [0.02117219 0.7763562  0.11359528 0.22844845 0.3824505 ]
  [0.10263167 0.48483418 0.01620143 0.8391797  0.04989422]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [36]:
# your code here
f[(d > d_min) & (d < d_mean)] = 25
f[(d < d_max) & (d > d_mean)] = 50
f[d == d_max] = 100
f[d == d_min] = 0
f[d == d_mean] = 50

# 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [37]:
# your code here
print(d)
print(f)

[[[1.42476348 1.30031313 1.98539975 1.67030128 1.24983073]
  [1.88602157 1.40964455 1.89939308 1.09946825 1.75423002]
  [1.47914147 1.40656387 1.969349   1.58586148 1.5092982 ]]

 [[1.4530604  1.26408613 1.78403827 1.87009994 1.56476561]
  [1.02117219 1.7763562  1.11359528 1.22844845 1.3824505 ]
  [1.10263167 1.48483418 1.01620143 1.8391797  1.04989422]]]
[[[ 25.  25. 100.  50.  25.]
  [ 50.  25.  50.  25.  50.]
  [ 25.  25.  50.  50.  50.]]

 [[ 25.  25.  50.  50.  50.]
  [ 25.  50.  25.  25.  25.]
  [ 25.  25.   0.  50.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [39]:
# your code here
f[(d > d_min) & (d < d_mean)] = "B"
f[(d < d_max) & (d > d_mean)] = "D"
f[d == d_max] = "E"
f[d == d_min] = "A"
f[d == d_mean] = "C"

print(f)

ValueError: could not convert string to float: 'B'