# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [36]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [37]:
# your code here
np.__version__

'1.20.3'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [38]:
# Method 1
a = np.random.random(size=(2,3,5))

In [39]:
# Method 2
a = np.random.rand(2,3,5)

In [40]:
# Method 3
a = np.random.randint(0,100,(2,3,5))

#### 4. Print *a*.


In [41]:
# your code here
print(a)

[[[34 70 10 80 79]
  [82  0 19 65 46]
  [65 62 55 78 32]]

 [[60 87 17 93 68]
  [28 72  7 79 67]
  [26 87 80 14 89]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [42]:
# your code here
b = np.ones(shape=(5,2,3))

#### 6. Print *b*.


In [43]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [44]:
# your code here
if a.shape == b.shape:
    print("They have the same shape!")
else:
    print(f"They have different shapes.\nShape of array 'a': {a.shape}\nShape of array 'b': {b.shape}")

They have different shapes.
Shape of array 'a': (2, 3, 5)
Shape of array 'b': (5, 2, 3)


#### 8. Are you able to add *a* and *b*? Why or why not?


In [45]:
# your answer here
try:
    a+b
except ValueError:
    print("Can only add arrays with common shapes.")

Can only add arrays with common shapes.


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [46]:
# your code here
print(b.shape)
c = np.transpose(b, axes=(1,2,0))


(5, 2, 3)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [47]:
# your code/answer here
d = a + c
d
# Now it works because they both have the same shape.

array([[[35., 71., 11., 81., 80.],
        [83.,  1., 20., 66., 47.],
        [66., 63., 56., 79., 33.]],

       [[61., 88., 18., 94., 69.],
        [29., 73.,  8., 80., 68.],
        [27., 88., 81., 15., 90.]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [48]:
# your code/answer here
print(f"'a': {a}\n'd': {d}")
print("They have the same shape and 'd' is the same as 'a' with each value incremented by 1 (because 'c' is an array of ones)")

'a': [[[34 70 10 80 79]
  [82  0 19 65 46]
  [65 62 55 78 32]]

 [[60 87 17 93 68]
  [28 72  7 79 67]
  [26 87 80 14 89]]]
'd': [[[35. 71. 11. 81. 80.]
  [83.  1. 20. 66. 47.]
  [66. 63. 56. 79. 33.]]

 [[61. 88. 18. 94. 69.]
  [29. 73.  8. 80. 68.]
  [27. 88. 81. 15. 90.]]]
They have the same shape and 'd' is the same as 'a' with each value incremented by 1 (because 'c' is an array of ones)


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [49]:
# your code here
e = a * c

#### 13. Does *e* equal to *a*? Why or why not?


In [50]:
# your code/answer here
print(f"'e': {e}\na: {a}")
print("Yes, they are equal, as we just multiplied each element of 'a' by 1.")

'e': [[[34. 70. 10. 80. 79.]
  [82.  0. 19. 65. 46.]
  [65. 62. 55. 78. 32.]]

 [[60. 87. 17. 93. 68.]
  [28. 72.  7. 79. 67.]
  [26. 87. 80. 14. 89.]]]
a: [[[34 70 10 80 79]
  [82  0 19 65 46]
  [65 62 55 78 32]]

 [[60 87 17 93 68]
  [28 72  7 79 67]
  [26 87 80 14 89]]]
Yes, they are equal, as we just multiplied each element of 'a' by 1.


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [51]:
# your code here
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [52]:
# your code here
f = np.empty(shape=(2,3,5))
f[:] = np.NaN
f

array([[[nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan]],

       [[nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [56]:
# your code here
condition1 = (d > d_min) & (d < d_mean)
condition2 = (d > d_mean) & (d < d_max)
condition3 = (d == d_mean)
condition4 = (d == d_min)
condition5 = (d == d_max)

f[condition1] = 25
f[condition2] = 75
f[condition3] = 50
f[condition4] = 0
f[condition5] = 100
f



array([[[ 25.,  75.,  25.,  75.,  75.],
        [ 75.,   0.,  25.,  75.,  25.],
        [ 75.,  75.,  25.,  75.,  25.]],

       [[ 75.,  75.,  25., 100.,  75.],
        [ 25.,  75.,  25.,  75.,  75.],
        [ 25.,  75.,  75.,  25.,  75.]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [59]:
# your code here
print(d)
print(f)

[[[35. 71. 11. 81. 80.]
  [83.  1. 20. 66. 47.]
  [66. 63. 56. 79. 33.]]

 [[61. 88. 18. 94. 69.]
  [29. 73.  8. 80. 68.]
  [27. 88. 81. 15. 90.]]]
[[[ 25.  75.  25.  75.  75.]
  [ 75.   0.  25.  75.  25.]
  [ 75.  75.  25.  75.  25.]]

 [[ 75.  75.  25. 100.  75.]
  [ 25.  75.  25.  75.  75.]
  [ 25.  75.  75.  25.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [64]:
# your code here
def bonus_question(my_array):
    if my_array == 0:
        return "A"
    elif my_array == 25:
        return "B"
    elif my_array == 50:
        return "C"
    elif my_array == 75:
        return "D"
    elif my_array == 100:
        return "E"
    else:
        return None

vectorize_bonus = np.vectorize(bonus_question)
vectorize_bonus(f)


array([[['B', 'D', 'B', 'D', 'D'],
        ['D', 'A', 'B', 'D', 'B'],
        ['D', 'D', 'B', 'D', 'B']],

       [['D', 'D', 'B', 'E', 'D'],
        ['B', 'D', 'B', 'D', 'D'],
        ['B', 'D', 'D', 'B', 'D']]], dtype='<U1')