# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [2]:
np.__version__

'1.21.6'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [20]:
# Method 
a = np.random.rand(2, 3, 5)

In [21]:
# Method 2
a = np.random.randn(2, 3, 5)

In [22]:
# Method 3
a = np.random.randint(1, 99, size=(2, 3, 5))

#### 4. Print *a*.


In [23]:
# your code here
print(a)

[[[62 78 10 63 39]
  [64  3 98 58 49]
  [65 20 88 92 60]]

 [[64 11 30 72 21]
  [49 45 40 48 41]
  [73 73 43 32 14]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [35]:
# your code here 
b = np.ones((5, 3, 2))

#### 6. Print *b*.


In [36]:
print(b)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [37]:
# your code here
a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [38]:
# your answer here
print("The shape of a is: ", a.shape)
print("The shape of b is: ", b.shape)

The shape of a is:  (2, 3, 5)
The shape of b is:  (5, 3, 2)


In [39]:
a+b

ValueError: ignored

As we can see the shape of both the arrays are different so we can not braodcast on each other, and hence addition operator isn't working.

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [41]:
# your code here
c = b.T

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [42]:
# your code/answer here
# your answer here
print("The shape of a is: ", a.shape)
print("The shape of c is: ", c.shape)

The shape of a is:  (2, 3, 5)
The shape of c is:  (2, 3, 5)


In [44]:
d = a+c

As we can see the shape of both 'a' and 'c' are same so we can easily broadcast on each other and, hence are able to perform addition.

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [45]:
# your code/answer here
print(a)

[[[62 78 10 63 39]
  [64  3 98 58 49]
  [65 20 88 92 60]]

 [[64 11 30 72 21]
  [49 45 40 48 41]
  [73 73 43 32 14]]]


In [46]:
print(d)

[[[63. 79. 11. 64. 40.]
  [65.  4. 99. 59. 50.]
  [66. 21. 89. 93. 61.]]

 [[65. 12. 31. 73. 22.]
  [50. 46. 41. 49. 42.]
  [74. 74. 44. 33. 15.]]]


As can be seen clearly that the values in array 'd' is one more than the value of a

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [48]:
# your code here
e = a*c
print(e)

[[[62. 78. 10. 63. 39.]
  [64.  3. 98. 58. 49.]
  [65. 20. 88. 92. 60.]]

 [[64. 11. 30. 72. 21.]
  [49. 45. 40. 48. 41.]
  [73. 73. 43. 32. 14.]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [49]:
# your code/answer here
print(e == a)

[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]


Yes 'e' is equal to 'a' and as can be seen when did e==a we can see True at all the places.

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [51]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [63]:
# your code here
f = np.empty(shape=(2,3,5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [64]:
# your code here
for i in range(2):
  for j in range(3):
    for k in range(5):
      if d[i, j, k] > d_min and d[i, j, k] < d_mean:
        f[i, j, k] = 25
      elif d[i, j, k] > d_mean and d[i, j, k] < d_max:
        f[i, j, k] = 75
      elif d[i, j, k] == d_mean:
        f[i, j, k] = 50
      elif d[i, j, k] == d_min:
        f[i, j, k] = 0
      elif d[i, j, k] == d_max:
        f[i, j, k] = 100

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [65]:
# your code here
print(d)

[[[63. 79. 11. 64. 40.]
  [65.  4. 99. 59. 50.]
  [66. 21. 89. 93. 61.]]

 [[65. 12. 31. 73. 22.]
  [50. 46. 41. 49. 42.]
  [74. 74. 44. 33. 15.]]]


In [66]:
print(f)

[[[ 75.  75.  25.  75.  25.]
  [ 75.   0. 100.  75.  25.]
  [ 75.  25.  75.  75.  75.]]

 [[ 75.  25.  25.  75.  25.]
  [ 25.  25.  25.  25.  25.]
  [ 75.  75.  25.  25.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [67]:
# your code here
f = f.astype(int)
f = f.astype(str)
for i in range(2):
  for j in range(3):
    for k in range(5):
      if f[i, j, k] == '0':
        f[i, j, k] = 'A'
      elif f[i, j, k] == '25':
        f[i, j, k] = 'B'
      elif f[i, j, k] == '50':
        f[i, j, k] = 'C'
      elif f[i, j, k] == '75':
        f[i, j, k] = 'D'
      elif f[i, j, k] == '100':
        f[i, j, k] = 'E'

In [68]:
print(f)

[[['D' 'D' 'B' 'D' 'B']
  ['D' 'A' 'E' 'D' 'B']
  ['D' 'B' 'D' 'D' 'D']]

 [['D' 'B' 'B' 'D' 'B']
  ['B' 'B' 'B' 'B' 'B']
  ['D' 'D' 'B' 'B' 'B']]]
