# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here

import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here

print(np.version.version)

1.19.0


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a = np.random.random((2,3,5))
print(a)

a.ndim
a.shape

[[[0.46426932 0.43968398 0.82237227 0.17123957 0.84325794]
  [0.80850699 0.74941093 0.90384097 0.59997834 0.18202827]
  [0.75494576 0.12418605 0.72859877 0.92722081 0.46657859]]

 [[0.17926235 0.98643458 0.93552288 0.44175274 0.62793066]
  [0.8322141  0.84395082 0.88220845 0.64738753 0.67569495]
  [0.73762764 0.41686484 0.9966783  0.72975932 0.70388578]]]


(2, 3, 5)

In [4]:
# Method 2
met_2 = np.random.randint(0, 100, size=(2, 3, 5))
print(met_2)

met_2.ndim

[[[ 0 31 48 68 14]
  [61 35 58 59 69]
  [ 9 40  6  6 60]]

 [[17 43 16 42  2]
  [74 89 82 67 69]
  [39 28 15 59 17]]]


3

In [5]:
# Method 3
met_3 = np.random.rand(2,3,5)
print(met_3)

met_3.ndim

[[[0.26981603 0.76816736 0.72528911 0.80689702 0.80201607]
  [0.25468077 0.4316864  0.64215035 0.35263914 0.30788587]
  [0.74446185 0.67967973 0.07080964 0.80149417 0.71686961]]

 [[0.13645797 0.43556718 0.17338114 0.22216208 0.19604017]
  [0.85034818 0.42955473 0.00124037 0.01796475 0.8794894 ]
  [0.1324114  0.64570337 0.04051609 0.67406478 0.57861149]]]


3

#### 4. Print *a*.


In [6]:
# your code here

print(a)

[[[0.46426932 0.43968398 0.82237227 0.17123957 0.84325794]
  [0.80850699 0.74941093 0.90384097 0.59997834 0.18202827]
  [0.75494576 0.12418605 0.72859877 0.92722081 0.46657859]]

 [[0.17926235 0.98643458 0.93552288 0.44175274 0.62793066]
  [0.8322141  0.84395082 0.88220845 0.64738753 0.67569495]
  [0.73762764 0.41686484 0.9966783  0.72975932 0.70388578]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here

b = np.ones((5,2,3))
print(b)

b.ndim

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


3

#### 6. Print *b*.


In [8]:
# your code here
print(b)

print(np.shape(b))

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
(5, 2, 3)


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here

np.size(a) == np.size(b)

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here
c = a * b

# We are not able to multiply because the arrays have different shape

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [19]:
# your code here
c = np.transpose(b, axes=(1,2,0))

print(np.shape(c))

(2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [20]:
# your code/answer here
d = a + c

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [21]:
# your code/answer here
print(a)
print(d)

# d* is composed by the values of a+1, because the array c is composed by ones

[[[0.46426932 0.43968398 0.82237227 0.17123957 0.84325794]
  [0.80850699 0.74941093 0.90384097 0.59997834 0.18202827]
  [0.75494576 0.12418605 0.72859877 0.92722081 0.46657859]]

 [[0.17926235 0.98643458 0.93552288 0.44175274 0.62793066]
  [0.8322141  0.84395082 0.88220845 0.64738753 0.67569495]
  [0.73762764 0.41686484 0.9966783  0.72975932 0.70388578]]]
[[[1.46426932 1.43968398 1.82237227 1.17123957 1.84325794]
  [1.80850699 1.74941093 1.90384097 1.59997834 1.18202827]
  [1.75494576 1.12418605 1.72859877 1.92722081 1.46657859]]

 [[1.17926235 1.98643458 1.93552288 1.44175274 1.62793066]
  [1.8322141  1.84395082 1.88220845 1.64738753 1.67569495]
  [1.73762764 1.41686484 1.9966783  1.72975932 1.70388578]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [22]:
# your code here

e = a * c

#### 13. Does *e* equal to *a*? Why or why not?


In [23]:
# your code/answer here

e == a

# In this case yes, because we are multiplying by 1

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [24]:
# your code here
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [25]:
# your code here
f = np.empty((2,3,5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [26]:
# your code here
z = []

for value in d.flatten():
    if value > d_min and value < d_mean:
        z.append(25)
    elif value > d_mean and value < d_max:
        z.append(75)
    elif value == d_mean:
        z.append(50)
    elif d_min:
        z.append(0)
    elif d_max:
        z.append(100)

f = np.array(z)

f.reshape(2,3,5)

print(d_max)
print(d_min)
print(d_mean)

1.9966782995951669
1.124186051374073
1.6541097823976487


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [27]:
# your code here
print(d)

print(f.reshape(2,3,5))

[[[1.46426932 1.43968398 1.82237227 1.17123957 1.84325794]
  [1.80850699 1.74941093 1.90384097 1.59997834 1.18202827]
  [1.75494576 1.12418605 1.72859877 1.92722081 1.46657859]]

 [[1.17926235 1.98643458 1.93552288 1.44175274 1.62793066]
  [1.8322141  1.84395082 1.88220845 1.64738753 1.67569495]
  [1.73762764 1.41686484 1.9966783  1.72975932 1.70388578]]]
[[[25 25 75 25 75]
  [75 75 75 25 25]
  [75  0 75 75 25]]

 [[25 75 75 25 25]
  [75 75 75 25 75]
  [75 25  0 75 75]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [28]:
# your code here

z = []

for value in d.flatten():
    if value > d_min and value < d_mean:
        z.append("A")
    elif value > d_mean and value < d_max:
        z.append("B")
    elif value == d_mean:
        z.append("C")
    elif d_min:
        z.append("D")
    elif d_max:
        z.append("E")

f = np.array(z)

print(f.reshape(2,3,5))

[[['A' 'A' 'B' 'A' 'B']
  ['B' 'B' 'B' 'A' 'A']
  ['B' 'D' 'B' 'B' 'A']]

 [['A' 'B' 'B' 'A' 'A']
  ['B' 'B' 'B' 'A' 'B']
  ['B' 'A' 'D' 'B' 'B']]]
