# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [52]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [53]:
# your code here
np.version.version

'1.16.5'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [86]:
# Method 1
a = np.random.random ((2,3,5))*6 -3

In [55]:
# Method 2
import random
lst = np.array([random.randint(0,10) for _ in range(2*3*5)])
a = lst.reshape(2,3,5)
print(a)

[[[ 6  1  8  7  0]
  [ 1  6 10  9  9]
  [ 2 10  2  2  7]]

 [[ 4  6  4  4  9]
  [ 4  9  2  1 10]
  [ 2 10  6  8  5]]]


In [56]:
# Method 3

#### 4. Print *a*.


In [57]:
# your code here
print(a)

[[[ 6  1  8  7  0]
  [ 1  6 10  9  9]
  [ 2 10  2  2  7]]

 [[ 4  6  4  4  9]
  [ 4  9  2  1 10]
  [ 2 10  6  8  5]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [58]:
# your code here
b=np.ones((5,2,3), dtype = int)

#### 6. Print *b*.


In [59]:
# your code here
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [72]:
# your code here
print(np.size(a)==np.size(b))
  
    
print( np.ndim(a)==np.ndim(b))

print (a.shape==b.shape)


True
True
False


#### 8. Are you able to add *a* and *b*? Why or why not?


In [61]:
# your answer here
#vstack_arr = np.vstack ([a,b])
#hstack_arr = np.hstack ([a,b])

#a +b 

# no, because they dont have the same shape (see above)

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [64]:
# your code here
c=b.transpose(1,2,0)
c.shape

(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [66]:
# your code/answer here
d = a+c

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [67]:
# your code/answer here
print (a)
print (d)

[[[ 6  1  8  7  0]
  [ 1  6 10  9  9]
  [ 2 10  2  2  7]]

 [[ 4  6  4  4  9]
  [ 4  9  2  1 10]
  [ 2 10  6  8  5]]]
[[[ 7  2  9  8  1]
  [ 2  7 11 10 10]
  [ 3 11  3  3  8]]

 [[ 5  7  5  5 10]
  [ 5 10  3  2 11]
  [ 3 11  7  9  6]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [68]:
# your code here
e =a * c

#### 13. Does *e* equal to *a*? Why or why not?


In [69]:
# your code/answer here
print (a)
print (e)

# yes because we did a = a * bT, and since b (and also b transposed ist only a 1 by 1 matrix, the matrix stays the same)

[[[ 6  1  8  7  0]
  [ 1  6 10  9  9]
  [ 2 10  2  2  7]]

 [[ 4  6  4  4  9]
  [ 4  9  2  1 10]
  [ 2 10  6  8  5]]]
[[[ 6  1  8  7  0]
  [ 1  6 10  9  9]
  [ 2 10  2  2  7]]

 [[ 4  6  4  4  9]
  [ 4  9  2  1 10]
  [ 2 10  6  8  5]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [77]:
# your code here
d_min=np.min(d) 
d_max=np.max(d) 
d_mean=np.mean(d) 
print(d_min)

1


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [107]:
# your code here
f = np.empty([2,3,5], dtype = int)*0
print (f)

[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [112]:
# your code here
print(f)
for x in range(2):
    for y in range(3):
        for z in range(5):
            if d[x,y,z]>d_min and d[x,y,z]<d_mean:
                f[x,y,z] = 25
            elif d[x,y,z]<d_max and d[x,y,z]>d_mean:
                f[x,y,z] = 75
            elif d[x,y,z]==d_mean:
                f[x,y,z] = 50
            elif d[x,y,z]==d_max:
                f[x,y,z] = 100


[[[ 75  25  75  75   0]
  [ 25  75 100  75  75]
  [ 25 100  25  25  75]]

 [[ 25  75  25  25  75]
  [ 25  75  25  25 100]
  [ 25 100  75  75  25]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [113]:
# your code here
print (f)

[[[ 75  25  75  75   0]
  [ 25  75 100  75  75]
  [ 25 100  25  25  75]]

 [[ 25  75  25  25  75]
  [ 25  75  25  25 100]
  [ 25 100  75  75  25]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [121]:
# your code here

x = np.array([''  for x in range(2*3*5)])
f = x.reshape(2,3,5)

print (f)


[[['' '' '' '' '']
  ['' '' '' '' '']
  ['' '' '' '' '']]

 [['' '' '' '' '']
  ['' '' '' '' '']
  ['' '' '' '' '']]]


In [123]:

for x in range(2):
    for y in range(3):
        for z in range(5):
            if d[x,y,z]>d_min and d[x,y,z]<d_mean:
                f[x,y,z] = 'B'
            elif d[x,y,z]<d_max and d[x,y,z]>d_mean:
                f[x,y,z] = 'D'
            elif d[x,y,z]==d_mean:
                f[x,y,z] = 'C'
            elif d[x,y,z]==d_max:
                f[x,y,z] = 'E'
            elif d[x,y,z]==d_min:
                f[x,y,z] = 'A'
print (f)

[[['D' 'B' 'D' 'D' 'A']
  ['B' 'D' 'E' 'D' 'D']
  ['B' 'E' 'B' 'B' 'D']]

 [['B' 'D' 'B' 'B' 'D']
  ['B' 'D' 'B' 'B' 'E']
  ['B' 'E' 'D' 'D' 'B']]]
[[['D' 'B' 'D' 'D' 'A']
  ['B' 'D' 'E' 'D' 'D']
  ['B' 'E' 'B' 'B' 'D']]

 [['B' 'D' 'B' 'B' 'D']
  ['B' 'D' 'B' 'B' 'E']
  ['B' 'E' 'D' 'D' 'B']]]
