# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [15]:
import numpy as np

#### 2. Print your NumPy version.

In [16]:
np.version.version

'1.18.5'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [17]:
# Method 1
a = np.random.random((2,3,5))

In [18]:
# Method 2
a2 = np.arange(30).reshape(2,3,5)
#It is not really a random array, considering I decided the numbers, but maybe it is one of the methods you are looking for

In [19]:
# Method 3
a3 = np.random.rand(2,3,5)
#I strongly suspect is the same function of the first method

#### 4. Print *a*.


In [20]:
print(a)

[[[0.34192085 0.16585709 0.59997836 0.27250456 0.22759037]
  [0.23611526 0.90350282 0.79900103 0.28942695 0.46448583]
  [0.02349381 0.35917735 0.47619923 0.38107009 0.35871348]]

 [[0.93044886 0.88211833 0.23196644 0.94700322 0.4433776 ]
  [0.19206138 0.43381822 0.46105545 0.29125309 0.55982335]
  [0.93047221 0.50727974 0.76443491 0.80181573 0.37742704]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [21]:
b = np.ones((5,2,3))

#### 6. Print *b*.


In [22]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [23]:
print(a.size)
print(b.size)
a.size == b.size

30
30


True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [24]:
print(a.shape)
print(b.shape)
#cannot be added because of different shapes

(2, 3, 5)
(5, 2, 3)


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [25]:
c = np.transpose(b).reshape(2,3,5)
print(c)
c.shape

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [26]:
d = np.add(a,c)
print(d)
#it works because both array a and c have the same shape
print(a.shape)
print(c.shape)

[[[1.34192085 1.16585709 1.59997836 1.27250456 1.22759037]
  [1.23611526 1.90350282 1.79900103 1.28942695 1.46448583]
  [1.02349381 1.35917735 1.47619923 1.38107009 1.35871348]]

 [[1.93044886 1.88211833 1.23196644 1.94700322 1.4433776 ]
  [1.19206138 1.43381822 1.46105545 1.29125309 1.55982335]
  [1.93047221 1.50727974 1.76443491 1.80181573 1.37742704]]]
(2, 3, 5)
(2, 3, 5)


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [27]:
print(a)
print()
print(d)
#the values of d are the values of a+1 because we summed a randomly created array with an array filled with 1

[[[0.34192085 0.16585709 0.59997836 0.27250456 0.22759037]
  [0.23611526 0.90350282 0.79900103 0.28942695 0.46448583]
  [0.02349381 0.35917735 0.47619923 0.38107009 0.35871348]]

 [[0.93044886 0.88211833 0.23196644 0.94700322 0.4433776 ]
  [0.19206138 0.43381822 0.46105545 0.29125309 0.55982335]
  [0.93047221 0.50727974 0.76443491 0.80181573 0.37742704]]]

[[[1.34192085 1.16585709 1.59997836 1.27250456 1.22759037]
  [1.23611526 1.90350282 1.79900103 1.28942695 1.46448583]
  [1.02349381 1.35917735 1.47619923 1.38107009 1.35871348]]

 [[1.93044886 1.88211833 1.23196644 1.94700322 1.4433776 ]
  [1.19206138 1.43381822 1.46105545 1.29125309 1.55982335]
  [1.93047221 1.50727974 1.76443491 1.80181573 1.37742704]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [28]:
e = np.multiply(a,c)
print(e)

[[[0.34192085 0.16585709 0.59997836 0.27250456 0.22759037]
  [0.23611526 0.90350282 0.79900103 0.28942695 0.46448583]
  [0.02349381 0.35917735 0.47619923 0.38107009 0.35871348]]

 [[0.93044886 0.88211833 0.23196644 0.94700322 0.4433776 ]
  [0.19206138 0.43381822 0.46105545 0.29125309 0.55982335]
  [0.93047221 0.50727974 0.76443491 0.80181573 0.37742704]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [29]:
print(a)
print()
print(e)
a == e
#they are indeed equal because: a is the first randomly created array but e=a*c with c filled by all 1, so it is like a*1 = a

[[[0.34192085 0.16585709 0.59997836 0.27250456 0.22759037]
  [0.23611526 0.90350282 0.79900103 0.28942695 0.46448583]
  [0.02349381 0.35917735 0.47619923 0.38107009 0.35871348]]

 [[0.93044886 0.88211833 0.23196644 0.94700322 0.4433776 ]
  [0.19206138 0.43381822 0.46105545 0.29125309 0.55982335]
  [0.93047221 0.50727974 0.76443491 0.80181573 0.37742704]]]

[[[0.34192085 0.16585709 0.59997836 0.27250456 0.22759037]
  [0.23611526 0.90350282 0.79900103 0.28942695 0.46448583]
  [0.02349381 0.35917735 0.47619923 0.38107009 0.35871348]]

 [[0.93044886 0.88211833 0.23196644 0.94700322 0.4433776 ]
  [0.19206138 0.43381822 0.46105545 0.29125309 0.55982335]
  [0.93047221 0.50727974 0.76443491 0.80181573 0.37742704]]]


array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [30]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print(d_max)
print(d_min)
print(d_mean)

1.9470032188034767
1.023493812166682
1.4884464216414124


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [31]:
f = np.empty((2,3,5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [32]:
f = np.where(d == d_max, 100, f)
f = np.where(d < d_max, 75, f)
f = np.where(d == d_mean, 50, f)
f = np.where(d < d_mean, 25, f)
f = np.where(d == d_min, 0, f)

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [33]:
print(f)
print()
print(d)

[[[ 25.  25.  75.  25.  25.]
  [ 25.  75.  75.  25.  25.]
  [  0.  25.  25.  25.  25.]]

 [[ 75.  75.  25. 100.  25.]
  [ 25.  25.  25.  25.  75.]
  [ 75.  75.  75.  75.  25.]]]

[[[1.34192085 1.16585709 1.59997836 1.27250456 1.22759037]
  [1.23611526 1.90350282 1.79900103 1.28942695 1.46448583]
  [1.02349381 1.35917735 1.47619923 1.38107009 1.35871348]]

 [[1.93044886 1.88211833 1.23196644 1.94700322 1.4433776 ]
  [1.19206138 1.43381822 1.46105545 1.29125309 1.55982335]
  [1.93047221 1.50727974 1.76443491 1.80181573 1.37742704]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [34]:
f = np.where(d == d_max, 'E', f)
f = np.where(d < d_max, 'D', f)
f = np.where(d == d_mean, 'C', f)
f = np.where(d < d_mean, 'B', f)
f = np.where(d == d_min, "A", f)

In [35]:
print(f)
print()
print(d)

[[['B' 'B' 'D' 'B' 'B']
  ['B' 'D' 'D' 'B' 'B']
  ['A' 'B' 'B' 'B' 'B']]

 [['D' 'D' 'B' 'E' 'B']
  ['B' 'B' 'B' 'B' 'D']
  ['D' 'D' 'D' 'D' 'B']]]

[[[1.34192085 1.16585709 1.59997836 1.27250456 1.22759037]
  [1.23611526 1.90350282 1.79900103 1.28942695 1.46448583]
  [1.02349381 1.35917735 1.47619923 1.38107009 1.35871348]]

 [[1.93044886 1.88211833 1.23196644 1.94700322 1.4433776 ]
  [1.19206138 1.43381822 1.46105545 1.29125309 1.55982335]
  [1.93047221 1.50727974 1.76443491 1.80181573 1.37742704]]]
