# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [2]:
print(np.__version__)

1.21.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
a=np.zeros(shape=(2,3,5), dtype=int) #second argument is columns and first is related to rows
a=a+2
a

array([[[2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2]],

       [[2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2]]])

In [4]:
a=np.ones(shape=(2,3,5), dtype=int) #second argument is columns and first is related to rows
a=a*5
a

array([[[5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5]],

       [[5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5]]])

In [5]:
a=np.random.random(size= (2,3,5))
a

array([[[0.0210077 , 0.91423659, 0.71015952, 0.80450424, 0.62626259],
        [0.11076567, 0.88582427, 0.04204942, 0.76757208, 0.55457121],
        [0.79724388, 0.34474585, 0.14657868, 0.92746708, 0.18799238]],

       [[0.0486118 , 0.1689581 , 0.8882221 , 0.69329927, 0.63680229],
        [0.3724571 , 0.33078235, 0.05618943, 0.09668378, 0.95730626],
        [0.9044028 , 0.14345274, 0.1494622 , 0.19050341, 0.47753865]]])

#### 4. Print *a*.


In [6]:
#printed above

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
b=np.ones(shape=(5,2,3), dtype=int) #second argument is columns and first is related to rows
b

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

#### 6. Print *b*.


In [8]:
b


array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
print("The shape of A is ", a.shape)
print("The shape of B is ",b.shape)
b.shape==a.shape 

The shape of A is  (2, 3, 5)
The shape of B is  (5, 2, 3)


False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:

a+b
#No. Because a and b have different array formats. 

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [12]:
c=b.reshape(2,3,5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [13]:
d=a+c #because both areas have the same shape

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [14]:
print("array A: ",a)
print("array D: ",d)
#D is the sum of A and B, the values are higher in D

array A:  [[[0.0210077  0.91423659 0.71015952 0.80450424 0.62626259]
  [0.11076567 0.88582427 0.04204942 0.76757208 0.55457121]
  [0.79724388 0.34474585 0.14657868 0.92746708 0.18799238]]

 [[0.0486118  0.1689581  0.8882221  0.69329927 0.63680229]
  [0.3724571  0.33078235 0.05618943 0.09668378 0.95730626]
  [0.9044028  0.14345274 0.1494622  0.19050341 0.47753865]]]
array D:  [[[1.0210077  1.91423659 1.71015952 1.80450424 1.62626259]
  [1.11076567 1.88582427 1.04204942 1.76757208 1.55457121]
  [1.79724388 1.34474585 1.14657868 1.92746708 1.18799238]]

 [[1.0486118  1.1689581  1.8882221  1.69329927 1.63680229]
  [1.3724571  1.33078235 1.05618943 1.09668378 1.95730626]
  [1.9044028  1.14345274 1.1494622  1.19050341 1.47753865]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [15]:
e=a*c

#### 13. Does *e* equal to *a*? Why or why not?


In [16]:
e==a #Yes! The arrays are equal because they have the same shape and the same items 

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [17]:
d_max=d.max()
d_min=d.min()
d_mean=d.mean()
print(d_max, d_min, d_mean )


1.9573062596659674 1.0210077018710102 1.465188448674296


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [22]:
f=np.empty(d.shape)
f

array([[[1.0210077 , 1.91423659, 1.71015952, 1.80450424, 1.62626259],
        [1.11076567, 1.88582427, 1.04204942, 1.76757208, 1.55457121],
        [1.79724388, 1.34474585, 1.14657868, 1.92746708, 1.18799238]],

       [[1.0486118 , 1.1689581 , 1.8882221 , 1.69329927, 1.63680229],
        [1.3724571 , 1.33078235, 1.05618943, 1.09668378, 1.95730626],
        [1.9044028 , 1.14345274, 1.1494622 , 1.19050341, 1.47753865]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [19]:
#for item in range(0, len(d)):
#    if item==d_min:
#        d[item]=f.append[item]
#        f[item]=0
#    elif item==d_max:
#        d[item]=f[item]
#        f[item]=100
#    elif item> d_min and item <d_mean:
#        d[item]=f[item]
#        f[item]=25
#    elif item>d_mean and d<d_max:
#        d[item]=f[item]
#        f[item]=75
#    else:
#        d[item]=f[item]
#        f[item]=50

conditions = [(d == d_min), (d > d_min) & (d < d_mean), (d == d_mean), (d > d_mean) & (d < d_max), (d == d_max)]
choices = [0,25,50,75,100]
f = np.select(conditions, choices)
print(f)
print(f.shape)

[[[  0  75  75  75  75]
  [ 25  75  25  75  75]
  [ 75  25  25  75  25]]

 [[ 25  25  75  75  75]
  [ 25  25  25  25 100]
  [ 75  25  25  25  75]]]
(2, 3, 5)


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
#Yes!

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [29]:
# your code here
f = f.astype(str)

conditions = [(d == d_min), (d > d_min) & (d < d_mean), (d == d_mean), (d > d_mean) & (d < d_max), (d == d_max)]
choices = ["A","B","C","D","E"]
f = np.select(conditions, choices)
print(f)

[[['A' 'D' 'D' 'D' 'D']
  ['B' 'D' 'B' 'D' 'D']
  ['D' 'B' 'B' 'D' 'B']]

 [['B' 'B' 'D' 'D' 'D']
  ['B' 'B' 'B' 'B' 'E']
  ['D' 'B' 'B' 'B' 'D']]]
