# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.__version__)

1.17.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a = np.random.random((2,3,5))
print(a)

[[[0.81281975 0.38581812 0.83059115 0.48622998 0.54924549]
  [0.83436119 0.88921743 0.70859313 0.83279394 0.14887461]
  [0.76641792 0.5308424  0.23558887 0.18326021 0.59756754]]

 [[0.3356423  0.12358505 0.99379015 0.8077936  0.0438131 ]
  [0.22676103 0.07310206 0.18882973 0.61901393 0.93834492]
  [0.83922903 0.07220658 0.99279906 0.93387442 0.63020045]]]


In [4]:
# Method 2
a2 = np.linspace(1,100,30)
a2.shape = (2,3,5)
print(a2)

[[[  1.           4.4137931    7.82758621  11.24137931  14.65517241]
  [ 18.06896552  21.48275862  24.89655172  28.31034483  31.72413793]
  [ 35.13793103  38.55172414  41.96551724  45.37931034  48.79310345]]

 [[ 52.20689655  55.62068966  59.03448276  62.44827586  65.86206897]
  [ 69.27586207  72.68965517  76.10344828  79.51724138  82.93103448]
  [ 86.34482759  89.75862069  93.17241379  96.5862069  100.        ]]]


In [5]:
# Method 3 
#can't think of one :(

#### 4. Print *a*.


In [6]:
# your code here
print(a)

[[[0.81281975 0.38581812 0.83059115 0.48622998 0.54924549]
  [0.83436119 0.88921743 0.70859313 0.83279394 0.14887461]
  [0.76641792 0.5308424  0.23558887 0.18326021 0.59756754]]

 [[0.3356423  0.12358505 0.99379015 0.8077936  0.0438131 ]
  [0.22676103 0.07310206 0.18882973 0.61901393 0.93834492]
  [0.83922903 0.07220658 0.99279906 0.93387442 0.63020045]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here
b = np.full((5,2,3),1)

#### 6. Print *b*.


In [8]:
# your code here
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here
a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here
np.add(a,b)

#the arrays do not have the same shape

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [11]:
np.add(a,a2) #trying np.add with same shape arrays

array([[[  1.81281975,   4.79961123,   8.65817735,  11.72760929,
          15.20441791],
        [ 18.9033267 ,  22.37197605,  25.60514486,  29.14313876,
          31.87301254],
        [ 35.90434895,  39.08256654,  42.20110611,  45.56257055,
          49.39067099]],

       [[ 52.54253886,  55.7442747 ,  60.02827291,  63.25606946,
          65.90588207],
        [ 69.5026231 ,  72.76275723,  76.292278  ,  80.13625531,
          83.86937941],
        [ 87.18405661,  89.83082727,  94.16521285,  97.52008131,
         100.63020045]]])

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [12]:
# your code here
c = np.reshape(b,(2,3,5))
print(c)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [13]:
# your code/answer here
d = np.add(a,c)
d
#it works because the arrays have the same shape so the values match up and can be iterated over

array([[[1.81281975, 1.38581812, 1.83059115, 1.48622998, 1.54924549],
        [1.83436119, 1.88921743, 1.70859313, 1.83279394, 1.14887461],
        [1.76641792, 1.5308424 , 1.23558887, 1.18326021, 1.59756754]],

       [[1.3356423 , 1.12358505, 1.99379015, 1.8077936 , 1.0438131 ],
        [1.22676103, 1.07310206, 1.18882973, 1.61901393, 1.93834492],
        [1.83922903, 1.07220658, 1.99279906, 1.93387442, 1.63020045]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [14]:
# your code/answer here
print(a)
print(d)
#d has the values of a + 1, the sum was applied to each value

[[[0.81281975 0.38581812 0.83059115 0.48622998 0.54924549]
  [0.83436119 0.88921743 0.70859313 0.83279394 0.14887461]
  [0.76641792 0.5308424  0.23558887 0.18326021 0.59756754]]

 [[0.3356423  0.12358505 0.99379015 0.8077936  0.0438131 ]
  [0.22676103 0.07310206 0.18882973 0.61901393 0.93834492]
  [0.83922903 0.07220658 0.99279906 0.93387442 0.63020045]]]
[[[1.81281975 1.38581812 1.83059115 1.48622998 1.54924549]
  [1.83436119 1.88921743 1.70859313 1.83279394 1.14887461]
  [1.76641792 1.5308424  1.23558887 1.18326021 1.59756754]]

 [[1.3356423  1.12358505 1.99379015 1.8077936  1.0438131 ]
  [1.22676103 1.07310206 1.18882973 1.61901393 1.93834492]
  [1.83922903 1.07220658 1.99279906 1.93387442 1.63020045]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [15]:
# your code here
e = np.multiply(a,c)
e

array([[[0.81281975, 0.38581812, 0.83059115, 0.48622998, 0.54924549],
        [0.83436119, 0.88921743, 0.70859313, 0.83279394, 0.14887461],
        [0.76641792, 0.5308424 , 0.23558887, 0.18326021, 0.59756754]],

       [[0.3356423 , 0.12358505, 0.99379015, 0.8077936 , 0.0438131 ],
        [0.22676103, 0.07310206, 0.18882973, 0.61901393, 0.93834492],
        [0.83922903, 0.07220658, 0.99279906, 0.93387442, 0.63020045]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [16]:
# your code/answer here
e == a
#yes, because the value type and shape are the same

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [17]:
# your code here
d_max = d.max()
d_max

1.993790148258015

In [18]:
d_min = d.min()
d_min

1.0438131049295856

In [19]:
d_mean = d.mean()
d_mean

1.55370690474388

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [20]:
# your code here
f = np.empty((2,3,5))
f

array([[[0.81281975, 0.38581812, 0.83059115, 0.48622998, 0.54924549],
        [0.83436119, 0.88921743, 0.70859313, 0.83279394, 0.14887461],
        [0.76641792, 0.5308424 , 0.23558887, 0.18326021, 0.59756754]],

       [[0.3356423 , 0.12358505, 0.99379015, 0.8077936 , 0.0438131 ],
        [0.22676103, 0.07310206, 0.18882973, 0.61901393, 0.93834492],
        [0.83922903, 0.07220658, 0.99279906, 0.93387442, 0.63020045]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [42]:
# your code here
f = []
for item in d:
    for subitem in item:
        for subsubitem in subitem:
            if subsubitem > d_min and subsubitem < d_mean :
                f.append(25)
            elif subsubitem > d_mean and subsubitem < d_max:
                f.append(75)
            elif subsubitem == d_mean:
                f.append(50)
            elif subsubitem == d_min:
                f.append(0)
            else:
                subsubitem == d_max
                f.append(100)
print(f)

f = np.reshape(f, (2,3,5))
print(f)

[75, 25, 75, 25, 25, 75, 75, 75, 75, 25, 75, 25, 25, 25, 75, 25, 25, 100, 75, 0, 25, 25, 25, 75, 75, 75, 25, 75, 75, 75]
[[[ 75  25  75  25  25]
  [ 75  75  75  75  25]
  [ 75  25  25  25  75]]

 [[ 25  25 100  75   0]
  [ 25  25  25  75  75]
  [ 75  25  75  75  75]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [43]:
# your code here
print(d)
print(f)

[[[1.81281975 1.38581812 1.83059115 1.48622998 1.54924549]
  [1.83436119 1.88921743 1.70859313 1.83279394 1.14887461]
  [1.76641792 1.5308424  1.23558887 1.18326021 1.59756754]]

 [[1.3356423  1.12358505 1.99379015 1.8077936  1.0438131 ]
  [1.22676103 1.07310206 1.18882973 1.61901393 1.93834492]
  [1.83922903 1.07220658 1.99279906 1.93387442 1.63020045]]]
[[[ 75  25  75  25  25]
  [ 75  75  75  75  25]
  [ 75  25  25  25  75]]

 [[ 25  25 100  75   0]
  [ 25  25  25  75  75]
  [ 75  25  75  75  75]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [73]:
# your code here5
a1 = np.where(f==0, 'A', f)
print(a1)
a2 = np.where(f==25, 'B', a1)
a3 = np.where(f==50, 'C', a2)
a4 = np.where(f==75, 'D', a3)
a5 = np.where(f==100, 'E', a4)
print(a5)

[[['75' '25' '75' '25' '25']
  ['75' '75' '75' '75' '25']
  ['75' '25' '25' '25' '75']]

 [['25' '25' '100' '75' 'A']
  ['25' '25' '25' '75' '75']
  ['75' '25' '75' '75' '75']]]
[[['D' 'B' 'D' 'B' 'B']
  ['D' 'D' 'D' 'D' 'B']
  ['D' 'B' 'B' 'B' 'D']]

 [['B' 'B' 'E' 'D' 'A']
  ['B' 'B' 'B' 'D' 'D']
  ['D' 'B' 'D' 'D' 'D']]]
