# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [8]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [14]:
print(np.__version__)
print(np.version.version)

1.19.2
1.19.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [10]:
a = np.random.rand(2,3,5)
print (a)

[[[0.63275337 0.70363618 0.36494472 0.08125648 0.00172958]
  [0.44532159 0.82984303 0.46424331 0.2819397  0.0308143 ]
  [0.3021925  0.97464829 0.81578724 0.85813532 0.44819203]]

 [[0.31769871 0.98429959 0.05135566 0.80835841 0.14448005]
  [0.66215996 0.89519625 0.28636425 0.84386699 0.68933834]
  [0.53770407 0.70018298 0.72533817 0.5427156  0.99761317]]]


In [15]:
b = np.random.randn(2,3,5)
print (b)
#Difference between rand (0-1) and randn(normal distribution around the mean)

[[[ 0.07999883 -0.05482475  1.00190725  0.23518239  0.11619692]
  [ 0.50394936 -1.63878305  1.33333206  0.58062948 -0.03807171]
  [-1.09704612  0.11907384 -0.22584622 -0.37574088 -0.12229028]]

 [[ 1.07359581  0.06952408  0.27644188 -1.04882439  0.65288956]
  [ 0.18887643  0.5332341   0.8976662  -1.89690192 -1.20789964]
  [-0.31895114 -0.98592791  0.99628515  0.91212506 -0.83973831]]]


In [36]:
c = np.random.randint(1,100,(2,3,5))
print (c)
#First two numbers, range from where vales are picked

[[[54 10 89 98 31]
  [57 97 66 84  7]
  [11 24 37 63 44]]

 [[10 27 44 63 74]
  [ 1 29 17 10 21]
  [20  3 44 17 49]]]


#### 4. Print *a*.


In [18]:
#For fun 
print(a)


[[[0.63275337 0.70363618 0.36494472 0.08125648 0.00172958]
  [0.44532159 0.82984303 0.46424331 0.2819397  0.0308143 ]
  [0.3021925  0.97464829 0.81578724 0.85813532 0.44819203]]

 [[0.31769871 0.98429959 0.05135566 0.80835841 0.14448005]
  [0.66215996 0.89519625 0.28636425 0.84386699 0.68933834]
  [0.53770407 0.70018298 0.72533817 0.5427156  0.99761317]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [20]:
b= np.ones((5,2,3,))


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 6. Print *b*.


In [21]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [24]:
# your code here
print (a.size)
a.size == b.size 

30


True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [26]:
sumab = a+b
peint(sumab)
#I cant add matrices of different shape 

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [29]:
# your code here
b= np.ones((5,3,2,))
c = b.transpose()
print(c.shape)


(2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [30]:
# your code/answer here
d= a+c
print(d)

[[[1.63275337 1.70363618 1.36494472 1.08125648 1.00172958]
  [1.44532159 1.82984303 1.46424331 1.2819397  1.0308143 ]
  [1.3021925  1.97464829 1.81578724 1.85813532 1.44819203]]

 [[1.31769871 1.98429959 1.05135566 1.80835841 1.14448005]
  [1.66215996 1.89519625 1.28636425 1.84386699 1.68933834]
  [1.53770407 1.70018298 1.72533817 1.5427156  1.99761317]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [31]:
# Simple addition of the contents of each matrix

print(a)
print(d)


[[[0.63275337 0.70363618 0.36494472 0.08125648 0.00172958]
  [0.44532159 0.82984303 0.46424331 0.2819397  0.0308143 ]
  [0.3021925  0.97464829 0.81578724 0.85813532 0.44819203]]

 [[0.31769871 0.98429959 0.05135566 0.80835841 0.14448005]
  [0.66215996 0.89519625 0.28636425 0.84386699 0.68933834]
  [0.53770407 0.70018298 0.72533817 0.5427156  0.99761317]]]
[[[1.63275337 1.70363618 1.36494472 1.08125648 1.00172958]
  [1.44532159 1.82984303 1.46424331 1.2819397  1.0308143 ]
  [1.3021925  1.97464829 1.81578724 1.85813532 1.44819203]]

 [[1.31769871 1.98429959 1.05135566 1.80835841 1.14448005]
  [1.66215996 1.89519625 1.28636425 1.84386699 1.68933834]
  [1.53770407 1.70018298 1.72533817 1.5427156  1.99761317]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [32]:
# your code here
e = a * c 
print(e)

[[[0.63275337 0.70363618 0.36494472 0.08125648 0.00172958]
  [0.44532159 0.82984303 0.46424331 0.2819397  0.0308143 ]
  [0.3021925  0.97464829 0.81578724 0.85813532 0.44819203]]

 [[0.31769871 0.98429959 0.05135566 0.80835841 0.14448005]
  [0.66215996 0.89519625 0.28636425 0.84386699 0.68933834]
  [0.53770407 0.70018298 0.72533817 0.5427156  0.99761317]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [33]:
# your code/answer here
e == a


array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [34]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(d_max, d_min, d_mean)

1.9976131654478873 1.0017295833793103 1.5474036604263548


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [37]:
# np.empty, based on the last memory
f = np.empty((2,3,5,))
print(f)

[[[0.63275337 0.70363618 0.36494472 0.08125648 0.00172958]
  [0.44532159 0.82984303 0.46424331 0.2819397  0.0308143 ]
  [0.3021925  0.97464829 0.81578724 0.85813532 0.44819203]]

 [[0.31769871 0.98429959 0.05135566 0.80835841 0.14448005]
  [0.66215996 0.89519625 0.28636425 0.84386699 0.68933834]
  [0.53770407 0.70018298 0.72533817 0.5427156  0.99761317]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [42]:
# your code here
f[d==d_max]=100
f[d==d_min]=0
f[(d>d_min)&(d<d_mean)]=25
f[(d>d_mean)&(d<d_max)]=75
print(f)


[[[ 75.  75.  25.  25.   0.]
  [ 25.  75.  25.  25.  25.]
  [ 25.  75.  75.  75.  25.]]

 [[ 25.  75.  25.  75.  25.]
  [ 75.  75.  25.  75.  75.]
  [ 25.  75.  75.  25. 100.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [48]:
# Numpy array cannot store different types of values. This Numpy built-in indexing itereates over the values of the arrawy


f=np.empty((2,3,5),dtype=str)
print(f)
f[d==d_max]='E'
f[d==d_min]='A'
f[(d>d_min)&(d<d_mean)]='B'
f[(d>d_mean)&(d<d_max)]='D'

print(f)


[[['' '' '' '' '']
  ['' '' '' '' '']
  ['' '' '' '' '']]

 [['' '' '' '' '']
  ['' '' '' '' '']
  ['' '' '' '' '']]]
[[['D' 'D' 'B' 'B' 'A']
  ['B' 'D' 'B' 'B' 'B']
  ['B' 'D' 'D' 'D' 'B']]

 [['B' 'D' 'B' 'D' 'B']
  ['D' 'D' 'B' 'D' 'D']
  ['B' 'D' 'D' 'B' 'E']]]


In [49]:
for i in f.flat:
    print (i)

D
D
B
B
A
B
D
B
B
B
B
D
D
D
B
B
D
B
D
B
D
D
B
D
D
B
D
D
B
E
