# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [22]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [23]:
# your code here
print(np.version.version)

1.20.3


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [24]:
# Method 1
a = np.random.random((2,3,5))


In [25]:
# Method 2
a = np.random.rand(2,3,5)



In [26]:
# Method 3
a = np.random.random_sample((2,3,5))


#### 4. Print *a*.


In [27]:
# your code here
print(a)

[[[0.92844988 0.65220424 0.83457035 0.44413805 0.0228023 ]
  [0.75836898 0.94426076 0.52104341 0.74232069 0.27191799]
  [0.5359908  0.10715748 0.84895435 0.15409525 0.70996995]]

 [[0.66582852 0.16650432 0.77008592 0.19122182 0.47103434]
  [0.21393455 0.51681234 0.19884432 0.88242446 0.94950242]
  [0.16710497 0.13953307 0.98470747 0.65106536 0.51760805]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [28]:
# your code here
b = np.ones((5,2,3))


#### 6. Print *b*.


In [29]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [30]:
# your code here
print(np.shape(a))
print(np.shape(b))
np.shape(a) == np.shape(b)

(2, 3, 5)
(5, 2, 3)


False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [31]:
# your answer here

#No, because they do not have the same shape. 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [32]:
# your code here

#arr = np.arange(60).reshape(6,10)
c = np.transpose(b, (1,2,0))
np.shape(c)

(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [33]:
# your code/answer here
d = c + a

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [34]:
# your code/answer here
print(a)
print(d)
#each number of the array was added to the same index.  

[[[0.92844988 0.65220424 0.83457035 0.44413805 0.0228023 ]
  [0.75836898 0.94426076 0.52104341 0.74232069 0.27191799]
  [0.5359908  0.10715748 0.84895435 0.15409525 0.70996995]]

 [[0.66582852 0.16650432 0.77008592 0.19122182 0.47103434]
  [0.21393455 0.51681234 0.19884432 0.88242446 0.94950242]
  [0.16710497 0.13953307 0.98470747 0.65106536 0.51760805]]]
[[[1.92844988 1.65220424 1.83457035 1.44413805 1.0228023 ]
  [1.75836898 1.94426076 1.52104341 1.74232069 1.27191799]
  [1.5359908  1.10715748 1.84895435 1.15409525 1.70996995]]

 [[1.66582852 1.16650432 1.77008592 1.19122182 1.47103434]
  [1.21393455 1.51681234 1.19884432 1.88242446 1.94950242]
  [1.16710497 1.13953307 1.98470747 1.65106536 1.51760805]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [35]:
# your code here
e = a*c

#### 13. Does *e* equal to *a*? Why or why not?


In [36]:
# your code/answer here

#Yes, because all numbers are multiplied by 1 "all numbers in c-array" 

a==e


array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [37]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print(d_max, d_min, d_mean)

1.984707474617188 1.02280229845814 1.5320818804812346


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [38]:
# your code here
f = np.empty(shape=(2,3,5))


#### 16. Populate the values in *f*. 

x In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [39]:
# your code here
f[(d > d_min) & (d < d_mean)] = 25
f[(d > d_mean) & (d < d_max)] = 75
f[(d == d_mean)] = 50
f[(d == d_min) ] = 0
f[(d == d_max) ] = 100

print(f)


[[[ 75.  75.  75.  25.   0.]
  [ 75.  75.  25.  75.  25.]
  [ 75.  25.  75.  25.  75.]]

 [[ 75.  25.  75.  25.  25.]
  [ 25.  25.  25.  75.  75.]
  [ 25.  25. 100.  75.  25.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [40]:
# your code here
print("max: ", str(d_max), " Min: ",  str(d_min), "Mean: ", str(d_mean))
print(d)
print(f)

max:  1.984707474617188  Min:  1.02280229845814 Mean:  1.5320818804812346
[[[1.92844988 1.65220424 1.83457035 1.44413805 1.0228023 ]
  [1.75836898 1.94426076 1.52104341 1.74232069 1.27191799]
  [1.5359908  1.10715748 1.84895435 1.15409525 1.70996995]]

 [[1.66582852 1.16650432 1.77008592 1.19122182 1.47103434]
  [1.21393455 1.51681234 1.19884432 1.88242446 1.94950242]
  [1.16710497 1.13953307 1.98470747 1.65106536 1.51760805]]]
[[[ 75.  75.  75.  25.   0.]
  [ 75.  75.  25.  75.  25.]
  [ 75.  25.  75.  25.  75.]]

 [[ 75.  25.  75.  25.  25.]
  [ 25.  25.  25.  75.  75.]
  [ 25.  25. 100.  75.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [43]:
# your code here
labels = ["A", "B", "C", "D", "E"]
l = np.empty(d.shape)
l[:] = "N/A"


l[(d > d_min) & (d < d_mean)] = "B"
l[(d > d_mean) & (d < d_max)] = "D"
l[(d == d_mean)] = "C"
l[(d == d_min) ] = "A"
l[(d == d_max) ] = "E"



ValueError: could not convert string to float: 'N/A'