# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here

import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.__version__)

1.20.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a = np.random.random(size=(2,3,5))

In [4]:
# Method 2 
np.random.random_integers(0, 20, (2,3,5))

<ipython-input-4-93ddc1526f07>:2: DeprecationWarning: This function is deprecated. Please call randint(0, 20 + 1) instead
  np.random.random_integers(0, 20, (2,3,5))


array([[[16, 14,  2,  4,  4],
        [ 5, 12, 17,  1, 20],
        [16,  4, 19, 14,  4]],

       [[17,  6, 13,  5, 13],
        [ 8,  2,  8, 12,  8],
        [11, 12,  3, 20, 14]]])

In [5]:
# Method 3
np.random.rand(2,3,5)

array([[[0.13432177, 0.76588957, 0.48466102, 0.01789833, 0.90576724],
        [0.39192815, 0.71078846, 0.78264297, 0.46935689, 0.40537122],
        [0.82855949, 0.6642706 , 0.07865087, 0.10347379, 0.99752495]],

       [[0.83555739, 0.98466537, 0.06319877, 0.95939469, 0.30632901],
        [0.65248713, 0.55388408, 0.38177447, 0.76236665, 0.45062675],
        [0.60856963, 0.11138877, 0.02520509, 0.02734281, 0.66473516]]])

#### 4. Print *a*.


In [6]:
# your code here
print(a)

[[[0.08933287 0.60042777 0.46732745 0.52886658 0.03356218]
  [0.73940622 0.67877962 0.04791963 0.29835314 0.89289411]
  [0.87537316 0.16027273 0.51825332 0.64468602 0.8265532 ]]

 [[0.67110632 0.04938019 0.77222296 0.13339961 0.336906  ]
  [0.127061   0.43769527 0.10302781 0.87597879 0.79749405]
  [0.49178921 0.58774017 0.46157724 0.32312703 0.65173156]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here

b= np.ones(shape = (5,3,2), dtype = int)   #ATTENTION FOR B TRANSPOSED TO BE POSSIBLE TO SUM TO A, THE MATRIX MUST HAVE A SHAPE OF (5,3,2) INSTEAD OF (5,2,3)

#### 6. Print *b*.


In [8]:
print(b)
# your code here

[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here

a.shape == b.shape

False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here

a + b

#No, because even though each of them are arrays (matrixes) since they don't have the same size, we can't add each position to the other

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,3,2) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here

c= b.transpose()
print(c)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [27]:
# your code/answer here

d= a + c
d

array([[[1.08933287, 1.60042777, 1.46732745, 1.52886658, 1.03356218],
        [1.73940622, 1.67877962, 1.04791963, 1.29835314, 1.89289411],
        [1.87537316, 1.16027273, 1.51825332, 1.64468602, 1.8265532 ]],

       [[1.67110632, 1.04938019, 1.77222296, 1.13339961, 1.336906  ],
        [1.127061  , 1.43769527, 1.10302781, 1.87597879, 1.79749405],
        [1.49178921, 1.58774017, 1.46157724, 1.32312703, 1.65173156]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [28]:
print(a)
print(d)# your code/answer here  #The difference is the adition of the matrix of ones (b)

[[[0.08933287 0.60042777 0.46732745 0.52886658 0.03356218]
  [0.73940622 0.67877962 0.04791963 0.29835314 0.89289411]
  [0.87537316 0.16027273 0.51825332 0.64468602 0.8265532 ]]

 [[0.67110632 0.04938019 0.77222296 0.13339961 0.336906  ]
  [0.127061   0.43769527 0.10302781 0.87597879 0.79749405]
  [0.49178921 0.58774017 0.46157724 0.32312703 0.65173156]]]
[[[1.08933287 1.60042777 1.46732745 1.52886658 1.03356218]
  [1.73940622 1.67877962 1.04791963 1.29835314 1.89289411]
  [1.87537316 1.16027273 1.51825332 1.64468602 1.8265532 ]]

 [[1.67110632 1.04938019 1.77222296 1.13339961 1.336906  ]
  [1.127061   1.43769527 1.10302781 1.87597879 1.79749405]
  [1.49178921 1.58774017 1.46157724 1.32312703 1.65173156]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [29]:
# your code here

e = a * c

#### 13. Does *e* equal to *a*? Why or why not?


In [30]:
# your code/answer here

e == a   #Yes, because everything multiplied by 1 is the number itself, so when we multiply a * c we are multiplyng the values in a*1 = a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [31]:
# your code here

max_d= d.max()
min_d= d.min()
mean_d = d.mean()

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [33]:
# your code here

f = np.empty(shape=[2,3,5], dtype=int)
f


array([[[   3801155,    5570652,    6619251,    7536754,    6488156],
        [   7274610,    7536739,    3014748,    7340137,    7602297],
        [   7274600,    6029422,    7471216,    6684783,    7077993]],

       [[   6226021,    6619236,    6357094,    7078005,    6029428],
        [   6881384,    7602291,    7471215,    3014777,    7405683],
        [   6881388,    6619252,    7798829,    7077985, 1769144320]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [39]:
# your code here

for value in d:
    for sub_value in value:
        for i in range(len(sub_value)):
            if  mean_d < sub_value[i] > min_d :
                sub_value[i] = 25
            elif  max_d < sub_value[i] > mean_d:
                sub_value[i] = 75
            elif sub_value[i] == mean_d:
                sub_value[i] = 50
            elif sub_value[i] == max_d:
                sub_value[i] = 100
            else:
                sub_value[i] = 0

                
                
print(d)      
print(f)

#I CHANGED D INSTEAD OF F, QUESTION PROFESSOR

[[[ 0. 25.  0. 25.  0.]
  [25. 25.  0.  0. 25.]
  [25.  0. 25. 25. 25.]]

 [[25.  0. 25.  0.  0.]
  [ 0.  0.  0. 25. 25.]
  [25. 25.  0.  0. 25.]]]
[[[   3801155    5570652    6619251    7536754    6488156]
  [   7274610    7536739    3014748    7340137    7602297]
  [   7274600    6029422    7471216    6684783    7077993]]

 [[   6226021    6619236    6357094    7078005    6029428]
  [   6881384    7602291    7471215    3014777    7405683]
  [   6881388    6619252    7798829    7077985 1769144320]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [40]:
# your code here
print(d)
print(f)

[[[ 0. 25.  0. 25.  0.]
  [25. 25.  0.  0. 25.]
  [25.  0. 25. 25. 25.]]

 [[25.  0. 25.  0.  0.]
  [ 0.  0.  0. 25. 25.]
  [25. 25.  0.  0. 25.]]]
[[[   3801155    5570652    6619251    7536754    6488156]
  [   7274610    7536739    3014748    7340137    7602297]
  [   7274600    6029422    7471216    6684783    7077993]]

 [[   6226021    6619236    6357094    7078005    6029428]
  [   6881384    7602291    7471215    3014777    7405683]
  [   6881388    6619252    7798829    7077985 1769144320]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [42]:
# your code here

for value in d:
    for sub_value in value:
        for i in range(len(sub_value)):
            if  mean_d < sub_value[i] > min_d :
                sub_value[i] = "B"
            elif  max_d < sub_value[i] > mean_d:
                sub_value[i] = "D"
            elif sub_value[i] == mean_d:
                sub_value[i] = "C"
            elif sub_value[i] == max_d:
                sub_value[i] = "E"
            else:
                sub_value[i] = "A"
print(d)  

#DID NOT WORK

ValueError: could not convert string to float: 'A'