# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [87]:
# your code here
import numpy as np


#### 2. Print your NumPy version.

In [88]:
# your code here
print(np.__version__)

1.18.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [140]:
# Method 1
a = np.random.random((2,3,5))


In [141]:
# Method 2

In [142]:
# Method 3

#### 4. Print *a*.


In [143]:
# your code here
print(a)

[[[0.36109438 0.9323086  0.05103128 0.56726493 0.48840204]
  [0.84500275 0.50842526 0.91863467 0.09160719 0.75590224]
  [0.82375376 0.64176073 0.92238504 0.69042036 0.90621244]]

 [[0.80439501 0.63667518 0.95913393 0.21805106 0.55006403]
  [0.26976187 0.62559161 0.33368482 0.74186296 0.27330136]
  [0.11014065 0.81392957 0.98747112 0.63395839 0.59496968]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [157]:
# your code here
b = np.ones((5,2,3), dtype = int)


#### 6. Print *b*.


In [202]:
# your code here
print(b)


[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
(5, 2, 3)


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [159]:
# your code here
print(a.shape == b.shape)
print(a.size == b. size)

False
True


#### 8. Are you able to add *a* and *b*? Why or why not?


In [160]:
# your answer here
#print(np.add(a,b))
#no, they don't have same shape although they have the same size.

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [181]:
# your code here

c= np.transpose(b, (1,2,0))

print("a",a.shape)
print("b",b.shape)
print("c",c.shape)



a (2, 3, 5)
b (5, 2, 3)
c (2, 3, 5)
[[[1.36109438 1.9323086  1.05103128 1.56726493 1.48840204]
  [1.84500275 1.50842526 1.91863467 1.09160719 1.75590224]
  [1.82375376 1.64176073 1.92238504 1.69042036 1.90621244]]

 [[1.80439501 1.63667518 1.95913393 1.21805106 1.55006403]
  [1.26976187 1.62559161 1.33368482 1.74186296 1.27330136]
  [1.11014065 1.81392957 1.98747112 1.63395839 1.59496968]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [183]:
# your code/answer here
d = a+c
print(d)
#have same shape, have the same size.

[[[1.36109438 1.9323086  1.05103128 1.56726493 1.48840204]
  [1.84500275 1.50842526 1.91863467 1.09160719 1.75590224]
  [1.82375376 1.64176073 1.92238504 1.69042036 1.90621244]]

 [[1.80439501 1.63667518 1.95913393 1.21805106 1.55006403]
  [1.26976187 1.62559161 1.33368482 1.74186296 1.27330136]
  [1.11014065 1.81392957 1.98747112 1.63395839 1.59496968]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [185]:
# your code/answer here
print("a")
print(a)
print("d")
print(d)

a
[[[0.36109438 0.9323086  0.05103128 0.56726493 0.48840204]
  [0.84500275 0.50842526 0.91863467 0.09160719 0.75590224]
  [0.82375376 0.64176073 0.92238504 0.69042036 0.90621244]]

 [[0.80439501 0.63667518 0.95913393 0.21805106 0.55006403]
  [0.26976187 0.62559161 0.33368482 0.74186296 0.27330136]
  [0.11014065 0.81392957 0.98747112 0.63395839 0.59496968]]]
d
[[[1.36109438 1.9323086  1.05103128 1.56726493 1.48840204]
  [1.84500275 1.50842526 1.91863467 1.09160719 1.75590224]
  [1.82375376 1.64176073 1.92238504 1.69042036 1.90621244]]

 [[1.80439501 1.63667518 1.95913393 1.21805106 1.55006403]
  [1.26976187 1.62559161 1.33368482 1.74186296 1.27330136]
  [1.11014065 1.81392957 1.98747112 1.63395839 1.59496968]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [186]:
# your code heree 
e = a*d
print(e)

[[[0.49148354 1.80150794 0.05363547 0.88905442 0.72693859]
  [1.55903239 0.7669215  1.76252432 0.09999906 1.32729043]
  [1.50232401 1.05361757 1.77317921 1.16710064 1.72743344]]

 [[1.45144634 1.04203047 1.87907184 0.26559732 0.85263447]
  [0.34253333 1.01695648 0.44503038 1.29222361 0.34799499]
  [0.12227161 1.47641092 1.96257032 1.03586164 0.94895859]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [188]:
# your code/answer here
print(a == e)

[[[False False False False False]
  [False False False False False]
  [False False False False False]]

 [[False False False False False]
  [False False False False False]
  [False False False False False]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [192]:
# your code here
d_max = np.max(d)
d_min =np.min(d)
d_mean = np.mean(d)

print(d_max)
print(d_min)
print(d_mean)



1.9874711168053014
1.0510312815962928
1.6019065637931549


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [201]:
# your code here
print(d.shape)

#the one below did not work
#f = np.empty([2,3,5])
#print(f)

f = np.zeros([2,3,5])
print(f)

(2, 3, 5)
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [221]:
# your code here
#Marie's code
#print(d)

#for understanding purposes
#for x in range(d.shape[0]): 
#    for y in range(d.shape[1]):
#        for z in range(d.shape[2]):
#            print([x,y,z])
        
for x in range(d.shape[0]): #dimension. without the zero, shape would be 2,3,5. 
    #Asking for the index 0, it gives me 2. The other "for loops" get me the final value.
    for y in range(d.shape[1]): #row
        for z in range(d.shape[2]): #column
            if d[x,y,z] > d_min and d[x,y,z] < d_mean:
                f[x,y,z] = 25
            elif d[x,y,z] > d_mean and d[x,y,z] < d_max:
                f[x,y,z] = 75
            elif d[x,y,z] == d_mean:
                f[x,y,z] = 50
            elif d[x,y,z] == d_max:
                f[x,y,z] = 100
            else:
                f[x,y,z] = 0
print(f)
    
#i in d if d_min < i < d_mean, i =25
#i in d if d_mean < i < d_max, i =75
#i in d if i == d_mean, i = 50
#d_min = 0
#d_max = 100

[[[ 25.  75.   0.  25.  25.]
  [ 75.  25.  75.  25.  75.]
  [ 75.  75.  75.  75.  75.]]

 [[ 75.  75.  75.  25.  25.]
  [ 25.  75.  25.  75.  25.]
  [ 25.  75. 100.  75.  25.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [233]:
# your code here

# your code here
#Marie's code
#print(d)

#arr = np.array([-3-2-1,0,1,2,3,4,5,6])
#new_arr = np.zeros(shape = arr.shape, dtype=np.str)

#new_arr[(arr>3)] = 'S'
#new_arr[((arr>=-3) & (arr<=-1))] = 'F'
#new_arr[((arr>=0)&(arr<=3))] = 'M'
#new_arr
#array(['', 'M', 'M', 'M', 'M', 'S', 'S', 'S'], dtype='<U1')

#for understanding purposes

new_arrf = np.zeros(shape = f.shape, dtype=np.str)
for x in range(f.shape[0]):  
    for y in range(f.shape[1]):
        for z in range(f.shape[2]):
            if f[x,y,z] == 25:
                new_arrf[x,y,z] = 'B'
            elif f[x,y,z] == 75:
                new_arrf[x,y,z] = 'D'
            elif f[x,y,z] == 50:
                new_arrf[x,y,z] = 'C'
            elif f[x,y,z] == 50:
                new_arrf[x,y,z] = 'A'
            else:
                new_arrf[x,y,z] = 'E'
print(new_arrf)
    
#i in d if d_min < i < d_mean, i =25
#i in d if d_mean < i < d_max, i =75
#i in d if i == d_mean, i = 50
#d_min = 0
#d_max = 100

[[['B' 'D' 'E' 'B' 'B']
  ['D' 'B' 'D' 'B' 'D']
  ['D' 'D' 'D' 'D' 'D']]

 [['D' 'D' 'D' 'B' 'B']
  ['B' 'D' 'B' 'D' 'B']
  ['B' 'D' 'E' 'D' 'B']]]
