# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np
import random

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.__version__)

1.21.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a=np.random.rand(2,3,5)
print(a)
print(a.shape)

[[[0.34242608 0.49559205 0.52279086 0.86305882 0.50279485]
  [0.42662931 0.09246819 0.92149876 0.18132948 0.34626472]
  [0.46023996 0.3050306  0.45495211 0.17149134 0.54259306]]

 [[0.042996   0.07486635 0.73711915 0.44898302 0.79519777]
  [0.91714368 0.75629411 0.5950528  0.34027537 0.1402157 ]
  [0.07261127 0.50474665 0.42782843 0.79573856 0.26160336]]]
(2, 3, 5)


In [4]:
# Method 2

a = np.random.randint(1,100, size=(2,3,5))
print(a)
print(a.shape)

[[[43 61 20  5 85]
  [87 43 11 35 42]
  [91 83 44 47  1]]

 [[52 83 66 27 12]
  [40 77 20 84 17]
  [94 20 71 96  9]]]
(2, 3, 5)


In [5]:
# Method 3
a=np.random.power(1, size=(2,3,5))
print(a)
print(a.shape)

[[[0.80678089 0.09220707 0.18819284 0.46779093 0.70287639]
  [0.93967745 0.35702858 0.36223304 0.67969605 0.37456895]
  [0.95679172 0.38430446 0.35434784 0.96744837 0.88117117]]

 [[0.90656561 0.80539828 0.93508508 0.71852918 0.16634225]
  [0.96647788 0.87880759 0.72347082 0.83495002 0.80545848]
  [0.77898709 0.5473424  0.06333658 0.93121675 0.79132045]]]
(2, 3, 5)


#### 4. Print *a*.


In [6]:
# your code here
print(a)

[[[0.80678089 0.09220707 0.18819284 0.46779093 0.70287639]
  [0.93967745 0.35702858 0.36223304 0.67969605 0.37456895]
  [0.95679172 0.38430446 0.35434784 0.96744837 0.88117117]]

 [[0.90656561 0.80539828 0.93508508 0.71852918 0.16634225]
  [0.96647788 0.87880759 0.72347082 0.83495002 0.80545848]
  [0.77898709 0.5473424  0.06333658 0.93121675 0.79132045]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here
b = np.random.randint(1,2, size=(5,2,3))


#### 6. Print *b*.


In [8]:
# your code here
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here

print(a.shape)
print(b.shape)

(2, 3, 5)
(5, 2, 3)


#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here
c=a+b
#can't due to different sizes

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [17]:
# your code here
c_1=np.transpose(b)
print(c_1.shape)
#print(c)

c_2=np.matrix.transpose(b)
print(c_2.shape)

c=np.reshape(b, (2,3,5)) #o fred fez com o reshape
print(c.shape)
print(c)

#don't get it???

(3, 2, 5)
(3, 2, 5)
(2, 3, 5)
[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# your code/answer here
d=a+c

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# your code/answer here
print(a.shape, "\n", a, "\n")
print(d.shape, "\n", d)

#array d is +1

(2, 3, 5) 
 [[[0.80678089 0.09220707 0.18819284 0.46779093 0.70287639]
  [0.93967745 0.35702858 0.36223304 0.67969605 0.37456895]
  [0.95679172 0.38430446 0.35434784 0.96744837 0.88117117]]

 [[0.90656561 0.80539828 0.93508508 0.71852918 0.16634225]
  [0.96647788 0.87880759 0.72347082 0.83495002 0.80545848]
  [0.77898709 0.5473424  0.06333658 0.93121675 0.79132045]]] 

(2, 3, 5) 
 [[[1.80678089 1.09220707 1.18819284 1.46779093 1.70287639]
  [1.93967745 1.35702858 1.36223304 1.67969605 1.37456895]
  [1.95679172 1.38430446 1.35434784 1.96744837 1.88117117]]

 [[1.90656561 1.80539828 1.93508508 1.71852918 1.16634225]
  [1.96647788 1.87880759 1.72347082 1.83495002 1.80545848]
  [1.77898709 1.5473424  1.06333658 1.93121675 1.79132045]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
# your code here
#e=np.matmul(a,c)
#e=np.dot(a,c) 
e=a*c #How if the two matrix have the same size? 
print(e)

[[[0.80678089 0.09220707 0.18819284 0.46779093 0.70287639]
  [0.93967745 0.35702858 0.36223304 0.67969605 0.37456895]
  [0.95679172 0.38430446 0.35434784 0.96744837 0.88117117]]

 [[0.90656561 0.80539828 0.93508508 0.71852918 0.16634225]
  [0.96647788 0.87880759 0.72347082 0.83495002 0.80545848]
  [0.77898709 0.5473424  0.06333658 0.93121675 0.79132045]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [16]:
# your code/answer here
print(a)
print(e)

#equal due to c beeing just one's 

[[[0.80678089 0.09220707 0.18819284 0.46779093 0.70287639]
  [0.93967745 0.35702858 0.36223304 0.67969605 0.37456895]
  [0.95679172 0.38430446 0.35434784 0.96744837 0.88117117]]

 [[0.90656561 0.80539828 0.93508508 0.71852918 0.16634225]
  [0.96647788 0.87880759 0.72347082 0.83495002 0.80545848]
  [0.77898709 0.5473424  0.06333658 0.93121675 0.79132045]]]
[[[0.80678089 0.09220707 0.18819284 0.46779093 0.70287639]
  [0.93967745 0.35702858 0.36223304 0.67969605 0.37456895]
  [0.95679172 0.38430446 0.35434784 0.96744837 0.88117117]]

 [[0.90656561 0.80539828 0.93508508 0.71852918 0.16634225]
  [0.96647788 0.87880759 0.72347082 0.83495002 0.80545848]
  [0.77898709 0.5473424  0.06333658 0.93121675 0.79132045]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [19]:
# your code here
d_max=d.max()
d_min=d.min()
d_mean=d.mean()
print(d_max, d_min, d_mean)

1.9674483726406324 1.063336576526797 1.6456134735884114


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [20]:
# your code here
f=np.empty([2,3,5])
f

array([[[0.80678089, 0.09220707, 0.18819284, 0.46779093, 0.70287639],
        [0.93967745, 0.35702858, 0.36223304, 0.67969605, 0.37456895],
        [0.95679172, 0.38430446, 0.35434784, 0.96744837, 0.88117117]],

       [[0.90656561, 0.80539828, 0.93508508, 0.71852918, 0.16634225],
        [0.96647788, 0.87880759, 0.72347082, 0.83495002, 0.80545848],
        [0.77898709, 0.5473424 , 0.06333658, 0.93121675, 0.79132045]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [32]:
x=-1
for matrix in d:
    x=x+1
    print(x)
    print(d[x])
    

0
[[1.80678089 1.09220707 1.18819284 1.46779093 1.70287639]
 [1.93967745 1.35702858 1.36223304 1.67969605 1.37456895]
 [1.95679172 1.38430446 1.35434784 1.96744837 1.88117117]]
1
[[1.90656561 1.80539828 1.93508508 1.71852918 1.16634225]
 [1.96647788 1.87880759 1.72347082 1.83495002 1.80545848]
 [1.77898709 1.5473424  1.06333658 1.93121675 1.79132045]]


In [42]:
# your code here
x=-1
y=-1
z=-1

for matrix in d:
    x=x+1
    y=-1
    for m in matrix:
        y=y+1
        z=-1
        for l in m:
            z=z+1
            if l>d_min and l<d_mean:
                f[x,y,z]=25
            elif l>d_mean and l<d_max:
                f[x,y,z]=75
            elif l==d_mean:
                f[x,y,z]=50
            elif l==d_min:
                f[x,y,z]=0
            elif l==d_max:
                f[x,y,z]=100

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [44]:
# your code here
print(d)
print("\n", "d_min:",d_min," d_mean:",d_mean," d_max:",d_max, "\n")
print(f)

[[[1.80678089 1.09220707 1.18819284 1.46779093 1.70287639]
  [1.93967745 1.35702858 1.36223304 1.67969605 1.37456895]
  [1.95679172 1.38430446 1.35434784 1.96744837 1.88117117]]

 [[1.90656561 1.80539828 1.93508508 1.71852918 1.16634225]
  [1.96647788 1.87880759 1.72347082 1.83495002 1.80545848]
  [1.77898709 1.5473424  1.06333658 1.93121675 1.79132045]]]

 d_min: 1.063336576526797  d_mean: 1.6456134735884114  d_max: 1.9674483726406324 

[[[ 75.  25.  25.  25.  75.]
  [ 75.  25.  25.  75.  25.]
  [ 75.  25.  25. 100.  75.]]

 [[ 75.  75.  75.  75.  25.]
  [ 75.  75.  75.  75.  75.]
  [ 75.  25.   0.  75.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [47]:
# your code here
x=-1
y=-1
z=-1
f_bonus=np.zeros([2,3,5])

for matrix in d:
    x=x+1
    y=-1
    for m in matrix:
        y=y+1
        z=-1
        for l in m:
            z=z+1
            if l>d_min and l<d_mean:
                f_bonus[x,y,z]="B"
            elif l>d_mean and l<d_max:
                f_bonus[x,y,z]="D"
            elif l==d_mean:
                f_bonus[x,y,z]="C"
            elif l==d_min:
                f_bonus[x,y,z]="A"
            elif l==d_max:
                f_bonus[x,y,z]="E"
                
prinf(f_bonus)

ValueError: could not convert string to float: 'D'