# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here

print(np.version.version)

1.19.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [28]:
# Method 1

a = rand2 = np.random.rand(2,3,5)
a

array([[[0.0128114 , 0.92039109, 0.20330219, 0.18537711, 0.85330668],
        [0.1568059 , 0.31645932, 0.97561248, 0.93097352, 0.90644725],
        [0.43469894, 0.15694354, 0.74663826, 0.63950427, 0.65167282]],

       [[0.03668062, 0.32397787, 0.72241255, 0.27586052, 0.09042981],
        [0.12452312, 0.93956808, 0.87186631, 0.75051532, 0.2342404 ],
        [0.31506624, 0.9633675 , 0.51898155, 0.43470784, 0.40012241]]])

In [27]:
# Method 2



my_array = np.random.randn(2,3,5)
my_array

array([[[ 0.45077071, -2.51020498, -1.3122317 ,  0.41636435,
          0.23305855],
        [ 0.27106841,  0.98552906,  0.37547123, -0.67370566,
          1.04466626],
        [ 1.47004088,  0.2896203 ,  0.78801254, -0.86453993,
          0.81888224]],

       [[-0.35411381,  0.48133379,  0.31195921,  0.84068887,
          0.80752127],
        [-0.07665791, -0.76260277, -0.93832138, -0.82124624,
         -1.00168198],
        [ 0.73884805, -0.60837219, -1.01856594, -0.27155835,
          0.40457506]]])

In [26]:
# Method 3

my_array = np.random.randint(0,100,(2,3,5))
my_array

array([[[93, 42, 36, 15, 58],
        [97, 35, 39,  7, 36],
        [76, 42, 88, 80,  4]],

       [[28, 75, 92, 61, 51],
        [86, 82,  4, 71, 26],
        [14, 13, 40, 28, 59]]])

#### 4. Print *a*.


In [29]:
# your code here

display(a)

array([[[0.0128114 , 0.92039109, 0.20330219, 0.18537711, 0.85330668],
        [0.1568059 , 0.31645932, 0.97561248, 0.93097352, 0.90644725],
        [0.43469894, 0.15694354, 0.74663826, 0.63950427, 0.65167282]],

       [[0.03668062, 0.32397787, 0.72241255, 0.27586052, 0.09042981],
        [0.12452312, 0.93956808, 0.87186631, 0.75051532, 0.2342404 ],
        [0.31506624, 0.9633675 , 0.51898155, 0.43470784, 0.40012241]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [30]:
# your code here

b = np.full((5,2,3),1)

#### 6. Print *b*.


In [31]:
# your code here

display(b)

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [35]:
# your code here

np.shape(a) == np.shape(b)

False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [36]:
# your answer here

a + b

# ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [41]:
# your code here

# c = np.transpose(b)
c = b.reshape(2,3,5)
print(np.shape(c))
c

(2, 3, 5)


array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [43]:
# your code/answer here

d = a + c
print(d)

# works because theyre the same shape

[[[1.0128114  1.92039109 1.20330219 1.18537711 1.85330668]
  [1.1568059  1.31645932 1.97561248 1.93097352 1.90644725]
  [1.43469894 1.15694354 1.74663826 1.63950427 1.65167282]]

 [[1.03668062 1.32397787 1.72241255 1.27586052 1.09042981]
  [1.12452312 1.93956808 1.87186631 1.75051532 1.2342404 ]
  [1.31506624 1.9633675  1.51898155 1.43470784 1.40012241]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [45]:
# your code/answer here

display(a)
display(d)

# array d is array a plus 1

array([[[0.0128114 , 0.92039109, 0.20330219, 0.18537711, 0.85330668],
        [0.1568059 , 0.31645932, 0.97561248, 0.93097352, 0.90644725],
        [0.43469894, 0.15694354, 0.74663826, 0.63950427, 0.65167282]],

       [[0.03668062, 0.32397787, 0.72241255, 0.27586052, 0.09042981],
        [0.12452312, 0.93956808, 0.87186631, 0.75051532, 0.2342404 ],
        [0.31506624, 0.9633675 , 0.51898155, 0.43470784, 0.40012241]]])

array([[[1.0128114 , 1.92039109, 1.20330219, 1.18537711, 1.85330668],
        [1.1568059 , 1.31645932, 1.97561248, 1.93097352, 1.90644725],
        [1.43469894, 1.15694354, 1.74663826, 1.63950427, 1.65167282]],

       [[1.03668062, 1.32397787, 1.72241255, 1.27586052, 1.09042981],
        [1.12452312, 1.93956808, 1.87186631, 1.75051532, 1.2342404 ],
        [1.31506624, 1.9633675 , 1.51898155, 1.43470784, 1.40012241]]])

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [47]:
# your code here

e = a*c
display(e)

array([[[0.0128114 , 0.92039109, 0.20330219, 0.18537711, 0.85330668],
        [0.1568059 , 0.31645932, 0.97561248, 0.93097352, 0.90644725],
        [0.43469894, 0.15694354, 0.74663826, 0.63950427, 0.65167282]],

       [[0.03668062, 0.32397787, 0.72241255, 0.27586052, 0.09042981],
        [0.12452312, 0.93956808, 0.87186631, 0.75051532, 0.2342404 ],
        [0.31506624, 0.9633675 , 0.51898155, 0.43470784, 0.40012241]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [48]:
# your code/answer here

e == a

# yes because it multiplied by 1

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [51]:
# your code here

d_max = d.max()
d_min = d.min()
d_mean = np.mean(d)

print(d_max, d_min, d_mean)

1.9756124829261288 1.01281139550129 1.5031088291130312


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [52]:
# your code here

f = np.empty((2,3,5))
f

array([[[0.0128114 , 0.92039109, 0.20330219, 0.18537711, 0.85330668],
        [0.1568059 , 0.31645932, 0.97561248, 0.93097352, 0.90644725],
        [0.43469894, 0.15694354, 0.74663826, 0.63950427, 0.65167282]],

       [[0.03668062, 0.32397787, 0.72241255, 0.27586052, 0.09042981],
        [0.12452312, 0.93956808, 0.87186631, 0.75051532, 0.2342404 ],
        [0.31506624, 0.9633675 , 0.51898155, 0.43470784, 0.40012241]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [61]:
# your code here

f1 = 25 * (d > d_min) * (d < d_mean) + 75 * (d < d_max) * (d > d_mean) + 0 * (d == d_min) + 100 * (d == d_max)
f1
                



array([[[  0,  75,  25,  25,  75],
        [ 25,  25, 100,  75,  75],
        [ 25,  25,  75,  75,  75]],

       [[ 25,  25,  75,  25,  25],
        [ 25,  75,  75,  75,  25],
        [ 25,  75,  75,  25,  25]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [62]:
# your code here

display(d)
display(f1)

array([[[1.0128114 , 1.92039109, 1.20330219, 1.18537711, 1.85330668],
        [1.1568059 , 1.31645932, 1.97561248, 1.93097352, 1.90644725],
        [1.43469894, 1.15694354, 1.74663826, 1.63950427, 1.65167282]],

       [[1.03668062, 1.32397787, 1.72241255, 1.27586052, 1.09042981],
        [1.12452312, 1.93956808, 1.87186631, 1.75051532, 1.2342404 ],
        [1.31506624, 1.9633675 , 1.51898155, 1.43470784, 1.40012241]]])

array([[[  0,  75,  25,  25,  75],
        [ 25,  25, 100,  75,  75],
        [ 25,  25,  75,  75,  75]],

       [[ 25,  25,  75,  25,  25],
        [ 25,  75,  75,  75,  25],
        [ 25,  75,  75,  25,  25]]])

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [63]:
# your code here

f2 = [[['B' if d_min<item<d_mean else 'D' if d_mean<item< d_max else 'A' if item == d_min else 'E' for item in in_list] for in_list in out_list] for out_list in d]

In [64]:
f2

[[['A', 'D', 'B', 'B', 'D'],
  ['B', 'B', 'E', 'D', 'D'],
  ['B', 'B', 'D', 'D', 'D']],
 [['B', 'B', 'D', 'B', 'B'],
  ['B', 'D', 'D', 'D', 'B'],
  ['B', 'D', 'D', 'B', 'B']]]