# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np


#### 2. Print your NumPy version.

In [5]:
print(np.__version__)

1.23.3


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [6]:
a = np.random.rand(2,3,5)

print(a)

[[[0.35478779 0.68012313 0.01186611 0.24592223 0.13942535]
  [0.62735522 0.23690968 0.57232244 0.22583718 0.66678275]
  [0.42847574 0.11517624 0.84417579 0.71587455 0.56203263]]

 [[0.07823134 0.71637799 0.27060928 0.46807413 0.42495236]
  [0.23208552 0.38191812 0.19775277 0.66375882 0.94148797]
  [0.18755324 0.02221066 0.35036304 0.12112755 0.64214376]]]


In [8]:
a = np.random.random(size=(2,3,5))

print(a)

[[[0.32330878 0.47366845 0.95019502 0.69988669 0.20470374]
  [0.46763005 0.80798573 0.0942514  0.83267225 0.39933   ]
  [0.48981383 0.21587732 0.65703642 0.2230791  0.73045912]]

 [[0.1987434  0.12479529 0.30504474 0.29160984 0.52523072]
  [0.32503454 0.04806165 0.37872718 0.43788032 0.13345645]
  [0.81430268 0.38438816 0.72771697 0.53126271 0.83945921]]]


In [5]:
a = np.random.randint(7, size=(2,3,5))
print(a)

[[[0 4 1 4 3]
  [4 4 6 4 0]
  [6 4 2 2 0]]

 [[5 5 3 0 4]
  [4 5 5 3 1]
  [2 6 4 4 0]]]


#### 4. Print *a*.


In [47]:
print(a)

[[[0 4 1 4 3]
  [4 4 6 4 0]
  [6 4 2 2 0]]

 [[5 5 3 0 4]
  [4 5 5 3 1]
  [2 6 4 4 0]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [48]:
b = np.ones(shape=(5,2,3))

#### 6. Print *b*.


In [49]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [50]:
a.shape == b.shape
# No.

False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [51]:
a + b

#ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 
#They don't have the same shape.

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [52]:
c = np.transpose(b).reshape(2,3,5)
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [53]:
d = a + c
d

##They now have the same shape.

array([[[1., 5., 2., 5., 4.],
        [5., 5., 7., 5., 1.],
        [7., 5., 3., 3., 1.]],

       [[6., 6., 4., 1., 5.],
        [5., 6., 6., 4., 2.],
        [3., 7., 5., 5., 1.]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [54]:
print(a)
print('---')
print(d)

## Values in d are equal to a+1 (a+c)


[[[0 4 1 4 3]
  [4 4 6 4 0]
  [6 4 2 2 0]]

 [[5 5 3 0 4]
  [4 5 5 3 1]
  [2 6 4 4 0]]]
---
[[[1. 5. 2. 5. 4.]
  [5. 5. 7. 5. 1.]
  [7. 5. 3. 3. 1.]]

 [[6. 6. 4. 1. 5.]
  [5. 6. 6. 4. 2.]
  [3. 7. 5. 5. 1.]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [55]:
e = a * c
e

array([[[0., 4., 1., 4., 3.],
        [4., 4., 6., 4., 0.],
        [6., 4., 2., 2., 0.]],

       [[5., 5., 3., 0., 4.],
        [4., 5., 5., 3., 1.],
        [2., 6., 4., 4., 0.]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [56]:
e == a

#Yes, because values in c are equal to 1

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [26]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

print(d_max)
print(d_min)
print(d_mean)

7.0
1.0
4.166666666666667


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [57]:
d

array([[[1., 5., 2., 5., 4.],
        [5., 5., 7., 5., 1.],
        [7., 5., 3., 3., 1.]],

       [[6., 6., 4., 1., 5.],
        [5., 6., 6., 4., 2.],
        [3., 7., 5., 5., 1.]]])

In [58]:
f = np.empty(shape=(2,3,5), like=d)

print(f)

[[[1. 5. 2. 5. 4.]
  [5. 5. 7. 5. 1.]
  [7. 5. 3. 3. 1.]]

 [[6. 6. 4. 1. 5.]
  [5. 6. 6. 4. 2.]
  [3. 7. 5. 5. 1.]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*.

If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. 

If a value equals to *d_mean*, assign 50 to the corresponding value in *f*.

Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*.

Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. 

In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [59]:
#but 

f[(d > d.min()) & (d < d.mean())] = 25

f[(d > d.mean()) & (d < d.max())] = 75

f[(d == d.mean())] = 50

f[(d == d.min())] = 0

f[(d == d.max())] = 100



#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [60]:
print(d)

print(f)

[[[1. 5. 2. 5. 4.]
  [5. 5. 7. 5. 1.]
  [7. 5. 3. 3. 1.]]

 [[6. 6. 4. 1. 5.]
  [5. 6. 6. 4. 2.]
  [3. 7. 5. 5. 1.]]]
[[[  0.  75.  25.  75.  25.]
  [ 75.  75. 100.  75.   0.]
  [100.  75.  25.  25.   0.]]

 [[ 75.  75.  25.   0.  75.]
  [ 75.  75.  75.  25.  25.]
  [ 25. 100.  75.  75.   0.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here