# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [2]:
print(np.__version__)

1.18.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
a = np.random.random((2,3,5))
print(a)

[[[0.4101027  0.29028974 0.25851331 0.19759076 0.72674168]
  [0.66766064 0.63432104 0.80771975 0.14268837 0.88884229]
  [0.37976013 0.22431117 0.11950838 0.13993731 0.77643685]]

 [[0.54091913 0.63070917 0.4865817  0.73077443 0.60952539]
  [0.24398214 0.34243418 0.13989741 0.90496226 0.81854689]
  [0.49389009 0.17733456 0.63607102 0.5433711  0.64039263]]]


In [4]:
a2 = np.random.rand(2,3,5)
print(a2)

[[[0.97049319 0.986191   0.93636048 0.1912698  0.87892175]
  [0.74571166 0.3912137  0.4045498  0.40154949 0.17415033]
  [0.98725434 0.06893559 0.85287044 0.61784705 0.34646845]]

 [[0.13886108 0.3458888  0.82181051 0.49459155 0.30129082]
  [0.14747404 0.54813297 0.36900531 0.67956562 0.45156521]
  [0.24588671 0.21778005 0.17359163 0.21620194 0.13354761]]]


In [5]:
# Method 3

#### 4. Print *a*.


In [6]:
print(a)

[[[0.4101027  0.29028974 0.25851331 0.19759076 0.72674168]
  [0.66766064 0.63432104 0.80771975 0.14268837 0.88884229]
  [0.37976013 0.22431117 0.11950838 0.13993731 0.77643685]]

 [[0.54091913 0.63070917 0.4865817  0.73077443 0.60952539]
  [0.24398214 0.34243418 0.13989741 0.90496226 0.81854689]
  [0.49389009 0.17733456 0.63607102 0.5433711  0.64039263]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [22]:
b = np.ones((5,2,3))

#### 6. Print *b*.


In [23]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
is_same_size = np.multiply(a,b)
print(is_same_size)
#operands could not be broadcast together with shapes (2,3,5) (5,2,3) ----> Different shapes! Different sizes!

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# In order to combine (i.e. multiply, subtract, sum....) 2 arrays they must have the same shape!!

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [29]:
c = np.transpose(b)
print(c)
print(np.shape(c))
print(np.shape(a))

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
(3, 2, 5)
(2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [27]:
print(a.shape)
print(b.shape)
print(c.shape)
d = np.sum(a,c)

# In order to combine (i.e. multiply, subtract, sum....) 2 arrays they must have the same shape!!

#d = np.sum(a,c) ---> Error, shapes are different

(2, 3, 5)
(5, 2, 3)
(3, 2, 5)


TypeError: only integer scalar arrays can be converted to a scalar index

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [26]:
print(a)
# array a --> is 2x3x5 3-dimensional array ---> 2 groups of arrays, consisted in 3 lines each group and 5 columns each group
print(d)
# array b --> is 5x2x3 3-dimensional array ---> 5 groups of arrays, consisted in 2 lines each group and 3 columns each group

print(type(a))
print(type(d))

print(a[0,0,0])
print(d[0,0,0])

print(type(a[0,0,0]))
print(type(d[0,0,0]))

#Both single values of each array, in this case, are considered floats

[[[0.4101027  0.29028974 0.25851331 0.19759076 0.72674168]
  [0.66766064 0.63432104 0.80771975 0.14268837 0.88884229]
  [0.37976013 0.22431117 0.11950838 0.13993731 0.77643685]]

 [[0.54091913 0.63070917 0.4865817  0.73077443 0.60952539]
  [0.24398214 0.34243418 0.13989741 0.90496226 0.81854689]
  [0.49389009 0.17733456 0.63607102 0.5433711  0.64039263]]]


NameError: name 'd' is not defined

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [15]:
e = np.multiply(c,b)
print(np.shape(a))
print(np.shape(c))

ValueError: operands could not be broadcast together with shapes (3,2,5) (5,2,3) 

#### 13. Does *e* equal to *a*? Why or why not?


In [ ]:
# a is 2x3x5
# b 5x2x3
# c 3x2x5 

print(np.shape(a))
print(np.shape(b))
print(np.shape(c))


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [ ]:
# your code here

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [ ]:
# your code here

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here