# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [40]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [41]:
# your code here
print(np.__version__)

1.21.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [42]:
# Method 1
a = np.random.random((2,3,5))
print(a)

[[[0.63475785 0.07023346 0.89769226 0.18872305 0.52734128]
  [0.42214279 0.1255481  0.7494775  0.92450562 0.74191894]
  [0.59677739 0.52094622 0.03568333 0.7515987  0.48764261]]

 [[0.16855153 0.54065334 0.81485219 0.71136769 0.26171642]
  [0.83101237 0.53026104 0.5640824  0.54862905 0.3396111 ]
  [0.3973555  0.51678714 0.28178826 0.84288815 0.41775809]]]


In [43]:
# Method 2
b = np.random.random((3,5,2))
b
a1 = b.reshape(2,3,5)
print(a1)

[[[0.77853671 0.54376183 0.50790989 0.52955968 0.62765371]
  [0.41937002 0.79115428 0.57621345 0.13286514 0.43089293]
  [0.54909533 0.5206272  0.91595043 0.38834749 0.27508427]]

 [[0.98383885 0.68151321 0.16838764 0.15375594 0.77614466]
  [0.87511026 0.36214429 0.41571778 0.77227912 0.36389367]
  [0.85378279 0.79799634 0.76141869 0.93383989 0.09077881]]]


In [44]:
# Method 3
a2= []
for i in range(2):
    a2.append(np.random.random((3,5)))
print(a2)

[array([[0.51207424, 0.08450342, 0.79957011, 0.29532223, 0.49888214],
       [0.08269897, 0.89506592, 0.22688061, 0.43150162, 0.51841886],
       [0.41548272, 0.17159028, 0.78754198, 0.4204652 , 0.55675119]]), array([[0.75389495, 0.61333689, 0.68612341, 0.86791207, 0.46245492],
       [0.97143763, 0.65369454, 0.72027341, 0.80474816, 0.90599076],
       [0.2827842 , 0.98906116, 0.66761988, 0.46506845, 0.86515535]])]


#### 4. Print *a*.


In [45]:
# your code here
print(a)

[[[0.63475785 0.07023346 0.89769226 0.18872305 0.52734128]
  [0.42214279 0.1255481  0.7494775  0.92450562 0.74191894]
  [0.59677739 0.52094622 0.03568333 0.7515987  0.48764261]]

 [[0.16855153 0.54065334 0.81485219 0.71136769 0.26171642]
  [0.83101237 0.53026104 0.5640824  0.54862905 0.3396111 ]
  [0.3973555  0.51678714 0.28178826 0.84288815 0.41775809]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [46]:
# your code here
b= np.ones([5,2,3], dtype=int)

#### 6. Print *b*.


In [47]:
# your code here
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [48]:
# your code here
a_size=a.size
b_size=b.size

if a_size == b_size:
    print("a and b have the same size")

a and b have the same size


#### 8. Are you able to add *a* and *b*? Why or why not?


In [49]:
# your answer here
a_shape=a.shape
b_shape=b.shape

print(a_shape,b_shape)

if a_shape == b_shape:
    print("It's possible to sum the tables if they have the same shape")
else:
    print("It's not possible to sum the tables because they don't have the same shape")

(2, 3, 5) (5, 2, 3)
It's not possible to sum the tables because they don't have the same shape


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [60]:
# your code here
c= b.transpose((1,2,0))
print(c)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [61]:
# your code/answer here
d= a+c
print(d)
print("It words because the two tables now have the same shape")

[[[1.63475785 1.07023346 1.89769226 1.18872305 1.52734128]
  [1.42214279 1.1255481  1.7494775  1.92450562 1.74191894]
  [1.59677739 1.52094622 1.03568333 1.7515987  1.48764261]]

 [[1.16855153 1.54065334 1.81485219 1.71136769 1.26171642]
  [1.83101237 1.53026104 1.5640824  1.54862905 1.3396111 ]
  [1.3973555  1.51678714 1.28178826 1.84288815 1.41775809]]]
It words because the two tables now have the same shape


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [62]:
# your code/answer here
print(a)
print(d)
print(d[0, 0, 0] == (a[0, 0, 0]+c[0, 0, 0]))
print(d.shape == a.shape == c.shape)
print("d has the same shape as a and c, and each value is the sum of the values in the same position in array a and c")

[[[0.63475785 0.07023346 0.89769226 0.18872305 0.52734128]
  [0.42214279 0.1255481  0.7494775  0.92450562 0.74191894]
  [0.59677739 0.52094622 0.03568333 0.7515987  0.48764261]]

 [[0.16855153 0.54065334 0.81485219 0.71136769 0.26171642]
  [0.83101237 0.53026104 0.5640824  0.54862905 0.3396111 ]
  [0.3973555  0.51678714 0.28178826 0.84288815 0.41775809]]]
[[[1.63475785 1.07023346 1.89769226 1.18872305 1.52734128]
  [1.42214279 1.1255481  1.7494775  1.92450562 1.74191894]
  [1.59677739 1.52094622 1.03568333 1.7515987  1.48764261]]

 [[1.16855153 1.54065334 1.81485219 1.71136769 1.26171642]
  [1.83101237 1.53026104 1.5640824  1.54862905 1.3396111 ]
  [1.3973555  1.51678714 1.28178826 1.84288815 1.41775809]]]
True
True
d has the same shape as a and c, and each value is the sum of the values in the same position in array a and c


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [63]:
# your code here
e = a*c
print(e)

[[[0.63475785 0.07023346 0.89769226 0.18872305 0.52734128]
  [0.42214279 0.1255481  0.7494775  0.92450562 0.74191894]
  [0.59677739 0.52094622 0.03568333 0.7515987  0.48764261]]

 [[0.16855153 0.54065334 0.81485219 0.71136769 0.26171642]
  [0.83101237 0.53026104 0.5640824  0.54862905 0.3396111 ]
  [0.3973555  0.51678714 0.28178826 0.84288815 0.41775809]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [64]:
# your code/answer here
e_shape= e.shape
e_size= e.size

a_shape= a.shape
a_size= a.size

if e_shape == a_shape:
    print("a and e have the same shape")
else: 
        print("a and e have different shapes")

if e_size == a_size:
    print("a and e have the same size")
else: 
        print("a and e have different sizes")

print("a can only be multiplied with an array of the same shape, hence giving an array with the same shape as well")


a and e have the same shape
a and e have the same size
a can only be multiplied with an array of the same shape, hence giving an array with the same shape as well


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [65]:
# your code here
d_max = d.max()
d_min = d.min()
d_mean = d.mean()
print(d_max, d_min, d_mean)

1.9245056159994083 1.0356833264061782 1.5147434450358062


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [66]:
# your code here
f = np.empty(shape = d.shape, dtype=float)
print(f)

[[[0.63475785 0.07023346 0.89769226 0.18872305 0.52734128]
  [0.42214279 0.1255481  0.7494775  0.92450562 0.74191894]
  [0.59677739 0.52094622 0.03568333 0.7515987  0.48764261]]

 [[0.16855153 0.54065334 0.81485219 0.71136769 0.26171642]
  [0.83101237 0.53026104 0.5640824  0.54862905 0.3396111 ]
  [0.3973555  0.51678714 0.28178826 0.84288815 0.41775809]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [73]:
# your code here
#My responde for my array d
shape= d.shape
print(shape)

for g in range(0,shape[0]):
    for l in range (0,shape[1]):
        for e in range (0,shape[2]):
            if d[g,l,e] > d_min and d[g,l,e] < d_mean:
                f[g,l,e] = 25
            elif d[g,l,e] > d_mean and d[g,l,e] < d_max:
                f[g,l,e] = 75
            elif d[g,l,e] == d_mean:
                f[g,l,e] = 50
            elif d[g,l,e] == d_min:
                f[g,l,e] = 0
            else:
                f[g,l,e] = 100
f        

(2, 3, 5)


array([[[ 75.,  25.,  75.,  25.,  75.],
        [ 25.,  25.,  75., 100.,  75.],
        [ 75.,  75.,   0.,  75.,  25.]],

       [[ 25.,  75.,  75.,  75.,  25.],
        [ 75.,  75.,  75.,  75.,  25.],
        [ 25.,  75.,  25.,  75.,  25.]]])

In [70]:
#my test code using the example bellow
teste = np.array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

shape= teste.shape
print(shape)

for g in range(0,shape[0]):
    for l in range (0,shape[1]):
        for e in range (0,shape[2]):
            if teste[g,l,e] > teste.min() and teste[g,l,e] < teste.mean():
                f[g,l,e] = 25
            elif teste[g,l,e] > teste.mean() and teste[g,l,e] < teste.max():
                f[g,l,e] = 75
            elif teste[g,l,e] == teste.mean():
                f[g,l,e] = 50
            elif teste[g,l,e] == teste.min():
                f[g,l,e] = 0
            else:
                f[g,l,e] = 100
f   

(2, 3, 5)


array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [74]:
# your code here
print(d)
print(f)

[[[1.63475785 1.07023346 1.89769226 1.18872305 1.52734128]
  [1.42214279 1.1255481  1.7494775  1.92450562 1.74191894]
  [1.59677739 1.52094622 1.03568333 1.7515987  1.48764261]]

 [[1.16855153 1.54065334 1.81485219 1.71136769 1.26171642]
  [1.83101237 1.53026104 1.5640824  1.54862905 1.3396111 ]
  [1.3973555  1.51678714 1.28178826 1.84288815 1.41775809]]]
[[[ 75.  25.  75.  25.  75.]
  [ 25.  25.  75. 100.  75.]
  [ 75.  75.   0.  75.  25.]]

 [[ 25.  75.  75.  75.  25.]
  [ 75.  75.  75.  75.  25.]
  [ 25.  75.  25.  75.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [81]:
# your code here
#my test code using the example bellow
teste = np.array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

letter = np.empty(shape = teste.shape, dtype=str)
shape= teste.shape
print(shape)

for g in range(0,shape[0]):
    for l in range (0,shape[1]):
        for e in range (0,shape[2]):
            if teste[g,l,e] > teste.min() and teste[g,l,e] < teste.mean():
                letter[g,l,e] = "B"
            elif teste[g,l,e] > teste.mean() and teste[g,l,e] < teste.max():
                letter[g,l,e] = "D"
            elif teste[g,l,e] == teste.mean():
                letter[g,l,e] = "C"
            elif teste[g,l,e] == teste.min():
                letter[g,l,e] = "A"
            else:
                letter[g,l,e] = "E"
letter

(2, 3, 5)


array([[['D', 'D', 'D', 'B', 'D'],
        ['D', 'D', 'B', 'B', 'B'],
        ['D', 'B', 'D', 'D', 'D']],

       [['B', 'B', 'B', 'B', 'E'],
        ['D', 'D', 'D', 'D', 'D'],
        ['B', 'D', 'A', 'D', 'D']]], dtype='<U1')