# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here

import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here

print(np.__version__)

1.20.3


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [7]:
# Method 1

a = np.random.random((2,3,5))

In [52]:
# Method 2

np.random.randint(0,100,(2,3,5))

array([[[69, 63, 22, 92, 21],
        [52, 71, 67, 17, 37],
        [13, 11, 65, 25, 28]],

       [[67, 27, 23, 79, 59],
        [51, 13, 20, 77, 98],
        [44, 12, 34, 86,  5]]])

In [9]:
# Method 3

np.random.rand(2,3,5)

array([[[0.54652912, 0.06303332, 0.59880413, 0.95466667, 0.17767682],
        [0.22223993, 0.56063294, 0.89853603, 0.63337373, 0.58895529],
        [0.31583715, 0.77975092, 0.18778787, 0.35362575, 0.3592156 ]],

       [[0.5960138 , 0.74588817, 0.33268964, 0.85495825, 0.05796081],
        [0.06246964, 0.67104327, 0.35868533, 0.50762818, 0.85997883],
        [0.40217269, 0.47150548, 0.39536591, 0.42591567, 0.26648505]]])

#### 4. Print *a*.


In [10]:
# your code here

print(a)

[[[0.64004312 0.37824051 0.04749471 0.43293738 0.51457028]
  [0.01276227 0.0552294  0.10896115 0.29879214 0.11164689]
  [0.31920683 0.86686657 0.98566184 0.99255494 0.56849223]]

 [[0.62923018 0.86219421 0.60482455 0.87961069 0.3792628 ]
  [0.29639477 0.69450318 0.36539751 0.1563863  0.82398079]
  [0.70419207 0.86893083 0.96720956 0.05382023 0.38558497]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [15]:
# your code here

b = np.ones((5,2,3))

#### 6. Print *b*.


In [16]:
# your code here

print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [18]:
# your code here

a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [31]:
# your answer here

add = a + b

#no, because they have different shapes

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [29]:
# your code here

c = b.reshape((2,3,5))

c.shape == a.shape


True

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [30]:
# your code/answer here

d = a + c

d

#they now have the same shape

array([[[1.64004312, 1.37824051, 1.04749471, 1.43293738, 1.51457028],
        [1.01276227, 1.0552294 , 1.10896115, 1.29879214, 1.11164689],
        [1.31920683, 1.86686657, 1.98566184, 1.99255494, 1.56849223]],

       [[1.62923018, 1.86219421, 1.60482455, 1.87961069, 1.3792628 ],
        [1.29639477, 1.69450318, 1.36539751, 1.1563863 , 1.82398079],
        [1.70419207, 1.86893083, 1.96720956, 1.05382023, 1.38558497]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [32]:
# your code/answer here

# the values of d are exactly 1 bigger than the values of a because of our calculations before

print(a)

print(d)

[[[0.64004312 0.37824051 0.04749471 0.43293738 0.51457028]
  [0.01276227 0.0552294  0.10896115 0.29879214 0.11164689]
  [0.31920683 0.86686657 0.98566184 0.99255494 0.56849223]]

 [[0.62923018 0.86219421 0.60482455 0.87961069 0.3792628 ]
  [0.29639477 0.69450318 0.36539751 0.1563863  0.82398079]
  [0.70419207 0.86893083 0.96720956 0.05382023 0.38558497]]]
[[[1.64004312 1.37824051 1.04749471 1.43293738 1.51457028]
  [1.01276227 1.0552294  1.10896115 1.29879214 1.11164689]
  [1.31920683 1.86686657 1.98566184 1.99255494 1.56849223]]

 [[1.62923018 1.86219421 1.60482455 1.87961069 1.3792628 ]
  [1.29639477 1.69450318 1.36539751 1.1563863  1.82398079]
  [1.70419207 1.86893083 1.96720956 1.05382023 1.38558497]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [34]:
# your code here

e = a * c

e

array([[[0.64004312, 0.37824051, 0.04749471, 0.43293738, 0.51457028],
        [0.01276227, 0.0552294 , 0.10896115, 0.29879214, 0.11164689],
        [0.31920683, 0.86686657, 0.98566184, 0.99255494, 0.56849223]],

       [[0.62923018, 0.86219421, 0.60482455, 0.87961069, 0.3792628 ],
        [0.29639477, 0.69450318, 0.36539751, 0.1563863 , 0.82398079],
        [0.70419207, 0.86893083, 0.96720956, 0.05382023, 0.38558497]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [35]:
# your code/answer here

# when you multiply a value by 1 it stays the same

e == a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [36]:
# your code here
d_max = d.max()

d_min = d.min()

d_mean = d.mean()

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [45]:
# your code here

f = np.empty((2,3,5))


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [47]:
# your code here

for i in d:
    if i > d_min and i < d_mean:
        f.append(i)
    elif i > d_mean and i < d_max:
        f.append(i)
    elif i == d_mean:
        f.append(i)
    else:
        f.append(0)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [48]:
# your code here

print(d)

print(f)

[[[1.64004312 1.37824051 1.04749471 1.43293738 1.51457028]
  [1.01276227 1.0552294  1.10896115 1.29879214 1.11164689]
  [1.31920683 1.86686657 1.98566184 1.99255494 1.56849223]]

 [[1.62923018 1.86219421 1.60482455 1.87961069 1.3792628 ]
  [1.29639477 1.69450318 1.36539751 1.1563863  1.82398079]
  [1.70419207 1.86893083 1.96720956 1.05382023 1.38558497]]]
[[[0.64004312 0.37824051 0.04749471 0.43293738 0.51457028]
  [0.01276227 0.0552294  0.10896115 0.29879214 0.11164689]
  [0.31920683 0.86686657 0.98566184 0.99255494 0.56849223]]

 [[0.62923018 0.86219421 0.60482455 0.87961069 0.3792628 ]
  [0.29639477 0.69450318 0.36539751 0.1563863  0.82398079]
  [0.70419207 0.86893083 0.96720956 0.05382023 0.38558497]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here