# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.__version__)

1.18.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a = np.random.random((2,3,5))
print(a)

[[[0.08832715 0.70242548 0.81582906 0.29254103 0.50835376]
  [0.98317054 0.64037497 0.50975059 0.23016932 0.2108094 ]
  [0.99160815 0.5784684  0.61276057 0.75951847 0.23430639]]

 [[0.70255466 0.89158198 0.07747746 0.81189718 0.78379204]
  [0.377824   0.59600867 0.63696112 0.840087   0.08699353]
  [0.97223854 0.72444691 0.33644692 0.50101052 0.92408927]]]


In [4]:
# Method 2
a = np.random.rand(2,3,5)
print(a)

[[[0.24691849 0.63707649 0.01466797 0.08070047 0.989904  ]
  [0.90661713 0.9430628  0.27394017 0.80110745 0.6117039 ]
  [0.13341273 0.30367757 0.24482244 0.53808326 0.63295071]]

 [[0.38937277 0.06395861 0.64259778 0.82143006 0.49643146]
  [0.44497538 0.83781081 0.83792779 0.51824011 0.36582232]
  [0.32823457 0.81171693 0.56016933 0.48470017 0.30258598]]]


In [5]:
# Method 3
a = np.random.choice(range(0,101), size=(2,3,5))
print(a)

[[[56 92 63 29 62]
  [80 21 49 68 54]
  [52 81 39 93 65]]

 [[96  2 40 81 67]
  [51 40 47 60 45]
  [15 80 78 33 61]]]


#### 4. Print *a*.


In [6]:
# your code here
print(a)

[[[56 92 63 29 62]
  [80 21 49 68 54]
  [52 81 39 93 65]]

 [[96  2 40 81 67]
  [51 40 47 60 45]
  [15 80 78 33 61]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here
b = np.full((5,2,3), 1)

#### 6. Print *b*.


In [8]:
# your code here
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here
np.shape(a) == np.shape(b)

False

#### 8. Are you able to add *a* and *b*? Why or why not?

In [10]:
# your answer here
# No I can't, because of the different shapes. Two matrices must have an equal number of rows and columns to be added.

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here
print(np.shape(b))
c = np.transpose(b,(1,2,0))
print(np.shape(c))

(5, 2, 3)
(2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# your code/answer here
d = a + c
print(d)

[[[57 93 64 30 63]
  [81 22 50 69 55]
  [53 82 40 94 66]]

 [[97  3 41 82 68]
  [52 41 48 61 46]
  [16 81 79 34 62]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# your code/answer here
print(a)
print(d)
# Each value has been incremented by one (becasue c has one in all positions)

[[[56 92 63 29 62]
  [80 21 49 68 54]
  [52 81 39 93 65]]

 [[96  2 40 81 67]
  [51 40 47 60 45]
  [15 80 78 33 61]]]
[[[57 93 64 30 63]
  [81 22 50 69 55]
  [53 82 40 94 66]]

 [[97  3 41 82 68]
  [52 41 48 61 46]
  [16 81 79 34 62]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
# your code here
e = a * c

#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
# your code/answer here
e == a
print(e)
print(a)
# Yes, because all we did was multiply every element of a by the equivalent in c, wich is filled with ones.

[[[56 92 63 29 62]
  [80 21 49 68 54]
  [52 81 39 93 65]]

 [[96  2 40 81 67]
  [51 40 47 60 45]
  [15 80 78 33 61]]]
[[[56 92 63 29 62]
  [80 21 49 68 54]
  [52 81 39 93 65]]

 [[96  2 40 81 67]
  [51 40 47 60 45]
  [15 80 78 33 61]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
# your code here
print(d)
d_max = np.amax(d)
d_min = np.amin(d)
d_mean = np.mean(d)
print(f"max: {d_max}, min: {d_min}, mean: {d_mean}")

[[[57 93 64 30 63]
  [81 22 50 69 55]
  [53 82 40 94 66]]

 [[97  3 41 82 68]
  [52 41 48 61 46]
  [16 81 79 34 62]]]
max: 97, min: 3, mean: 57.666666666666664


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [17]:
# your code here
f = np.empty((2,3,5))
print(f)

[[[0.24691849 0.63707649 0.01466797 0.08070047 0.989904  ]
  [0.90661713 0.9430628  0.27394017 0.80110745 0.6117039 ]
  [0.13341273 0.30367757 0.24482244 0.53808326 0.63295071]]

 [[0.38937277 0.06395861 0.64259778 0.82143006 0.49643146]
  [0.44497538 0.83781081 0.83792779 0.51824011 0.36582232]
  [0.32823457 0.81171693 0.56016933 0.48470017 0.30258598]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [18]:
# your code here
#print(d)
#print(np.shape(d))
#print(d[0,0,0])
#print(d[1,0,0])
#for z in d:
#    for y in z:
#        for x in y:
#            print(x)
        
#for z in d:
#    for y in z:
#        for x in y:
#            if x > d_min and x < d_mean:
#                f[z,y,x] = 25
#            if x > d_mean and x < d_max:
#                f[z,y,x] = 75
#            if x == d_mean:
#                f[z,y,x] = 50
#            if x == d_min:
#                f[z,y,x] = 0
#            if x == d_max:
#                f[z,y,x] = 100

#f = np.where(d > d_min and d < d_mean, 25)

f = np.where((d == d_max), 100, d)
f = np.where((f > d_mean) & (f < d_max), 75, f)
f = np.where((f == d_mean), 50, f)
f = np.where((f > d_min) & (f < d_mean), 25, f)
f = np.where((f == d_min), 0, f)

#print(f)


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [19]:
# your code here
print(d)
print(f)

[[[57 93 64 30 63]
  [81 22 50 69 55]
  [53 82 40 94 66]]

 [[97  3 41 82 68]
  [52 41 48 61 46]
  [16 81 79 34 62]]]
[[[ 25  75  75  25  75]
  [ 75  25  25  75  25]
  [ 25  75  25  75  75]]

 [[100   0  25  75  75]
  [ 25  25  25  75  25]
  [ 25  75  75  25  75]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [21]:
# your code here