# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [10]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [11]:
# your code here
np.version.version

'1.20.1'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [12]:
# Method 1
a = np.random.randint(10,90,(2,3,5))
a.shape

(2, 3, 5)

In [13]:
# Method 2
a = np.random.random((2,3,5))
a

array([[[0.59199297, 0.45272262, 0.49233096, 0.59577109, 0.27489996],
        [0.56501828, 0.59156241, 0.39767627, 0.21102486, 0.96341204],
        [0.04438875, 0.02299081, 0.84970963, 0.40943689, 0.15816535]],

       [[0.65649474, 0.49560809, 0.26110976, 0.85363786, 0.21095225],
        [0.30011441, 0.49256038, 0.22184948, 0.32617303, 0.6862462 ],
        [0.2898922 , 0.66267702, 0.30583602, 0.97580189, 0.02941319]]])

In [14]:
# Method 3
a = np.random.randn(2,3,5)
a

array([[[ 0.51453283, -0.48218513,  0.18572227,  0.17632637,
          0.91836097],
        [-1.38621501,  1.66428573, -1.19848688,  1.07660261,
         -0.36829204],
        [ 0.0903728 , -0.17826103, -1.03213473, -0.04022219,
         -0.66187988]],

       [[ 0.7256722 , -0.6336865 ,  0.00332352,  2.14434243,
          0.90093089],
        [ 0.016569  ,  0.12766122, -0.18298487,  0.83897195,
         -1.56514429],
        [ 1.66574001,  0.31999601,  0.30970394,  1.57622866,
         -0.44041356]]])

#### 4. Print *a*.


In [15]:
# your code here
print(a)

[[[ 0.51453283 -0.48218513  0.18572227  0.17632637  0.91836097]
  [-1.38621501  1.66428573 -1.19848688  1.07660261 -0.36829204]
  [ 0.0903728  -0.17826103 -1.03213473 -0.04022219 -0.66187988]]

 [[ 0.7256722  -0.6336865   0.00332352  2.14434243  0.90093089]
  [ 0.016569    0.12766122 -0.18298487  0.83897195 -1.56514429]
  [ 1.66574001  0.31999601  0.30970394  1.57622866 -0.44041356]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [16]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [17]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [18]:
# your code here
a.shape == b.shape
#ver depois size of matrix eu acho que isto é shape

False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [19]:
# your answer here

# a+b

"""matrixes with different sizes can't be added, by math """

"matrixes with different sizes can't be added, by math "

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [20]:
# your code here
# print(b.shape) ## (5, 2, 3)
c = b.transpose(1,2,0) ## (1,2,0) read docs
print(c.shape)

(2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [21]:
# your code/answer here
# print(a.shape)
# print(c.shape)
d=a+c
"""it works because now both a and c have the same dimentions"""

'it works because now both a and c have the same dimentions'

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [22]:
# your code/answer here
print(a)
print(d)
"""all cells belonging to d are exatly the cells of a added by 1"""

[[[ 0.51453283 -0.48218513  0.18572227  0.17632637  0.91836097]
  [-1.38621501  1.66428573 -1.19848688  1.07660261 -0.36829204]
  [ 0.0903728  -0.17826103 -1.03213473 -0.04022219 -0.66187988]]

 [[ 0.7256722  -0.6336865   0.00332352  2.14434243  0.90093089]
  [ 0.016569    0.12766122 -0.18298487  0.83897195 -1.56514429]
  [ 1.66574001  0.31999601  0.30970394  1.57622866 -0.44041356]]]
[[[ 1.51453283  0.51781487  1.18572227  1.17632637  1.91836097]
  [-0.38621501  2.66428573 -0.19848688  2.07660261  0.63170796]
  [ 1.0903728   0.82173897 -0.03213473  0.95977781  0.33812012]]

 [[ 1.7256722   0.3663135   1.00332352  3.14434243  1.90093089]
  [ 1.016569    1.12766122  0.81701513  1.83897195 -0.56514429]
  [ 2.66574001  1.31999601  1.30970394  2.57622866  0.55958644]]]


'all cells belonging to d are exatly the cells of a added by 1'

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [23]:
# your code here
e=a*c

#### 13. Does *e* equal to *a*? Why or why not?


In [24]:
# your code/answer here
e==a
#voltar aqui

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [25]:
# your code here
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [26]:
# your code here
f = np.empty((2,3,5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [27]:
# your code here
new_f = [] 
for group in d:
    for row in group:
        for num in row:
            if (d_min < num) and (num < d_mean):
                new_f.append(25)
            elif (d_mean < num) and (num < d_max):
                new_f.append(75)
            elif (num == d_mean):
                new_f.append(50)
            elif (num == d_min):
                new_f.append(0)
            else:
                new_f.append(100)
new_f = np.reshape(new_f, d.shape)
f = new_f

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [28]:
# your code here
print(d)
print(f)

[[[ 1.51453283  0.51781487  1.18572227  1.17632637  1.91836097]
  [-0.38621501  2.66428573 -0.19848688  2.07660261  0.63170796]
  [ 1.0903728   0.82173897 -0.03213473  0.95977781  0.33812012]]

 [[ 1.7256722   0.3663135   1.00332352  3.14434243  1.90093089]
  [ 1.016569    1.12766122  0.81701513  1.83897195 -0.56514429]
  [ 2.66574001  1.31999601  1.30970394  2.57622866  0.55958644]]]
[[[ 75  25  75  75  75]
  [ 25  75  25  75  25]
  [ 25  25  25  25  25]]

 [[ 75  25  25 100  75]
  [ 25  25  25  75   0]
  [ 75  75  75  75  25]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [29]:
# your code here
# your code here
new_f = [] 
for group in d:
    for row in group:
        for num in row:
            if (d_min < num) and (num < d_mean):
                new_f.append('B')
            elif (d_mean < num) and (num < d_max):
                new_f.append('E')
            elif (num == d_mean):
                new_f.append('C')
            elif (num == d_min):
                new_f.append('A')
            else:
                new_f.append('F')
new_f = np.reshape(new_f, d.shape)
f = new_f
print(f)

[[['E' 'B' 'E' 'E' 'E']
  ['B' 'E' 'B' 'E' 'B']
  ['B' 'B' 'B' 'B' 'B']]

 [['E' 'B' 'B' 'F' 'E']
  ['B' 'B' 'B' 'E' 'A']
  ['E' 'E' 'E' 'E' 'B']]]
