# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [2]:
print(np.version.version)

1.18.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
a = np.random.random((2,3,5))
a

array([[[0.75329121, 0.42980259, 0.93093635, 0.95595571, 0.71042439],
        [0.59638091, 0.25189133, 0.55512707, 0.20082569, 0.81966581],
        [0.36312671, 0.57559127, 0.99989469, 0.53115821, 0.09703684]],

       [[0.15728171, 0.92137321, 0.24391808, 0.11461558, 0.56532416],
        [0.97705318, 0.08742166, 0.89328486, 0.30799906, 0.75879689],
        [0.88475573, 0.59787881, 0.24841687, 0.05919727, 0.79807414]]])

In [4]:
a = np.random.rand(2,3,5)
a

array([[[0.79155378, 0.3660509 , 0.07718439, 0.47956926, 0.50634182],
        [0.90804618, 0.48479904, 0.40978677, 0.78165872, 0.11643856],
        [0.45344998, 0.58075583, 0.88933874, 0.84187521, 0.76310284]],

       [[0.85695298, 0.94301408, 0.20959469, 0.7900985 , 0.43167757],
        [0.70835839, 0.92574616, 0.93317522, 0.86433147, 0.07420934],
        [0.85644582, 0.18865236, 0.65371533, 0.36725057, 0.60249802]]])

In [5]:
a = np.empty((2,3,5))
a

array([[[0.79155378, 0.3660509 , 0.07718439, 0.47956926, 0.50634182],
        [0.90804618, 0.48479904, 0.40978677, 0.78165872, 0.11643856],
        [0.45344998, 0.58075583, 0.88933874, 0.84187521, 0.76310284]],

       [[0.85695298, 0.94301408, 0.20959469, 0.7900985 , 0.43167757],
        [0.70835839, 0.92574616, 0.93317522, 0.86433147, 0.07420934],
        [0.85644582, 0.18865236, 0.65371533, 0.36725057, 0.60249802]]])

#### 4. Print *a*.


In [6]:
a

array([[[0.79155378, 0.3660509 , 0.07718439, 0.47956926, 0.50634182],
        [0.90804618, 0.48479904, 0.40978677, 0.78165872, 0.11643856],
        [0.45344998, 0.58075583, 0.88933874, 0.84187521, 0.76310284]],

       [[0.85695298, 0.94301408, 0.20959469, 0.7900985 , 0.43167757],
        [0.70835839, 0.92574616, 0.93317522, 0.86433147, 0.07420934],
        [0.85644582, 0.18865236, 0.65371533, 0.36725057, 0.60249802]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
b = np.ones((5,2,3))
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 6. Print *b*.


In [8]:
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [ ]:
"""
#wrong i think... the answer below its correct(i think)
print(a.size)
print(b.size)

size_comp = a.size - b.size
print(size_comp)
"""

In [ ]:
np.subtract(a,b)
np.multiply(a,b)

#i dont think its possible do this king of math with shapes per say, they have different shapes and sizes

#### 8. Are you able to add *a* and *b*? Why or why not?


In [ ]:
np.add(a,b)

#add_both = np.concatenate((a,b))
#add_both

#np.stack((a,b),axis=0)

# i think to combine (or do math in general) to arrays, they should have the same shape and/or size

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [16]:
print(np.size(a), np.shape(a))
print(np.size(b), np.shape(b))
print("\n")

c = np.reshape(b,(2,3,5))
print(c)
print(np.shape(a))
print(np.shape(c))

30 (2, 3, 5)
30 (5, 2, 3)


[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
(2, 3, 5)
(2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [25]:
d = np.add(a,c)
print(d)

# because NOW they have the same goddamm shape and size lol

[[[1.79155378 1.3660509  1.07718439 1.47956926 1.50634182]
  [1.90804618 1.48479904 1.40978677 1.78165872 1.11643856]
  [1.45344998 1.58075583 1.88933874 1.84187521 1.76310284]]

 [[1.85695298 1.94301408 1.20959469 1.7900985  1.43167757]
  [1.70835839 1.92574616 1.93317522 1.86433147 1.07420934]
  [1.85644582 1.18865236 1.65371533 1.36725057 1.60249802]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [31]:
print(a)
print("\n")
print(d)
print("\n")


print(type(a))
print(np.shape(a))
print(a[0,0,0])
print(type(a[0,0,0]))
print("\n")
print(type(d))
print(np.shape(d))
print(d[0,0,0])
print(type(d[0,0,0]))


# the array C as a np.ones(3-dimensional array), and we add that(sum both basically) to array A(np.random.random 3-dim array)
# that means that all values on array A get summed by 1

[[[0.79155378 0.3660509  0.07718439 0.47956926 0.50634182]
  [0.90804618 0.48479904 0.40978677 0.78165872 0.11643856]
  [0.45344998 0.58075583 0.88933874 0.84187521 0.76310284]]

 [[0.85695298 0.94301408 0.20959469 0.7900985  0.43167757]
  [0.70835839 0.92574616 0.93317522 0.86433147 0.07420934]
  [0.85644582 0.18865236 0.65371533 0.36725057 0.60249802]]]


[[[1.79155378 1.3660509  1.07718439 1.47956926 1.50634182]
  [1.90804618 1.48479904 1.40978677 1.78165872 1.11643856]
  [1.45344998 1.58075583 1.88933874 1.84187521 1.76310284]]

 [[1.85695298 1.94301408 1.20959469 1.7900985  1.43167757]
  [1.70835839 1.92574616 1.93317522 1.86433147 1.07420934]
  [1.85644582 1.18865236 1.65371533 1.36725057 1.60249802]]]


<class 'numpy.ndarray'>
(2, 3, 5)
0.7915537813334514
<class 'numpy.float64'>


<class 'numpy.ndarray'>
(2, 3, 5)
1.7915537813334514
<class 'numpy.float64'>


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [32]:
e = np.multiply(a,c)
e

array([[[0.79155378, 0.3660509 , 0.07718439, 0.47956926, 0.50634182],
        [0.90804618, 0.48479904, 0.40978677, 0.78165872, 0.11643856],
        [0.45344998, 0.58075583, 0.88933874, 0.84187521, 0.76310284]],

       [[0.85695298, 0.94301408, 0.20959469, 0.7900985 , 0.43167757],
        [0.70835839, 0.92574616, 0.93317522, 0.86433147, 0.07420934],
        [0.85644582, 0.18865236, 0.65371533, 0.36725057, 0.60249802]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [39]:
e == a

print(np.shape(a))
print(a)
print("\n")
print(np.shape(e))
print(e)


#we got E by multiplying with the array A(random) and array C(with 1's)
# since 1 is a neutral element of multiplication, its like we didnt really multiply anything, so E==A

(2, 3, 5)
[[[0.79155378 0.3660509  0.07718439 0.47956926 0.50634182]
  [0.90804618 0.48479904 0.40978677 0.78165872 0.11643856]
  [0.45344998 0.58075583 0.88933874 0.84187521 0.76310284]]

 [[0.85695298 0.94301408 0.20959469 0.7900985  0.43167757]
  [0.70835839 0.92574616 0.93317522 0.86433147 0.07420934]
  [0.85644582 0.18865236 0.65371533 0.36725057 0.60249802]]]


(2, 3, 5)
[[[0.79155378 0.3660509  0.07718439 0.47956926 0.50634182]
  [0.90804618 0.48479904 0.40978677 0.78165872 0.11643856]
  [0.45344998 0.58075583 0.88933874 0.84187521 0.76310284]]

 [[0.85695298 0.94301408 0.20959469 0.7900985  0.43167757]
  [0.70835839 0.92574616 0.93317522 0.86433147 0.07420934]
  [0.85644582 0.18865236 0.65371533 0.36725057 0.60249802]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [43]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(d_max)
print(d_min)
print(d_mean)

1.9430140821051154
1.0742093366441676
1.5951890836399734


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [48]:
f = np.empty((2,3,5))
f

array([[[0.79155378, 0.3660509 , 0.07718439, 0.47956926, 0.50634182],
        [0.90804618, 0.48479904, 0.40978677, 0.78165872, 0.11643856],
        [0.45344998, 0.58075583, 0.88933874, 0.84187521, 0.76310284]],

       [[0.85695298, 0.94301408, 0.20959469, 0.7900985 , 0.43167757],
        [0.70835839, 0.92574616, 0.93317522, 0.86433147, 0.07420934],
        [0.85644582, 0.18865236, 0.65371533, 0.36725057, 0.60249802]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [57]:
f = np.copy(d)
f[(f > d_min) & (f < d_mean)] = 25
f[(f > d_mean) & (f < d_max)] = 75
f[(f == d_mean)] = 50
f[(f == d_min)] = 0
f[(f == d_max)] = 100

print(d_max)
print(d_min)
print(d_mean)
print("\n")

print(d)
print("\n")
print(f)



1.9430140821051154
1.0742093366441676
1.5951890836399734


[[[1.79155378 1.3660509  1.07718439 1.47956926 1.50634182]
  [1.90804618 1.48479904 1.40978677 1.78165872 1.11643856]
  [1.45344998 1.58075583 1.88933874 1.84187521 1.76310284]]

 [[1.85695298 1.94301408 1.20959469 1.7900985  1.43167757]
  [1.70835839 1.92574616 1.93317522 1.86433147 1.07420934]
  [1.85644582 1.18865236 1.65371533 1.36725057 1.60249802]]]


[[[ 75.  25.  25.  25.  25.]
  [ 75.  25.  25.  75.  25.]
  [ 25.  25.  75.  75.  75.]]

 [[ 75. 100.  25.  75.  25.]
  [ 75.  75.  75.  75.   0.]
  [ 75.  25.  75.  25.  75.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [58]:
# in the exercise above

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [71]:
#np.where(condition[, x, y]). Return elements chosen from x or y depending on condition
# didnt understand this method very well, i ask for help 

l = np.where(d == d_min, "A", d)
l = np.where((d > d_min) & (d < d_mean), "B", l)
l = np.where(d == d_mean, "C", l)
l = np.where((d > d_mean) & (d < d_max), "D", l)
l = np.where(d == d_max, "E", l)

print(l)

[[['D' 'B' 'B' 'B' 'B']
  ['D' 'B' 'B' 'D' 'B']
  ['B' 'B' 'D' 'D' 'D']]

 [['D' 'E' 'B' 'D' 'B']
  ['D' 'D' 'D' 'D' 'A']
  ['D' 'B' 'D' 'B' 'D']]]
