# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.__version__)

1.16.4


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a=np.random.random((2,3,5))
print(a)

[[[0.84587921 0.29252778 0.57070497 0.65240627 0.37317908]
  [0.55788655 0.62444182 0.38204227 0.04873328 0.89902611]
  [0.4864411  0.16238665 0.33596758 0.05824694 0.67092549]]

 [[0.71687209 0.60200739 0.00283419 0.89567352 0.14441945]
  [0.46371708 0.84934601 0.49174351 0.63897446 0.53933532]
  [0.90002211 0.31320269 0.35448749 0.03827492 0.43152991]]]


In [4]:
# Method 2
np.zeros((2,3,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [5]:
# Method 3
np.arange(5)

array([0, 1, 2, 3, 4])

#### 4. Print *a*.


In [6]:
# your code here
print(a)

[[[0.84587921 0.29252778 0.57070497 0.65240627 0.37317908]
  [0.55788655 0.62444182 0.38204227 0.04873328 0.89902611]
  [0.4864411  0.16238665 0.33596758 0.05824694 0.67092549]]

 [[0.71687209 0.60200739 0.00283419 0.89567352 0.14441945]
  [0.46371708 0.84934601 0.49174351 0.63897446 0.53933532]
  [0.90002211 0.31320269 0.35448749 0.03827492 0.43152991]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here
b=np.full((5,2,3), 1)

#### 6. Print *b*.


In [8]:
# your code here
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here
print(a.size)
print(b.size)

30
30


#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here

print(a.shape)
print(b.shape)

#It's not possible to add a and b because the 3º dimention of the elements is different.

(2, 3, 5)
(5, 2, 3)


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here
c=(np.reshape(b,(2,3,5)))


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# your code/answer here
d = a + c
print(d)


[[[1.84587921 1.29252778 1.57070497 1.65240627 1.37317908]
  [1.55788655 1.62444182 1.38204227 1.04873328 1.89902611]
  [1.4864411  1.16238665 1.33596758 1.05824694 1.67092549]]

 [[1.71687209 1.60200739 1.00283419 1.89567352 1.14441945]
  [1.46371708 1.84934601 1.49174351 1.63897446 1.53933532]
  [1.90002211 1.31320269 1.35448749 1.03827492 1.43152991]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# your code/answer here
print(a)
print(d)

#The array d as bigger values than the array a as expected. 

[[[0.84587921 0.29252778 0.57070497 0.65240627 0.37317908]
  [0.55788655 0.62444182 0.38204227 0.04873328 0.89902611]
  [0.4864411  0.16238665 0.33596758 0.05824694 0.67092549]]

 [[0.71687209 0.60200739 0.00283419 0.89567352 0.14441945]
  [0.46371708 0.84934601 0.49174351 0.63897446 0.53933532]
  [0.90002211 0.31320269 0.35448749 0.03827492 0.43152991]]]
[[[1.84587921 1.29252778 1.57070497 1.65240627 1.37317908]
  [1.55788655 1.62444182 1.38204227 1.04873328 1.89902611]
  [1.4864411  1.16238665 1.33596758 1.05824694 1.67092549]]

 [[1.71687209 1.60200739 1.00283419 1.89567352 1.14441945]
  [1.46371708 1.84934601 1.49174351 1.63897446 1.53933532]
  [1.90002211 1.31320269 1.35448749 1.03827492 1.43152991]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
# your code here
e=a*c
print(e)

[[[0.84587921 0.29252778 0.57070497 0.65240627 0.37317908]
  [0.55788655 0.62444182 0.38204227 0.04873328 0.89902611]
  [0.4864411  0.16238665 0.33596758 0.05824694 0.67092549]]

 [[0.71687209 0.60200739 0.00283419 0.89567352 0.14441945]
  [0.46371708 0.84934601 0.49174351 0.63897446 0.53933532]
  [0.90002211 0.31320269 0.35448749 0.03827492 0.43152991]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
# your code/answer here
# Yes.The array e is the product of array a and c. 
# The array c is compose by 1, therefore when we multiply the array a by 1 we obtain the same result.

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
# your code here
d_max=np.max(d)
d_min=np.min(d)
d_mean=np.mean(d)

print(d_max)
print(d_min)
print(d_mean)

1.9000221112598892
1.002834191288266
1.4781078413388036


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [17]:
# your code here
f = np.empty([2,3,5], dtype = int)


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [18]:
# your code here

f[(d_min < d) & (d < d_mean)] = 25

f[(d_mean < d) & (d < d_max)] = 75

f[d == d.mean] = 50
    
f[d == d.min] = 0
    
f[d == d.max] = 100
       
                   
print((f))

[[[75 25 75 75 25]
  [75 75 25 25 75]
  [75 25 25 25 75]]

 [[75 75  0 75 25]
  [25 75 75 75 75]
  [ 0 25 25 25 25]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [19]:
# your code here
print(d)

print(f)

[[[1.84587921 1.29252778 1.57070497 1.65240627 1.37317908]
  [1.55788655 1.62444182 1.38204227 1.04873328 1.89902611]
  [1.4864411  1.16238665 1.33596758 1.05824694 1.67092549]]

 [[1.71687209 1.60200739 1.00283419 1.89567352 1.14441945]
  [1.46371708 1.84934601 1.49174351 1.63897446 1.53933532]
  [1.90002211 1.31320269 1.35448749 1.03827492 1.43152991]]]
[[[75 25 75 75 25]
  [75 75 25 25 75]
  [75 25 25 25 75]]

 [[75 75  0 75 25]
  [25 75 75 75 75]
  [ 0 25 25 25 25]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [28]:
# your code here

o = np.empty([2,3,5], dtype = str)

o[(d_min < d) & (d < d_mean)] = "A"

o[(d_mean < d) & (d < d_max)] = "B"

o[d == d.mean] = "C"
    
o[d == d.min] = "D"
    
o[d == d.max] = "E"

print(o)

[[['B' 'A' 'B' 'B' 'A']
  ['B' 'B' 'A' 'A' 'B']
  ['B' 'A' 'A' 'A' 'B']]

 [['B' 'B' '' 'B' 'A']
  ['A' 'B' 'B' 'B' 'B']
  ['' 'A' 'A' 'A' 'A']]]
