# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [136]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [137]:
# your code here
np.version.version

'1.21.5'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [138]:
# Method 1
a = np.random.random((2,3,5))

In [139]:
# Method 2
a = np.random.randn(2,3,5)

In [140]:
# Method 3
a = np.random.rand(2,3,5)

#### 4. Print *a*.


In [141]:
# your code here
print(a)

[[[0.62685931 0.19298137 0.86105538 0.77472924 0.53917686]
  [0.67607384 0.68442526 0.10560228 0.27942381 0.21414295]
  [0.02992513 0.12405569 0.81730263 0.71386705 0.88806069]]

 [[0.15564406 0.0642394  0.92646944 0.7028728  0.91846473]
  [0.70392543 0.67796244 0.84708366 0.8148024  0.28540609]
  [0.07928522 0.36940072 0.93964675 0.56139738 0.41161123]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [142]:
# your code here
b = np.ones(shape = (5,2,3), dtype = int)

#### 6. Print *b*.


In [143]:
# your code here
b

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [144]:
# your code here
a.shape == b.shape
# ->> a and b are not of same size

False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [145]:
# your answer here
# ->> a and b are not in same shape we can not add without reshaping one of the array

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [146]:
# your code here
c = b.reshape(2,3,5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [147]:
# your code/answer here
d = a + c

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [148]:
# your code/answer here
print(a) 
print(d)

# ->> array d is the sum between array a and c. Array c was transformed form of array b which contains 
# value 1 for all the element. since array d is 1 more than the value of array a.

[[[0.62685931 0.19298137 0.86105538 0.77472924 0.53917686]
  [0.67607384 0.68442526 0.10560228 0.27942381 0.21414295]
  [0.02992513 0.12405569 0.81730263 0.71386705 0.88806069]]

 [[0.15564406 0.0642394  0.92646944 0.7028728  0.91846473]
  [0.70392543 0.67796244 0.84708366 0.8148024  0.28540609]
  [0.07928522 0.36940072 0.93964675 0.56139738 0.41161123]]]
[[[1.62685931 1.19298137 1.86105538 1.77472924 1.53917686]
  [1.67607384 1.68442526 1.10560228 1.27942381 1.21414295]
  [1.02992513 1.12405569 1.81730263 1.71386705 1.88806069]]

 [[1.15564406 1.0642394  1.92646944 1.7028728  1.91846473]
  [1.70392543 1.67796244 1.84708366 1.8148024  1.28540609]
  [1.07928522 1.36940072 1.93964675 1.56139738 1.41161123]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [149]:
# your code here
e = a * c
print(e)

[[[0.62685931 0.19298137 0.86105538 0.77472924 0.53917686]
  [0.67607384 0.68442526 0.10560228 0.27942381 0.21414295]
  [0.02992513 0.12405569 0.81730263 0.71386705 0.88806069]]

 [[0.15564406 0.0642394  0.92646944 0.7028728  0.91846473]
  [0.70392543 0.67796244 0.84708366 0.8148024  0.28540609]
  [0.07928522 0.36940072 0.93964675 0.56139738 0.41161123]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [150]:
# your code/answer here
e == a
# yes! the value of each element in array c is 1 so multiplying a with c will give same array as in a . 

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [151]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print(d_max)
print(d_min)
print(d_mean)

1.939646754914739
1.0299251334161892
1.5328631080671753


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [152]:
# your code here
f = np.empty([2,3,5])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [153]:
# your code here

for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d_min < d[i,j,k] <d_mean:
                f[i,j,k] = 25
            elif d_mean < d[i,j,k] < d_max:
                f[i,j,k] = 75
            elif d[i,j,k] == d_mean:
                f[i,j,k] = 50
            elif d[i,j,k] == d_min:
                f[i,j,k]= 0
            elif d[i,j,k] == d_max:
                f[i,j,k]= 100


[[[ 75.  25.  75.  75.  75.]
  [ 75.  75.  25.  25.  25.]
  [  0.  25.  75.  75.  75.]]

 [[ 25.  25.  75.  75.  75.]
  [ 75.  75.  75.  75.  25.]
  [ 25.  25. 100.  75.  25.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [154]:
# your code here
print(d)
print(f)

[[[1.62685931 1.19298137 1.86105538 1.77472924 1.53917686]
  [1.67607384 1.68442526 1.10560228 1.27942381 1.21414295]
  [1.02992513 1.12405569 1.81730263 1.71386705 1.88806069]]

 [[1.15564406 1.0642394  1.92646944 1.7028728  1.91846473]
  [1.70392543 1.67796244 1.84708366 1.8148024  1.28540609]
  [1.07928522 1.36940072 1.93964675 1.56139738 1.41161123]]]
[[[ 75.  25.  75.  75.  75.]
  [ 75.  75.  25.  25.  25.]
  [  0.  25.  75.  75.  75.]]

 [[ 25.  25.  75.  75.  75.]
  [ 75.  75.  75.  75.  25.]
  [ 25.  25. 100.  75.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [162]:
# your code here
f = np.empty_like(d, dtype = str)
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            f[i,j,k].astype(str)
            if d_min < d[i,j,k] <d_mean:
                f[i,j,k] = "B"
            elif d_mean < d[i,j,k] < d_max:
                f[i,j,k] = "D"
            elif d[i,j,k] == d_mean:
                f[i,j,k] = "C"
            elif d[i,j,k] == d_min:
                f[i,j,k]= "A"
            elif d[i,j,k] == d_max:
                f[i,j,k]= "E"
print(f)

[[['D' 'B' 'D' 'D' 'D']
  ['D' 'D' 'B' 'B' 'B']
  ['A' 'B' 'D' 'D' 'D']]

 [['B' 'B' 'D' 'D' 'D']
  ['D' 'D' 'D' 'D' 'B']
  ['B' 'B' 'E' 'D' 'B']]]
