# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [50]:
import numpy as np

#### 2. Print your NumPy version.

In [51]:
print(np.__version__)

1.20.3


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [52]:
a = np.random.random((2,3,5))
a

array([[[0.73892188, 0.78475927, 0.62589136, 0.93994006, 0.00445696],
        [0.839734  , 0.80481925, 0.03879046, 0.80242957, 0.20421218],
        [0.45414029, 0.88237498, 0.48308229, 0.80543719, 0.61009896]],

       [[0.42576854, 0.45097784, 0.52416876, 0.06726245, 0.87364788],
        [0.32604062, 0.50170696, 0.23010419, 0.752117  , 0.48911095],
        [0.40276766, 0.30895359, 0.71154191, 0.2474492 , 0.23473625]]])

In [10]:
a = np.random.randint(5,90,(2,3,5))
a

array([[[34, 18, 54, 78, 68],
        [62, 56, 68, 16, 71],
        [56, 18, 65, 71, 73]],

       [[58, 82, 17, 23, 79],
        [39, 62, 49, 17, 34],
        [81, 28, 10, 46,  7]]])

In [11]:
a = np.random.randn(2,3,5)
a

array([[[ 0.77899879, -0.21689209, -0.12338735,  0.41198994,
          1.4084077 ],
        [ 1.47974561,  0.18730292,  1.12605652, -0.76633225,
          0.57840756],
        [-0.69470726, -0.62996132,  1.32694365, -1.40815928,
          1.01663982]],

       [[-0.47015011, -0.05633881, -0.61636558, -0.00739679,
          1.16334046],
        [ 2.17925926,  0.67575819,  2.33850196,  0.46190077,
          1.3098475 ],
        [-0.78421551, -0.24465435, -0.85412642,  1.32929723,
         -0.27912597]]])

#### 4. Print *a*.


In [53]:
print(a)

[[[0.73892188 0.78475927 0.62589136 0.93994006 0.00445696]
  [0.839734   0.80481925 0.03879046 0.80242957 0.20421218]
  [0.45414029 0.88237498 0.48308229 0.80543719 0.61009896]]

 [[0.42576854 0.45097784 0.52416876 0.06726245 0.87364788]
  [0.32604062 0.50170696 0.23010419 0.752117   0.48911095]
  [0.40276766 0.30895359 0.71154191 0.2474492  0.23473625]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [54]:
b = np.ones((5,2,3))

#### 6. Print *b*.


In [55]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [56]:
print(a.shape)
print(b.shape)

#They don't have the same size

(2, 3, 5)
(5, 2, 3)


#### 8. Are you able to add *a* and *b*? Why or why not?


In [57]:
a + b

#Cannot add them as they don't have the same shape.

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [58]:
c = np.transpose(b,(1,2,0))
print(c.shape)
print(c)

(2, 3, 5)
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [95]:
d = a + c
print(d)
# It works because the shape is the same in both arrays now.

[[[1.73892188 1.78475927 1.62589136 1.93994006 1.00445696]
  [1.839734   1.80481925 1.03879046 1.80242957 1.20421218]
  [1.45414029 1.88237498 1.48308229 1.80543719 1.61009896]]

 [[1.42576854 1.45097784 1.52416876 1.06726245 1.87364788]
  [1.32604062 1.50170696 1.23010419 1.752117   1.48911095]
  [1.40276766 1.30895359 1.71154191 1.2474492  1.23473625]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [96]:
print(a)
print(d)

# The difference between the two arrays is that 'd' array has the same values as 'a' adding 1. 
# It can be easily checked subtracting the values as shown below:

print(d - a)

[[[0.73892188 0.78475927 0.62589136 0.93994006 0.00445696]
  [0.839734   0.80481925 0.03879046 0.80242957 0.20421218]
  [0.45414029 0.88237498 0.48308229 0.80543719 0.61009896]]

 [[0.42576854 0.45097784 0.52416876 0.06726245 0.87364788]
  [0.32604062 0.50170696 0.23010419 0.752117   0.48911095]
  [0.40276766 0.30895359 0.71154191 0.2474492  0.23473625]]]
[[[1.73892188 1.78475927 1.62589136 1.93994006 1.00445696]
  [1.839734   1.80481925 1.03879046 1.80242957 1.20421218]
  [1.45414029 1.88237498 1.48308229 1.80543719 1.61009896]]

 [[1.42576854 1.45097784 1.52416876 1.06726245 1.87364788]
  [1.32604062 1.50170696 1.23010419 1.752117   1.48911095]
  [1.40276766 1.30895359 1.71154191 1.2474492  1.23473625]]]
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [61]:
e = a * c
print(e)

[[[0.73892188 0.78475927 0.62589136 0.93994006 0.00445696]
  [0.839734   0.80481925 0.03879046 0.80242957 0.20421218]
  [0.45414029 0.88237498 0.48308229 0.80543719 0.61009896]]

 [[0.42576854 0.45097784 0.52416876 0.06726245 0.87364788]
  [0.32604062 0.50170696 0.23010419 0.752117   0.48911095]
  [0.40276766 0.30895359 0.71154191 0.2474492  0.23473625]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [62]:
e == a

# Yes, e equals a in all the elements of the array. Because c was composed by 
# only '1' values and therefore if we multiply an array by 1 the values will stay the same.

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [101]:
d_max = d.max()
print(d_max)

d_min = d.min()
print(d_min)

d_mean = d.mean()
print(d_mean)

1.9399400577933745
1.0044569570847177
1.5188480843435508


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [109]:
f = np.zeros((2, 3, 5))
print(f.shape)
print(f)

(2, 3, 5)
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [111]:
for element in range(0,2):
    for subelem in range(0,3):
        for subsubelem in range(0,5):
            if d_mean > d[element, subelem, subsubelem] > d_min :
                f[element, subelem, subsubelem] = 25
            elif d_max > d[element, subelem, subsubelem] > d_mean :
                f[element, subelem, subsubelem] = 75
            elif d[element, subelem, subsubelem] == d_mean :
                f[element, subelem, subsubelem] = 50
            elif d[element, subelem, subsubelem] == d_min :
                f[element, subelem, subsubelem] = 0
            elif d[element, subelem, subsubelem] == d_max :
                f[element, subelem, subsubelem] = 100
            else:
                continue
print(f.shape)
print(f)

(2, 3, 5)
[[[ 75.  75.  75. 100.   0.]
  [ 75.  75.  25.  75.  25.]
  [ 25.  75.  25.  75.  75.]]

 [[ 25.  25.  75.  25.  75.]
  [ 25.  25.  25.  75.  25.]
  [ 25.  25.  75.  25.  25.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [114]:
g = np.empty((2, 3, 5), str)

for element in range(0,2):
    for subelem in range(0,3):
        for subsubelem in range(0,5):
            if d_mean > d[element, subelem, subsubelem] > d_min :
                g[element, subelem, subsubelem] = 'A'
            elif d_max > d[element, subelem, subsubelem] > d_mean :
                g[element, subelem, subsubelem] = 'B'
            elif d[element, subelem, subsubelem] == d_mean :
                g[element, subelem, subsubelem] = 'C'
            elif d[element, subelem, subsubelem] == d_min :
                g[element, subelem, subsubelem] = 'D'
            elif d[element, subelem, subsubelem] == d_max :
                g[element, subelem, subsubelem] = 'E'
            else:
                continue
print(g.shape)
print(g)

(2, 3, 5)
[[['B' 'B' 'B' 'E' 'D']
  ['B' 'B' 'A' 'B' 'A']
  ['A' 'B' 'A' 'B' 'B']]

 [['A' 'A' 'B' 'A' 'B']
  ['A' 'A' 'A' 'B' 'A']
  ['A' 'A' 'B' 'A' 'A']]]
