# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [27]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [28]:
# your code here
np.version.version

'1.18.1'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [29]:
# Method 1
a=np.random.rand(2,3,5)
a

array([[[0.08975472, 0.24400588, 0.42940132, 0.9369105 , 0.79865865],
        [0.57510213, 0.40179437, 0.39143981, 0.0247527 , 0.59327602],
        [0.1994348 , 0.10386279, 0.66112649, 0.09747818, 0.9333282 ]],

       [[0.71004721, 0.15498073, 0.89540639, 0.82737505, 0.42211703],
        [0.92813228, 0.44825446, 0.61933699, 0.67833343, 0.90631085],
        [0.38301053, 0.62034171, 0.79408039, 0.96728218, 0.75450439]]])

In [30]:
# Method 2

In [31]:
# Method 3

#### 4. Print *a*.


In [32]:
# your code here
a

array([[[0.08975472, 0.24400588, 0.42940132, 0.9369105 , 0.79865865],
        [0.57510213, 0.40179437, 0.39143981, 0.0247527 , 0.59327602],
        [0.1994348 , 0.10386279, 0.66112649, 0.09747818, 0.9333282 ]],

       [[0.71004721, 0.15498073, 0.89540639, 0.82737505, 0.42211703],
        [0.92813228, 0.44825446, 0.61933699, 0.67833343, 0.90631085],
        [0.38301053, 0.62034171, 0.79408039, 0.96728218, 0.75450439]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [33]:
# your code here
b = np.ones((5,2,3), dtype=int)

#### 6. Print *b*.


In [34]:
# your code here
b

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [35]:
# your code here
a.size == b.size #get the array's sizes and compare them !


True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [36]:
# your answer here
b.shape
#a +b

#You cant because they have diferent shapes!
#but you can reshape them to make it possible 

(5, 2, 3)

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [37]:
# your code here

#this is the esiest way but doesn't comply with the request
"""
c = b.reshape(2,3,5)
"""


#this solution took some time but in the end i got there
#I even think this might be similar to the internals of reshape
list_arrays = []

for array in b:
    new_array = np.transpose(array)
    list_arrays.append(new_array)
#print(list_arrays) #used to get a visual clue of what was going on
test_array = np.array(list_arrays)
#print(np.transpose(test_array)) #seeing the result

c = np.transpose(test_array)
print(c)
print(c.shape)


#this also complies with the requested but doesn't make much sense geometricly speaking
#well at least I was struggling while thinking geometricly
#but basicly you change  the "coordinates" of the shape so if you have (c,a,b) and want (a,b,c)
#you would use (1,2,0) and you would get the wished (a,b,c)

"""
print(b)
print(np.transpose(b))
print(np.transpose(b,(1,2,0)).shape)
"""

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]
(2, 3, 5)


'\nprint(b)\nprint(np.transpose(b))\nprint(np.transpose(b,(1,2,0)).shape)\n'

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [38]:
# your code/answer here
d= [a + c]

#Because they have the samme shape!

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [48]:
# your code/answer here
print(a)
print(d)

#Well they have the same shape, and you can see that exists an exact disparity between both of them
#Of a value 1
#this appens because the table d is the result of the sum of table a and a table that pnly
#had values = 1

[[[0.08975472 0.24400588 0.42940132 0.9369105  0.79865865]
  [0.57510213 0.40179437 0.39143981 0.0247527  0.59327602]
  [0.1994348  0.10386279 0.66112649 0.09747818 0.9333282 ]]

 [[0.71004721 0.15498073 0.89540639 0.82737505 0.42211703]
  [0.92813228 0.44825446 0.61933699 0.67833343 0.90631085]
  [0.38301053 0.62034171 0.79408039 0.96728218 0.75450439]]]
[array([[[1.08975472, 1.24400588, 1.42940132, 1.9369105 , 1.79865865],
        [1.57510213, 1.40179437, 1.39143981, 1.0247527 , 1.59327602],
        [1.1994348 , 1.10386279, 1.66112649, 1.09747818, 1.9333282 ]],

       [[1.71004721, 1.15498073, 1.89540639, 1.82737505, 1.42211703],
        [1.92813228, 1.44825446, 1.61933699, 1.67833343, 1.90631085],
        [1.38301053, 1.62034171, 1.79408039, 1.96728218, 1.75450439]]])]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [40]:
# your code here
e = [a*c]

#### 13. Does *e* equal to *a*? Why or why not?


In [50]:
# your code/answer here
e==a
#It does, as you can see after comparing both we only got true, because of that we can
#assume both tables are equal in value and shape, other wise they would not match up

array([[[[ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True]],

        [[ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True]]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [55]:
# your code here
d_min = np.min(d)
d_max = np.max(d)
d_mean = np.mean(d)



#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [43]:
# your code here
f = np.empty((2,3,5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [58]:
# your code here

#preferebly try it without list comprehension
#than lose some airs with list comp...
#use loop within loop
#conditional and flag positoin with slicing ex.[g,l,num]



#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [45]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [46]:
# your code here