# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [36]:
# your code here

import numpy as np

#### 2. Print your NumPy version.

In [38]:
# your code here

np.version.version

'1.19.1'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [79]:
# Method 1 
a = np.random.random((2,3,5))

In [30]:
# Method 2

#a = np.linspace(2,3,5)

In [45]:
# Method 3
#a = np.arange(0,20).reshape(2,2)

#### 4. Print *a*.


In [80]:
# your code here
print(a)

[[[0.62669958 0.85423409 0.04271737 0.7100104  0.88399569]
  [0.3276759  0.55867568 0.78576788 0.5708183  0.61715411]
  [0.6869887  0.55822358 0.16256417 0.37449773 0.59209013]]

 [[0.54289802 0.73432699 0.62963645 0.59522042 0.30019756]
  [0.14598378 0.53570765 0.85648165 0.99225289 0.67003704]
  [0.40007844 0.63944507 0.91000837 0.41071809 0.20745159]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [81]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [82]:
# your code here
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [83]:
# your code here
a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [84]:
# your answer here
#I can append a to b

np.add(a, b)

#operands could not be broadcast together with shapes (2,3,5) (5,2,3)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [95]:
# your code here
c = b.reshape(2,3,5)
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [97]:
# your code/answer here

d = np.add(a, c)
d

array([[[1.62669958, 1.85423409, 1.04271737, 1.7100104 , 1.88399569],
        [1.3276759 , 1.55867568, 1.78576788, 1.5708183 , 1.61715411],
        [1.6869887 , 1.55822358, 1.16256417, 1.37449773, 1.59209013]],

       [[1.54289802, 1.73432699, 1.62963645, 1.59522042, 1.30019756],
        [1.14598378, 1.53570765, 1.85648165, 1.99225289, 1.67003704],
        [1.40007844, 1.63944507, 1.91000837, 1.41071809, 1.20745159]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [98]:
# your code/answer here
print(a)
print(d)

#they are created randomly

[[[0.62669958 0.85423409 0.04271737 0.7100104  0.88399569]
  [0.3276759  0.55867568 0.78576788 0.5708183  0.61715411]
  [0.6869887  0.55822358 0.16256417 0.37449773 0.59209013]]

 [[0.54289802 0.73432699 0.62963645 0.59522042 0.30019756]
  [0.14598378 0.53570765 0.85648165 0.99225289 0.67003704]
  [0.40007844 0.63944507 0.91000837 0.41071809 0.20745159]]]
[[[1.62669958 1.85423409 1.04271737 1.7100104  1.88399569]
  [1.3276759  1.55867568 1.78576788 1.5708183  1.61715411]
  [1.6869887  1.55822358 1.16256417 1.37449773 1.59209013]]

 [[1.54289802 1.73432699 1.62963645 1.59522042 1.30019756]
  [1.14598378 1.53570765 1.85648165 1.99225289 1.67003704]
  [1.40007844 1.63944507 1.91000837 1.41071809 1.20745159]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [100]:
# your code here
e = a*c

#### 13. Does *e* equal to *a*? Why or why not?


In [101]:
# your code/answer here

e == a

#b had a value of 1.0, and having c the same values of b reshaped we are multiplying for 1

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [122]:
# your code here
d_min = d.min()
d_max = d.max()
d_mean = d.mean()


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [150]:
# your code here

f = np.empty((2,3,5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [155]:
# your code here

for block in range(2):
    for row in range(3):
        for element in range(5):
            if(d_min < d[block][row][element] < d_mean):
                 f[block][row][element] = 25
            if(d_mean < d[block][row][element] < d_max):
                 f[block][row][element] = 75
            if(d[block][row][element] == d_mean):
                 f[block][row][element] = 50
            if(d[block][row][element] == d_min):
                 f[block][row][element] = 0
            if(d[block][row][element] == d_max):
                 f[block][row][element] = 100

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [156]:
# your code here
print(d)

[[[1.62669958 1.85423409 1.04271737 1.7100104  1.88399569]
  [1.3276759  1.55867568 1.78576788 1.5708183  1.61715411]
  [1.6869887  1.55822358 1.16256417 1.37449773 1.59209013]]

 [[1.54289802 1.73432699 1.62963645 1.59522042 1.30019756]
  [1.14598378 1.53570765 1.85648165 1.99225289 1.67003704]
  [1.40007844 1.63944507 1.91000837 1.41071809 1.20745159]]]


In [157]:
print(f)

[[[ 75.  75.   0.  75.  75.]
  [ 25.  25.  75.  75.  75.]
  [ 75.  25.  25.  25.  75.]]

 [[ 25.  75.  75.  75.  25.]
  [ 25.  25.  75. 100.  75.]
  [ 25.  75.  75.  25.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here