# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np


#### 2. Print your NumPy version.

In [4]:
# your code here
np.version

<module 'numpy.version' from 'c:\\anaconda3\\lib\\site-packages\\numpy\\version.py'>

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [62]:
# Method 1
import random as rd

a=np.array(rd.sample([i for i in range(100)], k=30)).reshape(2,3,5)
a

array([[[ 2, 32, 84, 81, 37],
        [90, 38, 48, 29, 12],
        [70, 53, 66, 52,  8]],

       [[80, 82, 26, 91, 24],
        [33, 62, 93, 28, 94],
        [ 1, 18, 97, 77, 92]]])

In [63]:
# Method 2
a = np.random.rand(30).reshape(2,3,5)
a

array([[[0.01339078, 0.1474264 , 0.53298964, 0.05521953, 0.47008752],
        [0.01322373, 0.37115146, 0.92853832, 0.01192953, 0.28889842],
        [0.59085862, 0.39211761, 0.38870736, 0.14146144, 0.07235479]],

       [[0.14442506, 0.35360671, 0.11204286, 0.82692412, 0.19935115],
        [0.61287197, 0.044141  , 0.34582081, 0.44977434, 0.08587826],
        [0.39462159, 0.88124237, 0.06301064, 0.67661668, 0.7212476 ]]])

In [64]:
# Method 3
a = np.random.randint(0,9, size=(2,3,5))
a

array([[[3, 6, 2, 4, 5],
        [2, 6, 3, 6, 7],
        [6, 1, 5, 7, 8]],

       [[6, 3, 4, 2, 6],
        [5, 5, 1, 6, 8],
        [8, 3, 1, 6, 3]]])

In [65]:
## Bonus

a = np.ndarray(shape = (2,3,5))
a

array([[[0.01339078, 0.1474264 , 0.53298964, 0.05521953, 0.47008752],
        [0.01322373, 0.37115146, 0.92853832, 0.01192953, 0.28889842],
        [0.59085862, 0.39211761, 0.38870736, 0.14146144, 0.07235479]],

       [[0.14442506, 0.35360671, 0.11204286, 0.82692412, 0.19935115],
        [0.61287197, 0.044141  , 0.34582081, 0.44977434, 0.08587826],
        [0.39462159, 0.88124237, 0.06301064, 0.67661668, 0.7212476 ]]])

#### 4. Print *a*.


In [66]:
# your code here
a

array([[[0.01339078, 0.1474264 , 0.53298964, 0.05521953, 0.47008752],
        [0.01322373, 0.37115146, 0.92853832, 0.01192953, 0.28889842],
        [0.59085862, 0.39211761, 0.38870736, 0.14146144, 0.07235479]],

       [[0.14442506, 0.35360671, 0.11204286, 0.82692412, 0.19935115],
        [0.61287197, 0.044141  , 0.34582081, 0.44977434, 0.08587826],
        [0.39462159, 0.88124237, 0.06301064, 0.67661668, 0.7212476 ]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [67]:
# your code here
b = ((np.ndarray(shape=(5,2,3)))*0+1)

#### 6. Print *b*.


In [68]:
# your code here
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [69]:
# your code here
a.shape == b.shape

False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [70]:
# your answer here
a + b
## Not possible since the shapes of the two arrays do not match

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [73]:
# your code here
c = b.reshape(2,3,5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [75]:
# your code/answer here
d = a+c
## to add two different arrays, they must first be the same size


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [77]:
# your code/answer here

print (a)

[[[0.01339078 0.1474264  0.53298964 0.05521953 0.47008752]
  [0.01322373 0.37115146 0.92853832 0.01192953 0.28889842]
  [0.59085862 0.39211761 0.38870736 0.14146144 0.07235479]]

 [[0.14442506 0.35360671 0.11204286 0.82692412 0.19935115]
  [0.61287197 0.044141   0.34582081 0.44977434 0.08587826]
  [0.39462159 0.88124237 0.06301064 0.67661668 0.7212476 ]]]


In [78]:
print (d)

## all values in d are bigger than a by 1

[[[1.01339078 1.1474264  1.53298964 1.05521953 1.47008752]
  [1.01322373 1.37115146 1.92853832 1.01192953 1.28889842]
  [1.59085862 1.39211761 1.38870736 1.14146144 1.07235479]]

 [[1.14442506 1.35360671 1.11204286 1.82692412 1.19935115]
  [1.61287197 1.044141   1.34582081 1.44977434 1.08587826]
  [1.39462159 1.88124237 1.06301064 1.67661668 1.7212476 ]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [81]:
# your code here
e = a*c


array([[[0.01339078, 0.1474264 , 0.53298964, 0.05521953, 0.47008752],
        [0.01322373, 0.37115146, 0.92853832, 0.01192953, 0.28889842],
        [0.59085862, 0.39211761, 0.38870736, 0.14146144, 0.07235479]],

       [[0.14442506, 0.35360671, 0.11204286, 0.82692412, 0.19935115],
        [0.61287197, 0.044141  , 0.34582081, 0.44977434, 0.08587826],
        [0.39462159, 0.88124237, 0.06301064, 0.67661668, 0.7212476 ]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [80]:
# your code/answer here
a == e

## e is a combination of a and a matrix of just "1" so it's the same

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [86]:
# your code here
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [102]:
# your code here
f = np.empty(shape=(2,3,5))
f

array([[[0.01339078, 0.1474264 , 0.53298964, 0.05521953, 0.47008752],
        [0.01322373, 0.37115146, 0.92853832, 0.01192953, 0.28889842],
        [0.59085862, 0.39211761, 0.38870736, 0.14146144, 0.07235479]],

       [[0.14442506, 0.35360671, 0.11204286, 0.82692412, 0.19935115],
        [0.61287197, 0.044141  , 0.34582081, 0.44977434, 0.08587826],
        [0.39462159, 0.88124237, 0.06301064, 0.67661668, 0.7212476 ]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [119]:
# your code here
lit = []
for i in d.tolist():
    for z in i:
        for q in z:
            if q == d_min:
                lit.append(0)
            if d_min< q < d_mean:
                lit.append(25)
                continue
            if q == d_mean:
                lit.append(50)
            if d_mean < q < d_max:
                lit.append(75)
                continue
            if q == d_max:
                lit.append(100)
f = np.array([lit])
f = f.reshape(2,3,5)

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [120]:
# your code here
print(d)

[[[1.01339078 1.1474264  1.53298964 1.05521953 1.47008752]
  [1.01322373 1.37115146 1.92853832 1.01192953 1.28889842]
  [1.59085862 1.39211761 1.38870736 1.14146144 1.07235479]]

 [[1.14442506 1.35360671 1.11204286 1.82692412 1.19935115]
  [1.61287197 1.044141   1.34582081 1.44977434 1.08587826]
  [1.39462159 1.88124237 1.06301064 1.67661668 1.7212476 ]]]


In [121]:
f

array([[[ 25,  25,  75,  25,  75],
        [ 25,  75, 100,   0,  25],
        [ 75,  75,  75,  25,  25]],

       [[ 25,  75,  25,  75,  25],
        [ 75,  25,  75,  75,  25],
        [ 75,  75,  25,  75,  75]]])

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here