# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
import numpy
print(numpy.__version__)


1.21.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [10]:
# Method 1
import numpy as np
a = np.random.random((2, 3, 5))



In [9]:
# Method 2
import numpy as np
a = np.random.rand(2, 3, 5)


In [8]:
# Method 3
import numpy as np
a = np.random.randint(10, size=(2, 3, 5))


#### 4. Print *a*.


In [7]:
# your code here
print(a)

[[[4 0 6 8 1]
  [5 0 2 4 9]
  [8 2 4 1 2]]

 [[5 2 8 5 2]
  [0 5 3 3 3]
  [9 1 6 1 1]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [13]:
# your code here
import numpy as np
b = np.ones((5,2,3))


#### 6. Print *b*.


In [14]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [15]:
# your code here
import numpy as np
a = np.random.random((2, 3, 5))
b = np.ones((5,2,3))

if np.shape(a) != np.shape(b):
    print("a and b do not have the same size")
else:
    print("a and b have the same size")


a and b do not have the same size


#### 8. Are you able to add *a* and *b*? Why or why not?


In [17]:
# your answer here
import numpy as np
a = np.random.random((2, 3, 5))
b = np.ones((5,2,3))
c = a + b
#no, because they have different shapes. In order to add two arrays together, they must have the same shape and compatible data types.

#In numpy, the addition operation is carried out element-wise, and it requires the arrays to have the same shape



ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [18]:
# your code here
import numpy as np
b = np.ones((5,2,3))
c = np.transpose(b, (1, 2, 0))


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [ ]:
# your code/answer here
#because they have the same shape.

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [19]:
# your code/answer here
import numpy as np
a = np.random.random((2, 3, 5))
b = np.ones((5,2,3))
c = np.transpose(b, (1, 2, 0))
d = a+c
print("a: \n", a)
print("d: \n", d)
#the relation between a and d is that d is the element-wise sum of a and c, which means that the corresponding elements of the two arrays are added together. The difference is that a contains random values and d contains the sum of a and c which is 1 for all the elements.

a: 
 [[[7.73842744e-01 6.46271057e-02 7.41829124e-01 2.43031337e-01
   3.87799475e-01]
  [3.69001408e-01 3.84537806e-01 7.26943071e-01 5.91315829e-01
   7.09083526e-01]
  [1.51438943e-02 1.01349602e-02 1.28303021e-01 4.13530005e-01
   3.23953008e-01]]

 [[7.47369373e-01 6.50582084e-02 2.70925995e-01 2.10144760e-01
   5.53167449e-01]
  [1.55637463e-01 2.85878682e-01 4.91064472e-01 1.22124472e-01
   4.19369130e-01]
  [7.24686873e-01 2.87766664e-01 5.48647395e-04 3.76636735e-01
   8.99708009e-01]]]
d: 
 [[[1.77384274 1.06462711 1.74182912 1.24303134 1.38779948]
  [1.36900141 1.38453781 1.72694307 1.59131583 1.70908353]
  [1.01514389 1.01013496 1.12830302 1.41353001 1.32395301]]

 [[1.74736937 1.06505821 1.27092599 1.21014476 1.55316745]
  [1.15563746 1.28587868 1.49106447 1.12212447 1.41936913]
  [1.72468687 1.28776666 1.00054865 1.37663673 1.89970801]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [20]:
# your code here
import numpy as np
a = np.random.random((2, 3, 5))
b = np.ones((5,2,3))
c = np.transpose(b, (1, 2, 0))
e = a * c


#### 13. Does *e* equal to *a*? Why or why not?


In [21]:
# your code/answer here
import numpy as np
a = np.random.random((2, 3, 5))
b = np.ones((5,2,3))
c = np.transpose(b, (1, 2, 0))
e = a * c
if np.array_equal(e, a):
    print("e is equal to a")
else:
    print("e is not equal to a")


e is equal to a


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [22]:
# your code here
import numpy as np
a = np.random.random((2, 3, 5))
b = np.ones((5,2,3))
c = np.transpose(b, (1, 2, 0))
d = a + c
d_max = np.amax(d)
d_min = np.amin(d)
d_mean = np.mean(d)


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [23]:
# your code here
import numpy as np
a = np.random.random((2, 3, 5))
b = np.ones((5,2,3))
c = np.transpose(b, (1, 2, 0))
d = a + c
f = np.empty(d.shape)


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [24]:
# your code here
import numpy as np
a = np.random.random((2, 3, 5))
b = np.ones((5,2,3))
c = np.transpose(b, (1, 2, 0))
d = a + c
d_max = np.amax(d)
d_min = np.amin(d)
d_mean = np.mean(d)
f = np.empty(d.shape)

for i in np.nditer(d, op_flags=['readwrite']):
    if i == d_min:
        i[...] = 0
    elif i == d_max:
        i[...] = 100
    elif i > d_min and i < d_mean:
        i[...] = 25
    elif i > d_mean and i < d_max:
        i[...] = 75
    elif i == d_mean:
        i[...] = 50


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [25]:
# your code here
print(d)
print(f)

[[[ 25.  75.  75.  75.  25.]
  [ 75.  75.  25.  75.  75.]
  [ 75.  25. 100.  25.  25.]]

 [[ 75.  25.   0.  25.  75.]
  [ 25.  25.  25.  25.  25.]
  [ 25.  75.  25.  75.  25.]]]
[[[1.28887638 1.37381941 1.60255201 1.72855524 1.08288443]
  [1.1825055  1.95899701 1.25601551 1.69979508 1.8240574 ]
  [1.03216927 1.439621   1.49162144 1.27153426 1.50631777]]

 [[1.49999398 1.40958781 1.84972099 1.15666466 1.08715654]
  [1.76895131 1.89728102 1.30428521 1.59443164 1.37689813]
  [1.03312341 1.65531764 1.40601503 1.46961333 1.40708048]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [26]:
# your code here
d = [[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]], [[16, 17, 18, 19, 20], [21, 22, 23, 24, 25], [26, 27, 28, 29, 30]]]
d_min = min(min(min(d)))
d_max = max(max(max(d)))
d_mean = (d_min + d_max) / 2
f = [[[0 for x in range(5)] for y in range(3)] for z in range(2)]

for i in range(len(d)):
    for j in range(len(d[i])):
        for k in range(len(d[i][j])):
            if d[i][j][k] == d_min:
                f[i][j][k] = 'A'
            elif d[i][j][k] == d_max:
                f[i][j][k] = 'E'
            elif d[i][j][k] > d_min and d[i][j][k] < d_mean:
                f[i][j][k] = 'B'
            elif d[i][j][k] > d_mean and d[i][j][k] < d_max:
                f[i][j][k] = 'D'
            elif d[i][j][k] == d_mean:
                f[i][j][k] = 'C'
