# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [2]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [4]:
# your code here
print(np.__version__)

1.18.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [8]:
# Method 1
a = np.random.random((2,3,5))
print(a)

[[[0.80174842 0.99825691 0.32168033 0.58726408 0.42215404]
  [0.26631635 0.34701361 0.0842411  0.82104427 0.18748972]
  [0.02078106 0.02181494 0.28478208 0.25449842 0.51288188]]

 [[0.3576921  0.2492604  0.39186709 0.55843633 0.99607317]
  [0.84681395 0.12491661 0.49823748 0.53857394 0.14869611]
  [0.62616475 0.90235001 0.11665264 0.81875501 0.350297  ]]]


In [19]:
# Method 2
a= np.random.uniform(0,1,size=(2,3,5))
print(a)

[[[0.63592737 0.29341747 0.92517552 0.34531009 0.31261697]
  [0.84505353 0.9910594  0.54188508 0.43459529 0.59105268]
  [0.88726453 0.89922781 0.98831588 0.52958963 0.39849583]]

 [[0.16079121 0.98392382 0.81639349 0.49156521 0.77940274]
  [0.35710226 0.44298875 0.66870722 0.66346351 0.93477029]
  [0.50196761 0.59949022 0.52549628 0.1141851  0.99137383]]]


In [35]:
# Method 3
hh=np.zeros((10,2))
print(hh)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


#### 4. Print *a*.


In [21]:
# your code here
print(a)

[[[0.63592737 0.29341747 0.92517552 0.34531009 0.31261697]
  [0.84505353 0.9910594  0.54188508 0.43459529 0.59105268]
  [0.88726453 0.89922781 0.98831588 0.52958963 0.39849583]]

 [[0.16079121 0.98392382 0.81639349 0.49156521 0.77940274]
  [0.35710226 0.44298875 0.66870722 0.66346351 0.93477029]
  [0.50196761 0.59949022 0.52549628 0.1141851  0.99137383]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [25]:
# your code here
b=np.random.uniform(1,1, size=(5,2,3))

#### 6. Print *b*.


In [26]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [27]:
# your code here
if a.size == b.size:
    print("same")

same


#### 8. Are you able to add *a* and *b*? Why or why not?


In [28]:
# your answer here
c=np.add(a,b)
print(c)
#have to be same shape

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [38]:
# your code here
c=b.reshape(2, 3, 5)

print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [40]:
# your code/answer here
d=np.add(a,c)
print(d)
#works because same shape

[[[1.63592737 1.29341747 1.92517552 1.34531009 1.31261697]
  [1.84505353 1.9910594  1.54188508 1.43459529 1.59105268]
  [1.88726453 1.89922781 1.98831588 1.52958963 1.39849583]]

 [[1.16079121 1.98392382 1.81639349 1.49156521 1.77940274]
  [1.35710226 1.44298875 1.66870722 1.66346351 1.93477029]
  [1.50196761 1.59949022 1.52549628 1.1141851  1.99137383]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [44]:
# your code/answer here
print(a)
print("\n\n")
print(d)

#difference is 1 cause b was an array of all 1 value

[[[0.63592737 0.29341747 0.92517552 0.34531009 0.31261697]
  [0.84505353 0.9910594  0.54188508 0.43459529 0.59105268]
  [0.88726453 0.89922781 0.98831588 0.52958963 0.39849583]]

 [[0.16079121 0.98392382 0.81639349 0.49156521 0.77940274]
  [0.35710226 0.44298875 0.66870722 0.66346351 0.93477029]
  [0.50196761 0.59949022 0.52549628 0.1141851  0.99137383]]]



[[[1.63592737 1.29341747 1.92517552 1.34531009 1.31261697]
  [1.84505353 1.9910594  1.54188508 1.43459529 1.59105268]
  [1.88726453 1.89922781 1.98831588 1.52958963 1.39849583]]

 [[1.16079121 1.98392382 1.81639349 1.49156521 1.77940274]
  [1.35710226 1.44298875 1.66870722 1.66346351 1.93477029]
  [1.50196761 1.59949022 1.52549628 1.1141851  1.99137383]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [46]:
# your code here
e=a*c
print(e)

[[[0.63592737 0.29341747 0.92517552 0.34531009 0.31261697]
  [0.84505353 0.9910594  0.54188508 0.43459529 0.59105268]
  [0.88726453 0.89922781 0.98831588 0.52958963 0.39849583]]

 [[0.16079121 0.98392382 0.81639349 0.49156521 0.77940274]
  [0.35710226 0.44298875 0.66870722 0.66346351 0.93477029]
  [0.50196761 0.59949022 0.52549628 0.1141851  0.99137383]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [ ]:
# your code/answer here
#yes, cause we multiply by 1

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [47]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [71]:
# your code here
f=np.empty((2,3,5))
print(f)

[[[0.63592737 0.29341747 0.92517552 0.34531009 0.31261697]
  [0.84505353 0.9910594  0.54188508 0.43459529 0.59105268]
  [0.88726453 0.89922781 0.98831588 0.52958963 0.39849583]]

 [[0.16079121 0.98392382 0.81639349 0.49156521 0.77940274]
  [0.35710226 0.44298875 0.66870722 0.66346351 0.93477029]
  [0.50196761 0.59949022 0.52549628 0.1141851  0.99137383]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [72]:
# larger than d_min but smaller than d_mean, assign 25 d_min<value<d_mean
# larger than d_mean but smaller than d_max, assign 75 d_mean<value<d_max
# If a value equals to d_mean, assign 50 d_mean == value
# Assign 0 to the corresponding value(s) in f for d_min in d_min == value
#100 d_max == value



ff=[25 if d_min<value<d_mean else 75 if d_mean<value<d_max else 50 if value == d_mean else 0 if value == d_min else 100 for first_group in d for sub_group in first_group for value in sub_group]
print(ff)


[75, 25, 75, 25, 25, 75, 75, 25, 25, 25, 75, 75, 75, 25, 25, 25, 75, 75, 25, 75, 25, 25, 75, 75, 75, 25, 25, 25, 0, 100]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [73]:
# your code here
f_array = np.array(ff)

f_array_reshape = f_array.reshape(2,3,5)
print(f_array_reshape)
print("\n\n\n")
print(f)

[[[ 75  25  75  25  25]
  [ 75  75  25  25  25]
  [ 75  75  75  25  25]]

 [[ 25  75  75  25  75]
  [ 25  25  75  75  75]
  [ 25  25  25   0 100]]]




[[[0.63592737 0.29341747 0.92517552 0.34531009 0.31261697]
  [0.84505353 0.9910594  0.54188508 0.43459529 0.59105268]
  [0.88726453 0.89922781 0.98831588 0.52958963 0.39849583]]

 [[0.16079121 0.98392382 0.81639349 0.49156521 0.77940274]
  [0.35710226 0.44298875 0.66870722 0.66346351 0.93477029]
  [0.50196761 0.59949022 0.52549628 0.1141851  0.99137383]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here