# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [2]:
print(np.version.version)

1.17.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
a = np.random.random((2,3,5))

In [4]:
a = np.random.normal(size=(2,3,5))

In [5]:
a = np.random.uniform(size=(2,3,5))

#### 4. Print *a*.


In [6]:
print(a)

[[[0.93888285 0.41392902 0.869702   0.75641957 0.2210088 ]
  [0.39848989 0.99532534 0.46766773 0.09258675 0.76509434]
  [0.25070461 0.92957501 0.99987221 0.60910503 0.20918436]]

 [[0.66126563 0.53523404 0.80271972 0.25130894 0.14583565]
  [0.7508927  0.80204137 0.75656769 0.52768556 0.0693454 ]
  [0.25138246 0.3608286  0.11840921 0.54703718 0.90024   ]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
b = np.ones((5,2,3), dtype = int)

#### 6. Print *b*.


In [8]:
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
if a.size == b.size:
    print(True)
else:
    print(False)

True


#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
np.add(a,b)
# No because the shapes of a and b are not the same

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
c = np.transpose(b, (1, 2, 0))
print(np.shape(c))

(2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
d = np.add(a,c)

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
print(a)
print(d)
# d is a + 1 since b was all ones

[[[0.93888285 0.41392902 0.869702   0.75641957 0.2210088 ]
  [0.39848989 0.99532534 0.46766773 0.09258675 0.76509434]
  [0.25070461 0.92957501 0.99987221 0.60910503 0.20918436]]

 [[0.66126563 0.53523404 0.80271972 0.25130894 0.14583565]
  [0.7508927  0.80204137 0.75656769 0.52768556 0.0693454 ]
  [0.25138246 0.3608286  0.11840921 0.54703718 0.90024   ]]]
[[[1.93888285 1.41392902 1.869702   1.75641957 1.2210088 ]
  [1.39848989 1.99532534 1.46766773 1.09258675 1.76509434]
  [1.25070461 1.92957501 1.99987221 1.60910503 1.20918436]]

 [[1.66126563 1.53523404 1.80271972 1.25130894 1.14583565]
  [1.7508927  1.80204137 1.75656769 1.52768556 1.0693454 ]
  [1.25138246 1.3608286  1.11840921 1.54703718 1.90024   ]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
e = np.multiply(a,c)
print(a)
print(c)
print(e)

[[[0.93888285 0.41392902 0.869702   0.75641957 0.2210088 ]
  [0.39848989 0.99532534 0.46766773 0.09258675 0.76509434]
  [0.25070461 0.92957501 0.99987221 0.60910503 0.20918436]]

 [[0.66126563 0.53523404 0.80271972 0.25130894 0.14583565]
  [0.7508927  0.80204137 0.75656769 0.52768556 0.0693454 ]
  [0.25138246 0.3608286  0.11840921 0.54703718 0.90024   ]]]
[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]
[[[0.93888285 0.41392902 0.869702   0.75641957 0.2210088 ]
  [0.39848989 0.99532534 0.46766773 0.09258675 0.76509434]
  [0.25070461 0.92957501 0.99987221 0.60910503 0.20918436]]

 [[0.66126563 0.53523404 0.80271972 0.25130894 0.14583565]
  [0.7508927  0.80204137 0.75656769 0.52768556 0.0693454 ]
  [0.25138246 0.3608286  0.11840921 0.54703718 0.90024   ]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
np.array_equal(a, e)
# they are equal because e is all values in array a multiplied with all values in c that are all ones

True

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
d_max = np.max(d)
print(d_max)
d_min = np.min(d)
print(d_min)
d_mean = np.sum(d) / np.size(d)
print(d_mean)

1.999872211016044
1.0693453978326763
1.5466113885155959


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [22]:
f = np.empty(shape = (2,3,5), dtype = float)

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [23]:
for x in range(d.shape[0]):
    for y in range(d.shape[1]):
        for z in range(d.shape[2]):
            if d[x,y,z] > d_min and d[x,y,z] < d_mean:
                f[x,y,z] = 25
            elif d[x,y,z] > d_mean and d[x,y,z] < d_max:
                f[x,y,z] = 75
            elif d[x,y,z] == d_mean:
                f[x,y,z] = 50
            elif d[x,y,z] == d_max:
                f[x,y,z] = 100
            else:
                f[x,y,z] = 0

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [24]:
print(d)
print(f)

[[[1.93888285 1.41392902 1.869702   1.75641957 1.2210088 ]
  [1.39848989 1.99532534 1.46766773 1.09258675 1.76509434]
  [1.25070461 1.92957501 1.99987221 1.60910503 1.20918436]]

 [[1.66126563 1.53523404 1.80271972 1.25130894 1.14583565]
  [1.7508927  1.80204137 1.75656769 1.52768556 1.0693454 ]
  [1.25138246 1.3608286  1.11840921 1.54703718 1.90024   ]]]
[[[ 75.  25.  75.  75.  25.]
  [ 25.  75.  25.  25.  75.]
  [ 25.  75. 100.  75.  25.]]

 [[ 75.  25.  75.  25.  25.]
  [ 75.  75.  75.  25.   0.]
  [ 25.  25.  25.  75.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [26]:
g = np.empty(shape = (2,3,5), dtype = '<U1')

for x in range(d.shape[0]):
    for y in range(d.shape[1]):
        for z in range(d.shape[2]):
            if d[x,y,z] > d_min and d[x,y,z] < d_mean:
                g[x,y,z] = 'B'
            elif d[x,y,z] > d_mean and d[x,y,z] < d_max:
                g[x,y,z] = 'D'
            elif d[x,y,z] == d_mean:
                g[x,y,z] = 'C'
            elif d[x,y,z] == d_max:
                g[x,y,z] = 'E'
            else:
                g[x,y,z] = 'A'

print(g)

[[['D' 'B' 'D' 'D' 'B']
  ['B' 'D' 'B' 'B' 'D']
  ['B' 'D' 'E' 'D' 'B']]

 [['D' 'B' 'D' 'B' 'B']
  ['D' 'D' 'D' 'B' 'A']
  ['B' 'B' 'B' 'D' 'D']]]
