# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.__version__)

1.20.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a=np.random.random((2,3,5))

#apenas para treinar como saber a dimensão e o shape
a.ndim
a.shape

(2, 3, 5)

In [4]:
# Method 2
a=np.arange(0,30, dtype=float).reshape(2,3,5)

#apenas para treinar como saber a dimensão
a.ndim

3

In [5]:
# Method 3
a=np.random.rand(2,3,5)

#### 4. Print *a*.


In [6]:
# your code here
print(a)

[[[0.86781702 0.35870152 0.93380593 0.55225396 0.92488749]
  [0.71780239 0.0368752  0.3022634  0.78050567 0.98566253]
  [0.36745095 0.688152   0.54003506 0.42075177 0.16240032]]

 [[0.55758606 0.1489796  0.14671314 0.78433495 0.55885519]
  [0.85675633 0.66385565 0.15131647 0.36781028 0.13023804]
  [0.97211918 0.57670905 0.21892081 0.77525353 0.84196704]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here
b=np.ones((5,2,3), dtype=int)


#### 6. Print *b*.


In [8]:
# your code here
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [17]:
# your code here
a.size==b.size


True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [20]:
# your answer here
a+b
#no because they have different shapes


ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [21]:
a.shape==b.shape

False

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [22]:
# your code here
c=b.reshape(2,3,5)
print(c)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [23]:
# your code/answer here
d=a+c
#It works because a and c have the same structure now

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [25]:
# your code/answer here
print(a)

print(d)

#The values of the array d are the values of a + the values of c

[[[0.86781702 0.35870152 0.93380593 0.55225396 0.92488749]
  [0.71780239 0.0368752  0.3022634  0.78050567 0.98566253]
  [0.36745095 0.688152   0.54003506 0.42075177 0.16240032]]

 [[0.55758606 0.1489796  0.14671314 0.78433495 0.55885519]
  [0.85675633 0.66385565 0.15131647 0.36781028 0.13023804]
  [0.97211918 0.57670905 0.21892081 0.77525353 0.84196704]]]
[[[1.86781702 1.35870152 1.93380593 1.55225396 1.92488749]
  [1.71780239 1.0368752  1.3022634  1.78050567 1.98566253]
  [1.36745095 1.688152   1.54003506 1.42075177 1.16240032]]

 [[1.55758606 1.1489796  1.14671314 1.78433495 1.55885519]
  [1.85675633 1.66385565 1.15131647 1.36781028 1.13023804]
  [1.97211918 1.57670905 1.21892081 1.77525353 1.84196704]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [26]:
# your code here
e=a*c

#### 13. Does *e* equal to *a*? Why or why not?


In [28]:
# your code/answer here
print(e)
a==e
#Yes, because the values of e are the values of a times the values of c(that means, times 1, since the values of c are 1)

[[[0.86781702 0.35870152 0.93380593 0.55225396 0.92488749]
  [0.71780239 0.0368752  0.3022634  0.78050567 0.98566253]
  [0.36745095 0.688152   0.54003506 0.42075177 0.16240032]]

 [[0.55758606 0.1489796  0.14671314 0.78433495 0.55885519]
  [0.85675633 0.66385565 0.15131647 0.36781028 0.13023804]
  [0.97211918 0.57670905 0.21892081 0.77525353 0.84196704]]]


array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [30]:
# your code here
d_max=d.max()
d_min=d.min()
d_mean=d.mean()
print(d_max)
print(d_min)
print(d_mean)

1.9856625255804508
1.036875199946738
1.5463593512053542


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [32]:
# your code here
f=np.empty([2,3,5])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [93]:
# your code here

f_list=[]

for sublist in d:
    for subsublist in sublist:
        for value in subsublist:
            if (d_min<value) and (value<d_mean):
                f_list.append(25.)
            elif (d_mean<value) and (d_max>value):
                f_list.append(75.)
            elif (value==d_mean):
                f_list.append(50.)
            elif (value==d_min):
                f_list.append(0.)
            elif (value==d_max):
                f_list.append(100.)

                               
f=np.array(f_list).reshape([2,3,5])




                   

In [85]:
f1 = 25 * (d > d_min) * (d < d_mean) + 75 * (d < d_max) * (d > d_mean) + 0 * (d == d_min) + 100 * (d == d_max)
print(f1)

[[[ 75  25  75  75  75]
  [ 75   0  25  75 100]
  [ 25  75  25  25  25]]

 [[ 75  25  25  75  75]
  [ 75  75  25  25  25]
  [ 75  75  25  75  75]]]


In [ ]:
#PQ NÃO FUNCIONA O CÓDIGO ABAIXO?? PERGUNTAR FELIPE


#for sublist in d:
#    for subsublist in sublist:
#        for value in subsublist:
#            if (d_min<value) and (value<d_mean):
#                np.append(f,25.)
#            elif (d_mean<value) and (d_max>value):
#                np.append(75.)
#            elif (value==d_mean):
#                np.append(50.)
#            elif (value==d_min):
#                np.append(0.)
#            elif (value==d_max):
#               np.append(100.)

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [94]:
# your code here
print(d)

print(f)

[[[1.86781702 1.35870152 1.93380593 1.55225396 1.92488749]
  [1.71780239 1.0368752  1.3022634  1.78050567 1.98566253]
  [1.36745095 1.688152   1.54003506 1.42075177 1.16240032]]

 [[1.55758606 1.1489796  1.14671314 1.78433495 1.55885519]
  [1.85675633 1.66385565 1.15131647 1.36781028 1.13023804]
  [1.97211918 1.57670905 1.21892081 1.77525353 1.84196704]]]
[[[ 75.  25.  75.  75.  75.]
  [ 75.   0.  25.  75. 100.]
  [ 25.  75.  25.  25.  25.]]

 [[ 75.  25.  25.  75.  75.]
  [ 75.  75.  25.  25.  25.]
  [ 75.  75.  25.  75.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [96]:
# your code here
f_list_2=[]

for sublist in d:
    for subsublist in sublist:
        for value in subsublist:
            if (d_min<value) and (value<d_mean):
                f_list_2.append('A')
            elif (d_mean<value) and (d_max>value):
                f_list_2.append('B')
            elif (value==d_mean):
                f_list_2.append('C')
            elif (value==d_min):
                f_list_2.append('D')
            elif  (value==d_max):
                f_list_2.append('E')

                
#np.append(f,100)
                
f=np.array(f_list_2).reshape([2,3,5])

In [97]:
print(f)

[[['B' 'A' 'B' 'B' 'B']
  ['B' 'D' 'A' 'B' 'E']
  ['A' 'B' 'A' 'A' 'A']]

 [['B' 'A' 'A' 'B' 'B']
  ['B' 'B' 'A' 'A' 'A']
  ['B' 'B' 'A' 'B' 'B']]]
