# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [2]:
import numpy as np

#### 2. Print your NumPy version.

In [6]:
np.version.version

'1.24.2'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [4]:
import numpy as np

a = np.random.rand(2, 3, 5)
print(a)

[[[0.22994732 0.85402183 0.06920446 0.12713647 0.54553723]
  [0.19333446 0.77719632 0.04050665 0.34264043 0.42888035]
  [0.70225931 0.36629179 0.37707756 0.98780883 0.29479798]]

 [[0.12754452 0.76775833 0.44568838 0.93092892 0.49618978]
  [0.24180846 0.11185735 0.67726857 0.95342851 0.81956733]
  [0.08979878 0.68055134 0.39471544 0.92338688 0.03363388]]]


In [9]:
b = np.random.sample(size = (2,3,5))
print (b)

[[[0.6392745  0.71473923 0.97765037 0.83331926 0.89510351]
  [0.48030721 0.9675124  0.82132377 0.71452134 0.49720732]
  [0.73294762 0.55329364 0.99652628 0.14991591 0.687638  ]]

 [[0.49061146 0.61152264 0.21450827 0.32045128 0.72902605]
  [0.28096238 0.1672366  0.61700693 0.22539691 0.28688449]
  [0.99528979 0.70439625 0.90060238 0.8062965  0.82237096]]]


In [10]:
c = np.random.random(size = (2,3,5))
print (c)

[[[0.88489881 0.40434761 0.43798143 0.17691545 0.7069395 ]
  [0.05894542 0.04949018 0.12233392 0.44478056 0.49289665]
  [0.46723047 0.61230726 0.75699837 0.78097504 0.39062554]]

 [[0.1579316  0.4783604  0.75666945 0.51036347 0.50104765]
  [0.1059208  0.10630203 0.23485837 0.17837837 0.89807836]
  [0.07171612 0.79254671 0.09423846 0.50079385 0.74610346]]]


#### 4. Print *a*.


In [11]:
print (a)

[[[0.22994732 0.85402183 0.06920446 0.12713647 0.54553723]
  [0.19333446 0.77719632 0.04050665 0.34264043 0.42888035]
  [0.70225931 0.36629179 0.37707756 0.98780883 0.29479798]]

 [[0.12754452 0.76775833 0.44568838 0.93092892 0.49618978]
  [0.24180846 0.11185735 0.67726857 0.95342851 0.81956733]
  [0.08979878 0.68055134 0.39471544 0.92338688 0.03363388]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [12]:
b = np.ones(shape = (5,2,3), dtype = int)

#### 6. Print *b*.


In [13]:
print (b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [14]:
a == b

C:\Users\Leticia Demarchi\AppData\Local\Temp\ipykernel_27480\160026346.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  a == b


False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [15]:
a + b

# the different size

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [16]:
c = b.transpose()
c

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [19]:
c = c.reshape(2,3,5)
d = a + c

print (d)



[[[1.22994732 1.85402183 1.06920446 1.12713647 1.54553723]
  [1.19333446 1.77719632 1.04050665 1.34264043 1.42888035]
  [1.70225931 1.36629179 1.37707756 1.98780883 1.29479798]]

 [[1.12754452 1.76775833 1.44568838 1.93092892 1.49618978]
  [1.24180846 1.11185735 1.67726857 1.95342851 1.81956733]
  [1.08979878 1.68055134 1.39471544 1.92338688 1.03363388]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [21]:
print(a)
print(d)

# Different because i added variable c to d

[[[0.22994732 0.85402183 0.06920446 0.12713647 0.54553723]
  [0.19333446 0.77719632 0.04050665 0.34264043 0.42888035]
  [0.70225931 0.36629179 0.37707756 0.98780883 0.29479798]]

 [[0.12754452 0.76775833 0.44568838 0.93092892 0.49618978]
  [0.24180846 0.11185735 0.67726857 0.95342851 0.81956733]
  [0.08979878 0.68055134 0.39471544 0.92338688 0.03363388]]]
[[[1.22994732 1.85402183 1.06920446 1.12713647 1.54553723]
  [1.19333446 1.77719632 1.04050665 1.34264043 1.42888035]
  [1.70225931 1.36629179 1.37707756 1.98780883 1.29479798]]

 [[1.12754452 1.76775833 1.44568838 1.93092892 1.49618978]
  [1.24180846 1.11185735 1.67726857 1.95342851 1.81956733]
  [1.08979878 1.68055134 1.39471544 1.92338688 1.03363388]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [22]:
e = a * c
print (e)

[[[0.22994732 0.85402183 0.06920446 0.12713647 0.54553723]
  [0.19333446 0.77719632 0.04050665 0.34264043 0.42888035]
  [0.70225931 0.36629179 0.37707756 0.98780883 0.29479798]]

 [[0.12754452 0.76775833 0.44568838 0.93092892 0.49618978]
  [0.24180846 0.11185735 0.67726857 0.95342851 0.81956733]
  [0.08979878 0.68055134 0.39471544 0.92338688 0.03363388]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [23]:
e == a

# Its true because they have same value.

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [24]:
d_max = d.max()
d_min = d.min()
d_mean =d.mean()

print(d_max)
print(d_min)
print(d_mean)

1.9878088273725407
1.0336338785069095
1.4676922484288266


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [25]:
f = np.empty(shape = (2,3,5))
print (f)

[[[0.22994732 0.85402183 0.06920446 0.12713647 0.54553723]
  [0.19333446 0.77719632 0.04050665 0.34264043 0.42888035]
  [0.70225931 0.36629179 0.37707756 0.98780883 0.29479798]]

 [[0.12754452 0.76775833 0.44568838 0.93092892 0.49618978]
  [0.24180846 0.11185735 0.67726857 0.95342851 0.81956733]
  [0.08979878 0.68055134 0.39471544 0.92338688 0.03363388]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [52]:
d_min = d.min()
d_max = d.max()
d_mean = d.mean()


f_populate = [0] * len(d)  

for i in range(len(d)):
    if d[i] == d_min:
        f_populate[i] = 0
    if d_min < d[i] < d_mean:
        f_populate[i] <= 25
    if d[i] == d_mean:
        f_populate[i] <= 50
    elif d_mean < d[i] < d_max:
        f_populate[i] <= 75
    else d[i] == d_max:
        f_populate[i] >= 100

SyntaxError: expected ':' (2206072419.py, line 17)

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [54]:
print("d =", d)


print("f =", f)

d = [[[1.22994732 1.85402183 1.06920446 1.12713647 1.54553723]
  [1.19333446 1.77719632 1.04050665 1.34264043 1.42888035]
  [1.70225931 1.36629179 1.37707756 1.98780883 1.29479798]]

 [[1.12754452 1.76775833 1.44568838 1.93092892 1.49618978]
  [1.24180846 1.11185735 1.67726857 1.95342851 1.81956733]
  [1.08979878 1.68055134 1.39471544 1.92338688 1.03363388]]]
f = [[[25, 75, 25, 25, 75], [25, 75, 25, 25, 25], [75, 25, 25, 100, 25]], [[25, 75, 25, 75, 75], [25, 25, 75, 75, 75], [25, 75, 25, 75, 0]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

ValueError: could not convert string to float: 'B'