# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [3]:
import numpy as np

#### 2. Print your NumPy version.

In [4]:
print('NumPy version ', np.version.version)

NumPy version  1.21.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [5]:
# Method 1 :
from numpy.random import default_rng
default_rng().random((2,3,5))

array([[[0.49124169, 0.61662417, 0.22696519, 0.82437445, 0.56495361],
        [0.8040861 , 0.32476507, 0.15342866, 0.86888934, 0.48669593],
        [0.84577651, 0.23119729, 0.298772  , 0.51598991, 0.43104926]],

       [[0.28605839, 0.11757199, 0.61813511, 0.5563093 , 0.02271394],
        [0.99026919, 0.1542093 , 0.86643939, 0.65229791, 0.65780072],
        [0.60874595, 0.68521053, 0.81051129, 0.29454926, 0.93984778]]])

In [6]:
# Method 2 (not sure if this counts)
np.indices((3,5))

array([[[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

In [7]:
# Method 3
np.random.rand(2,3,5)

array([[[0.07945509, 0.21197343, 0.88460671, 0.08406554, 0.43531483],
        [0.47423558, 0.75609191, 0.2116488 , 0.94229273, 0.0251203 ],
        [0.66895486, 0.99780554, 0.23502344, 0.10967702, 0.94416821]],

       [[0.59014129, 0.91042138, 0.29572563, 0.62432935, 0.39139568],
        [0.65328726, 0.93337717, 0.05558831, 0.06084968, 0.04269458],
        [0.26231223, 0.40686151, 0.15586606, 0.17450013, 0.87264132]]])

In [8]:
#Method 4
a = np.array([[np.random.rand(5) for x in range(0,3)] for i in range(0,2)])

#### 4. Print *a*.


In [9]:
print(a)

[[[5.23680818e-01 4.79935695e-01 1.05210636e-01 9.67373827e-01
   6.78064336e-02]
  [8.24645168e-01 9.86623256e-01 6.02620237e-01 3.03262263e-01
   5.71973944e-01]
  [9.58929872e-01 1.66995452e-01 5.03152469e-01 6.33873490e-01
   6.97277399e-01]]

 [[6.22727850e-01 1.18227568e-01 8.79024327e-01 7.48560786e-01
   7.91260509e-01]
  [8.48709683e-01 2.47277214e-01 9.24337938e-01 5.46470791e-04
   6.95129392e-01]
  [3.74239897e-01 4.36561167e-01 2.66613103e-01 3.15421679e-01
   3.49640061e-01]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [10]:
b = np.ones([5,2,3])

#### 6. Print *b*.


In [11]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [12]:
#
print(f'If len(a) = {len(a)} and len(b) = {len(b)} than {len(a) == len(b)}')
#To see if the size is the samen we should use:
print(a.size == b.size)

If len(a) = 2 and len(b) = 5 than False
True


#### 8. Are you able to add *a* and *b*? Why or why not?


In [13]:
#If it's possible? No.

ab = a+b
print(ab)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [16]:
#2 is n. of times, 3 n. of rows, 5 n. columns
c = b.reshape([2,3,5])
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [17]:
d = a+c
print(d)

[[[1.52368082 1.47993569 1.10521064 1.96737383 1.06780643]
  [1.82464517 1.98662326 1.60262024 1.30326226 1.57197394]
  [1.95892987 1.16699545 1.50315247 1.63387349 1.6972774 ]]

 [[1.62272785 1.11822757 1.87902433 1.74856079 1.79126051]
  [1.84870968 1.24727721 1.92433794 1.00054647 1.69512939]
  [1.3742399  1.43656117 1.2666131  1.31542168 1.34964006]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [18]:
print(a)
print(d)
#'d' is each value in 'a' with one value added
#because when we added 'c' to 'a' what we did was just that, add the value of one cell of 'a' to 'c'
print(d-1)

[[[5.23680818e-01 4.79935695e-01 1.05210636e-01 9.67373827e-01
   6.78064336e-02]
  [8.24645168e-01 9.86623256e-01 6.02620237e-01 3.03262263e-01
   5.71973944e-01]
  [9.58929872e-01 1.66995452e-01 5.03152469e-01 6.33873490e-01
   6.97277399e-01]]

 [[6.22727850e-01 1.18227568e-01 8.79024327e-01 7.48560786e-01
   7.91260509e-01]
  [8.48709683e-01 2.47277214e-01 9.24337938e-01 5.46470791e-04
   6.95129392e-01]
  [3.74239897e-01 4.36561167e-01 2.66613103e-01 3.15421679e-01
   3.49640061e-01]]]
[[[1.52368082 1.47993569 1.10521064 1.96737383 1.06780643]
  [1.82464517 1.98662326 1.60262024 1.30326226 1.57197394]
  [1.95892987 1.16699545 1.50315247 1.63387349 1.6972774 ]]

 [[1.62272785 1.11822757 1.87902433 1.74856079 1.79126051]
  [1.84870968 1.24727721 1.92433794 1.00054647 1.69512939]
  [1.3742399  1.43656117 1.2666131  1.31542168 1.34964006]]]
[[[5.23680818e-01 4.79935695e-01 1.05210636e-01 9.67373827e-01
   6.78064336e-02]
  [8.24645168e-01 9.86623256e-01 6.02620237e-01 3.03262263e-01
 

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [19]:
e = a*c
print(e)

[[[5.23680818e-01 4.79935695e-01 1.05210636e-01 9.67373827e-01
   6.78064336e-02]
  [8.24645168e-01 9.86623256e-01 6.02620237e-01 3.03262263e-01
   5.71973944e-01]
  [9.58929872e-01 1.66995452e-01 5.03152469e-01 6.33873490e-01
   6.97277399e-01]]

 [[6.22727850e-01 1.18227568e-01 8.79024327e-01 7.48560786e-01
   7.91260509e-01]
  [8.48709683e-01 2.47277214e-01 9.24337938e-01 5.46470791e-04
   6.95129392e-01]
  [3.74239897e-01 4.36561167e-01 2.66613103e-01 3.15421679e-01
   3.49640061e-01]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [20]:
#As explain in 11. what happens is that we are multiplying each value of 'c' by the same position in 'a'
#ex.: array[x y]*array[z w] = [x*z y*w]

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [21]:
d_max = np.amax(d)
d_min = np.amin(d)
d_mean = np.mean(d)
print(d_max, d_min, d_mean)

1.9866232564924258 1.0005464707914906 1.5337212867655383


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [22]:
f = np.empty((2,3,5))
print(f)

[[[5.23680818e-01 4.79935695e-01 1.05210636e-01 9.67373827e-01
   6.78064336e-02]
  [8.24645168e-01 9.86623256e-01 6.02620237e-01 3.03262263e-01
   5.71973944e-01]
  [9.58929872e-01 1.66995452e-01 5.03152469e-01 6.33873490e-01
   6.97277399e-01]]

 [[6.22727850e-01 1.18227568e-01 8.79024327e-01 7.48560786e-01
   7.91260509e-01]
  [8.48709683e-01 2.47277214e-01 9.24337938e-01 5.46470791e-04
   6.95129392e-01]
  [3.74239897e-01 4.36561167e-01 2.66613103e-01 3.15421679e-01
   3.49640061e-01]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

for value in 'd'
    if value>d_min and value<d_mean = 25
    if value>dmean and value<d_max = 75
    if value == d_mean = 50
    if value == d_min = 0
    if value == d_max = 100

In [23]:
for index, x in np.ndenumerate(d):
        if x == d_min:
            f[index] = 0
        elif x < d_mean:
            f[index] = 25
        elif x == d_mean:
            f[index] = 50
        elif x < d_max:
            f[index] = 75
        elif x == d_max:
            f[index] = 100
print(f)

[[[ 25.  25.  25.  75.  25.]
  [ 75. 100.  75.  25.  75.]
  [ 75.  25.  25.  75.  75.]]

 [[ 75.  25.  75.  75.  75.]
  [ 75.  25.  75.   0.  75.]
  [ 25.  25.  25.  25.  25.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [24]:
print(d)
print(f)

[[[1.52368082 1.47993569 1.10521064 1.96737383 1.06780643]
  [1.82464517 1.98662326 1.60262024 1.30326226 1.57197394]
  [1.95892987 1.16699545 1.50315247 1.63387349 1.6972774 ]]

 [[1.62272785 1.11822757 1.87902433 1.74856079 1.79126051]
  [1.84870968 1.24727721 1.92433794 1.00054647 1.69512939]
  [1.3742399  1.43656117 1.2666131  1.31542168 1.34964006]]]
[[[ 25.  25.  25.  75.  25.]
  [ 75. 100.  75.  25.  75.]
  [ 75.  25.  25.  75.  75.]]

 [[ 75.  25.  75.  75.  75.]
  [ 75.  25.  75.   0.  75.]
  [ 25.  25.  25.  25.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [44]:
#f.insert(index, value)
#f.pop(1)  2x3x5)

f = f.astype(str)

for index, x in np.ndenumerate(d):
        if x == d_min:
            f[index] = 'A'
        elif x < d_mean:
            f[index] = 'B'
        elif x == d_mean:
            f[index] = 'C'
        elif x < d_max:
            f[index] = 'D'
        elif x == d_max:
            f[index] = 'E'
print(f)



[[['B' 'B' 'B' 'D' 'B']
  ['D' 'E' 'D' 'B' 'D']
  ['D' 'B' 'B' 'D' 'D']]

 [['D' 'B' 'D' 'D' 'D']
  ['D' 'B' 'D' 'A' 'D']
  ['B' 'B' 'B' 'B' 'B']]]
