# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [2]:
a=np.random.random(size=(3,2,5))


In [3]:
# Method 2

In [4]:
# Method 3

#### 4. Print *a*.


In [5]:
print(a)

[[[0.75716121 0.50060247 0.57706944 0.43329046 0.86315914]
  [0.57949221 0.74315835 0.64102716 0.83587028 0.92585434]]

 [[0.74360225 0.09493323 0.47544044 0.93329088 0.92236719]
  [0.94893206 0.96643726 0.85268128 0.1364467  0.46767531]]

 [[0.6440603  0.17703333 0.37707356 0.55497724 0.35677872]
  [0.72122883 0.91063777 0.45816023 0.30434318 0.43717424]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [6]:
b= np.ones((5,2,3))

#### 6. Print *b*.


In [7]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [8]:
a.shape==b.shape


False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [9]:
a+b
#no because because they don't have the same shape

ValueError: operands could not be broadcast together with shapes (3,2,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [ ]:
c= b.transpose()
c.shape

(3, 2, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [ ]:
d=a+c

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [ ]:
print(a)
print(d)
#each value from c was added to each value of a by the same order

[[[0.54705881 0.6241156  0.22263906 0.52658263 0.32773221]
  [0.05190546 0.9635994  0.42652851 0.86058452 0.85621733]]

 [[0.29061373 0.65251373 0.4064845  0.40534852 0.78013091]
  [0.54248035 0.07022275 0.99182199 0.83716219 0.68381118]]

 [[0.62931624 0.34492526 0.85653972 0.47385678 0.58339542]
  [0.47744696 0.875733   0.6434055  0.90755858 0.17762875]]]
[[[1.54705881 1.6241156  1.22263906 1.52658263 1.32773221]
  [1.05190546 1.9635994  1.42652851 1.86058452 1.85621733]]

 [[1.29061373 1.65251373 1.4064845  1.40534852 1.78013091]
  [1.54248035 1.07022275 1.99182199 1.83716219 1.68381118]]

 [[1.62931624 1.34492526 1.85653972 1.47385678 1.58339542]
  [1.47744696 1.875733   1.6434055  1.90755858 1.17762875]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [ ]:
e=a*c

#### 13. Does *e* equal to *a*? Why or why not?


In [ ]:
print(e)
#yes, it is thats because we are multiplying each value of a by 1 so it returns the same array

[[[0.54705881 0.6241156  0.22263906 0.52658263 0.32773221]
  [0.05190546 0.9635994  0.42652851 0.86058452 0.85621733]]

 [[0.29061373 0.65251373 0.4064845  0.40534852 0.78013091]
  [0.54248035 0.07022275 0.99182199 0.83716219 0.68381118]]

 [[0.62931624 0.34492526 0.85653972 0.47385678 0.58339542]
  [0.47744696 0.875733   0.6434055  0.90755858 0.17762875]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [ ]:
d_max=np.max(d)
d_min=np.min(d)
d_mean=np.mean(d)
print(d_max, d_mean,d_min)



1.991821994393632 1.5679119856020025 1.0519054569535518


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [ ]:
f=np.empty((2,3,5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [ ]:
empty_list=[]
for dim in d:
    for column in dim:
        for row in column:
            if row > d_min and row<d_mean:
               empty_list.append(25)
            elif row < d_max and row>d_mean:
                empty_list.append(75)
            elif row == d_mean:
                empty_list.append(50)
            elif row == d_min:
                empty_list.append(0)
            elif row == d_max:
                empty_list.append(100)
f=np.array(empty_list)
f=f.reshape((2,3,5))

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
print(d)
print(f)

[[[1.54705881 1.6241156  1.22263906 1.52658263 1.32773221]
  [1.05190546 1.9635994  1.42652851 1.86058452 1.85621733]]

 [[1.29061373 1.65251373 1.4064845  1.40534852 1.78013091]
  [1.54248035 1.07022275 1.99182199 1.83716219 1.68381118]]

 [[1.62931624 1.34492526 1.85653972 1.47385678 1.58339542]
  [1.47744696 1.875733   1.6434055  1.90755858 1.17762875]]]
[[[ 25  75  25  25  25]
  [  0  75  25  75  75]
  [ 25  75  25  25  75]]

 [[ 25  25 100  75  75]
  [ 75  25  75  25  75]
  [ 25  75  75  75  25]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here