# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [67]:
# your code here

import numpy as np

#### 2. Print your NumPy version.

In [68]:
# your code here

print("NumPy Version : ",np.__version__)

NumPy Version :  1.21.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [69]:
# Method 1

a = np.random.random((2,3,5))

#other function
a = np.random.rand(2, 3 ,5)

# and:

a = np.empty([2,3,5])

print(a)

[[[0.35793847 0.40996213 0.60830382 0.61781197 0.33166755]
  [0.85513169 0.45136871 0.0076041  0.41419069 0.66573431]
  [0.75484761 0.10334251 0.32985868 0.88079135 0.25957427]]

 [[0.43381307 0.3714888  0.99773194 0.70878303 0.01332523]
  [0.46113306 0.05420083 0.92507867 0.61934015 0.94529067]
  [0.2600193  0.71178645 0.23364098 0.73541268 0.87593501]]]


In [70]:
# Method 2

a = np.random.rand(2, 3 ,5) * np.ones(shape = (2,3,5), dtype = float)
a

array([[[0.51771025, 0.90787948, 0.56639522, 0.01361848, 0.71867775],
        [0.92421535, 0.22735349, 0.3379502 , 0.88823404, 0.50536123],
        [0.82811882, 0.67207153, 0.20800767, 0.64159949, 0.665536  ]],

       [[0.44002483, 0.31685517, 0.77671594, 0.730269  , 0.32756126],
        [0.54440055, 0.39393172, 0.07478157, 0.01916929, 0.89076804],
        [0.29279902, 0.33118528, 0.33682272, 0.11551773, 0.40921701]]])

In [71]:
# Method 3

a = np.random.random((2,3,5)) + np.zeros(shape = (2,3,5), dtype = float)
a

array([[[0.36279253, 0.6456686 , 0.52435924, 0.77394589, 0.13135545],
        [0.81777708, 0.39292733, 0.47840306, 0.06814943, 0.91716956],
        [0.0353387 , 0.03100087, 0.12930546, 0.38493171, 0.80560073]],

       [[0.75501758, 0.47783621, 0.51755396, 0.23553356, 0.76662776],
        [0.88238481, 0.46597505, 0.89383904, 0.43401241, 0.27678708],
        [0.60348689, 0.17954692, 0.87377283, 0.58925327, 0.28375647]]])

#### 4. Print *a*.


In [72]:
# your code here

print(a)

[[[0.36279253 0.6456686  0.52435924 0.77394589 0.13135545]
  [0.81777708 0.39292733 0.47840306 0.06814943 0.91716956]
  [0.0353387  0.03100087 0.12930546 0.38493171 0.80560073]]

 [[0.75501758 0.47783621 0.51755396 0.23553356 0.76662776]
  [0.88238481 0.46597505 0.89383904 0.43401241 0.27678708]
  [0.60348689 0.17954692 0.87377283 0.58925327 0.28375647]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [73]:
# your code here

b = np.ones(shape = (5,3,2))

#### 6. Print *b*.


In [74]:
# your code here

print(b)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [75]:
# your code here

# a and b have the same number of elements, but they have different sizes:

print(a.shape)
print(b.shape)

(2, 3, 5)
(5, 3, 2)


#### 8. Are you able to add *a* and *b*? Why or why not?


In [76]:
# your answer here

a+b

#we are not able to add a and b because the two arrays have different sizes:

#ValueError: operands could not be broadcast together with shapes (2,3,5) (5,3,2) 

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,3,2) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [78]:
# your code here

c = b.transpose()
print(c.shape)
c

(2, 3, 5)


array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [79]:
# your code/answer here

# now we are able to sum these two arrays as they are now the same size (transpose of b becomes the shape of a):
d = a + c
d

array([[[1.36279253, 1.6456686 , 1.52435924, 1.77394589, 1.13135545],
        [1.81777708, 1.39292733, 1.47840306, 1.06814943, 1.91716956],
        [1.0353387 , 1.03100087, 1.12930546, 1.38493171, 1.80560073]],

       [[1.75501758, 1.47783621, 1.51755396, 1.23553356, 1.76662776],
        [1.88238481, 1.46597505, 1.89383904, 1.43401241, 1.27678708],
        [1.60348689, 1.17954692, 1.87377283, 1.58925327, 1.28375647]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [80]:
# your code/answer here

print(a)

print(d)

#a was based on random float numbers that are always between 1 and 0. d was based on a plus the array c which only contains ones

[[[0.36279253 0.6456686  0.52435924 0.77394589 0.13135545]
  [0.81777708 0.39292733 0.47840306 0.06814943 0.91716956]
  [0.0353387  0.03100087 0.12930546 0.38493171 0.80560073]]

 [[0.75501758 0.47783621 0.51755396 0.23553356 0.76662776]
  [0.88238481 0.46597505 0.89383904 0.43401241 0.27678708]
  [0.60348689 0.17954692 0.87377283 0.58925327 0.28375647]]]
[[[1.36279253 1.6456686  1.52435924 1.77394589 1.13135545]
  [1.81777708 1.39292733 1.47840306 1.06814943 1.91716956]
  [1.0353387  1.03100087 1.12930546 1.38493171 1.80560073]]

 [[1.75501758 1.47783621 1.51755396 1.23553356 1.76662776]
  [1.88238481 1.46597505 1.89383904 1.43401241 1.27678708]
  [1.60348689 1.17954692 1.87377283 1.58925327 1.28375647]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [81]:
# your code here

e = a*c
e

array([[[0.36279253, 0.6456686 , 0.52435924, 0.77394589, 0.13135545],
        [0.81777708, 0.39292733, 0.47840306, 0.06814943, 0.91716956],
        [0.0353387 , 0.03100087, 0.12930546, 0.38493171, 0.80560073]],

       [[0.75501758, 0.47783621, 0.51755396, 0.23553356, 0.76662776],
        [0.88238481, 0.46597505, 0.89383904, 0.43401241, 0.27678708],
        [0.60348689, 0.17954692, 0.87377283, 0.58925327, 0.28375647]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [82]:
# your code/answer here
e == a

#because e is the product of the multiplication of an array with one. Any number multiplied by one equals itself. Thus e = a*1 = a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [83]:
# your code here

d_max = d.max()

d_min = d.min()

d_mean = d.mean()

print(d_max)
print(d_min)
print(d_mean)

1.917169559197628
1.0310008668982895
1.4911369815009516


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [84]:
# your code here

f = np.empty([2,3,5])
f 

array([[[0.36279253, 0.6456686 , 0.52435924, 0.77394589, 0.13135545],
        [0.81777708, 0.39292733, 0.47840306, 0.06814943, 0.91716956],
        [0.0353387 , 0.03100087, 0.12930546, 0.38493171, 0.80560073]],

       [[0.75501758, 0.47783621, 0.51755396, 0.23553356, 0.76662776],
        [0.88238481, 0.46597505, 0.89383904, 0.43401241, 0.27678708],
        [0.60348689, 0.17954692, 0.87377283, 0.58925327, 0.28375647]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [85]:
# your code here

conditions = [(d == d_min), (d > d_min) & (d < d_mean), (d == d_mean), (d > d_mean) & (d < d_max), (d == d_max)]
choices = [0,25,50,75,100]

f = np.select(conditions, choices)

print(f)

print(f.shape)

[[[ 25  75  75  75  25]
  [ 75  25  25  25 100]
  [ 25   0  25  25  75]]

 [[ 75  25  75  25  75]
  [ 75  25  75  25  25]
  [ 75  25  75  75  25]]]
(2, 3, 5)


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [89]:
# your code here

d = [[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]

print(type(d))
d = np.asarray(d)

d_max = d.max()
d_min = d.min()
d_mean = d.mean()

print(d_max)
print(d_min)
print(d_mean)

expected = [[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
            
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]

conditions = [(d == d_min), (d > d_min) & (d < d_mean), (d == d_mean), (d > d_mean) & (d < d_max), (d == d_max)]
choices = [0,25,50,75,100]

res = np.select(conditions, choices)

res == expected

<class 'list'>
1.97066381
1.00656599
1.6175069086666667


array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [90]:
# your code here

conditions = [(d == d_min), (d > d_min) & (d < d_mean), (d == d_mean), (d > d_mean) & (d < d_max), (d == d_max)]
choices = ["A","B","C","D","E"]

res = np.select(conditions, choices)

print(res)


[[['D' 'D' 'D' 'B' 'D']
  ['D' 'D' 'B' 'B' 'B']
  ['D' 'B' 'D' 'D' 'D']]

 [['B' 'B' 'B' 'B' 'E']
  ['D' 'D' 'D' 'D' 'D']
  ['B' 'D' 'A' 'D' 'D']]]
