# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [93]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [94]:
# your code here
print(np.__version__)

1.18.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [95]:
# Method 1
a = np.random.random((2,3,5))
a

array([[[0.00698894, 0.0723351 , 0.51694169, 0.93115855, 0.76534616],
        [0.73529063, 0.22790399, 0.37438297, 0.27864282, 0.71474998],
        [0.33332167, 0.07054892, 0.23785229, 0.54560333, 0.68991255]],

       [[0.67882238, 0.38458908, 0.29634586, 0.38310368, 0.79049134],
        [0.65052549, 0.66880893, 0.2737509 , 0.65727091, 0.6740136 ],
        [0.83128131, 0.53553652, 0.46245451, 0.26061569, 0.80669317]]])

In [96]:
# Method 2
method_2 = np.random.randn(2,3,5)
print(method_2)

[[[ 0.33824617  0.44874312  1.07625215 -1.65201807  0.06506553]
  [ 0.86291389 -0.12259409 -0.19697698 -0.45108065  0.30405157]
  [-2.5190931   1.21992846 -0.79181571  1.00361081 -0.1907133 ]]

 [[-0.42780956 -1.95742349 -0.23168693  0.55980846  1.38089517]
  [-1.52863736 -1.15056895 -0.5195365   0.97801299 -0.5066386 ]
  [-0.93693479  0.06529176  0.14598692 -0.36653946  0.18140735]]]


In [97]:
# Method 3
method_3 = np.random.randint(100, size=(2,3,5))
print(method_3)

[[[14 43  0 19 20]
  [ 4 44  2 70 33]
  [33 62 45 58 66]]

 [[37  4 25 81 37]
  [44 56 36 71 66]
  [23 59 46 25 42]]]


#### 4. Print *a*.


In [98]:
# your code here
print(a)

[[[0.00698894 0.0723351  0.51694169 0.93115855 0.76534616]
  [0.73529063 0.22790399 0.37438297 0.27864282 0.71474998]
  [0.33332167 0.07054892 0.23785229 0.54560333 0.68991255]]

 [[0.67882238 0.38458908 0.29634586 0.38310368 0.79049134]
  [0.65052549 0.66880893 0.2737509  0.65727091 0.6740136 ]
  [0.83128131 0.53553652 0.46245451 0.26061569 0.80669317]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [99]:
# your code here
b = np.ones((5,2,3),dtype = int)

#### 6. Print *b*.


In [100]:
# your code here
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [101]:
# your code here

# Yes both have the same size:
print(a.size)

print(b.size)

a.size==b.size

30
30


True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [102]:
# your answer here
# It's not possible to add a to b, because they have diferent structures.
np.add(a, b)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [103]:
# your code here
c = np.transpose(b, axes=(1,2,0))
print(np.shape(c))

(2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [104]:
# your code/answer here
d = np.add(a, c)
print(d)

[[[1.00698894 1.0723351  1.51694169 1.93115855 1.76534616]
  [1.73529063 1.22790399 1.37438297 1.27864282 1.71474998]
  [1.33332167 1.07054892 1.23785229 1.54560333 1.68991255]]

 [[1.67882238 1.38458908 1.29634586 1.38310368 1.79049134]
  [1.65052549 1.66880893 1.2737509  1.65727091 1.6740136 ]
  [1.83128131 1.53553652 1.46245451 1.26061569 1.80669317]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [105]:
# your code/answer here
print(a)
print(d)
# The d array as different values from the array a, because we added the values from the array c, to the array a;
# Since all the values from the array c are equal to "1", the values of the array d, will be the same as the vallues in the array a, plus "1".

[[[0.00698894 0.0723351  0.51694169 0.93115855 0.76534616]
  [0.73529063 0.22790399 0.37438297 0.27864282 0.71474998]
  [0.33332167 0.07054892 0.23785229 0.54560333 0.68991255]]

 [[0.67882238 0.38458908 0.29634586 0.38310368 0.79049134]
  [0.65052549 0.66880893 0.2737509  0.65727091 0.6740136 ]
  [0.83128131 0.53553652 0.46245451 0.26061569 0.80669317]]]
[[[1.00698894 1.0723351  1.51694169 1.93115855 1.76534616]
  [1.73529063 1.22790399 1.37438297 1.27864282 1.71474998]
  [1.33332167 1.07054892 1.23785229 1.54560333 1.68991255]]

 [[1.67882238 1.38458908 1.29634586 1.38310368 1.79049134]
  [1.65052549 1.66880893 1.2737509  1.65727091 1.6740136 ]
  [1.83128131 1.53553652 1.46245451 1.26061569 1.80669317]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [106]:
# your code here
e = np.multiply(a, c)
print(e)

[[[0.00698894 0.0723351  0.51694169 0.93115855 0.76534616]
  [0.73529063 0.22790399 0.37438297 0.27864282 0.71474998]
  [0.33332167 0.07054892 0.23785229 0.54560333 0.68991255]]

 [[0.67882238 0.38458908 0.29634586 0.38310368 0.79049134]
  [0.65052549 0.66880893 0.2737509  0.65727091 0.6740136 ]
  [0.83128131 0.53553652 0.46245451 0.26061569 0.80669317]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [119]:
# your code/answer here
e == a
# Yes, both e and a are equal arrays, because the array e is the multiplication of 2 diferent arrays, but because we multiplied all the values by "1", the resulting values will be the same as the ones in the array a.

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [126]:
# your code here
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [127]:
# your code here
f = np.empty((2, 3, 5))
print(f)

[[[1.02491594 1.67835496 1.12092277 1.97794805 1.96047507]
  [1.45516114 1.93627947 1.6578976  1.63233811 1.13564964]
  [1.73077367 1.48849511 1.6461418  1.18981091 1.08263984]]

 [[1.32965364 1.36778308 1.01788468 1.99212425 1.10283942]
  [1.02828301 1.08430634 1.52573107 1.20680023 1.10120868]
  [1.09000378 1.40244699 1.80632115 1.73775253 1.5891521 ]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [150]:
# your code here

values = []
    
for element in d.flatten():
    
        if element > d_min and element < d_mean:
            values.append(25)
            
        elif element > d_mean and element < d_max:
            values.append(75)
            
        elif element == d_mean:
            values.append(50)
            
        elif d_min:
            values.append(0)
            
        elif d_max:
            values.append(100)

f = np.array(values)
    
f = f.reshape(2,3,5)

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [149]:
# your code here
print(d)
print(f)

[[[1.00698894 1.0723351  1.51694169 1.93115855 1.76534616]
  [1.73529063 1.22790399 1.37438297 1.27864282 1.71474998]
  [1.33332167 1.07054892 1.23785229 1.54560333 1.68991255]]

 [[1.67882238 1.38458908 1.29634586 1.38310368 1.79049134]
  [1.65052549 1.66880893 1.2737509  1.65727091 1.6740136 ]
  [1.83128131 1.53553652 1.46245451 1.26061569 1.80669317]]]
[[[ 0 25 75  0 75]
  [75 25 25 25 75]
  [25 25 25 75 75]]

 [[75 25 25 25 75]
  [75 75 25 75 75]
  [75 75 25 25 75]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here