# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.__version__)

1.18.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a = np.random.randn(2,3,5)


In [4]:
# Method 2
a = np.random.randint(10,90,(2,3,5)) 


In [5]:
# Method 3
a = np.random.random((2,3,5))

#### 4. Print *a*.


In [6]:
# your code here
print(a)

[[[0.44727641 0.2484823  0.93143945 0.6105793  0.6625508 ]
  [0.88122769 0.13103738 0.14422504 0.86558866 0.22669664]
  [0.74626099 0.14648207 0.79324912 0.79800421 0.27108516]]

 [[0.46830065 0.17005071 0.04174133 0.72976431 0.69191574]
  [0.21204137 0.21851436 0.0653824  0.28895543 0.51940472]
  [0.85683978 0.34840372 0.97151742 0.10679813 0.81672387]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here
b = np.ones((5, 2, 3))

#### 6. Print *b*.


In [8]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here
aSize = a.size
bSize = b.size
if aSize == bSize:
    print("a and b are equal.")
elif aSize > bSize:
    print("They don't have the same size. a is bigger than b")
else:
    print("They don't have the same size. b is bigger than a")
    

a and b are equal.


#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
''' 
a and b can't be added because they have different shapes
'''
print(np.add(a,b))

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here
c = b.reshape(2,3,5)
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# your code/it works because the shapes are the same after using the rshape function
d = sum(np.add(a,c))
print(d)

[[2.91557707 2.41853301 2.97318078 3.34034361 3.35446654]
 [3.09326906 2.34955174 2.20960745 3.15454409 2.74610136]
 [3.60310077 2.49488579 3.76476654 2.90480234 3.08780904]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# your code/answer here
print(a)
print(d)

[[[0.44727641 0.2484823  0.93143945 0.6105793  0.6625508 ]
  [0.88122769 0.13103738 0.14422504 0.86558866 0.22669664]
  [0.74626099 0.14648207 0.79324912 0.79800421 0.27108516]]

 [[0.46830065 0.17005071 0.04174133 0.72976431 0.69191574]
  [0.21204137 0.21851436 0.0653824  0.28895543 0.51940472]
  [0.85683978 0.34840372 0.97151742 0.10679813 0.81672387]]]
[[2.91557707 2.41853301 2.97318078 3.34034361 3.35446654]
 [3.09326906 2.34955174 2.20960745 3.15454409 2.74610136]
 [3.60310077 2.49488579 3.76476654 2.90480234 3.08780904]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
# your code here
e = a * c

#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
# your code/answer here
eSize = e.size
if aSize == eSize:
    print("a and e are equal.")
elif aSize > eSize:
    print("They don't have the same size. a is bigger than e")
else:
    print("They don't have the same size. e is bigger than a")

a and e are equal.


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [92]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [93]:
# your code here
f = np.empty([2, 3, 5])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [94]:
# your code here
f = []
for i in d:
    for x in i:
        if x > d_min and x < d_mean:
            f += [25]
        if x > d_mean and x < d_max:
            f += [75]
        if x == d_mean:
            f += [50]
        if x == d_min:
            f += [0]
        if x == d_max:
            f += [100]
f = np.reshape(f, (3,5))

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [95]:
# your code here
print(d)
print(f)


[[2.91557707 2.41853301 2.97318078 3.34034361 3.35446654]
 [3.09326906 2.34955174 2.20960745 3.15454409 2.74610136]
 [3.60310077 2.49488579 3.76476654 2.90480234 3.08780904]]
[[ 25  25  75  75  75]
 [ 75  25   0  75  25]
 [ 75  25 100  25  75]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [96]:
# your code here
f = []
for i in d:
    for x in i:
        if x > d_min and x < d_mean:
            f += ['A']
        if x > d_mean and x < d_max:
            f += ['B']
        if x == d_mean:
            f += ['C']
        if x == d_min:
            f += ['D']
        if x == d_max:
            f += ['E']
f = np.reshape(f, (3,5))

In [91]:
print(d)
print(f)

[[2.91557707 2.41853301 2.97318078 3.34034361 3.35446654]
 [3.09326906 2.34955174 2.20960745 3.15454409 2.74610136]
 [3.60310077 2.49488579 3.76476654 2.90480234 3.08780904]]
[['A' 'A' 'B' 'B' 'B']
 ['B' 'A' 'D' 'B' 'A']
 ['B' 'A' 'E' 'A' 'B']]
