# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.version.version)

1.17.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [5]:
# Method 1
a = np.random.random((2,3,5))


[[[0.3773928  0.36667257 0.00338957 0.00562677 0.95095218]
  [0.74109938 0.88272879 0.82361983 0.69203657 0.86341494]
  [0.24674389 0.73665518 0.13006202 0.12654556 0.28498218]]

 [[0.53875855 0.6833094  0.2122717  0.7579098  0.02483124]
  [0.93946855 0.44792506 0.33043066 0.24195525 0.36418057]
  [0.55453374 0.41713087 0.66536653 0.87867372 0.95253563]]]


In [8]:
# Method 2
a = np.indices((3,5))


[[[0 0 0 0 0]
  [1 1 1 1 1]
  [2 2 2 2 2]]

 [[0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]]]


In [9]:
# Method 3
a = np.random.rand(2,3,5)

[[[0.49707    0.75550404 0.97476209 0.13045857 0.64718978]
  [0.01243768 0.79550068 0.12766628 0.34159354 0.87947844]
  [0.89192835 0.77433309 0.23483557 0.7987288  0.0729021 ]]

 [[0.11195434 0.06982734 0.65560538 0.25453456 0.48509308]
  [0.53098284 0.11909911 0.16830546 0.25143795 0.95983286]
  [0.4781756  0.13507294 0.1360578  0.78506219 0.01140253]]]


#### 4. Print *a*.


In [10]:
print(a)

[[[0.49707    0.75550404 0.97476209 0.13045857 0.64718978]
  [0.01243768 0.79550068 0.12766628 0.34159354 0.87947844]
  [0.89192835 0.77433309 0.23483557 0.7987288  0.0729021 ]]

 [[0.11195434 0.06982734 0.65560538 0.25453456 0.48509308]
  [0.53098284 0.11909911 0.16830546 0.25143795 0.95983286]
  [0.4781756  0.13507294 0.1360578  0.78506219 0.01140253]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [24]:
# your code here

b= np.ones((5,2,3),dtype = int)


#### 6. Print *b*.


In [25]:
# your code here
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [15]:
# your code here

a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [28]:
# your code here

c = np.transpose(b, (1,2,0))
print(c)
print(np.shape(c))

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]
(2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [29]:
# your code/answer here

d = a + c

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [31]:
# your code/answer here

print(a)

[[[0.49707    0.75550404 0.97476209 0.13045857 0.64718978]
  [0.01243768 0.79550068 0.12766628 0.34159354 0.87947844]
  [0.89192835 0.77433309 0.23483557 0.7987288  0.0729021 ]]

 [[0.11195434 0.06982734 0.65560538 0.25453456 0.48509308]
  [0.53098284 0.11909911 0.16830546 0.25143795 0.95983286]
  [0.4781756  0.13507294 0.1360578  0.78506219 0.01140253]]]


In [32]:
print(d)

[[[1.49707    1.75550404 1.97476209 1.13045857 1.64718978]
  [1.01243768 1.79550068 1.12766628 1.34159354 1.87947844]
  [1.89192835 1.77433309 1.23483557 1.7987288  1.0729021 ]]

 [[1.11195434 1.06982734 1.65560538 1.25453456 1.48509308]
  [1.53098284 1.11909911 1.16830546 1.25143795 1.95983286]
  [1.4781756  1.13507294 1.1360578  1.78506219 1.01140253]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [35]:
# your code here

e = a *c
print(e)

[[[0.49707    0.75550404 0.97476209 0.13045857 0.64718978]
  [0.01243768 0.79550068 0.12766628 0.34159354 0.87947844]
  [0.89192835 0.77433309 0.23483557 0.7987288  0.0729021 ]]

 [[0.11195434 0.06982734 0.65560538 0.25453456 0.48509308]
  [0.53098284 0.11909911 0.16830546 0.25143795 0.95983286]
  [0.4781756  0.13507294 0.1360578  0.78506219 0.01140253]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [ ]:
#something multiplied by 1 equals that something

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [38]:
# your code here
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [39]:
# your code here
f = np.empty((2,3,5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [41]:
# For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
f[(d_min < d) & (d < d_mean)] = 25

#If a value in d is larger than d_mean but smaller than d_max, assign 75 
f[(d_mean < d) & (d < d_max)] = 75

#If a value equals to d_mean, assign 50
f[d_mean == d] = 50
   
#Assign 0 to the corresponding value(s) in f for d_min in d.
f[d_min == d] = 0
   
#Assign 100 to the corresponding value(s) in f for d_max in d
f[d_max == d] = 100

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [43]:
print(d)


[[[1.49707    1.75550404 1.97476209 1.13045857 1.64718978]
  [1.01243768 1.79550068 1.12766628 1.34159354 1.87947844]
  [1.89192835 1.77433309 1.23483557 1.7987288  1.0729021 ]]

 [[1.11195434 1.06982734 1.65560538 1.25453456 1.48509308]
  [1.53098284 1.11909911 1.16830546 1.25143795 1.95983286]
  [1.4781756  1.13507294 1.1360578  1.78506219 1.01140253]]]


In [44]:
print(f)

[[[ 75.  75. 100.  25.  75.]
  [ 25.  75.  25.  25.  75.]
  [ 75.  75.  25.  75.  25.]]

 [[ 25.  25.  75.  25.  75.]
  [ 75.  25.  25.  25.  75.]
  [ 75.  25.  25.  75.   0.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [46]:
f = np.empty((2,3,5), dtype = str)

In [47]:
f[(d_min < d) & (d < d_mean)] = "B"

f[(d_mean < d) & (d < d_max)] = "D"

f[d_mean == d] = "C"
   
f[d_min == d] = "A"
   
f[d_max == d] = "E"

In [48]:
print(f)

[[['D' 'D' 'E' 'B' 'D']
  ['B' 'D' 'B' 'B' 'D']
  ['D' 'D' 'B' 'D' 'B']]

 [['B' 'B' 'D' 'B' 'D']
  ['D' 'B' 'B' 'B' 'D']
  ['D' 'B' 'B' 'D' 'A']]]
