# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [3]:
# your code here
np.__version__

'1.20.3'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [5]:
# Method 1
a = np.random.random((2, 3, 5))
a

array([[[0.13333716, 0.0454795 , 0.26055064, 0.43970878, 0.88182987],
        [0.56380918, 0.30990862, 0.49858458, 0.30637083, 0.24416676],
        [0.86806886, 0.44204908, 0.55192152, 0.65197175, 0.50236997]],

       [[0.11700815, 0.50174313, 0.69467344, 0.83755298, 0.31936012],
        [0.61737469, 0.54117363, 0.72611187, 0.67596242, 0.70634376],
        [0.87366588, 0.97440439, 0.59870914, 0.88520666, 0.1267003 ]]])

In [27]:
# Method 2
a = np.random.randint(0,101, size = (2, 3, 5))
a

array([[[70, 89, 93, 96, 58],
        [57, 14, 10, 66, 71],
        [66, 61, 36, 44, 63]],

       [[53, 64, 44, 50, 63],
        [29, 29, 57,  9, 41],
        [12, 29, 31, 17, 19]]])

In [35]:
a

In [90]:
# Method 3
a = np.random.random_sample((2, 3, 5))
a

array([[[0.27743351, 0.96935619, 0.72010743, 0.33349239, 0.33579261],
        [0.94102208, 0.79559129, 0.40367622, 0.96401144, 0.56263113],
        [0.39318631, 0.64903896, 0.91725854, 0.53769038, 0.63163108]],

       [[0.4634324 , 0.2376227 , 0.33164116, 0.91031769, 0.3177504 ],
        [0.97441537, 0.76117931, 0.98853046, 0.89104623, 0.86339525],
        [0.94306661, 0.72492628, 0.97006052, 0.77231641, 0.5899268 ]]])

#### 4. Print *a*.


In [91]:
# your code here
a

array([[[0.27743351, 0.96935619, 0.72010743, 0.33349239, 0.33579261],
        [0.94102208, 0.79559129, 0.40367622, 0.96401144, 0.56263113],
        [0.39318631, 0.64903896, 0.91725854, 0.53769038, 0.63163108]],

       [[0.4634324 , 0.2376227 , 0.33164116, 0.91031769, 0.3177504 ],
        [0.97441537, 0.76117931, 0.98853046, 0.89104623, 0.86339525],
        [0.94306661, 0.72492628, 0.97006052, 0.77231641, 0.5899268 ]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [92]:
# your code here
b = np.ones((5, 2, 3))

#### 6. Print *b*.


In [93]:
# your code here
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [113]:
# your code here
a.shape == b.shape

False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [114]:
# your answer here
# Values from arrays of different shapes can not be added

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [115]:
# your code here
c = np.transpose(b, (1, 2, 0)).shape
c = b.reshape((2, 3, 5))
c.shape

(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [116]:
# your code/answer here
d = a + c
d
# Now it works because the two arrays have the same shape

array([[[1.27743351, 1.96935619, 1.72010743, 1.33349239, 1.33579261],
        [1.94102208, 1.79559129, 1.40367622, 1.96401144, 1.56263113],
        [1.39318631, 1.64903896, 1.91725854, 1.53769038, 1.63163108]],

       [[1.4634324 , 1.2376227 , 1.33164116, 1.91031769, 1.3177504 ],
        [1.97441537, 1.76117931, 1.98853046, 1.89104623, 1.86339525],
        [1.94306661, 1.72492628, 1.97006052, 1.77231641, 1.5899268 ]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [117]:
# your code/answer here
print('Array a:\n', a)
print('\n')
print('Array d:\n', d)

# In the array d each value is equal the value of the corresponding value in array a plus 1

Array a:
 [[[0.27743351 0.96935619 0.72010743 0.33349239 0.33579261]
  [0.94102208 0.79559129 0.40367622 0.96401144 0.56263113]
  [0.39318631 0.64903896 0.91725854 0.53769038 0.63163108]]

 [[0.4634324  0.2376227  0.33164116 0.91031769 0.3177504 ]
  [0.97441537 0.76117931 0.98853046 0.89104623 0.86339525]
  [0.94306661 0.72492628 0.97006052 0.77231641 0.5899268 ]]]


Array d:
 [[[1.27743351 1.96935619 1.72010743 1.33349239 1.33579261]
  [1.94102208 1.79559129 1.40367622 1.96401144 1.56263113]
  [1.39318631 1.64903896 1.91725854 1.53769038 1.63163108]]

 [[1.4634324  1.2376227  1.33164116 1.91031769 1.3177504 ]
  [1.97441537 1.76117931 1.98853046 1.89104623 1.86339525]
  [1.94306661 1.72492628 1.97006052 1.77231641 1.5899268 ]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [118]:
# your code here
e = a * c
e

array([[[0.27743351, 0.96935619, 0.72010743, 0.33349239, 0.33579261],
        [0.94102208, 0.79559129, 0.40367622, 0.96401144, 0.56263113],
        [0.39318631, 0.64903896, 0.91725854, 0.53769038, 0.63163108]],

       [[0.4634324 , 0.2376227 , 0.33164116, 0.91031769, 0.3177504 ],
        [0.97441537, 0.76117931, 0.98853046, 0.89104623, 0.86339525],
        [0.94306661, 0.72492628, 0.97006052, 0.77231641, 0.5899268 ]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [119]:
# your code/answer here
e == a
# Each value of a is equale the corresponding value of e 
# because in the array c all the values are equale to 1

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [120]:
# your code here
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

print('The maximum is ', d_max)
print('The minimum is ', d_min)
print('The mean is ', d_mean)

The maximum is  1.9885304554209822
The minimum is  1.2376227047026072
The mean is  1.6723849049686557


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [121]:
# your code here
f = np.empty((2, 3, 5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [122]:
d.shape

(2, 3, 5)

In [132]:
# your code here
f_values = []

for subgroup in d:
    for row in subgroup:
        for value in row:
            if value > d_min and value < d_mean:
                value = 25
                f_values.append(value)
            elif value > d_mean and value < d_max:
                value = 75
                f_values.append(value)
            elif value == d_mean:
                value = 50
                f_values.append(value)
            elif value == d_min:
                value = 0
                f_values.append(value)
            elif value == d_max:
                value = 100
                f_values.append(value)

f = np.asarray(f_values)
f = f.reshape(2, 3, 5)
f

array([[[ 25,  75,  75,  25,  25],
        [ 75,  75,  25,  75,  25],
        [ 25,  25,  75,  25,  25]],

       [[ 25,   0,  25,  75,  25],
        [ 75,  75, 100,  75,  75],
        [ 75,  75,  75,  75,  25]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [133]:
# your code here
print('Array d:\n', d)
print('\n')
print('Array f:\n', f)

Array d:
 [[[1.27743351 1.96935619 1.72010743 1.33349239 1.33579261]
  [1.94102208 1.79559129 1.40367622 1.96401144 1.56263113]
  [1.39318631 1.64903896 1.91725854 1.53769038 1.63163108]]

 [[1.4634324  1.2376227  1.33164116 1.91031769 1.3177504 ]
  [1.97441537 1.76117931 1.98853046 1.89104623 1.86339525]
  [1.94306661 1.72492628 1.97006052 1.77231641 1.5899268 ]]]


Array f:
 [[[ 25  75  75  25  25]
  [ 75  75  25  75  25]
  [ 25  25  75  25  25]]

 [[ 25   0  25  75  25]
  [ 75  75 100  75  75]
  [ 75  75  75  75  25]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [136]:
# your code here
characters = []

for subgroup in f:
    for row in subgroup:
        for value in row:
            if value == 0:
                value = 'A'
                characters.append(value)
            elif value == 25:
                value = 'B'
                characters.append(value)
            elif value == 50:
                value = 'C'
                characters.append(value)
            elif value == 75:
                value = 'D'
                characters.append(value)
            elif value == 100:
                value = 'E'
                characters.append(value)

g = np.asarray(characters)
g = g.reshape(2, 3, 5)
g

array([[['B', 'D', 'D', 'B', 'B'],
        ['D', 'D', 'B', 'D', 'B'],
        ['B', 'B', 'D', 'B', 'B']],

       [['B', 'A', 'B', 'D', 'B'],
        ['D', 'D', 'E', 'D', 'D'],
        ['D', 'D', 'D', 'D', 'B']]], dtype='<U1')