# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [22]:
import numpy as np

#### 2. Print your NumPy version.

In [23]:
print(np.version.version)

1.16.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [30]:
# Method 1
a = np.random.random((2,3,5))
print(a)

[[[0.76575561 0.3205204  0.16884625 0.41693444 0.43873688]
  [0.73009337 0.65928463 0.38346699 0.92703658 0.22131822]
  [0.10225299 0.24709187 0.33409601 0.72974554 0.73839167]]

 [[0.89936559 0.9939645  0.68791734 0.38773388 0.20000809]
  [0.37704431 0.45130349 0.32440519 0.82969594 0.16698392]
  [0.33632165 0.94271423 0.22181148 0.42005196 0.13276239]]]


In [31]:
# Method 2
a2 = np.random.rand(2,3,5)
print(a2)

[[[0.59910923 0.97590282 0.31161478 0.59099093 0.41524218]
  [0.98394326 0.63819683 0.16436667 0.36224865 0.16864103]
  [0.49569795 0.25716419 0.72424591 0.14823886 0.55597868]]

 [[0.72300611 0.53273095 0.54049804 0.27071401 0.10924391]
  [0.825976   0.41449574 0.9192918  0.67931636 0.36431475]
  [0.25139864 0.70643321 0.43408434 0.94383026 0.26810328]]]


In [32]:
# Method 3
a3 = np.random.randint(0,10, size= (2,3,5))
print(a3)

[[[5 1 1 7 4]
  [5 5 3 3 2]
  [0 8 6 5 5]]

 [[9 3 3 9 4]
  [4 2 1 9 7]
  [1 7 1 9 1]]]


#### 4. Print *a*.


In [7]:
print(a)

[[[0.54599716 0.32083998 0.10653635 0.58955929 0.1750449 ]
  [0.8236174  0.85824752 0.56039312 0.18846656 0.60811738]
  [0.67981215 0.29722189 0.9627614  0.72878882 0.7565258 ]]

 [[0.10436574 0.38514364 0.28362538 0.48022071 0.97581422]
  [0.82724659 0.44541649 0.6895224  0.43374465 0.61540728]
  [0.10465446 0.62572036 0.29908556 0.14299704 0.89650996]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [8]:
b = np.ones(shape=(5,3,2) ,dtype=int)

#### 6. Print *b*.


In [9]:
print(b)

[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [38]:
print("a size: ", a.size)
print("b size: ", b.size)

check_equal_size = a.size - b.size

print(check_equal_size)

#a and b both have 30 elements in the array so a.size-b.size should be 0

a size:  30
b size:  30
0


#### 8. Are you able to add *a* and *b*? Why or why not?


In [39]:
# I am not able to add a and b because they are not exactly the same size. a and b are arrays of different dimmensions.

sum_a_b = np.add(a,b)

print(sum_a_b)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,3,2) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [12]:
c = np.transpose(b,)
print(c)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [13]:
d = np.add(a,c)
print(d)

# Adding a and c works because they are arrays of the same size.

[[[1.54599716 1.32083998 1.10653635 1.58955929 1.1750449 ]
  [1.8236174  1.85824752 1.56039312 1.18846656 1.60811738]
  [1.67981215 1.29722189 1.9627614  1.72878882 1.7565258 ]]

 [[1.10436574 1.38514364 1.28362538 1.48022071 1.97581422]
  [1.82724659 1.44541649 1.6895224  1.43374465 1.61540728]
  [1.10465446 1.62572036 1.29908556 1.14299704 1.89650996]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [16]:
print(a)
print(d)

# d is the same array a just that each value has +1.

[[[0.54599716 0.32083998 0.10653635 0.58955929 0.1750449 ]
  [0.8236174  0.85824752 0.56039312 0.18846656 0.60811738]
  [0.67981215 0.29722189 0.9627614  0.72878882 0.7565258 ]]

 [[0.10436574 0.38514364 0.28362538 0.48022071 0.97581422]
  [0.82724659 0.44541649 0.6895224  0.43374465 0.61540728]
  [0.10465446 0.62572036 0.29908556 0.14299704 0.89650996]]]
[[[1.54599716 1.32083998 1.10653635 1.58955929 1.1750449 ]
  [1.8236174  1.85824752 1.56039312 1.18846656 1.60811738]
  [1.67981215 1.29722189 1.9627614  1.72878882 1.7565258 ]]

 [[1.10436574 1.38514364 1.28362538 1.48022071 1.97581422]
  [1.82724659 1.44541649 1.6895224  1.43374465 1.61540728]
  [1.10465446 1.62572036 1.29908556 1.14299704 1.89650996]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [15]:
e = np.multiply(a,c)
print(e)

[[[0.54599716 0.32083998 0.10653635 0.58955929 0.1750449 ]
  [0.8236174  0.85824752 0.56039312 0.18846656 0.60811738]
  [0.67981215 0.29722189 0.9627614  0.72878882 0.7565258 ]]

 [[0.10436574 0.38514364 0.28362538 0.48022071 0.97581422]
  [0.82724659 0.44541649 0.6895224  0.43374465 0.61540728]
  [0.10465446 0.62572036 0.29908556 0.14299704 0.89650996]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [17]:
# e equals to a because because I am multiplying each value of array a by each value of array c which is only composed of 1's. Thus, meaning that e equals to a.
print(e)
print(a)

[[[0.54599716 0.32083998 0.10653635 0.58955929 0.1750449 ]
  [0.8236174  0.85824752 0.56039312 0.18846656 0.60811738]
  [0.67981215 0.29722189 0.9627614  0.72878882 0.7565258 ]]

 [[0.10436574 0.38514364 0.28362538 0.48022071 0.97581422]
  [0.82724659 0.44541649 0.6895224  0.43374465 0.61540728]
  [0.10465446 0.62572036 0.29908556 0.14299704 0.89650996]]]
[[[0.54599716 0.32083998 0.10653635 0.58955929 0.1750449 ]
  [0.8236174  0.85824752 0.56039312 0.18846656 0.60811738]
  [0.67981215 0.29722189 0.9627614  0.72878882 0.7565258 ]]

 [[0.10436574 0.38514364 0.28362538 0.48022071 0.97581422]
  [0.82724659 0.44541649 0.6895224  0.43374465 0.61540728]
  [0.10465446 0.62572036 0.29908556 0.14299704 0.89650996]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [25]:
d_max = np.amax(d)
print("Max: ", d_max)

d_min = np.amin(d)
print("Min: ", d_min)

d_mean = np.mean(d)
print("Mean: ", d_mean)

Max:  1.9758142205438238
Min:  1.1043657447277835
Mean:  1.5170468059029332


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.

In [ ]:
f = np.empty((2,3,5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [27]:
values_f= [[[25 if d_min<value<d_mean else 75 if d_mean<value< d_max else 0 if value == d_min else 50 if value == d_mean else 100 for value in in_list] for in_list in out_list] for out_list in d]

f= np.array(values_f)

print(f)

[[[ 75  25  25  75  25]
  [ 75  75  75  25  75]
  [ 75  25  75  75  75]]

 [[  0  25  25  25 100]
  [ 75  25  75  25  75]
  [ 25  75  25  25  75]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [28]:
print(d)
print(f)

[[[1.54599716 1.32083998 1.10653635 1.58955929 1.1750449 ]
  [1.8236174  1.85824752 1.56039312 1.18846656 1.60811738]
  [1.67981215 1.29722189 1.9627614  1.72878882 1.7565258 ]]

 [[1.10436574 1.38514364 1.28362538 1.48022071 1.97581422]
  [1.82724659 1.44541649 1.6895224  1.43374465 1.61540728]
  [1.10465446 1.62572036 1.29908556 1.14299704 1.89650996]]]
[[[ 75  25  25  75  25]
  [ 75  75  75  25  75]
  [ 75  25  75  75  75]]

 [[  0  25  25  25 100]
  [ 75  25  75  25  75]
  [ 25  75  25  25  75]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [29]:
f2_values = [[["B" if d_min<value<d_mean else "D" if d_mean<value< d_max else "A" if value == d_min else "C" if value == d_mean else "E" for value in in_list] for in_list in out_list] for out_list in d]

f2 = np.array(f2_values)
print(f2)


[[['D' 'B' 'B' 'D' 'B']
  ['D' 'D' 'D' 'B' 'D']
  ['D' 'B' 'D' 'D' 'D']]

 [['A' 'B' 'B' 'B' 'E']
  ['D' 'B' 'D' 'B' 'D']
  ['B' 'D' 'B' 'B' 'D']]]
