# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [2]:
# your code here
import numpy as np 

#### 2. Print your NumPy version.

In [3]:
# your code here

print(np.__version__)

1.21.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [6]:
# Method 1
a = np.random.random(size=(2,3,5))
a

array([[[0.28116064, 0.81020849, 0.6678058 , 0.4901688 , 0.88109909],
        [0.73521561, 0.44114682, 0.9116241 , 0.05914448, 0.90301387],
        [0.47387656, 0.36161979, 0.35716125, 0.04269473, 0.583833  ]],

       [[0.0609455 , 0.0121095 , 0.98038992, 0.28153741, 0.900587  ],
        [0.16169308, 0.97387413, 0.95079972, 0.88625619, 0.27560733],
        [0.95884168, 0.5912912 , 0.59253316, 0.10375391, 0.96947028]]])

In [15]:
# Method 2
a1 = np.random.randint(0,200,size=(2,3,5))
a1

array([[[ 58,  25, 171,  38, 133],
        [  3,  68,  90, 102,  45],
        [102,  51,  20, 190, 151]],

       [[  6,  24,  35, 129,   9],
        [131, 103, 148,  74, 181],
        [ 65,  28,  63,  59, 117]]])

In [16]:
# Method 3
a2 = np.random.rand(2,3,5)
a2

array([[[0.50131634, 0.75412477, 0.18480161, 0.52852557, 0.3942796 ],
        [0.5325785 , 0.43566257, 0.24750063, 0.73306582, 0.27864661],
        [0.0623514 , 0.3695248 , 0.35855078, 0.02741781, 0.16715968]],

       [[0.77165695, 0.55186425, 0.84710737, 0.81801   , 0.24834856],
        [0.80773455, 0.90142555, 0.58040044, 0.31253842, 0.84741786],
        [0.608761  , 0.64116684, 0.80275281, 0.66726996, 0.42367079]]])

#### 4. Print *a*.


In [9]:
# your code here
print(a)

[[[0.28116064 0.81020849 0.6678058  0.4901688  0.88109909]
  [0.73521561 0.44114682 0.9116241  0.05914448 0.90301387]
  [0.47387656 0.36161979 0.35716125 0.04269473 0.583833  ]]

 [[0.0609455  0.0121095  0.98038992 0.28153741 0.900587  ]
  [0.16169308 0.97387413 0.95079972 0.88625619 0.27560733]
  [0.95884168 0.5912912  0.59253316 0.10375391 0.96947028]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [17]:
# your code here
b = np.ones(shape=(5,2,3), dtype=int)
b

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

#### 6. Print *b*.


In [18]:
# your code here
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [22]:
# your code here
a.shape == b.shape

False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [ ]:
# your answer here

# With the original shape a and b have now, it is not possible to add one to the other. 
# It can be possible if we reshape one of them, so they match the shape.

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [23]:
# your code here
c = b.reshape(2,3,5)
c


array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [24]:
# your code/answer here

d = a + c
d

# It works now because they have the same shape : 2 subgroups, each one with 3 rows and 5 columns. 

array([[[1.28116064, 1.81020849, 1.6678058 , 1.4901688 , 1.88109909],
        [1.73521561, 1.44114682, 1.9116241 , 1.05914448, 1.90301387],
        [1.47387656, 1.36161979, 1.35716125, 1.04269473, 1.583833  ]],

       [[1.0609455 , 1.0121095 , 1.98038992, 1.28153741, 1.900587  ],
        [1.16169308, 1.97387413, 1.95079972, 1.88625619, 1.27560733],
        [1.95884168, 1.5912912 , 1.59253316, 1.10375391, 1.96947028]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [25]:
# your code/answer here
print(a)
print(d)

# d is exactly the previous array, but with its values + 1 : what we did on the previous cell

[[[0.28116064 0.81020849 0.6678058  0.4901688  0.88109909]
  [0.73521561 0.44114682 0.9116241  0.05914448 0.90301387]
  [0.47387656 0.36161979 0.35716125 0.04269473 0.583833  ]]

 [[0.0609455  0.0121095  0.98038992 0.28153741 0.900587  ]
  [0.16169308 0.97387413 0.95079972 0.88625619 0.27560733]
  [0.95884168 0.5912912  0.59253316 0.10375391 0.96947028]]]
[[[1.28116064 1.81020849 1.6678058  1.4901688  1.88109909]
  [1.73521561 1.44114682 1.9116241  1.05914448 1.90301387]
  [1.47387656 1.36161979 1.35716125 1.04269473 1.583833  ]]

 [[1.0609455  1.0121095  1.98038992 1.28153741 1.900587  ]
  [1.16169308 1.97387413 1.95079972 1.88625619 1.27560733]
  [1.95884168 1.5912912  1.59253316 1.10375391 1.96947028]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [27]:
# your code here
e = a * c
e

array([[[0.28116064, 0.81020849, 0.6678058 , 0.4901688 , 0.88109909],
        [0.73521561, 0.44114682, 0.9116241 , 0.05914448, 0.90301387],
        [0.47387656, 0.36161979, 0.35716125, 0.04269473, 0.583833  ]],

       [[0.0609455 , 0.0121095 , 0.98038992, 0.28153741, 0.900587  ],
        [0.16169308, 0.97387413, 0.95079972, 0.88625619, 0.27560733],
        [0.95884168, 0.5912912 , 0.59253316, 0.10375391, 0.96947028]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [28]:
# your code/answer here

a == e

#  c is an array of 1 values. Multiplying by c will generate the same result as before, the original a array. 

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [29]:
# your code here

d_max = d.max()
print(d_max)

d_min = d.min()
print(d_min)

d_mean = d.mean()
print(d_mean)

1.9803899175575728
1.0121094953782057
1.5566487675622727


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [30]:
# your code here

f = np.empty(shape=(2,3,5))
f

array([[[0.28116064, 0.81020849, 0.6678058 , 0.4901688 , 0.88109909],
        [0.73521561, 0.44114682, 0.9116241 , 0.05914448, 0.90301387],
        [0.47387656, 0.36161979, 0.35716125, 0.04269473, 0.583833  ]],

       [[0.0609455 , 0.0121095 , 0.98038992, 0.28153741, 0.900587  ],
        [0.16169308, 0.97387413, 0.95079972, 0.88625619, 0.27560733],
        [0.95884168, 0.5912912 , 0.59253316, 0.10375391, 0.96947028]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [31]:
# your code here
f[(d > d_min) & (d < d_mean)] = 25
f[(d > d_mean) & (d < d_max)] = 75
f[(d == d.mean)] = 50
f[(d == d.min)] = 0
f[(d == d.max)] = 100
f

array([[[2.50000000e+01, 7.50000000e+01, 7.50000000e+01, 2.50000000e+01,
         7.50000000e+01],
        [7.50000000e+01, 2.50000000e+01, 7.50000000e+01, 2.50000000e+01,
         7.50000000e+01],
        [2.50000000e+01, 2.50000000e+01, 2.50000000e+01, 2.50000000e+01,
         7.50000000e+01]],

       [[2.50000000e+01, 1.21094954e-02, 9.80389918e-01, 2.50000000e+01,
         7.50000000e+01],
        [2.50000000e+01, 7.50000000e+01, 7.50000000e+01, 7.50000000e+01,
         2.50000000e+01],
        [7.50000000e+01, 7.50000000e+01, 7.50000000e+01, 2.50000000e+01,
         7.50000000e+01]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [32]:
# your code here
print(d)
print(f)

[[[1.28116064 1.81020849 1.6678058  1.4901688  1.88109909]
  [1.73521561 1.44114682 1.9116241  1.05914448 1.90301387]
  [1.47387656 1.36161979 1.35716125 1.04269473 1.583833  ]]

 [[1.0609455  1.0121095  1.98038992 1.28153741 1.900587  ]
  [1.16169308 1.97387413 1.95079972 1.88625619 1.27560733]
  [1.95884168 1.5912912  1.59253316 1.10375391 1.96947028]]]
[[[2.50000000e+01 7.50000000e+01 7.50000000e+01 2.50000000e+01
   7.50000000e+01]
  [7.50000000e+01 2.50000000e+01 7.50000000e+01 2.50000000e+01
   7.50000000e+01]
  [2.50000000e+01 2.50000000e+01 2.50000000e+01 2.50000000e+01
   7.50000000e+01]]

 [[2.50000000e+01 1.21094954e-02 9.80389918e-01 2.50000000e+01
   7.50000000e+01]
  [2.50000000e+01 7.50000000e+01 7.50000000e+01 7.50000000e+01
   2.50000000e+01]
  [7.50000000e+01 7.50000000e+01 7.50000000e+01 2.50000000e+01
   7.50000000e+01]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here