# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.__version__)

1.20.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [10]:
# Method 1
a = np.random.rand(2,3,5)
a


array([[[0.39555884, 0.95840751, 0.58591409, 0.36444279, 0.08114375],
        [0.11173961, 0.37513051, 0.85649971, 0.62982597, 0.26901573],
        [0.70417481, 0.20161879, 0.47898689, 0.23109571, 0.01331951]],

       [[0.35932745, 0.16949066, 0.9964057 , 0.07761077, 0.80365719],
        [0.22581786, 0.26983254, 0.40904567, 0.98890482, 0.87416886],
        [0.33986768, 0.17902766, 0.11467758, 0.93512336, 0.69144426]]])

In [29]:
# Method 2
a = np.random.randn(2,3,5)
a

array([[[ 1.24518465,  0.45001826,  1.04950493,  0.18947496,
         -0.94240075],
        [ 0.28236077,  0.1913781 ,  1.13784614,  0.13103784,
         -1.15226044],
        [ 1.61361882,  0.38134403,  0.39802539,  1.46037317,
          0.76595166]],

       [[-0.93810863, -0.14517985, -0.08045485,  0.84722545,
          0.5318008 ],
        [ 0.57916192,  0.75619981,  0.27648913, -0.2094096 ,
          1.05212071],
        [-0.87798466,  0.95900059,  1.06204356,  0.21317157,
         -1.35805181]]])

In [36]:
# Method 3
a=np.random.random(size = (2,3,5))


#### 4. Print *a*.


In [37]:
# your code here
print(a)

[[[0.52316372 0.0361468  0.96748181 0.35373965 0.08122286]
  [0.67106182 0.35551114 0.99544146 0.12850458 0.10951925]
  [0.79153253 0.78672675 0.28080216 0.43876727 0.33390863]]

 [[0.64974203 0.14259007 0.164385   0.26596103 0.22918095]
  [0.48574131 0.71760527 0.27312238 0.49236729 0.5032785 ]
  [0.10169246 0.04756282 0.55047603 0.23395907 0.47507108]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [12]:
# your code here
b = np.ones((5,2,3), dtype = int)

#### 6. Print *b*.


In [14]:
# your code here
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [41]:
# your code here
#
print(a.size)
b.size

if a.size == b.size:
    print('a and b have de same size')
else:
    print('a and b have different sizes')

30
a and b have de same size


#### 8. Are you able to add *a* and *b*? Why or why not?


In [19]:
# your answer here
a + b
# No, because a and b have different shapes

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [42]:
# your code here
c = b.reshape(2,3,5)


c.shape

(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [43]:
# your code/answer here
d = a + c
d

# It works because they have the same shape now

array([[[1.52316372, 1.0361468 , 1.96748181, 1.35373965, 1.08122286],
        [1.67106182, 1.35551114, 1.99544146, 1.12850458, 1.10951925],
        [1.79153253, 1.78672675, 1.28080216, 1.43876727, 1.33390863]],

       [[1.64974203, 1.14259007, 1.164385  , 1.26596103, 1.22918095],
        [1.48574131, 1.71760527, 1.27312238, 1.49236729, 1.5032785 ],
        [1.10169246, 1.04756282, 1.55047603, 1.23395907, 1.47507108]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [45]:
# your code/answer here
print(a)
print('\n')
print(d)

[[[0.52316372 0.0361468  0.96748181 0.35373965 0.08122286]
  [0.67106182 0.35551114 0.99544146 0.12850458 0.10951925]
  [0.79153253 0.78672675 0.28080216 0.43876727 0.33390863]]

 [[0.64974203 0.14259007 0.164385   0.26596103 0.22918095]
  [0.48574131 0.71760527 0.27312238 0.49236729 0.5032785 ]
  [0.10169246 0.04756282 0.55047603 0.23395907 0.47507108]]]


[[[1.52316372 1.0361468  1.96748181 1.35373965 1.08122286]
  [1.67106182 1.35551114 1.99544146 1.12850458 1.10951925]
  [1.79153253 1.78672675 1.28080216 1.43876727 1.33390863]]

 [[1.64974203 1.14259007 1.164385   1.26596103 1.22918095]
  [1.48574131 1.71760527 1.27312238 1.49236729 1.5032785 ]
  [1.10169246 1.04756282 1.55047603 1.23395907 1.47507108]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [46]:
# your code here
e = a * c
e

array([[[0.52316372, 0.0361468 , 0.96748181, 0.35373965, 0.08122286],
        [0.67106182, 0.35551114, 0.99544146, 0.12850458, 0.10951925],
        [0.79153253, 0.78672675, 0.28080216, 0.43876727, 0.33390863]],

       [[0.64974203, 0.14259007, 0.164385  , 0.26596103, 0.22918095],
        [0.48574131, 0.71760527, 0.27312238, 0.49236729, 0.5032785 ],
        [0.10169246, 0.04756282, 0.55047603, 0.23395907, 0.47507108]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [48]:
# your code/answer here
e == a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [56]:
# your code here
print('max:',d.max())
print('min:',d.min())
print('mean:',d.mean())

d_max = d.max()
d_min = d.min()
d_mean = d.mean()


max: 1.9954414644102179
min: 1.0361468026221066
mean: 1.406208857587004


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [61]:
# your code here
f = np.empty([2,3,5])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [64]:
# your code here

f[(d_mean > d) & (d_min < d)] = 25
f[(d_mean <d) & (d_max >d)]=75
f[d == d_mean]=50
f[d == d_min] = 0
f[d == d_max] = 100
print(f)

[[[ 75.   0.  75.  25.  25.]
  [ 75.  25. 100.  25.  25.]
  [ 75.  75.  25.  75.  25.]]

 [[ 75.  25.  25.  25.  25.]
  [ 75.  75.  25.  75.  75.]
  [ 25.  25.  75.  25.  75.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [65]:
# your code here
print(d)
print('\n')
print(f)

[[[1.52316372 1.0361468  1.96748181 1.35373965 1.08122286]
  [1.67106182 1.35551114 1.99544146 1.12850458 1.10951925]
  [1.79153253 1.78672675 1.28080216 1.43876727 1.33390863]]

 [[1.64974203 1.14259007 1.164385   1.26596103 1.22918095]
  [1.48574131 1.71760527 1.27312238 1.49236729 1.5032785 ]
  [1.10169246 1.04756282 1.55047603 1.23395907 1.47507108]]]


[[[ 75.   0.  75.  25.  25.]
  [ 75.  25. 100.  25.  25.]
  [ 75.  75.  25.  75.  25.]]

 [[ 75.  25.  25.  25.  25.]
  [ 75.  75.  25.  75.  75.]
  [ 25.  25.  75.  25.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.