# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [15]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [24]:
# your code here
print(np.__version__)
print(np.version.version)

1.18.3
1.18.3


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [94]:
# Method 1
a = np.random.random((2,3,5))
a

array([[[0.28704282, 0.63578135, 0.25792703, 0.60466265, 0.02696518],
        [0.92626347, 0.73560782, 0.86742998, 0.51476151, 0.62565408],
        [0.84831031, 0.29340118, 0.37402831, 0.62744349, 0.13569082]],

       [[0.35215157, 0.99783721, 0.58486459, 0.55278443, 0.46164173],
        [0.5345562 , 0.2255072 , 0.04277643, 0.37031753, 0.67683497],
        [0.20707604, 0.97967036, 0.08384687, 0.36582903, 0.10015947]]])

In [109]:
# Method 2
# If the idea was other efficient methods, then I am sure this was not the answer expected...
import random
a_2_list = [[[random.random() for x in range(5)] for y in range(3)] for z in range(2)]
a_2_array = np.array(a_2_list)
print(a_2_list)

#So, in this tiny mess I guess I used different elements that can be broken down in such way 
#that many slightly different methods may emerge...
#List comprenhensions, different libraries, coversion to pandas

[[[0.4874787480865702, 0.7294328168614178, 0.08199619741289099, 0.7258033528855552, 0.11773546825950676], [0.43533383469789555, 0.36232966243773623, 0.4718136421339171, 0.04915163855506821, 0.32856341593034244], [0.5941821730144241, 0.5504041585863444, 0.4528764276955938, 0.3155734899168894, 0.5854956346848709]], [[0.8899890204055302, 0.17485956011670645, 0.5700400282972632, 0.5572408695736266, 0.5418225901627134], [0.7825046414602546, 0.2887462005611673, 0.49914779839820156, 0.8579944465782452, 0.3709772013903371], [0.1627425140536347, 0.03322437468464412, 0.5418694751403077, 0.6854842690496193, 0.7030258479422954]]]


array([[[0.48747875, 0.72943282, 0.0819962 , 0.72580335, 0.11773547],
        [0.43533383, 0.36232966, 0.47181364, 0.04915164, 0.32856342],
        [0.59418217, 0.55040416, 0.45287643, 0.31557349, 0.58549563]],

       [[0.88998902, 0.17485956, 0.57004003, 0.55724087, 0.54182259],
        [0.78250464, 0.2887462 , 0.4991478 , 0.85799445, 0.3709772 ],
        [0.16274251, 0.03322437, 0.54186948, 0.68548427, 0.70302585]]])

In [ ]:
# Method 3

#### 4. Print *a*.


In [13]:
# your code here
print(a)

[[[0.22418834 0.18400291 0.85700358 0.51255609 0.99970282]
  [0.48858759 0.10463079 0.72201366 0.58598289 0.94483821]
  [0.45761734 0.84533814 0.85998644 0.51159489 0.53652852]]

 [[0.76392525 0.21294319 0.7859276  0.31971403 0.49225782]
  [0.02966878 0.71768147 0.51012709 0.77149284 0.15891014]
  [0.35516428 0.31779335 0.97510521 0.72898946 0.53389105]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [18]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [19]:
# your code here
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [20]:
# your code here
a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [27]:
# your answer here
c = np.add(a, b)

#different shapes

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [51]:
# your code here
c = np.transpose(b,(1,2,0))
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [53]:
# your code/answer here
d = np.add(a, c)

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [54]:
# your code/answer here
print(a)
print(d)
# Well, it is an array of random numbers + and array of ones. So we get an array of ones with random decimals

[[[0.22418834 0.18400291 0.85700358 0.51255609 0.99970282]
  [0.48858759 0.10463079 0.72201366 0.58598289 0.94483821]
  [0.45761734 0.84533814 0.85998644 0.51159489 0.53652852]]

 [[0.76392525 0.21294319 0.7859276  0.31971403 0.49225782]
  [0.02966878 0.71768147 0.51012709 0.77149284 0.15891014]
  [0.35516428 0.31779335 0.97510521 0.72898946 0.53389105]]]
[[[1.22418834 1.18400291 1.85700358 1.51255609 1.99970282]
  [1.48858759 1.10463079 1.72201366 1.58598289 1.94483821]
  [1.45761734 1.84533814 1.85998644 1.51159489 1.53652852]]

 [[1.76392525 1.21294319 1.7859276  1.31971403 1.49225782]
  [1.02966878 1.71768147 1.51012709 1.77149284 1.15891014]
  [1.35516428 1.31779335 1.97510521 1.72898946 1.53389105]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [56]:
# your code here
e = np.multiply(a,c)
e

array([[[0.22418834, 0.18400291, 0.85700358, 0.51255609, 0.99970282],
        [0.48858759, 0.10463079, 0.72201366, 0.58598289, 0.94483821],
        [0.45761734, 0.84533814, 0.85998644, 0.51159489, 0.53652852]],

       [[0.76392525, 0.21294319, 0.7859276 , 0.31971403, 0.49225782],
        [0.02966878, 0.71768147, 0.51012709, 0.77149284, 0.15891014],
        [0.35516428, 0.31779335, 0.97510521, 0.72898946, 0.53389105]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [57]:
# your code/answer here
e == a
#Yes, we are multiplying all elements by ones... 

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [72]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

TypeError: 'numpy.ndarray' object is not callable

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [63]:
# your code here
f = np.empty((2,3,5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [87]:
# your code here
for t in range(2):
    for r in range(3):
        for c in range(5):
            if d[t,r,c] > d_min and d[t,r,c] < d_mean:
                f[t,r,c] = 25
            elif d[t,r,c] > d_mean and d[t,r,c] < d_max:
                f[t,r,c] = 75
            elif d[t,r,c] == 0:
                f[t,r,c] = 0
            elif d[t,r,c] == d_mean:
                f[t,r,c] = 50
            else:
                f[t,r,c] = 100


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [76]:
# your code here
print(f)
print(" ")
print(d)

[[[25. 25. 75. 25. 50.]
  [25. 25. 75. 75. 75.]
  [25. 75. 75. 25. 25.]]

 [[75. 25. 75. 25. 25.]
  [50. 75. 25. 75. 25.]
  [25. 25. 75. 75. 25.]]]
 
[[[1.22418834 1.18400291 1.85700358 1.51255609 1.99970282]
  [1.48858759 1.10463079 1.72201366 1.58598289 1.94483821]
  [1.45761734 1.84533814 1.85998644 1.51159489 1.53652852]]

 [[1.76392525 1.21294319 1.7859276  1.31971403 1.49225782]
  [1.02966878 1.71768147 1.51012709 1.77149284 1.15891014]
  [1.35516428 1.31779335 1.97510521 1.72898946 1.53389105]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [88]:
# your code here
e = np.empty((2,3,5), dtype = str)
     
for t in range(2):
    for r in range(3):
        for c in range(5):
            if d[t,r,c] > d_min and d[t,r,c] < d_mean:
                e[t,r,c] = "D"
            elif d[t,r,c] > d_mean and d[t,r,c] < d_max:
                e[t,r,c] = "B"
            elif d[t,r,c] == 0:
                e[t,r,c] = "E"
            elif d[t,r,c] == d_mean:
                e[t,r,c] = "C"
            else:
                e[t,r,c] = "A"
                
print(e)

[[['D' 'D' 'B' 'D' 'A']
  ['D' 'D' 'B' 'B' 'B']
  ['D' 'B' 'B' 'D' 'D']]

 [['B' 'D' 'B' 'D' 'D']
  ['A' 'B' 'D' 'B' 'D']
  ['D' 'D' 'B' 'B' 'D']]]


In [92]:
# Here I am fooling around a more "pythonic" solution I saw Luke explaining
g = np.empty((2,3,5), dtype = str)
     
g[(d_min < d) & (d < d_mean)] = "D"
g[(d_mean < d) & (d < d_max)] = "B"
g[(d==d_min)] = "E"
g[(d==d_mean)] = "C"
g[(d==d_max)] = "A"

print(g)

[[['D' 'D' 'B' 'D' 'A']
  ['D' 'D' 'B' 'B' 'B']
  ['D' 'B' 'B' 'D' 'D']]

 [['B' 'D' 'B' 'D' 'D']
  ['E' 'B' 'D' 'B' 'D']
  ['D' 'D' 'B' 'B' 'D']]]


In [ ]:
#nice...