# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [2]:
print(np.__version__)

1.18.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
a = np.random.random((2,3,5))
print(a)

[[[0.89193187 0.22687718 0.26259857 0.98598927 0.44621086]
  [0.64911275 0.46556859 0.96217413 0.80788053 0.38051882]
  [0.24413499 0.18880309 0.30923462 0.91995406 0.28221702]]

 [[0.63108092 0.09493746 0.08862415 0.47478516 0.9207403 ]
  [0.19434336 0.14226195 0.09152265 0.36308007 0.78710363]
  [0.94989265 0.80426551 0.71105079 0.15865488 0.3448407 ]]]


In [4]:
a2 = np.random.rand(2,3,5)
print(a2)

[[[0.21130237 0.95133111 0.59166891 0.4256457  0.77565042]
  [0.60351025 0.60226144 0.73408382 0.56807673 0.23497305]
  [0.57500095 0.05302707 0.66644387 0.84884598 0.95843441]]

 [[0.83759993 0.32293879 0.3026453  0.09628351 0.53642252]
  [0.92726686 0.844723   0.13579238 0.05341637 0.91201427]
  [0.36335834 0.30976461 0.26402407 0.11912653 0.34845752]]]


In [5]:
a3 = np.empty((2,3,5))
print(a3)

[[[0.21130237 0.95133111 0.59166891 0.4256457  0.77565042]
  [0.60351025 0.60226144 0.73408382 0.56807673 0.23497305]
  [0.57500095 0.05302707 0.66644387 0.84884598 0.95843441]]

 [[0.83759993 0.32293879 0.3026453  0.09628351 0.53642252]
  [0.92726686 0.844723   0.13579238 0.05341637 0.91201427]
  [0.36335834 0.30976461 0.26402407 0.11912653 0.34845752]]]


#### 4. Print *a*.


In [6]:
print(a)

[[[0.89193187 0.22687718 0.26259857 0.98598927 0.44621086]
  [0.64911275 0.46556859 0.96217413 0.80788053 0.38051882]
  [0.24413499 0.18880309 0.30923462 0.91995406 0.28221702]]

 [[0.63108092 0.09493746 0.08862415 0.47478516 0.9207403 ]
  [0.19434336 0.14226195 0.09152265 0.36308007 0.78710363]
  [0.94989265 0.80426551 0.71105079 0.15865488 0.3448407 ]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
b = np.ones((5,2,3))

#### 6. Print *b*.


In [8]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
#is_same_size = np.multiply(a,b)
#print(is_same_size)
#operands could not be broadcast together with shapes (2,3,5) (5,2,3) ----> Different shapes! Different sizes!

#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# In order to combine (i.e. multiply, subtract, sum....) 2 arrays they must have the same shape!!

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
c = np.reshape(b,(2,3,5))
print(c)
print(np.shape(c))
print(np.shape(a))

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
(2, 3, 5)
(2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
print(a.shape)
print(c.shape)
d = np.add(a,c)

# In order to combine (i.e. multiply, subtract, sum....) 2 arrays they must have the same shape!! That's why it works!


(2, 3, 5)
(2, 3, 5)


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
print(a)
print("\n\n")
# array a --> is 2x3x5 3-dimensional array ---> 2 groups of arrays, consisted in 3 lines each group and 5 columns each group
print(d)
print("\n\n")
# array d --> is 2x3x5 3-dimensional array ---> 2 groups of arrays, consisted in 3 lines each group and 5 columns each group

print(type(a))

print(np.shape(d))
print(type(d))

print(a[0,0,0])
print("\n\n")
print(d[0,0,0])

print(type(a[0,0,0]))

print(type(d[0,0,0]))

#We are adding (2,3,5) 3-dimensional array 'c' full of 1s to array 'a', which mean all values on 'a' get summed 1.

[[[0.89193187 0.22687718 0.26259857 0.98598927 0.44621086]
  [0.64911275 0.46556859 0.96217413 0.80788053 0.38051882]
  [0.24413499 0.18880309 0.30923462 0.91995406 0.28221702]]

 [[0.63108092 0.09493746 0.08862415 0.47478516 0.9207403 ]
  [0.19434336 0.14226195 0.09152265 0.36308007 0.78710363]
  [0.94989265 0.80426551 0.71105079 0.15865488 0.3448407 ]]]



[[[1.89193187 1.22687718 1.26259857 1.98598927 1.44621086]
  [1.64911275 1.46556859 1.96217413 1.80788053 1.38051882]
  [1.24413499 1.18880309 1.30923462 1.91995406 1.28221702]]

 [[1.63108092 1.09493746 1.08862415 1.47478516 1.9207403 ]
  [1.19434336 1.14226195 1.09152265 1.36308007 1.78710363]
  [1.94989265 1.80426551 1.71105079 1.15865488 1.3448407 ]]]



<class 'numpy.ndarray'>
(2, 3, 5)
<class 'numpy.ndarray'>
0.8919318709330749



1.891931870933075
<class 'numpy.float64'>
<class 'numpy.float64'>


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
e = np.multiply(a,c)
print(np.shape(a))
print(np.shape(c))
print(e)

(2, 3, 5)
(2, 3, 5)
[[[0.89193187 0.22687718 0.26259857 0.98598927 0.44621086]
  [0.64911275 0.46556859 0.96217413 0.80788053 0.38051882]
  [0.24413499 0.18880309 0.30923462 0.91995406 0.28221702]]

 [[0.63108092 0.09493746 0.08862415 0.47478516 0.9207403 ]
  [0.19434336 0.14226195 0.09152265 0.36308007 0.78710363]
  [0.94989265 0.80426551 0.71105079 0.15865488 0.3448407 ]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
print(np.shape(a))
print(np.shape(e))

print(a)
print("\n\n")
print(e)

e == a
#the way we got 'e', was by multiplying a with an array full of 1s
#herefore e==1, 1 is the neutral element of multiplication

(2, 3, 5)
(2, 3, 5)
[[[0.89193187 0.22687718 0.26259857 0.98598927 0.44621086]
  [0.64911275 0.46556859 0.96217413 0.80788053 0.38051882]
  [0.24413499 0.18880309 0.30923462 0.91995406 0.28221702]]

 [[0.63108092 0.09493746 0.08862415 0.47478516 0.9207403 ]
  [0.19434336 0.14226195 0.09152265 0.36308007 0.78710363]
  [0.94989265 0.80426551 0.71105079 0.15865488 0.3448407 ]]]



[[[0.89193187 0.22687718 0.26259857 0.98598927 0.44621086]
  [0.64911275 0.46556859 0.96217413 0.80788053 0.38051882]
  [0.24413499 0.18880309 0.30923462 0.91995406 0.28221702]]

 [[0.63108092 0.09493746 0.08862415 0.47478516 0.9207403 ]
  [0.19434336 0.14226195 0.09152265 0.36308007 0.78710363]
  [0.94989265 0.80426551 0.71105079 0.15865488 0.3448407 ]]]


array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(d_max)
print(d_min)
print(d_mean)

1.9859892653361007
1.0886241522186084
1.4926796846465484


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [17]:
f = np.empty((2,3,5))
print(f)

[[[0.89193187 0.22687718 0.26259857 0.98598927 0.44621086]
  [0.64911275 0.46556859 0.96217413 0.80788053 0.38051882]
  [0.24413499 0.18880309 0.30923462 0.91995406 0.28221702]]

 [[0.63108092 0.09493746 0.08862415 0.47478516 0.9207403 ]
  [0.19434336 0.14226195 0.09152265 0.36308007 0.78710363]
  [0.94989265 0.80426551 0.71105079 0.15865488 0.3448407 ]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [18]:
f = np.copy(d)
f[f == d_min] = 0
f[(f>d_min) & (f<d_mean)] = 25
f[(f == d_mean)] = 50
f[(f>d_mean) & (f<d_max)] = 75
f[f == d_max] = 100

print(d)

print(f)

[[[1.89193187 1.22687718 1.26259857 1.98598927 1.44621086]
  [1.64911275 1.46556859 1.96217413 1.80788053 1.38051882]
  [1.24413499 1.18880309 1.30923462 1.91995406 1.28221702]]

 [[1.63108092 1.09493746 1.08862415 1.47478516 1.9207403 ]
  [1.19434336 1.14226195 1.09152265 1.36308007 1.78710363]
  [1.94989265 1.80426551 1.71105079 1.15865488 1.3448407 ]]]
[[[ 75.  25.  25. 100.  25.]
  [ 75.  25.  75.  75.  25.]
  [ 25.  25.  25.  75.  25.]]

 [[ 75.  25.   0.  25.  75.]
  [ 25.  25.  25.  25.  75.]
  [ 75.  75.  75.  25.  25.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [19]:
print(d)
print(f)

[[[1.89193187 1.22687718 1.26259857 1.98598927 1.44621086]
  [1.64911275 1.46556859 1.96217413 1.80788053 1.38051882]
  [1.24413499 1.18880309 1.30923462 1.91995406 1.28221702]]

 [[1.63108092 1.09493746 1.08862415 1.47478516 1.9207403 ]
  [1.19434336 1.14226195 1.09152265 1.36308007 1.78710363]
  [1.94989265 1.80426551 1.71105079 1.15865488 1.3448407 ]]]
[[[ 75.  25.  25. 100.  25.]
  [ 75.  25.  75.  75.  25.]
  [ 25.  25.  25.  75.  25.]]

 [[ 75.  25.   0.  25.  75.]
  [ 25.  25.  25.  25.  75.]
  [ 75.  75.  75.  25.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [22]:
g = np.where(d==d_min, "A", d)
g = np.where((d>d_min) & (d<d_mean), "B", g)
g = np.where(d == d_mean, "C", g)
g = np.where((d>d_mean) & (d<d_max) & (d<d_max), "D", g)
g = np.where(d == d_max, "E", g)
print("\n\n")
print(d_min)
print(d_mean)
print(d_max)
print("\n\n")
print(d)
print("\n\n")
print(g)
#Cool challenge




1.0886241522186084
1.4926796846465484
1.9859892653361007



[[[1.89193187 1.22687718 1.26259857 1.98598927 1.44621086]
  [1.64911275 1.46556859 1.96217413 1.80788053 1.38051882]
  [1.24413499 1.18880309 1.30923462 1.91995406 1.28221702]]

 [[1.63108092 1.09493746 1.08862415 1.47478516 1.9207403 ]
  [1.19434336 1.14226195 1.09152265 1.36308007 1.78710363]
  [1.94989265 1.80426551 1.71105079 1.15865488 1.3448407 ]]]



[[['D' 'B' 'B' 'E' 'B']
  ['D' 'B' 'D' 'D' 'B']
  ['B' 'B' 'B' 'D' 'B']]

 [['D' 'B' 'A' 'B' 'D']
  ['B' 'B' 'B' 'B' 'D']
  ['D' 'D' 'D' 'B' 'B']]]
