# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
np.version.version

'1.19.2'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a = np.random.random((2,3,5))


In [4]:
# Method 2
np.random.rand(2,3,5)

array([[[0.65591964, 0.55236327, 0.43348901, 0.73995201, 0.33415562],
        [0.96632824, 0.91554885, 0.8840427 , 0.50462478, 0.82733498],
        [0.16889948, 0.36585057, 0.36405897, 0.14880375, 0.63277856]],

       [[0.29896288, 0.3728518 , 0.07717808, 0.71221594, 0.58612337],
        [0.73861688, 0.74602475, 0.49197265, 0.24273916, 0.36171101],
        [0.96107669, 0.71023716, 0.11223028, 0.46806687, 0.81631604]]])

In [5]:
# Method 3
np.random.randint(100, size=(2,3,5))

array([[[53, 87, 11, 58, 85],
        [95, 80, 22, 63, 43],
        [20, 80, 63, 68, 59]],

       [[69, 27, 81,  1, 84],
        [52, 51, 69, 24, 30],
        [24, 87, 58,  3, 96]]])

#### 4. Print *a*.


In [6]:
# your code here
print(a)

[[[0.04173096 0.89752435 0.09113184 0.34027521 0.62657124]
  [0.1679225  0.01917534 0.10162742 0.07860485 0.24258484]
  [0.3327533  0.28254598 0.70400045 0.31103528 0.54974465]]

 [[0.87058949 0.24962515 0.67550385 0.00504727 0.20431933]
  [0.54123959 0.63053327 0.26537076 0.67105771 0.4697351 ]
  [0.41333845 0.61465116 0.28818817 0.06861371 0.53492585]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here
b = np.full((5,2,3), 1)

#### 6. Print *b*.


In [8]:
# your code here
b

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# with the size function we can see the count of elements of each array, in that case both have 30 elements.
a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here
# Is not possible to add them together because they have different shapes
np.add(a,b)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here
c = np.transpose(b, (1, 2, 0))

In [12]:
c.shape

(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [13]:
# it works now because they have the same shape.
d = np.add(a,c)

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [14]:
# your code/answer here
print(a)
print(" medium")
print(d)

[[[0.04173096 0.89752435 0.09113184 0.34027521 0.62657124]
  [0.1679225  0.01917534 0.10162742 0.07860485 0.24258484]
  [0.3327533  0.28254598 0.70400045 0.31103528 0.54974465]]

 [[0.87058949 0.24962515 0.67550385 0.00504727 0.20431933]
  [0.54123959 0.63053327 0.26537076 0.67105771 0.4697351 ]
  [0.41333845 0.61465116 0.28818817 0.06861371 0.53492585]]]
 medium
[[[1.04173096 1.89752435 1.09113184 1.34027521 1.62657124]
  [1.1679225  1.01917534 1.10162742 1.07860485 1.24258484]
  [1.3327533  1.28254598 1.70400045 1.31103528 1.54974465]]

 [[1.87058949 1.24962515 1.67550385 1.00504727 1.20431933]
  [1.54123959 1.63053327 1.26537076 1.67105771 1.4697351 ]
  [1.41333845 1.61465116 1.28818817 1.06861371 1.53492585]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [16]:
# your code here
e = a * c

#### 13. Does *e* equal to *a*? Why or why not?


In [19]:
# your code/answer here
e == a
# every element of the array matches with a. So we can conclude that "a" its igual to "e" 

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [20]:
# your code here
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

In [51]:
display(d_mean)

1.3763322352637466

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [109]:
# your code here
f = np.empty([2,3,5])

In [111]:
f

array([[[1.04173096, 1.89752435, 1.09113184, 1.34027521, 1.62657124],
        [1.1679225 , 1.01917534, 1.10162742, 1.07860485, 1.24258484],
        [1.3327533 , 1.28254598, 1.70400045, 1.31103528, 1.54974465]],

       [[1.87058949, 1.24962515, 1.67550385, 1.00504727, 1.20431933],
        [1.54123959, 1.63053327, 1.26537076, 1.67105771, 1.4697351 ],
        [1.41333845, 1.61465116, 1.28818817, 1.06861371, 1.53492585]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [138]:
# your code here

# f1 = [[[25 if d_min<item<d_mean else 75 if d_mean<item< d_max else 0 if item == d_min else 100 for item in in_list] for in_list in out_list] for out_list in d]
new_list = []

for array in d:
    for subarray in array:
        for value in subarray:
            if (value > d_min and value < d_mean):
                value = 25
                new_list.append(value)
            elif (value > d_mean and value < d_max):
                value = 75
                new_list.append(value)
            elif (value == d_mean):
                value = 50
                new_list.append(value)
            elif (value == d_min):
                value = 0
                new_list.append(value)
            else:
                f = 100
                new_list.append(value)


In [142]:
f= np.array([new_list])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here
f = np.reshape(f,[2,5,3])

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here