# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [92]:
import numpy as np

#### 2. Print your NumPy version.

In [93]:
print(np.version.version)

1.19.2


In [94]:
pip list

Package                            Version
---------------------------------- -------------------
alabaster                          0.7.12
anaconda-client                    1.7.2
anaconda-navigator                 1.10.0
anaconda-project                   0.8.3
argh                               0.26.2
argon2-cffi                        20.1.0
asn1crypto                         1.4.0
astroid                            2.4.2
astropy                            4.0.2
async-generator                    1.10
atomicwrites                       1.4.0
attrs                              20.3.0
autopep8                           1.5.4
Babel                              2.8.1
backcall                           0.2.0
backports.functools-lru-cache      1.6.1
backports.shutil-get-terminal-size 1.0.0
backports.tempfile                 1.0
backports.weakref                  1.0.post1
bcrypt                             3.2.0
beautifulsoup4                     4.9.3
bitarray                           

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [106]:
# Method 1
a = np.random.random((2,3,5))
print(a)
a.shape

[[[0.9110836  0.58390269 0.01435714 0.16035298 0.42689371]
  [0.18460433 0.00180052 0.30192468 0.33540474 0.6015341 ]
  [0.19976575 0.36371398 0.92847174 0.73942017 0.60826687]]

 [[0.91058325 0.45553026 0.44957915 0.38799452 0.84982653]
  [0.64244769 0.64973331 0.31540431 0.10662716 0.3641735 ]
  [0.50267239 0.04632013 0.38403808 0.52102341 0.91301292]]]


(2, 3, 5)

In [96]:
# Method 2
a2 = np.random.randint(10,90,(4,5)) # random numpy array of shape (4,5)
a2 

array([[19, 60, 27, 67, 70],
       [10, 61, 19, 16, 58],
       [76, 86, 82, 17, 37],
       [45, 58, 86, 16, 77]])

In [97]:
# Method 3
a3 = np.random.randn(4,5) # outputs an 4x5 array filled with random floating point numbers 
a3

array([[-0.9461561 ,  0.64030276, -1.56011392, -0.1869752 , -1.70512522],
       [ 0.34638426,  0.24536156,  0.08174028,  2.0818823 , -0.29621583],
       [ 0.25125155,  0.3925117 , -0.95514032, -0.73707261, -1.75310888],
       [-0.79430532,  0.41932717, -0.38852197, -0.15393691,  0.91137427]])

#### 4. Print *a*.


In [98]:

print(a)
a.ndim

[[[0.39273214 0.75821886 0.16528741 0.54780331 0.17898557]
  [0.27675052 0.60622156 0.44077362 0.25460044 0.75763088]
  [0.6263491  0.97354941 0.62718549 0.98619644 0.36014223]]

 [[0.5109755  0.68658257 0.1787554  0.31901042 0.85025917]
  [0.50870502 0.22896677 0.85498117 0.89013907 0.72587373]
  [0.12620447 0.09506011 0.3652477  0.63021948 0.9907859 ]]]


3

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [99]:
b = np.ones((5,2,3))

#### 6. Print *b*.


In [100]:
print(b)
b.ndim

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


3

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [101]:
#Prints the size using the size function
print('The size of a 5x2x3 3-dimensional array is  ',b.size,' !!!')
b_size = 5*2*3
#Prints the size using the size function
print('The size of a 5x2x3 3-dimensional array can be obtained by the product of each dimension  ',b_size,' !!!')

The size of a 5x2x3 3-dimensional array is   30  !!!
The size of a 5x2x3 3-dimensional array can be obtained by the product of each dimension   30  !!!


#### 8. Are you able to add *a* and *b*? Why or why not?


The two arrays have different dimensions, it is not possible do add them

In [102]:
#newArray = np.append(a, b, axis = 1)
new_Array = a + b
print(newArray)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [107]:
# your code here

b = np.ones((5,2,3))


c = np.transpose(b, (1,2,0))


print(np.transpose(b, (1,2,0)).shape)

c


(2, 3, 5)


array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [108]:
#d = np.append(a,c) 
d = a + c
print(d)
#print(d.shape)
print(a.shape)
print(c.shape)

#"The arrays now have the same shape, that is what makes it work!!!!!

[[[1.9110836  1.58390269 1.01435714 1.16035298 1.42689371]
  [1.18460433 1.00180052 1.30192468 1.33540474 1.6015341 ]
  [1.19976575 1.36371398 1.92847174 1.73942017 1.60826687]]

 [[1.91058325 1.45553026 1.44957915 1.38799452 1.84982653]
  [1.64244769 1.64973331 1.31540431 1.10662716 1.3641735 ]
  [1.50267239 1.04632013 1.38403808 1.52102341 1.91301292]]]
(2, 3, 5)
(2, 3, 5)


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [104]:
print(a)
print(d)

[[[0.39273214 0.75821886 0.16528741 0.54780331 0.17898557]
  [0.27675052 0.60622156 0.44077362 0.25460044 0.75763088]
  [0.6263491  0.97354941 0.62718549 0.98619644 0.36014223]]

 [[0.5109755  0.68658257 0.1787554  0.31901042 0.85025917]
  [0.50870502 0.22896677 0.85498117 0.89013907 0.72587373]
  [0.12620447 0.09506011 0.3652477  0.63021948 0.9907859 ]]]
[[[1.71141787 1.60627796 1.07409307 1.1597063  1.6484294 ]
  [1.13901264 1.47856781 1.34933251 1.63506225 1.51219929]
  [1.67030409 1.66055216 1.07379534 1.34801928 1.98217993]]

 [[1.94440015 1.69684575 1.15127578 1.97467101 1.71035069]
  [1.47709876 1.19862226 1.35147178 1.62659748 1.58247905]
  [1.66697488 1.51150481 1.71471698 1.95969873 1.80648231]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [ ]:
e = a * c

#### 13. Does *e* equal to *a*? Why or why not?


In [ ]:

print('Does e equal to a?',e.shape[0] == a.shape[0])



#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [111]:
d_max = np.max(d)
#print(d_max)
d_min = np.min(d)
#print(d_min)
d_mean = np.mean(d)

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [110]:
f = np.empty((2,3,5))
print(f)

[[[1.9110836  1.58390269 1.01435714 1.16035298 1.42689371]
  [1.18460433 1.00180052 1.30192468 1.33540474 1.6015341 ]
  [1.19976575 1.36371398 1.92847174 1.73942017 1.60826687]]

 [[1.91058325 1.45553026 1.44957915 1.38799452 1.84982653]
  [1.64244769 1.64973331 1.31540431 1.10662716 1.3641735 ]
  [1.50267239 1.04632013 1.38403808 1.52102341 1.91301292]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [112]:
f = np.where(d == d_max, 100, d)
f = np.where(d < d_max, 75, f)
f = np.where(d == d_mean, 50, f)
f = np.where(d < d_mean, 25, f)
f = np.where(d == d_min, 0, f)

print(d)
print(f)

[[[1.9110836  1.58390269 1.01435714 1.16035298 1.42689371]
  [1.18460433 1.00180052 1.30192468 1.33540474 1.6015341 ]
  [1.19976575 1.36371398 1.92847174 1.73942017 1.60826687]]

 [[1.91058325 1.45553026 1.44957915 1.38799452 1.84982653]
  [1.64244769 1.64973331 1.31540431 1.10662716 1.3641735 ]
  [1.50267239 1.04632013 1.38403808 1.52102341 1.91301292]]]
[[[ 75.  75.  25.  25.  25.]
  [ 25.   0.  25.  25.  75.]
  [ 25.  25. 100.  75.  75.]]

 [[ 75.  25.  25.  25.  75.]
  [ 75.  75.  25.  25.  25.]
  [ 75.  25.  25.  75.  75.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [113]:
f = np.where(d == d_max, 'C', d)
f = np.where(d < d_max, 'D', f)
f = np.where(d == d_mean, 'E', f)
f = np.where(d < d_mean, 'B', f)
f = np.where(d == d_min, 'A', f)

print(f)

[[['D' 'D' 'B' 'B' 'B']
  ['B' 'A' 'B' 'B' 'D']
  ['B' 'B' 'C' 'D' 'D']]

 [['D' 'B' 'B' 'B' 'D']
  ['D' 'D' 'B' 'B' 'B']
  ['D' 'B' 'B' 'D' 'D']]]
