# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here

import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
np.version.version

'1.18.5'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1 Random over normal distribution, mean 0.5
a= np.random.random((2,3,5))
print(a)
print(np.average(a))

[[[0.36081227 0.57813173 0.35628797 0.84748232 0.76876763]
  [0.21163469 0.15364345 0.67436447 0.0820975  0.23166859]
  [0.09229251 0.13395239 0.09145282 0.78682323 0.493165  ]]

 [[0.16128451 0.60262521 0.12616461 0.17859695 0.50235506]
  [0.76138665 0.35750741 0.82020224 0.62418017 0.57177997]
  [0.44051    0.57404232 0.05307395 0.88123133 0.90991758]]]
0.44758115143470645


In [4]:
# Method 2 Random over normal distribution, mean 0.5
b= np.random.rand[(2,3,5),(-2,3)]
print(b)
print(np.average(b))

TypeError: 'builtin_function_or_method' object is not subscriptable

In [ ]:
# Method 3 Random over normal distribution, mean 0
c= np.random.randn(2,3,5)
print(c)
print(np.average(c))

#### 4. Print *a*.


In [5]:
# your code here
print(a)
a.shape

[[[0.36081227 0.57813173 0.35628797 0.84748232 0.76876763]
  [0.21163469 0.15364345 0.67436447 0.0820975  0.23166859]
  [0.09229251 0.13395239 0.09145282 0.78682323 0.493165  ]]

 [[0.16128451 0.60262521 0.12616461 0.17859695 0.50235506]
  [0.76138665 0.35750741 0.82020224 0.62418017 0.57177997]
  [0.44051    0.57404232 0.05307395 0.88123133 0.90991758]]]


(2, 3, 5)

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [6]:
# your code here
b=np.ones((5,2,3))

#### 6. Print *b*.


In [7]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [8]:
# your code here
print(a.shape)
print(b.shape)
print(a.size)
print(b.size)


(2, 3, 5)
(5, 2, 3)
30
30


#### 8. Are you able to add *a* and *b*? Why or why not?


In [9]:
# your answer here
# Matrix shall share at least the dimension of the first column. 
d= np.add(a,b)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [10]:
# your code here
c= np.transpose(b, (1, 2, 0))
c.shape

(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [11]:
# your code/answer here
d= np.add(a,c)
print(d)

[[[1.36081227 1.57813173 1.35628797 1.84748232 1.76876763]
  [1.21163469 1.15364345 1.67436447 1.0820975  1.23166859]
  [1.09229251 1.13395239 1.09145282 1.78682323 1.493165  ]]

 [[1.16128451 1.60262521 1.12616461 1.17859695 1.50235506]
  [1.76138665 1.35750741 1.82020224 1.62418017 1.57177997]
  [1.44051    1.57404232 1.05307395 1.88123133 1.90991758]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [12]:
# your code/answer here: 

print(a)
print(d)
print(d-a)

[[[0.36081227 0.57813173 0.35628797 0.84748232 0.76876763]
  [0.21163469 0.15364345 0.67436447 0.0820975  0.23166859]
  [0.09229251 0.13395239 0.09145282 0.78682323 0.493165  ]]

 [[0.16128451 0.60262521 0.12616461 0.17859695 0.50235506]
  [0.76138665 0.35750741 0.82020224 0.62418017 0.57177997]
  [0.44051    0.57404232 0.05307395 0.88123133 0.90991758]]]
[[[1.36081227 1.57813173 1.35628797 1.84748232 1.76876763]
  [1.21163469 1.15364345 1.67436447 1.0820975  1.23166859]
  [1.09229251 1.13395239 1.09145282 1.78682323 1.493165  ]]

 [[1.16128451 1.60262521 1.12616461 1.17859695 1.50235506]
  [1.76138665 1.35750741 1.82020224 1.62418017 1.57177997]
  [1.44051    1.57404232 1.05307395 1.88123133 1.90991758]]]
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [13]:
# your code here
e= np.multiply(a,c)
print(e)

[[[0.36081227 0.57813173 0.35628797 0.84748232 0.76876763]
  [0.21163469 0.15364345 0.67436447 0.0820975  0.23166859]
  [0.09229251 0.13395239 0.09145282 0.78682323 0.493165  ]]

 [[0.16128451 0.60262521 0.12616461 0.17859695 0.50235506]
  [0.76138665 0.35750741 0.82020224 0.62418017 0.57177997]
  [0.44051    0.57404232 0.05307395 0.88123133 0.90991758]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [14]:
# your code/answer here
print(a-e)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [15]:
a==e

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [19]:
# your code here
print(d)
print(len(d))


[[[1.36081227 1.57813173 1.35628797 1.84748232 1.76876763]
  [1.21163469 1.15364345 1.67436447 1.0820975  1.23166859]
  [1.09229251 1.13395239 1.09145282 1.78682323 1.493165  ]]

 [[1.16128451 1.60262521 1.12616461 1.17859695 1.50235506]
  [1.76138665 1.35750741 1.82020224 1.62418017 1.57177997]
  [1.44051    1.57404232 1.05307395 1.88123133 1.90991758]]]
2


In [17]:
d_max=np.max(d)
d_min=np.min(d)
d_mean=np.average(d)
print(d_max,d_min,d_mean)

1.9099175812226465 1.0530739482118614 1.4475811514347063


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [36]:
# your code here
z = np.empty((2,3,5))
print(z)
z=list(z)


[[[1.36081227 1.57813173 1.35628797 1.84748232 1.76876763]
  [1.21163469 1.15364345 1.67436447 1.0820975  1.23166859]
  [1.09229251 1.13395239 1.09145282 1.78682323 1.493165  ]]

 [[1.16128451 1.60262521 1.12616461 1.17859695 1.50235506]
  [1.76138665 1.35750741 1.82020224 1.62418017 1.57177997]
  [1.44051    1.57404232 1.05307395 1.88123133 1.90991758]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [38]:
list_array=[]

In [53]:
# your code here
counter= 0
for groups in d:
    for subgroups in groups:
        for i in subgroups:
            counter +=1
            if d_min < i < d_mean:
                list_array.append(25)
            elif d_mean < i < d_max:
                list_array.append(75)
            elif  i == d_mean:
                list_array.append(50)
            elif  i == d_min:
                list_array.append(0)
            else:
                list_array.append(100)
print(counter)
d.size

30


30

In [40]:
print(list_array)

[25, 75, 25, 75, 75, 25, 25, 75, 25, 25, 25, 25, 25, 75, 75, 25, 75, 25, 25, 75, 75, 25, 75, 75, 75, 25, 75, 0, 75, 100]


In [46]:
z2= np.array(list_array)
print(z2)

[ 25  75  25  75  75  25  25  75  25  25  25  25  25  75  75  25  75  25
  25  75  75  25  75  75  75  25  75   0  75 100]


In [47]:
np.reshape(z2, (2,3,5))

array([[[ 25,  75,  25,  75,  75],
        [ 25,  25,  75,  25,  25],
        [ 25,  25,  25,  75,  75]],

       [[ 25,  75,  25,  25,  75],
        [ 75,  25,  75,  75,  75],
        [ 25,  75,   0,  75, 100]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [54]:
# your code here

list_array2=[]

counter= 0
for groups in d:
    for subgroups in groups:
        for i in subgroups:
            counter +=1
            if d_min < i < d_mean:
                list_array2.append('A')
            elif d_mean < i < d_max:
                list_array2.append('B')
            elif  i == d_mean:
                list_array2.append('C')
            elif  i == d_min:
                list_array2.append('D')
            else:
                list_array2.append('E')
                
print(list_array2)

['A', 'B', 'A', 'B', 'B', 'A', 'A', 'B', 'A', 'A', 'A', 'A', 'A', 'B', 'B', 'A', 'B', 'A', 'A', 'B', 'B', 'A', 'B', 'B', 'B', 'A', 'B', 'D', 'B', 'E']


In [55]:
z3= np.array(list_array2)
print(z3)

np.reshape(z3, (2,3,5))

['A' 'B' 'A' 'B' 'B' 'A' 'A' 'B' 'A' 'A' 'A' 'A' 'A' 'B' 'B' 'A' 'B' 'A'
 'A' 'B' 'B' 'A' 'B' 'B' 'B' 'A' 'B' 'D' 'B' 'E']


array([[['A', 'B', 'A', 'B', 'B'],
        ['A', 'A', 'B', 'A', 'A'],
        ['A', 'A', 'A', 'B', 'B']],

       [['A', 'B', 'A', 'A', 'B'],
        ['B', 'A', 'B', 'B', 'B'],
        ['A', 'B', 'D', 'B', 'E']]], dtype='<U1')