# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [109]:
import numpy as np

#### 2. Print your NumPy version.

In [110]:
print(np.version.version)

1.16.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [111]:
import random
a=np.random.randint(-10,10, size=(2,3,5))
print(a)

[[[  7  -3  -1  -4   8]
  [ -4   3   5  -8   9]
  [  1   6  -6   0 -10]]

 [[  0  -2  -1  -3  -3]
  [-10 -10  -2   9   6]
  [  2  -3  -1  -3   7]]]


In [100]:
a=np.random.rand(2,3,5)

In [101]:
# Method 3

#### 4. Print *a*.


In [102]:
print(a)

[[[0.84413299 0.34207123 0.34106573 0.96536779 0.75588699]
  [0.5022677  0.18022449 0.93432129 0.69738685 0.32642811]
  [0.52562204 0.36204172 0.87533045 0.15166998 0.13299685]]

 [[0.93920359 0.20486632 0.56219695 0.62818332 0.59248048]
  [0.32682431 0.06728194 0.77975377 0.19215393 0.40711799]
  [0.55878484 0.68062869 0.92468825 0.49450915 0.4622458 ]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [112]:
b=np.ones((5,2,3))

#### 6. Print *b*.


In [113]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [114]:
print(a.size)
print(b.size)

30
30


#### 8. Are you able to add *a* and *b*? Why or why not?


In [106]:
c= a+b
#No because their shapes are different

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [115]:
b2=b.copy()

c=b2.reshape((2,3,5))
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [116]:
d=a+c
print(d)
#because they have the same shape now

[[[ 8. -2.  0. -3.  9.]
  [-3.  4.  6. -7. 10.]
  [ 2.  7. -5.  1. -9.]]

 [[ 1. -1.  0. -2. -2.]
  [-9. -9. -1. 10.  7.]
  [ 3. -2.  0. -2.  8.]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [117]:
print(a+1)
print(d)

#the value of d is a + 1, thats because b was np.ones so a+1 = a+b




[[[ 8 -2  0 -3  9]
  [-3  4  6 -7 10]
  [ 2  7 -5  1 -9]]

 [[ 1 -1  0 -2 -2]
  [-9 -9 -1 10  7]
  [ 3 -2  0 -2  8]]]
[[[ 8. -2.  0. -3.  9.]
  [-3.  4.  6. -7. 10.]
  [ 2.  7. -5.  1. -9.]]

 [[ 1. -1.  0. -2. -2.]
  [-9. -9. -1. 10.  7.]
  [ 3. -2.  0. -2.  8.]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [118]:
e=a*c
print(e)

[[[  7.  -3.  -1.  -4.   8.]
  [ -4.   3.   5.  -8.   9.]
  [  1.   6.  -6.   0. -10.]]

 [[  0.  -2.  -1.  -3.  -3.]
  [-10. -10.  -2.   9.   6.]
  [  2.  -3.  -1.  -3.   7.]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [119]:
# no yes because we multiplied every element by 1
import numpy as np


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [120]:
d_min=d.min()
print(d_min)
d_max=d.max()
print(d_max)
d_mean=d.mean()
print(d_mean)

-9.0
10.0
0.6333333333333333


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [121]:

f=np.empty(shape=[2,3,5],dtype=int)
print(f)

[[[ 8 -2  0 -3  9]
  [-3  4  6 -7 10]
  [ 2  7 -5  1 -9]]

 [[ 1 -1  0 -2 -2]
  [-9 -9 -1 10  7]
  [ 3 -2  0 -2  8]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [124]:
# 2,3,5

for x in range (d.shape[0]):
    for y in range (d.shape[1]):
        for z in range (d.shape[2]):
            if d[x,y,z] > d_min and d[x,y,z] < d_mean:
                f[x,y,z]=25
            elif d[x,y,z]>d_mean and d[x,y,z]<d_max:
                f[x,y,z]=75
            elif d[x,y,z]==d_mean:
                f[x,y,z]=50
            elif d[x,y,z]== d_min:
                f[x,y,z]= 0
            else:
                f[x,y,z]=0



#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [125]:
print(d)
print(f)

[[[ 8. -2.  0. -3.  9.]
  [-3.  4.  6. -7. 10.]
  [ 2.  7. -5.  1. -9.]]

 [[ 1. -1.  0. -2. -2.]
  [-9. -9. -1. 10.  7.]
  [ 3. -2.  0. -2.  8.]]]
[[[75 25 25 25 75]
  [25 75 75 25  0]
  [75 75 25 75  0]]

 [[75 25 25 25 25]
  [ 0  0 25  0 75]
  [75 25 25 25 75]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here