# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [57]:
# your code here

import numpy as np


#### 2. Print your NumPy version.

In [58]:
# your code here

print(np.__version__)


1.18.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [59]:
# Method 1


a = np.random.random((2,3,5))
print(a)


[[[0.459486   0.4609384  0.93852018 0.29238009 0.37226617]
  [0.2256391  0.04578295 0.54566505 0.71486001 0.32070229]
  [0.96501385 0.55743905 0.17180879 0.22354125 0.58883765]]

 [[0.79599245 0.96999129 0.47018979 0.49031163 0.49381829]
  [0.47775555 0.9823676  0.86069627 0.0784845  0.09638725]
  [0.17392958 0.91260046 0.76443187 0.55707911 0.170903  ]]]


In [60]:
# Method 2

from numpy import random

x = random.rand(2, 3, 5)

print(x)



[[[0.51793464 0.94194266 0.90854572 0.46034302 0.32354635]
  [0.17280484 0.71506232 0.42132588 0.70526205 0.34048549]
  [0.44662063 0.61679264 0.92900071 0.04442037 0.11625368]]

 [[0.23046473 0.90947506 0.64149861 0.53431177 0.99531719]
  [0.21927995 0.5363986  0.5598549  0.5127198  0.22097285]
  [0.54889358 0.30567627 0.42431763 0.58997228 0.09280054]]]


In [10]:
# Method 3


x = random.choice([2, 3, 5], size=(2,3,5))

print(x)


[[[2 5 3 5 2]
  [3 5 3 3 3]
  [2 3 5 3 3]]

 [[5 3 2 5 2]
  [5 5 3 3 5]
  [3 2 2 3 2]]]


In [17]:
#method 
y = np.full((2,3,5), np.random.random())
print(y)

[[[0.58231521 0.58231521 0.58231521 0.58231521 0.58231521]
  [0.58231521 0.58231521 0.58231521 0.58231521 0.58231521]
  [0.58231521 0.58231521 0.58231521 0.58231521 0.58231521]]

 [[0.58231521 0.58231521 0.58231521 0.58231521 0.58231521]
  [0.58231521 0.58231521 0.58231521 0.58231521 0.58231521]
  [0.58231521 0.58231521 0.58231521 0.58231521 0.58231521]]]


#### 4. Print *a*.


In [61]:
# your code here
print(a)

[[[0.459486   0.4609384  0.93852018 0.29238009 0.37226617]
  [0.2256391  0.04578295 0.54566505 0.71486001 0.32070229]
  [0.96501385 0.55743905 0.17180879 0.22354125 0.58883765]]

 [[0.79599245 0.96999129 0.47018979 0.49031163 0.49381829]
  [0.47775555 0.9823676  0.86069627 0.0784845  0.09638725]
  [0.17392958 0.91260046 0.76443187 0.55707911 0.170903  ]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [38]:
# your code here



b = random.choice([1], size=(5,2,3))


#### 6. Print *b*.


In [39]:
# your code here

print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [40]:
# your code here

a_and_b = a + b
print(a_and_b)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 8. Are you able to add *a* and *b*? Why or why not?


In [ ]:
# your answer here

#No, because they are the same size/dimensions/shape

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [45]:
# your code here

c = np.transpose(b).reshape((2,3,5))

print(c)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [64]:
# your code/answer here

print(a)
d = a + c
print(d)

#It works becasue the arrays are the same shape/size/dimension



[[[0.459486   0.4609384  0.93852018 0.29238009 0.37226617]
  [0.2256391  0.04578295 0.54566505 0.71486001 0.32070229]
  [0.96501385 0.55743905 0.17180879 0.22354125 0.58883765]]

 [[0.79599245 0.96999129 0.47018979 0.49031163 0.49381829]
  [0.47775555 0.9823676  0.86069627 0.0784845  0.09638725]
  [0.17392958 0.91260046 0.76443187 0.55707911 0.170903  ]]]
[[[1.459486   1.4609384  1.93852018 1.29238009 1.37226617]
  [1.2256391  1.04578295 1.54566505 1.71486001 1.32070229]
  [1.96501385 1.55743905 1.17180879 1.22354125 1.58883765]]

 [[1.79599245 1.96999129 1.47018979 1.49031163 1.49381829]
  [1.47775555 1.9823676  1.86069627 1.0784845  1.09638725]
  [1.17392958 1.91260046 1.76443187 1.55707911 1.170903  ]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [65]:
# your code/answer here

print(a)


print(d)

#d is a + 1

[[[0.459486   0.4609384  0.93852018 0.29238009 0.37226617]
  [0.2256391  0.04578295 0.54566505 0.71486001 0.32070229]
  [0.96501385 0.55743905 0.17180879 0.22354125 0.58883765]]

 [[0.79599245 0.96999129 0.47018979 0.49031163 0.49381829]
  [0.47775555 0.9823676  0.86069627 0.0784845  0.09638725]
  [0.17392958 0.91260046 0.76443187 0.55707911 0.170903  ]]]
[[[1.459486   1.4609384  1.93852018 1.29238009 1.37226617]
  [1.2256391  1.04578295 1.54566505 1.71486001 1.32070229]
  [1.96501385 1.55743905 1.17180879 1.22354125 1.58883765]]

 [[1.79599245 1.96999129 1.47018979 1.49031163 1.49381829]
  [1.47775555 1.9823676  1.86069627 1.0784845  1.09638725]
  [1.17392958 1.91260046 1.76443187 1.55707911 1.170903  ]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [70]:
# your code here

e = a * c
print(e)

[[[0.459486   0.4609384  0.93852018 0.29238009 0.37226617]
  [0.2256391  0.04578295 0.54566505 0.71486001 0.32070229]
  [0.96501385 0.55743905 0.17180879 0.22354125 0.58883765]]

 [[0.79599245 0.96999129 0.47018979 0.49031163 0.49381829]
  [0.47775555 0.9823676  0.86069627 0.0784845  0.09638725]
  [0.17392958 0.91260046 0.76443187 0.55707911 0.170903  ]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [71]:
# your code/answer here

print(e.shape == a.shape)
e.shape

e == a
#It's not true because all the values equal each other as tehy're multiplied by one

True


array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [79]:
# your code here

d_max = np.amax(d)
print(d_max)

d_min = np.amin(d)
print(d_min)

d_mean = np.mean(d)
print(d_mean)

1.9823676024308245
1.0457829492842143
1.5059273150430599


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [83]:
# your code here

f = np.empty([2,3,5])

print(f)

[[[0.459486   0.4609384  0.93852018 0.29238009 0.37226617]
  [0.2256391  0.04578295 0.54566505 0.71486001 0.32070229]
  [0.96501385 0.55743905 0.17180879 0.22354125 0.58883765]]

 [[0.79599245 0.96999129 0.47018979 0.49031163 0.49381829]
  [0.47775555 0.9823676  0.86069627 0.0784845  0.09638725]
  [0.17392958 0.91260046 0.76443187 0.55707911 0.170903  ]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [91]:
# your code here


f = np.where(d == d_max, 100, d)
f = np.where(d < d_max, 75, f)
f = np.where(d == d_mean, 50, f)
f = np.where(d < d_mean, 25, f)
f = np.where(d == d_min, 0, f)

print(d)
print(f)

[[[1.459486   1.4609384  1.93852018 1.29238009 1.37226617]
  [1.2256391  1.04578295 1.54566505 1.71486001 1.32070229]
  [1.96501385 1.55743905 1.17180879 1.22354125 1.58883765]]

 [[1.79599245 1.96999129 1.47018979 1.49031163 1.49381829]
  [1.47775555 1.9823676  1.86069627 1.0784845  1.09638725]
  [1.17392958 1.91260046 1.76443187 1.55707911 1.170903  ]]]
[[[ 25.  25.  75.  25.  25.]
  [ 25.   0.  75.  75.  25.]
  [ 75.  75.  25.  25.  75.]]

 [[ 75.  75.  25.  25.  25.]
  [ 25. 100.  75.  25.  25.]
  [ 25.  75.  75.  75.  25.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here