# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [6]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [7]:
# your code here
np.version.version

'1.19.2'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [34]:
# Method 1
a = np.random.rand(2,3,5)

In [97]:
# Method 2
import random
new_array = np.zeros([2,3,5])
for one_D in range(2):
    for two_D in range(3):
        for three_D in range(5):
            new_array[one_D,two_D,three_D] = random.random()
new_array

array([[[0.60750703, 0.61954057, 0.48205486, 0.53174238, 0.12381169],
        [0.25333864, 0.47146216, 0.86195576, 0.89509217, 0.19369448],
        [0.2740532 , 0.33454548, 0.53023369, 0.6549428 , 0.4142992 ]],

       [[0.30268656, 0.67891713, 0.33243622, 0.81394295, 0.1178096 ],
        [0.28728086, 0.6699519 , 0.14202647, 0.95912753, 0.25544591],
        [0.29889419, 0.56846377, 0.34778844, 0.43846835, 0.13867143]]])

In [98]:
# Method 3
import random
new_array = np.empty([2,3,5])
for one_D in range(2):
    for two_D in range(3):
        for three_D in range(5):
            new_array[one_D,two_D,three_D] = random.random()
new_array

array([[[0.39494713, 0.63970884, 0.79529758, 0.28072744, 0.71315035],
        [0.57403031, 0.02195195, 0.50073085, 0.53280394, 0.06640899],
        [0.52427209, 0.95872297, 0.56110183, 0.51850037, 0.36957268]],

       [[0.97237358, 0.70989769, 0.80685753, 0.49819674, 0.32026205],
        [0.40228015, 0.56155996, 0.53728036, 0.82497017, 0.24648617],
        [0.00459449, 0.30591307, 0.90663061, 0.1110308 , 0.93615854]]])

#### 4. Print *a*.


In [99]:
# your code here
print(a)

[[[0.47386526 0.35719048 0.24267204 0.02190135 0.11172443]
  [0.0216918  0.86633823 0.58790198 0.43106297 0.85114351]
  [0.89581726 0.52021793 0.76923253 0.44325174 0.47877528]]

 [[0.32375398 0.80852526 0.44783811 0.7598707  0.69328936]
  [0.30159047 0.64589475 0.12390633 0.39847305 0.80103362]
  [0.19436045 0.57963588 0.08504077 0.12765217 0.65599573]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [100]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [101]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [102]:
# your code here
try:
    (a + b)
    print('They are the same size')
except:
    print('They are not the same size')

They are not the same size


#### 8. Are you able to add *a* and *b*? Why or why not?


In [103]:
# your answer here
#no because they are not the same size

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [104]:
# your code here
c = b.transpose(1,2,0)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [105]:
# your code/answer here
d = a+c
#it works because now they are the same size

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [106]:
# your code/answer here
print(a)
print(d)
#d is just a +1 for each value because b was a ones matrix

[[[0.47386526 0.35719048 0.24267204 0.02190135 0.11172443]
  [0.0216918  0.86633823 0.58790198 0.43106297 0.85114351]
  [0.89581726 0.52021793 0.76923253 0.44325174 0.47877528]]

 [[0.32375398 0.80852526 0.44783811 0.7598707  0.69328936]
  [0.30159047 0.64589475 0.12390633 0.39847305 0.80103362]
  [0.19436045 0.57963588 0.08504077 0.12765217 0.65599573]]]
[[[1.47386526 1.35719048 1.24267204 1.02190135 1.11172443]
  [1.0216918  1.86633823 1.58790198 1.43106297 1.85114351]
  [1.89581726 1.52021793 1.76923253 1.44325174 1.47877528]]

 [[1.32375398 1.80852526 1.44783811 1.7598707  1.69328936]
  [1.30159047 1.64589475 1.12390633 1.39847305 1.80103362]
  [1.19436045 1.57963588 1.08504077 1.12765217 1.65599573]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [107]:
# your code here
e = a*c

#### 13. Does *e* equal to *a*? Why or why not?


In [108]:
# your code/answer here
a == e
#e is equal to a because c is a ones matrix so it multiplies each value by one

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [109]:
# your code here
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [110]:
# your code here
f = np.empty((2,3,5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [111]:
# your code here
f = np.where(d<d_mean, 25, f)
f = np.where(d>d_mean, 75, f)
f = np.where(d == d_mean, 50, f)
f = np.where(d == d_max, 100, f)
f = np.where(d == d_min, 0, f)

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [112]:
# your code here
print(f)

[[[ 75.  25.  25.  25.  25.]
  [  0.  75.  75.  25.  75.]
  [100.  75.  75.  25.  75.]]

 [[ 25.  75.  25.  75.  75.]
  [ 25.  75.  25.  25.  75.]
  [ 25.  75.  25.  25.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [113]:
# your code here
f = np.where(d<d_mean, 'B', f)
f = np.where(d>d_mean, 'D', f)
f = np.where(d == d_mean, 'C', f)
f = np.where(d == d_max, 'E', f)
f = np.where(d == d_min, 'A', f)

In [114]:
print(f)

[[['D' 'B' 'B' 'B' 'B']
  ['A' 'D' 'D' 'B' 'D']
  ['E' 'D' 'D' 'B' 'D']]

 [['B' 'D' 'B' 'D' 'D']
  ['B' 'D' 'B' 'B' 'D']
  ['B' 'D' 'B' 'B' 'D']]]
