# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [2]:
print(np)

<module 'numpy' from '/Users/caionunez/opt/anaconda3/lib/python3.9/site-packages/numpy/__init__.py'>


In [3]:
print(np.__version__) #Upon doing some research find out this was a more accurate way of doing it.

1.21.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [4]:
a = np.random.randint(100, size=(2,3,5))  #Random array of integers up to 100
a

array([[[77, 44, 66, 47, 39],
        [49, 52, 24, 38, 38],
        [11,  0, 88, 93, 71]],

       [[70, 64,  3, 80, 99],
        [74, 51, 72, 51, 46],
        [ 0, 23, 75, 62, 19]]])

In [5]:
a1 = np.random.random(size=(2,3,5))  #Random array of floats from 0 to 1.0
a1

array([[[0.8461133 , 0.85527312, 0.99576826, 0.53275993, 0.08674461],
        [0.01623897, 0.03191551, 0.84437521, 0.20361331, 0.3253768 ],
        [0.57341489, 0.63787329, 0.99270021, 0.98943152, 0.54342345]],

       [[0.79877198, 0.23097107, 0.5637224 , 0.65089155, 0.55594442],
        [0.17990288, 0.95109084, 0.96435465, 0.49420316, 0.33542697],
        [0.85285023, 0.82022267, 0.66843771, 0.83434036, 0.54853692]]])

In [6]:
a2 = np.random.randn(2, 3, 5)
a2

array([[[ 1.35844531,  1.12529194,  0.51168662,  0.11543032,
         -1.40948216],
        [-1.07917267, -0.59538798,  0.58037845, -0.35377062,
          0.42900531],
        [-0.83519084, -0.95589407, -0.09433606, -0.75219027,
         -0.37601536]],

       [[-0.44898996, -0.6840606 ,  1.03961043,  0.36747413,
          0.39668053],
        [ 0.30795845,  1.42932107, -0.75860301,  0.11652953,
         -0.53693385],
        [-0.60901895, -0.6902036 , -0.05911381, -0.51410255,
         -0.21178899]]])

In [7]:
#Used three methods from random, not sure if that was intended or not. 
#All have different features but not sure if that was the intention of the exercise

#### 4. Print *a*.


In [8]:
print(a)

[[[77 44 66 47 39]
  [49 52 24 38 38]
  [11  0 88 93 71]]

 [[70 64  3 80 99]
  [74 51 72 51 46]
  [ 0 23 75 62 19]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [9]:
b = np.ones(shape=(5,2,3), dtype = int)

#### 6. Print *b*.


In [10]:
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [11]:
a.shape == b.shape  

#My answer is that they don't have the same size, but funny that .size returns True

False

In [12]:
len(a) == len(b)

False

In [13]:
a.size == b.size

True

In [14]:
np.array_equal(a,b)

False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [15]:
a + b

#No, as at the moment they don't have the same shape

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [16]:
c = b.reshape(2,3,5)
c

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [17]:
d = a + c
d

#After reshape arrays a and c have the same shape and allow operation sum

array([[[ 78,  45,  67,  48,  40],
        [ 50,  53,  25,  39,  39],
        [ 12,   1,  89,  94,  72]],

       [[ 71,  65,   4,  81, 100],
        [ 75,  52,  73,  52,  47],
        [  1,  24,  76,  63,  20]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [18]:
print("Array a is:\n\n", a, "\n")
print("Array d is:\n\n", d)

Array a is:

 [[[77 44 66 47 39]
  [49 52 24 38 38]
  [11  0 88 93 71]]

 [[70 64  3 80 99]
  [74 51 72 51 46]
  [ 0 23 75 62 19]]] 

Array d is:

 [[[ 78  45  67  48  40]
  [ 50  53  25  39  39]
  [ 12   1  89  94  72]]

 [[ 71  65   4  81 100]
  [ 75  52  73  52  47]
  [  1  24  76  63  20]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [19]:
e = a*c
e

array([[[77, 44, 66, 47, 39],
        [49, 52, 24, 38, 38],
        [11,  0, 88, 93, 71]],

       [[70, 64,  3, 80, 99],
        [74, 51, 72, 51, 46],
        [ 0, 23, 75, 62, 19]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [20]:
np.array_equal(a,e) #E was the result of A*C and C was an np.ones array so we just multiplied everthing by 1

True

In [21]:
a==e   #returning an array of booleans confirming all elements are equal

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [22]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

print(d_max)
print(d_min)
print(d_mean)

100
1
51.86666666666667


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [23]:
f = np.empty(shape=(2,3,5),dtype=int)
f

array([[[   0, 2043,    0,    0,    0],
        [   0,    0,    0,    0,    0],
        [   0,    0,    0,    0,    0]],

       [[   0,    0,    0,    0,    0],
        [   0,    0,    0,    0,    0],
        [   0,    0,    0,    0,    0]]])

In [24]:
10 > d_mean or 10 < d_mean

True

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [33]:
#Tried a few solutions, none worked. Will check with TA tomorrow. 

#I found one that works if using numpy, but I don't think that is the alternative


for x in d:
    for y in x:
        for number in y:
            if d_min < number < d_mean:
                f[number] = 25
            if d_mean < number < d_max:
                f[number] = 75
            if number == d_mean:
                f[number] = 50
            if number == d_min:
                f[number] = 0
            if number == d_max:
                f[number] = 100
        
print(f)

IndexError: index 78 is out of bounds for axis 0 with size 2

In [36]:
f[(d > d_min) & (d < d_mean)] = 25
f[(d > d_mean) & (d < d_max)] = 75
f[(d == d_mean)] = 50
f[(d == d_min) ] = 0
f[(d == d_max) ] = 100

f

#Ok I believe this now is working

array([[[ 75,  25,  75,  25,  25],
        [ 25,  75,  25,  25,  25],
        [ 25,   0,  75,  75,  75]],

       [[ 75,  75,  25,  75, 100],
        [ 75,  75,  75,  75,  25],
        [  0,  25,  75,  75,  25]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.