# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.__version__)

1.18.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1 
np.random.random((2,3,5))

array([[[0.07343637, 0.56268589, 0.51691649, 0.35521104, 0.18235913],
        [0.70758972, 0.13262162, 0.58805148, 0.97553839, 0.71827393],
        [0.31970993, 0.27739594, 0.70047415, 0.0405169 , 0.96257159]],

       [[0.24026021, 0.53946521, 0.21884634, 0.52300829, 0.65490534],
        [0.58153222, 0.79596555, 0.2610773 , 0.90682316, 0.20441769],
        [0.31469563, 0.66807351, 0.18634495, 0.51775159, 0.26604274]]])

In [4]:
# Method 2 
np.random.randint(100, size=(2,3, 5))

array([[[56,  2, 98, 94, 81],
        [47, 34, 45, 45, 81],
        [ 5, 12,  6, 90, 12]],

       [[11, 57, 42, 34,  4],
        [14, 24, 62, 87, 91],
        [31, 14, 22, 16, 27]]])

In [5]:
# Method 3 
a = np.random.rand(2,3,5)

#### 4. Print *a*.


In [6]:
# your code here
print(a)

[[[0.7741536  0.44399362 0.84576684 0.43095913 0.69682173]
  [0.92551055 0.42631237 0.3923295  0.49281016 0.81553379]
  [0.16834662 0.21875079 0.82661231 0.18850412 0.68868015]]

 [[0.00490741 0.73860311 0.49255172 0.27453183 0.26875526]
  [0.6434726  0.36784229 0.09002591 0.41329767 0.08652527]
  [0.41276268 0.56734747 0.47146212 0.68894783 0.95675796]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [8]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here
a.size==b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here
a_b= a+b
# that is not possible because the shape is different 

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here
#Transposing b to get the Format 2*3*5 

c= b.reshape(2,3,5)
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# your code/answer here
d= a+c
d
# It works now because the arrays have the same shape

array([[[1.7741536 , 1.44399362, 1.84576684, 1.43095913, 1.69682173],
        [1.92551055, 1.42631237, 1.3923295 , 1.49281016, 1.81553379],
        [1.16834662, 1.21875079, 1.82661231, 1.18850412, 1.68868015]],

       [[1.00490741, 1.73860311, 1.49255172, 1.27453183, 1.26875526],
        [1.6434726 , 1.36784229, 1.09002591, 1.41329767, 1.08652527],
        [1.41276268, 1.56734747, 1.47146212, 1.68894783, 1.95675796]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# your code/answer here
print(a)

print(d)

len(a)==len(d)
# Both arrays have the same size, same number of items stored
# every value in d is exactly a+1 from the equivalent value in a
print(sum(a))
print(sum(d))

[[[0.7741536  0.44399362 0.84576684 0.43095913 0.69682173]
  [0.92551055 0.42631237 0.3923295  0.49281016 0.81553379]
  [0.16834662 0.21875079 0.82661231 0.18850412 0.68868015]]

 [[0.00490741 0.73860311 0.49255172 0.27453183 0.26875526]
  [0.6434726  0.36784229 0.09002591 0.41329767 0.08652527]
  [0.41276268 0.56734747 0.47146212 0.68894783 0.95675796]]]
[[[1.7741536  1.44399362 1.84576684 1.43095913 1.69682173]
  [1.92551055 1.42631237 1.3923295  1.49281016 1.81553379]
  [1.16834662 1.21875079 1.82661231 1.18850412 1.68868015]]

 [[1.00490741 1.73860311 1.49255172 1.27453183 1.26875526]
  [1.6434726  1.36784229 1.09002591 1.41329767 1.08652527]
  [1.41276268 1.56734747 1.47146212 1.68894783 1.95675796]]]
[[0.77906101 1.18259672 1.33831857 0.70549096 0.965577  ]
 [1.56898315 0.79415466 0.48235541 0.90610783 0.90205906]
 [0.58110931 0.78609825 1.29807444 0.87745195 1.64543811]]
[[2.77906101 3.18259672 3.33831857 2.70549096 2.965577  ]
 [3.56898315 2.79415466 2.48235541 2.90610783 2.902

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
# your code here
e= a*c
e

array([[[0.7741536 , 0.44399362, 0.84576684, 0.43095913, 0.69682173],
        [0.92551055, 0.42631237, 0.3923295 , 0.49281016, 0.81553379],
        [0.16834662, 0.21875079, 0.82661231, 0.18850412, 0.68868015]],

       [[0.00490741, 0.73860311, 0.49255172, 0.27453183, 0.26875526],
        [0.6434726 , 0.36784229, 0.09002591, 0.41329767, 0.08652527],
        [0.41276268, 0.56734747, 0.47146212, 0.68894783, 0.95675796]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
# your code/answer here
a==e

print('e equals array a because e is the multiplication of values a with 1')

e equals array a because e is the multiplication of values a with 1


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [29]:
# your code here
d_max = d.max()
print('the max value in array d is: {}'.format(d_max))
d_min = d.min()
print('the min value in array d is: {}'.format(d_min))
d_mean = d.mean()
print('the mean value in array d is: {}'.format(d_mean))

the max value in array d is: 1.9567579602292282
the min value in array d is: 1.0049074083001057
the mean value in array d is: 1.4937625476065313


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [17]:
# your code here
f= np.empty([2,3,5])
f

array([[[0.7741536 , 0.44399362, 0.84576684, 0.43095913, 0.69682173],
        [0.92551055, 0.42631237, 0.3923295 , 0.49281016, 0.81553379],
        [0.16834662, 0.21875079, 0.82661231, 0.18850412, 0.68868015]],

       [[0.00490741, 0.73860311, 0.49255172, 0.27453183, 0.26875526],
        [0.6434726 , 0.36784229, 0.09002591, 0.41329767, 0.08652527],
        [0.41276268, 0.56734747, 0.47146212, 0.68894783, 0.95675796]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [66]:
# your code here
f= np.where((d > d_min) & (d<d_mean), 25, d)
f= np.where((d > d_mean) & (d<d_max), 75, f)
f= np.where(d == d_mean , 50, f)
f= np.where(d == d_min , 0, f)
f= np.where(d == d_max , 100, f)




array([[[ 75.,  25.,  75.,  25.,  75.],
        [ 75.,  25.,  25.,  25.,  75.],
        [ 25.,  25.,  75.,  25.,  75.]],

       [[  0.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  25.,  25.,  25.],
        [ 25.,  75.,  25.,  75., 100.]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [67]:
# your code here
f

array([[[ 75.,  25.,  75.,  25.,  75.],
        [ 75.,  25.,  25.,  25.,  75.],
        [ 25.,  25.,  75.,  25.,  75.]],

       [[  0.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  25.,  25.,  25.],
        [ 25.,  75.,  25.,  75., 100.]]])

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here