# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.version)

<module 'numpy.version' from 'C:\\Users\\TG\\Anaconda3\\lib\\site-packages\\numpy\\version.py'>


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a = np.random.random((2,3,5))
a

array([[[0.2627405 , 0.89113967, 0.65312361, 0.03907793, 0.48415546],
        [0.18695085, 0.29471439, 0.77774292, 0.17642751, 0.56100342],
        [0.94648885, 0.09466526, 0.70344416, 0.73301271, 0.31369664]],

       [[0.85719546, 0.12516167, 0.03743833, 0.37203229, 0.74775669],
        [0.44175682, 0.72676062, 0.30386771, 0.38744405, 0.43679122],
        [0.47127072, 0.18018107, 0.24590023, 0.22812326, 0.30187815]]])

In [4]:
# Method 2


In [5]:
# Method 3

#### 4. Print *a*.


In [6]:
# your code here

print(a)

[[[0.2627405  0.89113967 0.65312361 0.03907793 0.48415546]
  [0.18695085 0.29471439 0.77774292 0.17642751 0.56100342]
  [0.94648885 0.09466526 0.70344416 0.73301271 0.31369664]]

 [[0.85719546 0.12516167 0.03743833 0.37203229 0.74775669]
  [0.44175682 0.72676062 0.30386771 0.38744405 0.43679122]
  [0.47127072 0.18018107 0.24590023 0.22812326 0.30187815]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here

b = np.ones((5,2,3))


#### 6. Print *b*.


In [8]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here
size = a.size - b.size

if size == 0:
    print("They have the same size")
else:
    print("Don't have the same size")
    


They have the same size


#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here
add = a + b

#I can't because they have different shapes

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [12]:
# your code here
#c = b.transpose(np.ones((2,3,5)))

c = b.reshape(2,3,5)
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [60]:
# your code/answer here
d = a + c 

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [66]:
# your code/answer here
print(a)

print(d)

#Values are the sum of A and C, so they are related

[[[0.2627405  0.89113967 0.65312361 0.03907793 0.48415546]
  [0.18695085 0.29471439 0.77774292 0.17642751 0.56100342]
  [0.94648885 0.09466526 0.70344416 0.73301271 0.31369664]]

 [[0.85719546 0.12516167 0.03743833 0.37203229 0.74775669]
  [0.44175682 0.72676062 0.30386771 0.38744405 0.43679122]
  [0.47127072 0.18018107 0.24590023 0.22812326 0.30187815]]]
[[[1.2627405  1.89113967 1.65312361 1.03907793 1.48415546]
  [1.18695085 1.29471439 1.77774292 1.17642751 1.56100342]
  [1.94648885 1.09466526 1.70344416 1.73301271 1.31369664]]

 [[1.85719546 1.12516167 1.03743833 1.37203229 1.74775669]
  [1.44175682 1.72676062 1.30386771 1.38744405 1.43679122]
  [1.47127072 1.18018107 1.24590023 1.22812326 1.30187815]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [ ]:
# your code here

e = a * c
e

#### 13. Does *e* equal to *a*? Why or why not?


In [ ]:
# your code/answer here
e == a

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [30]:
# your code here

d_max = d.max()
d_min = d.min()
d_mean = d.mean()

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [31]:
# your code here
f = np.empty((2,3,5))



#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [78]:
# your code here

new_d = [num for sublist in d for subsublist in sublist for num in subsublist]
print(new_d)

new_lst = []

for value in new_d:
    if value > d_min and value < d_mean:
        new_lst.append(25)
    elif value > d_mean and value < d_max:
        new_lst.append(75)
    elif value == d_mean:
        new_lst.append(50)
    else:
        new_lst.append(0)
        
print(new_lst)

f = np.asarray(new_lst)


[1.262740501951658, 1.8911396659327337, 1.6531236146451265, 1.0390779279900408, 1.4841554597472726, 1.186950848426234, 1.2947143933758312, 1.7777429183598494, 1.176427506374499, 1.5610034244369495, 1.946488854927932, 1.0946652593574913, 1.70344416264305, 1.7330127142603393, 1.3136966354163606, 1.857195462499189, 1.1251616660774297, 1.0374383255781463, 1.3720322874957822, 1.7477566919254968, 1.4417568155217038, 1.726760615801472, 1.3038677135132424, 1.3874440497888259, 1.436791223421149, 1.471270721244367, 1.1801810719085093, 1.2459002330339668, 1.2281232567139888, 1.3018781527701082]
[25, 75, 75, 25, 75, 25, 25, 75, 25, 75, 0, 25, 75, 75, 25, 75, 25, 0, 25, 75, 75, 75, 25, 25, 75, 75, 25, 25, 25, 25]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [79]:
# your code here

print(d)


print(f.reshape(2,3,5))


[[[1.2627405  1.89113967 1.65312361 1.03907793 1.48415546]
  [1.18695085 1.29471439 1.77774292 1.17642751 1.56100342]
  [1.94648885 1.09466526 1.70344416 1.73301271 1.31369664]]

 [[1.85719546 1.12516167 1.03743833 1.37203229 1.74775669]
  [1.44175682 1.72676062 1.30386771 1.38744405 1.43679122]
  [1.47127072 1.18018107 1.24590023 1.22812326 1.30187815]]]
[[[25 75 75 25 75]
  [25 25 75 25 75]
  [ 0 25 75 75 25]]

 [[75 25  0 25 75]
  [75 75 25 25 75]
  [75 25 25 25 25]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here