# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here

import numpy as np

#### 2. Print your NumPy version.

In [7]:
# your code here

np.version.version

'1.19.2'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [8]:
# Method 1

a = np.random.random((2,3,5))


[[[0.51862546 0.27926604 0.62538208 0.4139255  0.1070457 ]
  [0.82024308 0.95908448 0.4414443  0.62354977 0.65628659]
  [0.509923   0.03366431 0.94790128 0.34204357 0.00836994]]

 [[0.80378364 0.21952224 0.72424512 0.75155051 0.05172862]
  [0.39655013 0.2698024  0.59949828 0.03592973 0.51790246]
  [0.99095602 0.84629838 0.55037965 0.57244364 0.63918969]]]


In [ ]:
# Method 2

In [ ]:
# Method 3

#### 4. Print *a*.


In [ ]:
# your code here

print(a)


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [9]:
# your code here

b = np.full((5, 2, 3), 1)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 6. Print *b*.


In [ ]:
# your code here

print (b)

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [12]:
# your code here

print (a.size == b.size)

True


#### 8. Are you able to add *a* and *b*? Why or why not?


In [14]:
# your answer here

c = np.add(a,b)

print (a.shape == b.shape)

# connot add a and b since the shape is not the same

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [29]:
# your code here

c = np.transpose(b, axes=(1,2,0))
print(np.shape(c))


(2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [32]:
# your code/answer here

print (a.shape == c.shape)

d = np.add(a,c)


True


array([[[1.51862546, 1.27926604, 1.62538208, 1.4139255 , 1.1070457 ],
        [1.82024308, 1.95908448, 1.4414443 , 1.62354977, 1.65628659],
        [1.509923  , 1.03366431, 1.94790128, 1.34204357, 1.00836994]],

       [[1.80378364, 1.21952224, 1.72424512, 1.75155051, 1.05172862],
        [1.39655013, 1.2698024 , 1.59949828, 1.03592973, 1.51790246],
        [1.99095602, 1.84629838, 1.55037965, 1.57244364, 1.63918969]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [34]:
# your code/answer here

print (a)

print (d)

# values of d are values of a + 1 

[[[0.51862546 0.27926604 0.62538208 0.4139255  0.1070457 ]
  [0.82024308 0.95908448 0.4414443  0.62354977 0.65628659]
  [0.509923   0.03366431 0.94790128 0.34204357 0.00836994]]

 [[0.80378364 0.21952224 0.72424512 0.75155051 0.05172862]
  [0.39655013 0.2698024  0.59949828 0.03592973 0.51790246]
  [0.99095602 0.84629838 0.55037965 0.57244364 0.63918969]]]
[[[1.51862546 1.27926604 1.62538208 1.4139255  1.1070457 ]
  [1.82024308 1.95908448 1.4414443  1.62354977 1.65628659]
  [1.509923   1.03366431 1.94790128 1.34204357 1.00836994]]

 [[1.80378364 1.21952224 1.72424512 1.75155051 1.05172862]
  [1.39655013 1.2698024  1.59949828 1.03592973 1.51790246]
  [1.99095602 1.84629838 1.55037965 1.57244364 1.63918969]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [35]:
# your code here

e = a * c

e

array([[[0.51862546, 0.27926604, 0.62538208, 0.4139255 , 0.1070457 ],
        [0.82024308, 0.95908448, 0.4414443 , 0.62354977, 0.65628659],
        [0.509923  , 0.03366431, 0.94790128, 0.34204357, 0.00836994]],

       [[0.80378364, 0.21952224, 0.72424512, 0.75155051, 0.05172862],
        [0.39655013, 0.2698024 , 0.59949828, 0.03592973, 0.51790246],
        [0.99095602, 0.84629838, 0.55037965, 0.57244364, 0.63918969]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [36]:
# your code/answer here

print (a==e)

# they are equal as the values of c are 1.

[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [41]:
# your code here

d_max = d.max()

print (d_max)

d_min = d.min()

print (d_min)

d_mean = d.mean()

print (d_mean)

1.9909560162114541
1.0083699431736628
1.5085511871829915


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [46]:
# your code here

f = np.empty ([2,3,5])

f

array([[[0.51862546, 0.27926604, 0.62538208, 0.4139255 , 0.1070457 ],
        [0.82024308, 0.95908448, 0.4414443 , 0.62354977, 0.65628659],
        [0.509923  , 0.03366431, 0.94790128, 0.34204357, 0.00836994]],

       [[0.80378364, 0.21952224, 0.72424512, 0.75155051, 0.05172862],
        [0.39655013, 0.2698024 , 0.59949828, 0.03592973, 0.51790246],
        [0.99095602, 0.84629838, 0.55037965, 0.57244364, 0.63918969]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [69]:
# your code here

print (d)

d_flatten = d.flatten()

print (d_flatten)

f = []

print (f)
    
for value in d_flatten:
    if value > d_min and value < d_mean:
        f.append (25)
    elif value > d_mean and value < d_max:
        f.append (75)
    elif value == d_mean:
        f.append (50)
    elif value == d_min:
        f.append (0)
    elif value == d_max:
        f.append (100)


[[[1.51862546 1.27926604 1.62538208 1.4139255  1.1070457 ]
  [1.82024308 1.95908448 1.4414443  1.62354977 1.65628659]
  [1.509923   1.03366431 1.94790128 1.34204357 1.00836994]]

 [[1.80378364 1.21952224 1.72424512 1.75155051 1.05172862]
  [1.39655013 1.2698024  1.59949828 1.03592973 1.51790246]
  [1.99095602 1.84629838 1.55037965 1.57244364 1.63918969]]]
[1.51862546 1.27926604 1.62538208 1.4139255  1.1070457  1.82024308
 1.95908448 1.4414443  1.62354977 1.65628659 1.509923   1.03366431
 1.94790128 1.34204357 1.00836994 1.80378364 1.21952224 1.72424512
 1.75155051 1.05172862 1.39655013 1.2698024  1.59949828 1.03592973
 1.51790246 1.99095602 1.84629838 1.55037965 1.57244364 1.63918969]
[]


In [58]:
for value in d:
    print (value)

[[1.51862546 1.27926604 1.62538208 1.4139255  1.1070457 ]
 [1.82024308 1.95908448 1.4414443  1.62354977 1.65628659]
 [1.509923   1.03366431 1.94790128 1.34204357 1.00836994]]
[[1.80378364 1.21952224 1.72424512 1.75155051 1.05172862]
 [1.39655013 1.2698024  1.59949828 1.03592973 1.51790246]
 [1.99095602 1.84629838 1.55037965 1.57244364 1.63918969]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here