# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [6]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [9]:
# your code here
print(np.__version__)

1.16.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [52]:
# Method 1
a = np.random.random((2,3,5))

In [53]:
# Method 2
a2 = np.arange(30).reshape(2,3,5)

In [54]:
# Method 3
a3 = np.zeros((2,3,5), dtype = int)

#### 4. Print *a*.


In [57]:
# your code here
print(a)

[[[0.52168827 0.67594036 0.5209868  0.81848889 0.21532665]
  [0.43395933 0.66980312 0.12172872 0.4640177  0.03457299]
  [0.85530974 0.76568749 0.08259402 0.54563837 0.57123121]]

 [[0.97959883 0.34363992 0.43023665 0.70093699 0.57570161]
  [0.35474129 0.72300759 0.26752953 0.81057    0.75244485]
  [0.30302328 0.21121827 0.11754564 0.84688168 0.74654921]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [58]:
# your code here
b = np.ones((5,3,2), dtype = int)

#### 6. Print *b*.


In [59]:
# your code here
print(b)

[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [60]:
# your code here
a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [61]:
# your answer here

a + b
# No because they don't have the same shape

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,3,2) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [62]:
# your code here
c = np.transpose(b)
print(c)
c.shape

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [63]:
# your code/answer here
d = a + c
print(d)
d.shape
# Now it works because a and c have the same shape

[[[1.52168827 1.67594036 1.5209868  1.81848889 1.21532665]
  [1.43395933 1.66980312 1.12172872 1.4640177  1.03457299]
  [1.85530974 1.76568749 1.08259402 1.54563837 1.57123121]]

 [[1.97959883 1.34363992 1.43023665 1.70093699 1.57570161]
  [1.35474129 1.72300759 1.26752953 1.81057    1.75244485]
  [1.30302328 1.21121827 1.11754564 1.84688168 1.74654921]]]


(2, 3, 5)

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [64]:
# your code/answer here
print(a)
print('\n')
print(d)
# d is greater than a by 1 because it results from the sum of a with a ones' array

[[[0.52168827 0.67594036 0.5209868  0.81848889 0.21532665]
  [0.43395933 0.66980312 0.12172872 0.4640177  0.03457299]
  [0.85530974 0.76568749 0.08259402 0.54563837 0.57123121]]

 [[0.97959883 0.34363992 0.43023665 0.70093699 0.57570161]
  [0.35474129 0.72300759 0.26752953 0.81057    0.75244485]
  [0.30302328 0.21121827 0.11754564 0.84688168 0.74654921]]]


[[[1.52168827 1.67594036 1.5209868  1.81848889 1.21532665]
  [1.43395933 1.66980312 1.12172872 1.4640177  1.03457299]
  [1.85530974 1.76568749 1.08259402 1.54563837 1.57123121]]

 [[1.97959883 1.34363992 1.43023665 1.70093699 1.57570161]
  [1.35474129 1.72300759 1.26752953 1.81057    1.75244485]
  [1.30302328 1.21121827 1.11754564 1.84688168 1.74654921]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [66]:
# your code here
e = a * c
print(e)

[[[0.52168827 0.67594036 0.5209868  0.81848889 0.21532665]
  [0.43395933 0.66980312 0.12172872 0.4640177  0.03457299]
  [0.85530974 0.76568749 0.08259402 0.54563837 0.57123121]]

 [[0.97959883 0.34363992 0.43023665 0.70093699 0.57570161]
  [0.35474129 0.72300759 0.26752953 0.81057    0.75244485]
  [0.30302328 0.21121827 0.11754564 0.84688168 0.74654921]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [68]:
# your code/answer here
e == a
# Yes it does, because we're just multiplying a by 1

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [69]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print(d_max, d_min, d_mean)

1.979598833830273 1.0345729886280952 1.5153533000047898


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [94]:
# your code here
f = np.empty((2,3,5), dtype = float)
print(f)

[[[5.21688266e-01 6.75940356e-01 5.20986801e-01 8.18488891e-01
   2.15326645e-01]
  [4.33959330e-01 6.69803116e-01 1.21728723e-01 4.64017702e-01
   3.45729886e-02]
  [8.55309740e-01 7.65687492e-01 8.25940209e-02 5.45638371e-01
   5.71231211e-01]]

 [[7.77777000e+05 3.43639922e-01 4.30236655e-01 7.00936995e-01
   5.75701612e-01]
  [3.54741287e-01 7.23007593e-01 2.67529526e-01 8.10570002e-01
   7.52444851e-01]
  [3.03023275e-01 2.11218266e-01 1.17545638e-01 8.46881678e-01
   7.46549211e-01]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [100]:
# your code here
for ds, fs in np.nditer([d,f], op_flags=['readwrite']) :
    if ds[...] > d_min and ds[...] < d_mean :
        fs[...] = 25
    elif ds[...] > d_mean and ds[...] < d_max :
        fs[...] = 75
    elif ds[...] == d_mean :
        fs[...] = 50
    elif ds[...] == d_min :
        fs[...] = 0
    elif ds[...] == d_max :
        fs[...] = 100

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [102]:
# your code here
print(d)
print('\n')
print(f)

[[[1.52168827 1.67594036 1.5209868  1.81848889 1.21532665]
  [1.43395933 1.66980312 1.12172872 1.4640177  1.03457299]
  [1.85530974 1.76568749 1.08259402 1.54563837 1.57123121]]

 [[1.97959883 1.34363992 1.43023665 1.70093699 1.57570161]
  [1.35474129 1.72300759 1.26752953 1.81057    1.75244485]
  [1.30302328 1.21121827 1.11754564 1.84688168 1.74654921]]]


[[[ 75.  75.  75.  75.  25.]
  [ 25.  75.  25.  25.   0.]
  [ 75.  75.  25.  75.  75.]]

 [[100.  25.  25.  75.  75.]
  [ 25.  75.  25.  75.  75.]
  [ 25.  25.  25.  75.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here