# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.__version__)

1.21.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a = np.random.random((2,3,5))

In [4]:
# Method 2
a = np.random.randint(1,100,(2,3,5))

In [5]:
# Method 3
a = np.random.randn(2,3,5)

#### 4. Print *a*.


In [6]:
# your code here
print(a)

[[[-0.66951934  0.41372776 -0.38852716 -1.57018483  0.73821033]
  [-0.28178132  0.17272698 -0.94632481 -1.69352338  0.68167085]
  [-0.43371258  1.1814646   1.88227288  0.70069985  0.51647976]]

 [[-0.11691942  1.83451037 -0.27012864  0.14834262  0.60739768]
  [-1.45627626  0.31719646 -0.79614065  0.13576802  0.57783065]
  [-0.58057173 -1.26192515 -1.06066479  0.8640568  -2.21716172]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here
b = np.ones((5,2,3),dtype=int)

#### 6. Print *b*.


In [8]:
# your code here
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here
print(a.shape)
print(b.shape)
a.shape == b.shape

(2, 3, 5)
(5, 2, 3)


False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# they don't have the same shape
c = a + b
print(c)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here
c = b.transpose(1,2,0)
print(c)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# Now they have the same shape
d = a + c
print(d)

[[[ 0.33048066  1.41372776  0.61147284 -0.57018483  1.73821033]
  [ 0.71821868  1.17272698  0.05367519 -0.69352338  1.68167085]
  [ 0.56628742  2.1814646   2.88227288  1.70069985  1.51647976]]

 [[ 0.88308058  2.83451037  0.72987136  1.14834262  1.60739768]
  [-0.45627626  1.31719646  0.20385935  1.13576802  1.57783065]
  [ 0.41942827 -0.26192515 -0.06066479  1.8640568  -1.21716172]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# Now they have the same shape
print(a.shape)
print(d.shape)
a.shape == d.shape

(2, 3, 5)
(2, 3, 5)


True

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
# your code here
e = a * c
e

array([[[-0.66951934,  0.41372776, -0.38852716, -1.57018483,
          0.73821033],
        [-0.28178132,  0.17272698, -0.94632481, -1.69352338,
          0.68167085],
        [-0.43371258,  1.1814646 ,  1.88227288,  0.70069985,
          0.51647976]],

       [[-0.11691942,  1.83451037, -0.27012864,  0.14834262,
          0.60739768],
        [-1.45627626,  0.31719646, -0.79614065,  0.13576802,
          0.57783065],
        [-0.58057173, -1.26192515, -1.06066479,  0.8640568 ,
         -2.21716172]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
# your code/answer here
print(a.shape)
print(e.shape)
a.shape == e.shape

(2, 3, 5)
(2, 3, 5)


True

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
# your code here
d_max = d.max() #show the max value
d_min = d.min() #show the min value
d_mean = d.mean() #show the mean between every value

print(d_max)
print(d_min)
print(d_mean)

2.882272880624917
-1.2171617241021027
0.900966461358969


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [17]:
# your code here
f = np.empty((2,3,5))
f

array([[[0.66951934, 0.41372776, 0.38852716, 1.57018483, 0.73821033],
        [0.28178132, 0.17272698, 0.94632481, 1.69352338, 0.68167085],
        [0.43371258, 1.1814646 , 1.88227288, 0.70069985, 0.51647976]],

       [[0.11691942, 1.83451037, 0.27012864, 0.14834262, 0.60739768],
        [1.45627626, 0.31719646, 0.79614065, 0.13576802, 0.57783065],
        [0.58057173, 1.26192515, 1.06066479, 0.8640568 , 2.21716172]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [34]:
# your code here

f_sub = []

for subarry in d:
    for sub_subarry in subarry:
        for i in sub_subarry:
            if (i > d_min) and (i < d_mean):
                f_sub.append(25.)
            elif (i > d_mean) and (i < d_max):
                f_sub.append(75.)
            elif (i == d_mean):
                f_sub.append(50.)
            elif (i == d_min):
                f_sub.append(0.)
            else:
                f_sub.append(100.)

f = np.array(f_sub).reshape([2,3,5])
print(f)

[[[ 25.  75.  25.  25.  75.]
  [ 25.  75.  25.  25.  75.]
  [ 25.  75. 100.  75.  75.]]

 [[ 25.  75.  25.  75.  75.]
  [ 25.  75.  25.  75.  75.]
  [ 25.  25.  25.  75.   0.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [35]:
# your code here
print(d)
print(f)

[[[ 0.33048066  1.41372776  0.61147284 -0.57018483  1.73821033]
  [ 0.71821868  1.17272698  0.05367519 -0.69352338  1.68167085]
  [ 0.56628742  2.1814646   2.88227288  1.70069985  1.51647976]]

 [[ 0.88308058  2.83451037  0.72987136  1.14834262  1.60739768]
  [-0.45627626  1.31719646  0.20385935  1.13576802  1.57783065]
  [ 0.41942827 -0.26192515 -0.06066479  1.8640568  -1.21716172]]]
[[[ 25.  75.  25.  25.  75.]
  [ 25.  75.  25.  25.  75.]
  [ 25.  75. 100.  75.  75.]]

 [[ 25.  75.  25.  75.  75.]
  [ 25.  75.  25.  75.  75.]
  [ 25.  25.  25.  75.   0.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [37]:
# your code here

f_sub = []

for subarry in d:
    for sub_subarry in subarry:
        for i in sub_subarry:
            if (i > d_min) and (i < d_mean):
                f_sub.append("B")
            elif (i > d_mean) and (i < d_max):
                f_sub.append("D")
            elif (i == d_mean):
                f_sub.append("C")
            elif (i == d_min):
                f_sub.append("A")
            else:
                f_sub.append("E")

f = np.array(f_sub).reshape([2,3,5])
print(f)

[[['B' 'D' 'B' 'B' 'D']
  ['B' 'D' 'B' 'B' 'D']
  ['B' 'D' 'E' 'D' 'D']]

 [['B' 'D' 'B' 'D' 'D']
  ['B' 'D' 'B' 'D' 'D']
  ['B' 'B' 'B' 'D' 'A']]]
