# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [2]:
import numpy as np

#### 2. Print your NumPy version.

In [3]:
print(np.__version__)

1.23.3


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [4]:
a = np.random.rand(2, 3, 5)
print(a)

[[[0.10734251 0.6360245  0.42336788 0.78543055 0.33726852]
  [0.87775381 0.30222002 0.74441841 0.14602234 0.23671898]
  [0.45065839 0.77676625 0.78701782 0.41264536 0.45710292]]

 [[0.55423976 0.15663404 0.43256253 0.50740218 0.34630962]
  [0.73320968 0.17899687 0.05595088 0.37982629 0.5438045 ]
  [0.76321098 0.61181213 0.14385757 0.07156545 0.16344009]]]


In [5]:
a = np.random.randn(2, 3, 5)
print(a)

[[[ 0.81193249 -0.76152328 -1.37994571 -1.6152447  -1.21104705]
  [ 0.05273063  0.25450326 -1.39558069  0.39939479  0.29929782]
  [-0.19658269 -0.8504625  -0.50951972  1.10228021 -1.86670971]]

 [[-1.34089196  0.65591039  0.35656296  0.45447707  0.10149163]
  [-0.55464493 -0.13966224 -0.54746175 -0.77255666 -0.11729826]
  [ 0.19822701  0.35760714 -1.26557108  0.2190364   0.46443209]]]


In [6]:
a = np.random.randint(0, 10, size=(2, 3, 5))
print(a)

[[[0 7 4 4 3]
  [1 1 7 2 0]
  [7 1 9 5 0]]

 [[3 1 8 1 4]
  [2 3 6 6 4]
  [6 3 6 2 6]]]


#### 4. Print *a*.


In [7]:
###Already did above

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [8]:
b = np.ones((5, 2, 3))

#### 6. Print *b*.


In [9]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [10]:
#They don't we can prove this by priting their shape
print("Shape of a:", a.shape)
print("Shape of b:", b.shape)

Shape of a: (2, 3, 5)
Shape of b: (5, 2, 3)


In [11]:
b.shape

(5, 2, 3)

#### 8. Are you able to add *a* and *b*? Why or why not?


In [12]:
#No, they have different shapes so they cannot be added.

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [13]:
c = np.transpose(b, axes=(1, 2, 0))
c.shape

(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [14]:
d = a + c
#it works now because they have the same shape.

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [15]:
print(a)
print(d)

[[[0 7 4 4 3]
  [1 1 7 2 0]
  [7 1 9 5 0]]

 [[3 1 8 1 4]
  [2 3 6 6 4]
  [6 3 6 2 6]]]
[[[ 1.  8.  5.  5.  4.]
  [ 2.  2.  8.  3.  1.]
  [ 8.  2. 10.  6.  1.]]

 [[ 4.  2.  9.  2.  5.]
  [ 3.  4.  7.  7.  5.]
  [ 7.  4.  7.  3.  7.]]]


In [16]:
# They have the same shape but different values

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [17]:
e = a*c
print(e)

[[[0. 7. 4. 4. 3.]
  [1. 1. 7. 2. 0.]
  [7. 1. 9. 5. 0.]]

 [[3. 1. 8. 1. 4.]
  [2. 3. 6. 6. 4.]
  [6. 3. 6. 2. 6.]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [18]:
print(np.array_equal(a, e)) 
#e is equal to a multiplied by an array of all ones, which is just a itself.
#also because the thing above says so.


True


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [19]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(np.amax(d))
print(np.amin(d))
print(np.mean(d))

10.0
1.0
4.733333333333333


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [20]:
f = np.empty(d.shape)

print("Shape of f:", f.shape)

Shape of f: (2, 3, 5)


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [21]:
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i,j,k] == d_min:
                f[i,j,k] = 0
            elif d_min < d[i,j,k] < d_mean:
                f[i,j,k] = 25
            elif d[i,j,k] == d_mean:
                f[i,j,k] = 50
            elif d_mean < d[i,j,k] < d_max:
                f[i,j,k] = 75
            elif d[i,j,k] == d_max:
                f[i,j,k] = 100

print(f)

[[[  0.  75.  75.  75.  25.]
  [ 25.  25.  75.  25.   0.]
  [ 75.  25. 100.  75.   0.]]

 [[ 25.  25.  75.  25.  75.]
  [ 25.  25.  75.  75.  75.]
  [ 75.  25.  75.  25.  75.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [22]:
print(d)
print(f)

[[[ 1.  8.  5.  5.  4.]
  [ 2.  2.  8.  3.  1.]
  [ 8.  2. 10.  6.  1.]]

 [[ 4.  2.  9.  2.  5.]
  [ 3.  4.  7.  7.  5.]
  [ 7.  4.  7.  3.  7.]]]
[[[  0.  75.  75.  75.  25.]
  [ 25.  25.  75.  25.   0.]
  [ 75.  25. 100.  75.   0.]]

 [[ 25.  25.  75.  25.  75.]
  [ 25.  25.  75.  75.  75.]
  [ 75.  25.  75.  25.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [23]:
f = np.empty_like(d, dtype='U1')

for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i,j,k] > d_min and d[i,j,k] < d_mean:
                f[i,j,k] = "B"
            elif d[i,j,k] > d_mean and d[i,j,k] < d_max:
                f[i,j,k] = "D"
            elif d[i,j,k] == d_mean:
                f[i,j,k] = "C"
            elif d[i,j,k] == d_min:
                f[i,j,k] = "A"
            elif d[i,j,k] == d_max:
                f[i,j,k] = "E"

print("d:\n", d)
print("f:\n", f)

d:
 [[[ 1.  8.  5.  5.  4.]
  [ 2.  2.  8.  3.  1.]
  [ 8.  2. 10.  6.  1.]]

 [[ 4.  2.  9.  2.  5.]
  [ 3.  4.  7.  7.  5.]
  [ 7.  4.  7.  3.  7.]]]
f:
 [[['A' 'D' 'D' 'D' 'B']
  ['B' 'B' 'D' 'B' 'A']
  ['D' 'B' 'E' 'D' 'A']]

 [['B' 'B' 'D' 'B' 'D']
  ['B' 'B' 'D' 'D' 'D']
  ['D' 'B' 'D' 'B' 'D']]]
