# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np
import random 

#### 2. Print your NumPy version.

In [2]:
print(np.__version__)

1.18.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [14]:
a = np.random.random((2,3,5))

In [16]:
a2 = np.random.randint(0, 10000000, size=(2, 3, 5 ))
print(a2)

[[[1315533  517912 4413443 8916695 1225350]
  [ 395171 8138725 9807716 5710874 2488337]
  [3666662  347523 6335405 1909287 6527697]]

 [[ 454103 9923947 7527148 2561786 1197674]
  [4422611 9178131 4953972 1470761 6024751]
  [4108370 9433425 1229893 1327235 4485376]]]


In [17]:
a3 = np.random.randn(2, 3, 5)
print(a3)

[[[-1.07161177 -0.36338942 -0.35170235 -1.46561506  0.55998989]
  [ 0.36492113  0.64319064  3.34574281  1.67227563 -0.24853622]
  [ 0.31855337  2.0363768   0.28969068 -1.68979476 -0.40737137]]

 [[-0.5600795  -1.06273993  0.878362    0.12315162 -0.06940426]
  [ 1.2516356  -0.64388582  1.0207738   0.34523877  0.36700414]
  [-0.69355701 -0.87475979  0.12127414  0.02922781  0.87984188]]]


#### 4. Print *a*.


In [18]:
print(a)

[[[0.16820443 0.41482926 0.57329206 0.77088819 0.36971962]
  [0.02475115 0.52860231 0.49832197 0.11046244 0.07346543]
  [0.08619275 0.83681752 0.87124502 0.49701974 0.83330134]]

 [[0.74187621 0.45101876 0.3963555  0.28556621 0.8321747 ]
  [0.24814403 0.70474719 0.87363921 0.54178231 0.05128945]
  [0.74056736 0.87374011 0.33716249 0.29798745 0.76845938]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [19]:
b =np.ones((5,2,3),dtype = int)

#### 6. Print *b*.


In [20]:
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [21]:
#len(a) == len(b)
a.shape == b.shape


False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [22]:
a_and_b = np.add(a, b)

#Because shape of two arrays are not same, that is a.shape != b.shape

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [23]:
#a= np.random.rand(2,3,5)
#b =np.ones((5,2,3),dtype = int)

#c = b.transpose(2,3,5) - deu erro, decidi usar reshape

c = b.reshape(2,3,5)

c.shape



(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [25]:
d = np.add(a, c)
print(d)


[[[1.16820443 1.41482926 1.57329206 1.77088819 1.36971962]
  [1.02475115 1.52860231 1.49832197 1.11046244 1.07346543]
  [1.08619275 1.83681752 1.87124502 1.49701974 1.83330134]]

 [[1.74187621 1.45101876 1.3963555  1.28556621 1.8321747 ]
  [1.24814403 1.70474719 1.87363921 1.54178231 1.05128945]
  [1.74056736 1.87374011 1.33716249 1.29798745 1.76845938]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [26]:
print(d)
print(a)

#The values of array c were added to each value of the array a 

[[[1.16820443 1.41482926 1.57329206 1.77088819 1.36971962]
  [1.02475115 1.52860231 1.49832197 1.11046244 1.07346543]
  [1.08619275 1.83681752 1.87124502 1.49701974 1.83330134]]

 [[1.74187621 1.45101876 1.3963555  1.28556621 1.8321747 ]
  [1.24814403 1.70474719 1.87363921 1.54178231 1.05128945]
  [1.74056736 1.87374011 1.33716249 1.29798745 1.76845938]]]
[[[0.16820443 0.41482926 0.57329206 0.77088819 0.36971962]
  [0.02475115 0.52860231 0.49832197 0.11046244 0.07346543]
  [0.08619275 0.83681752 0.87124502 0.49701974 0.83330134]]

 [[0.74187621 0.45101876 0.3963555  0.28556621 0.8321747 ]
  [0.24814403 0.70474719 0.87363921 0.54178231 0.05128945]
  [0.74056736 0.87374011 0.33716249 0.29798745 0.76845938]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [27]:
e = np.multiply(a, c)  
e.shape
print(e)


[[[0.16820443 0.41482926 0.57329206 0.77088819 0.36971962]
  [0.02475115 0.52860231 0.49832197 0.11046244 0.07346543]
  [0.08619275 0.83681752 0.87124502 0.49701974 0.83330134]]

 [[0.74187621 0.45101876 0.3963555  0.28556621 0.8321747 ]
  [0.24814403 0.70474719 0.87363921 0.54178231 0.05128945]
  [0.74056736 0.87374011 0.33716249 0.29798745 0.76845938]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [28]:
e == a

#In question 12, I multiplied the values of array a by the values of array c (array of number ones)

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [29]:
d_max= d.max()
d_min= d.min()
d_mean= d.mean()


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [30]:
#First create an empty array f with the same shape (i.e. 2x3x5) as d using np.empty

f = np.empty([2, 3, 5])
print(f)

#It returned an empty 3D Numpy Array with 2 matrices of 3 rows and 3 columns.
#but all values in this 3D numpy array were not initialized.

[[[0.16820443 0.41482926 0.57329206 0.77088819 0.36971962]
  [0.02475115 0.52860231 0.49832197 0.11046244 0.07346543]
  [0.08619275 0.83681752 0.87124502 0.49701974 0.83330134]]

 [[0.74187621 0.45101876 0.3963555  0.28556621 0.8321747 ]
  [0.24814403 0.70474719 0.87363921 0.54178231 0.05128945]
  [0.74056736 0.87374011 0.33716249 0.29798745 0.76845938]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [40]:
#For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f

#If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f

#If a value equals to d_mean, assign 50 to the corresponding value in f

#Assign 0 to the corresponding value(s) in f for d_min in d.
#Assign 100 to the corresponding value(s) in f for d_max in d. 


#for lst_lst in d:
#    for lst in lst_lst:
#        for i in lst:
#            if d_min <i< d_mean:
#                f.append(25)
                #assing 25 to the corresponding value in f
#            elif d_mean <i<d_max:
#                f.append(75)
                #assign 75 to the corresponding value in f
#           elif i == d_mean:
#                f.append(50)
                #assign 50 to the corresponding value in f
#            elif i == d_min:
#                f.append(0)
                #Assign 0 to the corresponding value(s) in f for d_min in d.
#            elif i == d_max:
#                f.append(100)
                #Assign 100 to the corresponding value(s) in f for d_max in d    
        


        
#In the end, f should have only the following values: 0, 25, 50, 75, and 100.
        
f = [[[25 if d_min<item<d_mean else 75 if d_mean<item<d_max else 0 if item == d_min else 100 for item in lst] for lst in lst_lst] for lst_lst in d]
        
   
        


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [41]:
print(f)

[[[25, 25, 75, 75, 25], [0, 75, 75, 25, 25], [25, 75, 75, 75, 75]], [[75, 25, 25, 25, 75], [25, 75, 75, 75, 25], [75, 100, 25, 25, 75]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [43]:
g = [[['B' if d_min<item<d_mean else 'D' if d_mean<item<d_max else 'A' if item == d_min else 'E' for item in lst] for lst in lst_lst] for lst_lst in d]
print(g)      

[[['B', 'B', 'D', 'D', 'B'], ['A', 'D', 'D', 'B', 'B'], ['B', 'D', 'D', 'D', 'D']], [['D', 'B', 'B', 'B', 'D'], ['B', 'D', 'D', 'D', 'B'], ['D', 'E', 'B', 'B', 'D']]]
