# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [2]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [3]:
# your code here
print(np.__version__)

1.20.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [4]:
# Method 1
a = np.random.rand(2,3,5)

In [5]:
# Method 2
a = np.random.randn(2,3,5)

In [6]:
# Method 3
a = np.random.random((2,3,5))

#### 4. Print *a*.


In [7]:
# your code here
print(a)

[[[0.19951534 0.22339274 0.73983037 0.59438456 0.38096019]
  [0.79267286 0.9607869  0.02757434 0.65816375 0.67844742]
  [0.3960157  0.01307998 0.67713657 0.24728379 0.31174946]]

 [[0.82966929 0.36667211 0.66697739 0.298771   0.29625438]
  [0.12810208 0.82500157 0.68134726 0.90608655 0.06147748]
  [0.04902661 0.91743588 0.95707007 0.92024058 0.76944345]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [8]:
# your code here
b = np.ones((5,2,3), dtype= int)

#### 6. Print *b*.


In [9]:
# your code here
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [12]:
# your code here
print(a.size)
print(b.size)

30
30


#### 8. Are you able to add *a* and *b*? Why or why not?


In [13]:
# your answer here
a+b
#Because they have the same amount of data even they do have a diferent shapes.

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [14]:
# your code here
c = b.reshape(2,3,5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [16]:
# your code/answer here
d=a+c

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [17]:
# your code/answer here
print(a)
print(d)

#Both are diferent due to the previews operations.

[[[0.19951534 0.22339274 0.73983037 0.59438456 0.38096019]
  [0.79267286 0.9607869  0.02757434 0.65816375 0.67844742]
  [0.3960157  0.01307998 0.67713657 0.24728379 0.31174946]]

 [[0.82966929 0.36667211 0.66697739 0.298771   0.29625438]
  [0.12810208 0.82500157 0.68134726 0.90608655 0.06147748]
  [0.04902661 0.91743588 0.95707007 0.92024058 0.76944345]]]
[[[1.19951534 1.22339274 1.73983037 1.59438456 1.38096019]
  [1.79267286 1.9607869  1.02757434 1.65816375 1.67844742]
  [1.3960157  1.01307998 1.67713657 1.24728379 1.31174946]]

 [[1.82966929 1.36667211 1.66697739 1.298771   1.29625438]
  [1.12810208 1.82500157 1.68134726 1.90608655 1.06147748]
  [1.04902661 1.91743588 1.95707007 1.92024058 1.76944345]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [18]:
# your code here
e=a*c

#### 13. Does *e* equal to *a*? Why or why not?


In [20]:
# your code/answer here
print(a)
print(e)

[[[0.19951534 0.22339274 0.73983037 0.59438456 0.38096019]
  [0.79267286 0.9607869  0.02757434 0.65816375 0.67844742]
  [0.3960157  0.01307998 0.67713657 0.24728379 0.31174946]]

 [[0.82966929 0.36667211 0.66697739 0.298771   0.29625438]
  [0.12810208 0.82500157 0.68134726 0.90608655 0.06147748]
  [0.04902661 0.91743588 0.95707007 0.92024058 0.76944345]]]
[[[0.19951534 0.22339274 0.73983037 0.59438456 0.38096019]
  [0.79267286 0.9607869  0.02757434 0.65816375 0.67844742]
  [0.3960157  0.01307998 0.67713657 0.24728379 0.31174946]]

 [[0.82966929 0.36667211 0.66697739 0.298771   0.29625438]
  [0.12810208 0.82500157 0.68134726 0.90608655 0.06147748]
  [0.04902661 0.91743588 0.95707007 0.92024058 0.76944345]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [22]:
# your code here
d_max=d.max()
d_min=d.min()
d_mean=d.mean()
print(d_max)
print(d_min)
print(d_mean)

1.9607869013558128
1.0130799805496946
1.5191523218268523


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [24]:
# your code here
f=np.empty([2,3,5])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [34]:
# your code here
def populate(d, f):
    for element in d:
        if element > d_min:
            if element < d_mean:
                return 25 in f
        if element > d_mean:
            if element < d_max:
                return 75 in f
        if element == d_mean:
                return 50 in f
        if element == d_min:
                return 0 in f
        if element == d_max: 
                return 100 in f                              

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [35]:
# your code here
print(d)
print(f)

[[[1.19951534 1.22339274 1.73983037 1.59438456 1.38096019]
  [1.79267286 1.9607869  1.02757434 1.65816375 1.67844742]
  [1.3960157  1.01307998 1.67713657 1.24728379 1.31174946]]

 [[1.82966929 1.36667211 1.66697739 1.298771   1.29625438]
  [1.12810208 1.82500157 1.68134726 1.90608655 1.06147748]
  [1.04902661 1.91743588 1.95707007 1.92024058 1.76944345]]]
[[[0.19951534 0.22339274 0.73983037 0.59438456 0.38096019]
  [0.79267286 0.9607869  0.02757434 0.65816375 0.67844742]
  [0.3960157  0.01307998 0.67713657 0.24728379 0.31174946]]

 [[0.82966929 0.36667211 0.66697739 0.298771   0.29625438]
  [0.12810208 0.82500157 0.68134726 0.90608655 0.06147748]
  [0.04902661 0.91743588 0.95707007 0.92024058 0.76944345]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here