#Numpy 

Numpy mean -- Numerical Python 
It's a Library that brings the computinal power from other languages like C and Fortran to Python.
This library is used for working with arrays and matrices.

In python we already have a data struture that serve the purpose of arrays, but they are slow to process. 


#Array 

An arrangmenet of objects, pictures and numbers in rows and columns.

NumPy arrays can also be two-dimensional, three-dimensional, or up to n-dimensional.

# Matrix 

Is a rectangular array of numbers, symbols, or expressions, arranged in rows and columns (a.k.a table).
It's a specialised 2-dimensional array.

In [ ]:
import numpy as np

In [ ]:
mylist = [1,2,3,4,5]

mylist*2
# :o why do you do this to me?

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [ ]:
mylist = [1,2,3,4,5]
for i, item in enumerate(mylist):
    mylist[i] = mylist[i]*2

mylist

[2, 4, 6, 8, 10]

In [ ]:
# numpy to the rescue!!!! 

np.array(mylist)*2 # this is called a 1-dimensional array (a.k.a vector)

array([ 4,  8, 12, 16, 20])

In [ ]:
np.array(mylist)+2 

array([3, 4, 5, 6, 7])

In [ ]:
# Numpy provides an array object that is up to 50x faster than traditional Python Lists

#N.T.S --> Faster because they are stored at one continuous place in memory unlike lists

#N.T.S --> The array object in Numpy is called ndarray --> a lot of functions: toolkits

In [ ]:
# create an array with zeros with the type you like 
a = np.zeros(shape = (3,2), dtype = int) 

a

# or create an array with zeros with the same shape as a given array 
#np.zeros_like(a)



array([[0, 0],
       [0, 0],
       [0, 0]])

In [ ]:
# check the shape of the array 
a.shape

(3, 2)

In [ ]:
#numpy is very useful to create and process numeric arrays

nparray = np.array([1,2,3,4,5])

# when dealing with arrays we many times want to know their format (we might receive them from another part of the code)
nparray.shape # in this case since its 1D array the sape gives you the number of elements


d2_array = np.ones((3,3),dtype = int) ## creates an array with ones 

# for a 2D array the shape would be (n,m) - n is the number of rows and m the number of columns 
d2_array.shape

(3, 3)

In [ ]:
np.random.random(size = (2,5)) # random floats from 0.0 to 1.0 with a certain shape/size

np.arange( start = 6, stop = 100) # evenly spaced ndarray  

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
       40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56,
       57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73,
       74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
       91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
#equivalent to range function but in a numpy context
np.arange(8)

#you can also chose the data type
np.arange(8, dtype= float)



array([0., 1., 2., 3., 4., 5., 6., 7.])

In [ ]:
# linspace is also very common to be used
a = np.linspace(start = 5.0, stop = 5000,num =10 )
a


array([   5.,  560., 1115., 1670., 2225., 2780., 3335., 3890., 4445.,
       5000.])

In [ ]:

np.random.random(size = (2,3,4))

array([[[0.2189664 , 0.78224965, 0.65253714, 0.8821892 ],
        [0.19757439, 0.98200676, 0.52480656, 0.63427767],
        [0.40919716, 0.41158576, 0.28960374, 0.7967518 ]],

       [[0.05750372, 0.13749222, 0.67832469, 0.8189827 ],
        [0.80722847, 0.30962953, 0.1835715 , 0.99524469],
        [0.16961847, 0.20821096, 0.01859953, 0.42847014]]])

In [ ]:
# arrays can also have multiple types in it like lists
x = np.array([[1],2,[3,3.5],4,5], dtype = object)
x

In [ ]:

#we have seen how to create numpy arrays. How can we index them?

# --> 1Dimension array
a = np.array([0,2])

print(a[1])

# --> 2Dimension array

x = np.array([[11, 22], [33, 44], [55, 66]])

#this works -> to slice a numpy array you have to give it another array object
x[0][1] # x[0,1]


2


22

In [ ]:
#slicing and index arrays
import numpy as np
x = np.arange(20)*2
print(x)

print(x[2:6])

print(x[np.array([2,5,6])]) ## the indexes you want

# you can also index on a consition

condition = x < 5

#print(condition) ## boolean mask
x[condition]

#relate to importance of pandas and filtering

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]
[ 4  6  8 10]
[ 4 10 12]
[ True  True  True False False False False False False False False False
 False False False False False False False False]


array([0, 2, 4])

In [ ]:
# transposing -> useful for generate manipulation

array = np.random.random((2,5))
array

array([[0.09515132, 0.24262666, 0.04634506, 0.73566319, 0.08228239],
       [0.41595084, 0.88724541, 0.1985826 , 0.1812518 , 0.61770969]])

In [ ]:
array.transpose()

array([[0.09515132, 0.41595084],
       [0.24262666, 0.88724541],
       [0.04634506, 0.1985826 ],
       [0.73566319, 0.1812518 ],
       [0.08228239, 0.61770969]])

In [ ]:
# view on 3d arrays
a_3d_array = np.array([
                       [[1, 2 , 3], [4, 5, 6]], 
                       [[7, 8, 9], [10, 11, 12]]
                       
                       ])
print(a_3d_array)

# reshape method to the shape you want 
print(a_3d_array.shape)

a_3d_array.reshape(4,3) # the number of elements must be the same 2x2x3 == 4x3


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
# Challenge: create two arrays:

# array1 with 2 rows and 6 columns with only ones
# array2 with 3 rows and 4 columns with only twos


array1 = np.ones(shape=(2,6))
array1 

array2 = np.zeros(shape=(3,4)) + 2
array2

# Can you sum the two arrays?
# Note: You can't sum arrays with diffetent shapes (check the error)

# try: reshape them 

array2 = array2.reshape(2,6)

array1 + array2

array([[3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3.]])

In [ ]:
# you can perform several mathematical operations on numpy arrays

array = np.random.random( size=(1000,100)) 

print(array)


[[0.56981911 0.18179573 0.58253608 ... 0.3741549  0.20229679 0.30511834]
 [0.06825926 0.27736389 0.757743   ... 0.4989395  0.93541867 0.44599527]
 [0.96037037 0.76971304 0.96497341 ... 0.71791504 0.64226771 0.36944984]
 ...
 [0.49970152 0.74438246 0.07770334 ... 0.00543891 0.40022693 0.71569719]
 [0.9921243  0.42367185 0.38993735 ... 0.76994329 0.66821033 0.27653431]
 [0.86721327 0.32043169 0.28408495 ... 0.71308236 0.21258154 0.69874627]]


In [ ]:
# check the max value in the array
print(array.max())
# get the mean of the full array 
print(array.mean())



0.9999876586321832
0.4994595459974218


In [ ]:
#what if I want to get the mean of each inner slice? -> use the axis keyword argument
x = np.array([[1,2,3],[4,5,6],[6,7,8],[1,1,1]])
x.mean()
x.mean(axis = 0) #  running vertically downwards across rows (axis 0) # calculate the mean by rows (row elements are added, divided by the number of times)
x.mean(axis = 1) #  running horizontally across columns (axis 1) #  calculate the mean by columns (column elements are added, divided by the number of times )

#NOTE: for example, then dimension n is collapsed and deleted, with each value in the new matrix equal to the sum of the corresponding collapsed values

array([2., 5., 7., 1.])

In [ ]:
# other cool methods for numpy arrays 
print(x)
print('\n')
print(x.shape)
print('\n')
print(np.power(x,4)) # raises each element of the array to the power you liked 
print('\n')
print(np.sum(x, axis = 1))
print('\n')
np.multiply(x,x) # multiply on array with another 

[[1 2 3]
 [4 5 6]
 [6 7 8]
 [1 1 1]]


(4, 3)


[[   1   16   81]
 [ 256  625 1296]
 [1296 2401 4096]
 [   1    1    1]]


[ 6 15 21  3]




array([[ 1,  4,  9],
       [16, 25, 36],
       [36, 49, 64],
       [ 1,  1,  1]])

# Performance 

In [ ]:
# performance from here downards
array.mean(axis = 1)

import time
t1 = time.time()
new_array = array**2
t2 = time.time()

print(t2-t1)

t1 = time.time()
new_array = np.square(array)
t2 = time.time()

print(t2-t1)



0.0001251697540283203
0.0001468658447265625


In [ ]:
#you can perform mathematical operations on the created arrays
import time
t1 = time.time()
np.power(x,3)
t2 = time.time()
print(t2-t1)
t1 = time.time()
x**3
t2 = time.time()
print(t2-t1)


0.0001201629638671875
0.00011205673217773438


In [ ]:
# lets test performance
import time

mynumbers = [i for i in range(0,100000)]

t1 = time.time()
mylist = []
for i in mynumbers:
  mylist.append(i**2)
t2 = time.time()
print("with append ", t2-t1)

mynumbers = [i for i in range(0,100000)]
t1 = time.time()
[i**2 for i in mynumbers]
t2 = time.time()
print("with list comprehension ", t2-t1)

mynumbers = np.array(mynumbers)
t1 = time.time()
np.square(mynumbers)
t2 = time.time()

print("with numpy functions ", t2-t1)

#who is more efficient

with append  0.041004180908203125
with list comprehension  0.028128385543823242
with numpy functions  0.00026798248291015625


In [ ]:
import numpy as np
def myfunc(a, b):
  "Return a-b if a>b, otherwise return a+b"
  if a > b:
    return a - b
  else:
    return a + b

numpyfunc = np.vectorize(myfunc) # takes a pyfunction you can design and apply the logic to an array element by element
print(numpyfunc)
numpyfunc([[1, 2, 3, 4],[3, 4, 5, 6]], 2)

array([[3, 4, 1, 2],
       [1, 2, 3, 4]])

In [ ]:
import numpy as np

array = np.random.random((5,10))
array

array([[0.06742512, 0.90994349, 0.05580007, 0.94939372, 0.13253851,
        0.47167494, 0.73270684, 0.96180373, 0.75248829, 0.58027573],
       [0.36707052, 0.16226348, 0.28529733, 0.223283  , 0.81463814,
        0.57191166, 0.37072709, 0.64708612, 0.92680018, 0.70084872],
       [0.78354232, 0.29926402, 0.58218595, 0.02121981, 0.06250774,
        0.14976513, 0.37518997, 0.80093182, 0.61559428, 0.80843562],
       [0.78184465, 0.1649198 , 0.47671237, 0.25433636, 0.5527487 ,
        0.59648818, 0.82652195, 0.74581998, 0.24972635, 0.54520782],
       [0.04718512, 0.25737361, 0.80981356, 0.55156381, 0.85159128,
        0.58295847, 0.80067638, 0.29538921, 0.79392873, 0.08215849]])

In [ ]:
#numpy vectorize
# WARNING: very advanced topic -> high performance computing
def newfunc(x):
  #here write complex domain specific logic
  return x**2+2*x-5

npfunc = np.vectorize(newfunc)

print(npfunc)
new_array = npfunc(array)
new_array

array([[-2.94928478, -3.43512226, -2.20762274, -3.89555923, -3.65425158,
        -3.12520824, -2.45541051, -3.31735824, -2.2938584 , -3.13041433],
       [-3.6070883 , -4.96382119, -2.00614465, -3.12468652, -3.46723443,
        -4.76391769, -4.0945315 , -2.33966927, -4.72806661, -3.12187142],
       [-4.78771793, -3.25893506, -2.0760113 , -4.51571797, -3.19508688,
        -4.2233826 , -4.74103065, -2.51047528, -2.01255925, -3.54348939],
       [-4.07150774, -4.82044348, -4.37425755, -3.96569273, -3.60652817,
        -4.94806141, -4.89560425, -3.59839416, -4.93056859, -4.23793966],
       [-2.65664147, -3.61450511, -4.84109417, -3.15269886, -3.53508105,
        -3.81148317, -3.11346953, -3.1208351 , -3.12734862, -2.87200573]])

In [ ]:
# let's check with one element from our array: 

0.03485456 **2 + 2*0.03485456 - 5

-4.929076039647207