# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np 

#### 2. Print your NumPy version.

In [2]:
np

<module 'numpy' from 'C:\\Users\\Rui Almeida\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
a=np.random.random((2,3,5))
a

array([[[0.22156937, 0.43462583, 0.24914124, 0.08698046, 0.06156538],
        [0.68034476, 0.4933848 , 0.24096882, 0.80620748, 0.82600996],
        [0.85218772, 0.41759222, 0.49649977, 0.09545803, 0.48634855]],

       [[0.01700855, 0.77627066, 0.42821296, 0.74877192, 0.78611554],
        [0.57074862, 0.47775986, 0.22200575, 0.36344696, 0.99178221],
        [0.23676773, 0.38375606, 0.04194764, 0.7355313 , 0.86998003]]])

In [4]:
a=np.random.rand(2,3,5)
a

array([[[0.3313672 , 0.62611579, 0.32280697, 0.52321299, 0.41556787],
        [0.19707058, 0.50413338, 0.20228481, 0.64963535, 0.37675518],
        [0.59690704, 0.18709672, 0.33963532, 0.37872993, 0.17914327]],

       [[0.81478057, 0.1979894 , 0.96809389, 0.73492382, 0.683104  ],
        [0.43677256, 0.20306222, 0.11162651, 0.29349063, 0.63893862],
        [0.7132374 , 0.62283736, 0.46866454, 0.76829723, 0.19926745]]])

In [7]:
x = np.random.randint(100, size=(2,3, 5))
x

array([[[65, 36, 64, 34, 71],
        [36, 70, 36, 91, 79],
        [13, 50, 18, 70, 17]],

       [[58, 52, 55, 53, 68],
        [86, 71, 11, 38, 21],
        [67, 17, 74,  9, 95]]])

#### 4. Print *a*.


In [ ]:
# your code here

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [9]:
b=np.ones((5,2,3))


          

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 6. Print *b*.


In [10]:
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [11]:
a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [14]:
b.reshape((2,3,5))
b
print(np.add(a, b))

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [31]:
c=b.reshape(2,3,5)



#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [41]:
d=(np.add(a, c))
d

array([[[1.3313672 , 1.62611579, 1.32280697, 1.52321299, 1.41556787],
        [1.19707058, 1.50413338, 1.20228481, 1.64963535, 1.37675518],
        [1.59690704, 1.18709672, 1.33963532, 1.37872993, 1.17914327]],

       [[1.81478057, 1.1979894 , 1.96809389, 1.73492382, 1.683104  ],
        [1.43677256, 1.20306222, 1.11162651, 1.29349063, 1.63893862],
        [1.7132374 , 1.62283736, 1.46866454, 1.76829723, 1.19926745]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [33]:
print(a)

[[[0.3313672  0.62611579 0.32280697 0.52321299 0.41556787]
  [0.19707058 0.50413338 0.20228481 0.64963535 0.37675518]
  [0.59690704 0.18709672 0.33963532 0.37872993 0.17914327]]

 [[0.81478057 0.1979894  0.96809389 0.73492382 0.683104  ]
  [0.43677256 0.20306222 0.11162651 0.29349063 0.63893862]
  [0.7132374  0.62283736 0.46866454 0.76829723 0.19926745]]]


In [34]:
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [35]:
e=np.multiply(a, c)
e

array([[[0.3313672 , 0.62611579, 0.32280697, 0.52321299, 0.41556787],
        [0.19707058, 0.50413338, 0.20228481, 0.64963535, 0.37675518],
        [0.59690704, 0.18709672, 0.33963532, 0.37872993, 0.17914327]],

       [[0.81478057, 0.1979894 , 0.96809389, 0.73492382, 0.683104  ],
        [0.43677256, 0.20306222, 0.11162651, 0.29349063, 0.63893862],
        [0.7132374 , 0.62283736, 0.46866454, 0.76829723, 0.19926745]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [37]:
e == a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [44]:
d_max=d.max()
d_max

1.9680938939947268

In [45]:
d_min=d.min()
d_min

1.1116265083249601

In [46]:
d_mean=d.mean()
d_mean

1.4561849540560026

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [56]:
f=np.empty
f

<function numpy.empty>

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here