# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [11]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [12]:
# your code here
print("The NumPy version is: "+np.version.version)

The NumPy version is: 1.18.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [13]:
# Method 1
a=np.random.random_sample((2,3,5))
print(a)

[[[0.54734993 0.29369677 0.14023452 0.23249579 0.34303334]
  [0.65615109 0.6669761  0.31152552 0.00198412 0.10690656]
  [0.08245124 0.07978473 0.80780679 0.14797298 0.37063559]]

 [[0.14841681 0.4536247  0.18526871 0.12753444 0.96993169]
  [0.30897314 0.34559204 0.05921431 0.47514923 0.23135918]
  [0.10817748 0.54945883 0.39814261 0.17268462 0.93507769]]]


In [4]:
# Method 2

In [5]:
# Method 3

#### 4. Print *a*.


In [14]:
# your code here
print(a)

[[[0.54734993 0.29369677 0.14023452 0.23249579 0.34303334]
  [0.65615109 0.6669761  0.31152552 0.00198412 0.10690656]
  [0.08245124 0.07978473 0.80780679 0.14797298 0.37063559]]

 [[0.14841681 0.4536247  0.18526871 0.12753444 0.96993169]
  [0.30897314 0.34559204 0.05921431 0.47514923 0.23135918]
  [0.10817748 0.54945883 0.39814261 0.17268462 0.93507769]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [15]:
# your code here
b=x = np.zeros((5,2,3))+1

#another way to do:
b=np.random.randint(1,2,(5,2,3))

#### 6. Print *b*.


In [16]:
# your code here
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [17]:
# your code here
answer=a==b
answer=answer.all()
print('''
First question answer: '''+str(answer)+'''
Second question answer: I think I have proven above.''')

C:\Users\joaop\anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  


AttributeError: 'bool' object has no attribute 'all'

#### 8. Are you able to add *a* and *b*? Why or why not?


In [18]:
# your answer here
answer="No, because although they are both 3 dimensional, they don't have the 𝕤𝕒𝕞𝕖 𝕣𝕠𝕨𝕤 𝕒𝕟𝕕 𝕔𝕠𝕝𝕦𝕞𝕟𝕤(?)"
print("João's answer: "+answer)

João's answer: No, because although they are both 3 dimensional, they don't have the 𝕤𝕒𝕞𝕖 𝕣𝕠𝕨𝕤 𝕒𝕟𝕕 𝕔𝕠𝕝𝕦𝕞𝕟𝕤(?)


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [19]:
# your code here
#c=np.transpose(b)  --> this way won't work.
c=b.reshape(2,3,5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [20]:
# your code/answer here
d=a+c
print(d)
#now it works because they have the same rows , colums 

[[[1.54734993 1.29369677 1.14023452 1.23249579 1.34303334]
  [1.65615109 1.6669761  1.31152552 1.00198412 1.10690656]
  [1.08245124 1.07978473 1.80780679 1.14797298 1.37063559]]

 [[1.14841681 1.4536247  1.18526871 1.12753444 1.96993169]
  [1.30897314 1.34559204 1.05921431 1.47514923 1.23135918]
  [1.10817748 1.54945883 1.39814261 1.17268462 1.93507769]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [ ]:
# your code/answer here
print(a)
print(d)

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [21]:
# your code here
e=a*c
print(e)

[[[0.54734993 0.29369677 0.14023452 0.23249579 0.34303334]
  [0.65615109 0.6669761  0.31152552 0.00198412 0.10690656]
  [0.08245124 0.07978473 0.80780679 0.14797298 0.37063559]]

 [[0.14841681 0.4536247  0.18526871 0.12753444 0.96993169]
  [0.30897314 0.34559204 0.05921431 0.47514923 0.23135918]
  [0.10817748 0.54945883 0.39814261 0.17268462 0.93507769]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [22]:
# your code/answer here

boolean_e=e.all()
boolean_a=a.all()
boolean=boolean_e==boolean_a

if boolean==True:
    print("The answer is true.")
elif boolean==False:
    print("The answer is false.")

The answer is true.


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [23]:
# your code here
d_max=d.max()
d_min=d.min()
d_mean=d.mean()

print('''
d_max='''+str(d_max)+'''
d_min='''+str(d_min)+'''
d_mean='''+str(d_mean))


d_max=1.9699316905542397
d_min=1.0019841155691511
d_mean=1.3419203514775178


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [24]:
# your code here
order="C"

f= np.empty((5,2,3),float,order)


##or this way:
#f= np.zeros((5,2,3))

print(f)

[[[0.54734993 0.29369677 0.14023452]
  [0.23249579 0.34303334 0.65615109]]

 [[0.6669761  0.31152552 0.00198412]
  [0.10690656 0.08245124 0.07978473]]

 [[0.80780679 0.14797298 0.37063559]
  [0.14841681 0.4536247  0.18526871]]

 [[0.12753444 0.96993169 0.30897314]
  [0.34559204 0.05921431 0.47514923]]

 [[0.23135918 0.10817748 0.54945883]
  [0.39814261 0.17268462 0.93507769]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [25]:
# your code here
for array  in d:
    for value in array:
        if (value.all()>d_min) and (value.all()<d_mean):
            f.append(d,25)
        elif (value.all()<d_max) and (value.all()>d_mean):
            f.append(d,75)
        elif (value.all()==d_mean):
            f.append(d,50)
        elif (value.all()==d_max):
            f.append(d,100)
        elif (value.all()==d_min):
            f.append(d,0)
        else:
            f.append(d,0)
print(f)

IndexError: index 3 is out of bounds for axis 2 with size 3

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here
print(d)
print(f)

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here