# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [3]:
# your code here
print(np.version.version)

1.20.3


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [5]:
# Method 1
a = np.random.random((2,3,5))
print(a)

[[[0.3063486  0.87026361 0.52654495 0.53400654 0.56919712]
  [0.14143839 0.1621637  0.93598128 0.0164399  0.34998153]
  [0.48420685 0.72271761 0.46376098 0.73944081 0.73776127]]

 [[0.82550815 0.98826098 0.82713233 0.20804607 0.52875094]
  [0.54189305 0.4816799  0.07933634 0.34069168 0.7585647 ]
  [0.98259937 0.75135075 0.66724922 0.76401908 0.21308721]]]


In [6]:
# Method 2
a = np.random.randn(2,3,5)
a

array([[[ 0.32672014,  0.6548905 , -1.64836786, -1.83265612,
          0.65731781],
        [ 0.69830988,  0.9772746 , -1.30712195,  1.40655404,
          0.22595882],
        [-1.24646874, -0.9849018 , -0.28709543,  1.8748913 ,
          1.46255452]],

       [[ 0.81717945,  0.30361505,  0.01175545, -0.16546636,
         -0.80900691],
        [-1.5457917 ,  0.81353337,  0.96923685, -0.1162634 ,
         -0.59961693],
        [-1.49161679,  0.52999131, -0.27321718,  0.05728721,
         -0.9816236 ]]])

In [14]:
my_array = np.random.randint(0,100,(2,3,5))
my_array

array([[[76, 34, 70, 55, 17],
        [40, 82, 18, 95, 40],
        [ 6, 39, 82,  2, 49]],

       [[96, 38, 74, 29, 54],
        [57, 80, 26, 75, 99],
        [54, 15, 76, 40, 15]]])

#### 4. Print *a*.


In [16]:
a = np.random.random((2,3,5))
print(a)

[[[0.78458999 0.52829964 0.67003399 0.72338458 0.41712282]
  [0.42717828 0.41383017 0.89133475 0.55882034 0.5792579 ]
  [0.11404609 0.98831553 0.32930294 0.82682694 0.37604514]]

 [[0.03211701 0.87113643 0.1122644  0.22608293 0.57865247]
  [0.72810245 0.1318956  0.81033579 0.4105328  0.14292814]
  [0.21191872 0.89066428 0.82988435 0.55789243 0.60374628]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [17]:
# your code here
b = np.full((5,2,3),1)

#### 6. Print *b*.


In [18]:
# your code here
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [19]:
# your code here
np.shape(a) == np.shape(b)

False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [20]:
# your answer here
a+b
#we cannot add the arrays because they have different shapes

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [25]:
# your code here
c = b.reshape(2,3,5)
print(np.shape(c))
print(c)

(2, 3, 5)
[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [29]:
# your code/answer here
d = a+c
print(d)

[[[1.78458999 1.52829964 1.67003399 1.72338458 1.41712282]
  [1.42717828 1.41383017 1.89133475 1.55882034 1.5792579 ]
  [1.11404609 1.98831553 1.32930294 1.82682694 1.37604514]]

 [[1.03211701 1.87113643 1.1122644  1.22608293 1.57865247]
  [1.72810245 1.1318956  1.81033579 1.4105328  1.14292814]
  [1.21191872 1.89066428 1.82988435 1.55789243 1.60374628]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [32]:
# your code/answer here
print(a)


print(d)

#you add one to all the elements in a (because matrix c is composed of 1s)

[[[0.78458999 0.52829964 0.67003399 0.72338458 0.41712282]
  [0.42717828 0.41383017 0.89133475 0.55882034 0.5792579 ]
  [0.11404609 0.98831553 0.32930294 0.82682694 0.37604514]]

 [[0.03211701 0.87113643 0.1122644  0.22608293 0.57865247]
  [0.72810245 0.1318956  0.81033579 0.4105328  0.14292814]
  [0.21191872 0.89066428 0.82988435 0.55789243 0.60374628]]]
[[[1.78458999 1.52829964 1.67003399 1.72338458 1.41712282]
  [1.42717828 1.41383017 1.89133475 1.55882034 1.5792579 ]
  [1.11404609 1.98831553 1.32930294 1.82682694 1.37604514]]

 [[1.03211701 1.87113643 1.1122644  1.22608293 1.57865247]
  [1.72810245 1.1318956  1.81033579 1.4105328  1.14292814]
  [1.21191872 1.89066428 1.82988435 1.55789243 1.60374628]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [33]:
# your code here
e = a*c
print(e)

[[[0.78458999 0.52829964 0.67003399 0.72338458 0.41712282]
  [0.42717828 0.41383017 0.89133475 0.55882034 0.5792579 ]
  [0.11404609 0.98831553 0.32930294 0.82682694 0.37604514]]

 [[0.03211701 0.87113643 0.1122644  0.22608293 0.57865247]
  [0.72810245 0.1318956  0.81033579 0.4105328  0.14292814]
  [0.21191872 0.89066428 0.82988435 0.55789243 0.60374628]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [34]:
# your code/answer here
a == e

#yes because c is composed of only 1s so by multiplying by 1 you are left with a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [38]:
# your code here
d_max = d.max()
print(d_max)


d_min = d.min()
print(d_min)

d_mean = d.mean()
print(d_mean)

1.9883155304880857
1.0321170083564422
1.5255514396492884


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [41]:
f = np.empty((2,3,5))
f


array([[[0.78458999, 0.52829964, 0.67003399, 0.72338458, 0.41712282],
        [0.42717828, 0.41383017, 0.89133475, 0.55882034, 0.5792579 ],
        [0.11404609, 0.98831553, 0.32930294, 0.82682694, 0.37604514]],

       [[0.03211701, 0.87113643, 0.1122644 , 0.22608293, 0.57865247],
        [0.72810245, 0.1318956 , 0.81033579, 0.4105328 , 0.14292814],
        [0.21191872, 0.89066428, 0.82988435, 0.55789243, 0.60374628]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [44]:
# your code here
f = 25 * (d > d_min) * (d < d_mean) + 75 * (d < d_max) * (d > d_mean) + 0 * (d == d_min) + 100 * (d == d_max)
f

array([[[ 75,  75,  75,  75,  25],
        [ 25,  25,  75,  75,  75],
        [ 25, 100,  25,  75,  25]],

       [[  0,  75,  25,  25,  75],
        [ 75,  25,  75,  25,  25],
        [ 25,  75,  75,  75,  75]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [45]:
# your code here
print(d)
print(f)
#yes 

[[[1.78458999 1.52829964 1.67003399 1.72338458 1.41712282]
  [1.42717828 1.41383017 1.89133475 1.55882034 1.5792579 ]
  [1.11404609 1.98831553 1.32930294 1.82682694 1.37604514]]

 [[1.03211701 1.87113643 1.1122644  1.22608293 1.57865247]
  [1.72810245 1.1318956  1.81033579 1.4105328  1.14292814]
  [1.21191872 1.89066428 1.82988435 1.55789243 1.60374628]]]
[[[ 75  75  75  75  25]
  [ 25  25  75  75  75]
  [ 25 100  25  75  25]]

 [[  0  75  25  25  75]
  [ 75  25  75  25  25]
  [ 25  75  75  75  75]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [49]:
# your code here
f1 = np.empty((2,3,5))
f1

f1 = [[['B' if d_min<item<d_mean else 'D' if d_mean<item< d_max else 'A' if item == d_min else 'E' for item in in_list] for in_list in out_list] for out_list in d]

print(f1)

[[['D', 'D', 'D', 'D', 'B'], ['B', 'B', 'D', 'D', 'D'], ['B', 'E', 'B', 'D', 'B']], [['A', 'D', 'B', 'B', 'D'], ['D', 'B', 'D', 'B', 'B'], ['B', 'D', 'D', 'D', 'D']]]
