NameError: name 'np' is not defined

In [2]:
import numpy as np

In [3]:
a = np.random.random((10,4))
print(a)

[[0.03158309 0.97231657 0.07789809 0.98416899]
 [0.91892017 0.12032184 0.91195972 0.1521784 ]
 [0.87366593 0.44431329 0.76913041 0.93414572]
 [0.41270659 0.2706027  0.93077905 0.03666224]
 [0.08531587 0.14963277 0.4526527  0.54974867]
 [0.88632443 0.53158691 0.26505149 0.20627569]
 [0.55134593 0.43846855 0.93972581 0.09199257]
 [0.41152169 0.24164092 0.15054638 0.22345101]
 [0.39710925 0.51218372 0.42668584 0.60975368]
 [0.87964996 0.8739056  0.78106218 0.29439998]]


In [4]:
print(a.shape)

(10, 4)


In [5]:
print(a.size)

40


In [6]:
b = np.random.random((5,2,3))
print(b)

[[[0.66669375 0.64283451 0.90501613]
  [0.40113214 0.44989432 0.23127182]]

 [[0.07705433 0.72226063 0.98858992]
  [0.37758878 0.1661723  0.45130655]]

 [[0.8090212  0.26244484 0.41302513]
  [0.9525808  0.56206728 0.46269848]]

 [[0.93776331 0.59932615 0.72072998]
  [0.83520657 0.4335352  0.63299563]]

 [[0.75177289 0.44700385 0.88202118]
  [0.16306935 0.55813704 0.84704439]]]


In [7]:
c = np.random.random((2,3,4,5))
print(c)

[[[[0.90648835 0.72365203 0.11837308 0.44697729 0.12737596]
   [0.40345271 0.22301801 0.16726019 0.23523474 0.37799553]
   [0.77736024 0.0712059  0.95119957 0.72344322 0.10905328]
   [0.29997586 0.71254522 0.13487974 0.91137657 0.21926477]]

  [[0.12604117 0.63281293 0.59267381 0.44392166 0.77390539]
   [0.19062756 0.86691159 0.45767455 0.51244108 0.4291931 ]
   [0.57361026 0.9208547  0.56299405 0.19517703 0.88505649]
   [0.95409282 0.70905026 0.3299379  0.17029438 0.64789353]]

  [[0.13998353 0.14587978 0.67827032 0.94111684 0.27122638]
   [0.14160301 0.11739064 0.57649993 0.53246525 0.64253568]
   [0.4642338  0.92769711 0.80860666 0.9316907  0.41144293]
   [0.26260731 0.74321684 0.91769537 0.97192927 0.35205373]]]


 [[[0.38711567 0.18606013 0.32384569 0.03750836 0.80808189]
   [0.97713376 0.06409279 0.62180544 0.1668592  0.51149813]
   [0.19807507 0.73250943 0.82935232 0.69545849 0.02560267]
   [0.21499008 0.50678036 0.82927517 0.23492798 0.10777544]]

  [[0.60316028 0.05831469 0.28

In [8]:
print(a[0])

[0.03158309 0.97231657 0.07789809 0.98416899]


In [9]:
print(a[:,0])

[0.03158309 0.91892017 0.87366593 0.41270659 0.08531587 0.88632443
 0.55134593 0.41152169 0.39710925 0.87964996]


In [10]:
#fifth row and third column of a matrix
print(a[4,2])

0.4526527028907581


In [11]:
print(a[0])

[0.03158309 0.97231657 0.07789809 0.98416899]


In [12]:
lst_lst = [[1,2,3], [4,5,6], [7,8,9]]
d = np.array(lst_lst)
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
print(np.sum(a))

19.79138439719759


In [14]:
print(np.sum(a, axis=0))

[5.44814292 4.55497286 5.70549166 4.08277695]


In [15]:
print(np.mean(a, axis=0))

[0.54481429 0.45549729 0.57054917 0.40827769]
